import {
  code,
  example,
  figure,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const quEstCeQueLaCybersecurite: NewLesson = {
  key: "l-c1-1",
  title: "Qu’est-ce que la cybersécurité ?",
  summary: "Définis la cybersécurité avec ses mots-clés, comprends pourquoi elle concerne aussi bien un téléphone qu’une petite structure, et apprends à raisonner en actifs, menaces, vulnérabilités et risques.",
  minutes: 20,
  xp: 40,
  upgrade: true,
  blocks: [
    goals("définir la cybersécurité, distinguer actif, menace, vulnérabilité, risque, attaque, impact et incident, expliquer la triade confidentialité, intégrité, disponibilité, inventorier tes actifs numériques, et estimer le coût simple d’une journée d’arrêt."),
    prerequisites("aucun."),
    scenario("Awa aide la coopérative Harmattan à gérer ses ventes sur téléphone et ordinateur. Un lundi matin, la messagerie ne répond plus et des factures ne sortent plus. Tout le monde parle de « piratage » sans préciser ce qui est touché. Pour réagir proprement, Awa doit d’abord comprendre ce que la cybersécurité protège et comment nommer le problème."),
    videoSlot("Comprendre la cybersécurité sans jargon inutile"),
    text("La cybersécurité protège les systèmes, les réseaux, les données et les personnes contre les usages non autorisés, les manipulations et les interruptions. La sécurité informatique vise surtout les ordinateurs et les réseaux. La sécurité de l’information est plus large : elle protège l’information sur tout support. La cybersécurité emprunte aux deux, avec un angle très concret sur les usages numériques."),
    figure({
      kind: "cards",
      title: "Vocabulaire de base",
      columns: 2,
      items: [
        { term: "Actif", text: "ce qui a de la valeur", tone: "green" },
        { term: "Menace", text: "ce qui peut causer un dommage", tone: "red" },
        { term: "Vulnérabilité", text: "faiblesse exploitable", tone: "amber" },
        { term: "Risque", text: "dommage plausible et impact estimé", tone: "violet" },
        { term: "Attaque", text: "action malveillante", tone: "red" },
        { term: "Impact", text: "conséquence subie", tone: "amber" },
        { term: "Incident", text: "événement qui perturbe ou compromet", tone: "blue" },
      ],
    }),
    text("On parle souvent de la triade C, I, D : confidentialité, intégrité, disponibilité. La confidentialité limite l’accès aux bonnes personnes. L’intégrité garantit qu’une information reste correcte. La disponibilité assure que le service reste accessible quand on en a besoin. Ces trois propriétés servent à décrire clairement ce qui est abîmé."),
    figure({
      kind: "table",
      title: "Triade C, I, D",
      columns: ["Propriété", "Exemple d’atteinte"],
      rows: [
        ["Confidentialité", "fuite d’une liste de clients"],
        ["Intégrité", "facture falsifiée avant validation"],
        ["Disponibilité", "rançongiciel qui bloque les postes"],
      ],
      highlight: 0,
    }),
    text("La cybersécurité n’est pas seulement une affaire d’experts. Ton téléphone, ta messagerie, ton argent mobile ou les dossiers d’une petite structure sont des actifs numériques. Les trois piliers sont les personnes, les processus et la technologie. Aucun système n’est sécurisé à 100 %. Le but réaliste est de réduire le risque, pas de promettre l’impossible."),
    text("Démonstration guidée : fais l’inventaire de tes actifs numériques avant de parler d’attaque. Sur ordinateur ou dans l’application Notes du téléphone, note ce qui existe, à quoi cela sert et ce qui ferait le plus mal en cas de perte, de fuite ou de blocage."),
    code("Actif                    Support         Pourquoi c’est important ?\nMessagerie principale    téléphone       réinitialisation des autres comptes\nCompte de paiement       téléphone       argent et historique des opérations\nDossiers clients         ordinateur      activité de la structure\nPhotos d’identité        cloud           données personnelles\nCarnet d’adresses        téléphone       continuité de contact", "text"),
    example("Exemple corrigé : un petit atelier réalise 8 réparations par jour et gagne 6 000 FCFA de marge par réparation. Une journée d’arrêt coûte donc environ 48 000 FCFA de marge, calcul simple : 8 x 6 000 = 48 000. Sans même compter les retards, la disponibilité a déjà une vraie valeur métier."),
    mistakes("réduire la cybersécurité aux antivirus ; confondre menace et vulnérabilité, par exemple appeler « mot de passe faible » une menace ; croire qu’un incident est forcément un grand piratage ; attendre une sécurité parfaite au lieu de réduire le risque tout de suite."),
    safety("si tu fais un inventaire ou un diagnostic, reste sur tes propres comptes, appareils et données, ou travaille avec une autorisation claire. Comprendre une attaque sert à mieux se défendre, pas à tester le système d’un tiers."),
    takeaway("la cybersécurité protège des actifs numériques qui ont une valeur réelle. La triade confidentialité, intégrité, disponibilité aide à décrire l’impact. Les personnes, les processus et la technologie travaillent ensemble, et l’objectif réaliste est de réduire le risque."),
    practice("ouvre « TP 5 : construire un registre de risques ». Classe chaque incident par confidentialité, intégrité ou disponibilité, puis réutilise ton propre inventaire d’actifs pour juger ce qui compte le plus. Termine par le quiz de la leçon."),
    reference("cybermalveillance"),
    reference("cisaSecureOurWorld"),
    reference("nistSmallBusiness"),
  ],
  quiz: {
    title: "Quiz : comprendre la cybersécurité",
    questions: [
      questions.choice("Quel énoncé décrit le mieux la cybersécurité ?", ["Installer un antivirus sur tous les ordinateurs", "Protéger systèmes, réseaux, données et personnes contre les usages non autorisés, les manipulations et les interruptions", "Cacher toutes les informations dans un cloud privé", "Réserver la sécurité à l’équipe informatique"], 1, "La cybersécurité couvre bien plus qu’un outil : elle protège des actifs, des comptes, des appareils et des personnes face à plusieurs types d’atteintes. L’antivirus aide, mais il ne couvre ni les procédures, ni les mots de passe, ni les erreurs humaines.", "facile"),
      questions.tf("Dire qu’un système est « sécurisé à 100 % » est une bonne manière de raisonner en cybersécurité.", false, "Faux : aucun système n’est totalement à l’abri. Le bon raisonnement consiste à réduire le risque par des mesures proportionnées. Promettre le risque zéro fait souvent oublier les priorités vraiment utiles.", "moyen"),
      questions.multi("Parmi ces situations, lesquelles relèvent surtout de la disponibilité ? (plusieurs réponses)", ["Un rançongiciel bloque l’ouverture des fichiers", "Une fuite expose une liste de clients", "Une panne empêche la messagerie de fonctionner pendant la journée", "Une facture est modifiée avant signature"], [0, 2], "La disponibilité concerne l’accès au service au bon moment. Un rançongiciel ou une panne de messagerie empêchent de travailler. La fuite de clients relève d’abord de la confidentialité, et la facture modifiée touche surtout l’intégrité.", "moyen"),
      questions.choice("Une petite structure perd l’accès à ses dossiers clients pendant une journée. Elle traite 8 dossiers par jour avec 6 000 FCFA de marge chacun. Quel coût direct de marge peux-tu estimer ?", ["14 000 FCFA", "24 000 FCFA", "48 000 FCFA", "86 000 FCFA"], 2, "Le calcul correct est 8 x 6 000 = 48 000 FCFA. C’est une estimation directe et défensive, utile pour comprendre pourquoi la disponibilité mérite des sauvegardes et un plan de reprise. 24 000 FCFA semble tentant si on oublie la moitié des dossiers.", "difficile"),
    ],
  },
};

const typesDeMenaces: NewLesson = {
  key: "l-c1-2",
  title: "Les types de menaces informatiques",
  summary: "Apprends à reconnaître les grandes familles de menaces, leur vecteur d’attaque habituel, la propriété de sécurité la plus touchée et la parade prioritaire à mettre en place.",
  minutes: 22,
  xp: 45,
  upgrade: true,
  blocks: [
    goals("reconnaître les principales familles de menaces, définir un vecteur d’attaque, relier une menace à la propriété C, I ou D la plus touchée, décrire un cycle d’attaque simplifié, et classer des incidents concrets."),
    prerequisites("avoir suivi « Qu’est-ce que la cybersécurité ? » ou déjà connaître la différence entre confidentialité, intégrité et disponibilité."),
    scenario("Koffi rejoint Atlas pour trier plusieurs incidents le même jour : faux message de paiement, ordinateur chiffré, mot de passe réutilisé, Wi-Fi public douteux, téléphone oublié dans un taxi. Si tout est rangé dans la case « attaque », l’équipe répondra mal. Koffi doit donc reconnaître la famille de menace, le point d’entrée probable et la parade principale."),
    videoSlot("Panorama des menaces informatiques pour débuter"),
    text("Une menace informatique est une famille de situations capables d’endommager un actif. Le vecteur d’attaque est la porte d’entrée utilisée : courriel, pièce jointe, mot de passe faible, réseau non sûr, appareil perdu ou fournisseur compromis. Deux incidents proches peuvent donc demander des parades très différentes."),
    figure({
      kind: "cards",
      title: "Grandes familles de menaces",
      columns: 2,
      items: [
        {
          term: "Logiciel malveillant",
          text: "virus, ver, cheval de Troie, espion, enregistreur de frappe, rançongiciel, agent de botnet",
          tone: "red",
        },
        { term: "Ingénierie sociale", text: "faux support, hameçonnage, appel urgent", tone: "amber" },
        { term: "Mots de passe", text: "devinette, dictionnaire, réutilisation", tone: "violet" },
        { term: "Réseau", text: "interception sur Wi-Fi non sûr, DoS, DDoS", tone: "blue" },
      ],
    }),
    text("Les logiciels malveillants regroupent plusieurs comportements. Un virus s’attache à un fichier, un ver se propage seul, un cheval de Troie se fait passer pour légitime, un logiciel espion collecte des données, et un rançongiciel bloque ou chiffre pour extorquer. À côté de cela, l’ingénierie sociale manipule la personne, les attaques sur mots de passe visent les comptes, le déni de service surcharge un service, et une faille non corrigée ouvre parfois la porte."),
    figure({
      kind: "table",
      title: "Menaces, propriété touchée et parade",
      columns: ["Menace", "C/I/D", "Exemple", "Parade principale"],
      rows: [
        ["Rançongiciel", "D", "fichiers bloqués", "sauvegardes + mises à jour"],
        ["Fuite d’identifiants", "C", "compte réutilisé", "mots de passe uniques + MFA"],
        ["Facture falsifiée", "I", "montant modifié", "double validation"],
        ["DoS ou DDoS", "D", "site saturé", "filtrage + capacité réseau"],
        ["Vol d’appareil", "C, D", "téléphone perdu", "chiffrement + verrouillage"],
      ],
      highlight: 1,
    }),
    text("On peut aussi raisonner avec un cycle d’attaque simplifié : reconnaissance, accès initial, installation ou déplacement, puis action sur l’objectif. Les menaces internes comptent aussi, par erreur ou malveillance. Pense également à la chaîne d’approvisionnement, quand un fournisseur, un logiciel tiers ou un prestataire devient la porte d’entrée."),
    text("Démonstration guidée : lis un incident court et réponds à trois questions dans cet ordre : quel est le vecteur probable, quelle propriété C, I ou D est la plus touchée, et quelle parade principale vient d’abord ? Sur téléphone, fais le même exercice dans une note."),
    code("Incident : « Un comptable reçoit un message urgent,\nouvre une pièce jointe et ses documents deviennent\nillisibles. Un message réclame un paiement. »\n\nVecteur probable : pièce jointe piégée\nPropriété la plus touchée : disponibilité\nParade principale : isoler le poste, restaurer depuis\nune sauvegarde saine, vérifier les mises à jour", "text"),
    example("Exemple corrigé : 1) faux message de virement : fraude, intégrité, double validation ; 2) identifiants réutilisés : attaque sur mots de passe, confidentialité, mots de passe uniques puis MFA ; 3) serveur saturé : DoS, disponibilité, filtrage ; 4) portable volé : confidentialité, chiffrement et effacement ; 5) faille non corrigée : entrée par vulnérabilité, parade par mises à jour."),
    mistakes("mélanger menace et vecteur d’attaque ; croire qu’un rançongiciel touche d’abord la confidentialité ; oublier les menaces internes ; chercher une parade compliquée alors qu’une mise à jour ou une double validation coupe déjà le scénario."),
    safety("n’essaie pas de reproduire une attaque réelle sur un système tiers pour « voir ». L’objectif d’une telle classification est défensif : reconnaître vite, contenir et orienter la bonne réponse."),
    takeaway("les menaces se distinguent par leur mode d’action, leur vecteur d’entrée et la propriété qu’elles touchent le plus. Le bon réflexe est d’identifier la famille, le point d’entrée probable et la parade prioritaire."),
    practice("ouvre « TP 5 : construire un registre de risques ». Classe les incidents par famille de menace et par propriété C, I ou D la plus touchée, puis compare avec la parade proposée. Termine par le quiz de la leçon."),
    reference("cmRancongiciels"),
    reference("cisaRansomware"),
  ],
  quiz: {
    title: "Quiz : types de menaces informatiques",
    questions: [
      questions.choice("Qu’appelle-t-on un vecteur d’attaque ?", ["Le but final de l’attaquant", "La porte d’entrée utilisée pour atteindre la cible", "La valeur financière d’un incident", "Le nom du logiciel de sécurité déployé"], 1, "Le vecteur d’attaque est bien le chemin utilisé pour entrer : courriel, mot de passe faible, service exposé, réseau non sûr. Le but final peut être le vol, le sabotage ou l’extorsion, mais ce n’est pas le vecteur.", "facile"),
      questions.tf("Une attaque par déni de service touche surtout la disponibilité.", true, "Vrai : le but principal d’un DoS ou DDoS est d’empêcher un service de répondre. On ne cherche pas d’abord à voler des données, mais à rendre la ressource indisponible pour les utilisateurs légitimes.", "facile"),
      questions.multi("Quelles situations relèvent surtout d’une menace interne, au moins en partie ? (plusieurs réponses)", ["Un employé envoie un fichier sensible au mauvais destinataire", "Un prestataire publie un faux site bancaire sous un domaine trompeur", "Un administrateur désactive volontairement des contrôles", "Un collègue partage son mot de passe pour aller plus vite"], [0, 2, 3], "Une menace interne peut venir d’une erreur ou d’une malveillance à l’intérieur de l’organisation. Le prestataire qui publie un faux site relève plutôt de la fraude externe ou de la chaîne d’approvisionnement selon le contexte.", "moyen"),
      questions.choice("Lis la situation suivante : « Nadia se connecte à un Wi-Fi public sans protection, puis son mot de passe de messagerie est capturé sur une page piégée ». Quelle lecture est la plus utile en premier ?", ["Menace : interception ou hameçonnage, vecteur : réseau non sûr ou faux portail, parade : vérifier l’adresse du site et protéger l’authentification", "Menace : rançongiciel, parade : restaurer une sauvegarde", "Menace : virus USB, parade : interdire les clés externes", "Menace : panne électrique, parade : acheter un onduleur"], 0, "La scène pointe vers un vol d’identifiants via réseau non sûr, faux portail ou faux site de connexion. Les autres réponses paraissent possibles si on lit trop vite, mais elles n’expliquent ni la capture du mot de passe ni le contexte du Wi-Fi public.", "difficile"),
    ],
  },
};

const principesDeSecurite: NewLesson = {
  key: "fond-principes",
  title: "Les principes de la sécurité : confidentialité, intégrité, disponibilité, moindre privilège",
  summary: "Maîtrise les propriétés et principes de base qui structurent toute bonne défense : C, I, D, authenticité, traçabilité, séparation des tâches et défense en profondeur.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer confidentialité, intégrité, disponibilité, authenticité, traçabilité et non-répudiation, distinguer identification, authentification et autorisation, appliquer le moindre privilège, et lire des couches de défense en profondeur."),
    prerequisites("avoir suivi « Qu’est-ce que la cybersécurité ? » et « Les types de menaces informatiques »."),
    scenario("L’association Teranga tient sa comptabilité et ses dossiers de bénévoles dans un espace partagé. Au début, tout le monde a accès à tout. Puis une facture est modifiée par erreur, un ancien bénévole garde encore son compte et personne ne sait qui a téléchargé un dossier sensible. L’équipe doit donc organiser les accès au lieu de compter sur la confiance seule."),
    videoSlot("Les grands principes de sécurité que tu retrouveras partout"),
    text("La triade confidentialité, intégrité, disponibilité reste la base, mais elle ne suffit pas toujours. L’authenticité répond à la question « est-ce bien la bonne personne ou machine ? ». La traçabilité permet de retrouver qui a fait quoi et quand. La non-répudiation rend plus difficile le fait de nier une action, par exemple avec une signature numérique et des journaux bien protégés."),
    figure({
      kind: "relations",
      title: "Question à poser et principe associé",
      pairs: [
        { from: "Qui es-tu ?", label: "renvoie à", to: "identification", tone: "cyan" },
        { from: "Peux-tu le prouver ?", label: "renvoie à", to: "authentification", tone: "blue" },
        { from: "À quoi as-tu droit ?", label: "renvoie à", to: "autorisation", tone: "violet" },
        { from: "Qui l’a fait ?", label: "renvoie à", to: "imputabilité", tone: "amber" },
        { from: "Peut-on le retracer ?", label: "renvoie à", to: "traçabilité", tone: "green" },
      ],
    }),
    text("Le moindre privilège signifie qu’un compte ne reçoit que les droits strictement nécessaires à sa mission. Le besoin d’en connaître va dans le même sens : on n’ouvre l’information qu’aux personnes qui en ont besoin. La séparation des tâches évite qu’une seule personne puisse initier, valider et payer une opération sensible."),
    figure({
      kind: "layers",
      title: "Défense en profondeur",
      nested: true,
      layers: [
        { label: "Humain", tone: "amber" },
        { label: "Données", tone: "violet" },
        { label: "Application", tone: "blue" },
        { label: "Appareil", tone: "green" },
        { label: "Réseau", tone: "cyan" },
        { label: "Physique", tone: "neutral" },
      ],
      caption: "Idée : plusieurs couches, pas une seule barrière.",
    }),
    text("La défense en profondeur empile des couches : physique, réseau, appareil, application, données et humain. Si l’une échoue, une autre peut encore limiter l’impact. La sécurité par défaut démarre avec des options sûres, par exemple un compte standard. La sécurité par conception pense aux risques dès le départ. La « confiance zéro » se résume ainsi : ne fais confiance à personne par défaut, vérifie chaque accès."),
    text("Démonstration guidée : regarde quels droits ton compte possède réellement. Sous Windows, « whoami /groups » liste les groupes de sécurité. Sous Linux, « id » montre l’identifiant utilisateur et les groupes. Un compte standard sert au quotidien ; un compte administrateur ne doit intervenir que lorsque c’est nécessaire. Sur téléphone, vérifie surtout les autorisations accordées aux applications."),
    code("Windows\nwhoami /groups\n\nLinux\nid\n\nExemple de lecture\nuid=1000(awa) gid=1000(awa) groups=1000(awa),27(sudo)\n\nSi ton compte appartient à un groupe d’administration,\ntu dois l’utiliser avec encore plus de prudence.", "text"),
    example("Exemple corrigé : l’association Teranga place sa comptabilité dans un espace où seule Nadia peut modifier, où le président peut lire sans écrire, et où les autres bénévoles n’ont aucun accès. La validation d’un paiement est séparée de sa préparation. Ici, confidentialité, intégrité, traçabilité et moindre privilège travaillent ensemble."),
    mistakes("donner les droits administrateur à tout le monde pour éviter les demandes d’assistance ; partager un même mot de passe entre collègues, ce qui détruit l’imputabilité ; croire qu’un bon antivirus remplace la séparation des tâches ; n’avoir qu’une seule couche de protection et tout perdre quand elle échoue."),
    safety("les commandes de vérification de compte doivent être lancées sur ton propre poste ou avec l’accord de la structure. Lire les droits d’un système tiers sans autorisation reste une action de reconnaissance non légitime."),
    takeaway("les principes de sécurité servent à décider qui peut faire quoi, comment on le vérifie et comment on limite les dégâts. Le moindre privilège, la séparation des tâches et la défense en profondeur réduisent fortement le risque sans exiger une grande infrastructure."),
    practice("ouvre « TP 5 : construire un registre de risques ». Pour chaque scénario, note quelle propriété C, I ou D est touchée, puis propose un contrôle de moindre privilège ou une couche de défense en plus. Termine par le quiz de la leçon."),
    reference("anssiHygiene"),
    reference("cnilAuthentifier"),
    reference("nistCsf"),
  ],
  quiz: {
    title: "Quiz : principes de sécurité",
    questions: [
      questions.choice("Quel principe dit qu’un compte doit recevoir uniquement les droits nécessaires à sa mission ?", ["La disponibilité", "Le moindre privilège", "La non-répudiation", "Le chiffrement intégral"], 1, "Le moindre privilège limite l’exposition en réduisant les droits disponibles. Le chiffrement ou la disponibilité répondent à d’autres besoins. La non-répudiation concerne plutôt la preuve d’une action et non le volume des autorisations.", "facile"),
      questions.tf("Identification, authentification et autorisation veulent dire exactement la même chose.", false, "Faux : l’identification déclare une identité, l’authentification cherche à la prouver, puis l’autorisation décide ce que cette identité peut faire. Confondre ces étapes conduit souvent à de mauvaises conceptions d’accès.", "moyen"),
      questions.multi("Quelles situations illustrent une défense en profondeur utile ? (plusieurs réponses)", ["Un poste chiffré, un compte standard et des sauvegardes séparées", "Un seul mot de passe administrateur partagé par toute l’équipe", "Un pare-feu, des mises à jour et une procédure de validation des virements", "Des journaux d’accès conservés pour comprendre un incident"], [0, 2, 3], "La défense en profondeur consiste à empiler des couches techniques et organisationnelles. Le mot de passe partagé va au contraire contre l’imputabilité et augmente le risque au lieu de le réduire.", "moyen"),
      questions.choice("Dans une petite association, la même personne prépare un paiement, l’approuve et l’exécute seule. Quel principe manque le plus clairement ?", ["La séparation des tâches", "La confidentialité", "Le chiffrement du disque", "La redondance réseau"], 0, "Quand une seule personne peut réaliser toute l’opération sensible sans contrôle croisé, la séparation des tâches manque. Les autres mesures peuvent être utiles, mais elles ne répondent pas directement à ce risque de fraude ou d’erreur.", "difficile"),
    ],
  },
};

const acteursCybersecurite: NewLesson = {
  key: "l-c1-3",
  title: "Les acteurs de la cybersécurité",
  summary: "Découvre qui attaque, qui défend, qui coordonne, qui corrige et pourquoi l’autorisation écrite fait toute la différence entre recherche légitime et acte illicite.",
  minutes: 18,
  xp: 40,
  upgrade: true,
  blocks: [
    goals("distinguer les grands types d’acteurs, expliquer les rôles de red team, blue team et purple team, situer SOC, CERT ou CSIRT, RSSI et DPO, et relier chaque rôle à une réponse à incident."),
    prerequisites("avoir suivi les trois leçons du module « Comprendre la cybersécurité »."),
    scenario("Sahel Services découvre qu’un compte de messagerie a été compromis. L’équipe technique veut couper l’accès, la direction veut rassurer les clients, et personne ne sait qui appeler pour vérifier l’angle données personnelles. En parallèle, un collègue demande si un « hacker éthique » peut tester la plateforme. Pour éviter la confusion, il faut savoir qui fait quoi et dans quel cadre légal."),
    videoSlot("Qui fait quoi en cybersécurité ?"),
    text("Tous les attaquants n’ont pas la même motivation. Les cybercriminels cherchent souvent l’argent. Les hacktivistes visent un message politique. Les acteurs étatiques recherchent l’influence ou l’espionnage. Les menaces internes viennent de personnes déjà proches de l’organisation, par erreur ou malveillance. Il existe aussi des curieux qui testent sans droit."),
    figure({
      kind: "cards",
      title: "Motivations d’un attaquant",
      items: [
        { term: "Financière", text: "voler, extorquer, frauder", tone: "red" },
        { term: "Politique", text: "afficher un message, perturber", tone: "amber" },
        { term: "Étatique", text: "espionner, préparer une influence", tone: "violet" },
        { term: "Interne", text: "abuser d’un accès déjà obtenu", tone: "blue" },
        { term: "Curiosité", text: "tester sans autorisation", tone: "neutral" },
      ],
    }),
    text("Les « chapeaux » aident à discuter, mais ne remplacent jamais la loi. Un white hat agit avec autorisation. Un black hat agit sans droit. Le grey hat existe dans certains discours, mais l’absence d’autorisation écrite reste un vrai problème juridique et éthique. Côté défense, la red team simule des attaques dans un cadre autorisé, la blue team détecte et répond, la purple team fait progresser les deux, et le SOC surveille les alertes au quotidien."),
    figure({
      kind: "relations",
      title: "Acteurs et relations",
      pairs: [
        { from: "Utilisateur", label: "signale", to: "un problème au SOC ou au support", tone: "cyan" },
        { from: "SOC / blue team", label: "analyse", to: "contient, escalade", tone: "blue" },
        { from: "CERT ou CSIRT", label: "coordonne", to: "la réponse à incident", tone: "violet" },
        { from: "RSSI", label: "décide", to: "des priorités de sécurité", tone: "amber" },
        { from: "DPO", label: "suit", to: "l’angle données personnelles", tone: "green" },
        { from: "Éditeur", label: "fournit", to: "correctifs et avis", tone: "neutral" },
        { from: "Autorité nationale", label: "publie", to: "guides et alertes", tone: "red" },
      ],
    }),
    text("Autour de l’incident, d’autres rôles comptent. Le CERT ou CSIRT coordonne la réponse. Le RSSI pilote la sécurité à l’échelle de la structure. Le DPO suit la protection des données personnelles. Les auditeurs évaluent, les chercheurs en vulnérabilités divulguent de façon responsable, les éditeurs publient des correctifs, et des autorités comme l’ANSSI diffusent des recommandations. L’utilisateur reste souvent le premier à voir un signe anormal."),
    text("Démonstration guidée : entraîne-toi à attribuer les rôles avant un vrai incident. Lis la scène, puis associe chaque action à l’acteur le plus logique. Sur téléphone, fais le même exercice dans une note. Le but n’est pas de retenir des sigles, mais de savoir qui alerter et qui décide."),
    code("Scène : « Une boîte mail envoie des messages suspects. »\n\nUtilisateur : signale le comportement inhabituel\nSOC ou support : confirme l’anomalie\nBlue team / admin : révoque les sessions et change l’accès\nRSSI : arbitre la priorité et la communication interne\nDPO : évalue l’impact sur les données personnelles\nÉditeur : fournit un correctif si une faille est en cause", "text"),
    example("Exemple corrigé : si une petite structure subit une compromission de messagerie, la blue team ou l’administrateur coupe les sessions, le support collecte les indices, le responsable sécurité coordonne, le DPO regarde l’impact sur les données personnelles, et la direction prépare la communication. Un pentest extérieur n’intervient que s’il est autorisé."),
    mistakes("croire que tous les attaquants poursuivent le même objectif financier ; appeler « éthique » toute action non autorisée sous prétexte qu’elle révèle une faille ; réduire la réponse à incident au seul technicien alors que coordination, juridique et communication comptent aussi ; oublier que l’utilisateur est souvent le premier capteur du problème."),
    safety("ne teste jamais un système qui n’est pas le tien sans accord explicite et écrit. La frontière pratique entre recherche légitime, audit autorisé et intrusion illégale se joue d’abord sur l’autorisation et le périmètre."),
    takeaway("l’écosystème de la cybersécurité réunit des motivations, des métiers et des responsabilités différentes. Bien réagir, c’est savoir qui détecte, qui décide, qui corrige, qui documente et dans quel cadre légal chacun agit."),
    practice("ouvre « Incident : un compte de messagerie compromis ». Observe qui fait quoi dans la chronologie et note quand la technique ne suffit plus sans coordination. Termine par le quiz de la leçon."),
    reference("anssiPortail"),
    reference("nistIncident"),
  ],
  quizExtension: {
    improve: [
      "La confidentialité consiste bien à limiter l’accès aux personnes autorisées. Rendre toutes les données publiques fait exactement l’inverse, et supprimer les sauvegardes aggrave en plus le risque sur la disponibilité sans protéger l’accès.",
      "La blue team travaille surtout sur la défense, la détection et la réponse aux incidents. Elle ne fabrique pas de publicités et elle ne supprime pas les contrôles de sécurité : ces deux options sont tentantes si on pense « équipe support », mais elles n’ont rien à voir avec sa mission principale.",
    ],
    add: [
      questions.choice("Dans une petite structure victime d’une compromission de messagerie, quel acteur est le plus directement chargé de coordonner la réponse technique et organisationnelle ?", ["Le service commercial", "Le designer du site web", "Le CERT ou CSIRT, s’il existe, ou le responsable sécurité désigné", "Le fournisseur d’accès Internet uniquement"], 2, "Le CERT ou CSIRT, ou à défaut le responsable sécurité désigné, coordonne la collecte d’informations, les actions de confinement et la circulation des décisions. Le fournisseur d’accès peut aider sur un point précis, mais il ne pilote pas toute la réponse.", "moyen"),
      questions.multi("Quelles affirmations sont correctes ? (plusieurs réponses)", ["Un white hat agit dans un cadre autorisé pour améliorer la sécurité", "Une purple team cherche à faire apprendre la red team et la blue team ensemble", "Un éditeur n’a aucun rôle une fois qu’une faille est découverte", "L’utilisateur peut être le premier à détecter un incident"], [0, 1, 3], "Le white hat agit avec autorisation, la purple team organise l’apprentissage entre offensif et défensif, et l’utilisateur repère souvent les premiers symptômes. Dire qu’un éditeur ne sert plus à rien est faux : il publie des correctifs, des avis et parfois des consignes de mitigation.", "difficile"),
    ],
  },
};

const metiersCybersecurite: NewLesson = {
  key: "fond-metiers",
  title: "Les métiers et les parcours de la cybersécurité",
  summary: "Explore les grandes familles de métiers de la cybersécurité, les compétences à développer, les parcours accessibles avec peu de moyens et la manière de construire un portfolio crédible.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("citer les grandes familles de métiers, distinguer compétences techniques et non techniques, relier un métier à une mission quotidienne, construire un parcours de départ réaliste, et choisir une prochaine étape d’apprentissage."),
    prerequisites("avoir suivi « Les acteurs de la cybersécurité » ou déjà savoir ce qu’est une blue team."),
    scenario("Binta veut entrer en cybersécurité, mais elle dispose surtout d’un téléphone, d’un ordinateur modeste et de peu de budget. Les annonces demandent parfois cloud, réseau, Linux, audit et code à la fois. Si elle tente de tout apprendre en même temps, elle se décourage. Il lui faut donc une carte simple des métiers et un chemin de progression réaliste."),
    videoSlot("Trouver ta voie dans les métiers de la cybersécurité"),
    text("La cybersécurité regroupe plusieurs familles de métiers. L’analyste SOC surveille et qualifie les alertes. La réponse à incident cherche à comprendre puis contenir. Le test d’intrusion évalue les défenses dans un cadre autorisé. La gouvernance, les risques et la conformité traduisent les exigences en politiques et preuves. D’autres rôles se concentrent sur la sécurité des applications, du cloud, l’architecture, la protection des données ou la sensibilisation."),
    figure({
      kind: "table",
      title: "Métiers et parcours conseillés",
      columns: ["Métier", "Mission du quotidien", "Parcours CyberPingo conseillé"],
      rows: [
        ["Analyste SOC", "lire journaux et alertes", "fondamentaux, réseaux"],
        ["Réponse à incident", "contenir, documenter", "fondamentaux, réseaux"],
        ["Pentest", "tester avec autorisation", "réseaux, web, Linux"],
        ["GRC / conformité", "cartographier contrôles", "fondamentaux"],
        ["AppSec", "sécuriser le code", "web, fondamentaux"],
        ["Cloud security", "sécuriser services cloud", "réseaux, fondamentaux"],
      ],
      highlight: 2,
    }),
    text("Les compétences techniques ne suffisent pas. Il faut aussi savoir rédiger, expliquer, écouter, documenter ses choix et respecter l’éthique. Pour un débutant avec peu de moyens, l’ordre utile est souvent : bases générales, réseaux, systèmes, lecture de journaux, web, puis spécialisation progressive. Les laboratoires gratuits et les mini comptes rendus écrits comptent beaucoup."),
    figure({
      kind: "cards",
      title: "Compétences à cultiver",
      items: [
        { term: "Technique", text: "réseaux, Linux, journaux, web, scripts", tone: "blue" },
        { term: "Méthode", text: "observation, priorisation, preuve", tone: "green" },
        { term: "Humain", text: "rédaction, pédagogie, éthique, calme", tone: "amber" },
        { term: "Portfolio", text: "compte rendu, capture d’écran, conclusion", tone: "violet" },
      ],
    }),
    text("Un portfolio crédible ne demande pas un grand laboratoire maison. Il peut contenir des comptes rendus de TP, une analyse d’incident fictif ou une explication claire d’une capture réseau. Les certifications existent, mais elles ne promettent pas un emploi à elles seules. Choisis-les selon ton objectif, leur coût réel et leur reconnaissance locale. Le référentiel NICE du NIST aide à explorer les rôles."),
    text("Démonstration guidée : pars de ce que tu aimes déjà faire. Si tu aimes comprendre pourquoi un service ne répond plus, commence par réseaux, journaux et réponse à incident. Si tu préfères expliquer et cadrer, regarde aussi la gouvernance. Sur téléphone, rédige ce plan en trois colonnes : « j’aime », « je dois apprendre », « prochaine action »."),
    code("Plan de départ de Binta\n\nJ’aime : enquêter, lire des journaux, expliquer\nÀ apprendre : bases réseaux, Linux, authentification\nProchaine action : finir les fondamentaux, puis faire\nun TP réseau et rédiger un court compte rendu\nObjectif 90 jours : 3 comptes rendus publiés", "text"),
    example("Exemple corrigé : Binta aime comprendre les incidents et rédiger clairement. Le parcours le plus cohérent pour elle est : fondamentaux, puis réseaux, puis pratique des journaux et de la réponse à incident. Elle complète chaque étape par un compte rendu court. Ce choix est meilleur qu’un départ direct en pentest, parce qu’il construit d’abord la méthode."),
    mistakes("chercher le « métier parfait » avant les bases ; croire qu’il faut choisir entre technique et communication ; accumuler des certifications sans preuves concrètes ; copier un portfolio sans expliquer ce qui a été compris."),
    safety("si tu pratiques sur des plateformes ou des laboratoires, reste dans le périmètre prévu et respecte les règles du service. Un portfolio crédible montre ce que tu sais faire légalement et proprement, pas ce que tu as forcé sans autorisation."),
    takeaway("la cybersécurité est un ensemble de métiers complémentaires. Commence par des bases solides, documente ce que tu apprends, puis spécialise-toi progressivement. Un bon portfolio prouve ta méthode."),
    practice("ouvre « Incident : un compte de messagerie compromis ». Observe les rôles nécessaires dans la chronologie, puis écris un mini compte rendu sur le métier qui t’attire le plus. Termine par le quiz de la leçon."),
    reference("nistNice"),
    reference("cybermalveillance"),
  ],
  quiz: {
    title: "Quiz : métiers et parcours de la cybersécurité",
    questions: [
      questions.choice("Quel rôle est le plus directement centré sur la surveillance des alertes et leur qualification quotidienne ?", ["Analyste SOC", "Designer graphique", "Comptable", "Opérateur de centre d’appels"], 0, "L’analyste SOC suit les alertes, les qualifie et les escalade si nécessaire. Les autres métiers peuvent contribuer à la sécurité, mais ce n’est pas leur mission principale au quotidien.", "facile"),
      questions.tf("En cybersécurité, savoir rédiger et expliquer clairement est secondaire par rapport aux compétences techniques.", false, "Faux : une bonne analyse mal expliquée aide peu. La rédaction, la pédagogie, la preuve et la méthode permettent aux autres d’agir, de comprendre le risque et de reproduire les bonnes pratiques.", "moyen"),
      questions.multi("Quelles démarches sont pertinentes pour un débutant avec peu de moyens ? (plusieurs réponses)", ["Faire des laboratoires gratuits et rédiger de courts comptes rendus", "Construire un portfolio avec ce que tu as réellement compris", "Attendre d’avoir beaucoup d’argent avant de commencer", "Utiliser le référentiel NICE pour explorer des rôles"], [0, 1, 3], "Les laboratoires, les comptes rendus et le référentiel NICE permettent d’avancer sans gros budget. Attendre des moyens parfaits bloque inutilement. Ce qui compte d’abord, c’est une progression régulière et documentée.", "moyen"),
      questions.choice("Binta aime lire des journaux, comprendre les incidents et expliquer ses conclusions. Quel premier chemin paraît le plus cohérent ?", ["Commencer directement par des attaques avancées sans bases réseau", "Suivre fondamentaux, puis réseaux, puis pratique des journaux et de la réponse à incident", "Éviter toute pratique écrite et viser seulement des vidéos", "Choisir une certification au hasard et ignorer les TP"], 1, "Ce chemin construit d’abord le langage, les observations réseau et la lecture des incidents. Les autres choix sautent des étapes utiles ou misent sur des signes extérieurs sans preuves concrètes de compréhension.", "difficile"),
    ],
  },
};

const referentielsEtLois: NewLesson = {
  key: "fond-referentiels",
  title: "Normes, référentiels et lois : le cadre de la sécurité",
  summary: "Comprends à quoi servent les normes, cadres, lois et bonnes pratiques, comment les distinguer, et pourquoi être conforme n’assure pas automatiquement d’être vraiment en sécurité.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer loi, norme, cadre et bonne pratique, citer les grands référentiels utiles en cybersécurité, expliquer l’intérêt d’un système de management de la sécurité, et choisir un cadre adapté à une petite structure."),
    prerequisites("avoir suivi « Les principes de la sécurité » et « Les acteurs de la cybersécurité »."),
    scenario("Le Cabinet Moussa doit rassurer un partenaire et formaliser ses pratiques. La direction entend parler d’ISO 27001, de NIST, du RGPD, de l’ANSSI, d’EBIOS et de clauses contractuelles, mais tout semble mélangé. Si l’équipe ne distingue pas loi, norme et bonne pratique, elle risque de faire beaucoup de papier sans gagner en sécurité réelle."),
    videoSlot("Le cadre de la sécurité : lois, normes et référentiels"),
    text("Un cadre de sécurité sert à éviter l’improvisation. Une loi crée des obligations juridiques. Une norme décrit des exigences ou des méthodes partagées, parfois certifiables. Un cadre organise les activités sans forcément viser une certification. Une bonne pratique est un conseil concret. La loi oblige, la norme structure, le cadre guide, la bonne pratique aide à agir."),
    figure({
      kind: "table",
      title: "Repères de conformité et de pilotage",
      columns: ["Nom", "Type", "Pour qui ?", "Usage courant"],
      rows: [
        ["RGPD", "loi", "organismes traitant", "protéger les données"],
        ["Convention de Malabo", "convention", "États et structures", "repère africain général"],
        ["ISO/IEC 27001", "norme", "organisations", "SMSI certifiable"],
        ["ISO/IEC 27002", "norme", "organisations", "catalogue de mesures"],
        ["NIST CSF 2.0", "cadre", "tout type d’orga", "piloter la cybersécurité"],
      ],
      highlight: 1,
    }),
    text("ISO/IEC 27001 décrit un système de management de la sécurité de l’information, souvent abrégé SMSI : gouvernance, objectifs, responsabilités, amélioration continue. ISO/IEC 27002 complète ce cadre avec des mesures de sécurité. Le NIST Cybersecurity Framework 2.0 organise la démarche en fonctions : gouverner, identifier, protéger, détecter, répondre, rétablir. Le guide d’hygiène de l’ANSSI rassemble une quarantaine de mesures concrètes. EBIOS Risk Manager aide à analyser les risques. Tu verras aussi MITRE ATT&CK pour décrire des techniques d’attaque, l’OWASP Top 10 pour les risques web fréquents, et PCI DSS pour encadrer la sécurité des données de carte de paiement."),
    figure({
      kind: "compare",
      title: "Conformité utile, mais limitée",
      sides: [
        {
          title: "Conforme sur le papier",
          tone: "amber",
          mark: "dot",
          items: ["exigences documentées", "cadre reconnu", "audit possible"],
        },
        {
          title: "Protégé dans la pratique",
          tone: "green",
          mark: "check",
          items: [
            "mesures réellement appliquées",
            "preuves et vérifications",
            "amélioration continue",
            "adaptation au risque réel",
          ],
        },
      ],
      verdict: "La conformité aide, mais elle ne remplace pas l’application réelle des mesures.",
    }),
    text("Les lois sur les données personnelles ajoutent un autre niveau. Le RGPD peut s’appliquer au-delà de l’Union européenne selon la situation. La Convention de Malabo, adoptée en 2014 et entrée en vigueur en 2023, donne un repère africain important, et de nombreux pays ont leur propre loi et autorité à rechercher. Les contrats imposent aussi parfois chiffrement, journalisation, délai de notification ou audit. Être conforme ne veut pourtant pas dire être en sécurité partout."),
    text("Démonstration guidée : prends une petite structure imaginaire et associe chaque besoin au bon cadre. Gouvernance globale : NIST CSF. SMSI formel : ISO 27001. Actions concrètes rapides : guide d’hygiène de l’ANSSI. Analyse de risques : EBIOS RM. Données personnelles : RGPD, Convention de Malabo et lois nationales. Sur téléphone, fais ce tri dans une note."),
    code("Besoins du Cabinet Moussa\n\n1. Prioriser les actions de base -> guide d’hygiène ANSSI\n2. Structurer la gouvernance -> NIST CSF 2.0\n3. Monter un SMSI certifiable -> ISO/IEC 27001\n4. Analyser les scénarios de risque -> EBIOS RM\n5. Encadrer les données personnelles -> RGPD,\n   Convention de Malabo, lois nationales", "text"),
    example("Exemple corrigé : une petite association n’a pas besoin de tout déployer d’un coup. Elle peut commencer par le guide d’hygiène de l’ANSSI, utiliser le NIST CSF pour classer ses actions, puis faire une première analyse de risques avec EBIOS RM. Si un partenaire exige une démarche plus formelle, elle pourra ensuite regarder ISO 27001."),
    mistakes("confondre conformité et sécurité réelle ; croire qu’un seul référentiel couvre tous les besoins ; ignorer les obligations contractuelles ; lancer une certification avant les pratiques de base."),
    safety("les référentiels guident une protection défensive. Si tu analyses un dispositif réel, respecte la confidentialité des preuves, les clauses contractuelles et les règles locales sur les données personnelles."),
    takeaway("loi, norme, cadre et bonne pratique ne jouent pas le même rôle. ISO 27001 structure un SMSI, le NIST CSF aide à piloter, le guide d’hygiène de l’ANSSI apporte des gestes concrets, et EBIOS RM aide à penser le risque. La conformité ne remplace pas l’application réelle des mesures."),
    practice("ouvre « Projet final : auditer la sécurité du Centre Numérique Soleil ». Repère quelles recommandations relèvent des mesures d’hygiène, du pilotage ou de l’analyse des risques, puis termine par le quiz de la leçon."),
    reference("anssiHygiene"),
    reference("nistCsf"),
    reference("anssiEbios"),
  ],
  quiz: {
    title: "Quiz : normes, référentiels et lois",
    questions: [
      questions.choice("Quel énoncé décrit le mieux ISO/IEC 27001 ?", ["Une méthode de chiffrement", "Une norme pour structurer un système de management de la sécurité de l’information", "Un antivirus gratuit", "Un protocole réseau"], 1, "ISO/IEC 27001 est une norme de management de la sécurité de l’information. Elle ne chiffre pas à elle seule et ne remplace ni des outils techniques, ni des procédures réellement appliquées.", "facile"),
      questions.tf("Être conforme à un référentiel donné garantit automatiquement qu’une organisation est totalement en sécurité.", false, "Faux : la conformité peut améliorer la structure, mais elle ne garantit ni l’application réelle, ni l’adaptation au risque, ni l’amélioration continue. Une sécurité vivante demande des vérifications concrètes.", "moyen"),
      questions.multi("Quelles associations sont correctes ? (plusieurs réponses)", ["Le guide d’hygiène de l’ANSSI propose des mesures concrètes de base", "EBIOS Risk Manager aide à analyser les risques", "Le NIST CSF 2.0 sert uniquement aux grandes banques américaines", "Les exigences contractuelles peuvent imposer des contrôles de sécurité"], [0, 1, 3], "Le guide d’hygiène de l’ANSSI et EBIOS RM ont bien ces rôles, et les contrats peuvent imposer des obligations fortes. Le NIST CSF n’est pas réservé à un seul secteur ou pays : il peut servir à de nombreuses organisations.", "moyen"),
      questions.choice("Une petite association veut d’abord lister ses actions prioritaires sans lancer une certification complète. Quel point de départ est le plus raisonnable ?", ["Copier toute une norme sans équipe dédiée", "Ignorer les données personnelles jusqu’à plus tard", "Commencer par des bonnes pratiques concrètes comme le guide d’hygiène de l’ANSSI, puis structurer progressivement", "Attendre un audit externe avant toute action"], 2, "Commencer par des mesures concrètes et structurantes est le choix le plus réaliste. Copier une norme entière ou attendre passivement donne l’illusion d’avancer sans améliorer tout de suite la protection effective.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c1:1",
    position: 1,
    existing: { fromTitle: "Comprendre la cybersécurité" },
    title: "Comprendre la cybersécurité",
    description: "Tu poses ici le vocabulaire, les menaces et les principes qui servent à lire n’importe quel problème de sécurité sans paniquer ni improviser. Critères de réussite : distinguer actif, menace, vulnérabilité et risque ; classer un incident selon confidentialité, intégrité ou disponibilité ; expliquer comment le moindre privilège et la défense en profondeur réduisent l’impact.",
    lessons: [quEstCeQueLaCybersecurite, typesDeMenaces, principesDeSecurite],
  },
  {
    key: "c1:2",
    position: 2,
    existing: { fromTitle: "L’écosystème de la sécurité" },
    title: "L’écosystème de la sécurité",
    description: "Ce module te montre qui agit dans la cybersécurité, comment ces rôles deviennent des métiers, et quels cadres guident une pratique sérieuse au quotidien. Critères de réussite : attribuer le bon rôle à chaque étape d’un incident ; relier un métier à ses missions et à un parcours d’apprentissage réaliste ; choisir un référentiel ou une loi pertinente selon le besoin d’une petite structure.",
    lessons: [acteursCybersecurite, metiersCybersecurite, referentielsEtLois],
  },
];
