import {
  code, example, figure, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const socialEngineeringLesson: NewLesson = {
  key: "fond-ingenierie-sociale",
  title: "L’ingénierie sociale : comment on manipule les gens",
  summary: "Comprendre comment un attaquant exploite la confiance, l’urgence ou la curiosité pour contourner les protections techniques, puis adopter des réflexes simples pour stopper la manipulation.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("identifier les principaux leviers psychologiques, reconnaître les techniques courantes d’ingénierie sociale, décrire les cinq étapes d’une attaque, repérer le moment où elle aurait pu être stoppée et appliquer un réflexe de vérification par un second canal."),
    prerequisites("avoir vu les familles de menaces informatiques ou connaître la différence entre une attaque technique et une manipulation humaine."),
    scenario("Nadia reçoit l’appel d’une personne qui se présente comme le support informatique de Baobab Tech. La voix parle vite, cite le nom du directeur et explique qu’un incident bloque les comptes. Nadia doit agir « tout de suite » pour éviter une coupure. Elle hésite, car l’interlocuteur semble bien informé et très sûr de lui."),
    videoSlot("Ingénierie sociale : reconnaître la manipulation avant de cliquer"),
    text("L’ingénierie sociale consiste à obtenir d’une personne une action, une information ou un accès qu’elle n’aurait pas dû donner. L’attaquant ne casse pas d’abord la machine : il influence un humain. Il cherche par exemple un mot de passe, un code de validation, un virement urgent, l’ouverture d’une pièce jointe ou l’accès à un bâtiment. La cible peut être un employé, un bénévole, un étudiant, un proche ou toi-même sur ton téléphone."),
    figure({
      kind: "table",
      title: "Leviers, signaux d’alarme et réflexes",
      columns: ["Levier", "Signal d’alarme", "Réflexe"],
      rows: [
        ["Autorité", "« Le directeur l’exige »", "Vérifier la demande"],
        ["Urgence", "« Dans 5 minutes sinon... »", "Ralentir"],
        ["Curiosité", "« Regarde ce document secret »", "Ouvrir avec prudence"],
        ["Peur", "« Ton compte sera bloqué »", "Passer par un canal sûr"],
        ["Appât du gain", "« Tu as gagné »", "Chercher la contrepartie"],
      ],
      highlight: 2,
    }),
    text("Les leviers psychologiques reviennent souvent : l’autorité, l’urgence, la rareté, la réciprocité, la preuve sociale, la sympathie, la peur, la curiosité et l’appât du gain. Un attaquant peut dire « tout le service l’a déjà fait » pour créer une preuve sociale, ou « je t’aide à distance » pour se rendre sympathique. Il peut aussi mélanger plusieurs leviers. Plus le message te pousse à agir vite et sans contrôle, plus le risque augmente."),
    figure({
      kind: "steps",
      title: "Anatomie d’une attaque en 5 étapes",
      numbered: true,
      items: [
        { title: "Reconnaissance", text: "collecte d’infos publiques", tone: "cyan" },
        { title: "Prétexte", text: "histoire crédible et rôle joué", tone: "blue" },
        { title: "Contact", text: "mail, SMS, appel, QR code, visite", tone: "violet" },
        { title: "Action", text: "obtenir clic, code, accès ou argent", tone: "amber" },
        { title: "Exploitation", text: "réutiliser ce qui a été obtenu", tone: "red" },
      ],
    }),
    text("La reconnaissance prépare l’attaque. Les réseaux sociaux, les signatures de courriel, un organigramme public, une affiche à l’accueil ou une conversation entendue dans un transport donnent déjà beaucoup d’indices. Ensuite vient le prétexte : faux support technique, faux collègue, faux recruteur, faux livreur, faux agent du service de paiement mobile. Les techniques varient : hameçonnage, SMS frauduleux, appel, QR code, clé USB abandonnée, filature à la porte, usurpation d’un collègue ou d’un prestataire."),
    text("Démonstration guidée : imagine qu’un appel commence par « je vois une activité anormale sur ton compte, donne-moi le code affiché pour que je bloque l’attaque ». Arrête-toi avant de répondre et déroule trois questions : qui parle réellement, par quel numéro rappelable, et quelle procédure interne autorise cette demande ? Si tu ne peux pas répondre clairement aux trois, coupe l’échange, retrouve le numéro officiel et appelle toi-même. Sur téléphone, le principe est le même : ne rappelle jamais le numéro dicté dans l’appel ou le SMS."),
    code("Appel reçu : « Bonjour, ici le support. J’ai besoin du code affiché sur ton téléphone. »\n\nRéponse sûre :\n1. « Je ne donne jamais de code pendant un appel. »\n2. « Je note votre demande. »\n3. Je raccroche.\n4. J’appelle le numéro officiel de l’organisation.\n5. Je signale la tentative à mon responsable ou au canal prévu.", "text"),
    text("Les contre-mesures sont surtout organisationnelles. Vérifier par un second canal, ralentir, demander une double validation pour l’argent ou les accès sensibles, limiter les privilèges, et installer une culture sans blâme : une personne doit pouvoir signaler un doute sans se faire ridiculiser. La meilleure défense n’est pas d’être « malin », mais d’avoir une procédure simple et répétable."),
    example("Exemple corrigé : Koffi reçoit l’appel d’un faux support. Le prétexte est crédible, car l’attaquant connaît le nom de son service. Les leviers utilisés sont l’autorité, l’urgence et la peur. L’attaque aurait pu s’arrêter dès la demande du code de validation, car un support légitime n’a pas besoin de ce secret. La bonne réaction est de raccrocher, de rappeler via le numéro officiel et de signaler la tentative."),
    mistakes("croire qu’une attaque réussit seulement contre les personnes « inattentives », alors que la pression émotionnelle touche tout le monde ; répondre dans l’instant à une demande urgente sans chercher un second canal ; publier trop d’informations de contexte sur les réseaux sociaux ; punir le signalement d’une erreur, ce qui pousse ensuite au silence."),
    safety("n’imite pas un support, un collègue ou un service de paiement mobile en dehors d’un exercice autorisé. Tester quelqu’un sans accord clair peut causer un préjudice réel et reste une mauvaise pratique, voire une infraction selon le contexte."),
    takeaway("l’ingénierie sociale cible d’abord l’humain. Les signes les plus utiles sont l’urgence, l’autorité non vérifiée et la demande d’un secret ou d’une action inhabituelle. Un second canal, une procédure simple et une culture sans blâme stoppent beaucoup d’attaques."),
    practice("ouvre le laboratoire « TP 1 : disséquer un courriel d’hameçonnage », observe comment l’attaquant pousse à agir vite, puis repère dans le SMS d’arnaque les leviers utilisés et la bonne réaction. Termine par le quiz de la leçon."),
    reference("wikiIngenierieSociale"),
    reference("cmHameconnage"),
    reference("cisaSecureOurWorld"),
  ],
  quiz: {
    title: "Quiz : ingénierie sociale",
    questions: [
      questions.choice("Quel signal doit t’alerter en priorité pendant un appel de « support » ?", ["Le fait que la personne parle calmement", "La demande de confirmer ton prénom", "La demande d’un code secret à communiquer tout de suite", "Le fait qu’elle connaisse le nom de ton organisation"], 2, "La demande immédiate d’un secret, comme un code de validation, est le meilleur indice d’une tentative de manipulation. Connaître le nom de l’organisation ou ton prénom peut venir d’informations publiques et ne prouve rien à lui seul.", "facile"),
      questions.tf("Vérifier une demande urgente par un second canal montre surtout que tu refuses d’aider l’équipe.", false, "Faux : vérifier par un second canal est un réflexe de sécurité, pas un manque de coopération. Cela protège l’équipe, les comptes et l’argent contre les prétextes crédibles qui exploitent précisément la pression du moment.", "moyen"),
      questions.multi("Quelles mesures peuvent réellement casser une attaque d’ingénierie sociale ? Plusieurs réponses sont justes.", ["Rappeler un numéro officiel trouvé soi-même", "Exiger une double validation pour un virement inhabituel", "Communiquer son code par SMS si l’appel semble pressé", "Permettre le signalement d’un doute sans blâme"], [0, 1, 3], "Rappeler un numéro officiel, imposer une double validation et encourager le signalement interrompent souvent la chaîne de manipulation. En revanche, envoyer un code parce que l’appel paraît urgent donne exactement à l’attaquant ce qu’il cherche.", "difficile"),
      questions.choice("Dans ce scénario, à quel moment l’attaque aurait-elle dû être stoppée ? « Bonjour, ici le support. Le directeur est au courant. J’ai besoin du code affiché sur ton téléphone avant 10 h. »", ["Quand le nom du directeur est cité", "Quand l’appelant dit bonjour", "Quand l’appelant demande le code affiché", "Seulement après avoir reçu un courriel de confirmation"], 2, "Le moment décisif est la demande du code affiché, car ce secret sert souvent à prendre le contrôle du compte. Le nom du directeur peut être public, et attendre un autre message garde la conversation ouverte inutilement.", "difficile"),
    ],
  },
};

const phishingLesson: NewLesson = {
  key: "fond-hameconnage",
  title: "Reconnaître un courriel d’hameçonnage : expéditeur, liens et pièces jointes",
  summary: "Apprendre à lire un message suspect sans se faire piéger : adresse réelle, en-têtes, domaine d’un lien, pièces jointes et bons réflexes si l’on a cliqué ou saisi un mot de passe.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer le nom affiché de l’adresse réelle, lire les champs essentiels d’un en-tête, interpréter simplement SPF, DKIM et DMARC, repérer un lien trompeur ou une pièce jointe risquée et choisir la bonne réaction après un clic."),
    prerequisites("avoir suivi la leçon sur l’ingénierie sociale ou savoir qu’un message peut manipuler l’émotion pour obtenir une action."),
    scenario("Awa reçoit un courriel censé venir de la comptabilité d’Atlas. Le nom affiché semble correct, mais le message menace de bloquer son accès si elle n’ouvre pas la pièce jointe avant midi. Sur son téléphone, le lien paraît court et rassurant. Avant de cliquer, Awa doit lire ce que le message révèle vraiment."),
    videoSlot("Lire un courriel suspect sans tomber dans le piège"),
    text("Un courriel d’hameçonnage imite souvent une organisation, un collègue ou un service connu pour te pousser à cliquer, ouvrir une pièce jointe ou donner une information sensible. Le premier piège est visuel : le nom affiché n’est pas la preuve de l’expéditeur réel. Ton client de messagerie peut montrer « Comptabilité Atlas » alors que l’adresse véritable est autre chose. Il faut donc regarder l’adresse complète et, si besoin, les en-têtes du message."),
    figure({
      kind: "anatomy",
      title: "Nom affiché ≠ adresse réelle",
      lines: [
        [
          { text: "Affiché :", tone: "neutral" },
          { text: "Comptabilité Atlas", label: "nom vu à l’écran", tone: "green" },
        ],
        [
          { text: "From :", tone: "neutral" },
          { text: "facturation@atlas-service.example.org", label: "adresse réelle", tone: "amber" },
        ],
        [
          { text: "Reply-To :", tone: "neutral" },
          { text: "recouvrement@example.net", label: "où partira la réponse", tone: "red" },
        ],
      ],
      caption: "Signal : la réponse part vers `example.net`, pas vers le domaine affiché à l’écran.",
    }),
    text("Les en-têtes racontent le trajet du message. « From » indique l’adresse annoncée à l’utilisateur. « Reply-To » peut forcer les réponses vers une autre boîte. « Return-Path » montre souvent où reviennent les erreurs de distribution. Les lignes « Received » décrivent les serveurs traversés, du plus récent au plus ancien. Enfin, « Authentication-Results » résume des contrôles utiles : SPF vérifie surtout si l’adresse utilisée pendant l’envoi, souvent visible via « Return-Path » ou « MAIL FROM », autorise bien le serveur d’envoi, DKIM vérifie une signature associée au domaine indiqué par « d= », et DMARC vérifie surtout si le domaine affiché dans « From » est aligné avec un SPF ou un DKIM qui a réussi. « pass » veut dire que le contrôle a réussi, « fail » qu’il a échoué, et « none » qu’il n’y a pas de résultat utile pour ce contrôle."),
    figure({
      kind: "anatomy",
      title: "Extrait d’en-têtes annoté",
      lines: [
        [
          { text: "Authentication-Results: mx.example.org;", label: "résumé des contrôles", tone: "neutral" },
        ],
        [
          { text: "spf=fail", label: "échec SPF", tone: "red" },
          { text: "smtp.mailfrom=atlas-service.example.org", label: "MAIL FROM", tone: "amber" },
        ],
        [
          { text: "dkim=none", label: "signature absente", tone: "amber" },
          { text: "header.d=none", label: "pas de domaine DKIM", tone: "amber" },
        ],
        [
          { text: "dmarc=fail", label: "échec DMARC", tone: "red" },
          { text: "Reply-To: aide@example.net", label: "la réponse part ailleurs", tone: "red" },
        ],
      ],
      caption: "Lecture simple : `fail` = échec, `none` = absent, et la réponse veut partir ailleurs.",
    }),
    text("Un lien se lit de droite à gauche à partir du domaine enregistrable. Dans « paiement.atlas.example.org.verif-example.net », le vrai domaine est « verif-example.net », pas « atlas.example.org ». Les faux domaines utilisent aussi des lettres échangées, des tirets ou des sous-domaines trompeurs. Les liens raccourcis cachent encore plus l’adresse finale. Sur ordinateur, le survol aide à voir la destination. Sur téléphone, mieux vaut appuyer longuement si l’application l’autorise, ou taper soi-même l’adresse officielle dans le navigateur."),
    text("Les pièces jointes dangereuses cherchent à être ouvertes vite : double extension, archive protégée par mot de passe, document qui réclame une macro, ou fichier inattendu. Le cadenas d’un site ne prouve pas sa légitimité : il indique surtout que la connexion est chiffrée. Un faux site de connexion peut donc afficher HTTPS et rester un piège. Les signaux les plus fiables restent l’adresse réelle, le domaine du lien, la demande d’un secret, l’urgence inhabituelle et la cohérence avec le contexte."),
    text("Démonstration guidée : dans ton client mail, cherche l’option « Afficher l’original », « Afficher la source » ou son équivalent. Sur téléphone, elle se cache souvent dans le menu du message. Lis ensuite quatre zones dans cet ordre : From, Reply-To, Authentication-Results, puis les premiers Received. Tu ne dois pas tout comprendre techniquement. Le but est de répondre à trois questions pratiques : qui prétend envoyer, qui recevra la réponse, et les contrôles du domaine concordent-ils ou non ?"),
    code("Checklist minimale d’un courriel suspect\n1. Afficher l’original ou la source du message\n2. Lire From et Reply-To\n3. Lire Authentication-Results\n4. Regarder le domaine du lien sans cliquer\n5. Si doute : fermer, signaler, puis taper l’adresse officielle soi-même", "text"),
    example("Exemple corrigé : Awa voit le lien « https://espace.atlas.example.org.verif-example.net/connexion ». En le lisant de droite à gauche, elle repère que le vrai domaine est « verif-example.net ». Les en-têtes montrent « spf=fail » et « dmarc=fail », et la réponse partirait vers une autre adresse. Le bon choix est de ne pas cliquer, de signaler le message et d’ouvrir elle-même le site officiel si elle veut vérifier son compte. Si elle avait déjà saisi son mot de passe, elle devrait le changer depuis le vrai site, activer la double authentification et prévenir l’organisation."),
    mistakes("se fier au seul nom affiché ; croire que le cadenas garantit l’identité du site ; ouvrir une pièce jointe inattendue « juste pour voir » ; répondre au message suspect pour demander si c’est vrai, alors que la réponse peut partir vers l’attaquant."),
    safety("n’ouvre pas volontairement des pièces jointes ou des liens suspects hors d’un laboratoire prévu pour cela. Si tu analyses un message réel, fais-le en lecture seule et suis la procédure de signalement de ton organisation."),
    takeaway("pour juger un courriel, lis l’adresse réelle, les en-têtes utiles et le vrai domaine d’un lien. SPF, DKIM et DMARC donnent des indices, mais ils ne remplacent pas le contexte. En cas de doute, ne clique pas, signale et repasse par une adresse officielle saisie par toi."),
    practice("ouvre le laboratoire « TP 1 : disséquer un courriel d’hameçonnage », lis l’expéditeur réel, les liens et la pièce jointe, puis compare tes indices avec le SMS d’arnaque du même TP. Termine par le quiz de la leçon."),
    reference("cmHameconnage"),
    reference("rfc5322"),
    reference("rfc7489"),
  ],
  quiz: {
    title: "Quiz : reconnaître un courriel d’hameçonnage",
    questions: [
      questions.choice("Quel champ doit t’alerter si le message semble venir d’une organisation connue, mais que les réponses partent ailleurs ?", ["Received", "Reply-To", "Subject", "Date"], 1, "Le champ Reply-To indique où partira ta réponse. S’il pointe vers un autre domaine que celui attendu, c’est un excellent signal d’alarme. Received et Date apportent du contexte, mais ils ne montrent pas directement ce piège de redirection.", "facile"),
      questions.tf("Si un site de connexion affiche un cadenas et « https », cela prouve que le site est légitime.", false, "Faux : le cadenas montre surtout que la connexion est chiffrée. Un attaquant peut très bien obtenir un certificat pour un faux domaine crédible. Il faut donc vérifier l’adresse complète et le domaine, pas seulement la présence de HTTPS.", "moyen"),
      questions.multi("Que peux-tu conclure de cet extrait ? « spf=fail », « dkim=none », « dmarc=fail », Reply-To vers example.net. Plusieurs réponses sont justes.", ["Le domaine affiché n’est pas correctement validé par les contrôles du message", "La réponse au message partira vers un autre domaine", "Le message est forcément légitime car il contient des en-têtes techniques", "Le message mérite d’être traité comme suspect"], [0, 1, 3], "Les échecs SPF et DMARC, l’absence de DKIM et un Reply-To différent montrent une forte incohérence. Les en-têtes ne rendent pas un message fiable par eux-mêmes : ils fournissent justement les indices qui permettent de douter.", "difficile"),
      questions.choice("Dans l’URL « portail.atlas.example.org.verif-example.net », quel est le domaine enregistrable à vérifier en priorité ?", ["atlas.example.org", "portail.atlas.example.org", "verif-example.net", "org.verif-example"], 2, "Le vrai domaine se lit de droite à gauche : ici, c’est « verif-example.net ». Le reste n’est qu’un sous-domaine placé pour te rassurer. Beaucoup de faux sites jouent précisément sur cette confusion visuelle.", "difficile"),
    ],
  },
};

const mobileScamsLesson: NewLesson = {
  key: "fond-arnaques-mobiles",
  title: "Arnaques par SMS, appels et paiements mobiles",
  summary: "Identifier les escroqueries qui visent surtout le téléphone : SMS, appels, QR codes, faux transferts, échange de carte SIM et faux comptes de messagerie instantanée.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("reconnaître les scénarios mobiles les plus courants, expliquer pourquoi un code reçu par SMS ne doit jamais être communiqué, repérer les signaux d’un faux transfert ou d’un faux conseiller et choisir la réaction la plus sûre sur téléphone."),
    prerequisites("avoir vu les bases de l’ingénierie sociale ou savoir qu’une urgence émotionnelle peut pousser à une mauvaise décision."),
    scenario("Mamadou reçoit un SMS : « colis en attente, frais à régler ». Une heure plus tard, une autre personne l’appelle en disant qu’un transfert mobile a été envoyé par erreur et qu’il faut le rembourser tout de suite. En parallèle, un proche lui écrit sur messagerie instantanée : « j’ai changé de numéro ». Tout arrive sur le même téléphone, au moment où Mamadou est pressé."),
    videoSlot("SMS, appels et paiements mobiles : les réflexes qui évitent l’arnaque"),
    text("Le téléphone concentre beaucoup de choses : messagerie, banque, paiement mobile, réseaux sociaux, codes de validation et parfois comptes professionnels. C’est pour cela qu’il attire autant les escrocs. Les scénarios les plus courants sont les SMS frauduleux au sujet d’un colis, d’une amende, d’un gain ou d’un compte bloqué ; les appels de faux conseillers ; les faux emplois ou faux investissements ; les QR codes piégés ; et les applications téléchargées hors boutique officielle."),
    figure({
      kind: "table",
      title: "Scénarios mobiles et bonne réaction",
      columns: ["Scénario", "Levier", "Réflexe"],
      rows: [
        ["SMS « colis en attente »", "Urgence", "Taper l’adresse officielle"],
        ["Appel du « conseiller »", "Autorité", "Raccrocher et rappeler"],
        ["« Transfert envoyé par erreur »", "Pression morale", "Vérifier le solde réel"],
        ["« J’ai changé de numéro »", "Confiance", "Vérifier par un autre canal"],
        ["QR code inconnu", "Curiosité", "Demander l’URL avant d’ouvrir"],
      ],
      highlight: 2,
    }),
    text("Le paiement mobile est une cible classique. Un escroc peut prétendre avoir envoyé de l’argent par erreur et te demander un remboursement immédiat avant que tu aies vérifié le solde réel dans l’application officielle. Un autre peut se faire passer pour un agent du service de paiement mobile et demander un code de validation ou un code PIN. Ce code ne se partage jamais. Un vrai conseiller n’en a pas besoin pour « sécuriser » ton compte."),
    text("La double authentification par SMS aide parfois, mais le SMS reste un facteur fragile. Un échange de carte SIM peut détourner les messages vers une autre puce si l’opérateur est trompé. C’est une raison de plus pour ne jamais considérer un code reçu par SMS comme une preuve d’identité à transmettre. Sur messagerie instantanée, le scénario « c’est moi, j’ai changé de numéro » sert souvent à réclamer de l’argent ou un code. Un mot de passe de famille ou une question connue seulement des proches peut casser cette manipulation."),
    figure({
      kind: "steps",
      title: "Réaction sûre sur téléphone",
      numbered: true,
      items: [
        { title: "Lire sans cliquer", tone: "cyan" },
        { title: "Chercher le service", text: "dans l’application officielle", tone: "blue" },
        { title: "Raccrocher", text: "si un secret est demandé", tone: "amber" },
        { title: "Vérifier", text: "par un autre canal", tone: "violet" },
        { title: "Bloquer et signaler", text: "conserver une preuve si besoin", tone: "green" },
      ],
    }),
    text("Démonstration guidée : prends un SMS suspect et réponds mentalement à trois questions avant toute action. Quel est le vrai domaine du lien ? Quelle émotion le message cherche-t-il à provoquer ? Quel canal officiel peux-tu utiliser à la place ? Si le message parle d’un colis, ouvre toi-même l’application ou le site officiel du transporteur. Si l’appel parle d’argent, raccroche puis rappelle le numéro officiel affiché sur ton contrat ou sur l’application connue."),
    code("Message reçu : « colis en attente, règle 1500 F maintenant »\n\nRéponse sûre :\n1. Je ne touche pas au lien.\n2. J’ouvre moi-même l’application ou le site officiel.\n3. Je vérifie si un colis existe vraiment.\n4. Si rien n’apparaît, je supprime et je signale.\n5. Si j’ai cliqué, je change mon mot de passe depuis le vrai site.", "text"),
    text("Si tu penses t’être fait piéger, agis vite : change le mot de passe du compte concerné depuis l’application ou le site légitime, active une méthode d’authentification plus robuste quand elle existe, contacte ton opérateur si tu crains un échange de SIM, surveille tes relevés, bloque le numéro et signale l’arnaque. Selon ton pays, tu peux aussi déposer plainte. Garde des captures datées, car elles peuvent servir pour le signalement."),
    example("Exemple corrigé : Mamadou reçoit « colis en attente » avec un lien vers « livraison-suivi.example.net ». Le domaine n’est pas celui du service officiel, l’urgence pousse à payer vite et le message demande une petite somme pour sembler crédible. Le bon réflexe est d’ouvrir lui-même l’application officielle de livraison ou le site saisi à la main, pas le lien reçu. Si un appel suit en demandant un code de validation, il doit raccrocher immédiatement."),
    mistakes("croire qu’un petit montant n’est pas grave, alors que le premier paiement sert souvent à tester la victime ; rappeler le numéro dicté par l’appelant au lieu d’un numéro officiel ; donner un code de validation pour « annuler » une opération ; installer une application depuis un fichier reçu par message alors qu’elle devrait venir d’une boutique officielle."),
    safety("ne simule jamais un faux conseiller, un faux agent de paiement mobile ou un proche en détresse sur des personnes réelles. Même « pour tester » un ami, tu risques de provoquer un vrai préjudice financier ou émotionnel."),
    takeaway("sur téléphone, l’urgence et la confiance sont exploitées en permanence. Un code de validation ou un code PIN ne se communique jamais. La règle la plus sûre reste de quitter le message, de rappeler un numéro officiel et de vérifier dans l’application légitime."),
    practice("ouvre le laboratoire « TP 1 : disséquer un courriel d’hameçonnage », puis applique les mêmes réflexes au SMS d’arnaque proposé : domaine du lien, émotion recherchée et bonne réaction. Termine par le quiz de la leçon."),
    reference("cybermalveillance"),
    reference("effSsd"),
    reference("cisaSecureOurWorld"),
  ],
  quiz: {
    title: "Quiz : arnaques mobiles",
    questions: [
      questions.choice("Que dois-tu faire si un appelant dit être ton conseiller et demande le code reçu par SMS pour « bloquer » une fraude ?", ["Ne jamais donner le code, raccrocher et rappeler le numéro officiel", "Donner le code une seule fois pour vérifier son identité", "Envoyer le code par message pour garder une trace", "Patienter en ligne jusqu’à recevoir un second code"], 0, "Le code reçu par SMS ou dans une application sert à prouver que c’est bien toi. Le communiquer donne souvent le contrôle du compte à l’attaquant. Le bon réflexe est de raccrocher puis de rappeler un numéro officiel trouvé par toi.", "facile"),
      questions.tf("Le SMS est toujours une preuve d’identité forte, car seul le propriétaire du numéro peut le recevoir.", false, "Faux : un SMS peut être intercepté ou détourné, notamment en cas d’échange de carte SIM ou de faiblesse chez l’opérateur. C’est mieux que rien dans certains cas, mais ce n’est pas une preuve absolue d’identité.", "moyen"),
      questions.multi("Quels réflexes sont adaptés face à un faux transfert envoyé « par erreur » ? Plusieurs réponses sont justes.", ["Vérifier le solde dans l’application officielle avant toute action", "Se fier uniquement à la capture d’écran envoyée par l’appelant", "Passer par le support officiel si la situation semble réelle", "Refuser de communiquer un code ou un code PIN"], [0, 2, 3], "La capture d’écran peut être falsifiée ou sortir du contexte. Il faut vérifier le solde réel dans l’application légitime, contacter le support officiel si nécessaire et ne jamais communiquer de secret. Céder sous la pression morale fait précisément réussir l’arnaque.", "difficile"),
      questions.choice("Quel indice rend un QR code reçu sur une affiche ou dans un message particulièrement risqué ?", ["Il est en noir et blanc", "Tu ne vois pas l’URL réelle avant de l’ouvrir", "Il est plus rapide à scanner qu’un lien écrit", "Il peut ouvrir l’appareil photo"], 1, "Le danger principal d’un QR code est qu’il masque l’adresse réelle tant que tu ne l’as pas ouverte ou prévisualisée. Sa couleur ou sa rapidité n’ont aucun rapport direct avec la sécurité ; le problème vient du manque de visibilité sur la destination.", "difficile"),
    ],
  },
};

const passwordsLesson: NewLesson = {
  key: "fond-mots-de-passe",
  title: "Mots de passe : comment on les attaque, comment les choisir",
  summary: "Comprendre les attaques contre les mots de passe, le rôle des empreintes salées, et pourquoi la longueur, l’unicité et les phrases de passe protègent mieux que des règles de complexité mal comprises.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("décrire les principales attaques contre les mots de passe, expliquer simplement le stockage par empreinte et sel, calculer une entropie et un nombre de combinaisons, distinguer un mot de passe faible d’une phrase de passe solide et choisir une stratégie défendable au quotidien."),
    prerequisites("connaître les bases des menaces informatiques et savoir qu’un site ne devrait jamais stocker ton mot de passe en clair."),
    scenario("Rokia gère plusieurs comptes pour l’association Teranga. Elle hésite entre un mot de passe très compliqué mais réutilisé partout, et une phrase de passe plus longue, unique pour chaque service. Après avoir entendu parler d’une fuite, elle veut comprendre comment les mots de passe sont réellement attaqués avant de choisir une méthode."),
    videoSlot("Mots de passe : longueur, réutilisation et calculs simples"),
    text("On attaque les mots de passe de plusieurs façons. Il y a la devinette simple, le dictionnaire de mots courants, la force brute qui essaie toutes les combinaisons, le bourrage d’identifiants qui reteste ailleurs des couples déjà volés, l’hameçonnage qui les fait saisir sur un faux site, et l’enregistreur de frappe qui les vole au clavier. La défense change selon l’attaque : une bonne phrase de passe aide contre la force brute, mais elle ne sert plus à rien si tu la réutilises partout et qu’un autre service fuit."),
    figure({
      kind: "table",
      title: "Attaques sur les mots de passe et défense utile",
      columns: ["Attaque", "Ce qui aide à se défendre"],
      rows: [
        ["Dictionnaire", "Longueur, mots inattendus, blocage"],
        ["Force brute", "Phrase de passe longue, limite d’essais"],
        ["Bourrage d’identifiants", "Un mot de passe unique par service"],
        ["Hameçonnage", "Vérifier le site, utiliser un gestionnaire"],
        ["Enregistreur de frappe", "Poste sain, mises à jour, MFA"],
      ],
      highlight: 1,
    }),
    text("Un service sérieux ne stocke pas ton mot de passe en clair. Il stocke une empreinte, aussi appelée hachage, plus un sel aléatoire. Le sel évite que deux personnes ayant le même mot de passe aient la même empreinte, et il gêne les tables pré-calculées. Des algorithmes lents comme bcrypt ou Argon2 sont utilisés pour rendre chaque essai coûteux. Cela protège mieux une base volée, mais ne corrige ni un mot de passe trop faible ni sa réutilisation."),
    figure({
      kind: "formula",
      title: "Entropie approximative",
      items: [
        {
          label: "Alphabet de 62 caractères",
          formula: "bits = longueur × log2(taille de l’alphabet)",
          example: "62 caractères possibles : a-z A-Z 0-9\n8 caractères : 8 × log2(62) ≈ 47,6 bits\n12 caractères : 12 × log2(62) ≈ 71,5 bits",
          tone: "cyan",
        },
        {
          label: "Diceware, 7776 mots",
          formula: "bits = mots × log2(7776)",
          example: "5 mots ≈ 64,6 bits\n6 mots ≈ 77,5 bits",
          tone: "green",
        },
      ],
    }),
    text("La longueur compte plus que la complexité superficielle. Un mot de passe comme « azerty » ou « password » est très faible. Ajouter une majuscule et un chiffre à un mot courant ne suffit pas toujours, car les attaquants testent ces variantes. Une phrase de passe de plusieurs mots tirés au hasard est souvent meilleure, plus mémorisable et plus robuste. Le principe important est l’unicité : un mot de passe solide réutilisé devient faible dès qu’un autre service est compromis."),
    text("Démonstration guidée : calcule l’empreinte SHA-256 d’une chaîne de test pour voir qu’un petit changement suffit à produire un résultat très différent. Sous Linux, la commande « sha256sum » est directe. Sous PowerShell, tu peux passer par .NET. Si tu n’as qu’un téléphone, contente-toi de comparer les sorties déjà fournies et n’utilise jamais un vrai secret. Le but n’est pas de retenir la commande par cœur, mais de voir qu’une empreinte ne permet pas de retrouver facilement l’entrée d’origine."),
    code("# Linux\nprintf \"motdepasse\" | sha256sum\n\n# PowerShell\n[System.BitConverter]::ToString(\n  [System.Security.Cryptography.SHA256]::Create().ComputeHash(\n    [System.Text.Encoding]::UTF8.GetBytes(\"motdepasse\")\n  )\n).Replace(\"-\", \"\").ToLower()\n\n# Node.js\nnode -e \"console.log(require('crypto').createHash('sha256').update('motdepasse').digest('hex'))\"", "text"),
    text("Exemple numérique défensif : si un attaquant peut tester hypothétiquement 10 milliards de tentatives par seconde hors protections modernes, l’espace de 62 puissance 8 combinaisons représente 218340105584896 possibilités, soit environ 6,1 heures à parcourir entièrement dans le pire cas. Pour 62 puissance 12, on monte à environ 3,23 × 10 puissance 21 possibilités, soit environ 10 223 ans au même rythme. Dans la réalité, les services en ligne bloquent et ralentissent les essais, donc l’attaque directe en ligne est souvent bien plus lente que ce calcul de laboratoire. Le message à retenir reste simple : quelques caractères de plus changent énormément l’ordre de grandeur."),
    example("Exemple corrigé : Rokia compare deux choix. « abc123 » est faible, car il est court et très courant. Une phrase de passe de cinq mots tirés au hasard offre environ 64,6 bits d’entropie, déjà plus qu’un mot de passe de 8 caractères choisi dans un alphabet de 62 signes, qui tourne autour de 47,6 bits. Si Rokia utilise une phrase de passe unique par service et vérifie qu’elle n’est pas compromise, elle réduit à la fois le risque de devinette et celui de bourrage d’identifiants."),
    mistakes("réutiliser le même mot de passe partout ; croire qu’un mot courant modifié par un chiffre devient soudain robuste ; changer ses mots de passe sans raison mais en gardant toujours le même motif ; choisir un mot de passe fort puis le saisir sur un faux site d’hameçonnage."),
    safety("n’essaie jamais de casser des empreintes ou de tester des comptes qui ne t’appartiennent pas. Les calculs de cette leçon servent à comprendre les ordres de grandeur pour mieux se protéger, pas à attaquer des services réels."),
    takeaway("la longueur et l’unicité protègent mieux qu’une complexité décorative. Les services sérieux stockent des empreintes salées, mais cela n’excuse jamais la réutilisation. Une phrase de passe aléatoire, longue et unique, reste l’un des meilleurs choix pour un débutant."),
    practice("ouvre le laboratoire « TP 2 : auditer des mots de passe et des comptes » pour repérer des mots de passe faibles, la réutilisation et les entropies, puis ajoute le défi « Auditer l’hygiène des mots de passe » pour t’entraîner encore. Termine par le quiz de la leçon."),
    reference("cmMotsDePasse"),
    reference("cnilMotsDePasse"),
    reference("owaspPasswordStorage"),
  ],
  quiz: {
    title: "Quiz : mots de passe",
    questions: [
      questions.choice("Quelle pratique réduit le mieux le risque de bourrage d’identifiants après une fuite chez un autre service ?", ["Ajouter un point final au même mot de passe partout", "Changer uniquement le mot de passe du service fuité", "Utiliser un mot de passe unique pour chaque service", "Choisir toujours 8 caractères avec un chiffre"], 2, "Le bourrage d’identifiants réutilise des couples déjà volés sur d’autres sites. La seule vraie défense côté utilisateur est donc l’unicité par service. Changer un seul compte ou modifier légèrement le même secret laisse les autres services exposés.", "facile"),
      questions.tf("À sécurité égale, la longueur d’une phrase de passe compte souvent plus que l’ajout décoratif de symboles à un mot courant.", true, "Vrai : ajouter un symbole à un mot courant reste souvent prévisible, alors qu’augmenter réellement la longueur fait exploser le nombre de combinaisons possibles. Cela ne remplace pas l’unicité, mais améliore bien mieux la résistance à la force brute hors ligne.", "moyen"),
      questions.multi("Quelles affirmations sont justes ? Plusieurs réponses sont correctes.", ["Un service sérieux stocke plutôt une empreinte salée qu’un mot de passe en clair", "Réutiliser un mot de passe solide sur plusieurs sites reste dangereux", "Le bourrage d’identifiants exploite des identifiants déjà volés", "Un mot de passe comme « azerty » devient robuste si on le garde secret"], [0, 1, 2], "Le stockage par empreinte salée, l’unicité et la compréhension du bourrage d’identifiants sont des bases correctes. En revanche, « azerty » reste faible même s’il n’est connu de personne aujourd’hui, car il fait partie des premiers essais des attaquants.", "difficile"),
      questions.choice("Au rythme hypothétique de 10 milliards d’essais par seconde, quel ordre de grandeur est le plus proche pour parcourir 62 puissance 8 combinaisons ?", ["Environ 6 heures", "Environ 6 jours", "Environ 6 mois", "Environ 6 ans"], 0, "62 puissance 8 vaut 218340105584896. Divisé par 10 milliards d’essais par seconde, on obtient environ 21834 secondes, soit environ 6,1 heures. Le piège le plus tentant est de sous-estimer l’impact énorme d’un alphabet large, mais ici le calcul reste de l’ordre de quelques heures seulement.", "difficile"),
    ],
  },
};

const mfaLesson: NewLesson = {
  key: "fond-mfa",
  title: "Gestionnaires de mots de passe, double authentification et clés d’accès",
  summary: "S’équiper correctement avec un gestionnaire de mots de passe, choisir le bon second facteur et comprendre pourquoi les passkeys résistent mieux à l’hameçonnage que le SMS.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer ce qu’apporte un gestionnaire de mots de passe, distinguer les facteurs d’authentification, comparer SMS, TOTP et clés d’accès, choisir les comptes à protéger en priorité et appliquer une procédure simple si le téléphone est perdu."),
    prerequisites("avoir vu comment un mot de passe est attaqué et pourquoi il doit être long, unique et difficile à réutiliser après une fuite."),
    scenario("Amina a amélioré ses mots de passe, mais elle craint toujours l’hameçonnage et la perte de son téléphone. Elle voit passer plusieurs options : SMS, application de codes, notifications « approuver ? », gestionnaire de mots de passe et nouvelles clés d’accès. Elle veut une méthode simple pour décider quoi activer en premier."),
    videoSlot("MFA et passkeys : choisir la bonne protection pour ses comptes"),
    text("Un gestionnaire de mots de passe stocke tes secrets dans un coffre chiffré protégé par un mot de passe principal solide. Il peut générer des mots de passe uniques, les mémoriser et les remplir à ta place. Un avantage pratique compte aussi pour la sécurité : si le site n’est pas le bon, le gestionnaire refuse souvent de remplir. Des options gratuites comme Bitwarden ou KeePassXC rendent cette discipline réaliste même avec peu de moyens."),
    figure({
      kind: "cards",
      title: "Facteurs d’authentification",
      items: [
        { term: "Ce que je sais", text: "mot de passe, code PIN", tone: "blue" },
        { term: "Ce que j’ai", text: "téléphone, clé de sécurité", tone: "green" },
        { term: "Ce que je suis", text: "empreinte, visage", tone: "violet" },
      ],
      caption: "Double authentification = au moins deux facteurs différents.",
    }),
    text("Tous les seconds facteurs ne se valent pas. Le SMS reste le plus fragile : échange de carte SIM, interception ou simple persuasion téléphonique peuvent suffire. Une application TOTP, décrite par la RFC 6238, génère un code qui change en général toutes les 30 secondes à partir d’un secret partagé. HOTP, son ancêtre, avance lui avec un compteur et non avec l’heure. TOTP est mieux que le SMS, mais un faux site peut encore te demander le code en direct. Les notifications push sont confortables, mais elles exposent à la fatigue d’approbation si un attaquant bombarde de demandes."),
    figure({
      kind: "cards",
      title: "Comparer les méthodes",
      columns: 2,
      items: [
        { term: "SMS", text: "simple, mais fragile face au SIM swap et au social", tone: "red" },
        { term: "TOTP", text: "mieux, mais un faux site peut voler le code", tone: "amber" },
        { term: "Push", text: "pratique, mais risque de fatigue d’approbation", tone: "violet" },
        { term: "Clé d’accès", text: "liée au site, très résistante à l’hameçonnage", tone: "green" },
      ],
    }),
    text("Les clés de sécurité et les clés d’accès, aussi appelées passkeys, utilisent WebAuthn. Elles sont liées au site légitime : même si tu arrives sur un faux domaine, la clé ne valide pas. C’est leur grand avantage contre l’hameçonnage. Quand c’est disponible, protège d’abord les comptes qui ouvrent la porte aux autres : ta messagerie principale, les comptes de paiement, les réseaux sociaux, puis les comptes d’administration ou professionnels. Pense aussi aux codes de secours : imprime-les ou note-les hors de l’appareil."),
    text("Démonstration guidée : pour activer une application TOTP, cherche dans un compte l’écran « sécurité » ou « double authentification ». Choisis l’option d’application d’authentification, scanne le QR code avec l’application, saisis le code affiché et enregistre immédiatement les codes de secours. Si tu changes de téléphone, transfère les comptes ou réactive la méthode un service après l’autre avant d’effacer l’ancien appareil."),
    code("Étapes génériques\n1. Ouvrir Paramètres > Sécurité du compte\n2. Choisir « application d’authentification »\n3. Scanner le QR code avec l’application TOTP\n4. Saisir le code à 6 chiffres affiché\n5. Télécharger ou noter les codes de secours\n6. Tester une reconnexion avant de fermer l’écran", "text"),
    text("Si tu perds ton téléphone, ne panique pas : utilise d’abord les codes de secours, une seconde clé d’accès ou un appareil déjà connecté si le service le permet. Change ensuite ton mot de passe principal si la situation est floue, révoque les sessions actives, retire l’ancien téléphone des appareils de confiance et contacte l’opérateur si tu crains un échange de SIM. Là encore, la préparation fait gagner du temps."),
    example("Exemple corrigé : face à trois attaques différentes, les méthodes n’offrent pas la même résistance. Contre un échange de carte SIM, le SMS est faible alors que TOTP et une clé d’accès restent meilleurs. Contre un faux site de connexion, le TOTP peut encore être recopié par la victime, alors qu’une clé d’accès liée au site bloque l’attaque. Contre la fatigue d’approbation, les notifications push sont les plus exposées si l’utilisateur finit par accepter sans vérifier."),
    mistakes("activer la MFA sans sauvegarder les codes de secours ; protéger en priorité un réseau social secondaire mais pas sa messagerie principale ; approuver une notification push « pour voir » ; croire qu’un gestionnaire de mots de passe remplace à lui seul la double authentification."),
    safety("n’enrôle jamais ton second facteur sur un appareil prêté ou non maîtrisé. Conserve tes codes de secours hors du téléphone principal, et n’envoie jamais ces codes dans une messagerie non chiffrée ou à une autre personne."),
    takeaway("un bon gestionnaire rend les mots de passe uniques réalistes au quotidien. La double authentification améliore beaucoup la sécurité, mais le SMS reste le plus faible des choix courants. Quand elles sont disponibles, les clés d’accès apportent la meilleure résistance à l’hameçonnage."),
    practice("ouvre le laboratoire « TP 2 : auditer des mots de passe et des comptes » pour repérer les comptes les plus sensibles et les faiblesses d’authentification, puis termine par le quiz de la leçon."),
    reference("anssiMfa"),
    reference("rfc6238"),
    reference("webauthnGuide"),
  ],
  quiz: {
    title: "Quiz : MFA, gestionnaires et clés d’accès",
    questions: [
      questions.choice("Quelle méthode résiste le mieux à un faux site de connexion bien imité ?", ["Le SMS", "Le code TOTP", "La clé d’accès liée au site", "La notification push"], 2, "La clé d’accès, ou passkey, est liée au bon domaine et refuse normalement de s’authentifier sur un faux site. Le SMS et le TOTP peuvent encore être demandés puis saisis sur un site piégé, et la notification push ne corrige pas ce problème d’origine.", "facile"),
      questions.tf("Un code TOTP reste valable tant que tu ne fermes pas l’application qui l’affiche.", false, "Faux : un code TOTP change à intervalles réguliers, souvent toutes les 30 secondes. Fermer ou laisser ouverte l’application ne change pas ce principe. C’est précisément ce renouvellement qui limite la durée d’utilisation du code.", "moyen"),
      questions.multi("Quels comptes faut-il protéger en priorité par une double authentification ? Plusieurs réponses sont justes.", ["La messagerie principale", "Les comptes de paiement", "Les comptes d’administration ou professionnels", "Un compte peu utilisé dont tu peux perdre l’accès sans conséquence"], [0, 1, 2], "La messagerie principale sert souvent de clé de récupération pour les autres comptes. Le paiement et l’administration ont un impact direct important. Un compte secondaire sans conséquence est moins prioritaire, même s’il vaut mieux le protéger ensuite si possible.", "difficile"),
      questions.choice("Quel risque correspond le mieux aux notifications push ?", ["Le vol de la carte SIM", "La fatigue d’approbation", "L’impossibilité de générer un secret partagé", "L’absence de codes de secours"], 1, "La fatigue d’approbation survient quand un utilisateur reçoit beaucoup de demandes et finit par en valider une par lassitude. Le vol de carte SIM concerne plutôt le SMS. Les codes de secours restent recommandés, mais leur absence n’est pas le risque spécifique du push.", "difficile"),
    ],
  },
};

const breachesLesson: NewLesson = {
  key: "fond-fuites",
  title: "Fuites de données : vérifier, réagir, se protéger",
  summary: "Comprendre comment une fuite survient, ce que les attaquants réutilisent ensuite, puis appliquer un plan de réaction priorisé pour limiter les dégâts sur ses comptes personnels ou professionnels.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("expliquer comment une fuite de données arrive, identifier ce qui peut être réutilisé après la fuite, vérifier une adresse ou un mot de passe compromis sans l’exposer inutilement, prioriser les actions de réaction et éviter les erreurs les plus coûteuses."),
    prerequisites("avoir vu les bases des mots de passe et de la double authentification, afin de comprendre pourquoi la réutilisation aggrave l’impact d’une fuite."),
    scenario("Seydou reçoit une alerte disant que son adresse figure dans une fuite. Il ne sait pas si le message est fiable, ni s’il doit d’abord changer un mot de passe, prévenir sa banque ou ignorer l’avertissement. Comme il a utilisé le même mot de passe sur plusieurs services il y a quelques années, il doit agir dans le bon ordre."),
    videoSlot("Fuites de données : que faire dans la première heure"),
    text("Une fuite de données peut venir d’un serveur piraté, d’une erreur de configuration, d’un appareil perdu, d’un partage mal maîtrisé ou d’une personne interne malveillante ou négligente. Ce qui fuit n’est pas toujours la même chose : adresses de messagerie, numéros de téléphone, mots de passe hachés, dates de naissance, documents, relevés, réponses à des questions de sécurité. Même une fuite ancienne peut être réutilisée longtemps après, car les attaquants croisent les données et les revendent."),
    figure({
      kind: "cards",
      title: "Après une fuite, les données servent à",
      items: [
        { term: "Réutilisation", text: "tester la réutilisation sur d’autres sites", tone: "red" },
        { term: "Hameçonnage ciblé", text: "lancer un message plus crédible", tone: "amber" },
        { term: "Récupération", text: "répondre à des questions de récupération", tone: "violet" },
        { term: "Usurpation", text: "faire du chantage ou de l’usurpation", tone: "red" },
        { term: "Revente", text: "alimenter d’autres bases revendues", tone: "blue" },
      ],
    }),
    text("Pour vérifier une adresse, tu peux utiliser un service connu comme Have I Been Pwned. Pour un mot de passe, le principe utile est différent : on ne l’envoie pas en clair. Le service s’appuie sur une idée de k-anonymat. Seuls les 5 premiers caractères de l’empreinte SHA-1 sont envoyés, puis la comparaison complète se fait localement. Par exemple, l’empreinte SHA-1 de « password » commence par « 5BAA6 ». Ce préfixe seul ne suffit pas à reconstruire le secret complet."),
    text("Démonstration guidée : avec une chaîne de test, calcule une empreinte SHA-1 et regarde seulement ses 5 premiers caractères. Tu verras ainsi l’idée du k-anonymat sans utiliser ton vrai mot de passe. Si tu n’as qu’un téléphone, compare simplement le préfixe obtenu avec l’exemple ci-dessous. Si tu consultes un service de vérification, fais-le depuis le site officiel et avec un mot de passe de démonstration, jamais un secret réel que tu utilises encore."),
    code("node -e \"console.log(require('crypto').createHash('sha1').update('password').digest('hex').toUpperCase())\"\n# Résultat attendu : 5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8\n# Préfixe envoyé dans le modèle k-anonymat : 5BAA6", "text"),
    text("La réaction doit être priorisée. D’abord, identifie le service concerné et change immédiatement le mot de passe de ce service, puis de tous les autres comptes où il a été réutilisé. Active ensuite la double authentification, surveille les comptes financiers, méfie-toi des courriels très ciblés qui peuvent suivre la fuite, et mets à jour les réponses ou adresses de récupération si nécessaire. Si des données financières sont concernées, contacte rapidement la banque ou le service de paiement."),
    figure({
      kind: "steps",
      title: "Plan d’action priorisé",
      numbered: true,
      items: [
        { title: "Vérifier", text: "que l’alerte est légitime", tone: "cyan" },
        { title: "Changer", text: "le mot de passe du service touché", tone: "blue" },
        { title: "Changer partout", text: "où il a été réutilisé", tone: "amber" },
        { title: "Activer", text: "la double authentification", tone: "green" },
        { title: "Surveiller", text: "comptes, relevés et messages suspects", tone: "violet" },
      ],
    }),
    text("Une organisation a, elle aussi, des responsabilités : comprendre l’incident, protéger les personnes concernées, informer selon le cadre applicable et améliorer ses contrôles. Tu verras ce volet plus en détail dans le module sur les données personnelles et la conformité. Côté utilisateur, l’erreur la plus dangereuse reste d’ignorer l’alerte ou de ne changer qu’un seul mot de passe alors qu’il a été réutilisé ailleurs."),
    example("Exemple corrigé : Seydou reçoit une alerte fiable pour un ancien service. Il commence par changer le mot de passe de ce service, puis il dresse la liste des autres sites où il a réutilisé le même secret. Il change d’abord sa messagerie principale et ses comptes de paiement, active la double authentification, puis surveille ses relevés et les messages de récupération inhabituels. Il n’attend pas de voir un vol effectif pour agir."),
    mistakes("ignorer l’alerte parce que la fuite semble ancienne ; changer uniquement le mot de passe du service cité sans traiter la réutilisation ; entrer son vrai mot de passe sur un site de vérification non officiel ; payer un maître chanteur au lieu de signaler, sécuriser et demander de l’aide adaptée."),
    safety("si tu analyses une fuite dans un cadre professionnel, ne collecte pas plus de données que nécessaire et respecte la confidentialité. La vérification d’un mot de passe compromis doit se faire avec des méthodes prévues pour cela, jamais en partageant le secret réel avec d’autres personnes."),
    takeaway("une fuite devient grave surtout quand les mêmes secrets sont réutilisés ailleurs. Vérifie prudemment, puis agis par priorité : service touché, réutilisation, double authentification, surveillance. Plus la réaction est rapide et structurée, plus l’impact baisse."),
    practice("ouvre le laboratoire « TP 2 : auditer des mots de passe et des comptes » pour repérer la réutilisation et juger quelles actions lancer en premier après une fuite, puis termine par le quiz de la leçon."),
    reference("hibp"),
    reference("hibpPasswords"),
    reference("cnilViolations"),
  ],
  quiz: {
    title: "Quiz : fuites de données",
    questions: [
      questions.choice("Quelle action est la plus urgente si une alerte fiable indique qu’un ancien mot de passe réutilisé a fuité ?", ["Supprimer immédiatement toute sa boîte mail", "Changer d’abord le mot de passe du service touché puis de tous les comptes où il a été réutilisé", "Attendre un prélèvement suspect avant d’agir", "Répondre au message d’alerte pour demander des détails"], 1, "Le vrai danger vient de la réutilisation : il faut donc sécuriser le service touché puis tous les autres comptes partageant le même secret, en commençant par la messagerie principale et les paiements. Attendre ou répondre au message peut faire perdre un temps précieux.", "facile"),
      questions.tf("Dans le modèle de vérification de mots de passe compromis par k-anonymat, le service reçoit le mot de passe complet en clair.", false, "Faux : le principe consiste justement à ne pas envoyer le mot de passe complet. Seul un préfixe de l’empreinte est transmis, puis la comparaison complète se fait côté client, ce qui réduit l’exposition du secret.", "moyen"),
      questions.multi("Après une fuite, quels risques secondaires sont plausibles ? Plusieurs réponses sont justes.", ["Du bourrage d’identifiants sur d’autres sites", "Des messages d’hameçonnage plus crédibles", "La disparition automatique de toutes les traces de l’incident", "La réutilisation de réponses de récupération ou d’informations personnelles"], [0, 1, 3], "Une fuite alimente souvent d’autres attaques : réutilisation des identifiants, hameçonnage ciblé et abus de données personnelles pour la récupération de compte. En revanche, rien ne fait disparaître magiquement les traces, les copies ou la revente des données.", "difficile"),
      questions.choice("Quel raisonnement décrit le mieux l’intérêt du préfixe « 5BAA6 » dans l’exemple de l’empreinte SHA-1 de « password » ?", ["Il suffit à retrouver sûrement le mot de passe complet", "Il remplace la double authentification", "Il illustre qu’on peut interroger une base avec une partie de l’empreinte plutôt qu’avec le secret complet", "Il prouve que SHA-1 est recommandé pour stocker les mots de passe"], 2, "Le préfixe « 5BAA6 » sert à montrer l’idée du k-anonymat : on compare une partie de l’empreinte au lieu d’envoyer le mot de passe complet. Ce n’est ni une garantie de reconstruction du secret, ni une recommandation pour stocker des mots de passe avec SHA-1.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c1:3",
    position: 3,
    title: "Ingénierie sociale et hameçonnage",
    description: "Tu apprends ici à voir les attaques qui passent par l’humain avant de passer par la technique : appels, SMS, courriels, QR codes et faux prétextes. Critères de réussite : repérer un levier de manipulation dans un message ou un appel ; vérifier un expéditeur, un lien ou une demande d’argent par un second canal ; choisir une réaction sûre sans cliquer ni divulguer de secret.",
    lessons: [socialEngineeringLesson, phishingLesson, mobileScamsLesson],
  },
  {
    key: "c1:4",
    position: 4,
    title: "Mots de passe et authentification",
    description: "Ce module transforme la sécurité des comptes en méthode concrète : choisir de meilleurs secrets, ajouter le bon second facteur et réagir proprement après une fuite. Critères de réussite : expliquer pourquoi la réutilisation est dangereuse ; comparer SMS, TOTP et clés d’accès selon le risque ; appliquer un plan d’action priorisé après une alerte de fuite.",
    lessons: [passwordsLesson, mfaLesson, breachesLesson],
  },
];
