import {
  code, example, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const misesAJourLesson: NewLesson = {
  key: "fond-mises-a-jour",
  title: "Mises à jour, antivirus et surface d’attaque",
  summary: "Comprends pourquoi les correctifs, l’antivirus, le pare-feu local et le compte standard réduisent la fenêtre d’exposition d’un appareil du quotidien.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer pourquoi une mise à jour corrige une vulnérabilité, distinguer système, application, navigateur, micrologiciel et routeur, vérifier l’état d’un poste, calculer un retard moyen de correctif, et proposer des actions simples pour réduire la surface d’attaque."),
    prerequisites("aucun. Savoir ouvrir les réglages d’un téléphone ou d’un ordinateur suffit."),
    scenario("Kwame aide la coopérative Harmattan, qui utilise cinq ordinateurs et plusieurs téléphones. Un poste sert encore pour la comptabilité alors que son navigateur n’a pas été mis à jour depuis longtemps. Un autre a deux antivirus installés en même temps. Kwame doit expliquer ce qui protège vraiment l’équipe, sans jargon inutile."),
    videoSlot("Mettre à jour sans paniquer : les bons réflexes sur ordinateur et téléphone"),
    text("Une mise à jour de sécurité corrige une vulnérabilité, c’est-à-dire une faiblesse exploitable dans un logiciel ou un appareil. Tant que le correctif n’est pas appliqué, la fenêtre d’exposition reste ouverte. Cela concerne le système, les applications, le navigateur, le téléphone et le micrologiciel d’un routeur ou d’une box. Un système en fin de support reste plus risqué : il fonctionne encore, mais ne reçoit plus les correctifs nécessaires."),
    schema("Élément à suivre         Exemple\nSystème                 Windows, Android, Ubuntu\nApplications            lecteur PDF, suite bureautique\nNavigateur              Firefox, Edge, Chrome\nMicrologiciel           box, routeur, imprimante\nÉtat critique           pris en charge ou fin de support"),
    text("Les mises à jour automatiques sont utiles, surtout pour les correctifs critiques, parce qu’elles raccourcissent le temps entre la publication d’une faille et sa correction. Lors de la propagation de WannaCry en 2017, le correctif existait déjà depuis environ deux mois. Il faut aussi télécharger depuis la source officielle : les logiciels piratés ou récupérés sur des sites douteux augmentent la surface d’attaque, c’est-à-dire le nombre de portes par lesquelles un attaquant peut entrer."),
    schema("Réduire la surface d’attaque\n1. désinstaller ce qui ne sert plus\n2. désactiver extensions et services inutiles\n3. garder un seul antivirus à la fois\n4. utiliser le pare-feu local\n5. travailler avec un compte standard"),
    text("Un antivirus aide, mais il n’est pas magique. Il repère des menaces connues par signature et certains comportements suspects. Deux antivirus actifs en même temps se gênent souvent. Sous Windows, Microsoft Defender offre déjà une base utile quand il est à jour. Le pare-feu local complète cette défense, et un compte standard limite les dégâts : un logiciel sans droits d’administration peut modifier moins de choses."),
    text("Démonstration guidée : sur Windows, tu peux vérifier d’un coup l’état de l’antivirus intégré. Sur Debian ou Ubuntu, tu peux lister les paquets à mettre à jour. L’idée n’est pas de devenir administrateur système en une minute, mais d’apprendre à regarder des indices concrets plutôt qu’à supposer que « tout va bien » parce que l’écran s’allume."),
    code("Get-MpComputerStatus | Select-Object AMServiceEnabled,AntivirusEnabled,AntivirusSignatureLastUpdated\n\n# Exemple de sortie\n# AMServiceEnabled              : True\n# AntivirusEnabled              : True\n# AntivirusSignatureLastUpdated : <date et heure récentes>\n\n# Debian ou Ubuntu\napt list --upgradable", "powershell"),
    example("Exemple corrigé : les cinq postes de Sahel Services ont 3, 7, 12, 20 et 28 jours de retard sur leurs mises à jour critiques. Le retard moyen vaut 14 jours, car (3 + 7 + 12 + 20 + 28) ÷ 5 = 14. Le poste à 28 jours n’est pas seulement « un peu en retard » : il tire la moyenne vers le haut et doit devenir prioritaire, avec celui à 20 jours."),
    mistakes("laisser un système sans support « tant qu’il démarre encore » ; installer les logiciels depuis des sources non officielles ; croire qu’un antivirus remplace les correctifs ; travailler tous les jours avec un compte administrateur alors qu’un compte standard suffit dans la plupart des cas."),
    safety("n’installe jamais un correctif ou un antivirus téléchargé depuis un site non officiel. Sur un parc d’entreprise ou d’association, applique les procédures internes et vérifie les sauvegardes avant un changement important."),
    takeaway("les correctifs réduisent la fenêtre d’exposition, mais seulement s’ils sont appliqués. Un antivirus à jour, un pare-feu actif, peu de logiciels inutiles et un compte standard changent beaucoup. Un appareil en fin de support doit être remplacé ou isolé."),
    practice("ouvre le laboratoire « TP 3 : auditer l’hygiène d’un parc de postes », calcule les retards de mises à jour, vérifie l’état de l’antivirus et repère les postes qui augmentent la surface d’attaque. Termine par le quiz de la leçon."),
    reference("cmMisesAJour"),
    reference("cmAntivirus"),
  ],
  quiz: {
    title: "Quiz : mises à jour et hygiène de poste",
    questions: [
      questions.choice("Pourquoi un système en fin de support pose-t-il un problème de sécurité ?", ["Parce qu’il consomme plus d’électricité", "Parce qu’il ne reçoit plus de correctifs de sécurité", "Parce qu’il refuse de lancer un navigateur", "Parce qu’il bloque automatiquement les sauvegardes"], 1, "Le risque principal vient de l’absence de correctifs : une faille connue peut rester exploitable pendant des mois. Le piège tentant est de croire qu’un système encore fonctionnel est forcément encore protégé, ce qui est faux.", "facile"),
      questions.tf("Installer deux antivirus actifs en même temps améliore presque toujours la protection d’un poste.", false, "Faux : deux antivirus actifs se gênent souvent, ralentissent la machine et peuvent produire des conflits de détection. Le vrai gain vient d’un seul outil bien configuré, à jour, complété par les correctifs et le pare-feu local.", "moyen"),
      questions.multi("Quelles actions réduisent réellement la surface d’attaque d’un poste ? (plusieurs réponses)", ["Désinstaller les logiciels inutiles", "Désactiver des services ou extensions non utilisés", "Télécharger les mises à jour depuis un site tiers plus rapide", "Utiliser un compte standard au quotidien"], [0, 1, 3], "Retirer l’inutile, limiter les services actifs et travailler sans droits d’administration réduisent les possibilités d’abus. Le faux bon choix est le site tiers : même rapide, il ajoute un risque de logiciel modifié ou piégé.", "difficile"),
      questions.choice("Un parc affiche des retards de 3, 7, 12, 20 et 28 jours. Quel poste faut-il traiter en premier si tu ne peux en corriger qu’un maintenant ?", ["Celui à 7 jours", "Celui à 12 jours", "Celui à 20 jours", "Celui à 28 jours"], 3, "Le poste à 28 jours cumule la plus grande fenêtre d’exposition et doit donc être prioritaire. La moyenne du parc aide à piloter l’ensemble, mais elle ne remplace pas le traitement du cas le plus en retard.", "moyen"),
    ],
  },
};

const sauvegardesLesson: NewLesson = {
  key: "fond-sauvegardes",
  title: "Sauvegardes : la règle 3-2-1 et le test de restauration",
  summary: "Apprends à distinguer sauvegarde, synchronisation et archivage, puis à planifier une stratégie 3-2-1 qui résiste aussi aux rançongiciels.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer sauvegarde, synchronisation et archivage, expliquer la règle 3-2-1, comparer complète, incrémentale et différentielle, calculer un besoin d’espace, et vérifier qu’une restauration est réellement possible."),
    prerequisites("avoir suivi « Mises à jour, antivirus et surface d’attaque » ou déjà connaître le risque de perte, de panne et de rançongiciel."),
    scenario("Awa gère les documents de la coopérative Harmattan. Ses fichiers sont aussi synchronisés sur un téléphone et un ordinateur portable. Un lundi matin, un logiciel malveillant chiffre le dossier partagé. Awa découvre alors qu’une synchronisation n’est pas une vraie sauvegarde : le fichier chiffré a été recopié partout."),
    videoSlot("Sauvegarder sans se mentir : copies, restauration et règle 3-2-1"),
    text("Une sauvegarde sert à retrouver des données perdues, supprimées ou modifiées. Une synchronisation recopie l’état actuel entre plusieurs appareils. Un archivage conserve des informations sur une longue durée. Ces trois notions se ressemblent, mais ne répondent pas au même besoin. Si un rançongiciel chiffre un dossier synchronisé, toutes les copies connectées peuvent propager le problème. Une vraie sauvegarde doit donc être séparée dans le temps, et au moins parfois séparée du réseau."),
    schema("But principal          Exemple\nSauvegarde             récupérer après panne, erreur, attaque\nSynchronisation        retrouver les mêmes fichiers partout\nArchivage              conserver longtemps, même peu consulté"),
    text("La règle 3-2-1 est un bon repère : 3 copies de tes données, sur 2 supports différents, dont 1 copie hors site. Pour les rançongiciels, une copie hors ligne ou immuable est encore meilleure : hors ligne signifie déconnectée, immuable signifie difficile à modifier avant la date prévue. Les sauvegardes sensibles doivent aussi être chiffrées, car une fuite de sauvegarde reste une fuite de données."),
    schema("Types de sauvegarde\nComplète       tout recopier\nIncrémentale   recopier ce qui a changé depuis la dernière sauvegarde\nDifférentielle recopier ce qui a changé depuis la dernière complète"),
    text("Le choix du type agit sur l’espace et sur le temps de restauration. Une complète est simple à restaurer, mais elle consomme plus d’espace. Une incrémentale est économe, mais elle exige souvent la complète initiale et toute la chaîne des changements. Une différentielle grossit au fil des jours, mais reste plus simple à restaurer qu’une longue chaîne d’incrémentales. Deux questions guident le choix : combien de données peux-tu perdre, ce qu’on appelle souvent le point de reprise, et combien de temps peux-tu rester à l’arrêt, c’est-à-dire la durée de reprise acceptable."),
    text("Démonstration guidée : avant une vraie copie, lance un test à blanc. Sous Linux ou macOS, « rsync -av --dry-run » montre ce qui serait copié sans rien modifier. Sous Windows, « robocopy » sert souvent au même type d’automatisation. Le point important est de vérifier ce qui va partir et ce qui va arriver avant d’utiliser des options destructrices."),
    code("# Linux ou macOS : test à blanc\nrsync -av --dry-run Documents/ sauvegarde/Documents/\n\n# Windows : exemple simple\nrobocopy Documents D:\\Sauvegardes\\Documents /MIR /L\n\n# /L affiche ce qui serait copié sans écrire\n# Évite d’ajouter une suppression sans avoir testé d’abord.", "bash"),
    example("Exemple corrigé : Awa stocke 80 Gio de données. Chaque semaine, elle fait une complète de 80 Gio. Chaque jour ouvré, elle produit environ 4 Gio de nouveaux fichiers ou de changements. Sur 4 semaines, avec 4 complètes et 20 incrémentales, il faut 400 Gio, car 4 × 80 + 20 × 4 = 320 + 80 = 400 Gio. Si sa dernière restauration de 1 250 Mo prend 25 minutes à 50 Mo par minute, sa durée de reprise est d’au moins 25 minutes pour ce lot précis."),
    mistakes("confondre dossier synchronisé et sauvegarde ; conserver toutes les copies branchées en permanence, donc exposées au même rançongiciel ; ne jamais tester de restauration ; oublier de sauvegarder aussi les configurations, les codes de secours et les clés nécessaires au redémarrage."),
    safety("ne restaure jamais par-dessus les données encore présentes sans avoir vérifié la source et la date de la sauvegarde. Dans une structure, documente qui peut lancer une restauration et garde les clés de chiffrement hors de l’appareil sauvegardé."),
    takeaway("une stratégie utile protège contre la panne, l’erreur humaine et l’attaque. La règle 3-2-1 donne une base solide, mais elle ne vaut que si tu testes la restauration. Une sauvegarde que tu n’as jamais restaurée est une promesse, pas une preuve."),
    practice("ouvre le laboratoire « TP 3 : auditer l’hygiène d’un parc de postes », vérifie si la règle 3-2-1 est respectée dans les journaux fournis et juge si les sauvegardes semblent réellement restaurables. Termine par le quiz de la leçon."),
    reference("cmSauvegardes"),
    reference("cnilSauvegarder"),
  ],
  quiz: {
    title: "Quiz : sauvegardes et restauration",
    questions: [
      questions.choice("Quelle phrase décrit le mieux une sauvegarde ?", ["Une copie prévue pour restaurer après une perte, une erreur ou une attaque", "Une duplication instantanée qui garde partout le même état actuel", "Un simple déplacement de fichiers vers une autre clé USB", "Un moyen d’éviter toutes les mises à jour de sécurité"], 0, "Une sauvegarde vise la récupération après incident. La réponse qui ressemble le plus, la synchronisation, recopie surtout l’état courant et peut donc propager une suppression ou un chiffrement non désiré.", "facile"),
      questions.tf("Si tes fichiers sont synchronisés sur deux appareils, tu respectes déjà automatiquement la règle 3-2-1.", false, "Faux : deux appareils synchronisés peuvent partager la même panne logique ou la même corruption. La règle 3-2-1 demande plusieurs copies, des supports différents et une copie hors site, pas seulement deux dossiers qui se suivent.", "moyen"),
      questions.multi("Quelles pratiques renforcent vraiment la capacité de restauration ? (plusieurs réponses)", ["Conserver une copie hors ligne ou immuable", "Chiffrer les sauvegardes sensibles", "Tester régulièrement une restauration", "Brancher en permanence tous les disques de sauvegarde au même poste"], [0, 1, 2], "Une copie séparée, un chiffrement adapté et un test de restauration réduisent le risque de mauvaise surprise. L’option tentante mais fausse est de tout laisser branché : c’est pratique, mais cela expose toutes les copies au même incident.", "difficile"),
      questions.choice("Tu planifies 4 sauvegardes complètes de 80 Gio et 24 incrémentales de 4 Gio. Quel espace total dois-tu prévoir ?", ["176 Gio", "320 Gio", "416 Gio", "640 Gio"], 2, "Le calcul correct est 4 × 80 + 24 × 4 = 320 + 96 = 416 Gio. Le piège le plus courant consiste à oublier les incrémentales ou à les compter comme des complètes, ce qui fausse complètement le dimensionnement.", "moyen"),
    ],
  },
};

const chiffrementAppareilsLesson: NewLesson = {
  key: "fond-chiffrement-appareils",
  title: "Chiffrer ses appareils et se protéger sur le Wi-Fi",
  summary: "Protège tes appareils volés ou perdus grâce au chiffrement complet, puis adopte les bons réflexes sur le Wi-Fi domestique et public.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer à quoi sert le chiffrement complet du disque, choisir un verrouillage d’écran solide, sécuriser un Wi-Fi domestique, évaluer un Wi-Fi public, et décider quand un VPN aide vraiment ou non."),
    prerequisites("avoir vu les bases des mises à jour et des sauvegardes, ou utiliser déjà un téléphone et un Wi-Fi au quotidien."),
    scenario("Fatou rentre d’un atelier avec son ordinateur portable et son téléphone. Dans le taxi, elle remarque trop tard que le sac a disparu. Le soir même, elle doit répondre à deux questions : un inconnu peut-il lire ses fichiers si l’appareil est éteint, et que vaut le Wi-Fi public utilisé la veille dans un café ?"),
    videoSlot("Téléphone perdu, Wi-Fi public : les protections qui comptent vraiment"),
    text("Le chiffrement complet du disque protège les données stockées quand un appareil est perdu ou volé. Sans la clé liée à ton mot de passe ou à ton code, le contenu reste illisible. Sur Windows, BitLocker remplit ce rôle. Sur macOS, on parle de FileVault. Sur Linux, LUKS est fréquent. Sur iPhone et sur beaucoup de téléphones Android récents, le stockage est chiffré quand un verrouillage d’écran est activé. Si l’appareil est déjà déverrouillé, le chiffrement aide beaucoup moins."),
    schema("Vol ou perte              Ce qui aide\nAppareil éteint           chiffrement complet + code solide\nAppareil déverrouillé     verrouillage rapide + effacement distant\nCompte lié à l’appareil   localisation + changement du mot de passe\nClé de récupération       copie hors de l’appareil"),
    text("Le code de déverrouillage doit être solide et différent des chiffres évidents comme 123456. La clé de récupération doit être conservée hors de l’appareil, par exemple imprimée ou notée dans un coffre numérique. Active aussi la fonction de localisation et d’effacement à distance quand elle existe. Perdre un téléphone peut exposer tes messages, tes photos, tes codes de secours et parfois tes accès professionnels."),
    text("Le Wi-Fi domestique mérite aussi de l’attention. Change le mot de passe d’administration de la box, active WPA2 ou WPA3, et coupe WPS si tu n’en as pas besoin. Sur un Wi-Fi public, le risque principal vient des faux points d’accès et des autres personnes sur le même réseau. HTTPS protège surtout le trajet vers le site visité, mais il ne masque pas tout le contexte et ne corrige pas un mauvais domaine. Un VPN peut chiffrer le trajet jusqu’au service VPN, mais il ne transforme pas un service malveillant en service honnête. Si tu veux aller plus loin sur le durcissement du Wi-Fi, le parcours Réseaux traite aussi ce sujet."),
    schema("À la maison              Dans un lieu public\nWPA2 ou WPA3             préférer HTTPS partout\nmot de passe box changé  éviter les opérations sensibles si possible\nWPS désactivé            se méfier des faux points d’accès\nappareils à jour         ne pas faire confiance au réseau seul"),
    text("Démonstration guidée : sur Windows, « netsh wlan show interfaces » affiche le nom du réseau, la bande et le type d’authentification. Si tu es administrateur, « manage-bde -status C: » indique l’état de BitLocker. Sur téléphone, ouvre les réglages de sécurité pour vérifier qu’un code protège bien l’appareil."),
    code("netsh wlan show interfaces\n\n# Exemple de sortie utile\n# SSID            : MonWiFiMaison\n# Authentification: WPA2 - Personnel\n# Chiffrement     : CCMP\n\nmanage-bde -status C:\n# Si BitLocker est actif, l’état du volume et la protection s’affichent.", "powershell"),
    example("Exemple corrigé : 1) ordinateur personnel à la maison sur WPA3 et système à jour : situation sûre ; 2) téléphone sans code sur le Wi-Fi d’un café : très risqué ; 3) portable chiffré, mais connecté à un faux point d’accès « WiFi Gratuit » pour saisir un mot de passe professionnel : le chiffrement du disque n’empêche pas l’hameçonnage ; 4) tablette en recharge sur une borne publique avec un câble inconnu : prudence. La réponse dépend du stockage, du réseau et du contexte."),
    mistakes("croire qu’un cadenas dans le navigateur suffit à rendre un Wi-Fi public sûr ; stocker la clé de récupération sur l’appareil lui-même ; laisser le mot de passe d’administration de la box tel qu’à l’achat ; penser qu’un VPN gratuit protège automatiquement mieux qu’un service sérieux bien configuré."),
    safety("n’emprunte pas un compte ni une connexion d’administration qui ne t’appartiennent pas pour « vérifier vite ». Sur un appareil professionnel, applique la politique de l’organisation et signale immédiatement toute perte ou tout vol."),
    takeaway("le chiffrement complet protège surtout un appareil éteint ou verrouillé. Un bon code, une clé de récupération séparée et l’effacement distant sont indispensables. Sur le Wi-Fi, protège la maison par une configuration correcte et traite les réseaux publics comme peu fiables."),
    practice("ouvre le laboratoire « TP 3 : auditer l’hygiène d’un parc de postes », repère quels postes sont chiffrés et lesquels restent exposés en cas de vol. Termine par le quiz de la leçon."),
    reference("msBitlocker"),
    reference("anssiWifi"),
  ],
  quiz: {
    title: "Quiz : chiffrement des appareils et Wi-Fi",
    questions: [
      questions.choice("Que protège d’abord le chiffrement complet du disque ?", ["Les données stockées quand l’appareil est perdu ou volé", "La qualité du signal Wi-Fi", "La vitesse de la sauvegarde", "La validité d’un certificat HTTPS"], 0, "Le chiffrement complet vise la confidentialité des données au repos sur l’appareil. L’erreur la plus tentante est de lui attribuer des pouvoirs réseau qu’il n’a pas : il ne remplace ni HTTPS, ni un pare-feu, ni une bonne prudence sur le Wi-Fi.", "facile"),
      questions.tf("Si un site affiche HTTPS, le Wi-Fi public utilisé devient automatiquement digne de confiance pour tout le reste.", false, "Faux : HTTPS protège surtout l’échange avec ce site précis, pas l’ensemble du réseau local ni les autres services. Un faux point d’accès, une mauvaise application ou une opération sensible sur un mauvais site restent dangereux.", "moyen"),
      questions.multi("Quels réflexes améliorent vraiment la sécurité d’un Wi-Fi domestique ? (plusieurs réponses)", ["Changer le mot de passe d’administration de la box", "Activer WPA2 ou WPA3", "Désactiver WPS si tu n’en as pas besoin", "Laisser la clé de récupération de l’ordinateur dans le dossier Téléchargements"], [0, 1, 2], "Changer l’administration, choisir un chiffrement moderne et retirer WPS quand il est inutile réduisent les risques. Le faux bon choix est de garder la clé de récupération sur l’appareil : en cas de vol, elle accompagne précisément ce qu’elle devrait protéger.", "difficile"),
      questions.choice("Quelle situation est la plus préoccupante ?", ["Un portable chiffré et verrouillé, oublié à la maison", "Un téléphone sans code de déverrouillage utilisé sur un Wi-Fi public", "Une box à jour avec WPA3 activé", "Un ordinateur chiffré avec clé de récupération rangée hors ligne"], 1, "Le téléphone sans code cumule risque physique et exposition réseau : l’accès local devient presque immédiat. Les autres situations restent plus maîtrisées, même si aucune configuration n’est parfaite sans vigilance continue.", "moyen"),
    ],
  },
};

const cryptoBasesLesson: NewLesson = {
  key: "fond-crypto-bases",
  title: "Chiffrer, encoder, hacher : ne plus confondre",
  summary: "Distingue enfin trois opérations souvent mélangées, puis reconnais quand une donnée a été encodée, chiffrée ou condensée en empreinte.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("différencier encodage, chiffrement et hachage, définir texte en clair, texte chiffré et clé, appliquer le principe de Kerckhoffs, reconnaître une empreinte courante, et utiliser une petite démonstration Base64 et SHA-256."),
    prerequisites("aucun. Il suffit de savoir qu’un message peut être transformé avant d’être transmis ou stocké."),
    scenario("Amina reçoit trois informations différentes : une chaîne « Qm9uam91cg== », un fichier accompagné d’une longue empreinte hexadécimale, et un message présenté comme « chiffré » alors qu’il suffit de décaler les lettres. Elle comprend vite que tout ce qui change l’apparence d’un texte n’a pas le même but. Pour se protéger, elle doit savoir quel outil répond à quel problème."),
    videoSlot("Encodage, chiffrement, hachage : trois outils, trois usages"),
    text("Encoder, chiffrer et hacher servent à des objectifs différents. L’encodage transforme des données pour les rendre compatibles avec un format ou un canal. Base64 et l’hexadécimal sont réversibles sans secret : ce n’est pas du chiffrement. Chiffrer vise la confidentialité : on part d’un texte en clair, on applique un algorithme et une clé, et on obtient un texte chiffré. Hacher produit une empreinte à sens unique, utile pour l’intégrité et le stockage prudent des mots de passe."),
    schema("Besoin                    Outil\ntransporter ou afficher    encodage\ncacher le contenu          chiffrement\nvérifier l’intégrité       hachage"),
    text("Le principe de Kerckhoffs dit qu’un système doit rester sûr même si tout le monde connaît l’algorithme, sauf la clé. Cacher l’algorithme ne suffit donc pas. Le chiffre de César et ROT13 sont utiles pour apprendre, mais ils sont faibles. À l’inverse, un chiffrement moderne comme AES est conçu pour résister à ces approches quand la clé est bien choisie et protégée."),
    schema("Vocabulaire utile\nTexte en clair   message lisible avant chiffrement\nTexte chiffré    message protégé par une clé\nClé              secret ou paramètre qui permet de chiffrer ou déchiffrer\nEmpreinte        résultat fixe d’une fonction de hachage"),
    text("Une bonne fonction de hachage est déterministe, rapide à calculer, produit un effet d’avalanche et doit rendre les collisions difficiles à trouver. L’effet d’avalanche signifie qu’un petit changement dans l’entrée transforme fortement la sortie. Pour la sécurité moderne, MD5 et SHA-1 sont à éviter. SHA-256 reste courant. Quand on protège des mots de passe, on ajoute aussi un sel, c’est-à-dire une valeur aléatoire différente pour chaque mot de passe, afin d’éviter que deux utilisateurs ayant le même secret aient la même empreinte stockée."),
    text("Démonstration guidée : avec Node.js, « Bonjour » encodé en Base64 donne « Qm9uam91cg== ». Ensuite, calcule une empreinte SHA-256 pour « Bonjour » puis pour « BonjouR ». Une seule lettre change, mais les deux empreintes n’ont presque rien en commun visuellement : c’est l’effet d’avalanche. Cette démonstration aide à reconnaître les transformations."),
    code("node -e \"console.log(Buffer.from('Bonjour').toString('base64'))\"\n# Qm9uam91cg==\n\nnode -e \"const crypto=require('node:crypto'); console.log(crypto.createHash('sha256').update('Bonjour').digest('hex'))\"\n# 9172e8eec99f144f72eca9a568759580edadb2cfd154857f07e657569493bc44\n\nnode -e \"const crypto=require('node:crypto'); console.log(crypto.createHash('sha256').update('BonjouR').digest('hex'))\"\n# 68507c350137bf38f0f1bcc1bf8bf08c79d296ff5b194246c01a6b8fb701718d", "bash"),
    example("Exemple corrigé : une chaîne hexadécimale de 32 caractères évoque MD5, 40 caractères évoquent SHA-1, et 64 caractères évoquent SHA-256. Si tu vois « Qm9uam91cg== », tu reconnais plutôt du Base64 que du chiffrement. Pour vérifier un fichier téléchargé, compare l’empreinte publiée avec celle que tu calcules localement : si elles diffèrent, le fichier a changé."),
    mistakes("dire « c’est chiffré » dès qu’un texte semble illisible ; croire que Base64 protège un secret ; utiliser encore MD5 ou SHA-1 pour un besoin de sécurité moderne ; oublier le sel quand on parle de stockage prudent des mots de passe."),
    safety("n’utilise ces notions que pour protéger, vérifier ou comprendre. Les exemples de César et de ROT13 sont pédagogiques et ne doivent pas servir à attaquer un système réel ou à contourner une protection."),
    takeaway("encodage, chiffrement et hachage répondent à trois questions différentes. Base64 transporte, AES protège la confidentialité, SHA-256 aide à vérifier l’intégrité. Un algorithme connu n’est pas un problème si la clé reste secrète et si le système a été bien conçu."),
    practice("ouvre le laboratoire « TP 4 : intégrité, chiffrement et certificats », vérifie des empreintes SHA-256, décode du Base64 et compare les résultats avec le défi « Casser un chiffrement de César ». Termine par le quiz de la leçon."),
    reference("rfc4648"),
    reference("wikiSha2"),
  ],
  quiz: {
    title: "Quiz : encodage, chiffrement et hachage",
    questions: [
      questions.choice("Quel outil répond d’abord à un besoin de confidentialité ?", ["Le chiffrement", "L’encodage Base64", "Le hachage SHA-256", "L’écriture hexadécimale"], 0, "Le chiffrement protège le contenu contre une lecture non autorisée. Base64 et l’hexadécimal sont réversibles sans secret, tandis que le hachage produit une empreinte utile pour l’intégrité mais pas pour relire le message.", "facile"),
      questions.tf("Une chaîne Base64 doit être considérée comme secrète, car elle ne peut être lue qu’avec une clé.", false, "Faux : Base64 est un encodage réversible sans clé, utilisé pour transporter ou représenter des données. Le piège courant consiste à confondre apparence inhabituelle et protection cryptographique réelle.", "moyen"),
      questions.multi("Quelles affirmations sont correctes ? (plusieurs réponses)", ["Le principe de Kerckhoffs suppose que l’algorithme peut être public", "SHA-256 produit souvent 64 caractères hexadécimaux", "MD5 est recommandé pour une signature moderne", "Un sel aide à distinguer les empreintes de mots de passe identiques"], [0, 1, 3], "Un bon système reste sûr même si l’algorithme est connu, SHA-256 s’écrit souvent sur 64 caractères hexadécimaux, et le sel empêche des égalités trop révélatrices. MD5 est le piège classique : il est encore vu partout, mais il n’est plus recommandé pour ce rôle.", "difficile"),
      questions.choice("Tu vois la chaîne « Qm9uam91cg== ». Quelle interprétation est la plus probable ?", ["Un mot de passe haché en SHA-256", "Un texte encodé en Base64", "Un certificat X.509 expiré", "Une clé publique RSA"], 1, "Cette chaîne correspond très bien à un encodage Base64, ici celui de « Bonjour ». L’option la plus tentante mais fausse est le hachage : une empreinte SHA-256 aurait une forme hexadécimale beaucoup plus longue.", "moyen"),
    ],
  },
};

const clesSignaturesLesson: NewLesson = {
  key: "fond-cles-signatures",
  title: "Clés secrètes, clés publiques et signatures numériques",
  summary: "Découvre la différence entre chiffrement symétrique et asymétrique, puis comprends comment une signature numérique prouve l’origine et l’intégrité d’un document.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer chiffrement symétrique et asymétrique, expliquer le problème du partage de clé, décrire le principe d’une signature numérique, protéger une clé privée, et lire une démonstration OpenSSL sans te perdre dans les mathématiques."),
    prerequisites("avoir suivi « Chiffrer, encoder, hacher : ne plus confondre » ou déjà savoir ce qu’est une clé et une empreinte."),
    scenario("Désiré doit envoyer un contrat à Atlas sans qu’on puisse le modifier discrètement. Il entend parler de clés secrètes, de clés publiques, de signatures et de TLS, mais tout semble mélangé. Son besoin est pourtant simple : savoir qui peut lire, qui peut prouver l’origine, et quelle clé ne doit jamais quitter sa poche numérique."),
    videoSlot("Clés publiques, clés privées et signatures sans formules compliquées"),
    text("Le chiffrement symétrique utilise une seule clé pour chiffrer et déchiffrer. Il est rapide, ce qui le rend utile pour protéger un grand volume de données. Son problème principal est le partage de la clé. Le chiffrement asymétrique répond à ce point avec une paire de clés : une clé publique que l’on peut diffuser, et une clé privée qui doit rester secrète. Ce mécanisme est plus coûteux en calcul, mais très pratique pour établir la confiance initiale."),
    schema("Type                    Avantage principal         Limite principale\nSymétrique              rapide                      partage de la clé\nAsymétrique             pas besoin de secret initial plus lent\nHybride                 combine les deux            demande une bonne mise en œuvre"),
    text("En pratique, beaucoup de protocoles modernes utilisent un modèle hybride. On emploie l’asymétrique pour établir ou protéger une clé de session, puis on bascule sur du symétrique pour échanger les données courantes. C’est l’idée générale de TLS. Les clés SSH reposent aussi sur cette logique pour éviter d’envoyer un mot de passe à chaque connexion."),
    text("Signer numériquement n’est pas la même chose que chiffrer. Pour signer, on calcule d’abord l’empreinte du document, puis on la signe avec la clé privée. La vérification se fait avec la clé publique. Si la vérification réussit, on obtient trois garanties utiles : le document n’a pas été modifié depuis la signature, il provient de la personne ou du service possédant la clé privée, et cette personne aura du mal à nier l’opération si la clé a été bien protégée. La clé privée ne se partage jamais. Pour RSA, une taille de 2048 bits ou plus reste un minimum courant ; les courbes elliptiques offrent une autre famille de clés plus compactes."),
    schema("Signature numérique\nDocument -> empreinte -> signature avec clé privée\n\nVérification\nDocument reçu -> empreinte recalculée\nsignature + clé publique -> résultat : valide ou non"),
    text("Démonstration guidée : si OpenSSL est installé, les commandes suivantes génèrent une clé RSA de 2048 bits, extraient la clé publique, signent un fichier puis vérifient la signature. Si la dernière ligne répond « Verified OK », la signature correspond bien au fichier et à la paire de clés utilisée."),
    code("openssl genpkey -algorithm RSA -out cle.pem -pkeyopt rsa_keygen_bits:2048\nopenssl pkey -in cle.pem -pubout -out cle.pub\nopenssl dgst -sha256 -sign cle.pem -out message.sig message.txt\nopenssl dgst -sha256 -verify cle.pub -signature message.sig message.txt\n# Verified OK", "bash"),
    example("Exemple corrigé : Désiré envoie un contrat PDF à Atlas. S’il veut seulement cacher le contenu, il peut chiffrer. S’il veut prouver que le PDF vient bien de lui et qu’il n’a pas changé, il doit le signer avec sa clé privée. Atlas vérifie ensuite la signature avec la clé publique de Désiré. Si Atlas modifie une seule ligne du contrat, même un accent, la vérification échoue."),
    mistakes("confondre signature et chiffrement ; partager la clé privée « pour dépanner vite » ; publier une clé privée dans un dépôt de code ; oublier de sauvegarder la clé privée et ses informations de récupération dans un endroit maîtrisé."),
    safety("ne signe ni ne chiffre jamais au nom d’une autre personne sans autorisation explicite. Une clé privée engage la confiance et parfois la responsabilité de son détenteur. Protège-la comme tu protégerais un cachet officiel ou une signature manuscrite importante."),
    takeaway("le symétrique est rapide, l’asymétrique simplifie le partage de confiance, et le modèle hybride combine les deux. La signature numérique ne cache pas le contenu : elle prouve l’intégrité et l’origine. La clé privée doit rester secrète du début à la fin."),
    practice("ouvre le laboratoire « TP 4 : intégrité, chiffrement et certificats », repère où l’on vérifie une empreinte et où l’on s’appuie sur une clé publique, puis relie ces gestes à la logique des signatures numériques. Termine par le quiz de la leçon."),
    reference("wikiPki"),
    reference("rfc5280"),
  ],
  quiz: {
    title: "Quiz : clés et signatures numériques",
    questions: [
      questions.choice("Quel est le principal problème du chiffrement symétrique ?", ["Il ne peut protéger qu’un seul fichier", "Il demande un secret partagé dès le départ", "Il ne fonctionne pas avec Internet", "Il interdit toute vérification d’intégrité"], 1, "Le vrai défi du symétrique est la distribution sûre de la clé aux deux parties. Le piège le plus courant est de croire qu’il est faible par nature, alors qu’il est au contraire très efficace une fois la clé bien partagée.", "facile"),
      questions.tf("Vérifier une signature numérique se fait avec la clé publique du signataire.", true, "Vrai : le signataire utilise sa clé privée pour créer la signature, et toute personne disposant de la clé publique correspondante peut vérifier le résultat. Inverser les rôles des clés est l’erreur la plus classique.", "moyen"),
      questions.multi("Quelles affirmations sont exactes ? (plusieurs réponses)", ["TLS utilise en pratique une logique hybride", "Une clé privée RSA de 2048 bits ou plus reste un minimum courant", "Signer un document revient toujours à le rendre illisible", "Une clé SSH repose sur la même idée générale de paire publique et privée"], [0, 1, 3], "TLS combine asymétrique et symétrique, une taille RSA de 2048 bits ou plus reste une base courante, et SSH exploite aussi une paire de clés. L’option trompeuse est la signature : elle ne cache pas le contenu, elle en prouve surtout l’origine et l’intégrité.", "difficile"),
      questions.choice("Atlas reçoit un contrat signé numériquement. Quel événement fera échouer la vérification ?", ["Le contrat est copié sur une autre clé USB", "Le contrat est renommé sans changer son contenu", "Une phrase du contrat est modifiée après la signature", "La clé publique du signataire est diffusée à plus de personnes"], 2, "Une modification du contenu change l’empreinte recalculée et casse la vérification. Renommer ou copier un fichier ne modifie pas son contenu binaire dans ce scénario, et diffuser la clé publique est au contraire attendu.", "moyen"),
    ],
  },
};

const httpsCertificatsLesson: NewLesson = {
  key: "fond-https-certificats",
  title: "HTTPS, certificats et confiance sur le web",
  summary: "Comprends ce que garantit vraiment HTTPS, comment lire un certificat simple et pourquoi un cadenas n’est pas une preuve de légitimité d’un site.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer ce que garantit HTTPS, résumer le rôle de TLS, lire les champs essentiels d’un certificat, décrire une chaîne de confiance, et réagir correctement à un avertissement du navigateur."),
    prerequisites("avoir suivi « Clés secrètes, clés publiques et signatures numériques » ou déjà comprendre le principe d’une paire de clés."),
    scenario("Rokia doit vérifier un portail de paiement ouvert dans son navigateur. Le cadenas est visible, mais l’adresse lui semble étrange. Elle doit décider si elle peut faire confiance au site, quoi regarder dans le certificat et quoi faire si le navigateur affiche une erreur de nom ou d’expiration."),
    videoSlot("HTTPS et certificats : pourquoi le cadenas ne suffit pas"),
    text("HTTPS ajoute TLS à HTTP. Son but est triple : protéger la confidentialité du trafic entre le navigateur et le serveur, préserver son intégrité, et fournir une identité de serveur que le navigateur peut vérifier. En grandes lignes, le client envoie un « hello », le serveur présente son certificat, les deux parties établissent des clés de session, puis le reste de l’échange se fait avec un chiffrement symétrique rapide. Cette négociation ne rend pas un site honnête par magie : elle sécurise surtout le canal."),
    schema("HTTPS garantit\n1. confidentialité du trajet\n2. intégrité du trajet\n3. identité du serveur si le certificat est valide\n\nHTTPS ne garantit pas\n1. que le site est bienveillant\n2. que son contenu est vrai\n3. que l’utilisateur ne se trompe pas d’adresse"),
    text("Un certificat contient notamment le sujet, l’émetteur, une période de validité, des noms alternatifs de sujet, appelés SAN, la clé publique du serveur et la signature de l’autorité qui l’a validé. Les navigateurs vérifient ensuite une chaîne de confiance : certificat du serveur, parfois un certificat intermédiaire, puis une autorité racine déjà approuvée. Des autorités de certification délivrent des certificats gratuits et de courte durée, comme Let’s Encrypt. Cela rend le renouvellement automatique très important."),
    schema("Chaîne de confiance\n[Autorité racine]\n        |\n[Autorité intermédiaire]\n        |\n[Certificat du serveur example.com]\n\nVérifications : nom, date, signature, chaîne"),
    text("Quand un navigateur avertit qu’un certificat est expiré, que le nom présenté ne correspond pas au site visité, ou que l’autorité est inconnue, il faut s’arrêter et vérifier. Le bon réflexe n’est pas de cliquer vite sur « continuer quand même », surtout sur un site sensible. HSTS demande au navigateur de revenir toujours en HTTPS pour un site qui l’a déjà annoncé. Le cadenas ne prouve pas la légitimité du domaine : un site d’hameçonnage peut aussi obtenir un certificat valide."),
    text("Démonstration guidée : tu peux afficher le certificat d’un site depuis le navigateur, puis lire sa période de validité et ses noms couverts. En ligne de commande (Linux, macOS ou Git Bash sous Windows), la commande suivante demande le certificat présenté par « example.com » puis n’en affiche que l’essentiel. Les options « -connect » et « -servername » sont celles attendues par OpenSSL pour viser le bon service et le bon nom. Les valeurs montrées ici sont fictives et servent seulement à apprendre quoi lire."),
    code("echo | openssl s_client -connect example.com:443 -servername example.com 2>/dev/null | openssl x509 -noout -subject -issuer -dates -ext subjectAltName\n\n# Exemple de sortie (valeurs fictives)\n# subject=CN=example.com\n# issuer=C=US, O=Example CA, CN=Example Intermediate CA\n# notBefore=Jan 10 00:00:00 2027 GMT\n# notAfter=Feb 15 00:00:00 2027 GMT\n# X509v3 Subject Alternative Name:\n#     DNS:example.com, DNS:www.example.com", "bash"),
    example("Exemple corrigé : si un certificat est valable du 10 janvier 2027 au 15 février 2027, il reste 36 jours au 10 janvier 2027 avant l’expiration. Ce nombre ne dit rien sur la qualité du site lui-même, seulement sur l’état temporel du certificat. Si Rokia visite « examp1e.com » avec un certificat valide pour ce faux domaine, le cadenas n’efface pas le risque d’hameçonnage : c’est l’adresse complète qu’il faut contrôler."),
    mistakes("penser qu’un cadenas prouve la bonne foi d’un site ; ignorer les erreurs de nom ou de date ; croire qu’un certificat gratuit protège moins bien par principe ; oublier de renouveler un certificat court alors qu’un service dépend de lui."),
    safety("si un avertissement de certificat apparaît sur un site bancaire, administratif ou professionnel, ne passe pas outre sans vérification indépendante. Utilise l’adresse officielle saisie à la main ou un contact de confiance avant toute action."),
    takeaway("HTTPS protège le canal, pas la moralité du site. Un certificat doit être valide, au bon nom et relié à une chaîne de confiance reconnue. Le cadenas est un indice technique utile, mais jamais un remplaçant de la vigilance sur l’adresse et le contexte."),
    practice("ouvre le laboratoire « TP 4 : intégrité, chiffrement et certificats », lis un certificat, vérifie une empreinte et relie chaque observation aux garanties réelles d’HTTPS. Termine par le quiz de la leçon."),
    reference("letsEncrypt"),
    reference("rfc5280"),
  ],
  quiz: {
    title: "Quiz : HTTPS et certificats",
    questions: [
      questions.choice("Que garantit principalement HTTPS quand tout se passe bien ?", ["La réputation commerciale du site", "La confidentialité, l’intégrité du trajet et l’identité du serveur", "L’absence totale de publicité ou de pistage", "La qualité des mots de passe des utilisateurs"], 1, "HTTPS protège le canal entre le client et le serveur et aide à vérifier l’identité du serveur présenté. Le piège le plus fréquent est d’y voir une garantie globale de fiabilité du site, ce qu’aucun certificat ne peut promettre seul.", "facile"),
      questions.tf("Un site d’hameçonnage peut lui aussi afficher un cadenas HTTPS valide.", true, "Vrai : un certificat valide prouve surtout qu’un serveur contrôle un domaine et présente une chaîne de confiance acceptable. Il ne garantit pas que ce domaine n’imite pas frauduleusement un autre service.", "moyen"),
      questions.multi("Quels éléments sont typiquement vérifiés dans un certificat de serveur ? (plusieurs réponses)", ["Le nom du site, via le sujet ou les SAN", "La période de validité", "La chaîne de signature jusqu’à une autorité de confiance", "Le nombre exact de visiteurs quotidiens du site"], [0, 1, 2], "Le nom, les dates et la chaîne de confiance sont au cœur de la vérification. L’option trompeuse est le nombre de visiteurs : c’est peut-être intéressant pour le marketing, mais cela n’a rien à voir avec la validité cryptographique du certificat.", "difficile"),
      questions.choice("Le navigateur signale que le certificat présenté par un portail sensible est expiré. Quelle réaction est la plus prudente ?", ["Continuer quand même si le cadenas était visible hier", "Ignorer l’alerte si le site a un bon design", "S’arrêter et vérifier par une autre voie avant toute saisie", "Désactiver le contrôle des certificats dans le navigateur"], 2, "Une expiration casse une vérification importante et doit déclencher une pause. Continuer sans contrôle expose à des erreurs d’identité ou à une interception. Le design du site ou le souvenir d’une visite précédente ne remplacent pas cette vérification technique.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c1:5",
    position: 5,
    title: "Appareils, sauvegardes et réseaux du quotidien",
    description: "Ce module t’apprend à protéger les appareils que tu utilises vraiment : ordinateurs, téléphones, box et copies de secours. Critères de réussite : repérer un poste mal entretenu, vérifier qu’une stratégie de sauvegarde est crédible, et choisir des protections adaptées contre le vol, la perte et les réseaux non fiables.",
    lessons: [misesAJourLesson, sauvegardesLesson, chiffrementAppareilsLesson],
  },
  {
    key: "c1:6",
    position: 6,
    title: "Cryptographie pour débutants",
    description: "Tu y distingues les notions cryptographiques utiles sans formules inutiles, puis tu apprends à lire les signes de confiance affichés par les outils du quotidien. Critères de réussite : reconnaître un encodage, une empreinte et une signature, expliquer le rôle des clés publiques et privées, et juger correctement ce que garantit HTTPS sur le web.",
    lessons: [cryptoBasesLesson, clesSignaturesLesson, httpsCertificatsLesson],
  },
];
