import {
  code, example, figure, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const risquesLesson: NewLesson = {
  key: "fond-risques",
  title: "Évaluer un risque : actifs, menaces, vulnérabilités",
  summary: "Apprends à inventorier ce qui compte, à distinguer menace et vulnérabilité, puis à prioriser des risques avec une matrice simple et un registre exploitable.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("identifier les actifs d’une petite structure, distinguer menace, vulnérabilité et risque, noter vraisemblance et impact sur une échelle claire, choisir un traitement adapté, et prioriser un registre de risques sans confondre urgence et gravité."),
    prerequisites("avoir suivi « Les principes de la sécurité : confidentialité, intégrité, disponibilité, moindre privilège » ou déjà savoir ce qu’est un actif et une propriété C, I ou D."),
    scenario("Kwame aide la coopérative Harmattan à mieux protéger son activité. Les responsables parlent de tout à la fois : mots de passe, panne électrique, perte d’ordinateur, erreur de virement, fuite de données. Sans méthode, chacun défend son inquiétude du moment. Kwame doit transformer cette discussion en registre de risques pour savoir quoi traiter d’abord."),
    videoSlot("Construire une matrice de risques simple et utile"),
    text("Un actif est ce que tu veux protéger : un compte de messagerie, un ordinateur, une base de clients, une caisse mobile, mais aussi du temps de travail, la réputation ou la confiance d’un partenaire. Sa valeur ne se résume pas à son prix : demande-toi aussi ce qu’une perte de confidentialité, d’intégrité ou de disponibilité ferait à l’activité. Une menace est ce qui pourrait causer un dommage : rançongiciel, vol, erreur humaine, incendie, fraude, panne. Une vulnérabilité est la faiblesse qui rend la menace plausible : absence de sauvegarde, mot de passe réutilisé, poste non chiffré, procédure inexistante. Le risque combine donc trois idées : quelque chose de précieux, un danger, et une faiblesse exploitable."),
    figure({
      kind: "formula",
      title: "Actif + menace + vulnérabilité = risque",
      items: [
        {
          label: "Exemple",
          formula: "risque = actif + menace + vulnérabilité",
          example: "Actif : messagerie\nMenace : prise de contrôle du compte\nVulnérabilité : pas de double authentification",
          result: "Impact possible : lecture de courriels, fraude, perte de confiance",
        },
      ],
    }),
    text("Pour noter un risque, on utilise souvent une formule simple : risque = vraisemblance × impact. La vraisemblance estime la probabilité raisonnable du scénario dans ton contexte. L’impact mesure les dégâts si le scénario se réalise. Sur une échelle de 1 à 4, tu peux définir 1 comme faible, 2 comme notable, 3 comme fort, 4 comme majeur. Avec cette grille, un score de 1 à 3 reste faible, de 4 à 7 moyen, de 8 à 11 élevé, et de 12 à 16 critique. L’important n’est pas de jouer au mathématicien : il faut surtout écrire des critères compréhensibles pour que deux personnes notent à peu près de la même façon."),
    figure({
      kind: "matrix",
      title: "Matrice 4 × 4",
      xLabel: "Impact",
      yLabel: "Vraisemblance",
      xs: ["1", "2", "3", "4"],
      ys: ["1", "2", "3", "4"],
      cells: [
        [{ text: "1", tone: "green" }, { text: "2", tone: "green" }, { text: "3", tone: "amber" }, { text: "4", tone: "amber" }],
        [{ text: "2", tone: "green" }, { text: "4", tone: "amber" }, { text: "6", tone: "amber" }, { text: "8", tone: "red" }],
        [{ text: "3", tone: "amber" }, { text: "6", tone: "amber" }, { text: "9", tone: "red" }, { text: "12", tone: "red" }],
        [{ text: "4", tone: "amber" }, { text: "8", tone: "red" }, { text: "12", tone: "red" }, { text: "16", tone: "red" }],
      ],
    }),
    text("Un registre de risques tient généralement en quelques colonnes : actif, scénario, menace, vulnérabilité, vraisemblance, impact, score, traitement, responsable, échéance, risque résiduel. Le traitement peut suivre quatre verbes. Réduire : ajouter une sauvegarde, activer la double authentification, former l’équipe. Éviter : abandonner un usage trop dangereux. Transférer : souscrire une assurance ou confier une fonction à un prestataire encadré. Accepter : garder le risque parce qu’il coûte plus cher à corriger que ce qu’il menace réellement. Même après une mesure, il reste souvent un risque résiduel : on le documente au lieu de faire semblant qu’il a disparu."),
    text("Démonstration guidée : ouvre un tableau sur ton téléphone, dans un tableur ou même sur papier. Liste d’abord cinq actifs réels, puis pour chacun une menace crédible et une faiblesse observable. Ensuite seulement, note vraisemblance et impact. Cette séquence évite l’erreur classique qui consiste à écrire directement « risque élevé » sans dire de quoi on parle."),
    code("Actif | Scénario | Menace | Vulnérabilité | V | I | Score | Traitement\nMessagerie | Compte repris | Hameçonnage | pas de MFA | 4 | 4 | 16 | Réduire\nPortable | Données lues après vol | Vol | disque non chiffré | 3 | 4 | 12 | Réduire\nSauvegarde | Activité arrêtée | Rançongiciel | une seule copie locale | 3 | 3 | 9 | Réduire\nComptes | Ancien accès encore valide | Menace interne | compte partagé | 2 | 4 | 8 | Éviter\nWi-Fi invité | Réseau interne exposé | Accès non autorisé | mauvaise séparation | 2 | 3 | 6 | Réduire", "text"),
    example("Exemple corrigé : chez la coopérative Harmattan, cinq risques sont notés. « Messagerie sans MFA » vaut 4 × 4 = 16, donc critique. « Portable non chiffré » vaut 3 × 4 = 12, critique aussi. « Sauvegarde unique sur le même poste » vaut 3 × 3 = 9, élevé. « Compte partagé après départ » vaut 2 × 4 = 8, élevé. « Wi-Fi invité mal séparé » vaut 2 × 3 = 6, moyen. L’ordre de traitement commence donc par la messagerie et le chiffrement du portable, avant d’optimiser le Wi-Fi invité."),
    mistakes("confondre menace et vulnérabilité, par exemple écrire « mot de passe faible » comme menace alors que c’est une faiblesse ; utiliser une échelle sans critères écrits, ce qui rend les notes arbitraires ; oublier de réévaluer après une mesure, alors que le contexte change ; vouloir protéger à n’importe quel prix un actif dont la valeur est modeste."),
    safety("une analyse de risques sert à protéger, pas à désigner un coupable. Si tu travailles pour une structure, fais valider le périmètre et manipule le registre comme un document sensible : il décrit précisément les faiblesses à corriger."),
    takeaway("un risque n’est ni une peur vague ni une simple panne : c’est un scénario qui relie un actif, une menace et une vulnérabilité. Une matrice simple suffit si ses critères sont clairs. Le vrai but est de prioriser l’action, pas de produire un beau tableau."),
    practice("ouvre le laboratoire « TP 5 : construire un registre de risques », classe les incidents par propriété C, I ou D, puis note les scénarios avant de choisir un traitement. Termine par le quiz de la leçon."),
    reference("anssiEbios"),
    reference("nistCsf"),
    reference("nistSmallBusiness"),
  ],
  quiz: {
    title: "Quiz : évaluer un risque",
    questions: [
      questions.choice("Quelle formulation décrit correctement un risque ?", ["Une menace seule, comme « rançongiciel »", "Une faiblesse seule, comme « mots de passe faibles »", "Un scénario reliant un actif, une menace et une vulnérabilité", "Une panne déjà arrivée et terminée"], 2, "La bonne réponse relie ce que tu protèges, ce qui peut lui nuire et la faiblesse exploitable. Une menace seule ou une vulnérabilité seule reste trop vague pour décider d’une priorité ou d’une mesure concrète.", "facile"),
      questions.multi("Quelles actions relèvent bien d’un traitement du risque ? (plusieurs réponses)", ["Activer la double authentification sur la messagerie", "Abandonner un ancien partage public devenu trop exposé", "Noter « critique » sans expliquer pourquoi", "Souscrire une assurance adaptée à l’activité"], [0, 1, 3], "Activer une mesure réduit le risque, abandonner un usage l’évite, et une assurance peut en transférer une partie. En revanche, écrire seulement « critique » ne traite rien : cela décrit une priorité sans action.", "moyen"),
      questions.tf("Si un risque est noté 12 sur 16, cela signifie qu’il se réalisera forcément.", false, "Faux : un score élevé signale une priorité de traitement, pas une certitude. La note combine vraisemblance et impact pour aider à décider avant l’incident, justement parce qu’on ne peut pas prédire l’avenir avec certitude.", "moyen"),
      questions.choice("Une association note « base des adhérents, exposition sur une messagerie sans MFA, vraisemblance 4, impact 4 ». Quel choix est le plus cohérent ?", ["Traiter d’abord ce scénario avant un Wi-Fi invité noté 6", "Ignorer le sujet car la formule est trop simple", "Reporter toute décision tant qu’un outil payant n’est pas acheté", "Classer ce risque en faible car rien n’est encore arrivé"], 0, "Un score de 16 est critique : il mérite une action rapide avant un scénario moyen noté 6. La formule est volontairement simple mais utile, et attendre un achat ou un incident réel serait justement une mauvaise gestion du risque.", "difficile"),
    ],
  },
};

const donneesPersonnellesLesson: NewLesson = {
  key: "fond-donnees-personnelles",
  title: "Protéger les données personnelles : principes, droits et obligations",
  summary: "Découvre ce qu’est une donnée personnelle, quels principes guident son traitement, quels droits ont les personnes et comment réagir quand une violation présente un risque.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("reconnaître une donnée personnelle, distinguer responsable de traitement et sous-traitant, citer les principes essentiels de protection, expliquer les droits des personnes, et réagir à une violation de données avec prudence juridique."),
    prerequisites("avoir suivi « Évaluer un risque : actifs, menaces, vulnérabilités » ou déjà savoir inventorier des actifs et qualifier un impact."),
    scenario("Amina aide l’association Teranga à gérer des inscriptions à une formation. Le formulaire demande un nom, un téléphone, une adresse, l’âge, le quartier et parfois des informations de santé pour l’accessibilité. L’équipe veut aussi exporter le fichier vers un outil de publipostage gratuit. Amina doit décider quelles données sont vraiment nécessaires, qui y accède, combien de temps elles restent conservées et quoi faire si le fichier est envoyé au mauvais destinataire."),
    videoSlot("Données personnelles : les bons réflexes sans jargon juridique inutile"),
    text("Une donnée personnelle est toute information qui identifie directement ou indirectement une personne. Un nom ou une photo identifie directement. Un numéro de téléphone, une adresse, un identifiant de compte, une plaque, une combinaison de date de naissance et de quartier peuvent identifier indirectement. Certaines catégories exigent une prudence renforcée, notamment les données de santé, biométriques, les opinions religieuses ou l’appartenance syndicale. Les données relatives aux condamnations et infractions suivent elles aussi un cadre particulier. Le réflexe utile n’est pas de réciter une liste : demande-toi toujours si l’information permet de reconnaître quelqu’un, seule ou croisée avec d’autres."),
    figure({
      kind: "cards",
      title: "Exemples rapides",
      items: [
        { term: "Donnée personnelle", text: "nom, téléphone, adresse, photo", tone: "green" },
        { term: "Souvent sensible", text: "santé, biométrie, croyances", tone: "red" },
        { term: "Pas forcément personnelle seule", text: "numéro interne sans contexte", tone: "neutral" },
        { term: "Devient personnelle", text: "si on peut relier le numéro à une personne", tone: "amber" },
      ],
    }),
    text("La protection des données repose sur des principes simples à retenir. Il faut une finalité claire : pourquoi collecter ? Il faut la licéité : sur quelle base agir, par exemple contrat, obligation légale, consentement, intérêt légitime. Il faut la minimisation : ne demander que ce qui est nécessaire. Il faut l’exactitude, une durée de conservation limitée, la transparence, et des mesures de sécurité adaptées. Le responsable de traitement décide pourquoi et comment les données sont utilisées. Le sous-traitant traite les données pour son compte, selon un cadre défini. Dans une petite structure, ces rôles peuvent tenir dans peu de personnes, mais ils doivent être compris. Le RGPD peut parfois s’appliquer même si l’organisation n’est pas établie dans l’Union européenne, par exemple si elle vise des personnes qui s’y trouvent."),
    figure({
      kind: "steps",
      title: "Questions avant toute collecte",
      numbered: true,
      items: [
        { title: "Pourquoi cette donnée ?" },
        { title: "Qui y accède ?" },
        { title: "Combien de temps la garder ?" },
        { title: "Où est-elle stockée ?" },
        { title: "Comment la protéger ?" },
        { title: "Comment la supprimer ou la corriger ?" },
      ],
    }),
    text("Les personnes disposent de droits : accéder à leurs données, demander une rectification, un effacement, une opposition, une limitation ou une portabilité selon les cas. Cela implique des procédures concrètes. Si quelqu’un écrit pour corriger son numéro ou demander ce que tu détiens, il faut savoir retrouver l’information, répondre clairement et documenter le traitement. Un registre des traitements aide justement à ne pas improviser. Un DPO, ou délégué à la protection des données, peut être désigné dans certains contextes ou simplement servir de point de contact quand la structure en a besoin."),
    text("Une violation de données personnelles correspond à un incident qui détruit, perd, altère, divulgue ou rend accessibles des données sans autorisation. Si cette violation présente un risque pour les personnes, une notification à l’autorité compétente peut être requise dans les 72 heures après en avoir pris connaissance. Si le risque est élevé, les personnes concernées doivent aussi être informées avec honnêteté. Tu n’as pas à mémoriser la loi de chaque pays. Retiens plutôt ceci : le RGPD est une référence utile, la Convention de Malabo pose un cadre africain, beaucoup de pays ont leur propre autorité, et il faut vérifier celle qui s’applique à ton contexte."),
    text("Démonstration guidée : prends un formulaire réel ou imaginaire et relis chaque champ comme si tu devais le défendre devant une personne concernée. Si tu ne peux pas expliquer en une phrase son utilité, enlève-le ou rends-le optionnel. Ensuite, note dans un mini-registre la finalité, la base légale, la durée de conservation et les mesures de sécurité. Tu peux faire cet exercice depuis un téléphone dans une note simple."),
    code("Traitement : inscriptions à une formation\nFinalité : gérer les candidatures et contacter les participants\nDonnées : nom, téléphone, adresse électronique\nÀ éviter si inutile : profession détaillée, copie d’identité, données de santé\nAccès : coordination et administration\nDurée : le temps nécessaire à la gestion puis archivage limité\nMesures : comptes nominatifs, MFA, export limité, suppression des doublons", "text"),
    example("Exemple corrigé : l’association Teranga collecte des fiches d’inscription pour une formation. La finalité est claire : organiser la session et prévenir les participants. Demander le nom, le téléphone et l’adresse électronique est cohérent ; demander l’état civil complet et une pièce d’identité ne l’est pas si rien ne le justifie. Les fiches sont conservées le temps de la session puis archivées de manière limitée pour le suivi administratif. Si Amina découvre un mercredi à 14 h 20 qu’un fichier a été envoyé à un mauvais destinataire et que le risque pour les personnes est réel, le délai de 72 heures mène au samedi à 14 h 20 pour la notification à l’autorité compétente."),
    mistakes("croire qu’une petite structure n’a aucune obligation parce qu’elle est petite ; demander « au cas où » des données qu’on n’utilisera pas ; confondre consentement et seule base légale possible, alors qu’il existe d’autres fondements ; traiter une violation comme un problème d’image uniquement, sans évaluer le risque pour les personnes."),
    safety("appuie-toi sur des principes généraux utiles partout : collecter le minimum, expliquer l’usage, limiter les accès, protéger les exports et réagir vite en cas de fuite. Pour une décision juridique ou une notification réelle, vérifie toujours la loi et l’autorité compétente de ton pays ou de celui des personnes concernées."),
    takeaway("une donnée personnelle n’est pas seulement un nom : c’est toute information qui permet d’identifier quelqu’un. Collecter moins, expliquer mieux et sécuriser davantage réduit à la fois le risque et la charge de conformité. En cas de violation, le temps compte, mais la qualité de l’évaluation compte aussi."),
    practice("travaille d’abord dans « TP 5 : construire un registre de risques » pour repérer les actifs contenant des données personnelles, puis poursuis avec « Incident : un compte de messagerie compromis » pour raisonner sur le délai de notification et les mesures à prendre. Termine par le quiz de la leçon."),
    reference("cnilRgpdEssentiel"),
    reference("cnilDroits"),
    reference("auMalabo"),
  ],
  quiz: {
    title: "Quiz : données personnelles et obligations",
    questions: [
      questions.choice("Quelle information est la plus clairement une donnée personnelle ?", ["Le mot « facture » seul", "Le nom et le numéro de téléphone d’un participant", "Le prix d’un ticket de bus", "Le type de clavier d’un poste"], 1, "Le nom et le téléphone permettent d’identifier directement une personne. Les autres éléments, pris seuls dans cet énoncé, ne permettent pas d’identifier quelqu’un avec la même évidence.", "facile"),
      questions.tf("Si une violation de données présente un risque pour les personnes, le délai de notification de référence au titre du RGPD est de 72 heures après en avoir pris connaissance.", true, "Vrai : la logique n’est pas « 72 heures après l’incident réel », mais bien après le moment où l’organisation en prend connaissance. Cela oblige à documenter l’heure de découverte et à évaluer rapidement le risque.", "moyen"),
      questions.multi("Quelles pratiques respectent mieux les principes de protection des données ? (plusieurs réponses)", ["Expliquer la finalité du formulaire", "Demander seulement les informations nécessaires", "Conserver tous les exports sans limite parce qu’ils pourraient servir plus tard", "Prévoir comment corriger ou supprimer une donnée"], [0, 1, 3], "Expliquer la finalité, minimiser la collecte et prévoir la rectification ou la suppression vont dans le sens des principes de licéité, minimisation et durée limitée. En revanche, garder tous les exports « au cas où » contredit justement ces principes.", "moyen"),
      questions.choice("Une petite association confie l’envoi de courriels à un prestataire selon ses instructions. Quel énoncé est le plus juste ?", ["Le prestataire devient forcément responsable de traitement unique", "L’association décide de la finalité et reste généralement responsable de traitement", "Les rôles juridiques disparaissent si le service est gratuit", "La protection des données ne concerne plus que le prestataire"], 1, "La structure qui décide du but et des moyens essentiels du traitement reste en général responsable de traitement. Le prestataire agit alors comme sous-traitant selon le cadre prévu. Le prix du service ne change pas cette logique.", "difficile"),
    ],
  },
};

const gouvernanceLesson: NewLesson = {
  key: "fond-gouvernance",
  title: "Politiques de sécurité, sensibilisation et culture de la sécurité",
  summary: "Comprends comment une petite structure fixe des règles utiles, répartit les responsabilités et construit une culture de signalement sans transformer la sécurité en punition.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("expliquer le rôle d’une politique de sécurité, répartir les responsabilités essentielles, choisir des actions de sensibilisation adaptées à un petit budget, suivre quelques indicateurs simples, et rédiger des règles courtes que l’équipe peut vraiment appliquer."),
    prerequisites("avoir suivi « Protéger les données personnelles : principes, droits et obligations » ou déjà connaître les enjeux de comptes, d’appareils et de signalement."),
    scenario("Mamadou coordonne une petite équipe chez Sahel Services. Tout le monde utilise la messagerie, parfois son propre téléphone, et certains travaillent à distance. Après plusieurs clics sur de faux messages, la direction demande « une politique de sécurité ». Mamadou veut éviter le document poussiéreux que personne ne lit. Il cherche des règles courtes, des responsabilités claires et une manière de faire remonter les incidents sans humilier les collègues."),
    videoSlot("Gouvernance sécurité : des règles simples qui changent vraiment les habitudes"),
    text("La gouvernance de la sécurité, ce n’est pas seulement un grand mot pour les grosses entreprises. C’est la manière d’organiser qui décide quoi, selon quelles règles, avec quels contrôles et quels retours d’expérience. Dans une petite structure, une politique de sécurité ou une charte informatique doit couvrir l’usage acceptable des outils, les mots de passe, la messagerie, les appareils personnels, le télétravail, les accès, le départ d’un collaborateur et le signalement des incidents. Si la règle n’est pas compréhensible en quelques secondes, elle sera contournée ou oubliée."),
    figure({
      kind: "relations",
      title: "Rôles minimaux",
      pairs: [
        { from: "Direction", label: "fixe", to: "les priorités et valide les moyens", tone: "amber" },
        { from: "Référent sécurité", label: "suit", to: "les actions et coordonne", tone: "blue" },
        { from: "Utilisateurs", label: "appliquent", to: "signalent, demandent en cas de doute", tone: "green" },
        { from: "Support ou prestataire", label: "met en œuvre", to: "documente", tone: "violet" },
      ],
    }),
    text("Une bonne politique ne vit pas seule. Elle s’accompagne d’une sensibilisation continue : capsules courtes, affiches, rappels en réunion, mini-exercices, messages simples. Le but n’est pas de piéger l’équipe, mais d’installer des réflexes. Une culture sans blâme est décisive : si quelqu’un a peur d’avouer un clic ou une erreur, l’incident grossira en silence. En revanche, si l’équipe sait qu’un signalement rapide sera accueilli avec sérieux, elle aidera la défense au lieu de la retarder."),
    figure({
      kind: "flow",
      title: "Cycle simple",
      nodes: [
        { label: "Règle claire" },
        { label: "Habitude" },
        { label: "Signalement rapide" },
        { label: "Retour d’expérience" },
      ],
      loop: "amélioration continue",
    }),
    text("Les indicateurs servent à voir si les habitudes changent vraiment. Tu peux suivre le taux de clic lors d’un exercice annoncé et éthique, le nombre de signalements utiles, le délai moyen de mise à jour, ou le temps nécessaire pour désactiver le compte d’une personne qui quitte la structure. Il faut peu d’indicateurs, mais ils doivent mener à une décision. Mesurer pour mesurer ne sert à rien."),
    text("Démonstration guidée : rédige une charte en huit règles maximum. Chaque règle doit commencer par un verbe d’action et répondre à un risque visible. Par exemple : activer la double authentification, ne pas partager de compte, signaler tout message suspect, séparer usage personnel et usage professionnel autant que possible. Relis ensuite la charte avec une personne non technique : si elle ne comprend pas un point, réécris-le."),
    code("Charte courte de l’association Teranga\n1. Utilise un compte nominatif.\n2. Active la double authentification quand elle existe.\n3. Ne partage jamais ton mot de passe.\n4. Signale tout message ou lien suspect.\n5. Verrouille ton appareil quand tu t’éloignes.\n6. Stocke les documents sensibles aux emplacements prévus.\n7. Préviens le référent avant de quitter la structure.\n8. Demande de l’aide avant d’improviser un contournement.", "text"),
    example("Exemple corrigé : Sahel Services lance un exercice annoncé auprès de 48 personnes. Six personnes cliquent sur le faux message. Le taux de clic est donc de 6 ÷ 48 = 12,5 %. Ce chiffre n’est utile que s’il mène à une action : par exemple renforcer la vérification des expéditeurs et rappeler la procédure de signalement. Si, le mois suivant, le taux baisse et que les signalements augmentent, la sensibilisation produit un effet concret."),
    mistakes("écrire une charte si longue qu’elle n’est jamais lue ; limiter la sécurité à la sanction, ce qui décourage le signalement ; oublier la gestion des arrivées, mutations et départs, alors que les comptes orphelins sont un risque classique ; suivre des indicateurs sans jamais les relier à une décision ou à un budget."),
    safety("les simulations d’hameçonnage doivent rester éthiques, proportionnées et connues du cadre interne. Le but est d’entraîner l’attention et le signalement, pas d’humilier des personnes ni de contourner leurs droits."),
    takeaway("la gouvernance traduit la sécurité en règles applicables, responsabilités claires et suivi régulier. Une bonne culture de sécurité fait remonter les doutes vite et sans blâme. Même avec peu de budget, quelques priorités bien tenues changent fortement le niveau de protection."),
    practice("prépare-toi pour « Projet final : auditer la sécurité du Centre Numérique Soleil » en relisant les règles, les rôles et les indicateurs que tu vérifierais dans une petite structure. Termine par le quiz de la leçon."),
    reference("anssiHygiene"),
    reference("cisaSecureOurWorld"),
    reference("nistSmallBusiness"),
  ],
  quiz: {
    title: "Quiz : gouvernance et culture sécurité",
    questions: [
      questions.choice("Quel énoncé décrit le mieux une bonne politique de sécurité pour une petite structure ?", ["Un document très long conservé par la direction uniquement", "Des règles courtes, comprises, relues et reliées à des responsabilités", "Une liste de sanctions sans procédure de signalement", "Un ensemble de règles secrètes pour éviter qu’elles soient contournées"], 1, "Une politique utile doit être lisible, applicable et reliée à des rôles concrets. Un document caché ou purement punitif ne crée pas d’habitudes sûres et freine le signalement des incidents.", "facile"),
      questions.tf("Une culture sans blâme signifie qu’aucune erreur n’a plus de conséquence.", false, "Faux : sans blâme ne veut pas dire sans responsabilité. Cela signifie qu’on favorise le signalement rapide et l’apprentissage, au lieu de pousser les personnes à cacher leurs erreurs par peur de la réaction.", "moyen"),
      questions.multi("Quels indicateurs peuvent aider un référent sécurité ? (plusieurs réponses)", ["Le délai de désactivation d’un compte lors d’un départ", "Le taux de clic à un exercice annoncé", "Le nombre exact de fonds d’écran installés", "Le nombre de signalements utiles reçus"], [0, 1, 3], "Ces trois indicateurs disent quelque chose sur les accès, les habitudes et la remontée d’alerte. En revanche, compter les fonds d’écran n’aide pas à piloter un risque de sécurité identifié.", "moyen"),
      questions.choice("Dans une équipe où les collègues cachent leurs clics sur des messages suspects, quelle priorité est la plus pertinente ?", ["Ajouter encore plus de jargon dans la charte", "Supprimer tout exercice de sensibilisation", "Créer un canal de signalement simple et rassurant, puis rappeler qu’un doute déclaré tôt aide tout le monde", "Ne suivre que le nombre de sanctions disciplinaires"], 2, "Quand les personnes cachent leurs erreurs, le problème est d’abord culturel et organisationnel. Un canal clair et une réponse non humiliante améliorent la détection réelle. Ajouter du jargon ou ne suivre que les sanctions aggrave souvent le silence.", "difficile"),
    ],
  },
};

const reponseIncidentLesson: NewLesson = {
  key: "fond-reponse-incident",
  title: "Répondre à un incident : le cycle en six étapes",
  summary: "Suis une méthode simple pour distinguer événement, incident et crise, puis contenir, éradiquer et restaurer sans oublier la preuve, la communication et le retour d’expérience.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer événement, incident et crise, décrire les six étapes d’une réponse à incident, choisir des mesures de confinement adaptées, répartir les rôles essentiels, et conduire un retour d’expérience utile."),
    prerequisites("avoir suivi « Politiques de sécurité, sensibilisation et culture de la sécurité » ou déjà connaître l’idée de rôles, d’escalade et de signalement."),
    scenario("Un lundi matin, Baobab Tech constate qu’un poste affiche une note de rançon et que des fichiers partagés deviennent illisibles. Le support veut éteindre toutes les machines. La direction veut prévenir immédiatement les clients. Une collègue pense qu’il suffit de restaurer les sauvegardes. Pour éviter la panique, Désiré doit conduire une réponse ordonnée et ne pas détruire les indices utiles."),
    videoSlot("Les six étapes d’une réponse à incident sans improvisation"),
    text("Tous les signaux ne sont pas des incidents. Un événement est un fait observé : une alerte antivirus, un échec de connexion, un service lent. Un incident de sécurité est un événement confirmé ou très plausible qui affecte la confidentialité, l’intégrité ou la disponibilité. Une crise apparaît quand l’impact dépasse le technique : activité bloquée, réputation menacée, décision de direction, obligations légales ou communication externe. Cette distinction évite deux excès : sous-réagir à un vrai problème, ou déclencher une cellule de crise pour une alerte isolée."),
    figure({
      kind: "flow",
      title: "Du signal à la décision",
      nodes: [
        { label: "Événement" },
        { label: "Qualification" },
        { label: "Incident" },
        { label: "Crise", text: "incident majeur, activité touchée, communication sensible", tone: "red" },
      ],
    }),
    text("Le cycle en six étapes est une façon simple de garder la tête froide. 1. Préparation : contacts, sauvegardes, journaux, exercices et fiche réflexe. 2. Identification : que se passe-t-il vraiment, sur quels actifs, avec quel impact ? 3. Confinement : empêcher la propagation. 4. Éradication : supprimer la cause technique, par exemple compte compromis, tâche malveillante ou point d’entrée. 5. Récupération : remettre en service et surveiller. 6. Retour d’expérience : comprendre ce qui a marché, ce qui a manqué, et quoi améliorer. Le NIST SP 800-61 révision 2, qui reste la référence citée ici, regroupe cette logique en quatre phases : préparation, détection et analyse, confinement-éradication-récupération, puis activité post-incident. Une révision 3 plus récente existe aussi, mais la logique pratique reste proche pour un débutant."),
    figure({
      kind: "relations",
      title: "Rôles pendant l’incident",
      pairs: [
        { from: "Responsable", label: "arbitre", to: "priorise", tone: "amber" },
        { from: "Technique", label: "enquête", to: "confine, restaure", tone: "blue" },
        { from: "Communication", label: "prépare", to: "les messages internes et externes", tone: "violet" },
        { from: "Juridique ou DPO", label: "aide", to: "sur les obligations de notification", tone: "green" },
      ],
    }),
    figure({
      kind: "cycle",
      title: "Cycle en 6 étapes",
      center: "réponse ordonnée",
      nodes: [
        { label: "Préparation" },
        { label: "Identification" },
        { label: "Confinement" },
        { label: "Éradication" },
        { label: "Récupération" },
        { label: "Retour d’expérience" },
      ],
    }),
    text("Le confinement ne signifie pas « tout couper sans réfléchir ». Isoler une machine du réseau, désactiver un compte, révoquer des sessions ou changer un mot de passe peut être pertinent. En revanche, éteindre brutalement un poste peut détruire des preuves volatiles, par exemple des sessions actives ou certains processus en mémoire. Il faut donc arbitrer selon le type d’incident. La communication compte aussi : mieux vaut dire clairement ce que l’on sait, ce que l’on ne sait pas encore, et qui décide de la suite."),
    text("Démonstration guidée : construis une fiche réflexe avant l’incident. Écris qui appeler, dans quel ordre, quels comptes d’urgence utiliser, où se trouvent les sauvegardes et quel canal employer si la messagerie est compromise. Termine par un petit exercice sur table : chacun lit la fiche et explique ce qu’il ferait dans les dix premières minutes. Cette fiche doit pouvoir tenir sur une page et rester disponible même si le poste principal est inutilisable."),
    code("Fiche réflexe minimale\n1. Noter l’heure et le premier symptôme\n2. Prévenir le référent sécurité et la direction\n3. Isoler l’actif touché du réseau si la propagation est possible\n4. Conserver journaux, captures et messages observés\n5. Désactiver ou réinitialiser les comptes compromis\n6. Vérifier l’état des sauvegardes\n7. Préparer la communication interne et externe\n8. Planifier le retour d’expérience", "text"),
    example("Exemple corrigé : chez Baobab Tech, la préparation existe déjà avec une fiche réflexe et des sauvegardes testées. À l’identification, l’équipe confirme qu’un partage commun est chiffré. En confinement, le poste suspect est isolé et le compte concerné est suspendu. En éradication, l’accès initial compromis est supprimé et les mots de passe réinitialisés. En récupération, les fichiers sains sont restaurés puis surveillés. Enfin, le retour d’expérience montre que la double authentification manquait sur la messagerie et que le canal de secours entre direction et support était trop flou."),
    mistakes("payer ou négocier avant d’avoir compris l’incident et évalué les options ; réinstaller trop vite sans conserver les journaux utiles ; confondre récupération et éradication, alors qu’un service remis en ligne peut rechuter ; ne rien noter pendant l’incident, ce qui ruine ensuite la chronologie et les leçons à tirer."),
    safety("tu n’interviens que sur des systèmes que tu es autorisé à traiter. Si des données personnelles sont impliquées, pense à l’évaluation du risque et au cadre de notification adapté sans improviser le droit d’un pays précis."),
    takeaway("une bonne réponse à incident suit un ordre : comprendre, contenir, éliminer, remettre en service, apprendre. Le confinement protège le périmètre, mais il doit respecter la valeur des preuves. Une fiche réflexe claire fait gagner des minutes qui comptent."),
    practice("travaille « Incident : un compte de messagerie compromis » en observant qui décide, qui confine et comment la chronologie mène aux bonnes mesures. Termine par le quiz de la leçon."),
    reference("nistIncident"),
    reference("cmRancongiciels"),
    reference("cisaRansomware"),
  ],
  quiz: {
    title: "Quiz : réponse à incident",
    questions: [
      questions.choice("Quelle étape vient juste après l’identification dans le cycle en six étapes présenté ici ?", ["La récupération", "Le confinement", "Le retour d’expérience", "La conformité"], 1, "Une fois l’incident qualifié, la priorité est d’empêcher son extension. La récupération et le retour d’expérience viennent plus tard, après la maîtrise de la propagation et la suppression de la cause.", "facile"),
      questions.tf("Éteindre immédiatement toute machine touchée est toujours la meilleure décision de confinement.", false, "Faux : couper brutalement peut parfois détruire des preuves volatiles utiles à l’analyse. Le bon réflexe est de choisir une mesure de confinement adaptée au scénario, par exemple isolation réseau ou désactivation d’un compte.", "moyen"),
      questions.multi("Quelles actions relèvent bien du confinement ? (plusieurs réponses)", ["Isoler un poste du réseau", "Révoquer des sessions suspectes", "Supprimer tout l’historique de journaux pour repartir proprement", "Suspendre temporairement un compte compromis"], [0, 1, 3], "Isoler, révoquer et suspendre limitent la propagation ou l’usage malveillant en cours. En revanche, supprimer les journaux détruit des éléments utiles pour comprendre, prouver et corriger correctement l’incident.", "moyen"),
      questions.choice("Dans une petite structure touchée par un rançongiciel, quelle formulation montre la meilleure maturité ?", ["« On réinstalle tout, on verra plus tard »", "« On note les heures, on isole, on vérifie les sauvegardes et on décide ensuite de la restauration »", "« On publie tout de suite un message rassurant sans vérifier »", "« On coupe Internet et on garde le silence total »"], 1, "Cette réponse garde l’ordre logique : observation, confinement, vérification des sauvegardes puis décision de restauration. Les autres options sautent des étapes essentielles ou privilégient la communication avant la compréhension.", "difficile"),
    ],
  },
};

const detecterPreuvesLesson: NewLesson = {
  key: "fond-detecter-preuves",
  title: "Détecter, signaler et préserver les preuves",
  summary: "Repère les signaux utiles, qualifie une alerte, aligne des journaux dans le bon fuseau horaire et protège l’intégrité des preuves avant l’analyse détaillée.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("repérer des indicateurs de compromission, distinguer un vrai positif d’un faux positif plausible, signaler un incident avec les bonnes informations, reconstruire une chronologie en UTC, et préserver les preuves sans les altérer."),
    prerequisites("avoir suivi « Répondre à un incident : le cycle en six étapes » ou déjà savoir pourquoi la chronologie et le confinement doivent être documentés."),
    scenario("Rokia reçoit trois signaux presque en même temps : un utilisateur dit que des courriels partent tout seuls, l’antivirus remonte une alerte mineure et le journal de la messagerie montre une connexion inhabituelle. Sur le groupe de discussion, chacun interprète les heures différemment car les outils n’utilisent pas le même fuseau. Rokia doit décider vite si c’est un vrai incident, puis conserver ce qui prouve la séquence des faits."),
    videoSlot("Chronologie, journaux et preuves : ne pas perdre l’essentiel"),
    text("La détection vient souvent de sources imparfaites. Un antivirus alerte, un utilisateur voit un comportement étrange, un journal de connexion signale un pays inattendu, ou des fichiers changent brutalement de nom. Un indicateur de compromission, ou IOC, peut être une adresse IP, un domaine, une empreinte de fichier, un nom de processus ou une règle de transfert de courriel. Aucun de ces éléments n’est magique pris seul. Il faut les recouper pour distinguer un vrai positif d’un faux positif, c’est-à-dire une alerte qui ressemble à une attaque sans en être une."),
    figure({
      kind: "cards",
      title: "Exemples de sources",
      items: [
        { term: "Alerte outil", text: "signal remonté par un outil", tone: "blue" },
        { term: "Journal de connexion", text: "traces de connexion", tone: "violet" },
        { term: "Signalement utilisateur", text: "symptôme vu par la personne", tone: "green" },
        { term: "Message de rançon", text: "texte laissé par l’attaquant", tone: "red" },
        { term: "Fichiers renommés", text: "changement brutal de noms", tone: "amber" },
        { term: "Courriels envoyés à l’insu du propriétaire", text: "activité visible sans accord", tone: "red" },
      ],
    }),
    text("Bien signaler un incident, c’est répondre à cinq questions : quoi, quand, où, comment, qui. Quoi : le symptôme précis. Quand : l’heure observée et le fuseau si nécessaire. Où : machine, compte, application, boîte mail, réseau concerné. Comment : pièce jointe, lien, session distante, support amovible, ou simple doute. Qui : personne qui observe et point de contact à prévenir. Une alerte vague comme « ça ne marche plus » ralentit tout le monde. Une alerte factuelle aide à qualifier sans dramatiser."),
    figure({
      kind: "steps",
      title: "Préserver la preuve",
      numbered: true,
      items: [
        { title: "Noter l’heure" },
        { title: "Capturer sans modifier si possible" },
        { title: "Copier avant d’analyser" },
        { title: "Calculer une empreinte si pertinent" },
        { title: "Garder la chaîne de conservation" },
      ],
    }),
    text("Le temps est un piège classique. Certains journaux parlent en UTC, d’autres en heure locale avec décalage. Pour aligner les événements, convertis tout dans un repère commun, souvent l’UTC, et vérifie que les horloges sont synchronisées, par exemple via NTP. Pense aussi à l’ordre de volatilité : la mémoire vive, les connexions actives et certains journaux temporaires peuvent disparaître plus vite qu’un fichier déjà écrit sur disque. Travailler sur des copies et vérifier leur intégrité avec une empreinte protège la valeur de la preuve. Cela compte pour l’analyse interne, et encore plus si un contentieux apparaît ensuite. Sur Windows, l’Observateur d’événements est une source courante ; sur Linux, on rencontre souvent « last » et « journalctl » ; une messagerie ou un service cloud possède aussi ses propres journaux."),
    text("Démonstration guidée : prends cinq lignes de journaux et convertis-les toutes en UTC avant de raconter l’histoire. Tu peux le faire dans un tableau, dans un fichier texte ou sur un téléphone. L’objectif n’est pas de devenir expert en forensique, mais d’éviter la chronologie fausse qui fait accuser la mauvaise action ou le mauvais compte."),
    code("09:05:00+01:00  Login success sur la messagerie\n10:25:00+02:00  Règle de transfert créée\n11:40:00+03:00  Transfert externe activé\n09:50:00Z       Compte désactivé\n09:55:00Z       Mot de passe réinitialisé\n\nConversion UTC\n09:05+01:00 -> 08:05Z\n10:25+02:00 -> 08:25Z\n11:40+03:00 -> 08:40Z", "text"),
    example("Exemple corrigé : une fois les heures alignées, la connexion réussie apparaît à 08:05Z, la règle de transfert à 08:25Z, l’activation du transfert externe à 08:40Z, puis le compte est désactivé à 09:50Z. La durée d’exposition entre le premier accès confirmé et la désactivation est donc de 1 h 45. Sans conversion en UTC, on pourrait croire à tort que la désactivation est arrivée avant certaines actions malveillantes."),
    mistakes("mélanger des heures locales et UTC dans la même chronologie ; ouvrir directement un fichier suspect sur le poste de travail au lieu d’en faire une copie ; signaler un incident sans dire quel compte ou quel actif est concerné ; considérer une adresse IP ou un domaine comme preuve absolue sans contexte supplémentaire."),
    safety("préserver une preuve ne t’autorise pas à fouiller n’importe quel système. Agis dans ton périmètre, respecte les règles internes et documente qui a manipulé quoi, quand et pour quelle raison."),
    takeaway("détecter, c’est recouper des signaux imparfaits. Signaler, c’est transmettre des faits exploitables. Préserver les preuves, c’est protéger la chronologie et l’intégrité de ce que tu observeras ensuite."),
    practice("ouvre « Incident : un compte de messagerie compromis », reconstruis la chronologie des journaux et note les preuves à conserver avant toute action irréversible. Termine par le quiz de la leçon."),
    reference("nistIncident"),
    reference("anssiHygiene"),
    reference("cybermalveillance"),
  ],
  quiz: {
    title: "Quiz : détection et preuves",
    questions: [
      questions.choice("Quel énoncé ressemble le plus à un bon signalement initial ?", ["« Aidez-moi vite »", "« Problème inconnu »", "« À 10 h 12, le compte de Nadia a envoyé des courriels non reconnus depuis la messagerie web »", "« Le réseau est bizarre depuis longtemps »"], 2, "Ce signalement précise quand, qui, où et quoi. Les autres formulations sont trop vagues pour aider à qualifier l’incident ou à retrouver les bons journaux sans perdre du temps.", "facile"),
      questions.tf("Pour comparer des journaux issus de plusieurs systèmes, convertir toutes les heures en UTC peut éviter des erreurs d’interprétation.", true, "Vrai : quand les sources n’utilisent pas le même fuseau, l’UTC fournit un repère commun. Sans cette conversion, une action peut sembler antérieure ou postérieure alors que seul l’affichage diffère.", "moyen"),
      questions.multi("Quelles pratiques aident à préserver des preuves exploitables ? (plusieurs réponses)", ["Travailler sur une copie quand c’est possible", "Noter qui a manipulé la preuve et quand", "Supprimer les journaux déjà lus pour éviter les doublons", "Vérifier l’intégrité d’un fichier par une empreinte quand c’est pertinent"], [0, 1, 3], "Copier, tracer la manipulation et contrôler l’intégrité renforcent la valeur de la preuve. Supprimer les journaux lus détruit au contraire des éléments qui peuvent devenir utiles plus tard, même s’ils semblent banals au premier regard.", "moyen"),
      questions.choice("Si un journal affiche « 10:25+02:00 » et qu’un autre affiche « 09:50Z », quelle conclusion est correcte après conversion ?", ["10:25+02:00 est après 09:50Z", "10:25+02:00 correspond à 08:25Z, donc avant 09:50Z", "Les deux heures sont incomparables", "09:50Z signifie heure locale du poste"], 1, "Le décalage +02:00 signifie qu’il faut retrancher deux heures pour obtenir l’UTC : 10:25+02:00 devient 08:25Z. L’événement de 08:25Z est donc antérieur à 09:50Z.", "difficile"),
    ],
  },
};

const auditHygieneLesson: NewLesson = {
  key: "fond-audit-hygiene",
  title: "Auditer l’hygiène d’une petite structure : méthode et rapport",
  summary: "Apprends à cadrer un audit d’hygiène, à collecter des constats factuels, à noter des contrôles avec pondération et à restituer des recommandations utiles sans accusation inutile.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("définir le périmètre d’un audit avec accord écrit, suivre une méthode simple en cinq étapes, collecter des preuves factuelles, calculer un score de conformité pondéré, et rédiger un rapport court mais exploitable."),
    prerequisites("avoir suivi « Évaluer un risque : actifs, menaces, vulnérabilités » et « Politiques de sécurité, sensibilisation et culture de la sécurité », ou déjà savoir prioriser des constats et formuler des actions."),
    scenario("Chantal doit auditer l’hygiène numérique du Cabinet Moussa avant l’ouverture d’un nouveau service en ligne. Le budget est limité, le personnel est peu nombreux et la direction veut « savoir où agir vite ». Chantal ne doit ni faire un test d’intrusion sauvage, ni livrer un rapport flou. Elle a besoin d’une méthode claire, de preuves concrètes et d’un langage compréhensible par la direction."),
    videoSlot("Audit d’hygiène : constater, noter, prioriser, restituer"),
    text("Auditer l’hygiène d’une petite structure, c’est vérifier si les pratiques de base sont tenues de façon régulière. Avant de commencer, il faut cadrer le périmètre et l’accord écrit : quels sites, quels postes, quels comptes, quels horaires, quelles limites. Sans cela, tu risques d’examiner trop, pas assez, ou sans autorisation. L’audit d’hygiène n’est pas un jugement moral. C’est un constat structuré qui relie des preuves, des risques et des recommandations réalistes."),
    figure({
      kind: "steps",
      title: "Méthode en 5 étapes",
      numbered: true,
      items: [
        { title: "Cadrer" },
        { title: "Inventorier" },
        { title: "Constater" },
        { title: "Évaluer" },
        { title: "Restituer" },
      ],
    }),
    text("La grille de contrôle peut couvrir au minimum : comptes et mots de passe, mises à jour et antivirus, sauvegardes, réseau et Wi-Fi, données personnelles, sensibilisation, gestion des incidents. Pour chaque point, tu cherches une preuve : observation, entretien, capture d’écran, export de configuration, journal, procédure écrite. Un constat solide ressemble à ceci : « sur 12 postes, 4 n’ont pas reçu les mises à jour critiques depuis plus de 30 jours ». Un constat faible ressemble à ceci : « la sécurité est moyenne ». Le premier se vérifie, le second se discute sans fin."),
    figure({
      kind: "formula",
      title: "Notation simple",
      items: [
        { label: "Conforme", formula: "1", tone: "green" },
        { label: "Partiel", formula: "0,5", tone: "amber" },
        { label: "Non conforme", formula: "0", tone: "red" },
        { label: "Score domaine", formula: "somme pondérée / poids total", tone: "blue" },
      ],
    }),
    text("La pondération aide à ne pas traiter tous les contrôles comme s’ils avaient le même poids. Une petite structure peut considérer que la double authentification, les sauvegardes testées et la revue des droits sont plus critiques qu’un point cosmétique. Après la note, il faut prioriser selon le risque et l’effort. Certains gains rapides valent beaucoup : activer la double authentification, retirer un compte partagé, changer le mot de passe de la box, vérifier une restauration. L’audit devient utile quand il débouche sur un plan d’action : quoi, qui, quand, coût ou effort estimé."),
    text("Démonstration guidée : prépare le squelette du rapport avant même la visite. Tu gagneras du temps et tu éviteras d’oublier une rubrique importante. Pendant l’audit, remplis les sections avec des faits observés, pas avec des impressions. Si un point n’a pas pu être vérifié, écris-le explicitement au lieu d’inventer une note."),
    code("Rapport d’audit d’hygiène\n1. Résumé pour la direction\n2. Périmètre et limites\n3. Méthode et sources de preuve\n4. Constats par domaine\n5. Score et priorités\n6. Plan d’action : quoi, qui, quand, effort\n7. Annexes : captures, extraits, inventaire", "text"),
    example("Exemple corrigé : pour le domaine « gestion des accès », Chantal pondère trois contrôles. MFA sur la messagerie, poids 5, partiel : 5 × 0,5 = 2,5. Sauvegardes des codes de secours administrateur, poids 3, conforme : 3 × 1 = 3. Revue trimestrielle des droits, poids 2, non conforme : 2 × 0 = 0. Le score du domaine vaut donc (2,5 + 3 + 0) ÷ 10 = 55 %. La priorité logique n’est pas de refaire le rapport, mais de compléter le MFA et d’instaurer la revue des droits."),
    mistakes("juger sans preuve observable ; écrire des recommandations vagues comme « améliorer la sécurité » ; oublier les gains rapides au profit d’un plan trop ambitieux ; diffuser le rapport sans précaution alors qu’il contient parfois des faiblesses sensibles."),
    safety("n’audite qu’avec un accord explicite et reste dans le périmètre convenu. Protège le rapport comme un document sensible : il peut décrire des faiblesses exploitables s’il circule sans contrôle."),
    takeaway("un audit d’hygiène utile est court, factuel et priorisé. La valeur vient des preuves, de la pondération assumée et d’un plan d’action concret. Le rapport doit aider à décider, pas seulement à archiver."),
    practice("prépare-toi à « Projet final : auditer la sécurité du Centre Numérique Soleil » en t’exerçant à noter un domaine, à justifier les preuves et à rédiger des recommandations précises. Termine par le quiz de la leçon."),
    reference("anssiHygiene"),
    reference("nistSmallBusiness"),
    reference("cnilPostes"),
  ],
  quiz: {
    title: "Quiz : audit d’hygiène",
    questions: [
      questions.choice("Quel élément doit être clarifié avant de lancer l’audit ?", ["Le nom du document final uniquement", "Le périmètre et l’accord écrit", "Le modèle du fond d’écran des auditeurs", "La couleur des tableaux du rapport"], 1, "Sans périmètre clair ni accord écrit, tu risques d’auditer sans autorisation ou de produire un résultat inutile. Les autres éléments sont secondaires par rapport au cadre et aux limites de la mission.", "facile"),
      questions.tf("Le constat « la sécurité est moyenne » est suffisant pour justifier une recommandation.", false, "Faux : ce constat n’est ni mesurable ni vérifiable. Un audit crédible s’appuie sur des faits observables, comme un nombre de postes non à jour, un contrôle absent ou une procédure introuvable.", "moyen"),
      questions.multi("Quelles pratiques rendent un rapport d’audit plus utile ? (plusieurs réponses)", ["Associer chaque constat à une preuve", "Prioriser par risque et effort", "Noter « non conforme » quand un point n’a pas été vérifié pour aller plus vite", "Formuler un plan d’action avec responsable et échéance"], [0, 1, 3], "Une preuve, une priorité et un plan d’action rendent le rapport exploitable. En revanche, déclarer « non conforme » sans vérification fabrique une certitude artificielle et affaiblit la crédibilité de l’audit.", "moyen"),
      questions.choice("Un domaine obtient 55 % après pondération. Quelle réaction est la plus pertinente ?", ["Supprimer le domaine du rapport, car 55 % n’est pas un vrai chiffre", "Chercher d’abord les mesures à fort effet, comme compléter le MFA et organiser la revue des droits", "Conclure que tout va bien car le score dépasse 50 %", "Refaire toute la mission jusqu’à obtenir 100 %"], 1, "Le score sert à prioriser, pas à humilier ni à rassurer artificiellement. Un 55 % signale des écarts significatifs : il faut cibler les mesures les plus utiles plutôt que nier le résultat ou poursuivre une perfection irréaliste.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c1:7",
    position: 7,
    title: "Risques, données personnelles et conformité",
    description: "Tu relies ici l’analyse de risques aux obligations de protection des données et à l’organisation quotidienne de la sécurité. Critères de réussite : construire un registre de risques lisible ; distinguer les principes, droits et obligations liés aux données personnelles ; proposer des règles et indicateurs réalistes pour une petite structure.",
    lessons: [risquesLesson, donneesPersonnellesLesson, gouvernanceLesson],
  },
  {
    key: "c1:8",
    position: 8,
    title: "Réagir à un incident",
    description: "Ce module t’apprend à passer du signal au plan d’action, puis du constat à la restitution utile sans casser les preuves ni improviser le droit. Critères de réussite : conduire une réponse à incident en six étapes ; reconstruire une chronologie fiable et préserver les preuves ; produire un audit d’hygiène factuel avec score et recommandations.",
    lessons: [reponseIncidentLesson, detecterPreuvesLesson, auditHygieneLesson],
  },
];
