import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const permissionsLesson: NewLesson = {
  key: "l-c3-2",
  title: "Les permissions : lire, calculer et modifier les droits",
  summary: "Lis une ligne « ls -l », convertis un mode symbolique en octal, applique « chmod » proprement et choisis des droits cohérents au lieu du réflexe dangereux « 777 ».",
  minutes: 24,
  xp: 65,
  upgrade: true,
  blocks: [
    goals("lire une ligne « ls -l », distinguer propriétaire, groupe et autres, calculer un mode octal, modifier les droits avec « chmod », puis choisir un réglage minimal adapté à un fichier ou à un dossier."),
    prerequisites("avoir suivi « Naviguer dans le système de fichiers Linux » ou déjà savoir te déplacer dans l’arborescence et lire un nom de fichier."),
    scenario("Awa reçoit un script de sauvegarde qui ne s’exécute pas, tandis qu’un dossier partagé laisse n’importe qui supprimer les fichiers. Elle ne veut ni bloquer le travail de l’équipe, ni ouvrir la porte à une erreur ou à un abus. Pour corriger cela, elle doit lire les droits Linux comme une fiche d’identité, puis les ajuster sans improviser."),
    videoSlot("Comprendre « rwx » et éviter le piège de « 777 »"),
    text("Sous Linux, chaque fichier ou dossier a trois catégories de droits : le propriétaire, le groupe et les autres. Tu les lis souvent avec « ls -l ». La première colonne commence par le type, puis trois triplets « rwx ». Pour un fichier, « r » permet de lire, « w » de modifier, « x » d’exécuter. Pour un dossier, le sens change un peu : « r » liste les noms, « w » crée, renomme ou supprime des entrées avec « x », et « x » autorise la traversée par le nom. Cette différence est essentielle en sécurité : un dossier trop ouvert expose parfois plus qu’un fichier trop ouvert."),
    schema("Type et droits d’une ligne « ls -l »\n-rwxr-x--- 1 awa admins 1540 Jun  7 09:15 sauvegarde.sh\n||||||||||\n|--------- type : - = fichier, d = dossier, l = lien\n |||------ propriétaire : rwx = 7\n    |||--- groupe : r-x = 5\n       ||| autres : --- = 0\nMode octal : 750"),
    text("Le calcul octal sert à aller vite. Chaque triplet additionne « r=4 », « w=2 », « x=1 ». Ainsi, « rw-r----- » vaut 640 et « rwxr-x--- » vaut 750. Tu verras souvent 644 pour un document lisible mais non exécutable, 600 pour une clé privée, 755 pour un script ou un dossier traversable, 700 pour un dossier personnel très fermé, et 640 pour un fichier de service lisible seulement par son groupe. Pour corriger un propriétaire ou un groupe erroné, tu complètes « chmod » avec « chown utilisateur:groupe fichier » ou « chgrp groupe fichier ». Le bon réflexe n’est pas « donner tous les droits », mais « donner seulement ce qui est nécessaire ». Le SUID existe aussi, mais nous le détaillerons dans « linux-droits-speciaux » car il change le contexte d’exécution, pas seulement la lecture ou l’écriture."),
    schema("Modes utiles à retenir\n644  -> rw-r--r--  fichier lisible par tous, modifiable par son propriétaire\n600  -> rw-------  clé privée, jeton, secret local\n755  -> rwxr-xr-x  dossier traversable ou script exécutable\n700  -> rwx------  dossier personnel sensible\n640  -> rw-r-----  journal ou configuration pour un groupe précis"),
    text("Démonstration guidée : fais tes essais dans un dossier de test, sur ta machine, une machine virtuelle, WSL ou Termux. Crée deux fichiers vides, applique d’abord un mode trop strict puis un mode adapté, et relis immédiatement la colonne des droits. Ce va-et-vient entre commande et observation t’évite de réciter des nombres sans comprendre leur effet."),
    code("# Préparer un dossier de test\nmkdir -p /tmp/demo-droits\ncd /tmp/demo-droits\n\n# Créer deux fichiers vides\n: > notes.txt\n: > sauvegarde.sh\n\n# Appliquer des droits adaptés\nchmod 640 notes.txt\nchmod 750 sauvegarde.sh\nls -l\n# exemple de sortie (valeurs fictives)\n# -rw-r----- 1 awa admins    0 Jun  7 09:15 notes.txt\n# -rwxr-x--- 1 awa admins    0 Jun  7 09:15 sauvegarde.sh\n\n# Ajuster symboliquement\nchmod go-rwx notes.txt\nchmod u+x sauvegarde.sh\nls -l notes.txt sauvegarde.sh\n# exemple de sortie (valeurs fictives)\n# -rw------- 1 awa admins    0 Jun  7 09:16 notes.txt\n# -rwxr-x--- 1 awa admins    0 Jun  7 09:16 sauvegarde.sh", "bash"),
    example("Exemple corrigé : « -rw-r----- » vaut 640, car 4+2 pour le propriétaire, 4 pour le groupe, 0 pour les autres. « drwxr-xr-x » vaut 755 et convient souvent à un dossier parcouru par plusieurs comptes. « -rwx------ » vaut 700 et limite l’accès au seul propriétaire. Si un collègue propose « chmod 777 » sur un script de sauvegarde pour “que ça marche”, refuse : tout le monde pourrait le modifier ou l’exécuter, ce qui viole le moindre privilège."),
    mistakes("confondre les droits d’un fichier et ceux d’un dossier ; retenir « 755 » ou « 644 » par cœur sans savoir les relire ; utiliser « 777 » comme pansement rapide ; lancer un « chmod -R » sans vérifier le dossier visé et les conséquences sur toute l’arborescence."),
    safety("travaille sur ta propre machine, une machine virtuelle ou un conteneur de test. N’élargis jamais des droits sur un système de production sans autorisation et sans savoir qui dépend du fichier, sinon tu peux créer une faille ou casser un service."),
    takeaway("les droits Linux se lisent en trois triplets : propriétaire, groupe, autres. Le calcul octal n’est qu’un raccourci pour exprimer « rwx ». Le bon réglage est le plus petit ensemble de droits qui permet le travail attendu."),
    practice("dans « TP 2 : auditer les droits, les comptes et sudo », entraîne-toi à traduire des lignes « ls -l » en modes octaux, à repérer un fichier trop ouvert et à justifier une correction. Termine par le quiz de la leçon."),
    reference("ubuntuFrPermissions"),
    reference("linuxCommandBook"),
    reference("anssiLinux"),
  ],
  quizExtension: {
    improve: [
      "La permission « r » signifie bien lecture. Sur un fichier, elle permet d’en lire le contenu. Sur un dossier, elle permet surtout d’en lister les noms. L’option « exécuter » correspond à « x », et « supprimer tous les comptes » n’a aucun rapport avec les droits Unix.",
      "Limiter les permissions applique le moindre privilège : chaque personne ou service reçoit seulement ce qui lui est utile. Donner tous les droits à tous simplifie parfois un dépannage de quelques minutes, mais crée ensuite un risque durable d’erreur, de fuite ou de modification malveillante.",
    ],
    add: [
      questions.choice("Tu lis la ligne « -rw-r----- 1 awa admins 812 rapport.txt ». Qui peut écrire dans ce fichier ?", ["Le groupe « admins »", "Tous les utilisateurs de la machine", "Seulement le propriétaire « awa »", "Personne, car le fichier n’est pas exécutable"], 2, "Le premier triplet « rw- » donne lecture et écriture au propriétaire. Le groupe n’a ici que « r-- », donc lecture seule, et les autres n’ont aucun droit. L’absence de bit d’exécution ne bloque pas l’écriture : ce sont deux usages différents.", "moyen"),
      questions.multi("Le mode « 750 » donne quels droits ? (plusieurs réponses)", ["Le propriétaire peut lire, écrire et exécuter", "Le groupe peut lire et exécuter, mais pas écrire", "Les autres peuvent lire le fichier", "Les autres n’ont aucun droit"], [0, 1, 3], "Le calcul « 7, 5, 0 » correspond à « rwx », « r-x », « --- ». Le piège classique consiste à croire que le groupe reçoit aussi l’écriture parce qu’il est “proche” du propriétaire, ou que « 0 » veut dire “lecture seule”, alors qu’il signifie aucun droit.", "difficile"),
    ],
  },
};

const usersLesson: NewLesson = {
  key: "linux-utilisateurs",
  title: "Utilisateurs, groupes et fichiers de comptes",
  summary: "Comprends ce que racontent « /etc/passwd », « /etc/shadow » et « /etc/group », puis repère les comptes à risque avant qu’ils ne deviennent un problème.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer compte humain, compte système et compte de service, lire une ligne de « /etc/passwd » et de « /etc/shadow », vérifier UID et groupes, puis repérer des anomalies simples lors d’un audit."),
    prerequisites("avoir compris les permissions Linux de base et savoir qu’un service ne doit pas disposer de plus de droits que nécessaire."),
    scenario("Nadia rejoint Baobab Tech et découvre un vieux serveur Debian partagé par plusieurs collègues. Certains scripts tournent encore avec des comptes oubliés, et un ancien stagiaire a peut-être laissé un accès trop large. Avant de supprimer quoi que ce soit, Nadia doit lire correctement les fichiers de comptes et comprendre quels utilisateurs sont humains, système ou techniques."),
    videoSlot("Lire « passwd » et « shadow » sans te tromper"),
    text("Un compte Linux n’est pas toujours une personne. Les comptes humains servent à ouvrir une session. Les comptes système et de service lancent des tâches ou des programmes avec un périmètre réduit. L’identité réelle d’un compte repose sur son UID et son GID, pas seulement sur son nom. L’UID 0 est particulier : il donne les privilèges de root, même si le compte ne s’appelle pas « root ». Sur Debian et Ubuntu, les comptes ordinaires commencent souvent à 1000, tandis que beaucoup de comptes techniques sont en dessous."),
    schema("Fichier             Rôle principal\n/etc/passwd        identité du compte, UID, GID, dossier, shell\n/etc/shadow        empreinte du mot de passe et règles d’expiration\n/etc/group         groupes et membres secondaires\nCommandes utiles   whoami, id, groups, who, w, last, lastlog"),
    text("Une ligne de « /etc/passwd » comporte sept champs : nom, mot de passe historique, UID, GID, commentaire, dossier personnel et shell. Le plus souvent, le deuxième champ vaut « x » : cela signifie que l’empreinte du mot de passe est stockée dans « /etc/shadow ». Le shell final dit si le compte ouvre une vraie session. Un compte de service sain utilise souvent « /usr/sbin/nologin », « /sbin/nologin » ou « /bin/false » pour empêcher une connexion interactive."),
    schema("Exemple « /etc/passwd »\nawa:x:1001:1001:Awa Diop:/home/awa:/bin/bash\n|   | |    |    |        |         |\n|   | |    |    |        |         +-- shell\n|   | |    |    |        +------------ dossier personnel\n|   | |    |    +--------------------- commentaire\n|   | |    +-------------------------- GID principal\n|   | +------------------------------- UID\n|   +--------------------------------- empreinte dans shadow\n+------------------------------------- nom du compte"),
    text("« /etc/shadow » garde l’information sensible : une empreinte de mot de passe, puis des nombres liés au vieillissement. Le deuxième champ peut commencer par « $y$ » pour yescrypt, « $6$ » pour SHA-512-crypt, « $5$ » pour SHA-256-crypt, ou par un autre identifiant d’algorithme. Un « ! » signifie compte verrouillé pour la connexion par mot de passe. Un « * » signale qu’aucun mot de passe utilisable n’est prévu. Le cas grave est le champ vide : il n’y a alors pas de mot de passe. Le troisième champ compte les jours depuis le 1er janvier 1970. Par exemple, 20360 jours correspondent au 29 septembre 2025 : ce n’est pas une heure lisible pour un humain, mais c’est suffisant pour les outils comme « chage -l »."),
    text("Le fichier « /etc/group » complète cette lecture avec des lignes « nom:x:GID:membres ». C’est là que tu retrouves les groupes secondaires. Pour administrer proprement, retiens surtout quelques actions : « adduser » ou « useradd » créent un compte, « usermod -aG sudo awa » ajoute un groupe sans effacer les autres, « passwd » change un mot de passe, « passwd -l » le verrouille, « userdel » supprime un compte, et « chage -l awa » lit la politique d’expiration. En audit, cherche les UID 0 multiples, les comptes de service avec shell interactif, les comptes jamais utilisés et les champs de mot de passe vides."),
    text("Démonstration guidée : commence par ton identité réelle, puis lis trois exemples commentés. Sur WSL, une machine virtuelle ou un vrai Linux, « id » et « groups » fonctionnent sans danger. La lecture de « /etc/shadow » demande en revanche les droits d’administration et reste à réserver à ta machine ou à un serveur de test autorisé."),
    code("# Voir ton identité et tes groupes\nwhoami\nid\ngroups\n\n# Lire quelques comptes\ngetent passwd | head -3\nsudo getent shadow | head -3\n# exemple de sortie (valeurs fictives)\n# root:x:0:0:root:/root:/bin/bash\n# awa:x:1001:1001:Awa Diop:/home/awa:/bin/bash\n# backup:x:998:998:Sauvegarde:/var/backups:/usr/sbin/nologin\n# root:$y$j9T$sel$abcd...:20310:0:99999:7:::\n# awa:$y$j9T$sel$efgh...:20360:0:99999:7:::\n# backup:!:20310:0:99999:7:::\n\n# Voir le vieillissement d’un compte\nsudo chage -l awa", "bash"),
    example("Exemple corrigé : « audit:x:0:0:Compte audit:/home/audit:/bin/bash » est risqué, car ce compte possède l’UID 0. « nadia::20360:0:99999:7::: » est critique, car le champ de mot de passe est vide. « backup:!:20310:0:99999:7::: » est au contraire cohérent pour un compte technique verrouillé. Lors d’un audit, cherche d’abord les UID 0 multiples, les shells interactifs inutiles et les champs de mot de passe vides."),
    mistakes("croire qu’un nom de compte suffit à juger son niveau de privilège ; oublier que « usermod -aG » a besoin du « -a » pour ajouter un groupe sans effacer les autres ; supprimer un compte sans vérifier s’il possède des fichiers ; considérer qu’un compte verrouillé avec « ! » est identique à un champ vide, alors que le premier est défensif et le second dangereux."),
    safety("ne modifie des comptes que sur ta propre machine, une machine virtuelle ou un serveur pour lequel tu as une autorisation écrite. Un changement de groupe, de shell ou d’expiration peut bloquer un service ou un collègue si tu agis sans préparation."),
    takeaway("les fichiers « passwd », « shadow » et « group » racontent qui est qui et comment un compte peut se connecter. L’UID 0 prime sur le nom, un shell interactif doit être justifié, et un champ de mot de passe vide exige une correction immédiate."),
    practice("dans « TP 2 : auditer les droits, les comptes et sudo », lis des extraits de « passwd », « shadow » et « group », puis classe les comptes en humains, services ou anomalies à corriger. Termine par le quiz de la leçon."),
    reference("ubuntuFrUsers"),
    reference("debianHandbook"),
    reference("anssiLinux"),
  ],
  quiz: {
    title: "Quiz : utilisateurs, groupes et fichiers de comptes",
    questions: [
      questions.choice("Que signifie surtout l’UID 0 sous Linux ?", ["Le compte appartient au premier utilisateur créé", "Le compte possède les privilèges de root", "Le compte ne peut jamais ouvrir de session", "Le compte appartient obligatoirement au groupe « sudo »"], 1, "L’UID 0 donne les privilèges de root, quel que soit le nom du compte. Le piège est de croire que seul le nom « root » compte, alors qu’un autre nom avec UID 0 serait tout aussi puissant et donc tout aussi sensible.", "facile"),
      questions.choice("Lis la ligne « backup:x:998:998:Sauvegarde:/var/backups:/usr/sbin/nologin ». Quelle conclusion est la plus cohérente ?", ["C’est probablement un compte de service sans connexion interactive", "C’est un compte humain prêt à travailler dans un terminal", "Le compte possède forcément les droits de root", "Le mot de passe est vide"], 0, "Le shell « /usr/sbin/nologin » indique qu’on ne veut pas de session interactive. Les champs UID et GID inférieurs à 1000 vont souvent dans le même sens. Rien n’indique ici un mot de passe vide ni un privilège root.", "moyen"),
      questions.multi("Quelles situations demandent une vérification prioritaire lors d’un audit ? (plusieurs réponses)", ["Un compte avec UID 0 supplémentaire", "Un champ de mot de passe vide dans « /etc/shadow »", "Un compte de service avec « /bin/bash » sans justification", "Un compte verrouillé avec « ! » pour un service"], [0, 1, 2], "Un UID 0 supplémentaire, un mot de passe vide et un shell interactif inutile élargissent tous la surface d’attaque. Le compte verrouillé avec « ! » est au contraire souvent une bonne mesure pour un service qui n’a pas besoin de se connecter.", "difficile"),
      questions.tf("Oublier le « -a » dans « usermod -aG sudo awa » peut retirer des groupes secondaires existants.", true, "Vrai : sans « -a », l’option « -G » remplace la liste des groupes secondaires au lieu d’ajouter un nouveau groupe. L’erreur semble minime, mais elle peut casser des accès nécessaires à des partages ou à des applications.", "moyen"),
    ],
  },
};

const sudoLesson: NewLesson = {
  key: "linux-sudo",
  title: "sudo, su et root : élever ses droits proprement",
  summary: "Utilise « sudo » sans transformer chaque maintenance en session root permanente, puis lis une règle « sudoers » avec l’œil d’un auditeur.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer pourquoi root doit rester exceptionnel, distinguer « sudo », « sudo -i » et « su - », lire une règle « sudoers », vérifier ses droits avec « sudo -l », puis repérer une délégation dangereuse."),
    prerequisites("savoir lire des comptes Linux et comprendre le principe du moindre privilège."),
    scenario("Moussa administre deux petites machines pour l’association Teranga. Un collègue lui demande un accès complet à root “pour gagner du temps”, tandis qu’un autre script redémarre un service web plusieurs fois par jour. Moussa veut déléguer juste ce qu’il faut, sans laisser un raccourci qui ouvrirait toute la machine."),
    videoSlot("Élever ses droits sans vivre en root"),
    text("Le compte root peut presque tout faire. C’est précisément pour cela qu’il doit être utilisé le moins possible. Une erreur de frappe, un mauvais chemin ou un script lancé trop vite ont alors un impact maximal. « sudo » élève les droits pour une commande précise, puis rend la main. « sudo -i » ouvre un shell proche d’une session root. « su - » bascule vers un autre compte, souvent root, avec son environnement complet. En pratique, un défenseur préfère garder une trace claire et un périmètre réduit avec « sudo » plutôt qu’une habitude de travail permanente en root."),
    schema("Commande        Effet principal\nsudo cmd       élève une seule commande\nsudo -l        liste ce que tu peux faire\nsudo -i        ouvre un shell root de maintenance\nsu -           ouvre une session d’un autre compte\nvisudo         édite sudoers avec vérification de syntaxe"),
    text("Sur Debian et Ubuntu, l’accès « sudo » passe souvent par le groupe « sudo ». Sur RHEL et Fedora, on parle plutôt de « wheel ». Les règles vivent dans « /etc/sudoers » et dans « /etc/sudoers.d/ ». On ne modifie pas ces fichiers avec un éditeur ordinaire : « visudo » teste la syntaxe avant d’enregistrer, ce qui évite de se bloquer hors de la machine. Une règle décrit qui peut agir, sur quelle machine, comme quel utilisateur cible, et sur quelles commandes."),
    schema("Exemples de règles\nawa ALL=(ALL:ALL) ALL\n%admins ALL=(root) /usr/bin/systemctl restart nginx\n%sauvegarde ALL=(root) NOPASSWD: /usr/local/bin/backup.sh\n\nLecture rapide\nqui          où    = (comme qui) commande autorisée"),
    text("Le danger commence quand une règle semble pratique, mais ouvre beaucoup plus que prévu. « NOPASSWD: ALL » supprime toute friction pour toutes les commandes. Autoriser un éditeur interactif, un pager ou une commande comme « find » peut aussi être risqué si elle sait lancer d’autres commandes. Tu n’as pas besoin de connaître des astuces offensives pour comprendre le principe : si la commande autorisée peut ouvrir un shell ou écrire n’importe où, elle élargit fortement le pouvoir réel de l’utilisateur. La parade consiste à autoriser des commandes précises, avec des chemins complets, et à préférer « sudoedit » pour l’édition contrôlée."),
    text("Démonstration guidée : sur ta machine de test, commence par voir tes droits avec « sudo -l ». Lis ensuite une petite règle dédiée à un service, puis regarde les traces de journal. Selon la distribution, tu trouveras ces traces dans le journal systemd, dans « /var/log/auth.log » ou dans « /var/log/secure ». Tu peux reproduire cette lecture sur une machine virtuelle ou un vrai serveur dont tu es responsable."),
    code("# Voir les droits sudo disponibles\nsudo -l\n# exemple de sortie (valeurs fictives)\n# User awa may run the following commands on web01:\n#     (root) /usr/bin/systemctl restart nginx\n#     (root) /usr/bin/systemctl status nginx\n\n# Éditer une règle dédiée sans casser la syntaxe\nsudo visudo -f /etc/sudoers.d/nginx-maintenance\n\n# Lire les traces récentes\nsudo journalctl -b _COMM=sudo --since \"1 hour ago\"\n# ou selon la distribution\nsudo tail -n 20 /var/log/auth.log", "bash"),
    example("Exemple corrigé : « awa ALL=(ALL:ALL) ALL » donne un pouvoir très large, mais reste plus traçable qu’un mot de passe root partagé. « %admins ALL=(root) /usr/bin/systemctl restart nginx » est ciblé et raisonnable si le groupe est bien géré. « %staff ALL=(root) NOPASSWD: ALL » est dangereux : toute personne du groupe devient root sans contrôle. « awa ALL=(root) /usr/bin/vim /etc/nginx/nginx.conf » paraît précis, mais l’éditeur interactif mérite une relecture sérieuse, car il sait faire bien plus qu’ouvrir un fichier."),
    mistakes("modifier « sudoers » sans « visudo » ; autoriser « ALL » parce qu’un dépannage presse ; oublier les chemins complets des commandes ; confondre « sudo -i » utile pour une maintenance courte et habitude de travailler toute la journée en root."),
    safety("n’accorde des droits sudo que sur ta propre machine, une machine de test ou un serveur pour lequel tu as une autorisation écrite. Une règle trop large peut offrir un accès complet à une personne qui n’en avait pas besoin."),
    takeaway("« sudo » sert à élever des droits de façon ciblée et journalisée. Une bonne règle délègue une action précise, avec un chemin clair et un groupe maîtrisé. Le vrai risque vient des règles larges ou des commandes capables d’en lancer beaucoup d’autres."),
    practice("dans « TP 2 : auditer les droits, les comptes et sudo », classe des règles « sudoers » selon leur risque, vérifie si elles respectent le moindre privilège et justifie une correction réaliste. Termine par le quiz de la leçon."),
    reference("ubuntuFrSudo"),
    reference("debSudoers"),
    reference("anssiLinux"),
  ],
  quiz: {
    title: "Quiz : sudo, su et root",
    questions: [
      questions.choice("Pourquoi un administrateur prudent évite-t-il de travailler en root toute la journée ?", ["Parce que root ne peut pas lire les journaux", "Parce qu’une erreur commise avec tous les privilèges a un impact maximal", "Parce que root ne peut pas redémarrer de service", "Parce que root ne peut pas utiliser de shell"], 1, "Le vrai problème n’est pas que root manque de capacités, mais qu’il en a trop. Une faute de frappe, un mauvais script ou un effacement lancé avec ces privilèges touche tout le système. « sudo » réduit ce risque en limitant l’élévation à l’action nécessaire.", "facile"),
      questions.choice("Que permet surtout « sudo -l » ?", ["Lister les groupes du système", "Voir les commandes sudo autorisées pour le compte courant", "Créer une nouvelle règle dans « sudoers »", "Changer le mot de passe de root"], 1, "« sudo -l » interroge la politique sudo et affiche ce que le compte peut lancer. C’est utile autant pour l’utilisateur que pour l’auditeur. Le piège est de le confondre avec un outil d’édition ou d’administration des groupes.", "moyen"),
      questions.multi("Quelles règles ou pratiques méritent une vigilance particulière ? (plusieurs réponses)", ["« NOPASSWD: ALL » pour un groupe large", "Autoriser un éditeur interactif sans réflexion", "Modifier « sudoers » avec « visudo »", "Utiliser des chemins complets dans les règles"], [0, 1], "« NOPASSWD: ALL » et les commandes interactives élargissent beaucoup le pouvoir réel accordé. Au contraire, « visudo » et les chemins complets sont de bonnes pratiques qui réduisent les erreurs et les ambiguïtés.", "difficile"),
      questions.tf("Sur Debian ou Ubuntu, les commandes sudo laissent généralement des traces consultables dans le journal ou dans « /var/log/auth.log ».", true, "Vrai : sudo journalise normalement les élévations et les commandes exécutées, ce qui aide autant le dépannage que l’audit. Penser qu’une action sudo est invisible serait une erreur de compréhension du mécanisme.", "moyen"),
    ],
  },
};

const specialRightsLesson: NewLesson = {
  key: "linux-droits-speciaux",
  title: "SUID, SGID, sticky bit, umask et ACL",
  summary: "Va au-delà des trois triplets « rwx » : comprends les bits spéciaux, calcule l’effet d’une « umask » et reconnais une délégation fine avec ACL.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("reconnaître SUID, SGID et sticky bit, expliquer quand ils sont utiles ou dangereux, calculer l’effet d’une « umask », lire un « + » d’ACL dans « ls -l », puis vérifier un cas simple avec « getfacl »."),
    prerequisites("avoir suivi la leçon sur les permissions Linux classiques et savoir traduire un mode octal simple."),
    scenario("Koffi audite un serveur de fichiers partagé. Il voit « /tmp » en « drwxrwxrwt », un dossier de travail en « 2775 » et un binaire SUID oublié dans « /usr/local/bin ». Pour décider ce qui est normal et ce qui doit être corrigé, il doit connaître les bits spéciaux, pas seulement les triplets « rwx »."),
    videoSlot("Les bits spéciaux Linux sans jargon inutile"),
    text("Les bits spéciaux complètent les droits classiques. Le SUID, valeur octale 4000, fait exécuter un programme avec les droits de son propriétaire. Le SGID, 2000, donne les droits du groupe propriétaire au programme et, sur un dossier, force les nouveaux fichiers à hériter du groupe. Le sticky bit, 1000, change surtout le comportement des dossiers partagés : dans un dossier comme « /tmp », tout le monde peut créer, mais seuls le propriétaire du fichier, le propriétaire du dossier ou root peuvent supprimer ou renommer."),
    schema("Bits spéciaux et affichage\n4755  -> -rwsr-xr-x  SUID actif\n2755  -> -rwxr-sr-x  SGID actif\n1777  -> drwxrwxrwt  sticky bit sur dossier partagé\nSi « x » manque : S ou T au lieu de s ou t"),
    text("Tous ces bits ne sont pas suspects. « /usr/bin/passwd » est légitimement SUID root, car un utilisateur ordinaire doit modifier sa propre empreinte stockée dans « /etc/shadow ». En revanche, un programme maison SUID placé dans « /usr/local/bin » mérite une revue sévère : il fait confiance à quiconque l’exécute avec les droits de son propriétaire. En audit, compare toujours la présence d’un SUID ou d’un SGID au besoin métier réel."),
    text("La « umask » agit au moment de la création. Elle retire des droits par défaut, elle n’en ajoute jamais. Avec « 022 », un fichier ordinaire naît en 644 et un dossier en 755. Avec « 027 », tu obtiens 640 et 750. Avec « 077 », tu fermes à 600 et 700. Les ACL, elles, servent à déléguer finement un droit à un utilisateur ou à un groupe précis sans changer complètement le propriétaire ou le groupe principal, par exemple avec « setfacl -m u:awa:r rapport.txt ». Leur présence se voit souvent par un « + » en fin de colonne « ls -l ». Tu peux aussi rencontrer « chattr +i » pour rendre un fichier immuable, « lsattr » pour voir cet attribut, et « getcap » pour repérer des capacités Linux accordées à un binaire sans passer par le SUID."),
    schema("Umask à retenir\n022  -> fichiers 644, dossiers 755\n027  -> fichiers 640, dossiers 750\n077  -> fichiers 600, dossiers 700\n\nACL : un « + » dans « ls -l » indique des entrées supplémentaires"),
    text("Démonstration guidée : observe d’abord les droits spéciaux, puis lis leur effet attendu. Sur une machine de test, tu peux créer un dossier collaboratif avec SGID, vérifier un dossier temporaire protégé par sticky bit, puis afficher l’ACL d’un fichier. Les commandes de découverte sont sûres. En revanche, n’ajoute pas un SUID sur un binaire au hasard : ce type de test reste à réserver à un laboratoire contrôlé."),
    code("# Repérer les bits spéciaux sur des dossiers connus\nls -ld /tmp /usr/bin/passwd\n# exemple de sortie (valeurs fictives)\n# drwxrwxrwt 18 root root   4096 Jun  7 09:20 /tmp\n# -rwsr-xr-x 1 root root  68248 Jun  7 09:20 /usr/bin/passwd\n\n# Rechercher les binaires SUID sur ton propre système\nfind / -xdev -perm -4000 -type f 2>/dev/null | head\n\n# Voir l’effet d’une ACL\ngetfacl rapport.txt\n# exemple de sortie (valeurs fictives)\n# user::rw-\n# user:awa:r--\n# group::r--\n# mask::r--\n# other::---", "bash"),
    example("Exemple corrigé : dans une liste de six binaires SUID, « /usr/bin/passwd » et « /usr/bin/su » peuvent être attendus selon la distribution, alors qu’un « /usr/local/bin/convert-paie » SUID root serait un signal fort d’audit. Pour la « umask », retiens les résultats vérifiés suivants : 022 donne 644 et 755, 027 donne 640 et 750, 077 donne 600 et 700. Si « ls -l » affiche « -rw-r-----+ », le « + » t’indique qu’une ACL complète l’histoire."),
    mistakes("croire qu’un bit spécial est toujours malveillant ; confondre SGID sur un programme et SGID sur un dossier collaboratif ; penser que « umask 027 » ajoute des droits, alors qu’elle en retire ; oublier que l’ACL peut autoriser un accès même si le groupe principal ne l’explique pas à lui seul."),
    safety("n’expérimente les changements de bits spéciaux que sur ta machine, une machine virtuelle ou un conteneur de test. Un SUID mal choisi ou une ACL trop large peuvent créer une élévation de privilèges très difficile à voir au premier coup d’œil."),
    takeaway("les bits spéciaux changent le contexte d’exécution ou de partage. « /tmp » en 1777 est normal, un binaire SUID maison ne l’est presque jamais. La « umask » ferme les droits par défaut, et l’ACL ajoute une délégation plus fine quand les trois triplets ne suffisent plus."),
    practice("dans « TP 2 : auditer les droits, les comptes et sudo », vérifie les bits spéciaux attendus, calcule l’effet d’une « umask » et relis l’épreuve « Audit Linux : droits, sudo et cron » pour t’entraîner à juger un cas ambigu. Termine par le quiz de la leçon."),
    reference("ubuntuFrPermissions"),
    reference("gnuCoreutils"),
    reference("anssiLinux"),
  ],
  quiz: {
    title: "Quiz : droits spéciaux, umask et ACL",
    questions: [
      questions.choice("Pourquoi « /tmp » apparaît-il souvent en « drwxrwxrwt » ?", ["Parce que seuls root et le groupe root peuvent y écrire", "Parce qu’il est partagé, mais protégé contre la suppression des fichiers des autres", "Parce qu’il contient toujours des secrets chiffrés", "Parce qu’il interdit toute exécution de script"], 1, "Le sticky bit final « t » laisse tout le monde créer dans « /tmp », mais limite la suppression ou le renommage aux propriétaires légitimes et à root. Le dossier reste partagé, il n’est donc pas réservé à root.", "facile"),
      questions.choice("Quel résultat donne une « umask » de 027 lors de la création par défaut ?", ["Fichiers 644 et dossiers 755", "Fichiers 666 et dossiers 777", "Fichiers 640 et dossiers 750", "Fichiers 600 et dossiers 700"], 2, "La « umask » retire des droits aux bases 666 pour les fichiers et 777 pour les dossiers. Avec 027, on obtient donc 640 et 750. Beaucoup de débutants confondent ce cas avec 077, qui ferme encore plus à 600 et 700.", "moyen"),
      questions.multi("Quelles affirmations sont correctes ? (plusieurs réponses)", ["Un programme SUID s’exécute avec les droits de son propriétaire", "Le SGID sur un dossier peut faire hériter le groupe aux nouveaux fichiers", "Une ACL se voit parfois par un « + » dans « ls -l »", "Le sticky bit sur un dossier empêche toute création de fichier"], [0, 1, 2], "Le SUID change bien le contexte d’exécution, le SGID facilite les dossiers collaboratifs, et un « + » signale souvent des ACL. Le sticky bit n’empêche pas la création, il protège surtout la suppression et le renommage des fichiers partagés.", "difficile"),
      questions.tf("Ajouter un SUID sur un petit binaire maison pour “aller plus vite” mérite une revue de sécurité avant toute mise en production.", true, "Vrai : un binaire SUID accorde les droits de son propriétaire à tout utilisateur qui l’exécute. Même si le programme paraît simple, une mauvaise validation d’entrée, un appel externe ou un chemin mal géré peuvent ouvrir une élévation de privilèges sérieuse.", "moyen"),
    ],
  },
};

const processLesson: NewLesson = {
  key: "linux-processus",
  title: "Les processus : ps, top, signaux et kill",
  summary: "Apprends à lire « ps », à repérer un processus suspect, puis à choisir le bon signal sans détruire des indices utiles pendant une investigation.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer programme et processus, lire les colonnes de « ps aux » et « ps -ef », expliquer les états courants, choisir entre SIGTERM, SIGHUP et SIGKILL, puis reconnaître un comportement suspect."),
    prerequisites("savoir qu’un compte Linux peut lancer un service ou un script avec des droits propres."),
    scenario("Fatou reçoit une alerte : « le serveur est lent ». En ouvrant un terminal, elle voit plusieurs processus, dont un binaire lancé depuis « /tmp » et un autre marqué « (deleted) ». Si elle tue tout trop vite, elle risque d’effacer des indices. Si elle ne lit rien correctement, elle risque de manquer la vraie cause."),
    videoSlot("Lire « ps » avant de lancer « kill »"),
    text("Un programme est un fichier sur disque. Un processus est ce programme en cours d’exécution, avec un PID, un parent, une mémoire et un contexte d’utilisateur. Le PID 1 correspond à « systemd » sur beaucoup de distributions modernes. Quand tu dépannes ou enquêtes, tu regardes surtout quatre choses : qui possède le processus, qui l’a lancé, ce qu’il exécute réellement, et dans quel état il se trouve."),
    schema("États fréquents\nR  -> en cours d’exécution\nS  -> en sommeil, attend un événement\nD  -> sommeil non interrompable, souvent lié à une E/S\nT  -> stoppé\nZ  -> zombie, terminé mais pas encore récupéré par son parent"),
    text("« ps aux » et « ps -ef » affichent les mêmes processus avec des colonnes différentes. Dans « ps aux », tu rencontres USER, PID, %CPU, %MEM, VSZ, RSS, TTY, STAT, START, TIME et COMMAND. Dans « ps -ef », les colonnes clés sont UID, PID, PPID, STIME, TTY, TIME et CMD. « top » ajoute une vue dynamique. Un défenseur n’a pas besoin de tout mémoriser d’un coup : il doit surtout savoir où trouver le PID, l’utilisateur, le parent et la commande complète."),
    schema("Lecture rapide de « ps aux »\nUSER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\nroot       861  0.0  0.8 121000 16480 ?        Ss   08:10   0:01 /usr/sbin/sshd -D\nwww-data  2140  3.8  4.1 286000 84200 ?        S    09:02   0:22 php-fpm: pool www\nawa       7312 98.0  0.2  23440  4212 pts/0    R    09:14   1:48 /tmp/.cache-update"),
    text("Les signaux servent à demander une action au processus. « kill PID » envoie SIGTERM par défaut : on demande un arrêt propre. « kill -HUP » sert souvent à recharger une configuration. « kill -9 » force avec SIGKILL : le processus ne peut ni l’ignorer ni nettoyer ses fichiers temporaires. En investigation, SIGKILL est donc un dernier recours. Avant d’arrêter un processus suspect, note son PID, son chemin, son parent, son utilisateur, son port éventuel et les liens « /proc/PID/exe » et « /proc/PID/cwd ». Lis aussi « /proc/PID/cmdline » pour voir la commande complète. Un binaire lancé depuis « /tmp », un nom qui imite un service système, une consommation CPU inexplicable ou un exécutable marqué « (deleted) » sont des indices importants."),
    text("Pour le tri rapide, « top » reste utile : la touche « P » trie par CPU, « M » par mémoire, « k » prépare l’envoi d’un signal et « q » quitte. Tu peux aussi lancer une commande en tâche de fond avec « & », revoir les tâches du shell avec « jobs » ou la détacher avec « nohup » si tu assumes de perdre le terminal. Enfin, « nice » règle la priorité de -20, très prioritaire, à 19, peu prioritaire. Ce n’est pas un outil de sécurité, mais c’est utile pour éviter qu’une tâche lourde gêne le reste."),
    text("Démonstration guidée : commence par lister, puis seulement après agir. Sur un Linux de test, « ps aux --sort=-%cpu | head » donne les processus les plus gourmands. « pgrep » retrouve un nom précis. « readlink » sur « /proc/PID/exe » ou « /proc/PID/cwd » montre le binaire et le dossier courant. Ce sont des commandes de lecture sûres et utiles sur un vrai serveur autorisé."),
    code("# Lister les processus les plus actifs\nps aux --sort=-%cpu | head\n# exemple de sortie (valeurs fictives)\n# USER       PID %CPU %MEM    VSZ   RSS TTY   STAT START   TIME COMMAND\n# awa       7312 98.0  0.2  23440  4212 pts/0 R    09:14   1:48 /tmp/.cache-update\n# root       861  0.0  0.8 121000 16480 ?     Ss   08:10   0:01 /usr/sbin/sshd -D\n\n# Retrouver un processus et ses chemins\npgrep -a sshd\ntr '\\0' ' ' < /proc/861/cmdline\nreadlink /proc/861/exe\nreadlink /proc/861/cwd\n# exemple de sortie (valeurs fictives)\n# /usr/sbin/sshd -D \n# /usr/sbin/sshd\n# /\n\n# Arrêt propre puis dernier recours seulement si nécessaire\nkill 7312\nkill -9 7312", "bash"),
    example("Exemple corrigé : parmi six lignes « ps aux », la plus suspecte est souvent celle qui cumule plusieurs signaux : utilisateur inattendu, chemin dans « /tmp » ou dans un dossier caché, CPU très élevé, parent étrange ou exécutable « (deleted) ». Une ligne « root 8451 95.0 0.3 23440 4212 pts/1 R 09:15 3:22 /tmp/.cache-update » mérite bien plus d’attention qu’un « sshd -D » lancé par root depuis « /usr/sbin »."),
    mistakes("tuer un processus avant d’avoir noté son PID, son chemin et son parent ; utiliser « kill -9 » comme réflexe normal ; confondre un zombie avec un processus encore actif ; croire qu’un fort CPU suffit à prouver une compromission sans regarder le contexte."),
    safety("sur un serveur de production, documente d’abord puis isole si nécessaire. N’arrête un processus que sur ta propre machine ou sur un système dont tu as la responsabilité et l’autorisation écrite, surtout si une investigation est en cours."),
    takeaway("un processus raconte qui exécute quoi, depuis où et dans quel état. « ps » sert d’abord à observer. SIGTERM est la voie normale, SIGKILL le dernier recours, et un binaire lancé depuis un emplacement inhabituel mérite une vérification immédiate."),
    practice("dans « TP 3 : processus, services et tâches planifiées », lis un extrait de « ps aux », relie un port à un processus et justifie lequel paraît anormal avant toute action. Termine par le quiz de la leçon."),
    reference("linuxCommandBook"),
    reference("debianReference"),
    reference("anssiLinux"),
  ],
  quiz: {
    title: "Quiz : processus, signaux et lecture de ps",
    questions: [
      questions.choice("Quel signal envoie « kill PID » par défaut ?", ["SIGHUP", "SIGKILL", "SIGTERM", "SIGSTOP"], 2, "Par défaut, « kill » envoie SIGTERM, qui demande un arrêt propre. Beaucoup de débutants pensent tout de suite à SIGKILL, mais « -9 » doit rester exceptionnel car il empêche le nettoyage normal du processus.", "facile"),
      questions.choice("Dans la ligne « awa 7312 98.0 0.2 23440 4212 pts/0 R 09:14 1:48 /tmp/.cache-update », quel indice est le plus suspect ?", ["Le fait que la ligne contienne un PID", "Le chemin du binaire dans « /tmp »", "L’utilisateur « awa » existe", "La présence d’un temps CPU"], 1, "Un exécutable lancé depuis « /tmp » est inhabituel pour un service légitime et mérite une investigation. Le PID et le temps CPU sont normaux dans « ps », et le simple fait qu’un utilisateur humain existe ne suffit pas à conclure.", "moyen"),
      questions.multi("Quels critères renforcent le soupçon sur un processus ? (plusieurs réponses)", ["Nom très proche d’un service système connu", "Exécutable marqué « (deleted) »", "Parent cohérent et binaire dans « /usr/sbin »", "Forte consommation CPU sans raison métier claire"], [0, 1, 3], "Un nom trompeur, un binaire supprimé pendant l’exécution et un CPU anormal peuvent signaler une persistance, un mineur ou un programme caché. En revanche, un parent cohérent et un chemin système attendu vont plutôt dans le sens d’un comportement normal.", "difficile"),
      questions.tf("En investigation, il vaut souvent mieux relever le PID, le chemin et le parent d’un processus suspect avant de le tuer.", true, "Vrai : ces éléments sont des preuves utiles pour comprendre ce qui se passe, corréler avec les journaux et éviter de supprimer des indices trop tôt. Tuer d’abord puis réfléchir ensuite complique souvent l’analyse.", "moyen"),
    ],
  },
};

const systemdLesson: NewLesson = {
  key: "linux-systemd",
  title: "Services et systemd : systemctl, unités et démarrage",
  summary: "Pilote un service avec « systemctl », lis un statut utile, puis comprends comment une unité systemd peut aider à administrer proprement ou servir de persistance.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer le rôle de systemd, distinguer « start » et « enable », lire « systemctl status », repérer les fichiers d’unité prioritaires, puis modifier une unité proprement avec « daemon-reload »."),
    prerequisites("avoir déjà lu des processus Linux et savoir qu’un service tourne sous un compte et un binaire précis."),
    scenario("Ama récupère un petit serveur web qui “redémarre parfois tout seul”. Le service fonctionne, mais personne ne sait s’il démarre au boot, quelle commande le lance, ni si une unité ajoutée récemment explique le comportement observé. Pour reprendre la main, Ama doit lire systemd au lieu de redémarrer à l’aveugle."),
    videoSlot("Comprendre systemd sans mémoriser mille commandes"),
    text("Sur Debian et Ubuntu actuels, systemd est le gestionnaire d’initialisation et de services. Il devient le PID 1 au démarrage, lance les unités nécessaires et garde l’état des services. Une unité peut représenter un service, un minuteur, un socket ou une cible logique. Pour l’administrateur, cela centralise le démarrage, l’arrêt, l’activation au boot et les journaux récents."),
    schema("Unités fréquentes\n.service  -> un service ou démon\n.timer    -> un déclencheur planifié\n.socket   -> une écoute activant un service\n.target   -> un ensemble logique d’unités"),
    text("Deux verbes sont souvent confondus. « systemctl start nom.service » agit maintenant. « systemctl enable nom.service » prépare le démarrage automatique plus tard. L’un n’implique pas l’autre. Pour savoir où tu en es, combine « status », « is-active » et « is-enabled ». « list-units » montre les unités chargées, alors que « list-unit-files » parcourt l’inventaire. Cette distinction t’évite de croire qu’un service “ne marche pas” alors qu’il tourne bien mais n’est pas activé au redémarrage, ou l’inverse."),
    schema("Commandes utiles\nsystemctl status ssh\nsystemctl start demo.service\nsystemctl stop demo.service\nsystemctl restart demo.service\nsystemctl reload nginx\nsystemctl enable demo.service\nsystemctl disable demo.service\nsystemctl mask demo.service\nsystemctl is-active demo.service\nsystemctl is-enabled demo.service"),
    text("Un fichier d’unité vit souvent dans « /usr/lib/systemd/system » ou « /lib/systemd/system » quand il vient d’un paquet, et dans « /etc/systemd/system » quand l’administrateur le crée ou le surcharge. Ce second emplacement est prioritaire. Après modification, « systemctl daemon-reload » demande à systemd de relire ses unités. En sécurité, retiens quatre idées : un service doit idéalement tourner sous un utilisateur dédié, des options comme « PrivateTmp=yes » ou « ProtectSystem=full » réduisent son exposition, toute unité inattendue déposée dans « /etc/systemd/system » peut être une persistance ajoutée par un attaquant ou par un script mal maîtrisé, et un audit gagne à lister les fichiers récents de ce répertoire avant de redémarrer quoi que ce soit."),
    text("Démonstration guidée : lis d’abord le statut, puis la définition complète. « systemctl cat » montre les fichiers réellement pris en compte. « journalctl -u nom -b » te donne le journal de la session de démarrage courante. Sur une machine virtuelle ou un serveur que tu administres, cela permet de comprendre un démarrage raté sans modifier le service à l’aveugle."),
    code("# Lire l’état et la définition d’un service\nsystemctl status ssh\n# exemple de sortie (valeurs fictives)\n# ● ssh.service - OpenBSD Secure Shell server\n#      Loaded: loaded (/lib/systemd/system/ssh.service; enabled; preset: enabled)\n#      Active: active (running) since Mon 2026-06-08 09:02:11 UTC; 14min ago\n#    Main PID: 861 (sshd)\n#       Tasks: 1\n#      Memory: 8.4M\n#         CPU: 152ms\n\nsystemctl cat ssh\njournalctl -u ssh -b --since \"30 minutes ago\"\n\n# Après modification d’une unité\nsudo systemctl daemon-reload\nsudo systemctl restart demo-backup.service", "bash"),
    schema("[Unit]\nDescription=Sauvegarde locale de démonstration\nAfter=network-online.target\n\n[Service]\nType=oneshot\nUser=backup\nExecStart=/usr/local/bin/backup-demo.sh\nRestart=no\n\n[Install]\nWantedBy=multi-user.target"),
    example("Exemple corrigé : si tu écris une unité « demo-backup.service » pour lancer une sauvegarde ponctuelle, place-la dans « /etc/systemd/system », relis-la avec « systemctl cat », puis exécute « daemon-reload ». Si « is-enabled » répond « disabled » mais « is-active » répond « active », le service tourne maintenant sans être prévu au prochain démarrage. C’est un état utile à comprendre lors d’un audit."),
    mistakes("modifier directement le fichier fourni par le paquet au lieu d’utiliser « /etc/systemd/system » ; oublier « daemon-reload » après un changement ; croire que « enable » démarre immédiatement le service ; redémarrer sans lire le journal ni le statut complet."),
    safety("teste tes unités sur ta propre machine, une machine virtuelle ou un serveur autorisé. Une erreur dans « ExecStart » ou un « restart » répété peut empêcher un service critique de démarrer correctement."),
    takeaway("systemd centralise le cycle de vie des services. « start » agit maintenant, « enable » prépare le futur. Les fichiers d’unité de l’administrateur dans « /etc/systemd/system » sont prioritaires et doivent être surveillés comme un point de persistance possible."),
    practice("dans « TP 3 : processus, services et tâches planifiées », lis une liste de services, retrouve celui qui est activé au démarrage, puis juge si une unité ajoutée récemment paraît légitime ou suspecte. Termine par le quiz de la leçon."),
    reference("debSystemctl"),
    reference("debSystemdService"),
    reference("debJournalctl"),
  ],
  quiz: {
    title: "Quiz : systemd et services",
    questions: [
      questions.choice("Quelle différence est correcte entre « systemctl start demo.service » et « systemctl enable demo.service » ?", ["« start » rend le service permanent, « enable » le lance juste une fois", "« start » agit maintenant, « enable » prépare le démarrage au boot", "Les deux commandes font exactement la même chose", "« enable » ne fonctionne que sur Fedora"], 1, "« start » touche l’instant présent, tandis que « enable » installe la relation nécessaire pour les prochains démarrages. Les confondre est fréquent et conduit à des diagnostics faux après un redémarrage.", "facile"),
      questions.choice("Dans « Loaded: loaded (/lib/systemd/system/ssh.service; enabled; preset: enabled) », quelle information dit que le service démarrera au boot ?", ["Le chemin « /lib/systemd/system/ssh.service »", "Le mot « loaded »", "Le mot « enabled »", "Le nom « ssh.service »"], 2, "Le mot « enabled » indique que le service est activé pour le démarrage. Le chemin montre seulement d’où vient le fichier, et « loaded » dit qu’il a été chargé, pas qu’il sera relancé automatiquement plus tard.", "moyen"),
      questions.multi("Quelles actions sont bonnes après avoir modifié un fichier d’unité ? (plusieurs réponses)", ["Exécuter « systemctl daemon-reload »", "Relire l’unité avec « systemctl cat »", "Ignorer le journal si le service ne démarre plus", "Vérifier ensuite « status » ou le journal"], [0, 1, 3], "Après une modification, il faut faire relire les unités, vérifier le contenu réellement pris en compte, puis consulter le statut ou le journal. Ignorer les journaux laisse passer des erreurs simples de syntaxe ou de chemin.", "difficile"),
      questions.tf("Une unité inattendue placée dans « /etc/systemd/system » mérite un contrôle lors d’un audit de persistance.", true, "Vrai : ce répertoire a priorité sur les unités du paquet et peut contenir un service légitime, une surcharge ou une persistance malveillante. Son contenu récent fait donc partie des points d’attention d’un auditeur Linux.", "moyen"),
    ],
  },
};

const cronLesson: NewLesson = {
  key: "linux-cron",
  title: "Tâches planifiées : cron et minuteurs systemd",
  summary: "Lis une règle cron sans te tromper, vérifie ses prochaines exécutions et comprends quand un minuteur systemd est plus propre qu’une vieille tâche planifiée.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("lire les cinq champs d’une règle cron, calculer la prochaine exécution, distinguer crontab utilisateur et table système, expliquer le piège du jour du mois et du jour de la semaine, puis comparer cron et minuteurs systemd."),
    prerequisites("savoir lire des services Linux et comprendre qu’un script lancé automatiquement devient un point de maintenance ou de persistance."),
    scenario("Yacine enquête sur un serveur qui réapplique chaque nuit une mauvaise configuration. Aucun utilisateur ne s’en souvient, mais un vieux script root tourne peut-être encore. Pour retrouver la source, Yacine doit lire les tâches planifiées, calculer quand elles se déclenchent et vérifier si le script associé est sûr."),
    videoSlot("Comprendre cron sans rater l’horaire"),
    text("Une règle cron classique comporte cinq champs : minute, heure, jour du mois, mois et jour de la semaine. Les valeurs « */5 », « 1,15 » et « 1-5 » signifient respectivement toutes les cinq unités, une liste précise, ou un intervalle. Le piège connu est le suivant : si le jour du mois ET le jour de la semaine sont tous deux restreints, cron exécute la tâche quand l’un OU l’autre correspond. Beaucoup de personnes lisent cela comme un ET logique, puis s’étonnent d’un lancement inattendu."),
    schema("Champs cron\nm h dom mon dow  commande\n| |  |   |   |\n| |  |   |   +-- jour semaine, 0 ou 7 = dimanche\n| |  |   +------ mois\n| |  +---------- jour du mois\n| +------------- heure\n+--------------- minute"),
    text("Les tables d’utilisateur se gèrent avec « crontab -e » et « crontab -l ». Les fichiers système comme « /etc/crontab » et ceux de « /etc/cron.d/ » ajoutent un champ utilisateur avant la commande. Les dossiers « /etc/cron.daily », « .hourly », « .weekly » et « .monthly » offrent un autre style de planification. Dans tous les cas, l’environnement reste minimal : peu de variables, pas de terminal interactif et souvent un « PATH » réduit. Voilà pourquoi les scripts cron doivent employer des chemins absolus, définir leurs variables utiles et rediriger leurs sorties vers un journal."),
    schema("Exemples utiles\n*/5 * * * *          toutes les 5 minutes\n30 2 * * 1-5         à 02 h 30, du lundi au vendredi\n0 3 1 * *            le 1er jour du mois à 03 h 00\n15 6 * * 0           chaque dimanche à 06 h 15"),
    text("Les minuteurs systemd répondent au même besoin avec quelques avantages pratiques : journal intégré, dépendances explicites, expressions de calendrier avec « OnCalendar= », et option « Persistent=true » pour rejouer une tâche manquée après un arrêt. Tu les verras via « systemctl list-timers ». Pour une action ponctuelle, pense aussi à « at », qui exécute une commande une seule fois plus tard. En défense, retiens surtout que cron et les minuteurs peuvent servir à la maintenance comme à la persistance. Une tâche root qui exécute un script modifiable par un autre utilisateur devient par exemple une élévation de privilèges presque annoncée."),
    text("Démonstration guidée : pars d’horaires simples. Si nous sommes un lundi à 14 h 17, « */5 * * * * » déclenchera à 14 h 20, 14 h 25 puis 14 h 30. Si nous sommes un jeudi à 16 h 40, « 30 2 * * 1-5 » déclenchera vendredi à 02 h 30. Pour l’audit, pense aussi à lister toutes les tables. En root sur un serveur autorisé, la boucle qui parcourt les utilisateurs donne une vue d’ensemble très utile."),
    code("# Voir les tâches de l’utilisateur courant\ncrontab -l\n# exemple de sortie (valeurs fictives)\n# 30 2 * * 1-5 /usr/local/bin/backup.sh >> /var/log/backup.log 2>&1\n\n# Extrait de /etc/crontab\n# exemple de sortie (valeurs fictives)\n# 17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly\n\n# Audit global en root\nfor u in $(cut -d: -f1 /etc/passwd); do\n  crontab -u \"$u\" -l 2>/dev/null\ndone\n\n# Voir les minuteurs systemd\nsystemctl list-timers --all", "bash"),
    example("Exemple corrigé : pour une sauvegarde tous les jours ouvrés à 02 h 30, la bonne règle est « 30 2 * * 1-5 ». Si tu écris « 30 2 1 * 1 », elle se lancera le premier jour du mois et aussi chaque lundi, pas seulement quand ces deux conditions tombent ensemble. Dans un audit, si tu vois une tâche root vers « /srv/atelier/backup.sh » alors que ce script est modifiable par le groupe « atelier », tu tiens un risque prioritaire. Pense aussi au scénario de persistance décrit dans « Incident : un serveur web Linux compromis » : cron fait partie des endroits à vérifier."),
    mistakes("lire les champs dans le mauvais ordre ; croire que jour du mois et jour de la semaine fonctionnent en ET ; oublier les chemins absolus dans un script cron ; laisser une tâche root appeler un script modifiable par un autre compte."),
    safety("teste tes règles sur ta machine, une machine virtuelle ou un serveur que tu administres avec autorisation écrite. Une tâche planifiée mal écrite peut écraser des fichiers, saturer un disque ou relancer indéfiniment une mauvaise commande."),
    takeaway("cron reste simple et puissant, mais il exige une lecture rigoureuse. Les tables utilisateur et système n’ont pas exactement le même format. Les minuteurs systemd offrent souvent une meilleure observabilité, et toute tâche planifiée doit être auditée comme un mécanisme de persistance potentiel."),
    practice("dans « TP 3 : processus, services et tâches planifiées », calcule les prochains horaires de plusieurs règles, repère une tâche anormale et relis aussi « Incident : un serveur web Linux compromis » pour voir comment cron peut servir de persistance. Termine par le quiz de la leçon."),
    reference("ubuntuFrCron"),
    reference("debCrontab"),
    reference("debSystemdTimer"),
  ],
  quiz: {
    title: "Quiz : cron et minuteurs systemd",
    questions: [
      questions.choice("Que signifie la règle « 30 2 * * 1-5 » ?", ["Toutes les 30 minutes entre 02 h et 05 h", "À 02 h 30 du lundi au vendredi", "Le 30 du mois à 02 h 05", "À 01 h 05 tous les jours"], 1, "Les champs sont minute, heure, jour du mois, mois, jour de la semaine. On lit donc bien 30 minutes, 2 heures, tous les jours du mois, tous les mois, du lundi au vendredi. Le piège fréquent est de lire les champs à l’envers.", "facile"),
      questions.choice("Pourquoi une tâche fonctionne-t-elle parfois à la main mais pas dans cron ?", ["Parce que cron ajoute automatiquement plus de variables d’environnement", "Parce que cron ne sait lancer que des commandes Python", "Parce que l’environnement cron est minimal et que les chemins relatifs posent problème", "Parce que cron n’accepte jamais la redirection vers un fichier"], 2, "Cron fournit peu de variables et un « PATH » réduit. Un script qui suppose un répertoire courant précis ou un binaire trouvé “par magie” peut donc échouer. Les redirections, elles, sont tout à fait possibles et même très utiles pour journaliser.", "moyen"),
      questions.multi("Quelles affirmations sont correctes ? (plusieurs réponses)", ["Une table système comme « /etc/crontab » ajoute un champ utilisateur", "Un minuteur systemd peut rejouer une tâche manquée avec « Persistent=true »", "« crontab -l » affiche les tâches de tous les utilisateurs d’un coup", "Une tâche root qui appelle un script modifiable par un autre compte est risquée"], [0, 1, 3], "La table système ajoute bien un utilisateur, les minuteurs systemd savent parfois compenser une exécution manquée, et un script root modifiable par un autre compte crée un risque d’élévation de privilèges. « crontab -l » ne montre que la table du compte courant, pas toutes les tables.", "difficile"),
      questions.tf("Si une règle cron restreint à la fois le jour du mois et le jour de la semaine, cron l’exécute lorsque l’un ou l’autre champ correspond.", true, "Vrai : c’est un piège classique. Beaucoup lisent ces deux champs comme un ET logique, alors que cron les traite comme un OU lorsqu’ils sont tous deux restreints. Cette nuance suffit à expliquer des lancements inattendus.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c3:2",
    position: 3,
    existing: { fromTitle: "Droits et utilisateurs" },
    title: "Droits et utilisateurs",
    description: "Tu apprends ici à lire les permissions, à comprendre les comptes Linux et à déléguer des actions sensibles sans exposer toute la machine. Critères de réussite : traduire une ligne « ls -l » en décision concrète ; repérer un compte ou une règle sudo risqués ; expliquer quand un bit spécial, une ACL ou une « umask » sont justifiés.",
    lessons: [permissionsLesson, usersLesson, sudoLesson, specialRightsLesson],
  },
  {
    key: "c3:5",
    position: 4,
    title: "Processus et services",
    description: "Ce module te donne une lecture opérationnelle de ce qui tourne, démarre et se planifie sur un système Linux. Critères de réussite : identifier un processus ou un service inhabituel ; distinguer action immédiate et démarrage automatique ; calculer le comportement d’une tâche planifiée et juger son risque.",
    lessons: [processLesson, systemdLesson, cronLesson],
  },
];
