import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  figure,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const linuxDemarrerLesson: NewLesson = {
  key: "linux-demarrer",
  title: "Linux, distributions et environnements : s’exercer gratuitement",
  summary: "Comprends ce qu’est Linux, comment choisir une distribution, et comment t’exercer sans risque depuis Windows, une machine virtuelle ou un téléphone Android.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("définir le noyau Linux et une distribution, distinguer Ubuntu, Debian, Fedora, RHEL et Arch, choisir un environnement d’entraînement gratuit, identifier le système utilisé, et expliquer pourquoi Linux compte dans un métier de défenseur."),
    prerequisites("aucun."),
    scenario("Awa aide Baobab Tech à préparer un futur serveur web, mais elle travaille encore sur un poste Windows et n’a pas de machine dédiée. Son collègue Moussa n’a qu’un vieux portable, et Fatou n’a parfois que son téléphone Android. Avant d’apprendre des commandes, l’équipe doit choisir un terrain d’exercice gratuit, réaliste et sans danger pour la machine de travail."),
    videoSlot("Découvrir Linux et choisir un environnement d’entraînement sûr"),
    text("Linux est d’abord un noyau : la partie du système qui parle au matériel, gère la mémoire, les processus et les périphériques. Une distribution ajoute autour du noyau des outils, un gestionnaire de paquets, des réglages et une documentation. Ubuntu et Debian appartiennent à la même famille et servent souvent de base pour des serveurs ou des laboratoires. Fedora et RHEL représentent une autre grande famille, très présente en entreprise. Arch est plus minimaliste et très pédagogique, mais moins simple pour un débutant pressé."),
    figure({
      kind: "flow",
      title: "Du noyau Linux à la distribution",
      nodes: [
        { label: "Noyau Linux", text: "gère le matériel, la mémoire et les processus", icon: "server", tone: "green" },
        { label: "Outils et paquets", text: "configuration et documentation", icon: "package", tone: "blue" },
        { label: "Distribution", text: "système complet prêt à l’usage", icon: "laptop", tone: "violet" },
      ],
      caption: "Familles courantes : Debian et Ubuntu pour l’apprentissage et des serveurs courants ; RHEL et Fedora en entreprise, avec `dnf` et SELinux ; Arch reste très manuel et très formateur.",
    }),
    text("Un défenseur doit connaître Linux parce que beaucoup de services en ligne, de journaux, de conteneurs, d’outils d’audit et de systèmes embarqués reposent dessus. Android utilise lui aussi un noyau Linux, même si son interface ne ressemble pas à un serveur. Linux est un logiciel libre : le code source peut être lu, étudié et redistribué selon sa licence. Cela n’assure pas la sécurité par magie, mais permet d’inspecter et d’améliorer les briques utilisées."),
    text("Pour t’exercer gratuitement, trois options reviennent souvent. Sous Windows, Microsoft documente l’installation de WSL avec « wsl --install » dans un terminal ouvert en administrateur, puis un redémarrage : c’est pratique pour apprendre les commandes et les chemins, mais il faut rester prudent sur les prérequis et la version de Windows, donc suis la page officielle. Une machine virtuelle avec VirtualBox isole mieux les essais et permet de prendre un instantané avant une manipulation risquée. Termux sur Android donne un vrai terminal et beaucoup d’outils, mais ce n’est pas une distribution Linux classique : pas de systemd, pas de vrais droits root, et une arborescence différente de Debian ou Ubuntu. Une clé USB « live » et les conteneurs existent aussi : le premier sert à essayer sans installer, le second sert à lancer vite un environnement applicatif, pas à remplacer tout un serveur d’apprentissage."),
    figure({
      kind: "cards",
      title: "Choix rapide pour s’exercer",
      columns: 2,
      items: [
        { term: "WSL", text: "pratique sous Windows, installation guidée", icon: "laptop", tone: "green" },
        { term: "Machine virtuelle", text: "plus fidèle, instantané avant essai", icon: "server", tone: "blue" },
        { term: "Termux", text: "utile sur téléphone, limites franches", icon: "phone", tone: "amber" },
        { term: "Live USB", text: "essai temporaire sans installation", icon: "usb", tone: "violet" },
        { term: "Conteneur", text: "utile pour une appli, pas pour tout le système", icon: "package", tone: "neutral" },
      ],
    }),
    text("Démonstration guidée : ouvre un terminal d’une vraie distribution, par exemple dans WSL, une machine virtuelle ou Termux, puis lis quatre informations de base. « uname -a » décrit le noyau, « cat /etc/os-release » annonce la distribution, « hostname » donne le nom de la machine et « whoami » te rappelle avec quel compte tu travailles. Si tu n’as que Git Bash sous Windows, garde-le pour t’entraîner au shell, puis refais cette lecture dans un vrai environnement Linux dès que possible."),
    code("# lire le noyau et la distribution\nuname -a\ncat /etc/os-release\nhostname\nwhoami\n\n# exemple de sortie (valeurs fictives)\n# Linux portable-awa 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Mon Aug 12 10:00:00 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux\n# PRETTY_NAME=\"Ubuntu 24.04.1 LTS\"\n# NAME=\"Ubuntu\"\n# portable-awa\n# awa", "bash"),
    example("Exemple corrigé : poste Windows récent de bureau, choisis WSL si tu veux apprendre vite les commandes et les chemins sans réinstaller la machine. Vieux portable récupéré, préfère une machine virtuelle légère ou même une installation Linux dédiée si l’ordinateur ne sert plus à autre chose. Téléphone Android seul, Termux est mieux que rien pour lire, filtrer et écrire de petits scripts, mais il ne remplace pas un serveur complet pour « systemctl », les services réseau ou les droits d’administration."),
    mistakes("installer Linux sur le disque principal sans sauvegarde préalable ; croire que Termux reproduit exactement un serveur Debian ou Ubuntu ; copier des commandes sans lire les options ; oublier de prendre un instantané de machine virtuelle avant les expériences plus risquées."),
    safety("entraîne-toi sur ta propre machine, ta machine virtuelle ou un environnement explicitement autorisé. Avant une expérience qui touche au stockage ou au réseau, fais une sauvegarde ou au minimum un instantané. Un environnement de test sert à apprendre sans casser le poste de production."),
    takeaway("Linux est un noyau, une distribution est un système complet construit autour de ce noyau. Ubuntu, Debian, Fedora et RHEL reviennent souvent en administration. WSL, la machine virtuelle et Termux sont trois portes d’entrée utiles, mais avec des limites différentes."),
    practice("ouvre le laboratoire « TP 1 : explorer l’arborescence et chercher dans les fichiers », puis refais la partie découverte de l’environnement : repère où tu es, quel compte tu utilises et quels fichiers de base sont présents. Termine par le quiz de la leçon."),
    reference("wslInstall"),
    reference("virtualboxManual"),
    reference("termuxHome"),
  ],
  quiz: {
    title: "Quiz : démarrer avec Linux",
    questions: [
      questions.choice("Que désigne le plus précisément Linux ?", ["Une suite bureautique", "Le noyau du système", "Un seul serveur web célèbre", "Le magasin d’applications d’Ubuntu"], 1, "Linux désigne d’abord le noyau, la partie qui dialogue avec le matériel et organise les ressources. La réponse la plus tentante est de dire « le système complet », mais ce rôle revient plutôt à une distribution comme Debian ou Ubuntu.", "facile"),
      questions.tf("Termux sur Android fournit souvent un terminal utile, mais il ne remplace pas un serveur Linux complet avec systemd et de vrais droits root.", true, "Vrai : Termux est très pratique pour apprendre des commandes, manipuler des fichiers et lancer certains outils, mais il ne reproduit pas fidèlement un serveur Debian ou Ubuntu. Le piège serait d’attendre de lui les mêmes services et privilèges qu’une machine dédiée.", "moyen"),
      questions.multi("Quels choix sont raisonnables pour s’entraîner gratuitement selon le contexte ? (plusieurs réponses)", ["WSL sur un poste Windows récent", "Une machine virtuelle avec instantané", "Termux pour pratiquer des commandes sur téléphone", "Le serveur de production de l’association, tant que tu fais attention"], [0, 1, 2], "WSL, la machine virtuelle et Termux sont trois chemins d’apprentissage valables selon le matériel disponible. La mauvaise idée est le serveur de production : même avec de bonnes intentions, un environnement réel ne sert pas de laboratoire sans autorisation et sans filet de sécurité.", "difficile"),
      questions.choice("Quelle commande répond le mieux à la question « quel compte suis-je en train d’utiliser ? »", ["hostname", "cat /etc/os-release", "whoami", "uname -a"], 2, "« whoami » affiche le compte courant, ce qui est crucial avant une commande sensible. « hostname » parle de la machine, « uname -a » du noyau et « cat /etc/os-release » de la distribution, donc ces réponses sont utiles mais ne répondent pas à la bonne question.", "moyen"),
    ],
  },
};

const linuxTerminalLesson: NewLesson = {
  key: "linux-terminal",
  title: "Le terminal et le shell : lire une commande et trouver de l’aide",
  summary: "Apprends à décortiquer une commande Linux, à trouver de l’aide fiable, et à utiliser l’historique, les guillemets et le code de retour sans te piéger.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("reconnaître les parties d’une commande, utiliser « man », « --help », « type » et « which », lire une invite de shell, expliquer le rôle de PATH et du code de retour, et interrompre proprement une commande."),
    prerequisites("avoir suivi « Linux, distributions et environnements : s’exercer gratuitement » ou déjà disposer d’un terminal Linux, WSL, machine virtuelle ou Termux."),
    scenario("Nadia reçoit une ligne copiée dans un groupe de discussion : « grep -rn motdepasse /home/awa/notes ». Elle voit bien des mots connus, mais ne sait pas encore ce qui est le programme, l’option ou l’argument. Comme elle devra un jour lire des commandes d’audit, de sauvegarde ou de dépannage, elle veut comprendre avant d’exécuter."),
    videoSlot("Lire une commande Linux sans paniquer"),
    text("Le terminal est la fenêtre dans laquelle tu écris des commandes. Le shell, souvent bash, est l’interpréteur qui lit ce que tu tapes puis lance les programmes. Une invite comme « awa@portable-awa:~$ » indique souvent l’utilisateur, la machine et le dossier courant. Le symbole « $ » rappelle qu’il s’agit d’un compte ordinaire. Le symbole « # » est généralement utilisé pour root : c’est un signal à prendre au sérieux, pas un décor."),
    figure({
      kind: "table",
      title: "Lire la commande `grep -rn motdepasse /home/awa/notes`",
      columns: ["Élément", "Valeur", "Rôle"],
      rows: [
        ["programme", "`grep`", "programme lancé"],
        ["option courte", "`-r`", "parcours récursif"],
        ["option courte", "`-n`", "affiche les numéros de ligne"],
        ["motif", "`motdepasse`", "motif recherché"],
        ["argument", "`/home/awa/notes`", "dossier à parcourir"],
      ],
      highlight: 2,
    }),
    text("Quand tu ne connais pas une commande, commence par l’aide. « man ls » ouvre le manuel, « /mot » cherche dans la page, « n » passe au résultat suivant et « q » quitte. « ls --help » donne un résumé plus court. « apropos archive » cherche des pages de manuel par mot-clé. « type grep » dit si « grep » est une commande interne du shell, un alias ou un programme, et « which grep » montre le chemin du binaire trouvé via PATH. Ce PATH est une liste de dossiers que le shell parcourt pour trouver un programme : y ajouter « . », le dossier courant, est une très mauvaise habitude, car tu pourrais lancer un faux programme simplement en te trouvant dans le mauvais dossier."),
    text("Le shell effectue aussi des traitements avant de lancer un programme. Les jokers comme « * » sont développés, les variables d’environnement sont remplacées, puis la commande est exécutée. Les guillemets simples gardent le texte presque tel quel. Les guillemets doubles laissent encore passer des variables comme « $HOME ». Attention : les jokers du shell et les motifs de « grep » ne parlent pas le même langage. Si tu veux chercher littéralement un motif, protège-le d’abord des expansions du shell. Quand une commande échoue, regarde son message d’erreur puis son code de retour avec « echo $? ». En général, 0 signifie succès. Tu peux enchaîner avec « ; » pour lancer plusieurs commandes l’une après l’autre, ou avec « && » pour n’exécuter la seconde que si la première a réussi."),
    figure({
      kind: "cards",
      title: "Raccourcis utiles dans le shell",
      items: [
        { term: "Tab", text: "complète un nom de commande ou de fichier", icon: "zap", tone: "green" },
        { term: "Flèche haut", text: "relit une commande précédente", icon: "upload", tone: "blue" },
        { term: "Ctrl+R", text: "cherche dans l’historique", icon: "search", tone: "violet" },
        { term: "Ctrl+C", text: "interrompt la commande courante", icon: "close", tone: "red" },
        { term: "Ctrl+L", text: "efface l’écran sans fermer le shell", icon: "document", tone: "neutral" },
      ],
    }),
    text("Démonstration guidée : quand tu découvres un outil, interroge d’abord le shell au lieu d’improviser. Regarde de quel type de commande il s’agit, où elle se trouve, puis teste une aide courte. Cette discipline paraît lente au début, mais elle évite beaucoup de copier-coller aveugle et t’apprend à lire la documentation officielle directement depuis le terminal."),
    code("# identifier une commande\ntype grep\nwhich grep\nls --help | head -n 3\n\n# exemple de sortie (valeurs fictives)\n# grep is /usr/bin/grep\n# /usr/bin/grep\n# Usage: ls [OPTION]... [FILE]...\n# List information about the FILEs (the current directory by default).\n# Sort entries alphabetically if none of -cftuvSUX nor --sort is specified.", "bash"),
    example("Exemple corrigé : dans « grep -rn motdepasse /home/awa/notes », « grep » est le programme, « -r » demande de parcourir récursivement les sous-dossiers et « -n » d’afficher les numéros de ligne. « motdepasse » est le motif recherché, et « /home/awa/notes » le dossier cible. Si Nadia oublie qu’un mot avec espace doit être protégé par des guillemets, le shell le coupera en plusieurs arguments avant même que « grep » ne démarre."),
    mistakes("confondre une option et un argument ; ignorer le message d’erreur pour relancer exactement la même commande ; travailler en root par habitude ; coller directement une commande trouvée sur un site sans l’avoir d’abord lue dans un éditeur ou comprise option par option."),
    safety("une commande collée depuis un site ou une messagerie peut cacher des retours à la ligne ou des caractères trompeurs. Colle-la d’abord dans un éditeur, relis-la, puis comprends ce qu’elle fera. Utilise « sudo » seulement quand tu sais pourquoi il est nécessaire."),
    takeaway("Le shell n’est pas magique : il lit, développe puis lance une commande précise. « man », « --help », « type » et « which » sont tes premiers réflexes. Un code de retour et un message d’erreur valent souvent plus qu’une intuition."),
    practice("ouvre le laboratoire « TP 1 : explorer l’arborescence et chercher dans les fichiers », puis prends chaque commande demandée et décompose-la comme dans la leçon : programme, options, arguments et résultat attendu. Termine par le quiz de la leçon."),
    reference("ubuntuCommandLine"),
    reference("man7Bash"),
    reference("gnuBash"),
  ],
  quiz: {
    title: "Quiz : terminal et shell",
    questions: [
      questions.choice("Dans l’invite « awa@portable-awa:~$ », que rappelle surtout le symbole « $ » ?", ["Que la machine est éteinte", "Que le compte affiché est en lecture seule", "Que l’on travaille en général avec un compte ordinaire", "Que le réseau est déconnecté"], 2, "Le symbole « $ » marque en général un shell utilisateur classique, alors que « # » est souvent associé à root. La réponse trompeuse serait de croire qu’il signifie « lecture seule », alors qu’il ne décrit pas à lui seul les droits du dossier.", "facile"),
      questions.tf("Ajouter le dossier courant « . » dans PATH est une bonne pratique, car cela permet de lancer plus vite les scripts présents dans n’importe quel dossier.", false, "Faux : ajouter « . » dans PATH augmente le risque de lancer par erreur un programme piégé portant un nom familier comme « ls » ou « grep ». Le gain de confort ne compense pas le risque de sécurité, surtout sur une machine d’administration.", "moyen"),
      questions.multi("Quels outils t’aident directement à comprendre une commande inconnue ? (plusieurs réponses)", ["« man ls »", "« ls --help »", "« type ls »", "« rm -rf / »"], [0, 1, 2], "Le manuel, l’aide courte et l’identification par le shell sont les bonnes portes d’entrée. La dernière option est au contraire l’exemple classique d’une commande destructrice qu’on ne lance jamais pour « voir ce que ça fait ».", "moyen"),
      questions.choice("Lis l’énoncé suivant : « grep -rn motdepasse /home/awa/notes ». Quel morceau est l’argument qui indique où chercher ?", ["« grep »", "« -rn »", "« motdepasse »", "« /home/awa/notes »"], 3, "Le chemin « /home/awa/notes » dit à « grep » où chercher. Le motif est « motdepasse », le programme est « grep » et « -rn » regroupe deux options courtes. Beaucoup de débutants confondent le motif et le chemin parce qu’ils viennent tous les deux après les options.", "difficile"),
    ],
  },
};

const linuxNavigationLesson: NewLesson = {
  key: "l-c3-1",
  title: "Naviguer dans le système de fichiers Linux",
  summary: "Repère les grands dossiers Linux, manipule chemins absolus et relatifs, et déplace-toi sans te perdre entre « / », « ~ », « .. » et les points de montage.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("décrire l’arborescence Linux, distinguer chemin absolu et chemin relatif, utiliser « pwd », « ls », « cd », « file » et « stat », repérer les dossiers importants pour la sécurité, et calculer un répertoire final après plusieurs « cd »."),
    prerequisites("avoir suivi « Le terminal et le shell : lire une commande et trouver de l’aide » ou déjà savoir lancer une commande simple."),
    scenario("Koffi récupère un export de serveur pour aider Atlas à trier des fichiers de configuration et des journaux. Il vient de Windows et cherche encore ses repères : pas de « C: », beaucoup de dossiers commencent par « / », et certains noms se ressemblent. Pour éviter de modifier le mauvais endroit, il doit comprendre comment Linux range son système avant d’aller plus loin."),
    videoSlot("Naviguer dans Linux sans se tromper de dossier"),
    text("Sous Linux, tout s’organise dans une seule arborescence qui part de « / », la racine. Il n’y a pas de lettres de lecteur comme sous Windows : un disque, une clé ou un autre système de fichiers est monté quelque part dans cette arborescence. L’idée « tout est fichier » aide à raisonner : fichiers ordinaires, dossiers, périphériques et parfois informations du noyau sont exposés comme des chemins. Pour un défenseur, cela simplifie beaucoup l’inspection, car configuration, journaux et données se trouvent dans des emplacements assez prévisibles."),
    figure({
      kind: "table",
      title: "Grands repères de l’arborescence Linux",
      columns: ["Chemin", "Rôle"],
      rows: [
        ["`/`", "racine de toute l’arborescence"],
        ["`/boot`", "fichiers du démarrage"],
        ["`/home`", "dossiers personnels des utilisateurs"],
        ["`/root`", "dossier personnel de root"],
        ["`/etc`", "configuration locale du système"],
        ["`/var/log`", "journaux"],
        ["`/run`", "état depuis le dernier démarrage"],
        ["`/tmp`", "fichiers temporaires effaçables"],
        ["`/usr`", "programmes, bibliothèques, documentation"],
        ["`/bin` et `/sbin`", "souvent liés vers `/usr` sur les distributions récentes"],
        ["`/opt` et `/srv`", "logiciels additionnels, données servies"],
        ["`/dev`, `/proc`, `/sys`", "périphériques et vues du noyau"],
        ["`/mnt` et `/media`", "montages manuels, médias amovibles"],
      ],
      mono: [0],
    }),
    text("Chaque dossier raconte quelque chose sur la sécurité. « /etc » contient les réglages à surveiller et à sauvegarder. « /var/log » contient les journaux utiles en audit ou en investigation. « /run » garde des informations volatiles depuis le dernier démarrage, par exemple des PID ou des sockets. « /tmp » sert aux fichiers temporaires et peut être vidé automatiquement. « /home » contient les données des utilisateurs, alors que « /root » appartient à l’administrateur. Les dossiers « /proc » et « /sys » ne sont pas des archives classiques : ils exposent surtout des informations dynamiques du noyau et du matériel."),
    text("Sur beaucoup de distributions modernes, « /bin » et « /sbin » sont aujourd’hui des liens vers « /usr/bin » et « /usr/sbin ». Tu verras donc encore ces anciens chemins dans des guides ou des scripts, mais les programmes réels vivent souvent sous « /usr ». Autre distinction utile : « /mnt » sert souvent aux montages temporaires faits à la main, alors que « /media » reçoit plus volontiers les clés USB et autres médias amovibles gérés par l’environnement."),
    text("Un chemin absolu commence par « / ». Un chemin relatif part du dossier courant. « . » désigne le dossier courant, « .. » son parent, « ~ » le dossier personnel du compte, et « cd - » revient au dossier précédent. Linux distingue les majuscules et les minuscules : « Rapport.txt » et « rapport.txt » sont deux fichiers différents. Les noms qui commencent par un point sont cachés par défaut dans « ls ». Un lien symbolique est un raccourci vers un autre chemin. Enfin, un point de montage est l’endroit où un autre système de fichiers apparaît dans l’arborescence."),
    figure({
      kind: "cards",
      title: "Repères de navigation",
      columns: 2,
      items: [
        { term: "`pwd`", text: "où suis-je ?", icon: "pin", tone: "green" },
        { term: "`ls -la`", text: "lister, y compris les fichiers cachés", icon: "list", tone: "blue" },
        { term: "`ls -lh`", text: "tailles lisibles", icon: "document", tone: "blue" },
        { term: "`ls -R`", text: "parcours récursif", icon: "layers", tone: "violet" },
        { term: "`cd /etc`", text: "chemin absolu", icon: "route", tone: "amber" },
        { term: "`cd ..`", text: "remonter d’un niveau", icon: "upload", tone: "neutral" },
        { term: "`cd ~`", text: "revenir au dossier personnel", icon: "home", tone: "green" },
        { term: "`cd -`", text: "revenir au dossier précédent", icon: "refresh", tone: "violet" },
      ],
    }),
    text("Démonstration guidée : commence à la racine, affiche quelques dossiers clés, identifie un fichier, puis reviens dans ton dossier personnel. « file » t’aide à reconnaître la nature d’un chemin. « stat » donne plus de détails, comme la taille et les dates. Quand tu veux un affichage stable pour un script, « stat -c » est souvent plus lisible que la sortie complète. Si « tree » est installé, il résume très bien une arborescence, mais il n’est pas toujours présent : ne base pas ta méthode uniquement dessus."),
    code("# se repérer et se déplacer\npwd\ncd /\nls -ld / /etc /run /var/log /home\nfile /etc/hosts\nstat -c 'File: %n | Type: %F | Size: %s bytes' /etc/hosts\ncd ~\npwd\n\n# exemple de sortie (valeurs fictives)\n# /home/awa\n# drwxr-xr-x  20 root root 4096 Oct  3 08:50 /\n# drwxr-xr-x  95 root root 4096 Oct  3 09:00 /etc\n# drwxr-xr-x  30 root root  920 Oct  3 09:00 /run\n# drwxr-xr-x  12 root root 4096 Oct  3 09:00 /var/log\n# drwxr-xr-x   4 root root 4096 Oct  3 08:50 /home\n# /etc/hosts: ASCII text\n# File: /etc/hosts | Type: regular file | Size: 123 bytes\n# /home/awa", "bash"),
    example("Exemple corrigé : point de départ « /home/awa/projets ». Tu exécutes « cd .. », puis « cd /var/log », puis « cd ../tmp ». Après « cd .. », tu es dans « /home/awa ». Ensuite, « cd /var/log » te place dans un chemin absolu qui oublie le chemin précédent. Enfin, « cd ../tmp » part de « /var/log », remonte à « /var » puis entre dans « /var/tmp ». Le répertoire final est donc « /var/tmp »."),
    mistakes("chercher des lettres de lecteur au lieu de raisonner avec « / » ; confondre « /root » avec « / », alors que le premier est un dossier personnel ; oublier la sensibilité à la casse ; lancer un « find / -name » sur un système qui n’est pas le tien au lieu de rester sur ton propre environnement de test."),
    safety("n’explore et ne recherche que sur ta machine, ta machine virtuelle ou un environnement explicitement autorisé. Même une simple recherche peut révéler des fichiers sensibles. Quand tu testes une commande large comme « find », commence par un dossier d’essai ou un chemin limité."),
    takeaway("Linux range tout dans une seule arborescence partant de « / ». Les chemins absolus commencent par la racine, les chemins relatifs dépendent du dossier courant. Savoir lire « /etc », « /var/log » et « /home » est déjà une base solide pour l’administration et l’audit."),
    practice("ouvre le laboratoire « TP 1 : explorer l’arborescence et chercher dans les fichiers », puis refais les exercices de chemins absolus et relatifs avant la partie filtrage. Termine par le quiz de la leçon."),
    reference("man7Hier"),
    reference("fhs"),
    reference("openclassroomsLinux"),
  ],
  quiz: {
    title: "Quiz : naviguer dans le système de fichiers Linux",
    questions: [
      questions.choice("Quel dossier contient le plus directement les journaux système utiles à un audit ?", ["« /tmp »", "« /var/log »", "« /root »", "« /usr »"], 1, "« /var/log » est l’emplacement classique des journaux sous Linux. « /tmp » contient du temporaire, « /root » le dossier personnel de root et « /usr » surtout des programmes et bibliothèques, donc ces réponses ne correspondent pas à l’objectif d’audit.", "facile"),
      questions.tf("Sous Linux, « Rapport.txt » et « rapport.txt » désignent en général deux chemins différents.", true, "Vrai : Linux distingue majuscules et minuscules dans les noms de fichiers. Oublier cette règle entraîne vite des erreurs de copie, de script ou de lecture de configuration, surtout quand on vient d’un environnement moins strict sur ce point.", "moyen"),
      questions.multi("Quels énoncés sur la navigation sont corrects ? (plusieurs réponses)", ["« ~ » renvoie au dossier personnel du compte courant", "« cd - » revient au dossier précédent", "« .. » désigne toujours la racine « / »", "Un chemin absolu commence par « / »"], [0, 1, 3], "Le tilde mène au dossier personnel, « cd - » revient au dernier dossier utilisé et un chemin absolu commence bien par « / ». La réponse trompeuse est « .. » : il désigne seulement le parent du dossier courant, pas automatiquement la racine.", "moyen"),
      questions.choice("Point de départ : « /home/awa/projets ». Tu exécutes « cd .. », puis « cd /var/log », puis « cd ../tmp ». Où arrives-tu ?", ["« /home/awa/tmp »", "« /var/log/tmp »", "« /var/tmp »", "« /tmp »"], 2, "Le premier « cd .. » amène à « /home/awa », mais le chemin absolu « /var/log » efface ce contexte. Depuis « /var/log », « ../tmp » remonte vers « /var » puis entre dans « /var/tmp ». Beaucoup d’apprenants choisissent « /tmp » trop vite en oubliant cette étape intermédiaire.", "difficile"),
    ],
  },
};

const linuxFichiersLesson: NewLesson = {
  key: "linux-fichiers",
  title: "Créer, copier, déplacer et supprimer sans rien casser",
  summary: "Maîtrise les commandes de base pour manipuler des fichiers et des dossiers, avec les bons réflexes de prudence avant une copie, un renommage ou une suppression.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("utiliser « mkdir », « touch », « cp », « mv », « rm », « rmdir » et « ln -s », expliquer les jokers et les accolades, prévisualiser une suppression avec le shell, et protéger les noms contenant des espaces ou commençant par un tiret."),
    prerequisites("avoir suivi « Naviguer dans le système de fichiers Linux » ou savoir te déplacer dans une arborescence simple."),
    scenario("Fatou doit ranger des exports reçus de plusieurs équipes dans « /srv/atelier ». Les fichiers arrivent avec des extensions mélangées, certains noms contiennent des espaces, et une collègue lui demande de supprimer les doublons. Pour éviter un effacement irréversible, elle veut une méthode où chaque étape se vérifie avant la suivante."),
    videoSlot("Manipuler des fichiers Linux sans accident"),
    text("Pour créer un dossier, utilise « mkdir ». Avec « -p », la commande crée aussi les parents manquants. « touch » crée un fichier vide ou met à jour sa date. « cp » copie : « -r » est nécessaire pour un dossier, et « -i » demande confirmation avant d’écraser. « mv » déplace ou renomme selon la destination : si elle est un dossier existant, le fichier y entre ; sinon il prend ce nouveau nom. « rm » supprime, « rm -i » demande confirmation, « rmdir » ne supprime qu’un dossier vide. « ln -s » crée un lien symbolique, c’est-à-dire un raccourci vers un autre chemin. Garde toujours en tête qu’il n’y a pas de corbeille intégrée dans « rm » : une suppression réussie est en général définitive."),
    figure({
      kind: "terminal",
      title: "Commandes de base pour manipuler des fichiers",
      lines: [
        { kind: "cmd", text: "mkdir -p dossiers/archives" },
        { kind: "cmd", text: "touch note.txt" },
        { kind: "cmd", text: "cp -i rapport.txt rapport.txt.bak" },
        { kind: "cmd", text: "cp -r source/ copie/" },
        { kind: "cmd", text: "mv ancien.txt nouveau.txt" },
        { kind: "cmd", text: "rm -i fichier.txt" },
        { kind: "cmd", text: "rmdir dossier_vide" },
        { kind: "cmd", text: "ln -s /srv/atelier/config.conf config-actuelle" },
      ],
    }),
    text("Le shell développe les jokers avant d’appeler la commande. « * » signifie « n’importe quelle suite de caractères », « ? » un seul caractère et « [abc] » un caractère parmi plusieurs. Les accolades, comme dans « facture-{01..03}.txt », servent à générer plusieurs noms. Ces jokers sont ceux du shell : ils ne se comportent pas comme les motifs de « grep ». Avant une suppression, « echo *.txt » montre ce que le shell sélectionnera vraiment. C’est une habitude simple qui évite de supprimer plus que prévu."),
    text("Pour écrire vite un petit fichier, tu peux utiliser « cat > note.txt », taper le contenu, puis finir avec Ctrl+D. « nano » est plus confortable pour modifier : Ctrl+O enregistre, Ctrl+X quitte. Deux pièges reviennent souvent. Le premier concerne les espaces : sans guillemets, « Rapport final.txt » devient deux arguments séparés. Le second concerne les noms qui commencent par un tiret : un fichier nommé « -rapport.txt » peut être pris pour une option. Dans ce cas, ajoute « -- » avant le nom pour dire à la commande que les options sont terminées. De manière générale, fais une copie de sauvegarde avant de modifier un fichier de configuration, par exemple « cp fichier fichier.bak »."),
    text("Démonstration guidée : travaille dans un dossier d’essai créé avec « mktemp -d », puis vérifie chaque résultat. Crée une arborescence, prévisualise un groupe de fichiers, classe-les par type et relis le résultat avec « find ». Cette discipline te servira aussi plus tard pour préparer une sauvegarde ou nettoyer des journaux sans toucher à la production."),
    code("# préparer un dossier d’essai\nworkdir=$(mktemp -d)\ncd \"$workdir\"\nmkdir -p notes source/{images,textes,archives}\ntouch notes/guide.txt notes/lecture.txt notes/photo.jpg notes/tableau.csv\n\n# prévisualiser puis classer\ncd notes\nprintf '%s\\n' *.txt\nmv -- *.jpg ../source/images/\nmv -- *.txt ../source/textes/\nmv -- *.csv ../source/archives/\ncd \"$workdir\"\nfind source -maxdepth 2 -type f | sort\n\n# exemple de sortie (valeurs fictives)\n# guide.txt\n# lecture.txt\n# source/archives/tableau.csv\n# source/images/photo.jpg\n# source/textes/guide.txt\n# source/textes/lecture.txt", "bash"),
    example("Exemple corrigé : pour trier 12 fichiers en 3 dossiers, tu peux d’abord créer « images », « textes » et « archives », puis déplacer « *.jpg » vers le premier, « *.txt » vers le second et « *.csv », « *.zip » et « *.tar.gz » vers le troisième. Le résultat attendu est celui montré par « find » : 3 images, 4 textes et 5 archives. Ce tri fonctionne parce que les jokers sont évalués par le shell avant « mv »."),
    mistakes("utiliser « rm » sans avoir d’abord listé ce que le joker vise ; croire que « mv » ne fait que renommer alors qu’il peut aussi déplacer ; oublier les guillemets autour d’un nom avec espace ; réutiliser une variable vide dans une commande destructive au lieu de vérifier sa valeur avant."),
    safety("supprimer récursivement doit rester une opération exceptionnelle et préparée. Vérifie le dossier cible avec « pwd » et « ls » avant toute suppression large. Sur un fichier de configuration, préfère une copie « .bak » et un dossier de test à une modification directe en production."),
    takeaway("Créer, copier, déplacer et supprimer sont des gestes simples seulement quand tu vérifies d’abord les chemins et les jokers. Le shell prépare les arguments avant le programme. Les guillemets, « -- » et une copie de sauvegarde évitent beaucoup d’accidents."),
    practice("ouvre le laboratoire « TP 1 : explorer l’arborescence et chercher dans les fichiers », puis refais la partie rangement et reconstitution de chemins avant les filtres sur journaux et CSV. Termine par le quiz de la leçon."),
    reference("ubuntuFrConsole"),
    reference("man7Ln"),
    reference("gnuCoreutils"),
  ],
  quiz: {
    title: "Quiz : manipuler des fichiers sans casse",
    questions: [
      questions.choice("À quoi sert surtout « mkdir -p » ?", ["À supprimer un dossier avec ses enfants", "À créer un dossier et ses parents manquants si besoin", "À copier récursivement un dossier", "À afficher l’arborescence complète"], 1, "« mkdir -p » crée le dossier demandé et les parents intermédiaires si nécessaire. Beaucoup de débutants le confondent avec une option de copie récursive parce que les deux servent souvent sur des arborescences entières, mais ce n’est pas du tout le même rôle.", "facile"),
      questions.tf("Avant « rm *.txt », afficher d’abord « echo *.txt » est un bon réflexe de prudence.", true, "Vrai : « echo *.txt » montre exactement ce que le shell développera avant d’appeler « rm ». Ce contrôle rapide permet de repérer un joker trop large ou un dossier inattendu avant une suppression qui, elle, n’offre pas de corbeille par défaut.", "moyen"),
      questions.multi("Quels énoncés sont justes pour éviter les pièges sur les noms de fichiers ? (plusieurs réponses)", ["Mettre des guillemets autour d’un nom contenant des espaces", "Utiliser « -- » avant un nom qui commence par un tiret", "Supposer que « mv » ne peut jamais déplacer vers un autre dossier", "Faire une copie « .bak » avant de modifier un fichier sensible"], [0, 1, 3], "Les guillemets protègent les espaces, « -- » coupe l’analyse des options, et une copie « .bak » crée un retour arrière simple. Le faux ami ici est « mv » : il peut renommer ou déplacer, donc il faut toujours relire sa destination.", "moyen"),
      questions.choice("Tu vois le résultat suivant après un tri : « source/images » contient 3 fichiers, « source/textes » en contient 4 et « source/archives » en contient 5. Combien de fichiers ont été rangés au total ?", ["9", "10", "11", "12"], 3, "Le total vaut 3 + 4 + 5 = 12 fichiers. La réponse 10 ou 11 paraît plausible si l’on oublie un dossier, ce qui est précisément l’erreur que l’on évite en relisant la sortie de « find » après l’opération.", "difficile"),
    ],
  },
};

const linuxTexteLesson: NewLesson = {
  key: "linux-texte",
  title: "Lire et chercher dans du texte : less, tail et grep",
  summary: "Lis rapidement un journal ou un export, puis retrouve des lignes utiles avec « less », « head », « tail », « wc » et « grep » sans te perdre dans le volume.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("utiliser « cat », « less », « head », « tail », « wc -l » et « grep », expliquer les options « -i », « -n », « -v », « -c », « -r », « -E » et « -w », lire une expression régulière simple, et interpréter le code de retour de « grep »."),
    prerequisites("avoir suivi « Créer, copier, déplacer et supprimer sans rien casser » ou déjà savoir ouvrir un fichier texte depuis le terminal."),
    scenario("Mamadou reçoit un extrait de journal SSH, un fichier CSV et plusieurs notes de configuration. Les fichiers sont trop longs pour être lus avec « cat » d’un seul bloc, et il veut d’abord retrouver les échecs de connexion puis vérifier si un mot de passe en clair traîne dans ses propres dossiers de test. Il lui faut donc des commandes de lecture et de recherche rapides, pas une lecture ligne par ligne à l’aveugle."),
    videoSlot("Chercher dans un journal Linux avec less, tail et grep"),
    text("« cat » affiche un fichier tel quel, ce qui devient vite pénible sur un gros journal. « less » est plus adapté : tu défiles avec les flèches, tu cherches avec « /mot », tu répètes avec « n », tu vas au début avec « g », à la fin avec « G », puis tu quittes avec « q ». « head -n » montre les premières lignes, « tail -n » les dernières et « tail -f » suit un journal qui grandit. « wc -l » compte les lignes : c’est utile pour mesurer rapidement la taille d’un fichier avant de choisir l’outil."),
    figure({
      kind: "table",
      title: "Repères de lecture et usages utiles de `grep`",
      columns: ["Commande", "Usage"],
      rows: [
        ["`head -n 5 journal.log`", "voir le début"],
        ["`tail -n 20 journal.log`", "voir la fin"],
        ["`less journal.log`", "lire et chercher"],
        ["`wc -l journal.log`", "compter les lignes"],
        ["`grep -n motif fichier`", "afficher le numéro de ligne"],
        ["`grep -c motif fichier`", "compter les lignes qui correspondent"],
        ["`grep -v motif fichier`", "exclure"],
        ["`grep -E 'motif1|motif2' fichier`", "alternatives"],
      ],
      mono: [0],
    }),
    text("« grep » cherche un motif dans du texte. Avec « -i », la casse est ignorée. Avec « -n », le numéro de ligne apparaît. « -c » compte les lignes qui correspondent, et non le nombre total d’occurrences sur une même ligne, puis « -r » parcourt récursivement un dossier. « -w » demande un mot entier. Les guillemets autour du motif évitent que le shell interprète certains caractères avant « grep ». C’est important, car « *.log » n’est pas un joker de shell une fois passé à « grep » : c’est une expression régulière qui ne veut pas dire la même chose. Les expressions régulières simples suffisent déjà souvent : « ^ » pour le début de ligne, « $ » pour la fin, « . » pour un caractère quelconque, « * » pour une répétition et « [ ] » pour une classe de caractères. Avec « -E », tu peux écrire une alternative comme « erreur|warning »."),
    text("Le code de retour de « grep » est très utile dans un script ou un audit rapide : 0 si le motif a été trouvé, 1 si rien ne correspond, et 2 avec GNU grep en cas d’erreur de lecture ou de syntaxe. Pour de la sécurité défensive, « grep » sert à retrouver des échecs de connexion dans un journal d’authentification, à repérer des secrets oubliés dans ses propres fichiers, par exemple avec « grep -rn 'password' ~/projets », ou à extraire les lignes d’un CSV avant un autre traitement. Évite en revanche de lire un journal volumineux avec « cat » puis de défiler pendant des minutes : commence par cibler."),
    text("Démonstration guidée : lis d’abord deux lignes pour reconnaître le format, puis filtre. Sur l’extrait suivant, « head » donne le début du journal, « grep -n » montre les lignes d’échec pour un compte précis, et « grep -c » t’indique combien d’échecs il y a au total. Cette progression fonctionne aussi bien dans WSL, en machine virtuelle, dans Termux ou sur un vrai serveur où tu n’as pas envie de faire défiler 50 000 lignes à la main."),
    code("# reconnaître le format puis filtrer\nhead -n 2 auth.log\ngrep -n 'Failed password for nadia' auth.log\ngrep -c 'Failed password' auth.log\ntail -n 3 auth.log\n\n# exemple de sortie (valeurs fictives)\n# Oct 03 09:10:01 srv-demo sshd[101]: Failed password for nadia from 192.168.1.20 port 55210 ssh2\n# Oct 03 09:10:08 srv-demo sshd[102]: Failed password for invalid user admin from 192.168.1.21 port 55211 ssh2\n# 1:Oct 03 09:10:01 srv-demo sshd[101]: Failed password for nadia from 192.168.1.20 port 55210 ssh2\n# 4:Oct 03 09:10:18 srv-demo sshd[104]: Failed password for nadia from 192.168.1.20 port 55213 ssh2\n# 7:Oct 03 09:10:33 srv-demo sshd[107]: Failed password for nadia from 192.168.1.20 port 55216 ssh2\n# 10:Oct 03 09:11:02 srv-demo sshd[110]: Failed password for nadia from 192.168.1.20 port 55219 ssh2\n# 7\n# Oct 03 09:10:41 srv-demo sshd[108]: Failed password for invalid user test from 172.16.5.4 port 55217 ssh2\n# Oct 03 09:10:55 srv-demo sshd[109]: Accepted publickey for koffi from 192.168.1.23 port 55218 ssh2: ED25519 SHA256:test456\n# Oct 03 09:11:02 srv-demo sshd[110]: Failed password for nadia from 192.168.1.20 port 55219 ssh2", "bash"),
    example("Exemple corrigé : sur cet extrait de 10 lignes, Nadia apparaît 4 fois dans des lignes « Failed password ». La commande « grep -c 'Failed password for nadia' auth.log » renvoie donc 4. Ce nombre est utile pour un premier tri, mais ne prouve pas à lui seul une compromission : il faut encore regarder les adresses IP, la période et d’éventuelles lignes de succès."),
    mistakes("oublier les guillemets autour d’un motif contenant des caractères spéciaux ; confondre le motif recherché avec une chaîne littérale plus large que prévu ; lire un énorme journal avec « cat » au lieu d’utiliser « less », « head » ou « tail » ; oublier qu’un fichier binaire n’est pas agréable à lire avec des outils prévus pour du texte."),
    safety("cherche des secrets ou des mots comme « password » seulement dans tes propres fichiers, tes exports de laboratoire ou un environnement autorisé. Un simple « grep -rn » peut révéler des données personnelles ou des identifiants, donc manipule les résultats avec la même prudence que les fichiers d’origine."),
    takeaway("Pour lire vite, commence par « head », « tail » ou « less ». Pour chercher, « grep » reste l’outil central, surtout avec « -n », « -c », « -i » et « -E ». Un bon filtrage remplace des minutes de défilement aveugle."),
    practice("ouvre le laboratoire « TP 1 : explorer l’arborescence et chercher dans les fichiers », puis concentre-toi sur la partie filtrage de journal, historique de commandes et fichier CSV avec « grep », « sort », « uniq » et « awk ». Termine par le quiz de la leçon."),
    reference("ubuntuFrConsole"),
    reference("man7Grep"),
    reference("man7Regex"),
  ],
  quiz: {
    title: "Quiz : lire et chercher dans du texte",
    questions: [
      questions.choice("Quel outil est le plus confortable pour lire un long fichier texte en te déplaçant et en cherchant dedans ?", ["« less »", "« rm »", "« chmod »", "« hostname »"], 0, "« less » permet de défiler, de chercher, d’aller au début ou à la fin puis de quitter sans modifier le fichier. Les autres commandes ont des rôles totalement différents et ne servent pas à lire un gros journal de façon pratique.", "facile"),
      questions.tf("Le code de retour 0 de « grep » signifie qu’au moins une correspondance a été trouvée.", true, "Vrai : « grep » renvoie 0 quand il trouve le motif, 1 quand il ne trouve rien, et 2 avec GNU grep en cas d’erreur. Ce détail est précieux en automatisation, car un script peut décider de continuer ou d’alerter selon ce résultat.", "moyen"),
      questions.multi("Quelles affirmations sur « grep » sont correctes ? (plusieurs réponses)", ["« -n » affiche les numéros de ligne", "« -c » compte les lignes correspondantes", "« -E » permet des alternatives comme « erreur|warning »", "« -v » chiffre automatiquement les lignes trouvées"], [0, 1, 2], "« -n », « -c » et « -E » ont bien ces rôles. Le piège est « -v » : cette option inverse la sélection et affiche les lignes qui ne correspondent pas, elle ne chiffre ni ne masque rien du tout. « -c » compte des lignes retenues, pas chaque occurrence séparée sur une même ligne.", "moyen"),
      questions.choice("Lis la commande suivante : « grep -c 'Failed password for nadia' auth.log ». Si elle renvoie 4, que peux-tu conclure immédiatement ?", ["Il y a exactement 4 lignes d’échec pour nadia dans ce fichier", "Le compte de Nadia a été compromis", "Le journal contient 4 adresses IP différentes", "Le fichier compte 4 lignes au total"], 0, "La seule conclusion immédiate est qu’il existe 4 lignes correspondant exactement au motif demandé. Une compromission, un nombre d’IP ou la taille totale du journal exigent d’autres vérifications. C’est précisément l’erreur à éviter : confondre un indice textuel avec une preuve complète.", "difficile"),
    ],
  },
};

const linuxPipesLesson: NewLesson = {
  key: "linux-pipes",
  title: "Redirections et tubes : composer des commandes",
  summary: "Comprends les flux standard, puis compose des filtres avec redirections, tubes, « sort », « uniq », « cut », « tr », « wc », « awk », « tee » et « xargs ».",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer entrée, sortie et erreur standard, utiliser « > », « >> », « 2> », « 2>&1 » et « | », construire un pipeline pas à pas, expliquer pourquoi « uniq -c » attend un tri, et extraire une colonne utile avec « cut » ou « awk »."),
    prerequisites("avoir suivi « Lire et chercher dans du texte : less, tail et grep » ou déjà savoir retrouver des lignes dans un fichier."),
    scenario("Rokia reçoit un export d’accès web et un CSV d’inscrits. Elle ne veut pas écrire un script complet pour chaque question simple : top des adresses, nombre d’inscrits par ville, lignes à exclure. Elle a besoin d’une boîte à outils pour faire parler le texte en plusieurs petites étapes vérifiables."),
    videoSlot("Composer des commandes Linux avec des tubes et des redirections"),
    text("Chaque commande travaille avec trois flux standard : l’entrée standard 0, la sortie standard 1 et l’erreur standard 2. « > » redirige la sortie vers un fichier en l’écrasant, « >> » ajoute à la fin, « 2> » redirige seulement l’erreur et « 2>&1 » fusionne l’erreur avec la sortie. « < » fournit un fichier en entrée. « /dev/null » agit comme une poubelle pour une sortie dont tu ne veux pas. Ces gestes simples suffisent déjà à capter un rapport ou à faire taire un bruit inutile, à condition de te souvenir que « > » écrase."),
    figure({
      kind: "cards",
      title: "Flux standard et redirections",
      columns: 2,
      items: [
        { term: "`0`", text: "entrée standard", tone: "green" },
        { term: "`1`", text: "sortie standard", tone: "blue" },
        { term: "`2`", text: "erreur standard", tone: "red" },
        { term: "`commande > rapport.txt`", text: "écrase `rapport.txt`", tone: "amber" },
        { term: "`commande >> rapport.txt`", text: "ajoute en fin de fichier", tone: "green" },
        { term: "`commande 2> erreurs.log`", text: "garde seulement les erreurs", tone: "violet" },
        { term: "`commande > tout.log 2>&1`", text: "fusionne sortie et erreur", tone: "neutral" },
      ],
    }),
    text("Le tube « | » envoie la sortie d’une commande vers l’entrée de la suivante. C’est la base de la philosophie Unix : faire une chose simple, puis combiner. « sort » trie, « uniq -c » compte les doublons mais seulement si les lignes identiques sont déjà regroupées, « cut -d, -f3 » extrait une colonne selon un séparateur, « tr » transforme des caractères, « wc » compte, « head » garde le début et « awk '{print $1}' » extrait vite la première colonne. « tee » duplique la sortie vers l’écran et un fichier. « xargs » transforme des lignes d’entrée en arguments, ce qui est puissant mais demande de la prudence, surtout avec les espaces et les caractères spéciaux."),
    text("La bonne méthode est de construire un pipeline maillon par maillon. Lance d’abord « awk '{print $1}' acces.log » et vérifie. Ajoute ensuite « sort », relis, puis « uniq -c », puis le tri numérique final. Ainsi, si le résultat devient bizarre, tu sais à quel étage il faut corriger. Cette méthode compte aussi pour des commandes défensives plus sensibles, comme des recherches de fichiers ou des listes à archiver."),
    text("Démonstration guidée : voici un pipeline classique pour obtenir le top des adresses vues dans un journal d’accès. La première commande extrait la première colonne, la seconde trie, la troisième compte les répétitions, la quatrième retrie numériquement en ordre décroissant et « head -5 » ne garde que les cinq premières lignes. La sortie ci-dessous a été relue étape par étape, ce qui est exactement la discipline à garder en administration."),
    code("# top des adresses dans un journal d’accès\nawk '{print $1}' access.log | sort | uniq -c | sort -rn | head -5\n\n# exemple de sortie (valeurs fictives)\n#       4 10.1.0.8\n#       3 192.168.1.20\n#       2 172.16.5.4\n#       1 192.168.1.21", "bash"),
    text("Un CSV se traite souvent avec « cut » et un tri. Sur « inscrits.csv », « cut -d, -f3 » extrait la colonne ville. « tail -n +2 » saute l’en-tête, puis « sort | uniq -c | sort -rn » donne le nombre d’inscrits par ville. « tr 'A-Z' 'a-z' » sert par exemple à normaliser la casse avant de compter. Garde cependant en tête qu’un CSV réel peut contenir des virgules internes ou des guillemets : pour un format irrégulier, un parseur dédié est plus fiable qu’un pipeline improvisé."),
    code("# compter des lignes par ville dans un CSV simple\ncut -d, -f3 inscrits.csv | tail -n +2 | sort | uniq -c | sort -rn\nprintf 'ALERTE SSH\\n' | tr 'A-Z' 'a-z'\n\n# exemple de sortie (valeurs fictives)\n#       4 Dakar\n#       2 Lome\n#       2 Abidjan\n#       1 Cotonou\n# alerte ssh", "bash"),
    example("Exemple corrigé : sur le CSV d’exemple, Dakar apparaît 4 fois, Lome 2 fois, Abidjan 2 fois et Cotonou 1 fois. Sans le premier « sort », « uniq -c » ne compterait pas correctement des valeurs identiques dispersées dans le fichier. Le piège classique est donc de lire « uniq » comme un compteur universel, alors qu’il ne voit que les répétitions déjà consécutives."),
    mistakes("oublier que « > » écrase un fichier existant ; utiliser « uniq -c » sans trier avant ; construire un pipeline complet d’un seul coup puis ne plus savoir où le résultat se déforme ; parser un format irrégulier avec « cut » sans vérifier la structure réelle du fichier."),
    safety("sur un fichier important, redirige d’abord vers un nouveau nom plutôt que d’écraser l’original. Quand tu utilises « xargs », privilégie les couples sûrs comme « -print0 » et « -0 » pour éviter les surprises avec les espaces, les retours à la ligne ou les noms inhabituels."),
    takeaway("Les redirections commandent où vont la sortie et l’erreur. Les tubes enchaînent de petits outils spécialisés. Un bon pipeline se construit et se vérifie morceau par morceau, surtout avant un traitement qui écrira sur disque ou préparera une action plus sensible."),
    practice("ouvre le laboratoire « TP 1 : explorer l’arborescence et chercher dans les fichiers », puis refais les parties filtre de journal, historique et CSV en lisant chaque étape du pipeline. Termine par le quiz de la leçon."),
    reference("man7Sort"),
    reference("man7Awk"),
    reference("gnuCoreutils"),
  ],
  quiz: {
    title: "Quiz : redirections et tubes",
    questions: [
      questions.choice("Quelle redirection ajoute une sortie à la fin d’un fichier existant au lieu de l’écraser ?", ["« > »", "« >> »", "« 2> »", "« | »"], 1, "« >> » ajoute en fin de fichier. « > » écrase, « 2> » vise l’erreur standard et « | » envoie la sortie vers une autre commande. Beaucoup de pertes de données viennent justement d’une confusion entre « > » et « >> ».", "facile"),
      questions.tf("Pour compter correctement des doublons avec « uniq -c », il faut d’abord regrouper les lignes identiques, en pratique avec « sort ».", true, "Vrai : « uniq » ne compte que les répétitions déjà consécutives. Si les valeurs identiques sont dispersées, le résultat sera faux ou incomplet. Le tri préalable n’est donc pas un détail de style, mais une condition du bon résultat.", "moyen"),
      questions.multi("Dans le pipeline « awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -5 », quels rôles sont exacts ? (plusieurs réponses)", ["« awk '{print $1}' » extrait la première colonne", "Le premier « sort » prépare le comptage par « uniq -c »", "Le second « sort -rn » classe du plus grand au plus petit", "« head -5 » fusionne la sortie et l’erreur"], [0, 1, 2], "Les trois premiers rôles sont corrects et expliquent le pipeline de bout en bout. Le faux piège est « head -5 » : cette commande ne fusionne rien, elle se contente de garder les cinq premières lignes du résultat déjà produit.", "moyen"),
      questions.choice("Tu lis la sortie suivante d’un pipeline : « 4 Dakar », « 2 Lome », « 2 Abidjan », « 1 Cotonou ». Quelle ville apparaît le plus dans le CSV ?", ["Lome", "Abidjan", "Cotonou", "Dakar"], 3, "La ville la plus fréquente est Dakar avec 4 occurrences. Les deux villes à 2 semblent proches et peuvent tromper quand on lit trop vite, d’où l’intérêt de trier numériquement de façon décroissante avant d’interpréter le résultat.", "difficile"),
    ],
  },
};

const linuxFindArchivesLesson: NewLesson = {
  key: "linux-find-archives",
  title: "Trouver, comparer et archiver : find, diff, tar",
  summary: "Retrouve des fichiers utiles avec « find », compare deux versions avec « diff », puis prépare et vérifie une archive « tar » sans extraire n’importe quoi.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("utiliser « find » avec « -name », « -type », « -size », « -mtime », « -user » et « -perm », lancer une action sûre avec « -exec » ou « -print0 | xargs -0 », comparer deux fichiers avec « diff » ou « cmp », et créer puis vérifier une archive avec « tar » et « sha256sum »."),
    prerequisites("avoir suivi « Redirections et tubes : composer des commandes » ou déjà savoir enchaîner quelques filtres simples."),
    scenario("Tidiane doit retrouver d’anciens journaux, comparer deux configurations reçues à une heure d’écart et préparer une archive propre avant de la transférer. Il sait déjà lire des chemins, mais veut éviter deux erreurs fréquentes : lancer une recherche trop large sans la tester et extraire aveuglément une archive inconnue dans le mauvais dossier."),
    videoSlot("Trouver et archiver sous Linux avec prudence"),
    text("« find » parcourt une arborescence en testant des conditions. « -name » filtre par nom, « -type f » ou « -type d » distingue fichiers et dossiers, « -size » regarde la taille, « -mtime » l’ancienneté en jours, « -user » le propriétaire et « -perm » les droits. Commence toujours par « -print » ou simplement la recherche seule avant d’ajouter une action. Avec « -exec commande {} \\; », « find » lance la commande une fois par chemin trouvé ; avec « {} + », il peut en regrouper plusieurs. Quand un nom de fichier peut contenir des espaces, le duo « -print0 | xargs -0 » est plus sûr qu’un passage naïf à « xargs »."),
    figure({
      kind: "table",
      title: "Modèles utiles avec `find`",
      columns: ["Commande", "But"],
      rows: [
        ["`find ./logs -type f -name '*.log'`", "chercher des fichiers `.log`"],
        ["`find /srv/atelier -type f -mtime +7`", "viser les fichiers vieux de plus de 7 jours"],
        ["`find /srv/atelier -type f -perm -0002`", "repérer les fichiers modifiables par tous"],
        ["`find /srv/atelier -type f -user awa`", "filtrer sur le propriétaire `awa`"],
        ["`-print`", "afficher"],
        ["`-exec commande {} \\;`", "agir fichier par fichier"],
        ["`-print0 | xargs -0`", "transmettre sans casser les noms"],
      ],
      mono: [0],
    }),
    text("Pour comparer deux versions d’un fichier, « diff -u » montre les lignes retirées et ajoutées, ce qui convient très bien à une configuration. « cmp » compare plus directement deux fichiers binaires ou texte et te dit s’ils diffèrent. Côté intégrité, « sha256sum » calcule une empreinte, puis « sha256sum -c » vérifie qu’un fichier correspond bien à l’empreinte attendue. Cela ne remplace pas une signature complète, mais c’est déjà un contrôle utile avant une restauration ou un transfert."),
    text("Une archive « tar » regroupe plusieurs fichiers dans un seul conteneur. Avec « -czf », tu crées une archive compressée en gzip. Avec « -tzf », tu listes son contenu sans l’extraire. Avec « -xzf -C dossier », tu l’extrais dans le dossier voulu. Par défaut, GNU tar retire le « / » initial des chemins absolus et l’annonce par un avertissement, sauf si tu forces « -P », mais il ne faut pas compter sur cette protection pour tout. Ce réflexe de listing avant extraction reste donc important : une archive inconnue peut contenir des chemins inattendus, voire des « ../ » qu’il faut inspecter avant de la déballer. « locate » peut trouver vite un nom si sa base est à jour, mais sa rapidité vient justement de cette base, pas d’un parcours temps réel."),
    figure({
      kind: "steps",
      title: "Avant d’extraire une archive inconnue",
      numbered: true,
      items: [
        { title: "Lister", text: "commencer avec `tar -tzf archive.tar.gz`", icon: "list", tone: "blue" },
        { title: "Vérifier", text: "relire les chemins affichés", icon: "search", tone: "amber" },
        { title: "Choisir", text: "préparer un dossier cible avec `-C`", icon: "folder", tone: "green" },
        { title: "Contrôler", text: "vérifier l’empreinte si elle est fournie", icon: "shield", tone: "violet" },
        { title: "Extraire", text: "déballer seulement ensuite", icon: "package", tone: "red" },
      ],
    }),
    text("Démonstration guidée : sur un dossier d’essai, commence par retrouver les journaux vieux de plus de 7 jours. Compare ensuite deux fichiers de configuration avec « diff -u », liste le contenu d’une archive, puis vérifie son empreinte. Cette chaîne correspond à un vrai usage défensif : retrouver des preuves, comparer un avant et un après, puis archiver proprement sans supposer que le conteneur reçu est sain."),
    code("# retrouver des journaux anciens\nfind ./logs -type f -name '*.log' -mtime +7 | sort\n\n# comparer deux versions d’un fichier\ndiff -u comparaison/config-v1.conf comparaison/config-v2.conf\n\n# lister et vérifier une archive\ntar -tzf sauvegarde/demo.tar.gz\nsha256sum -c sauvegarde/SHA256SUMS\n\n# exemple de sortie (valeurs fictives)\n# ./logs/app/ancien.log\n# ./logs/app/tres-ancien.log\n# --- comparaison/config-v1.conf\n# +++ comparaison/config-v2.conf\n# @@ -1,2 +1,2 @@\n#  mode=prod\n# -port=8080\n# +port=9090\n# dossier/\n# dossier/a.txt\n# dossier/b.txt\n# sauvegarde/demo.tar.gz: OK", "bash"),
    example("Exemple corrigé : sur le dossier d’essai, la commande « find ./logs -type f -name '*.log' -mtime +7 » renvoie 2 fichiers, « ancien.log » et « tres-ancien.log ». C’est un bon point de départ pour un audit, mais pas une preuve suffisante d’incident : une date de modification se change, donc elle sert à orienter la recherche, pas à conclure seule."),
    mistakes("lancer « -exec » avant d’avoir vérifié la liste produite par « find » ; extraire une archive inconnue sans la lister d’abord ; confondre comparaison de contenu et preuve d’intégrité ; oublier que « xargs » simple se casse facilement sur des noms avec espaces ou retours à la ligne."),
    safety("reste sur tes propres dossiers, tes exports de laboratoire ou un environnement autorisé. N’extrais jamais une archive inconnue directement dans un chemin sensible. Pour une recherche d’audit sur un vrai système, commence par une commande en lecture seule puis documente ce que tu trouves avant toute action."),
    takeaway("« find » sert à retrouver vite des fichiers selon plusieurs critères, « diff » à comprendre ce qui a changé, et « tar » à regrouper ou restaurer proprement. Liste d’abord, vérifie ensuite, puis agis. En défense, la prudence de la méthode compte autant que la commande elle-même."),
    practice("ouvre le laboratoire « TP 1 : explorer l’arborescence et chercher dans les fichiers », puis travaille surtout la partie chemins, recherche ciblée et filtres avant de relier le tout à une petite archive de travail. Termine par le quiz de la leçon."),
    reference("man7Find"),
    reference("man7Tar"),
    reference("wikiTar"),
  ],
  quiz: {
    title: "Quiz : find, diff et archives",
    questions: [
      questions.choice("Quelle option de « find » sert à ne garder que les fichiers ordinaires ?", ["« -type f »", "« -name f »", "« -size f »", "« -perm f »"], 0, "« -type f » sélectionne les fichiers ordinaires. Les autres propositions ressemblent à de vraies options, ce qui les rend plausibles, mais elles n’expriment pas le bon critère de type.", "facile"),
      questions.tf("Avant d’extraire une archive inconnue, la lister avec « tar -tzf » est un bon réflexe.", true, "Vrai : lister l’archive permet de repérer des chemins inattendus, des dossiers remontants ou une structure différente de celle attendue. C’est une étape simple qui évite d’extraire aveuglément dans un mauvais endroit ou d’écraser des fichiers utiles.", "moyen"),
      questions.multi("Quels usages défensifs correspondent bien à la leçon ? (plusieurs réponses)", ["Chercher des fichiers « .log » vieux de plus de 7 jours", "Comparer deux versions d’un fichier de configuration avec « diff -u »", "Vérifier une archive avec « sha256sum -c »", "Conclure à une compromission uniquement parce qu’un fichier est récent"], [0, 1, 2], "Les trois premiers gestes sont de bons usages d’administration et d’audit. La dernière proposition est le piège : une date de modification aide à cibler une recherche, mais ne prouve rien à elle seule sans autres indices ni contexte.", "moyen"),
      questions.choice("La commande « find ./logs -type f -name '*.log' -mtime +7 » renvoie deux fichiers. Quelle conclusion immédiate est correcte ?", ["Deux fichiers « .log » de ce dossier ont plus de 7 jours", "Le système a été compromis il y a 7 jours", "Il n’existe que deux journaux sur toute la machine", "Ces deux fichiers appartiennent forcément au même utilisateur"], 0, "La seule conclusion solide est descriptive : deux fichiers « .log » du périmètre parcouru ont plus de 7 jours. Les autres affirmations demandent des preuves supplémentaires sur l’incident, le périmètre ou les propriétaires des fichiers.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c3:1",
    position: 1,
    existing: { fromTitle: "Prendre en main Linux" },
    title: "Prendre en main Linux",
    description: "Ce module pose les repères indispensables avant toute administration : ce qu’est Linux, où l’utiliser sans risque, puis comment lire une commande et se déplacer dans l’arborescence sans se perdre. Critères de réussite : choisir un environnement d’entraînement adapté ; décomposer une commande et trouver son aide ; te repérer dans « / », « /etc », « /var/log » et « /home » sans confusion.",
    lessons: [linuxDemarrerLesson, linuxTerminalLesson, linuxNavigationLesson],
  },
  {
    key: "c3:4",
    position: 2,
    title: "Fichiers et texte",
    description: "Tu apprends ici à manipuler des fichiers et à faire parler du texte sans casser ton système. Le cœur du module est la méthode : prévisualiser, filtrer, comparer puis archiver proprement avant d’aller vers des usages plus sensibles. Critères de réussite : déplacer et supprimer avec prudence ; retrouver une information utile dans un journal ou un CSV ; construire un pipeline simple avec « grep », « sort », « uniq », « awk » et « find ».",
    lessons: [linuxFichiersLesson, linuxTexteLesson, linuxPipesLesson, linuxFindArchivesLesson],
  },
];
