import {
  code, example, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathBlock, type PathModuleEntry,
} from "./path-kit";

const scriptsBasesLesson: NewLesson = {
  key: "linux-scripts-bases",
  title: "Écrire un premier script shell",
  summary: "Écris tes premiers scripts Bash, passe des arguments, lis un code de retour et automatise une petite tâche d’audit sans copier des commandes au hasard.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("écrire un script Bash avec un shebang, exécuter un fichier rendu exécutable, utiliser « $0 », « $1 », « $@ » et « $# », tester une condition simple, et relire la sortie avec « bash -n » puis « bash -x »."),
    prerequisites("avoir suivi « Redirections et tubes : composer des commandes » et « Lire et chercher dans du texte : less, tail et grep »."),
    scenario("Awa reçoit un export de journal SSH et doit compter vite les échecs de connexion avant la réunion du matin. Elle travaille sur un poste Windows modeste, avec Git Bash, et veut éviter de retaper la même commande à chaque nouveau fichier. Un script shell lui permet d’encapsuler la logique, de la relire et de la rejouer sans rien oublier. Le but n’est pas de faire du « grand développement », mais d’automatiser proprement une tâche répétitive d’administration."),
    videoSlot("Écrire un premier script Bash sans magie"),
    text("Un script shell est un fichier texte que Bash lit ligne par ligne. La première ligne, « #!/bin/bash », s’appelle le shebang : elle indique quel interpréteur doit exécuter le fichier. Ensuite, tu rends le script exécutable avec « chmod +x ». Cette mécanique fonctionne sur un vrai Linux, mais aussi pour t’exercer gratuitement dans WSL, une machine virtuelle ou Git Bash. Sur Android, Termux suffit pour les scripts de base qui ne dépendent pas de « systemd » ou de droits d’administration."),
    schema("#!/bin/bash\n./script.sh journal.log\n\n$0  nom du script\n$1  premier argument\n$@  tous les arguments\n$#  nombre d’arguments\n$?  code de retour de la dernière commande\n\n0   succès\n1   erreur fonctionnelle simple\n2   mauvais usage du script"),
    text("Le shell remplace les variables avant d’exécuter une commande. « journal=$1 » stocke donc le premier argument dans la variable « journal ». Les tests de Bash, écrits avec « [[ ... ]] », servent à vérifier un fichier, un dossier ou un texte vide avant d’aller plus loin. Tu n’as pas besoin d’apprendre tout Bash d’un coup : pour un premier script utile, maîtrise d’abord les variables, « if », « for », « while », « $(commande) » et « printf »."),
    text("Démonstration guidée : voici un script minimal qui compte les lignes « Failed password » dans un export de journal. Il a été testé dans Git Bash sur un fichier d’exemple. La logique tient en trois étapes : prendre l’argument, compter avec « grep -c », puis afficher un résultat lisible."),
    code("# Script de base\ncat > compter-echecs.sh <<'EOF'\n#!/bin/bash\nfichier=$1\ncompte=$(grep -c \"Failed password\" \"$fichier\")\nprintf 'Echecs SSH: %s\\n' \"$compte\"\nEOF\nchmod +x compter-echecs.sh\n./compter-echecs.sh auth.log\n# exemple de sortie (valeurs fictives)\n# Echecs SSH: 5", "bash"),
    text("Un deuxième usage classique consiste à boucler sur plusieurs fichiers. Le shell parcourt alors une liste, par exemple « ./*.jpg », et applique la même opération à chacun. Le mot-clé important est « même » : un script shell excelle sur des tâches répétitives, modestes et transparentes. Quand la logique devient longue ou fragile, tu gardes le shell pour l’orchestration et tu délègues le reste à un outil plus adapté."),
    code("# Renommer tous les JPG d'un dossier d'essai\ncat > renommer-jpg.sh <<'EOF'\n#!/bin/bash\nprefixe=$1\nfor fichier in ./*.jpg; do\n  base=${fichier#./}\n  nouveau=\"${prefixe}${base}\"\n  mv \"$base\" \"$nouveau\"\n  printf '%s -> %s\\n' \"$base\" \"$nouveau\"\ndone\nEOF\nchmod +x renommer-jpg.sh\n./renommer-jpg.sh archive-\nls -1 *.jpg *.txt\n# exemple de sortie (valeurs fictives)\n# photo final.jpg -> archive-photo final.jpg\n# photo-01.jpg -> archive-photo-01.jpg\n# archive-photo final.jpg\n# archive-photo-01.jpg\n# notes.txt", "bash"),
    example("Exemple corrigé : si ton dossier contient « photo-01.jpg », « photo final.jpg » et « notes.txt », le script de renommage ne touche que les fichiers qui correspondent au motif « *.jpg ». Il préserve l’espace dans « photo final.jpg » parce que le nouveau nom est construit dans une variable citée entre guillemets. Sans cette rigueur, tu passerais déjà d’un script utile à un script imprévisible."),
    text("Pour déboguer, commence par « bash -n script.sh » : Bash vérifie la syntaxe sans exécuter le fichier. Ensuite, « bash -x script.sh ... » montre chaque ligne au moment où elle part réellement vers l’interpréteur. Cette trace est précieuse quand un « if » ne prend pas la branche attendue ou quand une variable ne contient pas ce que tu crois."),
    mistakes("oublier le shebang puis lancer le fichier comme un binaire ; confondre le nom du script « $0 » avec son premier argument « $1 » ; écrire un script sans le tester sur un petit jeu de données d’exemple ; croire qu’un copier-coller suffit sans relire les chemins et les variables."),
    safety("teste toujours tes premiers scripts dans un dossier de démonstration, sur ta machine, WSL, une machine virtuelle ou Termux. Évite les suppressions et les écritures sur des fichiers réels tant que tu n’as pas vérifié la sortie avec « echo », « printf » ou un simple « ls »."),
    takeaway("un script shell est d’abord un fichier texte lisible. Le shebang choisit Bash, les arguments « $1 » et « $@ » font entrer les données, et le code de retour dit si l’exécution s’est bien passée. Commence petit, teste sur des exemples, puis ajoute une boucle ou une condition quand la tâche devient répétitive."),
    practice("ouvre le laboratoire « TP 6 : lire, tester et corriger des scripts shell », commence par prédire la sortie des petits scripts, puis rejoue la partie sur les arguments, les boucles et le débogage avec « bash -x ». Termine par le quiz de la leçon."),
    reference("ubuntuFrConsole"),
    reference("tldpBash"),
    reference("gnuBash"),
  ],
  quiz: {
    title: "Quiz : écrire un premier script shell",
    questions: [
      questions.choice("À quoi sert la ligne « #!/bin/bash » placée en tête d’un script ?", ["À chiffrer automatiquement le script", "À indiquer quel interpréteur doit exécuter le fichier", "À créer un utilisateur Bash", "À rendre le script exécutable sans « chmod +x »"], 1, "Le shebang indique à quel programme confier le fichier, ici Bash. Le rendre exécutable reste une étape distincte : sans « chmod +x », le système peut connaître l’interpréteur tout en refusant l’exécution directe.", "facile"),
      questions.choice("Dans un script lancé ainsi « ./compter-echecs.sh auth.log », que vaut « $1 » ?", ["Le nom du script", "Le code de retour de la dernière commande", "Le nombre d’arguments", "Le texte « auth.log »"], 3, "« $1 » représente le premier argument transmis au script, ici « auth.log ». Le piège tentant est de répondre « le nom du script », mais cette information se trouve dans « $0 », pas dans « $1 ».", "moyen"),
      questions.tf("La commande « bash -n script.sh » exécute réellement le script et montre ses sorties.", false, "Faux : « bash -n » vérifie seulement la syntaxe. C’est utile pour repérer une accolade ou un « fi » oublié sans toucher aux fichiers. Pour observer l’exécution réelle, on utilise plutôt « bash -x ».", "moyen"),
      questions.multi("Lis ce petit extrait : « for fichier in ./*.jpg; do mv \\\"$fichier\\\" archive/; done ». Quelles affirmations sont justes ? (plusieurs réponses)", ["La boucle ne parcourt que les fichiers qui finissent par « .jpg »", "Les guillemets autour de « $fichier » protègent les espaces dans le nom", "Le script déplacera aussi automatiquement les fichiers « .txt »", "La commande « mv » renomme ou déplace selon le chemin donné"], [0, 1, 3], "Le motif « *.jpg » limite la boucle aux JPG, les guillemets empêchent la casse sur les espaces, et « mv » sait aussi bien déplacer que renommer. L’option trompeuse est « .txt » : rien dans ce motif ne les sélectionne.", "difficile"),
    ],
  },
};

const scriptsRobustesLesson: NewLesson = {
  key: "linux-scripts-robustes",
  title: "Des scripts fiables et sûrs : guillemets, erreurs, ShellCheck",
  summary: "Rends tes scripts prévisibles : protège les variables, valide les arguments, nettoie les fichiers temporaires et comprends ce que ShellCheck signale vraiment.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("protéger une variable avec des guillemets, expliquer « set -euo pipefail », valider les arguments d’un script, utiliser « mktemp » et « trap » pour nettoyer, et corriger un avertissement ShellCheck de type SC2086."),
    prerequisites("avoir suivi « Écrire un premier script shell » et déjà manipulé des fichiers avec espaces et jokers."),
    scenario("Koffi automatise une copie de journaux pour l’association Teranga. Le script marche sur « auth.log », mais casse le jour où quelqu’un lui donne « journal juin.log ». Comme il sera lancé plus tard par une tâche planifiée, il veut corriger le défaut avant de le déployer sur un serveur Debian. C’est exactement le moment où l’on passe d’un script « qui marche chez moi » à un script fiable."),
    videoSlot("Écrire des scripts Bash qui cassent moins"),
    text("Les trois pannes les plus courantes d’un script shell tiennent à peu de choses : une variable non citée entre guillemets, une variable vide qui change complètement le sens d’une commande, et une erreur ignorée qui laisse croire que tout va bien. Le shell découpe en mots et interprète les jokers avant de lancer la commande : si tu oublies les guillemets autour d’une variable, un simple espace dans un nom de fichier devient déjà un bug."),
    schema("Danger                     Symptôme                      Réflexe\nvariable non citée         espace découpe le nom         écrire \"$var\"\nvariable vide              chemin tronqué ou faux        vérifier l’argument\nerreur ignorée             script continue en silence    tester le retour\nfichier temporaire oublié  traces inutiles ou fuite      mktemp + trap"),
    text("Démonstration guidée : commence par observer l’échec, puis corrige-le. Le script cassé ci-dessous a été testé dans Git Bash avec un fichier nommé « journal juin.log ». Il tente de copier le fichier, mais comme « $fichier » n’est pas cité, Bash le découpe en deux morceaux. Le piège est double : la copie échoue, mais le script affiche quand même « copie terminee » et rend le code 0, car la dernière commande réussit. Le script corrigé ajoute « set -euo pipefail », cite la variable et affiche un message fiable."),
    code("# Script casse\ncat > copie-cassee.sh <<'EOF'\n#!/bin/bash\nfichier=$1\nmkdir -p copie\ncp $fichier copie/\nprintf 'copie terminee\\n'\nEOF\nchmod +x copie-cassee.sh\n./copie-cassee.sh \"journal juin.log\"\necho $?\n# exemple de sortie (valeurs fictives)\n# cp: cannot stat 'journal': No such file or directory\n# cp: cannot stat 'juin.log': No such file or directory\n# copie terminee\n# 0\n\n# Script corrige\ncat > copie-sure.sh <<'EOF'\n#!/bin/bash\nset -euo pipefail\nfichier=${1:?usage: ./copie-sure.sh \"fichier\"}\nmkdir -p copie\ncp -- \"$fichier\" copie/\nprintf 'copie terminee : %s\\n' \"$(basename \"$fichier\")\"\nEOF\nchmod +x copie-sure.sh\n./copie-sure.sh \"journal juin.log\"\nls -1 copie\n# exemple de sortie (valeurs fictives)\n# copie terminee : journal juin.log\n# journal juin.log", "bash"),
    text("« set -euo pipefail » aide beaucoup, mais ne remplace pas la lecture du script. « -e » arrête sur beaucoup d’erreurs, « -u » refuse les variables non définies, et « pipefail » fait remonter l’échec d’une commande située à gauche d’un tube. Pourtant, « -e » ne déclenche pas dans tous les contextes : un test dans « if », la branche gauche de « || » ou un « grep » qui ne trouve rien peuvent demander un traitement explicite. Tu gardes donc un esprit critique : le but n’est pas de réciter une formule magique, mais de décider quand vérifier volontairement une condition."),
    code("# Squelette robuste pour un fichier temporaire\ncat > squelette.sh <<'EOF'\n#!/bin/bash\nset -euo pipefail\ntmp=$(mktemp)\ntrap 'rm -f \"$tmp\"' EXIT\njournal=${1:?usage: ./squelette.sh journal.log}\n[[ -f \"$journal\" ]] || { printf 'fichier absent : %s\\n' \"$journal\" >&2; exit 2; }\ngrep 'Failed password' \"$journal\" > \"$tmp\"\nwc -l \"$tmp\"\nEOF\nbash -n squelette.sh\n# exemple de sortie (valeurs fictives)\n# aucune sortie : la syntaxe est correcte", "bash"),
    text("ShellCheck complète cette discipline. Son avertissement SC2086 signale précisément les expansions non citées, comme « cp $fichier copie/ ». Il ne faut pas suivre l’outil aveuglément, mais le message est souvent un bon déclencheur de relecture. Sur un poste modeste, tu peux déjà coller un script dans le site du projet si tu n’as pas encore l’outil installé localement."),
    example("Exemple corrigé : dans un script de dix lignes qui lance « tar -czf $archive $dossier », écrit « PATH=.:$PATH » et reçoit un mot de passe en argument, trois défauts sautent aux yeux. D’abord, « $archive » et « $dossier » doivent être cités. Ensuite, ajouter « . » au PATH expose à l’exécution d’un faux programme placé dans le dossier courant. Enfin, un secret en argument reste visible dans les colonnes « COMMAND » ou « CMD » de « ps » : mieux vaut lire ce secret depuis l’entrée standard, un fichier protégé ou une variable d’environnement bien contrôlée."),
    mistakes("ajouter « set -euo pipefail » puis croire le script infaillible ; écrire des chemins relatifs dans un script prévu pour cron ; utiliser « eval » sur une entrée externe alors qu’une variable ou un tableau suffit ; laisser des fichiers temporaires traîner dans « /tmp » ou le dossier courant."),
    safety("n’exécute pas un script reçu d’un tiers sans le lire. Les scripts lancés avec des droits élevés doivent utiliser des chemins absolus, vérifier leurs entrées et éviter les secrets en argument, car ceux-ci peuvent apparaître dans la liste des processus."),
    takeaway("un script robuste commence par des guillemets, une validation d’arguments et une gestion claire des erreurs. « set -euo pipefail » aide, « mktemp » et « trap » nettoient, et ShellCheck rappelle les pièges classiques avant qu’ils n’arrivent en production."),
    practice("ouvre le laboratoire « TP 6 : lire, tester et corriger des scripts shell », retrouve la ligne qui casse sur un espace, puis corrige les variables non protégées et les arguments manquants. Termine par le quiz de la leçon."),
    reference("shellcheckSc2086"),
    reference("shellcheck"),
    reference("gnuBash"),
  ],
  quiz: {
    title: "Quiz : scripts robustes et sûrs",
    questions: [
      questions.choice("Pourquoi la commande « cp $fichier copie/ » est-elle dangereuse dans un script ?", ["Parce qu’elle rend automatiquement le fichier exécutable", "Parce qu’une variable non citée peut être découpée en plusieurs mots", "Parce qu’elle supprime la copie précédente", "Parce qu’elle chiffre le fichier avant la copie"], 1, "Sans guillemets, Bash découpe la variable selon les espaces et peut aussi interpréter des jokers. Le danger réel n’est donc pas un chiffrement ou une suppression magique, mais un changement silencieux de la ligne de commande transmise à « cp ».", "facile"),
      questions.tf("« set -euo pipefail » garantit à lui seul qu’un script Bash est sûr.", false, "Faux : cette ligne réduit beaucoup de pièges, mais elle ne remplace ni la validation des arguments, ni la lecture du code, ni le choix de chemins sûrs. Un script peut garder une logique dangereuse même avec cette protection.", "moyen"),
      questions.choice("Que t’indique surtout ShellCheck avec l’avertissement SC2086 ?", ["Que le script manque d’une licence", "Qu’un fichier temporaire n’est pas supprimé", "Qu’une expansion doit souvent être mise entre guillemets", "Que Bash n’accepte plus la commande « grep »"], 2, "SC2086 vise les expansions non citées, source fréquente de découpage en mots ou d’interprétation de jokers. Le faux bon réflexe serait de croire à une règle purement esthétique : c’est une alerte sur le comportement du shell.", "moyen"),
      questions.multi("Lis ce début de script : « tmp=$(mktemp) ; trap 'rm -f \"$tmp\"' EXIT ; journal=${1:?usage} ». Quelles affirmations sont justes ? (plusieurs réponses)", ["« mktemp » crée un nom temporaire plus sûr qu’un nom inventé à la main", "Le « trap » programme le nettoyage du fichier temporaire à la fin normale du script", "« ${1:?usage} » refuse un appel sans premier argument", "Le script devient portable vers n’importe quel shell, même si Bash manque"], [0, 1, 2], "« mktemp », « trap » et « ${1:?usage} » répondent chacun à un problème précis : collision de nom, nettoyage sur sortie normale du shell et argument absent. En revanche, ce script reste écrit pour Bash, notamment parce que le shebang et certaines constructions le supposent.", "difficile"),
    ],
  },
};

const scriptsSecuriteLesson: NewLesson = {
  key: "linux-scripts-securite",
  title: "Automatiser la sécurité : inventaires, alertes et rapports",
  summary: "Écris trois petits scripts défensifs : compter des échecs SSH, suivre l’intégrité d’un dossier et déclencher une alerte simple sur l’occupation d’un disque.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("compter des échecs de connexion par adresse IP, générer puis vérifier un manifeste d’empreintes, parser une sortie « df » pour retourner un code d’alerte, et formater une sortie lisible pour cron ou une supervision simple."),
    prerequisites("avoir suivi « Des scripts fiables et sûrs : guillemets, erreurs, ShellCheck » et connaître « Trouver, comparer et archiver : find, diff, tar »."),
    scenario("Nadia prépare une petite boîte à outils défensive pour Baobab Tech. Elle n’a pas encore accès au serveur de production, mais elle veut tester toute la logique dans Git Bash avant de la déployer sur Debian. Son objectif n’est pas d’écrire un énorme produit de supervision : elle veut trois scripts simples, lisibles et assez fiables pour l’alerter sur des symptômes concrets."),
    videoSlot("Trois petits scripts shell utiles pour la défense"),
    text("Un bon script de sécurité ne remplace ni une supervision complète, ni un EDR, ni un audit humain. En revanche, il sait faire une chose précise et la faire clairement : compter des échecs, produire un manifeste, signaler un seuil dépassé. La vraie valeur tient souvent dans la sortie : une ligne facile à relire, un code de retour cohérent, un jeu de données d’exemple pour vérifier que l’alerte part quand elle doit partir."),
    schema("Format de sortie conseillé\nOK;détail\nALERTE;détail\n\nCode de retour\n0  état normal\n1  alerte à relire\n2  mauvais usage du script"),
    text("Démonstration guidée : premier cas, repérer les adresses qui dépassent un seuil d’échecs SSH. Le script ci-dessous a été testé dans Git Bash sur un export de journal d’exemple. Il filtre les lignes « Failed password », récupère le champ placé après « from », compte avec « uniq -c » et n’affiche que les adresses au-dessus du seuil demandé. S’il n’y a aucun échec dans le fichier, il ne doit pas échouer juste parce que la recherche ne trouve rien."),
    code("# Script d'alerte sur les echecs SSH\ncat > alerte-bruteforce.sh <<'EOF'\n#!/bin/bash\nset -euo pipefail\njournal=${1:?usage: ./alerte-bruteforce.sh journal seuil}\nseuil=${2:?usage: ./alerte-bruteforce.sh journal seuil}\nawk '/Failed password/ { for (i = 1; i <= NF; i++) if ($i == \"from\") print $(i + 1) }' \"$journal\" | sort | uniq -c | awk -v seuil=\"$seuil\" '$1 >= seuil { printf \"%s;%s\\n\", $2, $1 }'\nEOF\nchmod +x alerte-bruteforce.sh\n./alerte-bruteforce.sh auth.log 3\n# exemple de sortie (valeurs fictives)\n# 192.168.1.20;4", "bash"),
    text("Deuxième cas, l’intégrité. Tu peux figer l’état d’un dossier en calculant les empreintes SHA-256 de ses fichiers, puis vérifier plus tard si l’un d’eux a changé. Le manifeste doit être écrit dans le dossier audité avec un chemin cohérent, et la collecte doit accepter les noms contenant des espaces. Pour tester le cas d’échec, modifie ensuite un fichier avant de lancer la vérification. Cette méthode dit qu’un fichier a changé, pas pourquoi, ni qui l’a changé : elle complète un audit, elle ne le remplace pas."),
    code("# Initialiser puis verifier un manifeste d'integrite\ncat > integrite.sh <<'EOF'\n#!/bin/bash\nset -euo pipefail\nmode=${1:?usage: ./integrite.sh init|check dossier manifeste}\ndossier=${2:?usage: ./integrite.sh init|check dossier manifeste}\nmanifeste=${3:?usage: ./integrite.sh init|check dossier manifeste}\nmanifeste_nom=$(basename \"$manifeste\")\ncase \"$mode\" in\n  init)\n    (cd \"$dossier\" && find . -maxdepth 1 -type f ! -name \"$manifeste_nom\" -printf '%P\\0' | LC_ALL=C sort -z | xargs -0 sha256sum -- > \"$manifeste_nom\")\n    ;;\n  check)\n    (cd \"$dossier\" && sha256sum -c \"$manifeste_nom\")\n    ;;\n  *)\n    echo 'mode inconnu' >&2\n    exit 2\n    ;;\nesac\nEOF\nchmod +x integrite.sh\n./integrite.sh init empreintes empreintes/manifeste.sha256\ncat empreintes/manifeste.sha256\nprintf 'port=2222\\n' > empreintes/config.txt\n./integrite.sh check empreintes empreintes/manifeste.sha256\n# exemple de sortie (valeurs fictives)\n# 74a74a728a6f1b19a9a327f223db0c58cfa8c216d8ae75a1a636990c03de27ee *config.txt\n# f4a3b0f16b45a4139d92d6dd9993a35bb7328440d5aa8036b32f02c4ca167bb7 *liste.txt\n# config.txt: FAILED\n# liste.txt: OK\n# sha256sum: WARNING: 1 computed checksum did NOT match", "bash"),
    text("Troisième cas, la supervision minimale. Un script lancé par cron ou par un minuteur doit pouvoir dire rapidement « tout va bien » ou « alerte ». Le plus simple est de parser une sortie « df » exportée, puis de retourner 1 quand le seuil est atteint. Sur un vrai serveur Linux, tu liras directement la commande « df -hP / » ; pour t’exercer sans risque, tu peux commencer avec un fichier d’exemple."),
    code("# Alerter si un point de montage depasse un seuil\ncat > verifier-df.sh <<'EOF'\n#!/bin/bash\nset -euo pipefail\nfichier=${1:?usage: ./verifier-df.sh fichier seuil}\nseuil=${2:?usage: ./verifier-df.sh fichier seuil}\nawk -v seuil=\"$seuil\" 'NR==1 { next } { taux=$5; gsub(/%/, \"\", taux); if (taux + 0 >= seuil) { printf \"ALERTE;%s;%s\\n\", $6, taux; trouve=1; exit 1 } } END { if (!trouve && NR > 1) { printf \"OK;%s\\n\", seuil } }' \"$fichier\"\nEOF\nchmod +x verifier-df.sh\n./verifier-df.sh df.txt 80\necho $?\n# exemple de sortie (valeurs fictives)\n# ALERTE;/;85\n# 1", "bash"),
    example("Exemple corrigé : si ton seuil vaut 85 % sur un volume de 20 Gio, l’alerte doit partir dès 17 Gio utilisés. Le calcul est simple, mais il faut l’écrire une bonne fois : 20 × 0,85 = 17. Dans un rapport, cette conversion aide à expliquer le seuil à une équipe qui raisonne en taille libre et non en pourcentage."),
    text("Ces trois scripts deviennent vraiment utiles quand tu les relies à une tâche planifiée, à un journal et à une habitude de relecture. Un script qui écrit « ALERTE » cinquante fois par jour sans tri finit ignoré. Un script qui produit une ligne sobre, une preuve vérifiable et un code de retour stable est beaucoup plus exploitable pour un administrateur débutant."),
    mistakes("parser un format qui change sans le documenter ; mélanger un rôle d’alerte et un rôle de correction automatique dans le même script ; oublier de tester le code de retour, donc de laisser une supervision aveugle ; garder des exemples trop optimistes qui n’exercent jamais le cas d’échec."),
    safety("les scripts d’alerte se testent d’abord sur des exports ou dans un dossier d’essai. N’écris jamais de mot de passe en clair dans le script, et n’envoie pas automatiquement des actions de correction sur un serveur que tu n’as pas relu et autorisé."),
    takeaway("un petit script défensif vaut par sa clarté : entrée simple, sortie lisible, code de retour cohérent. Compter, vérifier et alerter sont trois tâches parfaites pour le shell tant que tu travailles sur des formats bien compris et des jeux de données testés."),
    practice("ouvre le laboratoire « TP 6 : lire, tester et corriger des scripts shell », rejoue les parties sur les sorties de journaux, les empreintes et les codes de retour, puis adapte les scripts aux fichiers fournis. Termine par le quiz de la leçon."),
    reference("anssiLinux"),
    reference("shellcheck"),
    reference("gnuCoreutils"),
  ],
  quiz: {
    title: "Quiz : automatiser la sécurité",
    questions: [
      questions.choice("Quel est le rôle principal d’un code de retour 1 dans un petit script d’alerte ?", ["Indiquer qu’un état à relire mérite une attention humaine", "Signaler que le script a chiffré le système", "Forcer Bash à redémarrer automatiquement le serveur", "Créer un journal sans contenu"], 0, "Dans une supervision simple, le code 1 représente souvent une alerte fonctionnelle : le script a travaillé, mais le résultat demande une vérification. Le piège serait de le confondre avec une action destructive ou avec un simple succès silencieux.", "facile"),
      questions.choice("Pourquoi le script d’intégrité calcule-t-il des empreintes SHA-256 ?", ["Pour compresser les fichiers avant sauvegarde", "Pour renommer automatiquement les fichiers modifiés", "Pour disposer d’une preuve de changement entre deux états", "Pour ouvrir les fichiers dans « less » plus rapidement"], 2, "Une empreinte stable sert de repère : si le fichier change, l’empreinte change aussi. Elle ne remplace pas un journal ou une investigation, mais elle permet de détecter une modification. Compression, renommage et lecture rapide ne sont pas le sujet.", "moyen"),
      questions.tf("Un script maison qui lit « df » ou un journal SSH remplace à lui seul une supervision complète.", false, "Faux : un script maison couvre un besoin ciblé, souvent très utile, mais il ne remplace ni une collecte centralisée, ni des corrélations, ni des tableaux de bord. Le bon usage est de compléter la surveillance, pas de croire qu’elle est terminée.", "moyen"),
      questions.multi("Lis cette sortie : « ALERTE;/;85 ». Quelles conclusions sont justes ? (plusieurs réponses)", ["Le point de montage « / » a atteint ou dépassé le seuil", "Le script a produit une sortie simple à relire par un autre outil", "Le pourcentage observé vaut 85", "Le script prouve à lui seul pourquoi l’espace disque augmente"], [0, 1, 2], "La ligne dit quoi surveiller et combien a été vu, ce qui est parfait pour une alerte concise. En revanche, elle ne prouve pas la cause de l’occupation : il faut encore enquêter avec des outils comme « du », les journaux ou l’historique des déploiements.", "difficile"),
    ],
  },
};

const durcissementLesson: NewLesson = {
  key: "linux-durcissement",
  title: "Durcir un serveur Linux : checklist, Lynis et référentiels",
  summary: "Réduis la surface d’attaque d’un serveur Linux avec une checklist claire, des commandes d’audit ciblées et des référentiels comme l’ANSSI, CIS ou Lynis.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("expliquer ce qu’est le durcissement, vérifier une checklist de base, interpréter un extrait de Lynis, justifier l’intérêt d’AppArmor ou SELinux, et prioriser des actions selon l’impact et l’exploitabilité."),
    prerequisites("avoir suivi « SSH : connexion, clés et durcissement de sshd_config », « Pare-feu sous Linux : ufw et nftables » et « Correctifs de sécurité, mises à jour et fin de support »."),
    scenario("Moussa reprend un petit serveur web Ubuntu pour Sahel Services. Le site fonctionne, mais personne ne sait vraiment ce qui écoute, quels services sont actifs ni si les sauvegardes sont testées. Moussa ne cherche pas un score parfait pour faire joli : il veut fermer d’abord les portes les plus faciles à abuser, sans casser le service rendu aux utilisateurs."),
    videoSlot("Durcir un serveur Linux sans se perdre dans une liste infinie"),
    text("Durcir un serveur, c’est réduire la surface d’attaque et limiter les dégâts d’une compromission. On retire ce qui ne sert pas, on garde le système à jour, on applique le moindre privilège, on ferme le réseau par défaut et on journalise ce qui compte. Le durcissement n’est pas une course au réglage le plus obscur : c’est une suite de décisions défendables, testées une à une, avec retour arrière possible."),
    schema("Famille                 Vérifications de base\nservices                désactiver l’inutile, compte dédié\ncorrectifs              paquets à jour, redémarrage planifié\ncomptes et SSH          clés, sudo précis, pas de root direct\nréseau                  ports utiles, pare-feu en refus par défaut\nfichiers                droits stricts, partitions sensibles\npreuves                 journaux, sauvegardes, vérification"),
    text("Une checklist simple couvre déjà l’essentiel : installation minimale, comptes nominatifs, clés SSH plutôt que mots de passe, règle « deny incoming » au pare-feu, surveillance des ports à l’écoute, sauvegardes testées, et contrôle d’accès obligatoire si disponible. Sur Ubuntu et Debian, AppArmor ajoute une couche de contrôle d’accès au-dessus des droits classiques. Sur RHEL et Fedora, le rôle est souvent tenu par SELinux. Dans les deux cas, le but est le même : limiter ce qu’un service compromis peut faire."),
    text("Démonstration guidée : commence par relever l’état actuel avant de changer quoi que ce soit. Sur un vrai serveur Linux, tu peux lister les paquets à mettre à jour, les ports ouverts, les unités activées et les fichiers SUID. Tu peux aussi lire quelques paramètres « sysctl » utiles : « kernel.randomize_va_space = 2 » active la randomisation complète de l’espace d’adressage, « net.ipv4.tcp_syncookies = 1 » laisse le noyau activer les SYN cookies quand la file SYN déborde, et « net.ipv4.conf.all.accept_redirects = 0 » évite d’accepter des redirections ICMP sur un serveur durci."),
    code("# Releve de base sur un serveur Debian ou Ubuntu\napt list --upgradable\nss -tulpn\nsystemctl list-unit-files --state=enabled\nfind / -xdev -perm -4000 -type f 2>/dev/null\nsysctl kernel.randomize_va_space net.ipv4.tcp_syncookies net.ipv4.conf.all.accept_redirects\nlynis audit system\n# exemple de sortie (format reel, valeurs variables selon l'hote)\n# kernel.randomize_va_space = 2\n# net.ipv4.tcp_syncookies = 1\n# net.ipv4.conf.all.accept_redirects = 0", "bash"),
    text("Lynis et les référentiels CIS ou ANSSI servent de guide, pas de pilote automatique. Sur l’écran, Lynis enchaîne des tests marqués « [ OK ] » ou « [ WARNING ] », puis regroupe en fin d’exécution les sections « Warnings », « Suggestions » et un « Hardening index ». La documentation du projet précise aussi que le détail technique part dans « /var/log/lynis.log » et les constats utiles dans « lynis-report.dat ». Un indice ou une suggestion n’a donc de valeur que si tu la relies à ton contexte : un port ouvert sans usage, oui, c’est une priorité. Une recommandation qui casse une application critique sans alternative claire, non."),
    schema("Prioriser un constat\nimpact élevé + exploitable à distance      critique\nimpact élevé ou exploitable localement     important\nimpact limité et peu exploitable           mineur\n\nNote aussi l’exposition, la preuve et l’effort de correction."),
    example("Exemple corrigé : si « PasswordAuthentication yes » reste actif sur un SSH exposé à Internet, que le pare-feu autorise trop large et qu’un compte de service possède un shell interactif, tu cumules des constats à forte exploitabilité. Le premier et le deuxième valent facilement 9 sur 9 dans une matrice simple, car l’impact et l’exploitabilité sont élevés. À l’inverse, une rotation de journaux perfectible mais sans panne immédiate ressemble plutôt à un 4 sur 9 : il faut la corriger, mais après les accès distants et le filtrage."),
    mistakes("empiler des changements en une seule maintenance, puis ne plus savoir lequel a cassé le service ; viser un score Lynis parfait sans relire les recommandations ; laisser des mots de passe SSH actifs « juste le temps de tester » ; oublier de documenter l’état avant et après le durcissement."),
    safety("ne durcis jamais directement un serveur que tu ne maîtrises pas sans sauvegarde, fenêtre de changement et retour arrière. Une règle de pare-feu ou un réglage SSH appliqué trop vite peut te couper l’accès ; garde une console ou une session déjà ouverte pendant le test."),
    takeaway("durcir, c’est choisir et vérifier. La base reste simple : moins de services, moins de privilèges, moins de ports, plus de journaux et des sauvegardes testées. Les référentiels et Lynis aident à ne rien oublier, mais la décision finale doit toujours rester contextualisée."),
    practice("ouvre le « Projet final : auditer un serveur Linux et rédiger le rapport », utilise la checklist du cours pour prioriser les écarts, puis compare ta hiérarchie avec les preuves du dossier. Termine par le quiz de la leçon."),
    reference("anssiLinux"),
    reference("lynis"),
    reference("cisBenchmarks"),
    reference("redhatHardening"),
  ],
  quiz: {
    title: "Quiz : durcir un serveur Linux",
    questions: [
      questions.choice("Quel énoncé résume le mieux le durcissement d’un serveur Linux ?", ["Ajouter le plus grand nombre possible d’outils de sécurité", "Réduire la surface d’attaque et l’impact d’une compromission", "Bloquer tout le trafic sortant sans exception", "Changer chaque réglage noyau trouvé sur Internet"], 1, "Le durcissement consiste à réduire ce qui peut être attaqué et ce qu’un attaquant pourrait faire après une compromission. Ajouter des outils ou changer tous les réglages sans méthode peut au contraire augmenter la complexité et les erreurs.", "facile"),
      questions.choice("Dans la ligne « tcp LISTEN 0 128 0.0.0.0:22 », quel constat mérite d’abord une relecture de durcissement ?", ["Le service SSH écoute, donc il faut vérifier s’il est vraiment nécessaire et bien restreint", "Le port 22 prouve que le serveur est déjà compromis", "La ligne signifie que le pare-feu est désactivé", "Le service est forcément limité à 127.0.0.1"], 0, "Cette ligne indique que SSH écoute sur toutes les interfaces IPv4. Ce n’est pas une compromission en soi, mais c’est un point de contrôle important : configuration SSH, pare-feu, origine des connexions autorisées. Le piège serait de tirer une conclusion définitive sans contexte.", "moyen"),
      questions.tf("Un bon indice Lynis dispense de lire les comptes, les ports et les règles SSH à la main.", false, "Faux : un score ou une suggestion reste un signal utile, pas une preuve complète. Les décisions de durcissement exigent encore la lecture du contexte réel, des services exposés, des comptes et des effets métier possibles.", "moyen"),
      questions.multi("Quelles mesures relèvent bien d’un durcissement défensif ? (plusieurs réponses)", ["Désactiver les services inutiles", "Imposer des clés SSH et limiter sudo", "Documenter l’état avant et après un changement", "Laisser un compte de service avec un shell interactif pour gagner du temps"], [0, 1, 2], "Désactiver l’inutile, renforcer les accès et documenter les changements réduisent réellement le risque. Laisser un shell interactif à un compte de service est au contraire un élargissement du risque, pas un durcissement.", "difficile"),
    ],
  },
};

const auditMethodeLesson: NewLesson = {
  key: "linux-audit-methode",
  title: "Mener un audit Linux et rédiger le rapport",
  summary: "Cadre, collecte de preuves, gravité, constats et restitution : apprends une méthode d’audit Linux défensive, lisible et compatible avec un vrai rapport.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("cadrer un audit avec autorisation écrite, collecter des preuves en lecture seule, horodater puis hacher les sorties, qualifier une gravité selon l’impact et l’exploitabilité, et rédiger un constat avec preuve, gravité, recommandation et effort."),
    prerequisites("avoir suivi « Auditer droits, comptes et tâches planifiées » et « Durcir un serveur Linux : checklist, Lynis et référentiels »."),
    scenario("Fatou doit auditer un serveur Debian pour Cabinet Moussa avant une mise en production. Elle a l’autorisation écrite, une fenêtre courte et un objectif clair : relever les écarts sans modifier l’hôte. Son rapport devra être lisible par la direction, mais aussi assez précis pour qu’un administrateur puisse corriger les points relevés et prouver ensuite qu’ils le sont."),
    videoSlot("La méthode d’audit Linux, de la preuve au rapport"),
    text("Un audit Linux commence avant la première commande. Tu définis le périmètre, les comptes autorisés, la fenêtre de temps et le niveau d’intrusion acceptable. En pratique, le mot d’ordre est simple : lecture seule d’abord. Tu documentes les commandes prévues, la destination des preuves et la personne qui valide le cadre. Sans cela, tu risques de modifier le système audité ou de produire un rapport contestable."),
    schema("Étapes d’un audit\n1 cadrer : périmètre, accord écrit, fenêtre\n2 collecter : commandes en lecture seule\n3 figer : horodatage et empreintes\n4 croiser : comptes, réseau, services, journaux\n5 noter : gravité, effort, priorité\n6 restituer : résumé, constats, annexes"),
    text("La collecte de preuves doit être répétable. Tu récupères l’identité du système, la liste des comptes, les services activés, les ports à l’écoute, les tâches planifiées, la configuration SSH, le pare-feu, l’occupation disque et quelques journaux utiles. Chaque sortie est horodatée et conservée telle quelle, puis tu en calcules une empreinte. Cette discipline ne rend pas la preuve parfaite à elle seule, mais elle limite déjà les contestations du type « ce fichier a été retouché après coup »."),
    text("Démonstration guidée : même sans serveur Linux sous la main, tu peux déjà répéter la méthode dans Git Bash avec des commandes disponibles partout, puis réserver les commandes propres au noyau Linux au serveur audité. Le script ci-dessous a été testé sur des données d’exemple et produit un fichier de preuves horodaté avec son empreinte."),
    code("# Script d'inventaire minimal\ncat > inventaire.sh <<'EOF'\n#!/bin/bash\nset -euo pipefail\nsortie=${1:?usage: ./inventaire.sh sortie preuve}\npreuve=${2:?usage: ./inventaire.sh sortie preuve}\nbase=$(dirname \"$sortie\")\npreuve_nom=$(basename \"$preuve\")\nsortie_nom=$(basename \"$sortie\")\n{\n  printf '# date_utc\\n'\n  date -u +\"%Y-%m-%dT%H:%M:%SZ\"\n  printf '# uname\\n'\n  uname -a\n  printf '# id\\n'\n  id\n  printf '# sha256\\n'\n  (cd \"$base\" && sha256sum \"$preuve_nom\")\n} > \"$sortie\"\n(cd \"$base\" && sha256sum \"$sortie_nom\")\nEOF\nchmod +x inventaire.sh\nprintf 'preuve demo\\n' > preuve.txt\n./inventaire.sh preuves.txt preuve.txt\ncat preuves.txt\n# exemple de sortie (format reel, valeurs variables selon l'hote et l'heure)\n# d440ec35ae9cdc870eee330cd0bff4976e5f71d5966f59a0fac3b1c928fc55f4 *preuves.txt\n# # date_utc\n# 2026-10-03T20:14:33Z\n# # uname\n# MINGW64_NT-10.0-26200 DESKTOP-HLJ4RBP 3.6.10-5a1665c8.x86_64 2026-09-28 10:40 UTC x86_64 Msys\n# # id\n# uid=197609(Evans Abah) gid=197609 groups=197609\n# # sha256\n# d816f0cc00168adbaa0a2e37f706f5ac289b8cf5c982c2f9e0cafd29186e4ce1 *preuve.txt", "bash"),
    text("Sur le vrai serveur, tu ajoutes ensuite les commandes de lecture seule utiles au périmètre : « uname -a », « getent passwd », « id », « ss -tulpn », « systemctl list-unit-files --state=enabled », « crontab -l », « journalctl -u ssh --since », « ufw status verbose », « find / -xdev -perm -0002 » et d’autres relevés comparables. L’idée n’est pas d’exécuter tout ce qui existe, mais de couvrir les familles de risque pertinentes et de pouvoir relier chaque constat à une preuve précise. Un bon rapport distingue aussi nettement la gravité du constat, l’effort de correction et l’éventuelle urgence métier."),
    schema("Structure d’un constat\nObservation : ce que tu vois\nPreuve : commande, fichier, extrait\nGravité : critique, importante, mineure\nRecommandation : quoi changer\nEffort : faible, moyen, élevé"),
    example("Exemple corrigé : 1) observation, « le fichier /etc/sudoers.d/nadia accorde NOPASSWD: ALL » ; preuve, la ligne extraite du fichier ; gravité, critique car l’impact et l’exploitabilité sont forts ; recommandation, limiter à des commandes précises ; effort, faible. 2) observation, « le service PostgreSQL écoute seulement sur 127.0.0.1 » ; preuve, la ligne « 127.0.0.1:5432 » dans « ss -tulpn » ; gravité, mineure ; recommandation, aucune urgente. 3) observation, « une tâche cron root appelle un script modifiable par tous » ; preuve, la ligne cron et le mode de fichier ; gravité, critique ; recommandation, corriger les droits et revoir la tâche ; effort, moyen."),
    text("Le rapport final parle à deux publics. En tête, un résumé d’une page maximum explique les risques majeurs, les priorités et les prochaines étapes. Ensuite, un tableau de constats aligne observation, preuve, gravité, recommandation et effort. Les annexes conservent les extraits de commandes et les empreintes. Un audit n’est pas une investigation d’incident : il décrit un état à un instant donné. Quand tu dois reconstruire une intrusion, tu t’orientes plutôt vers une chronologie, comme dans l’évaluation « Incident : un serveur web Linux compromis »."),
    mistakes("auditer sans autorisation écrite ni périmètre ; modifier le système pendant la collecte alors que la mission porte sur l’état observé ; produire un constat sans preuve vérifiable ; écrire des recommandations vagues comme « améliorer la sécurité » sans indiquer quoi changer ni avec quel effort."),
    safety("un audit donne accès à des comptes, des journaux et parfois des données personnelles. Respecte la confidentialité, minimise les copies, protège les preuves collectées et ne conserve pas plus d’informations que nécessaire après la mission."),
    takeaway("un audit Linux crédible repose sur le cadre, la preuve et la rédaction. Lecture seule d’abord, empreintes ensuite, puis constats argumentés. Un bon rapport dit ce qui a été vu, pourquoi c’est risqué, comment corriger, et quel effort prévoir."),
    practice("ouvre le « Projet final : auditer un serveur Linux et rédiger le rapport », applique la méthode du cours pour tes preuves et tes constats, puis compare ton résumé avec les annexes. Reprends aussi « Incident : un serveur web Linux compromis » pour bien distinguer audit d’état et reconstitution d’intrusion. Termine par le quiz de la leçon."),
    reference("anssiHygiene"),
    reference("anssiLinux"),
    reference("nistCsf"),
    reference("lynis"),
  ],
  quiz: {
    title: "Quiz : mener un audit Linux",
    questions: [
      questions.choice("Quelle règle guide le mieux le début d’un audit Linux ?", ["Modifier d’abord les points évidents pour gagner du temps", "Lecture seule d’abord, avec périmètre et autorisation écrite", "Redémarrer les services sensibles avant la collecte", "Installer immédiatement tous les outils de sécurité trouvés"], 1, "Le cadre et la lecture seule protègent la valeur probante de l’audit et évitent d’introduire tes propres changements. Corriger, redémarrer ou installer avant la collecte brouillerait les preuves et rendrait le rapport contestable.", "facile"),
      questions.choice("Pourquoi calculer l’empreinte d’un fichier de preuves avec « sha256sum » ?", ["Pour compresser le rapport avant envoi", "Pour chiffrer automatiquement les journaux", "Pour pouvoir vérifier plus tard que le fichier n’a pas changé", "Pour convertir les preuves en format PDF"], 2, "L’empreinte sert d’empreinte numérique : si le contenu change, le SHA-256 change aussi. Ce n’est ni une compression, ni un chiffrement, ni une conversion de format, mais un moyen simple de contrôler l’intégrité d’un relevé.", "moyen"),
      questions.tf("Le constat « sudo est dangereux » est suffisant dans un rapport d’audit.", false, "Faux : un constat utile doit nommer l’observation, citer la preuve, expliquer le risque et proposer une recommandation. Sans cette structure, la phrase reste trop vague pour être corrigée, priorisée ou défendue devant un responsable.", "moyen"),
      questions.multi("Tu lis ce constat : « une tâche cron root appelle un script en mode 777 ». Que doit contenir un rapport sérieux ? (plusieurs réponses)", ["L’extrait de la tâche cron et le mode du script comme preuves", "Une phrase sur le risque d’exécution avec les droits de root", "Une recommandation précise pour corriger les droits ou la tâche", "Seulement la conclusion « machine compromise » sans autre détail"], [0, 1, 2], "La preuve, le risque et la recommandation forment le cœur d’un constat exploitable. Conclure directement à une compromission sans démonstration serait excessif : le défaut est grave, mais il faut encore distinguer le risque présent de l’attaque effectivement observée.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c3:9",
    position: 8,
    title: "Scripts shell",
    description: "Ce module te fait passer de la commande ponctuelle à l’automatisation défensive lisible et testée. Critères de réussite : écrire un script Bash qui prend des arguments, corriger un défaut de guillemets ou de gestion d’erreur, et produire une alerte ou un rapport simple réutilisable par un autre administrateur.",
    lessons: [scriptsBasesLesson, scriptsRobustesLesson, scriptsSecuriteLesson],
  },
  {
    key: "c3:3",
    position: 9,
    existing: { fromTitle: "Auditer un système Linux" },
    title: "Auditer un système Linux",
    description: "Ce module t’apprend à lire des journaux et des droits, à relever les écarts de durcissement les plus importants et à transformer des preuves techniques en rapport actionnable. Critères de réussite : exploiter correctement les journaux et les droits, prioriser des mesures de durcissement réalistes, et rédiger des constats d’audit avec preuve, gravité, recommandation et effort.",
    lessons: [
      { key: "linux-journaux", existing: true },
      { key: "linux-audit-droits", existing: true },
      durcissementLesson,
      auditMethodeLesson,
    ],
  },
];

export const references: Array<{ key: string; blocks: PathBlock[] }> = [
  {
    key: "linux-journaux",
    blocks: [
      reference("wikiSyslog"),
      reference("rfc5424"),
      reference("ubuntuServerDocs"),
      reference("debianHandbook"),
    ],
  },
  {
    key: "linux-audit-droits",
    blocks: [
      reference("ubuntuFrPermissions"),
      reference("ubuntuFrUsers"),
      reference("ubuntuFrSudo"),
      reference("ubuntuFrCron"),
    ],
  },
];
