import {
  code, example, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const paquetsLesson: NewLesson = {
  key: "linux-paquets",
  title: "Gérer les logiciels : apt, dnf, dépôts et signatures",
  summary: "Apprends comment Linux installe un logiciel, d’où viennent les paquets, pourquoi les signatures comptent, et comment limiter le risque lié aux dépôts tiers.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("repérer le rôle d’un paquet et d’un dépôt, distinguer « apt update », « apt upgrade » et « apt full-upgrade », retrouver à quel paquet appartient un fichier, expliquer la confiance accordée à une clé de signature, et comparer les réflexes Debian ou Ubuntu avec Fedora ou RHEL."),
    prerequisites("avoir déjà ouvert un terminal et savoir lire une commande simple."),
    scenario("Awa administre un petit serveur web chez Baobab Tech et un poste Fedora pour la graphiste. Un collègue veut installer un outil en copiant une commande trouvée sur un forum, puis ajouter un dépôt tiers « parce que c’est plus rapide ». Awa doit expliquer ce que le système va vraiment faire, et à qui on choisit de faire confiance."),
    videoSlot("Comprendre les paquets Linux sans casser son système"),
    text("Sous Linux, un logiciel s’installe le plus souvent sous la forme d’un paquet. Un paquet contient des fichiers, des métadonnées et parfois des dépendances, c’est-à-dire d’autres paquets nécessaires à son fonctionnement. Sur Debian et Ubuntu, « apt » pilote l’installation et « dpkg » tient l’inventaire local. Sur Fedora et RHEL, le duo courant est « dnf » et « rpm ». Le principe reste le même : on prend des paquets depuis un dépôt, on vérifie leur authenticité, puis on les installe avec leurs dépendances."),
    schema([
      "Dépôt signé",
      "   |",
      "   v",
      "Liste des paquets  <- « apt update »",
      "   |",
      "   v",
      "Paquet choisi      <- « apt install »",
      "   |",
      "   +--> dépendances",
      "   |",
      "   v",
      "Base locale        <- « dpkg -l », « rpm -qa »",
    ].join("\n")),
    text("Le point important pour la sécurité est la chaîne de confiance. « apt » vérifie surtout la signature des métadonnées du dépôt, puis l’intégrité des paquets annoncés. « dnf » et « rpm » peuvent aussi vérifier la signature des paquets. Ajouter un dépôt tiers revient donc à lui faire confiance pour te livrer du code avec des droits d’administration. C’est pour cela qu’un simple « curl ... | sudo bash » est une mauvaise habitude : tu laisses un site distant décider quoi exécuter sur ta machine sans contrôle intermédiaire. Quand tu peux, préfère les dépôts officiels, lis la documentation du projet, et garde les clés dans un emplacement prévu, comme « /etc/apt/keyrings/ » ou « /usr/share/keyrings/ »."),
    text("Sur Debian ou Ubuntu, « apt update » ne met rien à jour dans tes logiciels : il télécharge seulement la liste des versions disponibles. « apt upgrade » installe les nouvelles versions sans supprimer de paquet. « apt full-upgrade » peut supprimer des paquets pour résoudre des changements de dépendances. Cette nuance compte : lancer « update » seul donne une impression de sécurité trompeuse. Tu as des informations fraîches, mais pas encore de correctif appliqué. Pense aussi aux formats comme Snap, Flatpak ou AppImage : ils peuvent être pratiques, mais ils déplacent seulement la question de confiance vers une autre source ou un autre mécanisme de mise à jour."),
    text("Démonstration guidée : tu peux refaire cette lecture dans une machine virtuelle Debian ou Ubuntu, et en partie dans WSL si tu as les droits d’administration sur l’instance. Observe d’abord ce qui vient d’un dépôt, puis ce que le gestionnaire sait déjà d’un paquet installé. Regarde aussi d’où provient une version précise : cela sert à vérifier qu’un serveur ne tire pas sans le vouloir ses logiciels d’une source non prévue."),
    code([
      "# Mettre à jour la liste des paquets disponibles",
      "apt update",
      "# exemple de sortie (valeurs fictives)",
      "# Atteint :1 http://deb.debian.org/debian bookworm InRelease",
      "# Atteint :2 http://security.debian.org/debian-security bookworm-security InRelease",
      "# Lecture des listes de paquets... Fait",
      "",
      "# Voir les mises à jour en attente",
      "apt list --upgradable",
      "# exemple de sortie (valeurs fictives)",
      "# Listing... Done",
      "# openssl/stable-security 3.0.11-1+deb12u3 amd64 [upgradable from: 3.0.11-1+deb12u2]",
      "# openssh-client/stable-security 1:9.2p1-2+deb12u5 amd64 [upgradable from: 1:9.2p1-2+deb12u4]",
      "# vim/stable 2:9.0.1378-2 amd64 [upgradable from: 2:9.0.1378-1]",
      "",
      "# Voir d’où vient une version et laquelle est installée",
      "apt policy openssh-client",
      "# exemple de sortie (valeurs fictives)",
      "# openssh-client:",
      "#   Installed: 1:9.2p1-2+deb12u4",
      "#   Candidate: 1:9.2p1-2+deb12u5",
      "#   Version table:",
      "#      1:9.2p1-2+deb12u5 500",
      "#         500 http://security.debian.org/debian-security bookworm-security/main amd64 Packages",
      "",
      "# Identifier le paquet propriétaire d’un fichier",
      "dpkg -S /usr/bin/ssh",
      "# exemple de sortie (valeurs fictives)",
      "# openssh-client: /usr/bin/ssh",
    ].join("\n"), "bash"),
    schema([
      "Commande              Effet principal",
      "apt search motif      cherche un paquet",
      "apt show paquet       décrit un paquet",
      "apt install paquet    installe le paquet demandé",
      "apt remove paquet     retire le logiciel, garde souvent sa config",
      "apt purge paquet      retire aussi la configuration du paquet",
      "apt autoremove        retire des dépendances devenues inutiles",
      "dpkg -l               liste les paquets connus localement",
      "dpkg -L paquet        liste les fichiers fournis par ce paquet",
      "dpkg -S /chemin       retrouve le paquet depuis un fichier",
      "dnf search ou dnf upgrade  équivalents courants côté Fedora ou RHEL",
    ].join("\n")),
    example("Exemple corrigé : si « apt list --upgradable » montre cinq paquets et que deux lignes portent le suffixe « /stable-security », tu ne conclus pas que les trois autres sont sans importance. Tu conclus seulement que deux correctifs viennent explicitement du canal de sécurité, et que les autres peuvent être des corrections de bogues ou des dépendances. La bonne réaction est de lire « apt changelog » ou l’avis du fournisseur, pas de trier à l’aveugle entre « critique » et « optionnel » selon le nom du paquet."),
    mistakes("confondre « apt update » avec l’installation des correctifs ; ajouter un dépôt tiers sans savoir qui le maintient ; supprimer un paquet « inutile » sans regarder ses dépendances ; croire qu’un format portable comme AppImage, Snap ou Flatpak annule tout risque de chaîne d’approvisionnement."),
    safety("installe sur ta propre machine, une machine virtuelle ou un serveur de test autorisé. N’exécute jamais une commande d’installation copiée depuis un site sans lire chaque option. Évite de modifier les dépôts d’un serveur de production sans sauvegarde et sans fenêtre de changement."),
    takeaway("un paquet est un logiciel emballé avec ses métadonnées et ses dépendances. Le gestionnaire de paquets ne protège que si tu gardes une chaîne de confiance claire. « apt update » informe, « apt upgrade » corrige, et un dépôt tiers reçoit une confiance très large."),
    practice("Travaille dans « TP 5 : mises à jour, disques et sauvegardes » : identifie les paquets en attente, repère ceux du canal de sécurité et vérifie d’où vient une version avant de terminer par le quiz de la leçon."),
    reference("ubuntuFrApt"),
    reference("debApt"),
    reference("fedoraDnf"),
  ],
  quiz: {
    title: "Quiz : paquets et dépôts",
    questions: [
      questions.choice("Que fait vraiment « apt update » ?", ["Il installe les nouvelles versions de paquets", "Il rafraîchit la liste des versions disponibles", "Il supprime les dépendances inutiles", "Il vide le cache du système"], 1, "« apt update » télécharge l’index des paquets, puis s’arrête là. Le piège courant est de croire que la machine est corrigée juste après cette étape, alors qu’aucune nouvelle version n’a encore été installée.", "facile"),
      questions.choice("Tu lis la ligne « openssh-client/stable-security 1:9.2p1-2+deb12u5 amd64 [upgradable from: 1:9.2p1-2+deb12u4] ». Quelle conclusion est la plus solide ?", ["Le paquet va être supprimé par la prochaine mise à jour", "La ligne prouve qu’un dépôt tiers a pris la main", "Une version plus récente du paquet est disponible via le canal de sécurité", "Le service SSH écoute forcément sur Internet"], 2, "La ligne indique simplement qu’une version plus récente du paquet est proposée par le dépôt de sécurité. Le faux ami est l’idée de suppression : aucune suppression n’est montrée ici, seulement une version candidate plus récente.", "moyen"),
      questions.multi("Quels choix réduisent le risque lié aux logiciels sous Linux ? (plusieurs réponses)", ["Privilégier les dépôts officiels documentés", "Lire l’origine d’une version avec « apt policy »", "Ajouter un dépôt tiers au hasard si son nom paraît familier", "Vérifier une empreinte ou une signature avant d’installer un téléchargement manuel"], [0, 1, 3], "Privilégier des sources connues, vérifier l’origine d’une version et contrôler un téléchargement renforcent la chaîne de confiance. Le mauvais réflexe tentant est le dépôt tiers pris au hasard : il obtient un pouvoir large sur le système.", "difficile"),
      questions.tf("Ajouter un dépôt tiers revient à lui faire confiance pour fournir du code à ton système avec un niveau de privilège élevé.", true, "Vrai : si tu ajoutes un dépôt et sa clé de signature, le gestionnaire de paquets peut ensuite installer ses paquets avec les droits d’administration. Ce n’est donc jamais un geste neutre ni purement « pratique ».", "moyen"),
    ],
  },
};

const misesAJourLinuxLesson: NewLesson = {
  key: "linux-mises-a-jour",
  title: "Correctifs de sécurité, mises à jour et fin de support",
  summary: "Comprends comment réduire la fenêtre d’exposition d’un serveur Linux, distinguer une information de mise à jour d’un correctif réellement appliqué, et planifier le redémarrage utile.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer ce qu’est un correctif de sécurité, mesurer une fenêtre d’exposition, repérer une version encore supportée, vérifier si un redémarrage est nécessaire, et choisir entre mise à jour manuelle, testée ou automatisée."),
    prerequisites("avoir suivi « Gérer les logiciels : apt, dnf, dépôts et signatures »."),
    scenario("Moussa maintient un petit serveur d’intranet pour l’association Teranga. Les avis de sécurité arrivent vite, mais le service doit aussi rester disponible pendant la journée. Moussa doit décider quand corriger, quoi redémarrer, et comment expliquer qu’un correctif téléchargé mais jamais appliqué ne protège personne."),
    videoSlot("Mettre à jour un serveur Linux sans se rassurer trop tôt"),
    text("Une mise à jour de sécurité contient un correctif pour une vulnérabilité connue. Entre la publication du correctif et son installation effective, ton système reste dans une fenêtre d’exposition. Cette durée dépend de ton organisation : vitesse de veille, validation, sauvegarde, déploiement, puis redémarrage éventuel. Dire « le paquet existe » ne suffit pas. Il faut vérifier que la version corrigée est bien installée et que le service concerné utilise encore ce code corrigé."),
    schema([
      "Publication d’un avis",
      "        |",
      "        v",
      "Lecture de l’impact",
      "        |",
      "        v",
      "Test ou sauvegarde",
      "        |",
      "        v",
      "Installation du correctif",
      "        |",
      "        v",
      "Redémarrage du service ou du noyau",
    ].join("\n")),
    text("Sous Debian ou Ubuntu, les correctifs de sécurité arrivent souvent via un dépôt « -security ». « apt list --upgradable » donne la vue d’ensemble, puis « apt changelog paquet » aide à lire ce qui change. Sur Fedora ou RHEL, le rôle équivalent passe plutôt par « dnf upgrade » et les avis du fournisseur. Dans tous les cas, la notion clé n’est pas la marque de la distribution, mais le support réel de la version utilisée. Une version en fin de support peut continuer à démarrer, tout en cessant de recevoir les correctifs attendus. Les variantes à support long existent pour aider à planifier, mais il faut toujours vérifier la date de fin de support publiée par le projet."),
    text("Le redémarrage compte. Un noyau mis à jour n’est pas en service tant que la machine n’a pas redémarré. De même, une bibliothèque ou un démon peut rester en mémoire avec l’ancienne version tant que son processus n’est pas relancé. Sur Debian ou Ubuntu, le fichier « /var/run/reboot-required » sert de drapeau simple. Des outils comme « needrestart » aident à repérer les services encore lancés avec d’anciens fichiers. Certaines offres proposent des correctifs en direct du noyau, mais elles ne remplacent pas une politique claire de suivi et de redémarrage."),
    text("Démonstration guidée : cette lecture se refait bien dans une machine virtuelle Debian ou Ubuntu, et parfois dans WSL pour les commandes de consultation. Sur un vrai serveur, ajoute toujours une sauvegarde ou un instantané avant un changement important. Lis d’abord les mises à jour disponibles, puis vérifie si un redémarrage est demandé après installation."),
    code([
      "# Voir les paquets à mettre à jour",
      "apt list --upgradable",
      "# exemple de sortie (valeurs fictives)",
      "# Listing... Done",
      "# openssl/stable-security 3.0.11-1+deb12u3 amd64 [upgradable from: 3.0.11-1+deb12u2]",
      "# linux-image-amd64/stable-security 6.1.148-1 amd64 [upgradable from: 6.1.124-1]",
      "",
      "# Lire le détail d’un changement",
      "apt changelog openssl",
      "",
      "# Vérifier si un redémarrage système est attendu",
      "test -f /var/run/reboot-required && echo \"redemarrage requis\"",
      "# exemple de sortie (valeurs fictives)",
      "# redemarrage requis",
    ].join("\n"), "bash"),
    schema([
      "Automatique et prudent : unattended-upgrades, dnf-automatic",
      "À surveiller          : journaux, fenêtre de maintenance, sauvegarde",
      "À ne pas oublier      : relancer le service ou redémarrer si requis",
      "À vérifier            : support de la version et source officielle",
    ].join("\n")),
    example("Exemple corrigé : un avis est publié le 12 mai 2026 à 09 h 00, le correctif est installé le 15 mai 2026 à 13 h 30. La fenêtre d’exposition vaut 76,5 heures, soit 3 jours et 4 h 30. Ce calcul n’indique pas le risque métier à lui seul, mais il montre combien de temps le serveur est resté vulnérable alors qu’un correctif existait déjà."),
    mistakes("lancer « apt update » sans jamais appliquer les correctifs ; oublier qu’un noyau mis à jour demande souvent un redémarrage ; tout déployer en production sans test ni sauvegarde ; rester sur une version hors support parce qu’« elle marche encore »."),
    safety("sur un serveur de production, mets à jour pendant une fenêtre autorisée, avec sauvegarde ou instantané, et garde un moyen de retour arrière. Les tests se font sur ton propre environnement, une machine virtuelle ou un serveur dont tu as la charge et l’autorisation."),
    takeaway("un correctif n’aide qu’après installation réelle, puis relance du service ou redémarrage nécessaire. La fenêtre d’exposition se mesure entre publication et application. Le support officiel de la version utilisée reste une condition de base pour recevoir les correctifs attendus."),
    practice("Dans « TP 5 : mises à jour, disques et sauvegardes », repère les mises à jour en attente, estime lesquelles relèvent de la sécurité et juge si un redémarrage ou une relance de service manque encore, puis termine par le quiz."),
    reference("cmMisesAJour"),
    reference("ubuntuSecurityNotices"),
    reference("debianSecurity"),
  ],
  quiz: {
    title: "Quiz : correctifs et support",
    questions: [
      questions.choice("Qu’appelle-t-on « fenêtre d’exposition » ?", ["Le temps où la salle serveur reste ouverte", "Le délai entre la publication d’un correctif et son application effective", "Le temps nécessaire pour télécharger un paquet", "La durée de vie maximale d’un disque SSD"], 1, "La fenêtre d’exposition mesure le temps pendant lequel une vulnérabilité connue reste présente alors qu’un correctif existe déjà. Le faux ami est le temps de téléchargement : il ne représente qu’une petite partie possible du problème.", "facile"),
      questions.choice("Tu lis « linux-image-amd64/stable-security 6.1.148-1 amd64 [upgradable from: 6.1.124-1] » puis le fichier « /var/run/reboot-required » existe. Quelle action manque encore après l’installation ?", ["Supprimer le paquet précédent à la main", "Redémarrer le système au moment autorisé", "Désactiver le dépôt de sécurité", "Créer un nouvel utilisateur root"], 1, "La présence du drapeau de redémarrage indique qu’un changement système important, souvent le noyau, n’est pas encore totalement pris en compte. Supprimer l’ancien paquet manuellement n’active pas le nouveau noyau en mémoire.", "moyen"),
      questions.multi("Quelles pratiques améliorent une politique de mises à jour sous Linux ? (plusieurs réponses)", ["Vérifier si la version de la distribution est encore supportée", "Sauvegarder ou prendre un instantané avant un changement important", "Appliquer en production sans lire l’impact parce que le canal est officiel", "Contrôler après coup si un redémarrage ou une relance de service reste nécessaire"], [0, 1, 3], "Le support de la version, la sauvegarde et la vérification post-correctif renforcent la sécurité sans aveuglement. Le mauvais réflexe tentant est de tout appliquer sans lecture : une source officielle limite le risque, mais n’annule ni l’impact métier ni les besoins de planification.", "difficile"),
      questions.tf("Un système qui démarre encore peut être hors support et ne plus recevoir les correctifs attendus.", true, "Vrai : le support n’est pas lié au simple fait que le système fonctionne. Une version vieillissante peut sembler stable tout en restant exposée parce que le fournisseur ne publie plus de correctifs pour elle.", "moyen"),
    ],
  },
};

const reseauLesson: NewLesson = {
  key: "linux-reseau",
  title: "Voir et diagnostiquer le réseau : ip, ss, dig, curl",
  summary: "Apprends à lire une interface, une route, un port à l’écoute et une résolution DNS pour diagnostiquer un souci réseau sans sauter directement à la mauvaise conclusion.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("lire une interface avec « ip », expliquer une route par défaut, interpréter une écoute dans « ss », vérifier une résolution DNS, et suivre une méthode de diagnostic simple de l’interface jusqu’au service."),
    prerequisites("connaître le rôle d’une adresse IP, d’un port et d’un service réseau."),
    scenario("Nadia reçoit un appel de Sahel Services : l’application interne n’est plus joignable depuis un poste, alors que le serveur semble allumé. Le collègue dit seulement « le réseau est cassé ». Nadia doit vérifier si le problème vient de l’interface, de la passerelle, du DNS ou d’un service qui n’écoute plus."),
    videoSlot("Lire le réseau Linux sans paniquer devant les ports"),
    text("La commande « ip » remplace plusieurs anciens outils. « ip -br a » donne une vue courte des interfaces, de leur état et de leurs adresses. « ip a » montre plus de détails, comme les adresses IPv4 ou IPv6, leur portée et l’état complet de l’interface. « ip r » affiche la table de routage, c’est-à-dire le chemin choisi pour sortir du réseau local. La ligne commençant par « default via » indique la passerelle par défaut : c’est souvent la box ou le routeur local. Si l’interface est coupée, il est inutile de suspecter tout de suite le DNS ou le serveur distant."),
    schema([
      "Diagnostic par couches",
      "1. interface : « ip -br a »",
      "2. route locale : « ip r »",
      "3. voisin et passerelle : « ip neigh », « ping -c 3 »",
      "4. nom DNS : « dig +short »",
      "5. service : « ss -tulpn », « curl -I »",
    ].join("\n")),
    text("« ss -tulpn » sert à lire les sockets ouvertes. Les lettres de l’option rappellent ce que tu demandes : TCP, UDP, listening, process et numeric. Le tableau affiche notamment « Netid », « State », « Recv-Q », « Send-Q », « Local Address:Port », « Peer Address:Port » et le processus. Un port à l’écoute est une surface d’attaque potentielle : il faut donc savoir à quel processus il appartient et s’il écoute partout ou seulement en local. « 0.0.0.0:22 » signifie que le service écoute sur toutes les interfaces IPv4. « [::]:22 » fait de même en IPv6. En revanche « 127.0.0.1:5432 » n’est joignable qu’en local : c’est un bon réflexe pour une base de données qui n’a pas à accepter des connexions depuis le réseau."),
    text("Le DNS et HTTP se vérifient séparément. « dig +short nom » répond à la question « ce nom résout-il vers une adresse ? ». « curl -I https://... » demande seulement les en-têtes HTTP, ce qui suffit souvent pour voir si le service répond. Si le chemin réseau reste flou, « tracepath » ou « traceroute » aident à voir où le trafic se perd. Les fichiers « /etc/resolv.conf » et « /etc/hosts » complètent l’enquête : le premier décrit souvent les résolveurs DNS, le second peut forcer des correspondances locales. Si tu emploies « nmap », ce doit être seulement sur tes propres machines ou avec autorisation écrite."),
    text("Démonstration guidée : commence par lire l’interface, puis la route, puis les ports à l’écoute. Enfin, interroge un nom DNS et un service web. L’ordre compte : si « ip -br a » montre une interface DOWN, les étapes suivantes t’apprennent moins qu’un simple branchement ou qu’une mauvaise configuration locale."),
    code([
      "# Vue courte des interfaces",
      "ip -br a",
      "# exemple de sortie (valeurs fictives)",
      "# lo               UNKNOWN        127.0.0.1/8 ::1/128",
      "# eth0             UP             192.168.1.20/24 fe80::5054:ff:fe12:3456/64",
      "",
      "# Route par défaut",
      "ip r",
      "# exemple de sortie (valeurs fictives)",
      "# default via 192.168.1.1 dev eth0 proto dhcp metric 100",
      "# 192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.20",
      "",
      "# Ports à l’écoute",
      "ss -tulpn",
      "# exemple de sortie (valeurs fictives)",
      "# Netid State  Recv-Q Send-Q Local Address:Port  Peer Address:Port Process",
      "# tcp   LISTEN 0      128    0.0.0.0:22          0.0.0.0:*         users:((\"sshd\",pid=731,fd=3))",
      "# tcp   LISTEN 0      244    127.0.0.1:5432      0.0.0.0:*         users:((\"postgres\",pid=812,fd=5))",
    ].join("\n"), "bash"),
    schema([
      "Écoute observée        Lecture utile",
      "0.0.0.0:22            service exposé sur toutes les interfaces IPv4",
      "127.0.0.1:5432        service limité à la machine locale",
      "[::]:80               service exposé sur toutes les interfaces IPv6",
      "default via 192.168.1.1  sortie réseau par la passerelle 192.168.1.1",
    ].join("\n")),
    example("Exemple corrigé : dans une sortie « ss », le port 22 sur « 0.0.0.0 » mérite une vérification de pare-feu et de politique SSH. Le port 5432 sur « 127.0.0.1 » est plus rassurant : le serveur PostgreSQL n’écoute qu’en local. Si l’application web sur la même machine doit seule lui parler, cette limitation réduit la surface d’attaque sans casser le service."),
    mistakes("croire qu’un service sur « 0.0.0.0 » est forcément visible depuis Internet, alors qu’un pare-feu peut encore le bloquer ; diagnostiquer le DNS avant d’avoir vérifié l’interface ; confondre un port en écoute locale avec un service publié ; oublier que le résultat de « curl -I » décrit l’application, pas la route réseau complète."),
    safety("scanne uniquement tes propres machines ou celles pour lesquelles tu as une autorisation. Sur un poste de production, contente-toi d’abord de commandes de lecture comme « ip », « ss », « dig » et « curl » avant d’envisager un changement."),
    takeaway("diagnostiquer le réseau Linux commence par l’interface, puis la route, puis la résolution et le service. Chaque port à l’écoute compte comme une surface d’attaque potentielle. Lire « 0.0.0.0 », « [::] » et « 127.0.0.1 » t’aide à décider quoi fermer, limiter ou publier."),
    practice("Dans « TP 4 : réseau, SSH et pare-feu », lis la configuration réseau, la route par défaut et les ports à l’écoute avant de relier chaque service à son exposition réelle, puis termine par le quiz."),
    reference("man7Ip"),
    reference("man7Ss"),
    reference("mdnHttp"),
  ],
  quiz: {
    title: "Quiz : diagnostic réseau Linux",
    questions: [
      questions.choice("Que signifie la ligne « default via 192.168.1.1 dev eth0 » dans « ip r » ?", ["Le service DNS écoute sur le port 192.168.1.1", "La passerelle par défaut est 192.168.1.1 via l’interface eth0", "L’interface eth0 n’a pas d’adresse IP", "Le pare-feu bloque toutes les sorties"], 1, "La route par défaut désigne la passerelle utilisée pour joindre les réseaux hors du sous-réseau local. Le piège classique est de confondre cette ligne avec un réglage DNS ou de pare-feu, alors qu’elle décrit le routage.", "facile"),
      questions.choice("Tu lis « tcp LISTEN 0 244 127.0.0.1:5432 0.0.0.0:* ». Quelle conclusion est correcte ?", ["La base de données est accessible depuis n’importe quelle machine", "Le service n’écoute qu’en local sur la machine", "Le serveur écoute uniquement en IPv6", "Le processus ne peut pas démarrer"], 1, "L’adresse locale 127.0.0.1 limite l’écoute à la boucle locale. Le faux bon choix est « accessible partout » : cette conclusion vaudrait plutôt pour 0.0.0.0 ou pour une adresse réseau réelle.", "moyen"),
      questions.multi("Quelles commandes correspondent le mieux à ces questions ? (plusieurs réponses)", ["« ip -br a » pour vérifier l’état d’une interface", "« dig +short intranet.example » pour tester la résolution d’un nom", "« ss -tulpn » pour lister les services à l’écoute", "« curl -I https://intranet.example » pour afficher l’adresse MAC de la passerelle"], [0, 1, 2], "Les trois premières commandes couvrent interface, DNS et sockets. « curl -I » interroge un service HTTP et n’affiche pas l’adresse MAC de la passerelle, qui relève plutôt de « ip neigh » ou d’outils voisins.", "difficile"),
      questions.tf("Un port à l’écoute sur « 0.0.0.0 » mérite une vérification de pare-feu ou de besoin métier, car il augmente potentiellement la surface d’attaque.", true, "Vrai : écouter sur toutes les interfaces n’est pas toujours un problème, mais cela mérite une décision explicite. Le bon réflexe est de vérifier l’usage, le pare-feu et la possibilité de restreindre l’écoute si le service n’a pas besoin d’être exposé partout.", "moyen"),
    ],
  },
};

const sshLesson: NewLesson = {
  key: "linux-ssh",
  title: "SSH : connexion, clés et durcissement de sshd_config",
  summary: "Apprends à te connecter proprement en SSH, à utiliser des clés plutôt qu’un mot de passe, et à lire « sshd_config » sans te couper toi-même l’accès.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("créer une paire de clés SSH, vérifier une empreinte de serveur, expliquer le rôle de « authorized_keys » et « known_hosts », tester une configuration « sshd_config », et déduire la valeur effective d’un réglage avec « Include » ou « Match »."),
    prerequisites("avoir vu « Voir et diagnostiquer le réseau : ip, ss, dig, curl » et savoir ce qu’est un port réseau."),
    scenario("Koffi doit administrer un serveur Ubuntu chez Atlas sans rester devant l’écran physique. La connexion fonctionne encore au mot de passe, mais le journal montre des tentatives d’authentification répétées. Koffi veut passer aux clés, limiter les comptes autorisés et durcir « sshd_config » sans se verrouiller dehors."),
    videoSlot("SSH sans se couper l’accès : clés, empreintes et configuration"),
    text("SSH fournit un accès distant chiffré et authentifié. Le client vérifie l’identité du serveur, puis l’utilisateur s’authentifie par mot de passe ou, mieux, par paire de clés. SSH sert aussi à transférer des fichiers avec « scp », « sftp » ou « rsync -e ssh », et les tunnels permettent de faire passer un autre flux dans la connexion sans exposer un service de plus. Côté client, la clé privée reste dans « ~/.ssh/ » et ne se partage jamais. La clé publique, elle, peut être copiée sur le serveur dans « authorized_keys ». Quand tout est en place, la connexion par clé réduit fortement le risque lié aux mots de passe devinés ou réutilisés."),
    schema([
      "Client                        Serveur",
      "~/.ssh/id_ed25519            /home/awa/.ssh/authorized_keys",
      "clé privée : 600             fichier : 600",
      "clé publique : partageable   dossier .ssh : 700",
      "known_hosts : mémoire des    sshd_config : règles du service",
      "empreintes de serveur",
    ].join("\n")),
    text("La première connexion demande un effort de vérification : l’empreinte du serveur doit correspondre à celle annoncée par l’administrateur ou vue depuis une console sûre. Si l’empreinte change sans raison connue, tu n’acceptes pas machinalement : cela peut signaler une réinstallation, mais aussi une interception. Le fichier « known_hosts » sert justement à mémoriser les serveurs déjà vus."),
    text("Le durcissement de « sshd_config » commence souvent par « PermitRootLogin no », « PasswordAuthentication no » une fois les clés testées, puis « AllowUsers » ou « AllowGroups » pour limiter qui peut entrer. Le détail à retenir est subtil : pour un mot-clé donné, la première valeur rencontrée compte. Comme Debian et Ubuntu placent souvent « Include /etc/ssh/sshd_config.d/*.conf » en tête, un fichier du dossier « .d » peut l’emporter sur une ligne plus bas dans le fichier principal."),
    text("Les blocs « Match » ajoutent une autre couche : ils s’appliquent seulement aux connexions concernées, par exemple un utilisateur ou une adresse, puis restent actifs jusqu’au prochain bloc « Match » ou jusqu’à la fin du fichier. Le fichier « ~/.ssh/config » côté client sert, lui, à mémoriser un nom d’hôte, un port ou une clé à utiliser. Tu testes toujours avec « sshd -t » avant de recharger. « sshd -T » affiche ensuite la configuration effective globale, et l’option « -C » permet de simuler un cas précis pour relire l’effet d’un bloc « Match ». Sur Debian et Ubuntu, le service s’appelle le plus souvent « ssh » ; sur RHEL et Fedora, c’est plutôt « sshd ». Garde toujours une session déjà ouverte pendant la modification : cette habitude évite de transformer un durcissement bien intentionné en coupure de service."),
    text("Démonstration guidée : tu peux créer une clé dans Git Bash, WSL, Termux ou une machine virtuelle. En revanche, modifier « sshd_config » demande un vrai serveur Linux ou au moins une machine virtuelle où tu es administrateur. Crée d’abord la clé, lis ensuite une empreinte publique, puis vérifie la syntaxe d’un extrait de configuration avant d’aller plus loin."),
    code([
      "# Créer une paire de clés côté client",
      "ssh-keygen -t ed25519",
      "",
      "# Lire l’empreinte d’une clé publique",
      "ssh-keygen -lf ~/.ssh/id_ed25519.pub",
      "",
      "# Copier la clé publique vers un serveur",
      "ssh-copy-id awa@192.168.1.20",
      "",
      "# Tester la syntaxe de la configuration serveur",
      "sshd -t",
      "",
      "# Voir la configuration effective hors bloc Match",
      "sshd -T | grep -E 'permitrootlogin|passwordauthentication|maxauthtries'",
      "",
      "# Simuler un cas precis pour un bloc Match",
      "sshd -T -C user=awa,host=srv-demo,addr=192.168.1.20 | grep -E 'passwordauthentication|maxauthtries'",
    ].join("\n"), "bash"),
    code([
      "# Extrait de configuration et de journal (valeurs fictives)",
      "Include /etc/ssh/sshd_config.d/*.conf",
      "PermitRootLogin yes",
      "PasswordAuthentication yes",
      "",
      "Match User awa",
      "    PasswordAuthentication no",
      "",
      "# exemple de journal",
      "# Failed password for invalid user admin from 192.168.1.60 port 51234 ssh2",
      "# Accepted publickey for awa from 192.168.1.20 port 44218 ssh2: ED25519 SHA256:57qiy2BUfE1i...",
    ].join("\n"), "text"),
    example("Exemple corrigé : si « /etc/ssh/sshd_config.d/10-hardening.conf » contient déjà « PermitRootLogin no » et que le fichier principal plus bas dit encore « PermitRootLogin yes », la valeur effective reste « no » parce que la première occurrence compte. En revanche, un bloc « Match User awa » peut ensuite changer seulement l’authentification par mot de passe pour Awa, sans modifier le cas des autres utilisateurs."),
    mistakes("désactiver les mots de passe avant d’avoir testé la clé ; accepter une nouvelle empreinte de serveur sans la vérifier ; laisser des droits trop ouverts sur « ~/.ssh » ou « authorized_keys » ; croire que changer le port SSH suffit à sécuriser le service."),
    safety("travaille sur un serveur à toi ou sous autorisation écrite. Garde toujours une session déjà ouverte pendant la modification de « sshd_config ». N’active pas une restriction que tu ne peux pas tester, et ne partage jamais une clé privée."),
    takeaway("SSH protège la connexion, mais pas une configuration imprudente. Les clés limitent le risque lié aux mots de passe, « known_hosts » protège contre les changements d’identité non expliqués, et « sshd -t » doit précéder tout rechargement de configuration."),
    practice("Dans « TP 4 : réseau, SSH et pare-feu », interprète une configuration avec « Include » et « Match », puis lis le journal d’authentification avant de finir par le quiz. Tu peux aussi rapprocher ce sujet de « Incident : un serveur web Linux compromis » pour l’analyse des tentatives SSH."),
    reference("ubuntuFrSsh"),
    reference("debSshdConfig"),
    reference("openssh"),
  ],
  quiz: {
    title: "Quiz : SSH et durcissement",
    questions: [
      questions.choice("Quel fichier côté serveur reçoit habituellement la clé publique d’un utilisateur SSH ?", ["« /etc/ssh/known_hosts »", "« ~/.ssh/authorized_keys »", "« ~/.ssh/id_ed25519 »", "« /etc/passwd »"], 1, "« authorized_keys » contient les clés publiques autorisées pour l’utilisateur du serveur. Le piège fréquent est de confondre ce fichier avec « known_hosts », qui mémorise les serveurs déjà vus côté client.", "facile"),
      questions.choice("Tu lis cette configuration : « Include /etc/ssh/sshd_config.d/*.conf », puis plus bas « PermitRootLogin yes ». Si le fichier « 10-hardening.conf » inclus contient déjà « PermitRootLogin no », quelle valeur gagne hors bloc « Match » ?", ["yes, car le fichier principal a toujours priorité", "no, car la première valeur rencontrée pour ce mot-clé compte", "les deux se neutralisent", "la valeur dépend uniquement du port SSH"], 1, "Avec OpenSSH, la première valeur rencontrée pour un mot-clé compte dans ce contexte. Le réflexe trompeur est de croire que la ligne la plus basse gagne forcément, comme dans d’autres formats de configuration.", "moyen"),
      questions.multi("Quels réflexes réduisent le risque de te couper l’accès ou d’ouvrir trop grand SSH ? (plusieurs réponses)", ["Garder une session ouverte pendant les tests", "Tester la syntaxe avec « sshd -t » avant rechargement", "Désactiver immédiatement l’authentification par mot de passe avant de vérifier la clé", "Limiter les comptes autorisés avec « AllowUsers » ou « AllowGroups »"], [0, 1, 3], "Garder une session active, valider la syntaxe et limiter les comptes autorisés sont de bonnes pratiques. Le faux bon choix est de couper tout de suite les mots de passe sans avoir validé la clé : c’est un moyen classique de se bloquer soi-même.", "difficile"),
      questions.tf("Une empreinte de serveur SSH qui change sans explication mérite une vérification avant de poursuivre la connexion.", true, "Vrai : le changement peut venir d’une réinstallation légitime, mais il peut aussi signaler une interception ou une erreur de cible. Continuer sans contrôle vide « known_hosts » de son intérêt défensif.", "moyen"),
    ],
  },
};

const pareFeuLesson: NewLesson = {
  key: "linux-pare-feu",
  title: "Pare-feu sous Linux : ufw et nftables",
  summary: "Apprends à raisonner avec une politique par défaut, à lire des règles « ufw » ou « nftables », et à éviter de couper l’accès SSH en voulant bien faire.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer le rôle d’un pare-feu local, choisir une politique par défaut, lire l’ordre des règles « ufw », interpréter une règle « nftables », et décider si un paquet donné sera accepté ou bloqué."),
    prerequisites("avoir suivi « Voir et diagnostiquer le réseau : ip, ss, dig, curl » et « SSH : connexion, clés et durcissement de sshd_config »."),
    scenario("Fatou doit ouvrir seulement ce qui est nécessaire sur un petit serveur Ubuntu chez Cabinet Moussa. Le service web doit être public, SSH seulement depuis le réseau local, et la base de données ne doit pas être exposée du tout. Elle veut appliquer un refus par défaut sans perdre sa session distante."),
    videoSlot("Pare-feu Linux : ouvrir juste ce qu’il faut"),
    text("Le pare-feu Linux s’appuie sur le filtrage du noyau, souvent appelé netfilter. L’idée défensive simple est de refuser par défaut ce qui entre, d’autoriser ce qui sort, puis d’ajouter des exceptions précises. Ce n’est pas une solution magique : un pare-feu ne corrige ni un logiciel vulnérable ni une authentification faible. En revanche, il réduit la surface d’attaque visible depuis le réseau."),
    schema([
      "Politique sobre",
      "Entrée   : deny par défaut",
      "Sortie   : allow par défaut",
      "Boucle locale : allow",
      "Connexions établies : allow",
      "Exceptions utiles : SSH, HTTP, HTTPS, selon le besoin réel",
    ].join("\n")),
    text("« ufw » simplifie la gestion sur Debian et Ubuntu. Tu peux définir les politiques par défaut, autoriser un port, restreindre une source, limiter les tentatives SSH et relire les règles numérotées. L’ordre compte : la première règle qui correspond décide. C’est pour cela qu’une exception très large placée trop haut peut rendre les lignes suivantes inutiles. Avant d’activer, tu autorises SSH ou tu prépares un accès console, sinon tu peux te bloquer dehors. Les journaux apparaissent souvent dans « /var/log/ufw.log » avec des lignes marquées « [UFW BLOCK] »."),
    text("« nftables » expose plus directement la logique du filtrage. Tu y lis des tables, des chaînes, une politique et des règles comme « ct state established,related accept » pour laisser passer les réponses à des connexions déjà établies. Une chaîne « input » avec « policy drop » annonce une philosophie claire : tout est rejeté sauf ce qui est explicitement accepté. La commande de lecture la plus directe est « nft list ruleset »."),
    text("Démonstration guidée : sur une machine virtuelle Ubuntu où tu es administrateur, commence par lire l’état du pare-feu, puis imagine le chemin d’un paquet SSH venant du réseau local. Vérifie enfin quelle règle le laisse passer. Sur un vrai serveur, garde une seconde session ou une console hors bande avant toute activation."),
    code([
      "# Définir une politique simple avant activation",
      "ufw default deny incoming",
      "ufw default allow outgoing",
      "ufw allow from 192.168.1.0/24 to any port 22 proto tcp",
      "ufw allow 80/tcp",
      "ufw allow 443/tcp",
      "ufw limit ssh",
      "ufw enable",
      "",
      "# Lire l’état et les règles numérotées",
      "ufw status verbose",
      "# exemple de sortie (valeurs fictives)",
      "# Status: active",
      "# Logging: on (low)",
      "# Default: deny (incoming), allow (outgoing), disabled (routed)",
      "# New profiles: skip",
      "",
      "ufw status numbered",
      "# exemple de sortie (valeurs fictives)",
      "# [ 1] 22/tcp                     ALLOW IN    192.168.1.0/24",
      "# [ 2] 80/tcp                     ALLOW IN    Anywhere",
      "# [ 3] 443/tcp                    ALLOW IN    Anywhere",
      "# [ 4] 22/tcp                     LIMIT IN    Anywhere",
      "",
      "# Supprimer une règle par son numéro",
      "ufw delete 4",
      "",
      "# Journal typique",
      "# [UFW BLOCK] IN=eth0 SRC=192.168.1.60 DST=192.168.1.20 PROTO=TCP SPT=52314 DPT=22",
    ].join("\n"), "bash"),
    code([
      "# Lire puis interpréter les règles nftables",
      "nft list ruleset",
      "# exemple de sortie (valeurs fictives)",
      "table inet filter {",
      "  chain input {",
      "    type filter hook input priority 0; policy drop;",
      "    ct state established,related accept",
      "    iif \"lo\" accept",
      "    tcp dport 22 ip saddr 192.168.1.0/24 accept",
      "    tcp dport { 80, 443 } accept",
      "  }",
      "}",
    ].join("\n"), "text"),
    example("Exemple corrigé : avec les règles « ufw » ci-dessus, un paquet SSH venant de 192.168.1.50 est accepté par la règle 1 avant même que la règle 4 ne soit examinée. Un paquet SSH venant de 10.1.5.9 ne correspond pas à la règle 1. Il peut alors être autorisé par la règle « limit ssh » si les tentatives restent raisonnables, puis bloqué si elles deviennent trop fréquentes. La lecture correcte demande donc de suivre l’ordre et de comprendre que « limit » ne veut pas dire « deny immédiat »."),
    mistakes("activer un refus par défaut sans avoir autorisé SSH ni préparé une console ; croire qu’ouvrir le port d’un service suffit à le rendre sûr ; oublier que l’ordre des règles décide ; laisser une base de données écouter et passer au pare-feu alors qu’elle devrait rester locale."),
    safety("teste sur ta propre machine, une machine virtuelle ou un serveur que tu administres. N’active jamais un pare-feu à distance sans second accès de secours. Garde aussi en tête que les règles réseau complètent le durcissement, elles ne le remplacent pas."),
    takeaway("un pare-feu local met en œuvre le principe du refus par défaut. « ufw » simplifie les cas courants, « nftables » montre la logique plus bas niveau, et l’ordre des règles décide du résultat. Autorise seulement ce qui sert vraiment."),
    practice("Dans « TP 4 : réseau, SSH et pare-feu », lis les règles, déduis si un paquet est accepté ou bloqué, puis vérifie si la politique correspond vraiment au besoin avant de répondre au quiz."),
    reference("anssiFiltrage"),
    reference("ubuntuFrUfw"),
    reference("debNft"),
  ],
  quiz: {
    title: "Quiz : pare-feu Linux",
    questions: [
      questions.choice("Quelle politique de départ est la plus cohérente pour un serveur classique ?", ["Allow incoming et deny outgoing par défaut", "Deny incoming et allow outgoing par défaut", "Allow incoming et allow outgoing par défaut", "Deny incoming et deny outgoing sans exception"], 1, "Refuser l’entrée par défaut tout en laissant sortir le trafic utile est le point de départ le plus courant. Autoriser tout en entrée revient à exposer des services sans décision explicite, ce qui va contre le moindre privilège réseau.", "facile"),
      questions.choice("Avec « ufw status numbered », pourquoi la position d’une règle est-elle importante ?", ["Parce que la première règle qui correspond décide du sort du paquet", "Parce que seules les règles paires sont appliquées", "Parce qu’ufw lit toujours les règles de bas en haut", "Parce qu’une règle mal placée change le mot de passe root"], 0, "Le moteur suit l’ordre des règles et s’arrête sur la première correspondance utile. Le piège courant est de lire la liste comme un simple inventaire, alors qu’une exception très large placée tôt peut annuler l’effet attendu des lignes suivantes.", "moyen"),
      questions.multi("Quels réflexes évitent les erreurs classiques lors de l’activation d’un pare-feu ? (plusieurs réponses)", ["Autoriser SSH avant d’activer si l’on administre à distance", "Prévoir une console ou une seconde session", "Ouvrir la base de données sur toutes les interfaces « pour être tranquille »", "Relire l’état avec « ufw status verbose » ou l’équivalent"], [0, 1, 3], "Autoriser SSH, garder un accès de secours et relire l’état sont des réflexes simples et efficaces. Le faux confort est d’ouvrir la base partout : cela augmente la surface d’attaque au lieu de sécuriser le service.", "difficile"),
      questions.tf("Une règle « ct state established,related accept » dans « nftables » sert à laisser passer les réponses aux connexions déjà ouvertes.", true, "Vrai : cette règle évite d’avoir à écrire une permission séparée pour chaque flux de réponse. Elle reconnaît le contexte de la connexion, ce qui simplifie la politique tout en restant plus strict qu’un grand « allow all ».", "moyen"),
    ],
  },
};

const disquesLesson: NewLesson = {
  key: "linux-disques",
  title: "Disques, partitions et systèmes de fichiers",
  summary: "Apprends à lire « lsblk », « df » et « /etc/fstab », à repérer un disque presque plein ou à court d’inodes, et à monter un système de fichiers sans pari risqué.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer disque, partition et système de fichiers, lire « lsblk -f » et « df -h », expliquer les 6 champs de « /etc/fstab », calculer un pourcentage d’occupation, et repérer des options de montage utiles au durcissement."),
    prerequisites("savoir se repérer dans l’arborescence Linux et lire un bloc de code simple."),
    scenario("Amina reçoit une alerte : le serveur de fichiers de la coopérative Harmattan écrit mal ses journaux et l’application refuse de nouveaux documents. Le disque n’est pas « cassé », mais quelque chose manque. Amina doit lire l’état des volumes, comprendre « fstab » et décider si le problème vient de l’espace, des inodes ou d’un montage mal prévu."),
    videoSlot("Disques Linux : lire avant d’écrire"),
    text("Sous Linux, un disque est un périphérique bloc comme « /dev/sda », « /dev/vda » ou « /dev/nvme0n1 ». Il peut contenir des partitions, puis chaque partition porte souvent un système de fichiers comme ext4, xfs ou btrfs. « lsblk -f » montre cette hiérarchie et les points de montage. « df -h » répond à une autre question : combien d’espace reste-t-il sur les systèmes de fichiers montés ? Tu évites ainsi de confondre un disque présent mais non monté avec un volume réellement utilisé par le système."),
    schema([
      "Disque            -> /dev/vda",
      "Partition système -> /dev/vda1  -> /",
      "Partition données -> /dev/vda2  -> /srv/atelier",
      "Système de fichiers : ext4, xfs, btrfs",
      "Point de montage    : endroit de l’arborescence où le volume apparaît",
    ].join("\n")),
    text("« /etc/fstab » décrit les montages persistants. Les six champs, dans l’ordre, sont le périphérique, le point de montage, le type, les options, puis « dump » et « pass ». On préfère souvent « UUID=... » au nom brut du périphérique pour éviter les surprises de renommage au démarrage. Après une modification, « mount -a » permet de tester le fichier sans redémarrer. Si tu te trompes dans « fstab », tu peux retarder ou bloquer le démarrage du système."),
    text("Les commandes de lecture se complètent. « findmnt » montre où un volume est monté. « blkid » aide à retrouver UUID et type. « du -sh * » répond à une autre question que « df » : quels dossiers consomment vraiment l’espace dans un endroit donné ? Pour un montage ponctuel, « mount » attache un système de fichiers à l’arborescence et « umount » le détache proprement. Dans des environnements plus avancés, LVM ajoute une couche logique souple au-dessus des partitions."),
    text("Les options de montage servent aussi au durcissement. « nodev » empêche l’usage de fichiers spéciaux de périphérique sur le point de montage. « nosuid » ignore les bits SUID et SGID. « noexec » empêche l’exécution directe de binaires. Ces options sont souvent utiles pour « /tmp », « /var/tmp » ou des supports amovibles, à condition de vérifier qu’elles ne cassent pas un usage légitime. Pense aussi à la rotation des journaux : un « logrotate » mal réglé peut te laisser croire qu’un disque grossit mystérieusement alors que ce sont juste les journaux qui débordent."),
    text("L’espace n’est pas le seul piège : un système de fichiers peut manquer d’inodes avant de manquer d’octets. « df -i » répond à cette question. Un volume qui héberge beaucoup de petits fichiers, journaux ou caches peut donc tomber en panne alors qu’il reste encore plusieurs gigaoctets libres. C’est un problème de disponibilité, pas seulement d’administration « propre »."),
    text("Démonstration guidée : lis d’abord les volumes avec « lsblk -f », puis vérifie l’occupation avec « df -h » et « df -i ». Enfin, ouvre « /etc/fstab » pour voir comment le système retrouvera ses montages au prochain démarrage. Cette lecture se pratique bien dans une machine virtuelle ou un serveur de test. En revanche, les commandes destructrices comme « mkfs » ou « dd » ne se collent jamais sur un vrai disque sans procédure claire."),
    code([
      "# Lire les volumes et leurs points de montage",
      "lsblk -f",
      "# exemple de sortie (valeurs fictives)",
      "# NAME   FSTYPE FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINTS",
      "# vda",
      "# ├─vda1 ext4   1.0         11111111-2222-3333-4444-555555555555   7.6G    81% /",
      "# └─vda2 ext4   1.0         66666666-7777-8888-9999-aaaaaaaaaaaa  15.2G    24% /srv/atelier",
      "",
      "# Vérifier l’espace et les inodes",
      "df -h",
      "# exemple de sortie (valeurs fictives)",
      "# Filesystem      Size  Used Avail Use% Mounted on",
      "# /dev/vda1        80G   62G   18G  78% /",
      "# /dev/vda2        20G  4.8G   15G  24% /srv/atelier",
      "",
      "df -i",
      "# exemple de sortie (valeurs fictives)",
      "# Filesystem       Inodes   IUsed   IFree IUse% Mounted on",
      "# /dev/vda1      2000000 1900000 100000   95% /",
    ].join("\n"), "bash"),
    code([
      "# Extrait /etc/fstab (valeurs fictives)",
      "UUID=11111111-2222-3333-4444-555555555555 /           ext4 defaults                         0 1",
      "UUID=66666666-7777-8888-9999-aaaaaaaaaaaa /srv/atelier ext4 defaults,nosuid,nodev          0 2",
      "UUID=bbbbbbbb-cccc-dddd-eeee-ffffffffffff /tmp        ext4 defaults,nosuid,nodev,noexec    0 2",
      "",
      "# Tester sans redémarrer",
      "mount -a",
    ].join("\n"), "text"),
    example("Exemple corrigé : la racine « / » de 80 Gio contient 62 Gio utilisés, soit 77,5 %, donc environ 78 %. Cela n’est pas encore une panne, mais ce n’est plus confortable si les journaux grossissent vite. Le vrai signal d’alerte ici est aussi « df -i » : 1 900 000 inodes utilisés sur 2 000 000, soit 95 %. Même avec 18 Gio libres, le volume peut refuser de nouveaux fichiers. Deux problèmes sautent donc aux yeux : la marge d’espace se réduit, et la marge d’inodes est déjà critique."),
    mistakes("se tromper de périphérique et écrire sur le mauvais disque ; croire que l’espace libre suffit toujours alors que les inodes peuvent manquer ; modifier « /etc/fstab » sans tester « mount -a » ; monter un volume de données sans options adaptées alors qu’il n’a pas besoin d’exécuter quoi que ce soit."),
    safety("n’exécute pas « mkfs », « dd » ni une commande de formatage sur un vrai disque pour « essayer ». Les manipulations de lecture se font sur ta propre machine, une machine virtuelle ou un serveur que tu administres. Toute écriture sur un disque doit suivre une procédure validée et sauvegardée."),
    takeaway("un disque, une partition et un système de fichiers ne sont pas la même chose. « lsblk » décrit la structure, « df » décrit l’usage, et « /etc/fstab » décrit le prochain démarrage. L’espace libre et les inodes doivent être surveillés ensemble."),
    practice("Dans « TP 5 : mises à jour, disques et sauvegardes », lis « df », « lsblk » et « fstab », puis repère ce qui menace la disponibilité ou le durcissement avant de finir par le quiz."),
    reference("man7Lsblk"),
    reference("man7Fstab"),
    reference("archFstab"),
  ],
  quiz: {
    title: "Quiz : disques et montages",
    questions: [
      questions.choice("Pourquoi préfère-t-on souvent « UUID=... » à « /dev/sda1 » dans « /etc/fstab » ?", ["Parce que l’UUID accélère le disque", "Parce que le nom brut du périphérique peut changer selon l’ordre détecté au démarrage", "Parce que « /dev/sda1 » interdit l’usage de ext4", "Parce que l’UUID chiffre automatiquement les données"], 1, "L’UUID reste stable même si l’ordre de détection des disques change. Le faux ami est l’idée de performance : l’intérêt ici est la fiabilité du repérage au montage, pas la vitesse.", "facile"),
      questions.choice("Tu lis « /dev/vda1 80G 62G 18G 78% / » puis « /dev/vda1 2000000 1900000 100000 95% / » dans « df -i ». Quel risque est le plus immédiat ?", ["Le système manque d’inodes avant même d’avoir épuisé l’espace en octets", "Le système a déjà redémarré en mode secours", "Le disque n’est pas monté", "Le système de fichiers a forcément été chiffré"], 0, "Les 95 % d’inodes utilisés signalent qu’il reste peu de place pour créer de nouveaux fichiers, même si 18 Gio sont encore libres. Le piège est de ne regarder que les gigaoctets et d’ignorer le nombre d’entrées disponibles.", "moyen"),
      questions.multi("Quelles options de montage servent souvent au durcissement selon le contexte ? (plusieurs réponses)", ["nodev", "nosuid", "noexec", "rw"], [0, 1, 2], "« nodev », « nosuid » et « noexec » limitent des usages risqués sur certains points de montage. « rw » ne durcit pas à lui seul : il indique seulement un montage en lecture et écriture, souvent nécessaire pour fonctionner.", "difficile"),
      questions.tf("Après avoir modifié « /etc/fstab », tester avec « mount -a » permet de détecter des erreurs avant un redémarrage.", true, "Vrai : cette commande tente de monter ce que décrit le fichier et révèle rapidement de nombreuses erreurs de syntaxe ou d’option. Elle ne remplace pas une relecture attentive, mais elle évite bien des surprises au prochain boot.", "moyen"),
    ],
  },
};

const sauvegardesLesson: NewLesson = {
  key: "linux-sauvegardes",
  title: "Sauvegarder sous Linux : tar, rsync, restic",
  summary: "Apprends à distinguer archive, synchronisation et sauvegarde versionnée, à relire une politique de rétention, et à tester une restauration au lieu de faire confiance à un simple journal « OK ».",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("différencier « tar », « rsync » et « restic », expliquer la règle 3-2-1 appliquée à un serveur, vérifier l’effet d’une barre finale dans « rsync », calculer une rétention, et décrire une restauration de test crédible."),
    prerequisites("avoir suivi « Disques, partitions et systèmes de fichiers » et connaître la différence entre un dossier source et un point de destination."),
    scenario("Seydou gère les documents et scripts d’un petit serveur pour l’association Teranga. Les sauvegardes semblent tourner chaque nuit, mais personne n’a jamais restauré un fichier pour vérifier. Seydou doit comprendre ce que fait chaque outil, lire la politique de rétention et éviter qu’une erreur de synchronisation efface aussi la copie de secours."),
    videoSlot("Sauvegarder sous Linux sans confondre copie et vraie restauration"),
    text("Sous Linux, plusieurs outils de sauvegarde répondent à des besoins différents. « tar » crée une archive, pratique pour regrouper et transporter un ensemble de fichiers. « rsync » synchronise efficacement un contenu entre une source et une destination, localement ou via SSH. « restic » ajoute un dépôt chiffré, des instantanés et de la déduplication, donc une vraie histoire des sauvegardes. Aucun de ces outils n’est « meilleur » en soi : tu choisis selon la fréquence, la taille, la rétention et le besoin de restauration."),
    text("Sur un serveur, tu ne sauvegardes pas seulement les documents : pense aussi aux fichiers de configuration, à la liste des paquets installés, et aux exports de bases de données. La règle 3-2-1 reste utile : au moins trois copies, sur deux supports différents, dont une hors site. Une synchronisation locale seule n’y suffit pas. La planification se fait souvent via cron ou un minuteur systemd, mais le plus important reste de vérifier qu’une restauration complète ou partielle est réaliste."),
    schema([
      "Outil      Force principale                 Limite à garder en tête",
      "tar        archive simple et portable      peu de versionnement natif",
      "rsync      copie efficace et différentielle une mauvaise option peut refléter une erreur",
      "restic     instantanés chiffrés, déduplication exige une gestion sérieuse du mot de passe",
    ].join("\n")),
    text("« rsync » a un piège célèbre : la barre finale. « rsync -a src/ dest/ » copie le contenu de « src » dans « dest ». Sans barre finale, tu copies le dossier « src » lui-même. L’option « --delete » peut être utile pour garder un miroir fidèle, mais elle devient dangereuse si la source est incomplète ou mal ciblée. On la teste donc d’abord avec « --dry-run -v ». Si ton environnement d’exercice n’a pas « rsync » ou « restic », retiens au moins la logique et entraîne-toi ensuite dans WSL, une machine virtuelle Linux ou le laboratoire du parcours."),
    text("« restic » travaille autrement : chaque sauvegarde devient un instantané. Tu peux lancer « restic backup », lister avec « restic snapshots », restaurer le dernier avec « restic restore latest --target ... », oublier ceux qui dépassent la politique, puis lancer « restic check ». Le mot de passe du dépôt protège les données, mais sa perte rend la sauvegarde inutilisable. Une bonne hygiène comprend aussi le droit 600 sur le fichier qui contient ce secret, si tu automatises l’accès au dépôt."),
    text("Démonstration guidée : sur une machine de test, crée réellement une archive « tar », liste-la, extrais-la et compare le contenu restauré. Pour « rsync » et « restic », lis les commandes types puis vérifie ensuite leur comportement sur un Linux de test. Le réflexe défensif central reste le même : vérifier la restauration, pas seulement la copie."),
    code([
      "# Créer puis lister une archive",
      "tar -czf sauvegarde-demo.tar.gz dossier-demo",
      "tar -tzf sauvegarde-demo.tar.gz",
      "# exemple de sortie (valeurs fictives)",
      "# dossier-demo/",
      "# dossier-demo/docs/",
      "# dossier-demo/docs/rapport.txt",
      "# dossier-demo/logs/",
      "# dossier-demo/logs/app.log",
      "",
      "# Extraire vers un dossier de test",
      "mkdir -p restauration-demo",
      "tar -xzf sauvegarde-demo.tar.gz -C restauration-demo",
      "",
      "# Vérifier l’archive avec une empreinte",
      "sha256sum sauvegarde-demo.tar.gz > SHA256SUMS",
      "sha256sum -c SHA256SUMS",
      "# exemple de sortie (valeurs fictives)",
      "# sauvegarde-demo.tar.gz: OK",
    ].join("\n"), "bash"),
    code([
      "# Synchroniser sans modifier la destination au premier essai",
      "rsync -a --dry-run -v /srv/atelier/ /backup/atelier/",
      "# exemple de sortie (valeurs fictives)",
      "# sending incremental file list",
      "# docs/rapport.txt",
      "# logs/app.log",
      "# sent 184 bytes  received 24 bytes  416.00 bytes/sec",
      "# total size is 2048  speedup is 9.85 (DRY RUN)",
      "",
      "# Créer, relire, restaurer et contrôler un dépôt restic",
      "restic backup /srv/atelier",
      "restic snapshots",
      "# exemple de sortie (valeurs fictives)",
      "# ID        Time                 Host      Tags        Paths",
      "# 7ab31c42  2026-10-02 20:00:01  srv-demo              /srv/atelier",
      "# c91d8f10  2026-10-01 20:00:01  srv-demo              /srv/atelier",
      "",
      "restic restore latest --target /tmp/restore",
      "restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prune",
      "restic check",
    ].join("\n"), "text"),
    example("Exemple corrigé : avec une sauvegarde chaque soir et un dernier instantané daté du samedi 3 octobre, la politique « --keep-daily 7 --keep-weekly 4 --keep-monthly 6 » conserve 13 instantanés distincts, pas 17. Tu gardes 7 daily du 27 septembre au 3 octobre, 2 weekly supplémentaires pour les semaines finies le 20 et le 13 septembre, puis 4 monthly supplémentaires aux fins de mois de mai, juin, juillet et août. Les instantanés du 3 octobre et du 30 septembre comptent déjà comme daily, et certains comptent aussi comme weekly ou monthly. De même, une complète de 18 Gio suivie de six incrémentales de 2, 1, 3, 2, 2 et 1 Gio représente 29 Gio de données à stocker avant déduplication."),
    mistakes("appeler « sauvegarde » un simple miroir non versionné ; lancer « rsync --delete » sans « --dry-run » ; oublier que le mot de passe du dépôt restic est aussi vital que les données ; croire un journal « succès » sans jamais tester une restauration."),
    safety("travaille sur tes propres données de test, une machine virtuelle ou un serveur autorisé. Avant d’utiliser une option destructive comme « --delete », fais un essai à blanc. Ne stocke jamais le mot de passe d’un dépôt de sauvegarde dans l’historique d’un shell ou dans un dépôt Git."),
    takeaway("une archive, une synchronisation et une sauvegarde versionnée répondent à des besoins différents. « rsync » demande de la prudence, « restic » ajoute la mémoire des instantanés, et une sauvegarde non restaurée en test reste une promesse plus qu’une preuve."),
    practice("Dans « TP 5 : mises à jour, disques et sauvegardes », lis un journal de sauvegarde, juge la rétention, vérifie si la restauration paraît réaliste, puis termine avec le quiz."),
    reference("cmSauvegardes"),
    reference("ubuntuFrRsync"),
    reference("restic"),
  ],
  quiz: {
    title: "Quiz : sauvegardes Linux",
    questions: [
      questions.choice("Que change la barre finale dans « rsync -a src/ dest/ » ?", ["Elle chiffre la copie", "Elle copie le contenu de « src » plutôt que le dossier « src » lui-même", "Elle empêche toute suppression", "Elle active une sauvegarde complète"], 1, "Avec la barre finale, « rsync » recopie le contenu du dossier source. Sans elle, il recrée le dossier source dans la destination. Cette nuance paraît petite, mais elle change complètement l’arborescence obtenue.", "facile"),
      questions.choice("Pourquoi « --dry-run » est-il si utile avant « rsync --delete » ?", ["Parce qu’il accélère toujours la copie réelle", "Parce qu’il montre ce qui serait copié ou supprimé sans rien modifier", "Parce qu’il remplace automatiquement la sauvegarde hors site", "Parce qu’il vérifie la signature GnuPG du dépôt"], 1, "« --dry-run » affiche les effets attendus sans toucher aux fichiers. Le piège tentant est d’y voir un gain de performance, alors que sa vraie valeur est la réduction du risque d’effacement involontaire.", "moyen"),
      questions.multi("Quelles affirmations sont correctes à propos d’une politique « keep-daily 7, keep-weekly 4, keep-monthly 6 » ? (plusieurs réponses)", ["Les catégories peuvent se chevaucher", "Le total d’instantanés distincts n’est pas toujours égal à 17", "Un instantané récent peut compter à la fois comme daily et weekly", "La politique dispense de tester les restaurations"], [0, 1, 2], "Les instantanés retenus par plusieurs catégories se recouvrent souvent, donc le total distinct varie. Le mauvais raisonnement consiste à croire qu’une belle politique de rétention remplace le test de restauration, alors qu’elle n’en dit rien.", "difficile"),
      questions.tf("Un journal de sauvegarde qui affiche « OK » ne prouve pas à lui seul que tu pourras réellement restaurer les données.", true, "Vrai : il prouve surtout qu’un outil a terminé sans erreur visible. Seule une restauration d’essai vérifie que les données, le mot de passe, les chemins et la procédure permettent vraiment un retour en service.", "moyen"),
    ],
  },
};

const chiffrementLesson: NewLesson = {
  key: "linux-chiffrement",
  title: "Chiffrer sous Linux : LUKS, GnuPG et OpenSSL",
  summary: "Apprends à distinguer chiffrement de disque, de fichier et vérification d’intégrité, puis à utiliser GnuPG, OpenSSL et les empreintes sans te mettre en danger avec une commande destructive.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer le chiffrement d’un disque, d’un fichier et d’une signature, expliquer à quoi sert LUKS, vérifier une empreinte avec « sha256sum » ou OpenSSL, signer puis vérifier avec GnuPG, et reconnaître une commande trop risquée pour être collée telle quelle."),
    prerequisites("avoir suivi « Sauvegarder sous Linux : tar, rsync, restic » et connaître la notion d’empreinte."),
    scenario("Rokia doit transmettre une archive sensible à un collègue et préparer le chiffrement d’un disque externe de sauvegarde. Elle veut aussi vérifier qu’un fichier téléchargé n’a pas été modifié. Rokia doit donc choisir le bon outil selon le besoin : chiffrer un volume entier, protéger un fichier, ou prouver l’intégrité et l’origine d’un téléchargement."),
    videoSlot("Chiffrer sous Linux sans confondre hash, signature et secret"),
    text("Le chiffrement ne sert pas toujours au même niveau. LUKS protège un disque ou une partition entière : utile pour un portable perdu ou un support de sauvegarde volé. GnuPG protège ou signe des fichiers : pratique pour un export de base, une archive ou un document à transmettre. « sha256sum » et « openssl dgst -sha256 » ne chiffrent rien : ils calculent une empreinte, c’est-à-dire un résumé détectant une modification accidentelle ou malveillante."),
    schema([
      "Besoin                            Outil adapté",
      "protéger un disque entier         LUKS avec cryptsetup",
      "protéger un fichier à envoyer     GnuPG",
      "vérifier qu’un fichier n’a pas changé  sha256sum ou openssl dgst",
      "prouver l’origine d’un fichier    signature GnuPG + clé de confiance",
    ].join("\n")),
    text("Avec LUKS, le danger principal est simple : « luksFormat » efface le périphérique visé. Cette commande n’est donc jamais un exemple à coller sur un vrai disque sans préparation. En revanche, il faut connaître le vocabulaire : « open » déverrouille, « close » referme, « luksDump » décrit l’en-tête, et « luksHeaderBackup » sauvegarde une partie critique de la structure. LUKS gère plusieurs emplacements de clé, ce qui aide à changer ou révoquer une phrase secrète sans rechiffrer tout le volume. Si tu perds la phrase secrète ou l’en-tête sans secours, les données peuvent devenir illisibles."),
    text("GnuPG permet un chiffrement symétrique avec « gpg -c », ou asymétrique avec « gpg -e -r ». Tu peux aussi déchiffrer avec « gpg -d », signer avec « gpg --detach-sign » et afficher l’empreinte d’une clé avec « gpg --fingerprint » pour la comparer à une source de confiance. Pour l’enseignement ici, la démonstration la plus sûre consiste à signer puis vérifier un fichier avec une clé de test jetable. Tu évites ainsi de passer un secret en argument de commande, ce qui serait visible dans un processus ou un historique. Les droits restent importants : un fichier sensible ou une clé privée devrait rester lisible seulement par son propriétaire."),
    text("Une empreinte seule ne suffit pas si elle vient du même site compromis que le fichier téléchargé. La signature ajoute un lien avec une clé publique connue. C’est pour cela que les projets sérieux publient à la fois une somme de contrôle et un moyen de vérifier l’identité du signataire. OpenSSL peut aussi calculer une empreinte ou générer de l’aléa avec « openssl rand -hex 16 », mais son chiffrement de fichier seul n’offre pas toujours les garanties d’authenticité que l’on attend d’une signature. Pour un support perdu ou volé, pense aussi aux sauvegardes chiffrées."),
    text("Démonstration guidée : dans Git Bash, calcule réellement une empreinte, demande à OpenSSL le même résumé, puis signe et vérifie un petit fichier avec une clé GnuPG temporaire. Sur un vrai Linux de test, tu peux ensuite lire un en-tête LUKS avec « cryptsetup luksDump ». Pour l’effacement, retiens une limite importante : « shred » n’est pas fiable partout, en particulier sur SSD et sur des systèmes de fichiers journalisés."),
    code([
      "# Vérifier une archive avec deux outils",
      "sha256sum sauvegarde-demo.tar.gz",
      "openssl dgst -sha256 sauvegarde-demo.tar.gz",
      "# exemple de sortie (valeurs fictives)",
      "# e0c527e1...5bb86df5  sauvegarde-demo.tar.gz",
      "# SHA2-256(sauvegarde-demo.tar.gz)= e0c527e1...5bb86df5",
      "",
      "# Signer puis vérifier un fichier avec une clé de test",
      "gpg --detach-sign rapport.txt",
      "gpg --verify rapport.txt.sig rapport.txt",
      "# exemple de sortie (valeurs fictives)",
      "# gpg: Good signature from \"Demo Linux C <demo-linux-c@example.com>\"",
    ].join("\n"), "bash"),
    code([
      "# Lire un en-tête LUKS et préparer sa sauvegarde",
      "cryptsetup luksDump /dev/sdb1",
      "# exemple de sortie (valeurs fictives)",
      "# LUKS header information",
      "# Version:        2",
      "# UUID:           4b3a7b7d-6d8e-4bde-9c73-3b4f2e8c1234",
      "# Keyslots:",
      "#   0: luks2",
      "",
      "cryptsetup luksHeaderBackup /dev/sdb1 --header-backup-file entete-sdb1.img",
      "",
      "cryptsetup open /dev/sdb1 sauvegarde_luks",
      "# exemple de sortie (valeurs fictives)",
      "# Aucun texte si l’ouverture réussit",
    ].join("\n"), "text"),
    example("Exemple corrigé : tu télécharges une archive, une empreinte SHA-256 et une signature. Si l’empreinte correspond mais provient du même site compromis que l’archive, tu n’es pas encore rassuré. Le contrôle le plus solide consiste à vérifier la signature avec une clé publique de confiance, puis à confirmer que l’empreinte calculée localement correspond à celle annoncée par une source indépendante. Le hash seul détecte une modification ; la signature ajoute l’identité du signataire."),
    mistakes("confondre empreinte et chiffrement ; vouloir lancer « luksFormat » sur un vrai disque juste pour tester ; passer une phrase secrète en argument de commande ; publier une clé privée ou un fichier secret avec des droits trop ouverts."),
    safety("ne chiffre que tes propres supports ou ceux que tu gères avec autorisation. Toute manipulation LUKS doit se faire sur un disque de test clairement identifié. N’inscris pas de secret dans une ligne de commande visible dans l’historique, et conserve les sauvegardes d’en-tête LUKS hors du volume chiffré."),
    takeaway("le bon outil dépend du besoin : LUKS pour un volume, GnuPG pour un fichier ou une signature, « sha256sum » ou OpenSSL pour l’intégrité. Une empreinte ne prouve pas à elle seule l’origine d’un fichier, et une commande destructive sur un disque ne se teste jamais au hasard."),
    practice("Dans « TP 5 : mises à jour, disques et sauvegardes », vérifie une empreinte, juge si un contrôle est suffisant et explique quelle preuve manque encore avant de répondre au quiz."),
    reference("ubuntuFrGpg"),
    reference("debCryptsetup"),
    reference("opensslDocs"),
  ],
  quiz: {
    title: "Quiz : chiffrement Linux",
    questions: [
      questions.choice("Quel outil correspond le mieux au chiffrement d’un disque ou d’une partition complète sous Linux ?", ["sha256sum", "cryptsetup avec LUKS", "curl", "df -h"], 1, "LUKS, manipulé via « cryptsetup », protège un volume entier. Le piège est de choisir « sha256sum », qui ne chiffre rien du tout : il calcule seulement une empreinte destinée à vérifier l’intégrité.", "facile"),
      questions.choice("Tu lis « gpg: Good signature from \"Demo Linux C <demo-linux-c@example.com>\" ». Que peux-tu conclure ?", ["Le fichier est forcément secret", "La signature correspond à la clé utilisée pour signer ce fichier", "Le disque système est maintenant chiffré", "Le fichier n’a besoin d’aucune autre vérification"], 1, "Cette ligne montre que la signature est valide pour le fichier et la clé utilisée. Le faux raccourci est de croire que cela rend le fichier « secret » : une signature prouve l’intégrité et l’origine, pas la confidentialité.", "moyen"),
      questions.multi("Quelles affirmations sont justes ? (plusieurs réponses)", ["Une empreinte seule ne prouve pas l’origine d’un fichier si elle vient du même site que le téléchargement", "Passer une phrase secrète en argument de commande peut l’exposer dans l’historique ou les processus", "« luksFormat » est une commande à essayer librement sur le premier disque visible", "Une clé privée ou un fichier sensible mérite des droits très restrictifs"], [0, 1, 3], "Une source indépendante pour l’empreinte, l’évitement des secrets en argument et des droits serrés sont de bonnes pratiques. Le faux geste catastrophique est d’essayer « luksFormat » au hasard : cette commande prépare un volume en détruisant son contenu.", "difficile"),
      questions.tf("Un hash détecte une modification, mais il ne chiffre pas un fichier.", true, "Vrai : une empreinte résume un contenu pour repérer les changements. Elle ne cache pas les données et ne protège pas contre la lecture, contrairement à un vrai chiffrement de fichier ou de volume.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c3:6",
    position: 5,
    title: "Logiciels et mises à jour",
    description: "Ce module t’apprend à faire confiance avec méthode : d’où viennent les paquets, comment appliquer un correctif et comment vérifier qu’il protège réellement le système. Critères de réussite : distinguer dépôt, paquet et signature ; lire des mises à jour en attente et leur source ; décider quand un service ou le noyau doit être relancé après correction.",
    lessons: [paquetsLesson, misesAJourLinuxLesson],
  },
  {
    key: "c3:7",
    position: 6,
    title: "Réseau et accès à distance",
    description: "Tu y développes une lecture défensive du réseau Linux : interfaces, routes, ports, SSH et filtrage local, toujours avec le moindre privilège en tête. Critères de réussite : diagnostiquer du poste au service sans brûler les étapes ; sécuriser l’accès SSH sans se verrouiller dehors ; relire des règles de pare-feu et en déduire l’exposition réelle.",
    lessons: [reseauLesson, sshLesson, pareFeuLesson],
  },
  {
    key: "c3:8",
    position: 7,
    title: "Stockage, sauvegardes et chiffrement",
    description: "Ce module relie disponibilité et confidentialité : lire les volumes, protéger la capacité, sauvegarder avec vérification et choisir le bon niveau de chiffrement selon le besoin. Critères de réussite : interpréter « lsblk », « df » et « fstab » ; juger si une sauvegarde est vraiment restaurable ; choisir entre empreinte, signature, chiffrement de fichier et chiffrement de volume.",
    lessons: [disquesLesson, sauvegardesLesson, chiffrementLesson],
  },
];
