import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const correlationSourcesLesson: NewLesson = {
  key: "logs-correlation-sources",
  title: "Corréler plusieurs sources : clés communes, pivots et enrichissement",
  summary: "Apprends à relier plusieurs journaux sans confondre corrélation, causalité et preuve, puis à bâtir une chronologie propre en UTC avec des pivots défendables.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("choisir une clé de corrélation, pivoter d’une source à une autre, repérer une clé trompeuse, bâtir une chronologie en UTC, et défendre une conclusion par au moins deux sources indépendantes."),
    prerequisites("avoir suivi « Relier les événements sans conclure trop vite » et savoir lire un journal web, un journal d’authentification et un journal de proxy."),
    scenario("Nadia reçoit un signal faible sur « web01 ». Un même poste interne apparaît dans un journal SSH, dans les accès d’un portail et dans le journal du mandataire. Elle doit comprendre si ces traces racontent une même histoire, ou si elles mélangent un collègue pressé, un robot de supervision et un simple téléchargement légitime."),
    videoSlot("Corréler trois journaux sans surinterpréter les indices"),
    text("Corréler, ce n’est pas aligner des lignes qui se ressemblent. C’est relier des événements par une clé commune : adresse IP, compte, nom de machine, identifiant de session, identifiant de requête, empreinte de fichier ou plage de temps. Le pivot est le point de départ que tu poursuis dans une autre source. Avant toute jointure, tu notes le fuseau de chaque journal puis tu convertis en UTC. Sinon, une horloge décalée peut te faire relier un effet à une cause qui n’existe pas."),
    schema([
      "Clé commune utile        Ce qu’elle relie",
      "IP source               un poste précis ou une sortie partagée, par exemple derrière un NAT ou un VPN",
      "Compte utilisateur      une action humaine ou un service",
      "Nom de machine          un actif précis de l’inventaire",
      "Identifiant de session  un parcours applicatif sur plusieurs lignes",
      "Identifiant de requête  une transaction web ou API",
      "Empreinte de fichier    un même artefact sur plusieurs hôtes",
      "Fenêtre de temps        des événements proches à confirmer par une autre clé",
    ].join("\n")),
    text("Une bonne corrélation garde une place aux trous et aux pièges. Un NAT, une passerelle VPN de sortie, un bail DHCP, des adresses partagées, deux machines qui portent le même nom dans des domaines différents, ou une horloge non synchronisée peuvent casser le lien. Tu le notes, puis tu cherches une deuxième source indépendante. Une adresse IP prouve qu’une source a consigné une communication associée à cette adresse à ce moment-là. Elle ne prouve ni, à elle seule, la personne au clavier, ni l’intention, ni même la machine exacte derrière une sortie partagée. La corrélation montre donc un lien plausible ; elle ne prouve pas, à elle seule, la cause de ce lien."),
    text("Démonstration guidée : sur trois extraits inventés de 15 lignes chacun, on repère d’abord l’adresse qui réussit en SSH après plusieurs échecs, puis on regarde ce qu’elle fait dans le portail web et dans le proxy. Les commandes ci-dessous ont été rejouées sur les extraits. Elles montrent une méthode simple : détecter, pivoter, convertir l’heure en UTC, puis résumer. Avec les outils GNU, retiens aussi que « sort », « join » et « comm » travaillent sur des listes triées selon la clé utile. Tu peux refaire cette lecture avec Git Bash, WSL, Termux ou PowerShell, sans SIEM."),
    code([
      "# Extraire les adresses qui réussissent après au moins deux échecs",
      "awk '/Failed password|Accepted password/ {",
      "  if (match($0,/from ([0-9.]+)/,m)) {",
      "    ip=m[1]",
      "    if ($0 ~ /Failed password/) failed[ip]++",
      "    else if (failed[ip] >= 2) print ip \"\\tssh_ok_apres_\" failed[ip] \"_echecs\"",
      "  }",
      "}' auth.log | sort -t $'\\t' -k1,1 -u > suspect.tsv",
      "# exemple de sortie (valeurs fictives)",
      "# 10.1.4.23\tssh_ok_apres_3_echecs",
      "",
      "# Associer ensuite les chemins web vus depuis cette même adresse",
      "awk 'match($0,/^([0-9.]+) - - \\[[^]]+\\] \"[A-Z]+ ([^ ]+)/,m){print m[1] \"\\t\" m[2]}' access.log | sort -t $'\\t' -k1,1 -k2,2 -u > web.tsv",
      "join -t $'\\t' suspect.tsv web.tsv | head -3",
      "# exemple de sortie (valeurs fictives)",
      "# 10.1.4.23\tssh_ok_apres_3_echecs\t/admin/audit",
      "# 10.1.4.23\tssh_ok_apres_3_echecs\t/admin/dashboard",
      "# 10.1.4.23\tssh_ok_apres_3_echecs\t/admin/export.csv",
      "",
      "# Vérifier ce qui apparaît dans les deux listes d’adresses",
      "cut -f1 suspect.tsv | sort -u > suspect-ip.txt",
      "cut -f1 web.tsv | sort -u > web-ip.txt",
      "comm -12 suspect-ip.txt web-ip.txt",
      "# exemple de sortie (valeurs fictives)",
      "# 10.1.4.23",
    ].join("\n"), "bash"),
    schema([
      "Chronologie UTC à produire",
      "2026-03-12T08:12:02Z | auth  | succès SSH pour awa depuis 10.1.4.23",
      "2026-03-12T08:13:02Z | web   | GET /admin/export.csv depuis 10.1.4.23",
      "2026-03-12T08:13:55Z | proxy | GET http://files.example.org/archive.zip",
      "Preuve minimale : fichier, ligne, clé de pivot, hypothèse encore ouverte",
    ].join("\n")),
    text("Sous PowerShell, tu peux obtenir le même type de résumé avec des objets. Le réflexe utile est de compter d’abord, puis de joindre seulement ce qui mérite une lecture humaine. En Windows PowerShell 5.1, il n’existe pas de cmdlet native de jointure tabulaire générique : on rapproche donc les sources avec « Group-Object », des tables de hachage et un filtrage explicite sur la clé choisie. Ici, on importe trois petits fichiers CSV déjà normalisés en UTC, puis on rapproche les adresses présentes dans les trois sources. Cette étape ne prouve toujours pas une compromission : elle prépare une analyse plus serrée."),
    code([
      "# Importer les trois sources normalisées en UTC, puis joindre les adresses communes",
      "$auth = Import-Csv .\\corr-auth.csv",
      "$web = Import-Csv .\\corr-web.csv",
      "$proxy = Import-Csv .\\corr-proxy.csv",
      "",
      "$webByIp = @{}",
      "$web | Group-Object Ip | ForEach-Object { $webByIp[$_.Name] = ($_.Group.Path -join ', ') }",
      "$proxyByIp = @{}",
      "$proxy | Group-Object Ip | ForEach-Object { $proxyByIp[$_.Name] = ($_.Group.Url -join ', ') }",
      "",
      "$auth | Group-Object Ip -NoElement | Sort-Object Count -Descending",
      "# exemple de sortie (valeurs fictives)",
      "# Count Name",
      "# ----- ----",
      "#     1 10.1.4.52",
      "#     1 10.1.4.23",
      "",
      "$auth | Where-Object { $webByIp.ContainsKey($_.Ip) -and $proxyByIp.ContainsKey($_.Ip) } |",
      "  Select-Object Ip,User,@{Name='Web';Expression={$webByIp[$_.Ip]}},@{Name='Proxy';Expression={$proxyByIp[$_.Ip]}} |",
      "  Format-Table -AutoSize",
      "# exemple de sortie (valeurs fictives)",
      "# Ip        User Web                      Proxy",
      "# --        ---- ---                      -----",
      "# 10.1.4.23 awa  /login, /admin/dashboard http://intranet.example.org/notes, http://updates.example.net/tool.txt",
      "# 10.1.4.52 awa  /docs                    http://docs.example.org/guide, http://docs.example.org/api",
    ].join("\n"), "powershell"),
    example("Exemple corrigé : trois échecs puis une réussite sur « 10.1.4.52 » pourraient faire croire à une attaque. La deuxième source casse pourtant l’emballement : le portail ne montre qu’un accès à « /docs », et le proxy ne voit que de la documentation interne. Un bail DHCP ou une sortie VPN partagée peuvent aussi expliquer une adresse vue ailleurs au même moment. L’hypothèse raisonnable devient donc « mot de passe mal saisi puis correction », pas « compromission ». Une corrélation sérieuse accepte de retirer une suspicion quand la deuxième source la contredit."),
    mistakes("utiliser une seule clé sans vérifier si elle est partagée ; joindre des heures locales et UTC sans conversion ; oublier NAT, DHCP, VPN ou horloge décalée ; confondre corrélation et causalité ; conclure à partir d’un seul succès ou d’un seul échec sans deuxième preuve indépendante."),
    safety("tu analyses seulement les journaux de ton organisation ou d’un système pour lequel tu as un mandat écrit. Si tu dois enrichir une adresse ou un domaine, commence par les sources internes. Ne colle jamais un extrait complet de journal réel dans un service en ligne : il peut contenir des identifiants, des adresses et des habitudes de travail."),
    takeaway("corréler, c’est relier par une clé commune puis vérifier que cette clé tient. Convertis d’abord le temps en UTC, cherche ensuite ce qui confirme et ce qui contredit, puis garde une deuxième source avant toute conclusion. Un pivot utile ouvre une enquête, pas une causalité automatique."),
    practice("Travaille dans « TP 4 : corréler trois sources et dresser la chronologie » : pars d’une adresse ou d’un compte, pivote vers les autres journaux, note les trous éventuels, puis termine par le quiz de la leçon."),
    reference("anssiJournalisation"),
    reference("nistLogMgmt"),
    reference("msGroupObject"),
  ],
  quiz: {
    title: "Quiz : corrélation de sources",
    questions: [
      questions.choice("Quelle clé de corrélation demande le plus de prudence si plusieurs personnes partagent une même sortie Internet ?", ["L’adresse IP publique", "Le nom exact d’un fichier exporté", "L’identifiant d’une requête web", "L’empreinte SHA-256 d’un binaire"], 0, "Une adresse IP publique peut représenter un NAT, un proxy, un VPN ou un réseau mobile entier. Les autres clés citées sont souvent plus étroites, même si elles ne remplacent pas le contexte global.", "facile"),
      questions.choice("Tu lis : « 10.1.4.23 ssh_ok_apres_3_echecs /admin/export.csv ». Que peux-tu conclure immédiatement ?", ["Le poste 10.1.4.23 a forcément exfiltré des données", "La même clé apparaît au moins dans le journal SSH et dans le journal web", "Le compte awa a été volé avec certitude", "Le proxy a validé une fuite"], 1, "Cette ligne prouve seulement qu’une même adresse relie un succès SSH et une action web. Elle ne dit encore rien, à elle seule, sur l’intention, l’impact réel ni la présence d’une exfiltration.", "moyen"),
      questions.multi("Dans une chronologie sérieuse, que dois-tu conserver ? (plusieurs réponses)", ["L’heure normalisée, par exemple en UTC", "La source et la ligne qui servent de preuve", "Les trous, comme un journal absent ou tourné", "Seulement l’hypothèse finale, pour aller plus vite"], [0, 1, 2], "Une chronologie utile se rejoue. Elle garde l’heure normalisée, la preuve et les manques constatés. Supprimer les trous ou ne garder que la conclusion empêche un collègue de vérifier ton raisonnement.", "difficile"),
      questions.tf("Deux sources indépendantes qui racontent la même séquence valent mieux qu’une seule source très bavarde.", true, "Vrai : la corrélation renforce une hypothèse quand deux journaux distincts convergent. Un seul journal, même détaillé, peut être incomplet, faux ou sorti de son contexte sans que tu t’en rendes compte.", "moyen"),
    ],
  },
};

const detectionReglesLesson: NewLesson = {
  key: "logs-detection-regles",
  title: "Écrire une règle de détection : seuils, fenêtres de temps et Sigma",
  summary: "Transforme une observation en règle simple, choisis un seuil défendable, compare fenêtre fixe et glissante, puis relie ta détection à Sigma, à ATT&CK et à la pyramide de la douleur sans promettre plus que ce que tu peux prouver.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("définir une condition de détection, choisir un seuil et une fenêtre de temps, grouper par source ou par compte, écrire une règle Sigma simple, et rattacher une détection à une technique ATT&CK pertinente."),
    prerequisites("savoir compter dans un journal avec grep, awk, PowerShell, et avoir compris ce qu’est une corrélation."),
    scenario("Mamadou doit transformer une observation répétée en détection exploitable. Son équipe voit souvent des échecs SSH et quelques scans web. Il lui faut une règle qui attire l’attention sur le bruit anormal, sans noyer ses collègues sous des alertes inutiles."),
    videoSlot("Passer d’une intuition à une règle de détection simple"),
    text("Une règle de détection décrit ce qui doit attirer ton attention. Elle répond à cinq questions : quel événement, sur quelle source, groupé comment, au-dessus de quel seuil, et dans quelle fenêtre de temps. Exemple classique : « au moins cinq échecs SSH depuis une même adresse en cinq minutes ». Sans seuil ni fenêtre, tu crées souvent une alerte bavarde. Sans regroupement, tu mélanges plusieurs utilisateurs ou plusieurs adresses et tu perds le sens opérationnel."),
    schema([
      "Une règle simple contient",
      "condition      ce qui doit être vrai",
      "groupement     par source, par compte, par machine ou par processus",
      "fenêtre        combien de minutes ou d’heures",
      "seuil          à partir de combien d’occurrences",
      "contexte       exclusions, heures ouvrées, biens critiques",
      "sortie         gravité, titre, description, prochaine action",
    ].join("\n")),
    text("Sigma n’est pas un SIEM. C’est un format de règle indépendant du produit, en YAML, pour décrire une sélection et la partager. Une règle Sigma simple contient notamment « title », « id », « status », « logsource », « detection », « condition », « falsepositives », « level » et « tags ». Reste simple : champs, valeurs, condition. La corrélation avancée et l’agrégation changent selon l’outil de destination. Pour un débutant, la bonne pratique est donc d’écrire une sélection claire en Sigma, puis de tester le seuil et la fenêtre avec un script ou dans le moteur de requête de ton outil."),
    code([
      "title: Échecs SSH répétés depuis une même source",
      "id: 11111111-2222-4333-8444-555555555555",
      "status: experimental",
      "description: Détecte des messages \"Failed password\" dans sshd.",
      "logsource:",
      "  product: linux",
      "  service: sshd",
      "detection:",
      "  selection:",
      "    message|contains: \"Failed password\"",
      "  condition: selection",
      "falsepositives:",
      "  - faute de frappe répétée sur un bastion",
      "level: medium",
      "tags:",
      "  - attack.t1110",
    ].join("\n"), "yaml"),
    text("Le tag « attack.t1110 » rattache ici la règle à la technique MITRE ATT&CK « T1110 Brute Force ». C’est utile pour ranger les détections par comportement observé, pas pour faire joli. Côté défense, la pyramide de la douleur aide à choisir quoi viser. Bloquer une adresse IP gêne peu un attaquant. Détecter un comportement, comme une rafale d’échecs suivie d’un succès, lui coûte plus cher à contourner parce qu’il doit changer sa méthode, pas seulement une valeur de configuration."),
    text("Démonstration guidée : on prend un extrait de journal d’authentification et on applique la règle « au moins cinq échecs entre 08:14:00 et 08:18:59, groupés par adresse source ». C’est une fenêtre fixe : le temps est découpé ici en un intervalle prédéfini. Une fenêtre glissante regarderait cinq minutes à partir de chaque nouvel événement et réévaluerait la condition à chaque arrivée. La sortie a été vérifiée deux fois : une fois avec awk, une fois avec Node pour contrôler le compte final. Le résultat montre une seule adresse à suivre."),
    code([
      "# Compter les échecs SSH par adresse dans une fenêtre de cinq minutes",
      "awk '$3 >= \"08:14:00\" && $3 <= \"08:18:59\" && /Failed password/ {",
      "  if (match($0,/from ([0-9.]+)/,m)) n[m[1]]++",
      "}",
      "END {",
      "  for (ip in n) if (n[ip] >= 5) print ip \"\\t\" n[ip]",
      "}' auth.log | sort",
      "# exemple de sortie (valeurs fictives)",
      "# 192.0.2.44\t5",
    ].join("\n"), "bash"),
    schema([
      "Fenêtre et seuil doivent être explicites",
      "Fenêtre fixe      : intervalle prédéfini, ici 08:14:00 à 08:18:59",
      "Fenêtre glissante : cinq minutes recalculées à partir de chaque nouvel événement",
      "Seuil 3 : attrape aussi un utilisateur qui insiste trop vite",
      "Seuil 5 : garde ici le scanner 192.0.2.44, laisse passer le poste 10.1.4.23",
      "Seuil 8 : risque de rater l’attaque lente",
    ].join("\n")),
    example("Exemple corrigé : si ton extrait contient cinq échecs de « 192.0.2.44 » entre 08:14:10 et 08:14:28, puis seulement trois échecs de « 10.1.4.23 » avant un succès légitime plus tôt dans la matinée, un seuil de 5 en cinq minutes est plus défendable qu’un seuil de 3. Le seuil de 3 ferait remonter l’utilisateur pressé, alors que celui de 5 garde le comportement agressif. Tu documentes aussi si ta fenêtre est fixe ou glissante, car ce choix change le moment où l’alerte se déclenche."),
    mistakes("écrire une règle sans dire comment elle regroupe les événements ; oublier de préciser si la fenêtre est fixe ou glissante ; confondre un exemple Sigma simple avec une corrélation complète dépendante d’un SIEM ; coller un identifiant ATT&CK sans lien réel avec le comportement observé ; choisir un seuil « parce qu’il sonne bien » sans test sur un extrait connu."),
    safety("les exemples servent à reconnaître des traces défensivement. Tu n’essaies pas de reproduire une force brute sur un système réel. Analyse uniquement des journaux fournis, les tiens, ou des systèmes sur lesquels tu as une autorisation écrite."),
    takeaway("une règle utile décrit une condition, un regroupement, un seuil et une fenêtre de temps. Dis toujours si la fenêtre est fixe ou glissante. Sigma t’aide à partager la sélection de base. ATT&CK t’aide à nommer le comportement. Le bon seuil vient d’un test, pas d’une intuition."),
    practice("Travaille dans « TP 5 : règles de détection : seuils, fenêtres et faux positifs » : applique plusieurs seuils au même jeu de journaux, relie la règle à une technique pertinente, puis termine par le quiz."),
    reference("sigmaRules"),
    reference("mitreT1110"),
    reference("pyramidOfPain"),
  ],
  quiz: {
    title: "Quiz : écrire une règle de détection",
    questions: [
      questions.choice("Dans une règle « au moins cinq échecs SSH depuis une même source en cinq minutes », quel élément décrit le groupement ?", ["Le mot « cinq »", "L’expression « depuis une même source »", "Le mot « SSH »", "La gravité finale"], 1, "Le groupement dit comment on rassemble les événements avant de compter. Ici, on regroupe par adresse source. Le seuil de cinq vient ensuite, une fois les groupes construits.", "facile"),
      questions.choice("Pourquoi garder la règle Sigma simple dans une première version ?", ["Parce que Sigma interdit toute condition", "Parce que les seuils et agrégations avancées dépendent souvent du moteur cible", "Parce que Sigma ne peut servir qu’aux journaux Windows", "Parce qu’une règle simple n’a jamais de faux positifs"], 1, "Sigma sert à décrire une sélection portable. Les corrélations complexes évoluent selon le backend, donc une première règle claire et simple évite de promettre une syntaxe universelle qui n’existe pas.", "moyen"),
      questions.multi("Lis l’extrait « 08:14:10 échec, 08:14:15 échec, 08:14:19 échec, 08:14:24 échec, 08:14:28 échec » pour la même adresse. Que peux-tu affirmer ? (plusieurs réponses)", ["Le seuil de 5 sur cinq minutes est atteint", "La technique T1110 de force brute est un rattachement plausible", "La compromission est certaine parce qu’il y a cinq échecs", "Le regroupement par adresse source est cohérent pour ce test"], [0, 1, 3], "Cinq échecs dans la fenêtre atteignent bien le seuil, et un rattachement prudent à T1110 est cohérent. En revanche, sans succès ni autre preuve, tu ne peux pas déclarer la compromission certaine.", "difficile"),
      questions.tf("Bloquer une seule adresse IP fait généralement plus mal à l’attaquant que détecter son comportement répété.", false, "Faux : changer d’adresse IP coûte peu à un attaquant. Détecter un comportement, comme une séquence d’échecs répétée, l’oblige davantage à adapter sa méthode, ce qui correspond à la logique de la pyramide de la douleur.", "moyen"),
    ],
  },
};

const falsePositivesLesson: NewLesson = {
  key: "logs-faux-positifs",
  title: "Faux positifs et réglage : mesurer et améliorer une détection",
  summary: "Mesure ce que ta règle voit vraiment, calcule précision et rappel, puis règle un seuil ou une exclusion documentée sans sacrifier la surveillance.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer vrai positif, faux positif et faux négatif, calculer précision et rappel, comparer deux seuils, documenter une exclusion, et choisir un réglage qui reste défendable."),
    prerequisites("avoir déjà écrit une règle simple avec un seuil et une fenêtre de temps."),
    scenario("Awa a enfin une règle qui lève des alertes, mais son équipe soupire : certaines sont utiles, d’autres tombent à chaque lundi matin sur les mêmes postes. Elle doit mesurer le problème, pas seulement le ressentir, puis corriger la règle sans la désactiver par fatigue."),
    videoSlot("Réduire les faux positifs sans rendre une règle aveugle"),
    text("Une alerte utile est un vrai positif : elle signale quelque chose qui mérite réellement l’attention. Un faux positif alerte à tort. Un faux négatif est pire : l’attaque existe, mais la règle ne la voit pas. Un vrai négatif correspond à une activité bénigne que la règle ne signale pas. Pour améliorer une détection, tu comptes donc d’abord VP, FP et FN, et tu gardes le VN pour le raisonnement global si besoin. La précision répond à « parmi les alertes levées, combien étaient justifiées ? ». Le rappel répond à « parmi les attaques réelles, combien ont été détectées ? ». Il faut regarder les deux, sinon tu risques de féliciter une règle silencieuse qui laisse tout passer."),
    schema([
      "Mesures de base",
      "VP = vrai positif, FP = faux positif, FN = faux négatif, VN = vrai négatif",
      "précision = VP / (VP + FP)",
      "rappel    = VP / (VP + FN)",
      "seuil bas  : plus sensible, souvent plus bruyant",
      "seuil haut : moins bruyant, mais peut rater des attaques lentes",
    ].join("\n")),
    text("Le réglage ne se fait pas au bruit ambiant. Il se fait sur un jeu de vérité : un petit lot d’événements étiquetés, dont tu connais le résultat attendu. C’est la seule manière honnête de comparer deux seuils, deux fenêtres, ou une exclusion. Si tu exclus un compte de supervision, tu notes qui l’a décidé, pourquoi, jusqu’à quand, et dans quel contexte cette exclusion reste valide."),
    text("Démonstration guidée : le fichier « jeu-verite.csv » contient 30 événements étiquetés, avec un nombre d’échecs par source et l’étiquette finale « attaque » ou « normal ». On calcule ensuite VP, FP et FN pour deux seuils. Les résultats PowerShell ont été recalculés avec Node sur le même fichier pour vérifier les chiffres et les formules. Tu peux refaire exactement la même méthode sur un vrai export de ton organisation."),
    code([
      "# Comparer deux seuils sur le même jeu de vérité",
      "$rows = Import-Csv .\\jeu-verite.csv",
      "foreach ($threshold in 3,5) {",
      "  $flagged = $rows | Where-Object { [int]$_.failures -ge $threshold }",
      "  $vp = @($flagged | Where-Object truth -eq 'attaque').Count",
      "  $fp = @($flagged | Where-Object truth -eq 'normal').Count",
      "  $fn = @($rows | Where-Object { $_.truth -eq 'attaque' -and [int]$_.failures -lt $threshold }).Count",
      "  [pscustomobject]@{ Seuil=$threshold; Alertes=@($flagged).Count; VP=$vp; FP=$fp; FN=$fn }",
      "} | Format-Table -AutoSize",
      "# exemple de sortie (valeurs fictives)",
      "# Seuil Alertes VP FP FN",
      "# ----- ------- -- -- --",
      "#     3      16  8  8  0",
      "#     5       8  6  2  2",
    ].join("\n"), "powershell"),
    text("La règle a besoin d’un compromis explicite. Ici, le seuil 3 n’oublie aucune attaque, mais il produit autant de faux positifs que de vrais. Le seuil 5 réduit fortement le bruit, au prix de deux faux négatifs. Le bon choix dépend du contexte : un compte d’administration exposé justifie plus de sensibilité qu’un poste bureautique connu. L’important est de choisir consciemment, puis de mesurer à nouveau après chaque changement."),
    code([
      "// Rejouer tous les calculs de précision et de rappel avec Node.js",
      "const scenarios = [",
      "  { nom: 'seuil_3', vp: 8, fp: 8, fn: 0 },",
      "  { nom: 'seuil_5', vp: 6, fp: 2, fn: 2 },",
      "  { nom: 'autre_scenario', vp: 6, fp: 34, fn: 2 },",
      "];",
      "for (const s of scenarios) {",
      "  const precision = s.vp / (s.vp + s.fp);",
      "  const rappel = s.vp / (s.vp + s.fn);",
      "  console.log(`${s.nom}\\tprecision=${(precision * 100).toFixed(1)}%\\trappel=${(rappel * 100).toFixed(1)}%`);",
      "}",
      "// exemple de sortie (valeurs fictives)",
      "// seuil_3\tprecision=50.0%\trappel=100.0%",
      "// seuil_5\tprecision=75.0%\trappel=75.0%",
      "// autre_scenario\tprecision=15.0%\trappel=75.0%",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : sur le jeu de 30 événements, le seuil 3 donne ici VP=8, FP=8 et FN=0, donc une précision de 50,0 % et un rappel de 100,0 %. Le seuil 5 donne VP=6, FP=2 et FN=2, donc une précision de 75,0 % et un rappel de 75,0 %. Sur l’autre scénario connu, 40 alertes dont 6 justifiées pour 8 attaques réelles donnent bien 34 faux positifs et 2 faux négatifs, soit 15,0 % de précision et 75,0 % de rappel. Si ton équipe croule déjà sous le bruit, le seuil 5 peut être plus tenable à court terme, à condition de l’accompagner d’une revue périodique et d’un plan pour récupérer les deux attaques ratées. En revanche, désactiver la règle sans mesure serait une décision aveugle."),
    mistakes("juger une règle au ressenti sans jeu de vérité ; ne regarder que la précision ou seulement le rappel ; monter le seuil jusqu’au silence puis déclarer la règle « réglée » ; créer une exclusion permanente sans propriétaire ni date de révision ; couper une règle devenue bruyante sans comprendre d’où viennent les faux positifs."),
    safety("ne publie pas un jeu de vérité réel contenant des identifiants ou des traces internes. Si tu dois partager un cas, désarme les indicateurs et retire tout détail personnel qui n’est pas nécessaire à l’apprentissage."),
    takeaway("une règle se règle avec des mesures, pas avec de l’agacement. Compte VP, FP et FN, refais les formules à la main, puis mesure avant et après le changement. Une exclusion défendable est datée, motivée, et révisée. Une règle silencieuse n’est pas forcément une bonne règle."),
    practice("Travaille dans « TP 5 : règles de détection : seuils, fenêtres et faux positifs » : compare au moins deux réglages, calcule précision et rappel, documente une exclusion prudente, puis termine par le quiz."),
    reference("nistLogMgmt"),
    reference("anssiJournalisation"),
    reference("sigmaSite"),
  ],
  quiz: {
    title: "Quiz : faux positifs et réglage",
    questions: [
      questions.choice("Que mesure la précision d’une règle ?", ["La part des alertes levées qui étaient justifiées", "La durée totale de l’enquête", "Le nombre d’attaques dans le monde", "La taille du journal en mégaoctets"], 0, "La précision compare les vrais positifs à l’ensemble des alertes levées. Elle dit donc si la règle est surtout utile ou surtout bruyante, pas combien de temps dure l’enquête ni combien d’attaques existent ailleurs.", "facile"),
      questions.choice("Une règle lève 8 alertes justifiées et 8 faux positifs. Quelle phrase est la plus juste ?", ["La règle a forcément un excellent rappel", "La règle a une précision de 50 % sur cet échantillon", "La règle est inutilisable sans autre calcul", "La règle n’a aucun vrai négatif"], 1, "Avec 8 vrais positifs et 8 faux positifs, la précision vaut 8 sur 16, soit 50 %. Cela ne suffit pas à juger le rappel, qui dépend aussi du nombre d’attaques réelles manquées.", "moyen"),
      questions.multi("Que doit contenir une exclusion documentée ? (plusieurs réponses)", ["Le propriétaire de l’exclusion ou l’équipe qui l’assume", "La raison précise, par exemple un compte de supervision connu", "Une date ou une condition de révision", "La promesse implicite qu’on n’en reparlera plus"], [0, 1, 2], "Une exclusion sérieuse appartient à quelqu’un, à une raison et à une révision prévue. La dernière proposition est dangereuse : une exclusion oubliée finit souvent par masquer un comportement qui a changé.", "difficile"),
      questions.tf("Monter fortement le seuil réduit souvent les faux positifs, mais peut créer des faux négatifs.", true, "Vrai : un seuil plus haut filtre une partie du bruit, mais il laisse aussi passer des attaques plus lentes ou moins massives. C’est exactement pour cela qu’on compare précision et rappel avant de choisir.", "moyen"),
    ],
  },
};

const triageLesson: NewLesson = {
  key: "logs-triage",
  title: "Qualifier une alerte et documenter la suite",
  summary: "Apprends à trier une alerte sans te précipiter, à distinguer les faits des hypothèses, puis à rédiger une note que ton équipe pourra reprendre sans ambiguïté.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("comprendre l’alerte et sa règle, vérifier dans d’autres sources, qualifier le résultat, prioriser la suite, escalader selon la procédure, et rédiger une note de triage exploitable."),
    prerequisites("avoir suivi « Relier les événements sans conclure trop vite » et savoir lire au moins deux sources de journaux sur un même cas."),
    scenario("Amina débute au SOC de la coopérative Harmattan. Une alerte de force brute apparaît pendant qu’un collègue gère déjà un incident web. Si sa note de triage est floue, l’équipe perdra du temps. Elle doit donc aller droit aux faits, sans oublier les autorisations et l’impact métier possible."),
    videoSlot("Trier une alerte avec méthode et laisser une note utile"),
    text("Le triage est un premier diagnostic, pas un verdict définitif. Tu commences par comprendre l’alerte elle-même : quelle règle l’a levée, sur quelles données, avec quel seuil, et quel bien est concerné. Ensuite seulement, tu vérifies dans d’autres sources. Cette séparation t’évite de confondre le signal initial avec le contexte qui lui donne son vrai sens."),
    schema([
      "Les six gestes du triage",
      "1. comprendre l’alerte",
      "2. vérifier dans d’autres sources",
      "3. qualifier : vrai positif, faux positif, à surveiller, non concluant",
      "4. prioriser",
      "5. escalader selon la procédure",
      "6. documenter faits, hypothèses, actions et suite",
    ].join("\n")),
    text("Une bonne note de triage distingue clairement les faits des hypothèses. Un fait est observable et sourcé : « cinq échecs SSH depuis 192.0.2.44 entre 08:14:10 et 08:14:28, aucun succès vu ». Une hypothèse est marquée comme telle : « probable scan opportuniste » ou « tentative de force brute à confirmer ». Tu peux aussi indiquer un niveau de confiance, par exemple faible, moyen ou élevé. Cette qualification nourrit ensuite la certitude utilisée pour classer la priorité. Cette hygiène de rédaction est aussi importante que la lecture des journaux, car un autre analyste doit pouvoir reprendre ton travail sans t’appeler."),
    text("Démonstration guidée : on traite une alerte inventée de force brute. On recompte les échecs, on vérifie s’il existe un succès SSH, puis on regarde si la même adresse touche aussi l’application web. Les commandes ont été rejouées sur les extraits. Elles montrent une alerte qui mérite une action défensive, mais ne prouve pas une prise de contrôle."),
    code([
      "# Vérifier le cœur de l’alerte et chercher un succès",
      "ip=\"192.0.2.44\"",
      "awk -v ip=\"$ip\" 'index($0, ip) && /Failed password/ {n++} END {print \"echecs_ssh=\" n+0}' auth.log",
      "awk -v ip=\"$ip\" 'index($0, ip) && /Accepted/ {n++} END {print \"succes_ssh=\" n+0}' auth.log",
      "awk -v ip=\"$ip\" '$1 == ip {n++} END {print \"requetes_web=\" n+0}' access.log",
      "awk -v ip=\"$ip\" '$1 == ip {match($0,/\"[A-Z]+ ([^ ]+) HTTP\\/[0-9.]+\" ([0-9]+)/,m); print m[1] \"\\t\" m[2]}' access.log",
      "# exemple de sortie (valeurs fictives)",
      "# echecs_ssh=5",
      "# succes_ssh=0",
      "# requetes_web=3",
      "# /.env\t404",
      "# /wp-login.php\t404",
      "# /phpmyadmin/\t404",
    ].join("\n"), "bash"),
    schema([
      "Note de triage",
      "Faits : ce qui est vu, où, quand, source, ligne",
      "Hypothèses : marquées comme telles",
      "Actions : vérification, blocage, appel, ticket",
      "Décision : vrai positif, faux positif, à surveiller, non concluant",
      "Confiance : faible, moyenne ou élevée",
      "Suite : À qui passer la main, avec quel niveau d’urgence",
    ].join("\n")),
    text("Dans cet exemple, la qualification prudente est « vrai positif pour une tentative de scan ou de force brute, compromission non confirmée ». L’adresse touche SSH puis plusieurs chemins web connus des scanners, mais aucun succès n’apparaît. La suite logique peut être un blocage, une surveillance renforcée ou une escalade vers l’équipe en charge du site, selon ta procédure. Tu n’effaces rien, tu ne touches pas à la machine sans autorisation, et tu notes si une action de confinement risque d’interrompre un service."),
    example("Exemple corrigé : mauvaise note, « attaque réussie, l’attaquant est sûrement entré, blocage immédiat ». Note réécrite, « Faits : 5 échecs SSH depuis 192.0.2.44 entre 08:14:10 et 08:14:28 dans auth.log ; 3 requêtes web sur /.env, /wp-login.php et /phpmyadmin/ avec code 404 ; aucun succès SSH observé. Hypothèse : scan opportuniste ou tentative de force brute non aboutie. Décision : vrai positif pour activité malveillante, compromission non confirmée. Confiance : moyenne. Suite : proposer un blocage réseau selon la procédure et conserver les preuves. »"),
    mistakes("copier l’alerte telle quelle sans vérifier la source ; mélanger faits et hypothèses dans la même phrase ; prendre une mesure de confinement sans regarder l’impact sur le service ; oublier d’écrire qui reprend le dossier et avec quel niveau d’urgence."),
    safety("un triage peut déclencher une action sur un système critique. Tu suis donc la procédure, les autorisations prévues et le cadre légal. Tu analyses tes journaux ou ceux d’un système sur lequel tu as un mandat écrit, et tu protèges les traces recueillies."),
    takeaway("trier une alerte, c’est comprendre, vérifier, qualifier, prioriser et documenter. Une note claire sépare les faits des hypothèses. Une alerte solide peut justifier une action défensive sans prouver à elle seule une compromission."),
    practice("Travaille dans « Projet final : trier une semaine d’alertes et rédiger le rapport d’analyse » : transforme chaque alerte en note courte, défendable et sourcée, puis termine par le quiz."),
    reference("nistForensics"),
    reference("cnilTracer"),
    reference("cnilGuideSecurite"),
  ],
  quizExtension: {
    improve: [
      "Séparer faits et hypothèses évite de transformer une intuition en preuve. Un autre analyste doit pouvoir relire la note, retrouver les sources exactes et comprendre ce qui est certain, probable ou encore à vérifier avant d’agir.",
      "Avant une action de confinement qui peut couper un service, tu suis la procédure et les autorisations prévues. Bloquer trop vite peut détruire une preuve, interrompre un métier critique ou toucher un utilisateur légitime sans nécessité.",
    ],
    add: [
      questions.choice("Tu relis la phrase « 5 échecs SSH, donc le compte a sûrement été compromis ». Que faut-il faire en premier ?", ["Supprimer le mot « sûrement » et conserver le reste", "Bloquer tous les comptes similaires immédiatement", "Séparer le fait observé de l’hypothèse, puis chercher une preuve complémentaire", "Effacer les journaux pour éviter une fuite"], 2, "Le fait est « 5 échecs SSH ». La compromission n’est qu’une hypothèse tant qu’aucun succès, aucune action postérieure ou aucune autre source ne la confirme. Le bon geste est donc de reformuler, puis de vérifier davantage.", "moyen"),
      questions.multi("Lis l’extrait « echecs_ssh=5 ; succes_ssh=0 ; /.env 404 ; /wp-login.php 404 ; /phpmyadmin/ 404 ». Quelles affirmations sont solides ? (plusieurs réponses)", ["L’activité mérite un triage et une documentation", "Aucune réussite SSH n’est visible dans cet extrait", "La compromission du serveur est certaine", "Les requêtes web ressemblent à des chemins de scan connus"], [0, 1, 3], "L’extrait montre un comportement suspect qui mérite une qualification et une note. Il montre aussi l’absence de succès SSH dans cette fenêtre. En revanche, rien n’autorise encore à conclure à une compromission certaine sans autre preuve.", "difficile"),
    ],
  },
};

const gravitePrioritesLesson: NewLesson = {
  key: "logs-gravite-priorites",
  title: "Gravité, priorité et escalade : décider quoi traiter en premier",
  summary: "Distingue la gravité de la priorité, calcule la gravité par impact × probabilité puis la priorité par gravité × criticité du bien × certitude, et décide quoi traiter d’abord sans inventer de délai standard.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer gravité et priorité, calculer la gravité, transformer une qualification en certitude, appliquer une formule de priorité cohérente, classer plusieurs alertes, et préparer une escalade claire en quelques lignes."),
    prerequisites("avoir compris le triage d’une alerte et savoir distinguer faits, hypothèses et décision."),
    scenario("Koffi ouvre sa file d’attente et voit six alertes en même temps : un scan web, un compte de service ajouté à un groupe admin, un DNS inhabituel, un échec isolé, un export sensible et un effacement de journal Security. Il doit décider quoi traiter d’abord sans céder au réflexe « premier arrivé, premier servi »."),
    videoSlot("Choisir une priorité sans inventer une norme de réponse"),
    text("La gravité mesure ce que l’événement pourrait causer. La priorité décide ce que tu traites en premier. Dans ce parcours, on garde une seule formule de classement : « priorité = gravité × criticité du bien × certitude ». La gravité décrit le dommage potentiel. La priorité ordonne l’action. La certitude vient de la qualification du triage : vrai positif, à surveiller, ou faux positif. Deux alertes peuvent donc partager la même gravité et ne pas avoir la même priorité."),
    schema([
      "Repères utiles",
      "impact      = ce qui pourrait être cassé, perdu ou exposé",
      "probabilité = vraisemblance du scénario redouté",
      "gravité     = impact × probabilité",
      "criticité   = importance du bien concerné",
      "certitude   = confiance issue de la qualification",
      "priorité    = gravité × criticité du bien × certitude",
      "échelles    = chaque organisation fixe ses entiers et ses seuils",
    ].join("\n")),
    text("Une manière simple d’enseigner la méthode consiste à choisir des échelles entières locales. Ici, on prend impact, probabilité et criticité sur 1 à 4, puis certitude sur 0 à 4 avec un exemple prudent : faux positif = 0, à surveiller = 2, vrai positif = 4. Ce sont des choix pédagogiques, pas une norme universelle. Le calcul aide au classement ; chaque organisation fixe ses propres échelles, ses seuils d’escalade et ses objectifs de réaction."),
    text("Démonstration guidée : sur quatre alertes inventées, on calcule d’abord la gravité, puis la priorité complète avec la formule du parcours. Les commandes Git Bash et PowerShell ci-dessous ont été rejouées, puis les totaux ont été recalculés avec Node pour vérifier les produits, les pourcentages éventuels et le classement final."),
    code([
      "# Rejouer le classement dans Git Bash à partir d’un TSV",
      "awk -F '\\t' 'NR==1 {print $0 \"\\tgravite\\tpriorite\"; next} {",
      "  gravite = $2 * $3",
      "  priorite = gravite * $4 * $5",
      "  print $0 \"\\t\" gravite \"\\t\" priorite",
      "}' priorites.tsv | sort -t $'\\t' -k7,7nr -k6,6nr",
      "# exemple de sortie (valeurs fictives)",
      "# alerte\timpact\tprobabilite\tcriticite\tcertitude\tgravite\tpriorite",
      "# export_admin_confirme\t4\t3\t4\t4\t12\t192",
      "# effacement_security\t4\t1\t4\t4\t4\t64",
      "# dns_inhabituel_metier\t3\t2\t3\t2\t6\t36",
      "# scan_404_vitrine\t2\t2\t2\t2\t4\t16",
    ].join("\n"), "bash"),
    code([
      "$rows = Import-Csv .\\priorites.csv | ForEach-Object {",
      "  $impact = [int]$_.impact; $probabilite = [int]$_.probabilite; $criticite = [int]$_.criticite; $certitude = [int]$_.certitude",
      "  [pscustomobject]@{",
      "    Alerte=$_.alerte; Impact=$impact; Probabilite=$probabilite; Criticite=$criticite; Certitude=$certitude;",
      "    Gravite=$impact*$probabilite; Priorite=($impact*$probabilite)*$criticite*$certitude",
      "  }",
      "}",
      "$rows | Sort-Object Priorite -Descending, Gravite -Descending | Format-Table -AutoSize",
      "# exemple de sortie (valeurs fictives)",
      "# Alerte                 Impact Probabilite Criticite Certitude Gravite Priorite",
      "# ------                 ------ ----------- --------- --------- ------- --------",
      "# export_admin_confirme       4           3         4         4      12      192",
      "# effacement_security         4           1         4         4       4       64",
      "# dns_inhabituel_metier       3           2         3         2       6       36",
      "# scan_404_vitrine            2           2         2         2       4       16",
    ].join("\n"), "powershell"),
    code([
      "// Vérifier les produits et le classement avec Node.js",
      "const certitude = { vrai_positif: 4, a_surveiller: 2, faux_positif: 0 };",
      "const alertes = [",
      "  { alerte: 'export_admin_confirme', impact: 4, probabilite: 3, criticite: 4, certitude: certitude.vrai_positif },",
      "  { alerte: 'effacement_security', impact: 4, probabilite: 1, criticite: 4, certitude: certitude.vrai_positif },",
      "  { alerte: 'dns_inhabituel_metier', impact: 3, probabilite: 2, criticite: 3, certitude: certitude.a_surveiller },",
      "  { alerte: 'scan_404_vitrine', impact: 2, probabilite: 2, criticite: 2, certitude: certitude.a_surveiller },",
      "];",
      "const classes = alertes.map(a => ({",
      "  ...a,",
      "  gravite: a.impact * a.probabilite,",
      "  priorite: a.impact * a.probabilite * a.criticite * a.certitude,",
      "})).sort((a, b) => b.priorite - a.priorite || b.gravite - a.gravite || b.criticite - a.criticite);",
      "console.table(classes);",
      "// exemple de sortie (valeurs fictives) : export_admin_confirme reste devant effacement_security,",
      "// puis dns_inhabituel_metier, puis scan_404_vitrine.",
    ].join("\n"), "javascript"),
    schema([
      "Exemple d’échelles locales à expliquer",
      "impact, probabilité, criticité : 1 à 4",
      "certitude 0 : faux positif confirmé",
      "certitude 2 : à surveiller",
      "certitude 4 : vrai positif confirmé",
      "même gravité ≠ même priorité",
    ].join("\n")),
    schema([
      "Escalade claire en dix lignes maximum",
      "quoi : type d’alerte et système",
      "quand : heure UTC",
      "preuve : journal et ligne clé",
      "gravité : ce que l’événement pourrait causer",
      "priorité : pourquoi ce cas passe avant les autres",
      "proposition : surveiller, bloquer, appeler, passer la main",
    ].join("\n")),
    text("Deux alertes peuvent donc partager la même gravité et ne pas avoir la même priorité. Dans l’exemple, « effacement_security » et « scan_404_vitrine » ont tous deux une gravité de 4. Pourtant, leurs priorités diffèrent fortement, car la criticité du bien et la certitude ne sont pas les mêmes. Le calcul est une aide au classement. Il ne remplace ni la procédure, ni le contexte métier, ni le jugement d’un responsable si une mesure risque de couper un service. Il ne fixe jamais, à lui seul, un délai « standard » de réaction."),
    example("Exemple corrigé : deux alertes ont la même gravité 4. La première est « effacement_security » avec impact 4, probabilité 1, criticité 4 et certitude 4, soit une priorité de 64. La seconde est « scan_404_vitrine » avec impact 2, probabilité 2, criticité 2 et certitude 2, soit une priorité de 16. Même gravité, ordre différent : tu traites d’abord la première parce qu’elle touche un bien plus critique et qu’elle est mieux confirmée. Tu n’inventes pas un délai standard : la formule aide à classer, puis la procédure locale fixe l’escalade et les délais."),
    mistakes("confondre gravité et priorité ; mélanger dans une seule formule des échelles que personne n’a définies ; oublier que la certitude vient de la qualification ; traiter le calcul comme un pilote automatique ; annoncer un délai de réaction « standard » qui n’existe pas dans ton organisation."),
    safety("une priorisation ne t’autorise pas à accuser une personne ni à prendre seul une mesure lourde sur un service critique. Si une action coupe un accès ou touche des données personnelles, suis la procédure et garde une trace de la décision."),
    takeaway("la gravité dit ce qui pourrait arriver. La priorité dit ce que tu traites maintenant. Dans ce parcours, la priorité se classe avec « gravité × criticité du bien × certitude ». Les échelles restent locales à l’organisation. L’escalade doit être courte, sourcée et prudente."),
    practice("Travaille dans « Projet final : trier une semaine d’alertes et rédiger le rapport d’analyse » : classe les alertes, justifie leur ordre de traitement, rédige une escalade claire, puis termine par le quiz."),
    reference("nistForensics"),
    reference("cnilGuideSecurite"),
    reference("firstTlp"),
  ],
  quiz: {
    title: "Quiz : gravité, priorité et escalade",
    questions: [
      questions.choice("Quelle phrase distingue correctement la gravité de la priorité ?", ["La gravité classe l’ordre de traitement, la priorité décrit l’impact", "La gravité décrit le dommage potentiel, la priorité classe l’ordre de traitement", "La gravité et la priorité veulent toujours dire la même chose", "La priorité se calcule sans tenir compte du bien concerné"], 1, "La gravité parle du dommage potentiel. La priorité sert à ordonner l’action. C’est justement pour cela qu’on ajoute ici la criticité du bien et la certitude à la gravité.", "facile"),
      questions.choice("Une alerte a impact 3, probabilité 2, criticité 4 et certitude 2. Avec la formule du parcours, quelle proposition est correcte ?", ["gravité 5 et priorité 20", "gravité 6 et priorité 24", "gravité 6 et priorité 48", "gravité 8 et priorité 64"], 2, "La gravité vaut 3 × 2 = 6. La priorité vaut ensuite 6 × 4 × 2 = 48. Le calcul a été rejoué avec Node dans la démonstration.", "moyen"),
      questions.choice("Deux alertes ont la même gravité 4. Laquelle traites-tu d’abord si l’une a criticité 4 et certitude 4, et l’autre criticité 2 et certitude 2 ?", ["Celle avec criticité 2 et certitude 2", "Elles sont forcément à égalité", "Celle avec criticité 4 et certitude 4", "On ne peut jamais les départager"], 2, "À gravité égale, la criticité du bien et la certitude font monter la priorité. Ici, 4 × 4 × 4 donne une priorité supérieure à 4 × 2 × 2.", "difficile"),
      questions.choice("Sur l’échelle d’exemple de cette leçon, que devient la priorité d’un faux positif confirmé ?", ["Elle augmente car il faut le traiter en urgence", "Elle reste inchangée", "Elle tombe à 0 parce que la certitude vaut 0", "Elle devient négative"], 2, "Dans l’exemple pédagogique proposé ici, un faux positif confirmé reçoit une certitude de 0. La priorité calculée tombe donc à 0 tant que la qualification ne change pas.", "moyen"),
    ],
  },
};

const renseignementLesson: NewLesson = {
  key: "logs-renseignement",
  title: "Enrichir une alerte : réputation, WHOIS et sources de renseignement",
  summary: "Ajoute du contexte à une alerte avec prudence, désarme les indicateurs avant partage, puis utilise inventaire, WHOIS ou RDAP, RIPEstat et réputation sans exposer de données internes sensibles.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("choisir une source d’enrichissement adaptée, désarmer un indicateur, noter la source et la date d’une recherche, indiquer un niveau de confiance, interpréter prudemment un résultat contradictoire, et protéger la confidentialité des données internes."),
    prerequisites("avoir compris le triage d’une alerte et savoir quels indicateurs doivent être protégés dans un rapport."),
    scenario("Fatou reçoit une alerte sur une adresse IP externe et un domaine peu connu. Son responsable veut un peu de contexte, mais sans envoyer un extrait de journal complet à un service tiers. Elle doit enrichir proprement, puis écrire ce qu’elle sait, ce qu’elle ignore, et ce qu’elle n’a pas le droit de publier."),
    videoSlot("Enrichir une alerte sans divulguer tes propres données"),
    text("L’enrichissement ajoute du contexte à un indicateur. Tu peux chercher un DNS inverse, un enregistrement WHOIS ou RDAP, une plage réseau dans RIPEstat, un historique de réputation dans un service comme VirusTotal ou URLhaus, ou simplement l’inventaire interne de ton organisation. WHOIS reste un service de consultation de données d’enregistrement. RDAP est son successeur structuré sur HTTP et JSON. Chaque source répond à une question différente. Aucune ne donne la vérité entière. Une adresse peut être partagée, dynamique, louée à un hébergeur légitime ou déjà réattribuée. Une mauvaise réputation aide à prioriser, mais ne prouve pas une attaque. L’absence de réputation ne prouve pas l’innocence non plus."),
    schema([
      "Source                 Ce qu’elle apporte                 Limite principale",
      "inventaire interne     propriété, usage, criticité       parfois incomplet",
      "DNS inverse            nom parfois parlant               souvent absent ou trompeur",
      "WHOIS ou RDAP          données d’enregistrement          pas toujours la machine réelle ni l’activité",
      "RIPEstat               contexte IP, ASN, mesures réseau  vue macro, pas l’intention",
      "VirusTotal             analyses et réputation externes   un verdict n’est pas une preuve ; ne pas soumettre un fichier sensible",
      "URLhaus                URLs malveillantes recensées      centré sur la diffusion de malwares ; absence ≠ innocence",
    ].join("\n")),
    text("Commence toujours par ce que tu contrôles. Un journal interne, un inventaire d’actifs, une CMDB ou l’historique d’un proxy sont souvent plus utiles qu’une recherche publique immédiate. Si tu sors de l’organisation, protège la confidentialité. Tu n’envoies jamais un fichier confidentiel, un extrait complet de journal, un jeton, un nom de machine interne ou un identifiant applicatif vers un service en ligne sans base légale, sans procédure et sans nécessité établie. Tu désarmes aussi les indicateurs dans tes notes : « hxxp://example[.]org » et « 192[.]0[.]2[.]77 » se partagent mieux qu’une URL directement cliquable."),
    text("Démonstration guidée : ici, on prépare seulement la partie locale et le rapport. Les étapes en ligne sont décrites, mais pas jouées avec des valeurs réelles internes. On transforme d’abord les indicateurs en forme non cliquable, puis on note ce que l’on cherchera : propriétaire du préfixe, DNS inverse éventuel, réputation, date de la recherche, outil utilisé et niveau de confiance. Les commandes ont été rejouées sur des indicateurs inventés."),
    code([
      "# Désarmer une IP et une URL dans PowerShell",
      "$indicator = '192.0.2.77'",
      "$url = 'http://login.example.org/reset?ticket=abc123'",
      "$indicator -replace '\\\\.', '[.]'",
      "($url -replace '^http', 'hxxp') -replace '\\\\.', '[.]'",
      "# exemple de sortie (valeurs fictives)",
      "# 192[.]0[.]2[.]77",
      "# hxxp://login[.]example[.]org/reset?ticket=abc123",
      "",
      "# Même principe dans un terminal bash",
      "printf '%s\\n' 'http://login.example.org/reset?ticket=abc123' | sed -e 's#^http#hxxp#' -e 's/\\./[.]/g'",
      "# exemple de sortie (valeurs fictives)",
      "# hxxp://login[.]example[.]org/reset?ticket=abc123",
    ].join("\n"), "powershell"),
    schema([
      "Fiche d’enrichissement minimale",
      "indicateur : 192[.]0[.]2[.]77",
      "source     : RIPEstat",
      "date UTC   : 2026-03-14T09:20:00Z",
      "requête    : prefix overview",
      "résultat   : hébergeur mutualisé, à confirmer par l’inventaire",
      "confiance  : moyenne",
      "prudence   : adresse potentiellement partagée",
    ].join("\n")),
    text("Le TLP sert ensuite à partager le bon niveau d’information avec le bon public. En version 2.0, les libellés valides sont « TLP:CLEAR », « TLP:GREEN », « TLP:AMBER », « TLP:AMBER+STRICT » et « TLP:RED ». « TLP:CLEAR » peut être diffusé largement. « TLP:GREEN » reste dans la communauté prévue, sans publication ouverte. « TLP:AMBER » se limite au besoin d’en connaître dans l’organisation et ses clients. « TLP:AMBER+STRICT » restreint ce partage à l’organisation seule. « TLP:RED » reste limité aux destinataires individuels. Le label n’efface pas la prudence : tu partages seulement ce qui est nécessaire."),
    example("Exemple corrigé : le DNS inverse de « 192.0.2.77 » est vide, RIPEstat renvoie un hébergeur mutualisé, et l’inventaire interne dit qu’un prestataire approuvé utilise ce même hébergeur pour les mises à jour du portail. Un service de réputation de domaines signale en plus une observation ancienne, mais sans détail exploitable. La conclusion prudente n’est pas « indicateur malveillant », mais « hébergeur partagé, contexte externe insuffisant, confiance faible à moyenne, à recouper avec l’URL exacte, l’heure et le poste ayant lancé la connexion ». Trois enrichissements contradictoires appellent plus de contexte, pas une certitude forcée."),
    mistakes("envoyer un extrait complet de journal à un service public ; traiter un résultat de réputation comme une preuve définitive ; oublier de noter la source, la date et le niveau de confiance d’un enrichissement ; publier une URL active dans un rapport partagé."),
    safety("les journaux réels peuvent contenir des données personnelles, des identifiants et parfois des secrets. Tu travailles d’abord avec des sources internes et tu sors seulement des indicateurs minimaux, désarmés, sur des services autorisés par ta procédure."),
    takeaway("enrichir, c’est ajouter du contexte sans trahir la confidentialité. Commence par l’interne, désarme les indicateurs, note la source, la date et le niveau de confiance, puis accepte qu’un résultat externe reste souvent ambigu tant qu’il n’est pas recoupé."),
    practice("Travaille dans « TP 4 : corréler trois sources et dresser la chronologie » : enrichis seulement les indicateurs nécessaires, note leur origine, désarme ce que tu partages, puis termine par le quiz."),
    reference("cnilGuideSecurite"),
    reference("ripeStat"),
    reference("virusTotal"),
    reference("firstTlp"),
  ],
  quiz: {
    title: "Quiz : enrichissement et renseignement",
    questions: [
      questions.choice("Quel est le meilleur point de départ pour enrichir une alerte sans exposer de données sensibles ?", ["Un service public de partage de fichiers", "Les sources internes, comme l’inventaire et les journaux locaux", "Une publication immédiate sur un forum", "Le réseau social du fournisseur"], 1, "Les sources internes donnent souvent le contexte le plus fiable tout en protégeant la confidentialité. Les services externes peuvent aider ensuite, mais seulement avec des indicateurs minimaux et selon la procédure.", "facile"),
      questions.choice("Pourquoi désarmer une URL sous la forme « hxxp://example[.]org » dans un rapport ?", ["Pour la rendre plus rapide à analyser", "Pour éviter qu’elle soit cliquable ou exécutée par erreur", "Pour prouver qu’elle est forcément malveillante", "Pour masquer l’heure de l’événement"], 1, "Le désarmement réduit le risque de clic involontaire ou d’activation d’un lien potentiellement dangereux. Il ne dit rien, à lui seul, sur la nature malveillante ou bénigne de l’URL.", "moyen"),
      questions.multi("Quelles affirmations sont prudentes face à une adresse IP publique ? (plusieurs réponses)", ["Elle peut être partagée par plusieurs clients ou services", "Une mauvaise réputation aide à prioriser, mais ne suffit pas à conclure", "L’absence de réputation prouve qu’elle est légitime", "Il faut noter la source et la date de chaque recherche"], [0, 1, 3], "Une adresse publique peut être mutualisée et une base de réputation peut se tromper ou manquer d’historique. Documenter la source et la date est essentiel, alors qu’une absence de réputation ne constitue jamais une preuve d’innocence.", "difficile"),
      questions.tf("Envoyer un fichier confidentiel à un service en ligne comme outil d’enrichissement est acceptable tant qu’on retire le nom de l’utilisateur.", false, "Faux : un fichier peut contenir bien plus qu’un nom d’utilisateur, et certains services partagent ce qui est soumis. On n’envoie donc jamais un fichier interne sensible sans autorisation explicite et sans nécessité établie.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c6:9",
    position: 7,
    title: "Corrélation et détection",
    description: "Ce module t’apprend à transformer des traces isolées en une lecture défensive cohérente, puis à écrire des détections simples que tu sais mesurer et régler. Critères de réussite : choisir une clé de corrélation et bâtir une chronologie en UTC ; écrire une règle avec seuil, fenêtre et groupement explicites ; mesurer précision et rappel avant de modifier une détection.",
    lessons: [correlationSourcesLesson, detectionReglesLesson, falsePositivesLesson],
  },
  {
    key: "c6:2",
    position: 8,
    title: "Qualifier une alerte",
    description: "Tu y apprends à décider sans te précipiter : qualifier une alerte, ordonner une file d’attente et enrichir les indicateurs sans perdre la confidentialité des journaux. Critères de réussite : rédiger une note de triage qui sépare faits et hypothèses ; classer plusieurs alertes par priorité avec une justification claire ; enrichir un indicateur en notant la source, la date et les limites de l’information obtenue.",
    existing: { fromTitle: "Qualifier une alerte" },
    lessons: [triageLesson, gravitePrioritesLesson, renseignementLesson],
  },
];
