import {
  code, example, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const pareFeuLesson: NewLesson = {
  key: "logs-pare-feu",
  title: "Journaux de pare-feu : lire un ALLOW, un DENY et une série de ports",
  summary: "Apprends à lire une ligne de pare-feu champ par champ, à distinguer le bruit normal d’Internet d’un motif utile, et à compter ports, sources et actions sans conclure trop vite.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("repérer l’action, l’interface, la source, la destination et les ports d’une ligne de pare-feu, distinguer ALLOW, DENY, DROP et REJECT, reconnaître un balayage de ports, compter par source et par port, et expliquer pourquoi un refus n’est pas un incident à lui seul."),
    prerequisites("avoir déjà lu un journal horodaté et savoir qu’une adresse source et un port de destination ne racontent pas la même chose."),
    scenario("Awa surveille le petit réseau d’Atlas. Le pare-feu01 journalise des refus SSH et RDP toute la journée, mais un poste interne semble aussi parler vers une destination inhabituelle. Awa doit éviter deux erreurs : paniquer devant le bruit normal d’Internet, et manquer un flux autorisé qui mérite une vérification."),
    videoSlot("Lire un journal de pare-feu sans confondre bruit et incident"),
    text("Un journal de pare-feu enregistre surtout une décision : laisser passer, refuser en silence, ou refuser avec une réponse. Autour de cette décision, tu lis des champs techniques utiles : interface d’entrée ou de sortie, protocole, adresse source, adresse de destination, port source, port de destination, parfois les drapeaux TCP comme SYN, ACK, RST ou FIN. Le port source est souvent éphémère côté client. Le port de destination te dit plutôt quel service était visé."),
    schema([
      "2026-03-10T09:15:01Z ... [UFW BLOCK] IN=eth0 SRC=192.0.2.11",
      "DST=10.1.0.10 PROTO=TCP SPT=52341 DPT=22 ... SYN",
      "",
      "[UFW BLOCK]  -> action prise",
      "IN=eth0      -> interface ou le paquet arrive",
      "SRC=...      -> adresse qui envoie",
      "DST=...      -> adresse visée",
      "SPT=52341    -> port source, souvent éphémère",
      "DPT=22       -> port du service visé",
      "SYN          -> début d’une tentative TCP",
    ].join("\n")),
    text("ALLOW et ACCEPT signifient qu’une règle a laissé passer le trafic. DENY, DROP, BLOCK et REJECT signifient qu’il a été refusé, mais pas toujours de la même manière. Un DROP ne répond pas. Un REJECT renvoie un refus explicite, par exemple un reset TCP ou une erreur ICMP selon le protocole. Sur Linux, tu verras souvent des préfixes comme « [UFW BLOCK] », « [UFW ALLOW] » ou « [UFW LIMIT] ». Avec nftables ou un équipement comme pfSense, les noms et l’ordre changent, mais la logique reste la même : décision, sens, adresses, ports, indicateurs. Pour l’analyse défensive, retiens surtout ceci : un pare-feu exposé à Internet reçoit en permanence des refus. Le signal utile est souvent ailleurs, dans les flux autorisés inattendus, les sorties vers des ports peu habituels, ou une machine interne qui tente de joindre un segment qu’elle ne devrait pas atteindre."),
    text("Démonstration guidée : travaille sur une copie du journal, jamais sur l’original. Commence par compter les actions, puis les sources bloquées, puis les ports visés. Ensuite seulement, relis quelques lignes autour du motif dominant. Tu cherches une forme : une source qui essaie beaucoup de ports sur la même cible, ou au contraire la même machine qui insiste plusieurs fois sur un seul port."),
    code([
      "# Répartir les actions observées",
      "grep -Eo '\\[UFW [A-Z]+\\]' fw.log | sed 's/\\[UFW //; s/\\]//' | sort | uniq -c | sort -rn",
      "# exemple de sortie (valeurs fictives)",
      "#      20 BLOCK",
      "#       5 ALLOW",
      "",
      "# Sources qui déclenchent le plus de refus",
      "grep \"UFW BLOCK\" fw.log | awk '{for (i=1;i<=NF;i++) if ($i ~ /^SRC=/) {split($i,a,\"=\"); print a[2]}}' | sort | uniq -c | sort -rn",
      "# exemple de sortie (valeurs fictives)",
      "#       8 192.0.2.11",
      "#       6 192.0.2.33",
      "#       3 192.0.2.22",
      "#       2 10.1.4.20",
      "#       1 192.0.2.44",
      "",
      "# Ports les plus visés dans les refus",
      "grep \"UFW BLOCK\" fw.log | awk '{for (i=1;i<=NF;i++) if ($i ~ /^DPT=/) {split($i,a,\"=\"); print a[2]}}' | sort | uniq -c | sort -rn",
      "# exemple de sortie (valeurs fictives)",
      "#       4 443",
      "#       4 3306",
      "#       3 80",
      "#       2 445",
      "#       2 3389",
      "#       2 22",
      "#       1 8080",
      "#       1 5432",
      "#       1 23",
    ].join("\n"), "bash"),
    schema([
      "Motif utile                     Lecture prudente",
      "Une source, beaucoup de ports   Balayage de ports probable",
      "Un port, beaucoup de cibles     Balayage d’hôtes probable",
      "Beaucoup de refus sur 22        Bruit courant d’Internet",
      "ALLOW sortant sur port rare     À vérifier en priorité",
      "Trafic inter-segments refusé    Peut révéler un poste mal placé",
    ].join("\n")),
    example("Exemple corrigé : l’adresse 192.0.2.11 touche successivement 22, 23, 80, 443, 445, 3389, 5432 et 3306 sur la même destination, avec le drapeau SYN et sans échange établi ensuite. C’est un balayage de ports probable : elle explore la surface d’exposition. À l’inverse, une même source qui ne réessaie que 443 plusieurs fois ressemble davantage à un client ou à un script qui tente encore le même service. Dans les deux cas, tu notes le contexte, mais tu priorises davantage un ALLOW sortant inattendu qu’un simple BLOCK entrant."),
    mistakes("confondre le port source éphémère avec le service visé ; conclure à une intrusion sur la seule base d’un refus ; ignorer les flux autorisés sortants parce que le mot « ALLOW » semble rassurant ; oublier que la rotation peut déplacer les lignes anciennes dans un fichier archivé."),
    safety("analyse uniquement les journaux de ton organisation ou d’un système pour lequel tu as un mandat écrit. Les journaux de pare-feu contiennent des adresses IP et parfois des noms de segments : ne les publie pas et ne les envoie pas à un service tiers sans nécessité. Toute action de blocage durable suit la procédure prévue par ton organisation."),
    takeaway("un journal de pare-feu raconte une décision, pas toute l’histoire. Les refus entrants sont souvent du bruit normal. Le vrai signal vient des motifs : beaucoup de ports, beaucoup de cibles, ou un flux autorisé qui ne colle pas à la base de référence."),
    practice("Travaille dans « TP 3 : pare-feu, DNS et proxy : trouver la machine qui balise » : compte les sources, les ports et les actions, puis distingue un balayage de ports d’un simple client qui réessaie avant de finir par le quiz."),
    reference("anssiJournalisation"),
    reference("netfilterDoc"),
    reference("debNft"),
  ],
  quiz: {
    title: "Quiz : journaux de pare-feu",
    questions: [
      questions.choice("Dans une ligne de pare-feu, que représente le champ « DPT=22 » ?", ["Le port du service visé sur la machine de destination", "Le port source éphémère du client", "La gravité du journal", "Le nombre de paquets déjà bloqués"], 0, "« DPT » veut dire destination port. Ici, 22 désigne le service visé, typiquement SSH. Le faux ami le plus tentant est le port source : c’est plutôt « SPT », souvent élevé et peu utile pour savoir quel service était attaqué.", "facile"),
      questions.choice("Quelle phrase décrit le mieux la différence entre DROP et REJECT ?", ["DROP compresse le paquet et REJECT le chiffre", "DROP ne répond pas, REJECT renvoie un refus", "DROP laisse passer et REJECT bloque seulement en IPv6", "DROP est réservé à DNS et REJECT à HTTP"], 1, "La différence utile pour l’analyste est la réponse fournie ou non à l’émetteur. Rien ici ne parle de chiffrement ou d’IPv6 uniquement. Le piège courant est d’attribuer à ces mots un sens applicatif alors qu’ils décrivent le comportement du filtrage.", "moyen"),
      questions.choice("Tu lis plusieurs lignes comme « [UFW BLOCK] ... SRC=192.0.2.11 ... DPT=22 », puis la même source vise 23, 80, 443, 445 et 3389 en moins de trente secondes. Quelle hypothèse est la plus solide ?", ["Un utilisateur interne a oublié son mot de passe", "Le serveur est déjà compromis avec certitude", "Un balayage de ports est probable", "Le service DNS est tombé"], 2, "Une même source qui enchaîne beaucoup de ports différents en peu de temps correspond bien à un balayage de ports. La mauvaise réponse tentante est la compromission certaine : le journal montre une exploration, pas encore une entrée réussie.", "difficile"),
      questions.multi("Quelles situations méritent souvent plus d’attention qu’un simple BLOCK entrant ? (plusieurs réponses)", ["Un ALLOW sortant vers un port inhabituel", "Un trafic entre deux segments qui ne devraient pas communiquer", "Un unique refus entrant sur 22 depuis Internet", "Une suite de refus sur un seul port déjà connu et déjà bloqué"], [0, 1], "Les flux autorisés inattendus et les communications internes anormales ont plus de valeur analytique car ils peuvent traduire une activité réelle. Un refus entrant isolé ou un bruit déjà connu ne suffit pas, à lui seul, à élever la priorité.", "moyen"),
    ],
  },
};

const dnsProxyLesson: NewLesson = {
  key: "logs-dns-proxy",
  title: "DNS et mandataire : domaines rares, volumes et appels réguliers",
  summary: "Tu apprendras à lire un journal DNS et un access.log Squid, à mesurer la régularité d’un domaine, et à relier un nom demandé à un volume sortant sans surévaluer un faux positif.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("repérer le client, le nom demandé, le type et le code de réponse d’un journal DNS, lire le format natif de Squid, mesurer les intervalles entre appels, additionner un volume sortant, et conclure avec prudence sur un domaine rare ou régulier."),
    prerequisites("savoir qu’un nom de domaine peut mener à une adresse IP, et qu’un proxy journalise des requêtes web même quand le contenu HTTPS reste chiffré."),
    scenario("Moussa doit expliquer pourquoi un poste de la comptabilité contacte toujours le même domaine à intervalles réguliers. En parallèle, un autre poste accumule des NXDOMAIN et des requêtes TXT étranges. Avec les journaux DNS et le mandataire, Moussa veut montrer ce qui est mesuré, ce qui manque encore, et ce qui doit être vérifié auprès de l’utilisateur avant de parler d’incident."),
    videoSlot("Relier DNS et proxy pour comprendre un trafic répétitif"),
    text("Le DNS transforme un nom en information exploitable par un logiciel : le plus souvent une adresse IP, parfois un serveur de messagerie ou un autre nom. Dans un journal DNS, tu cherches au minimum l’heure, le client, le nom demandé, le type de requête, par exemple A, AAAA, TXT, MX ou NS, et le code de réponse. Si la réponse est journalisée aussi, note l’adresse ou le CNAME renvoyé pour pouvoir relier ensuite ce nom à une destination vue dans un proxy ou un flux. « NOERROR » veut d’abord dire qu’il n’y a pas d’erreur DNS signalée. « NXDOMAIN » signifie que le nom n’existe pas. « SERVFAIL » indique un échec du résolveur ou de la chaîne amont. « REFUSED » veut dire qu’un serveur refuse de répondre à cette requête selon sa politique."),
    schema([
      "Extrait DNS normalisé :",
      "2026-03-10T09:18:02Z  192.168.1.50  k3n9za.service.example  TXT  NXDOMAIN",
      "heure                 client        qname                 type rcode",
      "",
      "Extrait Squid natif :",
      "1773134100.000 120 192.168.1.44 TCP_MISS/200 512 GET http://api.sync.example/health - HIER_DIRECT/192.0.2.40 application/json",
      "",
      "time  durée(ms)  client  résultat/code  octets  méthode  URL  identité  pair/statut  type",
    ].join("\n")),
    text("Le mandataire Squid raconte autre chose. Son format natif commence par un horodatage epoch en secondes avec millisecondes, puis la durée en millisecondes, le client, le résultat du cache avec le code HTTP, le nombre d’octets, la méthode, l’URL, l’identité éventuelle, le pair ou la destination, puis le type MIME. La ligne est en général écrite à la fin de la transaction. « TCP_MISS/200 » veut dire que l’objet n’a pas été servi depuis le cache et qu’une réponse HTTP 200 est partie vers le client. Pour HTTPS sans déchiffrement, tu verras surtout des lignes CONNECT, souvent avec un résultat comme « TCP_TUNNEL/200 » : le domaine et le port, pas le chemin ni le contenu. « TCP_DENIED/403 » montre qu’une politique locale a refusé la requête."),
    text("Un domaine rare, des noms aléatoires, une rafale de NXDOMAIN, beaucoup de TXT ou des appels très réguliers peuvent être utiles. Ce ne sont pas des preuves à eux seuls. Un antivirus, une mise à jour automatique, un CDN ou un agent de supervision peuvent faire la même chose. L’analyste vérifie donc trois choses : la régularité des horodatages, la gigue entre deux appels, le volume échangé, et le contexte métier de la machine qui appelle."),
    text("Démonstration guidée : commence par le DNS. Compte les NXDOMAIN par client. Puis calcule les écarts successifs pour un domaine répété. Enfin, ouvre le journal Squid pour voir si le même poste transfère peu d’octets, ou au contraire un volume qui mérite une vérification. Tu ne cherches pas encore une certitude, tu cherches un motif reproductible et une éventuelle gigue autour d’un rythme stable."),
    code([
      "# Quels clients cumulent des NXDOMAIN ?",
      "awk -F '\\t' '$5==\"NXDOMAIN\" {print $2}' dns.log | sort | uniq -c | sort -rn",
      "# exemple de sortie (valeurs fictives)",
      "#       4 192.168.1.50",
      "",
      "# Intervalles, en secondes, entre les requêtes vers le même domaine",
      "awk -F '\\t' '$2==\"192.168.1.44\" && $3==\"api.sync.example\" { split(substr($1,12,8),t,\":\"); s=t[1]*3600+t[2]*60+t[3]; if (prev != \"\") print s-prev; prev=s }' dns.log",
      "# exemple de sortie (valeurs fictives)",
      "# 16",
      "# 17",
      "# 18",
      "# 17",
      "# 16",
      "",
      "# Volume HTTP vu par Squid pour le client régulier",
      "awk '$3==\"192.168.1.44\" {bytes += $5} END {print bytes}' squid.log",
      "# exemple de sortie (valeurs fictives)",
      "# 19086",
    ].join("\n"), "bash"),
    schema([
      "Signal observé                 Question suivante",
      "NXDOMAIN en rafale             Le domaine est-il aléatoire ou juste mal saisi ?",
      "Beaucoup de TXT                Quel logiciel légitime peut faire cela ?",
      "CONNECT vers un domaine rare   Quel poste, quel utilisateur, quelle heure ?",
      "Intervalles réguliers          Supervision légitime ou balisage ?",
      "Volume sortant élevé           Sauvegarde, mise à jour ou exfiltration ?",
    ].join("\n")),
    example("Exemple corrigé : le poste 192.168.1.44 demande « api.sync.example » avec des écarts de 16, 17, 18, 17 et 16 secondes. La médiane vaut 17 secondes et la gigue reste faible, avec seulement 2 secondes entre l’intervalle le plus court et le plus long. Squid montre ensuite 19 086 octets au total pour ces appels, soit environ 18,64 Kio. Le volume reste faible et le chemin « /health » ressemble à une sonde applicative. À l’inverse, 192.168.1.50 cumule quatre NXDOMAIN en TXT : cela mérite davantage de contexte avant de conclure, surtout si aucun gros volume proxy n’apparaît pour ce même poste."),
    mistakes("prendre NXDOMAIN comme une preuve de malware ; oublier qu’un CONNECT HTTPS ne montre pas le chemin ; additionner les octets sans vérifier s’il s’agit d’une erreur HTML ou d’un vrai contenu ; ignorer les exceptions légitimes comme les mises à jour, l’antivirus ou la supervision."),
    safety("les journaux DNS et proxy peuvent révéler les habitudes de navigation et des données personnelles. Analyse-les seulement dans le cadre de ton organisation ou d’un mandat écrit, informe-toi des règles internes, et n’envoie pas des domaines internes ou des URL sensibles à un service public sans autorisation. Le principe reste défensif : comprendre et protéger, jamais suivre ou profiler sans cadre."),
    takeaway("DNS te dit ce qui a été demandé. Le proxy te dit ce qui a été tenté en HTTP ou HTTPS visible. La régularité, le code de réponse et le volume sont des indices à croiser, jamais une preuve isolée."),
    practice("Travaille dans « TP 3 : pare-feu, DNS et proxy : trouver la machine qui balise » : compte les NXDOMAIN, mesure les intervalles d’un domaine répété, puis relie ce domaine au volume vu dans le mandataire avant de finir par le quiz."),
    reference("rfc1035"),
    reference("squidLog"),
    reference("anssiJournalisation"),
  ],
  quiz: {
    title: "Quiz : DNS et mandataire",
    questions: [
      questions.choice("Que signifie le code « NXDOMAIN » dans un journal DNS ?", ["Le nom demandé n’existe pas", "La réponse était chiffrée", "Le proxy a bloqué la requête", "Le client a changé d’adresse IP"], 0, "« NXDOMAIN » indique que le nom demandé n’existe pas selon le serveur interrogé. Le faux ami tentant est le blocage par proxy : cela relève plutôt d’un journal HTTP ou Squid, pas d’un code DNS.", "facile"),
      questions.choice("Dans un access.log Squid sans déchiffrement HTTPS, que montre surtout une ligne « CONNECT domaine:443 » ?", ["Le contenu exact de la page HTML", "Le nom du domaine et le port cible, pas le chemin ni le contenu", "Le mot de passe saisi par l’utilisateur", "La liste des certificats du serveur"], 1, "Le proxy voit la tentative de tunnel HTTPS vers un hôte et un port. Sans interception TLS, il ne lit ni le chemin ni le contenu. L’erreur la plus tentante est de croire qu’une URL complète reste visible comme en HTTP clair.", "moyen"),
      questions.choice("Tu mesures des intervalles de 17, 17, 17, 17 et 17 secondes vers le même domaine. Quelle conclusion est la plus juste ?", ["C’est forcément un malware", "Le poste est forcément en train d’exfiltrer des données", "Le comportement est régulier et doit être croisé avec le volume et le contexte", "Il faut supprimer le domaine du DNS interne"], 2, "La régularité est un fait solide, mais elle ne suffit pas à elle seule pour conclure à une compromission. Une supervision applicative ou une mise à jour peut faire pareil. Le bon raisonnement consiste à croiser fréquence, volume, utilisateur et rôle du poste.", "difficile"),
      questions.multi("Quels indices peuvent mériter une vérification approfondie dans les journaux DNS ou proxy ? (plusieurs réponses)", ["Beaucoup de requêtes TXT inhabituelles", "Un domaine jamais vu auparavant", "Un unique NOERROR pour un site de l’entreprise", "Des appels réguliers vers le même domaine depuis un seul poste"], [0, 1, 3], "Les requêtes TXT inhabituelles, un domaine nouveau ou une fréquence très régulière peuvent signaler un comportement sortant à analyser. Un NOERROR isolé vers un site interne ne suffit pas. Le faux positif classique vient justement du trafic banal de production.", "moyen"),
    ],
  },
};

const fluxIdsLesson: NewLesson = {
  key: "logs-flux-ids",
  title: "Flux réseau et détection d’intrusion : NetFlow, Zeek et Suricata",
  summary: "Cette leçon t’apprend ce qu’un flux résume, comment lire un extrait de conn.log Zeek et une alerte EVE JSON Suricata, puis comment qualifier une alerte sans extrapoler.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer ce que résume un flux réseau, lire les champs essentiels d’un conn.log Zeek, filtrer une alerte EVE JSON Suricata, repérer « timestamp », « event_type », « flow_id », « alert.signature » et « alert.signature_id », distinguer gravité et priorité, et formuler une phrase factuelle sans transformer une alerte en certitude."),
    prerequisites("avoir vu ce qu’un port, une adresse source, une adresse de destination et un volume d’octets signifient dans un journal réseau."),
    scenario("Nadia reçoit quatre alertes IDS en moins d’une minute. L’une parle d’un domaine rare, une autre d’un gros transfert sortant, une troisième ressemble à une mise à jour web ordinaire. Nadia doit trier vite, mais sans oublier qu’une alerte IDS n’est que le point de départ d’une vérification."),
    videoSlot("Lire un flux réseau et une alerte IDS avec méthode"),
    text("NetFlow et IPFIX ne conservent pas le contenu des paquets. Ils résument une conversation : qui parle à qui, sur quels ports, avec quel protocole, pendant combien de temps, et avec combien d’octets ou de paquets. Ce résumé suffit souvent pour repérer un nouveau pair réseau, un transfert sortant inhabituel, une durée anormalement longue ou un protocole inattendu entre deux segments."),
    schema([
      "Flux -> source, destination, ports, protocole, début, fin, octets",
      "",
      "Utile pour :",
      "- repérer un gros transfert sortant",
      "- voir si un poste parle à une destination inédite",
      "- compter les connexions vers un même serveur",
      "",
      "Limite :",
      "- pas de contenu applicatif",
      "- pas de preuve, seulement un résumé",
    ].join("\n")),
    text("Zeek produit des journaux spécialisés. Dans « conn.log », tu lis notamment « ts », « uid », « id.orig_h », « id.orig_p », « id.resp_h », « id.resp_p », « proto », « service », « duration », « orig_bytes », « resp_bytes » et « conn_state ». « conn_state » résume l’état de la conversation : « SF » pour une ouverture et une fermeture normales, « S0 » pour une tentative sans réponse, « REJ » pour une tentative rejetée. « dns.log » ajoute par exemple « query », « qtype_name » et « rcode_name », tandis que « http.log » aide à relier « method », « host », « uri » et « status_code ». Les lignes commencent souvent par des en-têtes « #fields » et « #types », utiles pour ne pas deviner les colonnes."),
    code([
      "# Ligne Zeek intéressante vers la destination 192.0.2.44",
      "awk -F '\\t' '!/^#/ && $5==\"192.0.2.44\" {print $1, $3, $5, $10, $11, $12}' conn.log",
      "# exemple de sortie (valeurs fictives)",
      "# 1773135200.000000 10.1.2.9 192.0.2.44 1048576 26214400 SF",
    ].join("\n"), "bash"),
    text("Suricata écrit souvent ses alertes dans EVE JSON. Chaque ligne JSON représente un événement. Tu y lis le champ « timestamp », « event_type », les adresses et ports, le protocole, « flow_id », puis le bloc « alert » avec au moins « signature_id », « signature », « category », « severity » et l’action. Une alerte n’est pas une preuve de compromission. La règle peut être trop large, le trafic légitime, ou le flux déjà bloqué. Tu confirmes donc avec la direction du trafic, le volume, l’action prise et, si possible, une autre source comme un proxy ou un pare-feu."),
    text("Démonstration guidée : extrais d’abord les alertes dans un format lisible. Puis compare-les au flux Zeek. Une alerte « gros transfert sortant » est plus crédible si le flux montre vraiment beaucoup d’octets de réponse ou de destination selon le sens observé. Une alerte sur un domaine rare devient moins urgente si le même poste effectue une mise à jour attendue, depuis un service connu, avec un faible volume."),
    code([
      "# Filtrer les alertes EVE et garder l’essentiel",
      "jq -c 'select(.event_type==\"alert\") | {ts:.timestamp,event_type,flow_id,src:.src_ip,dst:.dest_ip,sig_id:.alert.signature_id,sig:.alert.signature,sev:.alert.severity,action:.alert.action}' eve.json",
      "# exemple de sortie (valeurs fictives)",
      "# {\"ts\":\"2026-03-10T09:30:12.000000+0000\",\"event_type\":\"alert\",\"flow_id\":880001,\"src\":\"192.168.1.50\",\"dst\":\"192.0.2.77\",\"sig_id\":2030011,\"sig\":\"ET POLICY Possible Rare Domain Contact\",\"sev\":3,\"action\":\"allowed\"}",
      "# {\"ts\":\"2026-03-10T09:31:05.000000+0000\",\"event_type\":\"alert\",\"flow_id\":880002,\"src\":\"10.1.2.9\",\"dst\":\"192.0.2.44\",\"sig_id\":2030012,\"sig\":\"ET POLICY Large Outbound Transfer\",\"sev\":2,\"action\":\"allowed\"}",
      "# {\"ts\":\"2026-03-10T09:31:44.000000+0000\",\"event_type\":\"alert\",\"flow_id\":880003,\"src\":\"192.168.1.21\",\"dst\":\"192.0.2.90\",\"sig_id\":2030013,\"sig\":\"ET WEB_CLIENT Example Browser Update\",\"sev\":3,\"action\":\"allowed\"}",
      "# {\"ts\":\"2026-03-10T09:32:10.000000+0000\",\"event_type\":\"alert\",\"flow_id\":880004,\"src\":\"192.168.1.32\",\"dst\":\"192.0.2.70\",\"sig_id\":2030014,\"sig\":\"ET DNS Query for .example Domain\",\"sev\":4,\"action\":\"blocked\"}",
    ].join("\n"), "bash"),
    code([
      "# Équivalent PowerShell 5.1 pour les alertes EVE JSON",
      "Get-Content eve.json | ForEach-Object { $_ | ConvertFrom-Json } | Where-Object event_type -eq 'alert' | ForEach-Object { \"{0} {1} {2} {3} {4}\" -f $_.timestamp, $_.flow_id, $_.alert.signature_id, $_.alert.action, $_.alert.signature }",
      "# exemple de sortie (valeurs fictives)",
      "# 2026-03-10T09:30:12.000000+0000 880001 2030011 allowed ET POLICY Possible Rare Domain Contact",
      "# 2026-03-10T09:31:05.000000+0000 880002 2030012 allowed ET POLICY Large Outbound Transfer",
      "# 2026-03-10T09:31:44.000000+0000 880003 2030013 allowed ET WEB_CLIENT Example Browser Update",
      "# 2026-03-10T09:32:10.000000+0000 880004 2030014 blocked ET DNS Query for .example Domain",
    ].join("\n"), "powershell"),
    schema([
      "Alerte IDS                  Réaction analytique",
      "Gravité faible, trafic légitime   À surveiller ou faux positif probable",
      "Gros volume + action allowed      À traiter rapidement",
      "Action blocked par une politique  Vérifier, mais priorité souvent plus basse",
      "Signature seule                    Jamais suffisante",
    ].join("\n")),
    example("Exemple corrigé : l’alerte « ET POLICY Large Outbound Transfer » porte le « flow_id » 880002 et le « signature_id » 2030012, et vise le flux 10.1.2.9 -> 192.0.2.44. Le conn.log associé à ce flux montre 26 214 400 octets en réponse, soit environ 25,00 Mio, et l’action Suricata vaut « allowed ». Celle-ci passe donc en « à traiter ». L’alerte « Example Browser Update » ressemble plutôt à une mise à jour web ordinaire : même si la signature existe, elle devient « faux positif probable » tant qu’aucun autre indice ne l’aggrave. Enfin, « ET DNS Query for .example Domain » est déjà « blocked » : on la note, mais elle ne passe pas devant le gros transfert autorisé."),
    mistakes("confondre gravité numérique de la règle et priorité de traitement ; oublier le sens du flux ; croire qu’un seul outil dit toute la vérité ; citer une signature sans noter si le trafic a été autorisé, bloqué ou si le volume reste banal."),
    safety("Suricata, Zeek et les collecteurs de flux demandent en pratique une sonde ou un serveur dédié. Analyse ces données uniquement sur ton réseau ou un environnement autorisé. Les journaux réseau restent des données sensibles : ils révèlent qui parle à qui, parfois à quel rythme. Ne les confie pas à un service tiers sans nécessité et sans cadre."),
    takeaway("un flux réseau résume une conversation. Une alerte IDS dit qu’une règle a correspondu, pas qu’une attaque est confirmée. Le bon réflexe consiste à croiser signature, action, volume, direction et autre source avant de conclure."),
    practice("Travaille dans « TP 3 : pare-feu, DNS et proxy : trouver la machine qui balise » : pars d’un flux ou d’une alerte, relie-le au reste des journaux, puis justifie ce qui passe « à traiter », « à surveiller » ou « faux positif probable » avant le quiz."),
    reference("rfc7011"),
    reference("suricataEve"),
    reference("nistLogMgmt"),
  ],
  quiz: {
    title: "Quiz : flux réseau et IDS",
    questions: [
      questions.choice("Que manque-t-il en général à un enregistrement NetFlow ou IPFIX par rapport à une capture complète de paquets ?", ["Le contenu détaillé des paquets", "Les adresses IP source et destination", "La durée de la conversation", "Le protocole et les ports"], 0, "Un flux résume les conversations sans conserver le contenu applicatif détaillé. Les adresses, ports, protocoles et volumes font justement partie des informations qu’il garde. Le piège classique consiste à attendre d’un flux le même niveau de preuve qu’un paquet complet.", "facile"),
      questions.choice("Dans un conn.log Zeek, à quoi servent les lignes « #fields » et « #types » ?", ["À chiffrer le journal avant archivage", "À vérifier la signature du fichier", "À nommer les colonnes pour ne pas deviner la position des champs", "À supprimer les flux terminés"], 2, "Ces lignes documentent le format du fichier et évitent d’inventer le sens des colonnes. La confusion la plus tentante est d’y voir un mécanisme de sécurité, alors qu’il s’agit d’un guide de lecture pour l’analyste.", "moyen"),
      questions.choice("Une alerte EVE JSON Suricata affiche « action\":\"blocked\" ». Quelle lecture est la plus prudente ?", ["L’attaque a réussi avec certitude", "Il ne faut plus regarder le reste des journaux", "Le trafic a été bloqué selon la politique observée, mais l’alerte mérite encore une vérification contextuelle", "Le poste source est hors ligne"], 2, "L’action « blocked » signifie que le moteur ou la politique a empêché le flux, ce qui baisse souvent la priorité immédiate. Le faux raccourci serait d’ignorer totalement l’alerte : il faut encore vérifier la source, la signature et les autres journaux.", "difficile"),
      questions.multi("Quels éléments aident à qualifier une alerte IDS ? (plusieurs réponses)", ["Le volume du flux", "La direction source -> destination", "Le fait que la signature soit spectaculaire", "L’action observée, par exemple allowed ou blocked"], [0, 1, 3], "Le volume, la direction et l’action aident à rapprocher l’alerte d’un comportement réel. Une signature impressionnante ne suffit pas. C’est justement ainsi qu’on produit des faux positifs trop convaincants pour être remis en question.", "moyen"),
    ],
  },
};

const grepAwkLesson: NewLesson = {
  key: "logs-grep-awk",
  title: "Extraire et compter : grep, awk, sort et uniq sur des journaux",
  summary: "Tu vas construire des pipelines simples sur des journaux texte, comprendre ce que chaque maillon apporte, et refaire la même lecture avec des équivalents PowerShell sur Windows.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("filtrer un journal avec grep ou Select-String, extraire un champ utile, compter par valeur, trier un top, repérer le piège de uniq sans sort, et comparer une lecture Git Bash avec une lecture PowerShell."),
    prerequisites("savoir ouvrir un fichier texte et lire une ligne de journal avec heure, programme et message."),
    scenario("Koffi doit résumer une rafale d’échecs SSH reçue sur un serveur. Il travaille parfois dans Git Bash, parfois dans PowerShell 5.1, selon le poste qu’il a sous la main. Son objectif n’est pas d’écrire tout de suite un gros script, mais de vérifier pas à pas quel poste échoue le plus et à quel moment."),
    videoSlot("Construire un pipeline d’analyse fiable sur un journal texte"),
    text("La boîte à outils minimale sur des journaux texte tient en peu de commandes. « grep » ou « Select-String » filtrent. « awk » ou une combinaison PowerShell extraient un champ. « sort » ordonne. « uniq -c » ou « Group-Object » comptent. Le bon réflexe consiste à tester chaque maillon séparément avant de les enchaîner. Ainsi, quand le résultat semble absurde, tu sais quel étage corriger. Retenir les options exactes t’évite aussi des erreurs de lecture : « grep -E » pour les regex étendues, « -i » pour ignorer la casse, « -v » pour exclure, « -c » pour compter, « -o » pour ne garder que la correspondance, « -w » pour un mot entier, et « -A/-B/-C » pour le contexte. « grep -P » existe sur certains environnements GNU, mais reste moins portable qu’une ERE avec « -E »."),
    schema([
      "Commande ou option              Usage défensif courant",
      "grep -E -i -v -c -n -o -w      motif, casse, exclusion, compteur, ligne, sous-partie, mot",
      "grep -A/-B/-C                  voir le contexte avant ou après une ligne",
      "awk -F ':' '... END {...}'     séparateur explicite, conditions, totaux",
      "sort -n -r -k -t -u            tri numérique, inverse, par clé, avec séparateur, valeurs uniques",
      "uniq -c                        compter après tri",
      "cut, comm, join, column -t    découper, comparer, joindre, relire un tableau",
      "Select-String, Group-Object   équivalents courants sous PowerShell",
    ].join("\n")),
    text("Deux pièges reviennent souvent. D’abord, « uniq -c » ne regroupe que des lignes identiques adjacentes : il faut presque toujours trier avant. Ensuite, un champ n’est pas toujours à la même position quand le message varie. Sur un auth.log, il vaut parfois mieux chercher le mot « from » puis prendre l’adresse qui suit, plutôt que compter aveuglement les colonnes. « cut » découpe des caractères ou des champs avec un séparateur donné ; « comm » compare deux fichiers triés ligne par ligne ; « join » rapproche deux fichiers triés sur une clé commune. Enfin, PowerShell 5.1 lit parfois mal l’UTF-8 si tu n’indiques pas explicitement l’encodage, et « Select-String » travaille lui aussi ligne par ligne : « -AllMatches » remonte plusieurs correspondances sur une même ligne, « -Context » ajoute des lignes avant et après."),
    text("Démonstration guidée : pars d’un journal d’authentification. Filtre les lignes « Failed password ». Observe-en quelques-unes pour confirmer le motif. Puis extrais les adresses IP après le mot « from ». Enfin, compte et trie le résultat. Rejoue la même démarche dans PowerShell : tu apprendras vite quel outil est disponible sur quel poste."),
    code([
      "# Voir les premières lignes d’échec avec leur numéro",
      "grep -n \"Failed password\" tool-auth.log | head -5",
      "# exemple de sortie (valeurs fictives)",
      "# 1:Mar 10 10:00:01 web01 sshd[1201]: Failed password for invalid user admin from 192.0.2.11 port 51001 ssh2",
      "# 2:Mar 10 10:00:12 web01 sshd[1202]: Failed password for invalid user admin from 192.0.2.11 port 51002 ssh2",
      "# 3:Mar 10 10:00:30 web01 sshd[1203]: Failed password for awa from 192.0.2.44 port 51003 ssh2",
      "# 4:Mar 10 10:01:05 web01 sshd[1204]: Failed password for invalid user test from 192.0.2.11 port 51004 ssh2",
      "# 6:Mar 10 10:01:44 web01 sshd[1206]: Failed password for invalid user oracle from 192.0.2.99 port 51005 ssh2",
      "",
      "# Top des adresses sources en échec",
      "awk '/Failed password/ {for (i=1;i<=NF;i++) if ($i==\"from\") print $(i+1)}' tool-auth.log | sort | uniq -c | sort -rn | head -5",
      "# exemple de sortie (valeurs fictives)",
      "#      11 192.0.2.11",
      "#       6 192.0.2.44",
      "#       5 192.0.2.99",
      "#       5 192.0.2.55",
    ].join("\n"), "bash"),
    code([
      "# Équivalent PowerShell 5.1",
      "Select-String -Path tool-auth.log -Pattern \"Failed password\" | Select-Object -First 5",
      "# exemple de sortie (valeurs fictives)",
      "# tool-auth.log:1:Mar 10 10:00:01 web01 sshd[1201]: Failed password for invalid user admin from 192.0.2.11 port 51001 ssh2",
      "# tool-auth.log:2:Mar 10 10:00:12 web01 sshd[1202]: Failed password for invalid user admin from 192.0.2.11 port 51002 ssh2",
      "",
      "Get-Content tool-auth.log | Where-Object { $_ -match \"Failed password\" } | ForEach-Object { if ($_ -match \"from (?<ip>[0-9.]+)\") { $Matches.ip } } | Group-Object -NoElement | Sort-Object Count -Descending | Select-Object -First 5 | ForEach-Object { \"{0} {1}\" -f $_.Count, $_.Name }",
      "# exemple de sortie (valeurs fictives)",
      "# 11 192.0.2.11",
      "# 6 192.0.2.44",
      "# 5 192.0.2.55",
      "# 5 192.0.2.99",
    ].join("\n"), "powershell"),
    example("Exemple corrigé : si tu veux les cinq adresses qui échouent le plus, la version Bash et la version PowerShell racontent la même histoire : 192.0.2.11 domine nettement. Ce n’est pas encore une attaque prouvée, mais c’est une priorité de lecture. Si tu oublies « sort » avant « uniq -c », tu sous-comptes ou tu éclates le résultat en plusieurs blocs, puis tu prends une mauvaise décision sur la source dominante."),
    mistakes("utiliser « uniq -c » sur des lignes non triées ; supposer qu’une IP est toujours dans la même colonne ; confondre ce qui est filtre et ce qui est compte ; oublier « -Encoding UTF8 » en PowerShell quand le fichier n’est pas lu correctement sous Windows PowerShell 5.1."),
    safety("travaille sur une copie de journal et garde le fichier original intact. Les journaux contiennent des adresses IP, des noms de comptes et parfois des chemins sensibles : ne les colle pas dans un service en ligne. Analyse seulement des traces de ton organisation ou d’un système autorisé."),
    takeaway("un pipeline fiable se construit par petits étages : filtrer, vérifier, extraire, compter, puis trier. Bash et PowerShell peuvent mener au même résultat, à condition de nommer clairement ce que chaque étape produit."),
    practice("Travaille dans « TP 1 : lire, normaliser et dater des journaux de formats différents » : refais un top d’adresses, compare les résultats Bash et PowerShell, puis vérifie que tu obtiens les mêmes nombres avant le quiz."),
    reference("man7Grep"),
    reference("man7Awk"),
    reference("msSelectString"),
  ],
  quiz: {
    title: "Quiz : grep, awk, sort et uniq",
    questions: [
      questions.choice("Pourquoi place-t-on souvent « sort » avant « uniq -c » ?", ["Parce que uniq ne regroupe que les lignes identiques adjacentes", "Parce que sort ajoute les nombres manquants", "Parce que uniq sait lire seulement le JSON", "Parce que grep ne fonctionne plus après uniq"], 0, "« uniq -c » compte seulement les doublons consécutifs. Sans tri préalable, des valeurs identiques séparées dans le fichier restent séparées dans le résultat. Le faux ami est de croire que « uniq » retrouve tout seul toutes les occurrences dans tout le journal.", "facile"),
      questions.choice("Dans un auth.log où les messages varient, quelle technique est la plus robuste pour extraire l’IP source des lignes d’échec ?", ["Prendre toujours la 12e colonne sans vérifier", "Chercher le mot « from » puis lire la valeur suivante", "Compter le nombre de caractères par ligne", "Ne garder que les lignes qui finissent par « ssh2 »"], 1, "Chercher « from » puis la valeur suivante résiste mieux aux variations du message. La réponse tentante est la colonne fixe : elle casse dès qu’une ligne a un compte existant au lieu de « invalid user ».", "moyen"),
      questions.choice("Tu lis « awk '/Failed password/ {for (i=1;i<=NF;i++) if ($i==\"from\") print $(i+1)}' tool-auth.log | sort | uniq -c | sort -rn | head -5 ». Quel est le but du deuxième « sort -rn » ?", ["Trier les adresses par ordre alphabétique", "Afficher les lignes sans numéros", "Classer les comptes du plus élevé au plus faible", "Classer les comptages du plus grand au plus petit"], 3, "Le premier tri prépare « uniq -c ». Le second, avec « -rn », trie les comptes numériques du plus grand au plus petit pour faire un top. L’erreur tentante est de confondre ce tri avec un tri alphabétique sur les adresses.", "difficile"),
      questions.multi("Quelles affirmations sont justes quand tu analyses un journal texte ? (plusieurs réponses)", ["Vérifier quelques lignes brutes avant de compter", "Comparer Bash et PowerShell si tu changes d’environnement", "Laisser les accents mal lus sous Windows, cela n’influence jamais l’analyse", "Documenter la commande qui a produit le top final"], [0, 1, 3], "Vérifier les lignes brutes, comparer les environnements et garder la commande finale renforcent la reproductibilité. Le faux confort est d’ignorer l’encodage : une mauvaise lecture UTF-8 peut casser des motifs, des noms ou des compteurs.", "moyen"),
    ],
  },
};

const regexJsonLesson: NewLesson = {
  key: "logs-regex-json",
  title: "Expressions régulières et JSON : jq et PowerShell",
  summary: "Apprends à extraire proprement des champs avec une regex, à filtrer du JSON lignes avec jq ou ConvertFrom-Json, et à corriger un motif trop large qui produit des faux positifs.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("utiliser des ancres, classes et groupes dans une regex, extraire IP, chemin et code HTTP d’une ligne web, filtrer du JSON lignes avec jq, faire l’équivalent en PowerShell, et repérer une regex trop large."),
    prerequisites("avoir déjà manipulé un journal texte ligne par ligne, et savoir qu’un objet JSON lignes occupe une ligne par événement."),
    scenario("Nadia doit expliquer à un collègue pourquoi sa recherche « tout ce qui contient 200 » est trompeuse. Elle veut montrer une méthode plus propre : une regex qui capture les bons champs dans un journal web, puis un filtre JSON pour isoler les erreurs applicatives. Sa contrainte : sous Windows, jq n’est pas installé par défaut, il faut donc connaître l’alternative PowerShell."),
    videoSlot("Extraire juste ce qu’il faut avec une regex et du JSON lignes"),
    text("Une expression régulière sert à décrire un motif. Les ancres « ^ » et « $ » bornent le début et la fin. Les classes comme « [0-9] » décrivent un ensemble de caractères. Les quantificateurs comme « + » et « {3} » disent combien de fois le motif peut revenir. Un point non échappé vaut « n’importe quel caractère » : si tu veux un point littéral dans une adresse IP, tu écris « \\. », sinon tu attrapes bien plus que prévu. Avec « grep -E », tu es en regex étendues. « grep -P » active des regex de type Perl, mais cette option n’est pas disponible partout : n’écris pas une leçon qui dépend de « -P » si tu peux rester en ERE portable avec « [0-9] » plutôt que « \\d »."),
    schema([
      "Élément regex   Sens",
      "^              début de ligne",
      "$              fin de ligne",
      "[0-9]          un chiffre",
      "+              une ou plusieurs fois",
      "( ... )        groupe capture",
      "|              ou logique",
      "\\.            point littéral",
    ].join("\n")),
    text("Le JSON lignes, lui, suit une autre idée : un objet JSON par ligne. C’est très pratique pour filtrer sans recoller des blocs multi-lignes. Avec « jq », tu peux sélectionner, reformater et grouper rapidement : « -r » pour sortir une chaîne sans les guillemets JSON, « -c » pour garder une sortie compacte sur une ligne, « -s » pour rassembler toutes les lignes avant d’exécuter le filtre une seule fois, en sachant que « -s » charge tout en mémoire. Sous Windows, « jq » n’est pas installé par défaut : c’est pourquoi « ConvertFrom-Json » reste une compétence importante. En JSON lignes, tu l’utilises généralement ligne par ligne ; dans Windows PowerShell 5.1, un commentaire JSON fait échouer l’analyse. Pour un CSV, bascule plutôt vers « Import-Csv » que vers une regex fragile. Dans les deux cas, n’envoie jamais un journal réel vers un service public de test. Si tu veux valider une regex en ligne, utilise des valeurs inventées."),
    text("Démonstration guidée : commence par un journal d’accès web. La regex doit extraire l’adresse IP, le chemin et le code HTTP sans avaler trop de texte. Ensuite, passe sur un fichier JSON lignes d’application pour ne garder que les erreurs. Tu compares enfin la version Bash et la version PowerShell : elles doivent raconter la même histoire, même si la syntaxe diffère."),
    code([
      "# Extraire adresse, code et chemin depuis un journal web",
      "sed -En 's#^([0-9.]+) .* \"[A-Z]+ ([^ ]+) HTTP/[0-9.]+\" ([0-9]{3}) .*#\\1 \\3 \\2#p' access.log",
      "# exemple de sortie (valeurs fictives)",
      "# 192.0.2.11 200 /index.html",
      "# 192.0.2.44 403 /admin",
      "# 192.0.2.55 404 /wp-login.php",
      "# 192.0.2.11 200 /catalogue?id=7",
      "# 192.0.2.44 200 /api/list",
      "# 192.0.2.55 500 /catalogue?id=7%27",
      "# 192.0.2.11 200 /status",
      "# 192.0.2.44 500 /catalogue?id=7%20OR%201=1",
      "# 192.0.2.55 200 /uploads/x.php?cmd=id",
      "# 192.0.2.44 204 /health",
      "",
      "# Garder seulement les erreurs applicatives en JSON lignes",
      "jq -c 'select(.level==\"error\") | {ts,ip,path}' app.jsonl",
      "# exemple de sortie (valeurs fictives)",
      "# {\"ts\":\"2026-03-10T10:00:21Z\",\"ip\":\"192.0.2.55\",\"path\":\"/catalogue\"}",
      "# {\"ts\":\"2026-03-10T10:00:41Z\",\"ip\":\"192.0.2.11\",\"path\":\"/upload\"}",
      "# {\"ts\":\"2026-03-10T10:01:11Z\",\"ip\":\"192.0.2.44\",\"path\":\"/catalogue\"}",
      "# {\"ts\":\"2026-03-10T10:01:31Z\",\"ip\":\"192.0.2.55\",\"path\":\"/upload\"}",
    ].join("\n"), "bash"),
    code([
      "# Équivalent PowerShell 5.1 pour la regex",
      "Get-Content access.log | ForEach-Object { if ($_ -match '^(?<ip>[0-9.]+) .* \"[A-Z]+ (?<path>[^ ]+) HTTP/[0-9.]+\" (?<code>[0-9]{3}) ') { \"{0} {1} {2}\" -f $Matches.ip, $Matches.code, $Matches.path } }",
      "# exemple de sortie (valeurs fictives)",
      "# 192.0.2.11 200 /index.html",
      "# 192.0.2.44 403 /admin",
      "# 192.0.2.55 404 /wp-login.php",
      "",
      "# Équivalent PowerShell 5.1 pour le JSON lignes",
      "Get-Content app.jsonl | ForEach-Object { $_ | ConvertFrom-Json } | Where-Object level -eq 'error' | ForEach-Object { \"{0} {1} {2}\" -f $_.ts, $_.ip, $_.path }",
      "# exemple de sortie (valeurs fictives)",
      "# 2026-03-10T10:00:21Z 192.0.2.55 /catalogue",
      "# 2026-03-10T10:00:41Z 192.0.2.11 /upload",
      "# 2026-03-10T10:01:11Z 192.0.2.44 /catalogue",
      "# 2026-03-10T10:01:31Z 192.0.2.55 /upload",
    ].join("\n"), "powershell"),
    example("Exemple corrigé : la regex trop large « 200 » remonte n’importe quelle ligne qui contient ce nombre, y compris un octet ou un identifiant. La version corrigée capture explicitement le code HTTP après la requête. De même, le point non échappé dans une adresse IP accepte trop de caractères. Quand tu remplaces « . » par « \\. », tu fermes la porte à beaucoup de faux positifs."),
    mistakes("oublier d’échapper un point littéral ; utiliser une regex sans vérifier quelques lignes de sortie ; croire que jq est disponible de série sous Windows ; charger des journaux réels dans un testeur web de regex."),
    safety("les journaux web et JSON applicatifs peuvent contenir des identifiants, des adresses IP et des chemins sensibles. Ne les copie pas dans un service tiers. Sous Windows, préfère « ConvertFrom-Json » si jq n’est pas installé. Tu analyses uniquement des journaux de ton organisation ou d’un environnement autorisé."),
    takeaway("une bonne regex est précise, pas seulement « pratique ». Le JSON lignes simplifie les filtres parce qu’il garde un objet par ligne. Bash avec jq et PowerShell avec ConvertFrom-Json peuvent produire la même lecture si tu nommes bien ce que tu veux extraire."),
    practice("Travaille dans « TP 1 : lire, normaliser et dater des journaux de formats différents » : extrais quelques champs avec une regex, filtre un JSON lignes en Bash et en PowerShell, puis compare les sorties avant de finir par le quiz."),
    reference("wikiRegex"),
    reference("jqManual"),
    reference("msConvertFromJson"),
  ],
  quiz: {
    title: "Quiz : regex et JSON lignes",
    questions: [
      questions.choice("Pourquoi écrit-on « \\. » dans une regex qui doit reconnaître une adresse IP ?", ["Parce qu’un point non échappé veut dire n’importe quel caractère", "Parce que cela oblige la ligne à finir par un point", "Parce que JSON exige deux antislashs", "Parce que PowerShell refuse les points simples"], 0, "Dans une regex, « . » tout seul capture presque n’importe quoi. Pour viser un point réel entre deux octets d’IP, il faut l’échapper. Le faux ami le plus courant est de traiter la regex comme un texte brut sans règles propres.", "facile"),
      questions.choice("Qu’est-ce qu’un fichier JSON lignes ?", ["Un gros tableau JSON sur plusieurs pages", "Un fichier binaire compressé", "Un objet JSON par ligne", "Un CSV qui utilise des accolades"], 2, "Le JSON lignes garde un objet complet par ligne, ce qui facilite les filtres et le traitement en flux. La réponse tentante est le grand tableau JSON : utile aussi, mais moins pratique pour des journaux volumineux ligne par ligne.", "moyen"),
      questions.choice("Tu lis la ligne « 192.0.2.55 - - [10/Mar/2026:10:00:51 +0000] \"GET /catalogue?id=7%27 HTTP/1.1\" 500 ... ». Quel élément doit remonter si ta regex capture correctement IP, code et chemin ?", ["192.0.2.55 500 /catalogue?id=7%27", "500 192.0.2.55 HTTP/1.1", "/catalogue 192.0.2.55 200", "10/Mar/2026 192.0.2.55 /catalogue?id=7%27 404"], 0, "La ligne contient bien l’IP source, le code 500 et le chemin demandé. Les autres propositions mélangent les champs ou changent le code. Le bon test d’une regex consiste justement à comparer l’extraction à la ligne brute, pas à une intuition rapide.", "difficile"),
      questions.multi("Quelles pratiques sont saines quand tu manipules regex et JSON en analyse défensive ? (plusieurs réponses)", ["Vérifier quelques lignes de sortie à la main", "Utiliser ConvertFrom-Json sur Windows si jq manque", "Coller un journal réel dans un service web public pour gagner du temps", "Corriger un motif trop large dès que des faux positifs apparaissent"], [0, 1, 3], "Vérifier la sortie, utiliser l’outil disponible localement et resserrer un motif trop large sont de bons réflexes. Le faux gain de temps consiste à publier un journal réel dans un service web, ce qui peut divulguer des données sensibles ou internes.", "moyen"),
    ],
  },
};

const scriptsAnalyseLesson: NewLesson = {
  key: "logs-scripts-analyse",
  title: "Automatiser l’analyse : des scripts reproductibles et vérifiables",
  summary: "Cette leçon montre comment transformer une analyse répétitive en script rejouable, avec fichier en lecture seule, hash d’entrée, seuil clair et vérification du résultat attendu.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer pourquoi scripter une analyse, vérifier un fichier d’entrée avant lecture, compter avec un seuil, conserver une empreinte pour la reproductibilité, comparer une version Bash et PowerShell, et repérer un bug logique comme « uniq » sans tri."),
    prerequisites("avoir déjà filtré un journal texte et compris qu’une commande manuelle peut être rejouée plus sûrement quand elle est documentée."),
    scenario("Amina doit compter chaque matin les adresses qui dépassent un seuil d’échecs de connexion. Faire les mêmes commandes à la main devient fastidieux, et un collègue obtient parfois un résultat différent parce qu’il oublie une étape. Amina veut donc livrer un petit script lisible, testable et prudent, sans modifier le journal d’origine."),
    videoSlot("Passer du one-liner au script d’analyse reproductible"),
    text("Scripter ne veut pas dire compliquer. Cela veut dire rejouer la même analyse sans oublier d’étape, partager exactement ce qui a été fait, et vérifier qu’un collègue retrouve le même résultat. Un bon script d’analyse commence par vérifier les arguments, lire un fichier en entrée seulement, afficher une sortie explicite, et garder la trace de l’empreinte du fichier et de la version d’outil quand c’est utile."),
    schema([
      "Checklist d’un script d’analyse",
      "1. Vérifier le fichier d’entrée",
      "2. Travailler en lecture seule",
      "3. Nommer le seuil ou les filtres",
      "4. Trier avant de compter si nécessaire",
      "5. Afficher un résultat simple à relire",
      "6. Conserver hash et commande pour rejouer",
    ].join("\n")),
    text("Sous Bash, « set -euo pipefail » et les guillemets autour des variables évitent bien des erreurs. « -e » fait quitter sur beaucoup d’erreurs, « -u » refuse l’expansion d’une variable non définie, et « pipefail » fait remonter l’échec d’une étape intermédiaire d’un pipeline. Cela a pourtant des limites : « -e » ne se comporte pas de la même façon dans les tests de « if », « while » ou « until », ni pour toutes les commandes d’une liste « && » ou « || ». Cela aide, mais ne remplace ni les tests explicites, ni un jeu d’essai connu. Sous PowerShell, les objets facilitent le tri et le comptage. Dans les deux cas, le principe est le même : d’abord la preuve d’entrée, ensuite le comptage, et sur de gros fichiers un traitement en flux plutôt qu’un chargement complet en mémoire."),
    text("Démonstration guidée : le script prend un journal et un seuil. Il vérifie d’abord que le fichier existe, affiche la version de l’outil, puis calcule l’empreinte SHA-256 du fichier d’entrée. Ensuite, il compte les adresses vues après le mot « from » dans les lignes « Failed password ». Enfin, il n’affiche que celles dont le total dépasse ou atteint le seuil. Rejoue la même logique en Bash et en PowerShell : si le résultat diffère, le problème vient d’un maillon de lecture, pas d’une « magie » du shell."),
    code([
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      "logfile=\"${1:?usage: analyse-failures.sh <journal> <seuil>}\"",
      "threshold=\"${2:?usage: analyse-failures.sh <journal> <seuil>}\"",
      "[ -f \"$logfile\" ] || { echo \"fichier introuvable: $logfile\" >&2; exit 1; }",
      "bash --version | head -1",
      "sha256sum \"$logfile\"",
      "awk '/Failed password/ {for (i=1;i<=NF;i++) if ($i==\"from\") print $(i+1)}' \"$logfile\" | sort | uniq -c | awk -v limit=\"$threshold\" '$1 >= limit {print $2 \",\" $1}'",
      "# exemple de sortie (valeurs fictives)",
      "# bash 5.3.15(2)-release",
      "# c67ce98586c725e43d78f84ccc0e5c33a684343aff8e1d773996deb457d2b779 *tool-auth.log",
      "# 192.0.2.11,11",
      "# 192.0.2.44,6",
      "# 192.0.2.55,5",
      "# 192.0.2.99,5",
    ].join("\n"), "bash"),
    code([
      "param([string]$Path,[int]$Threshold=5)",
      "if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw \"Fichier introuvable : $Path\" }",
      "$PSVersionTable.PSVersion.ToString()",
      "Get-FileHash -LiteralPath $Path -Algorithm SHA256 | ForEach-Object { $_.Hash }",
      "Get-Content -LiteralPath $Path | Where-Object { $_ -match \"Failed password\" } | ForEach-Object { if ($_ -match \"from (?<ip>[0-9.]+)\") { $Matches.ip } } | Group-Object -NoElement | Where-Object Count -ge $Threshold | Sort-Object Count -Descending | ForEach-Object { \"{0},{1}\" -f $_.Name, $_.Count }",
      "# exemple de sortie (valeurs fictives)",
      "# 5.1.26100.9549",
      "# C67CE98586C725E43D78F84CCC0E5C33A684343AFF8E1D773996DEB457D2B779",
      "# 192.0.2.11,11",
      "# 192.0.2.44,6",
      "# 192.0.2.55,5",
      "# 192.0.2.99,5",
    ].join("\n"), "powershell"),
    example("Exemple corrigé : si ton premier script oublie le tri avant « uniq -c », tu obtiens un résultat incohérent selon l’ordre du fichier. Le jeu de test attendu doit ici sortir quatre adresses au seuil 5 : 192.0.2.11, 192.0.2.44, 192.0.2.55 et 192.0.2.99. Si ton script en montre moins ou fragmente les comptes, le bug n’est pas dans le journal : il est dans la logique de comptage."),
    mistakes("modifier le journal original au lieu de travailler en lecture seule ; oublier de vérifier que le fichier existe ; laisser des variables non protégées sans guillemets en Bash ; croire qu’un script juste une fois est juste pour toujours sans jeu de test connu."),
    safety("un script d’analyse ne doit jamais réécrire ni nettoyer le journal d’origine. Garde les traces sensibles sur ton poste ou ton environnement autorisé, pas dans un dépôt public. N’inscris aucun secret dans le script ni dans la ligne de commande, et note toujours sur quel fichier et avec quel seuil tu as travaillé."),
    takeaway("scripter, c’est rendre ton analyse rejouable, partageable et vérifiable. Le hash du fichier, le seuil explicite et le petit jeu de test attendu font gagner plus de fiabilité qu’un one-liner impressionnant mais opaque."),
    practice("Travaille dans « TP 1 : lire, normaliser et dater des journaux de formats différents » : transforme une analyse répétée en script, compare Bash et PowerShell, puis vérifie le résultat attendu avant de finir par le quiz."),
    reference("nistForensics"),
    reference("shellcheckSc2086"),
    reference("msWhereObject"),
  ],
  quiz: {
    title: "Quiz : scripts d’analyse",
    questions: [
      questions.choice("Quel est le principal intérêt d’un petit script d’analyse par rapport à une suite de commandes retapées à la main ?", ["Il rend l’analyse plus difficile à vérifier", "Il permet de rejouer la même méthode sans oublier d’étape", "Il chiffre automatiquement tous les journaux", "Il remplace le besoin de comprendre les logs"], 1, "Le script capture une méthode et la rend rejouable. Il ne remplace ni la compréhension ni la vérification. Le faux raccourci tentant est de penser qu’automatiser dispense de relire le résultat ou de comprendre les hypothèses du comptage.", "facile"),
      questions.choice("Pourquoi calculer l’empreinte SHA-256 du fichier d’entrée avant l’analyse peut-il aider ?", ["Pour prouver quel fichier exact a été traité et rejouer la même analyse plus tard", "Pour compresser le journal avant lecture", "Pour convertir le fichier en UTF-8", "Pour supprimer les doublons du journal"], 0, "L’empreinte sert de repère d’intégrité et de reproductibilité : on sait quel fichier a été analysé. Elle ne compresse rien et ne remplace pas la lecture du contenu. Le faux ami est de lui attribuer un effet de transformation sur le journal.", "moyen"),
      questions.choice("Ton script Bash compte avec « uniq -c » mais oublie « sort ». Quel effet est le plus probable ?", ["Les lignes identiques non adjacentes ne seront pas regroupées correctement", "Le script efface le journal d’origine", "La commande devient plus rapide et plus fiable", "Le hash SHA-256 change automatiquement"], 0, "Sans tri préalable, « uniq -c » ne voit que les doublons consécutifs. Le bug produit donc des comptes fragmentés ou trop faibles. La mauvaise intuition consiste à croire que « uniq » parcourt tout le fichier et regroupe à distance.", "difficile"),
      questions.multi("Quelles pratiques renforcent la reproductibilité d’une analyse scriptée ? (plusieurs réponses)", ["Nommer le seuil dans les arguments", "Conserver la commande ou le script utilisés", "Travailler directement sur le journal original et le modifier au besoin", "Tester d’abord sur un petit jeu dont on connaît la bonne réponse"], [0, 1, 3], "Un seuil explicite, un script conservé et un petit jeu de test connu aident à rejouer et vérifier l’analyse. Modifier l’original va à l’inverse de la reproductibilité et peut même détruire une preuve ou compliquer une investigation ultérieure.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c6:7",
    position: 5,
    title: "Réseau, pare-feu, DNS et proxy",
    description: "Ce module t’apprend à lire les journaux réseau sans te laisser impressionner par le volume : pare-feu, DNS, proxy, flux et alertes IDS disent chacun une partie de l’histoire. Critères de réussite : distinguer bruit entrant et signal utile ; relier un domaine à un poste, un volume et un rythme ; qualifier une alerte réseau avec prudence avant d’escalader.",
    lessons: [pareFeuLesson, dnsProxyLesson, fluxIdsLesson],
  },
  {
    key: "c6:8",
    position: 6,
    title: "Outils d’analyse",
    description: "Tu y développes ta boîte à outils quotidienne pour transformer un journal brut en réponse argumentée, puis en analyse rejouable. Critères de réussite : construire un pipeline texte fiable ; extraire proprement des champs avec regex, jq ou PowerShell ; automatiser une analyse simple avec un résultat vérifiable.",
    lessons: [grepAwkLesson, regexJsonLesson, scriptsAnalyseLesson],
  },
];
