import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const windowsEventsLesson: NewLesson = {
  key: "logs-windows-evenements",
  title: "Les journaux d’événements Windows : Security, System et Application",
  summary: "Repère les grands journaux Windows, lis la structure d’un événement, comprends ce que l’audit produit ou ne produit pas, puis filtre un export sans dépendre de l’Observateur d’événements.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("repérer le rôle des journaux Security, System, Application et des journaux « Applications et services », lire les champs d’un événement, expliquer ce qu’une stratégie d’audit doit activer, filtrer un export avec PowerShell, puis reconnaître un effacement de journal comme un signal à vérifier."),
    prerequisites("avoir suivi « D’où viennent les journaux : sources, formats et niveaux de gravité » et « Lire un événement dans un journal »."),
    scenario("Nadia reçoit d’un collègue un export « .evtx » et un CSV issus d’un poste Windows 11 de l’association Teranga. Le collègue a vu des ouvertures de session étranges, mais il n’est pas sûr d’avoir regardé le bon journal. Nadia doit d’abord choisir où lire, puis vérifier si les événements utiles existent vraiment avant d’interpréter quoi que ce soit."),
    videoSlot("Trouver le bon journal Windows avant de conclure"),
    text("Sous Windows, un événement n’est pas une simple ligne de texte : il appartient à un journal, a un fournisseur, un identifiant, un niveau, une heure et des données propres à son type. Les journaux les plus utilisés au début sont « Security » pour l’audit de sécurité, « System » pour le système et les services, « Application » pour les applications classiques, puis les journaux « Applications et services » pour des composants plus spécialisés comme PowerShell ou Sysmon. Les fichiers sont stockés au format « .evtx », que tu lis avec l’Observateur d’événements, « Get-WinEvent » ou « wevtutil »."),
    schema([
      "Journal Windows        Ce qu’on y cherche souvent",
      "Security              ouvertures de session, comptes, audit",
      "System                services, pilotes, démarrages, arrêts",
      "Application           erreurs et messages applicatifs",
      "Applications et services",
      "  PowerShell          blocs de script, journalisation du moteur",
      "  Sysmon              processus, DNS, réseau, fichiers",
    ].join("\n")),
    text("L’anatomie d’un événement reste stable d’un journal à l’autre : « EventID », fournisseur, machine, heure, niveau, puis un bloc de données. Dans le XML, « TimeCreated SystemTime » est écrit en UTC, ce qui est précieux pour une chronologie. L’Observateur d’événements l’affiche souvent en heure locale : ne mélange pas ces deux lectures sans noter le fuseau. Dans « Security », tu verras aussi des champs comme « TargetUserName », « IpAddress », « LogonType » ou « Status », mais seulement pour les événements qui les définissent."),
    schema([
      "Exemple de lecture d’un événement de sécurité",
      "EventID           4624",
      "Provider          Microsoft-Windows-Security-Auditing",
      "Computer          atelier-pc",
      "TimeCreated       2026-03-10T08:15:21Z",
      "Data              TargetUserName=awa",
      "                  LogonType=10",
      "                  IpAddress=192.168.1.77",
      "                  AuthenticationPackageName=Negotiate",
    ].join("\n")),
    text("Le piège classique est de croire qu’un événement absent prouve qu’il ne s’est rien passé. Sous Windows, l’audit doit être activé pour produire les événements de sécurité utiles. Sans sous-catégorie d’audit adaptée, tu n’auras pas de 4624 ou de 4625 à analyser. Il faut aussi surveiller la taille maximale du journal et son mode d’écrasement : un journal trop petit écrase les vieux événements exactement quand tu as besoin d’eux. Enfin, lire « Security » demande souvent des droits d’administration, ce qui explique pourquoi un export CSV ou XML est pratique pour relire ailleurs un sous-ensemble autorisé. Pense aussi au 104 du fournisseur « Microsoft-Windows-Eventlog », souvent visible quand un journal Windows est effacé, et au 1102 dans « Security » : ce sont des signaux d’effacement à expliquer."),
    text("Démonstration guidée : sur Windows, tu peux exporter des événements puis filtrer la copie au lieu d’ouvrir le journal réel à chaque fois. Ici, le CSV est inventé mais dans un format banal : une ligne par événement, avec les champs utiles. La commande ci-dessous isole les identifiants 4624, 4625 et 1102. Le 1102 signifie que le journal d’audit de sécurité a été effacé : c’est un signal à expliquer, pas une preuve automatique de malveillance."),
    code([
      "# Filtrer un export CSV d'événements Windows",
      "Import-Csv .\\windows-events.csv |",
      "  Where-Object { $_.Id -in '4624','4625','1102' } |",
      "  Select-Object TimeCreated, Id, TargetUserName, IpAddress, LogonType, Status |",
      "  Format-Table -AutoSize",
      "# exemple de sortie (valeurs fictives)",
      "# TimeCreated          Id   TargetUserName IpAddress    LogonType Status",
      "# -----------          --   -------------- ---------    --------- ------",
      "# 2026-03-10T08:14:52Z 4625 awa            192.168.1.77 10        0xC000006A",
      "# 2026-03-10T08:15:04Z 4625 awa            192.168.1.77 10        0xC000006A",
      "# 2026-03-10T08:15:21Z 4624 awa            192.168.1.77 10        -",
      "# 2026-03-10T08:20:35Z 4624 svc-sync       -            5         -",
      "# 2026-03-10T08:21:02Z 4625 nadia          192.168.1.90 2         0xC0000234",
      "# 2026-03-10T08:22:10Z 1102 -              -            -         -",
    ].join("\n"), "powershell"),
    text("Tu peux aussi interroger directement Windows avec « Get-WinEvent -FilterHashtable » ou « wevtutil qe », mais sur une machine partagée ou peu puissante, travailler sur un export réduit le risque d’erreur et facilite le partage interne. Garde en tête que ces journaux contiennent des noms de comptes, parfois des adresses IP et d’autres données personnelles. Un export doit être protégé comme une donnée sensible et ne pas partir vers un service tiers sans nécessité ni mandat."),
    example("Exemple corrigé : si tu lis un 4624 avec « TargetUserName=awa », « LogonType=10 », « IpAddress=192.168.1.77 » et « AuthenticationPackageName=Negotiate », tu peux dire : une session RDP réussie a été créée pour le compte « awa » depuis l’adresse interne « 192.168.1.77 ». Tu ne peux pas encore dire : c’était une attaque. Il te manque le contexte habituel du compte, la machine source réelle et les événements juste avant."),
    mistakes("ouvrir seulement « Application » et oublier que l’audit de sécurité est ailleurs ; confondre heure locale affichée et heure UTC du XML ; croire qu’un identifiant absent prouve l’absence d’action alors que l’audit n’était peut-être pas activé ; exporter des journaux réels puis les envoyer hors de l’organisation sans précaution."),
    safety("Tu analyses les journaux de ton organisation ou d’un système pour lequel tu as un mandat écrit. Lire « Security » peut demander des droits élevés : privilégie un export limité quand c’est possible. Ne vide jamais un journal réel pour « faire propre » avant d’avoir suivi la procédure de conservation des preuves."),
    takeaway("Sous Windows, il faut d’abord choisir le bon journal, puis lire l’événement dans sa structure complète. L’heure UTC du XML sert de référence. Un événement manquant peut venir d’une stratégie d’audit absente, et l’effacement du journal de sécurité mérite toujours une explication."),
    practice("Travaille dans « TP 2 : journaux Windows : sessions, comptes et PowerShell » : repère quel export correspond à « Security », filtre les identifiants utiles avec PowerShell, puis explique à quoi sert chaque champ avant de passer au quiz."),
    reference("msEventLogging"),
    reference("msGetWinEvent"),
    reference("msEvent1102"),
  ],
  quiz: {
    title: "Quiz : journaux d’événements Windows",
    questions: [
      questions.choice("Quel journal Windows est la source la plus naturelle pour lire les ouvertures de session auditées ?", ["Application", "Security", "Setup", "PowerShell"], 1, "Les événements d’ouverture de session audités, comme 4624 et 4625, appartiennent au journal « Security ». « Application » contient plutôt les messages des applications, et « PowerShell » ne remplace pas l’audit de sécurité du système.", "facile"),
      questions.choice("Pourquoi une exportation CSV ou XML d’un journal Windows est-elle souvent utile ?", ["Parce qu’elle transforme tous les événements en texte libre non structuré", "Parce qu’elle permet de relire un sous-ensemble sans interroger le journal réel à chaque fois", "Parce qu’elle supprime automatiquement les données personnelles", "Parce qu’elle active l’audit à ta place"], 1, "Un export te permet de travailler hors ligne, de partager un sous-ensemble en interne et de rejouer tes filtres. Il ne supprime pas les données sensibles et n’active aucune stratégie d’audit par magie.", "moyen"),
      questions.multi("Lis cet extrait « TimeCreated=2026-03-10T08:15:21Z, EventID=4624, TargetUserName=awa, LogonType=10, IpAddress=192.168.1.77 ». Quelles conclusions sont solides ? (plusieurs réponses)", ["L’événement est horodaté en UTC", "Une session à distance de type RDP a été créée", "Le compte « awa » est forcément compromis", "L’adresse source observée est 192.168.1.77"], [0, 1, 3], "Le suffixe « Z » indique l’UTC, le type 10 correspond à une ouverture de session distante, et l’adresse observée est bien celle du champ. Le piège est de transformer trop vite une trace en compromission certaine sans contexte supplémentaire.", "difficile"),
      questions.tf("L’événement 1102 mérite d’être surveillé parce qu’il signale un effacement du journal d’audit de sécurité.", true, "Vrai : Microsoft recommande de surveiller 1102, car le journal de sécurité ne devrait pas être vidé sans raison claire. Cela demande une vérification, même si une maintenance légitime peut parfois l’expliquer.", "moyen"),
    ],
  },
};

const windowsSessionsLesson: NewLesson = {
  key: "logs-windows-sessions",
  title: "Ouvertures de session et comptes : événements 4624, 4625, 4672 et 4720",
  summary: "Lis les principaux événements de session et de comptes sous Windows, interprète les types d’ouverture de session et les codes d’échec, puis groupe les traces par source et par compte sans confondre automatisme et intrusion.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer 4624 et 4625, relire les types de session les plus courants, interpréter des codes d’échec vérifiés, repérer un verrouillage ou une création de compte, compter les rafales par source avec PowerShell, puis formuler une conclusion prudente."),
    prerequisites("avoir suivi « Les journaux d’événements Windows : Security, System et Application »."),
    scenario("Awa reçoit un export du journal « Security » d’un poste « pc-awa » et d’un serveur « srv-demo ». Plusieurs collègues se plaignent d’un verrouillage de compte et d’une session Bureau à distance inhabituelle. Awa doit séparer trois choses : le bruit normal des services, les erreurs de mot de passe humaines et une éventuelle séquence de connexion anormale."),
    videoSlot("Lire 4624 et 4625 comme un analyste prudent"),
    text("Les événements centraux ici sont 4624 pour une ouverture de session réussie et 4625 pour un échec. Microsoft documente aussi 4672 quand une nouvelle session reçoit des privilèges sensibles, 4720 quand un compte est créé, 4740 quand un compte est verrouillé, et 4648 quand un processus tente une ouverture de session avec des identifiants explicites. Tu verras souvent 4634 pour la fermeture de session. Chaque identifiant n’est qu’un morceau de l’histoire : c’est la séquence qui compte."),
    schema([
      "LogonType à retenir d’abord",
      "2   Interactive        clavier local",
      "3   Network            accès réseau, partage, service distant",
      "4   Batch              tâche planifiée",
      "5   Service            service Windows",
      "7   Unlock             déverrouillage",
      "10  RemoteInteractive  RDP",
      "11  CachedInteractive  ouverture hors ligne avec cache",
    ].join("\n")),
    text("Pour 4624 et 4625, les champs utiles sont souvent « SubjectUserName » et « SubjectDomainName » pour l’acteur qui tente ou lance l’action, puis « TargetUserName » et « TargetDomainName » pour le compte visé par l’ouverture de session. Tu ajoutes « LogonType », « AuthenticationPackageName », « WorkstationName », « IpAddress » et « IpPort ». Pour 4625, Microsoft documente aussi des codes d’échec utiles dans « Status » et parfois « SubStatus » : « 0xC000006A » pour un nom correct mais un mauvais mot de passe, « 0xC0000064 » pour un nom d’utilisateur inexistant, « 0xC0000234 » pour un compte verrouillé et « 0xC0000072 » pour un compte désactivé. Ne récite pas ces codes par cœur : lis-les dans les champs avant d’interpréter."),
    text("Le type de session t’aide à éviter les faux positifs. Un 4624 de type 5 correspond souvent à un service qui démarre, un type 4 à une tâche planifiée, un type 3 à un accès réseau comme un partage, et un type 10 à du Bureau à distance. Une alerte sur un compte de service peut donc être bénigne si elle correspond à son rôle attendu. Inversement, un type 10 depuis une machine qui n’utilise jamais RDP mérite de l’attention, surtout s’il suit plusieurs 4625 sur le même compte. Garde aussi la chronologie fine en tête : 4647 indique une déconnexion demandée par l’utilisateur, alors que 4634 signale surtout que la session se ferme ; ce n’est pas tout à fait la même histoire."),
    text("Démonstration guidée : commence par compter les échecs par source et par compte. La commande ci-dessous groupe tous les 4625 d’un export CSV inventé. Tu vois immédiatement qu’une même adresse a tenté plusieurs comptes, puis qu’un seul compte a été retenté plusieurs fois. C’est la différence entre arrosage, brute force ciblée et simple oubli de mot de passe."),
    code([
      "# Compter les échecs 4625 par adresse et par compte",
      "Import-Csv .\\windows-sessions.csv |",
      "  Where-Object { $_.Id -eq '4625' } |",
      "  Group-Object IpAddress, TargetUserName |",
      "  Sort-Object Count -Descending |",
      "  Select-Object Count, Name |",
      "  Format-Table -AutoSize",
      "# exemple de sortie (valeurs fictives)",
      "# Count Name",
      "# ----- ----",
      "#     4 192.168.1.77, awa",
      "#     1 192.168.1.90, nadia",
      "#     1 192.168.1.77, koffi",
      "#     1 192.168.1.77, moussa",
      "#     1 192.168.1.77, ama",
    ].join("\n"), "powershell"),
    schema([
      "Lecture prudente d’une séquence",
      "4625  awa   type 10  192.168.1.77  status 0xC000006A",
      "4625  awa   type 10  192.168.1.77  status 0xC000006A",
      "4624  awa   type 10  192.168.1.77  succès",
      "4672  awa   privilèges sensibles attribués",
      "4634  awa   fin de session",
      "=> série à vérifier, pas preuve suffisante seule",
    ].join("\n")),
    text("Quand tu vois 4720, tu regardes qui a créé le compte et depuis quelle session. Si, juste après, tu observes 4728 ou 4732, donc un ajout à un groupe de sécurité, l’histoire devient plus lourde. Selon l’environnement, 4768, 4769, 4771 ou 4776 peuvent compléter la même enquête côté Kerberos ou NTLM : ils aident à comprendre quel protocole a porté l’authentification, pas à remplacer 4624 et 4625. Enfin, 4648 apparaît souvent avec « RUNAS » ou certaines tâches : ce n’est pas malveillant par nature, mais utile pour comprendre quel processus a utilisé des identifiants explicites. Et 4740 te donne au minimum le compte verrouillé à pivoter avec les échecs précédents."),
    example("Exemple corrigé : la séquence « 4625 awa type 10 depuis 192.168.1.77 », répétée deux fois, puis « 4624 awa type 10 » et juste après « 4672 awa » raconte ceci : une session RDP du compte « awa » a finalement réussi depuis cette adresse, et cette session dispose de privilèges sensibles. Tu ne peux pas encore affirmer une compromission, mais tu as assez d’indices pour pivoter vers la machine source, l’horaire habituel du compte et les événements de processus qui suivent."),
    mistakes("lire un type 5 comme une session humaine alors qu’il s’agit d’un service ; oublier qu’un compte verrouillé génère un code précis dans 4625 ; traiter un 4672 isolé comme une preuve d’attaque alors qu’un compte administrateur légitime peut le produire ; bloquer trop vite une adresse partagée sans vérifier le contexte métier."),
    safety("Ces journaux relient des comptes à des machines et parfois à des personnes. Tu les traites comme des données à protéger. Si tu dois surveiller des salariés ou des comptes nominatifs, applique la politique de ton organisation, l’information préalable et la proportionnalité attendues par le cadre légal."),
    takeaway("Les événements de session Windows se lisent en séquence, pas un par un. Le type d’ouverture, l’adresse source et le code d’échec changent totalement l’interprétation. Les comptes de service et les tâches planifiées expliquent beaucoup de bruit, mais une réussite inattendue après plusieurs échecs reste un pivot fort."),
    practice("Dans « TP 2 : journaux Windows : sessions, comptes et PowerShell », groupe les 4625 par source, relis une séquence 4625 puis 4624 puis 4672, et explique quels comptes relèvent d’un service, d’une tâche ou d’une session humaine avant le quiz."),
    reference("msEvent4624"),
    reference("msEvent4625"),
    reference("msLogonTypes"),
  ],
  quiz: {
    title: "Quiz : sessions et comptes Windows",
    questions: [
      questions.choice("Quel type d’ouverture de session correspond au Bureau à distance réussi ?", ["Type 3", "Type 5", "Type 10", "Type 11"], 2, "Le type 10 est « RemoteInteractive », utilisé par RDP. Le type 3 est un accès réseau, le type 5 un service et le type 11 une ouverture avec identifiants mis en cache.", "facile"),
      questions.choice("Que signifie le code « 0xC0000064 » dans un 4625 selon la documentation Microsoft ?", ["Le compte est verrouillé", "Le nom d’utilisateur n’existe pas", "Le mot de passe est correct", "La session est un service"], 1, "Ce code indique un nom d’utilisateur inexistant. Le code tentant à confondre est « 0xC000006A », qui décrit au contraire un nom correct avec un mauvais mot de passe.", "moyen"),
      questions.multi("Lis cet extrait : « 4624 svc-sync type 5 », « 4624 backup-local type 4 », « 4624 awa type 10 depuis 192.168.1.77 ». Quelles lectures sont raisonnables ? (plusieurs réponses)", ["« svc-sync » ressemble à une ouverture de service", "« backup-local » ressemble à une tâche planifiée", "La session « awa » mérite plus de contexte car elle est distante", "Les trois lignes prouvent la même attaque"], [0, 1, 2], "Le type 5 correspond à un service, le type 4 à un traitement par lot, et le type 10 à une session distante qui mérite un contrôle du contexte. Le raccourci faux est d’unifier trois comportements différents en une seule attaque.", "difficile"),
      questions.tf("Un 4672 indique qu’une nouvelle session a reçu des privilèges sensibles, mais il peut aussi apparaître lors d’une activité administrative légitime.", true, "Vrai : 4672 n’est pas un verdict. Il mérite surtout d’être corrélé avec le compte, la source, l’heure et les actions qui suivent pour distinguer administration normale et usage inattendu.", "moyen"),
    ],
  },
};

const sysmonPowerShellLesson: NewLesson = {
  key: "logs-sysmon-powershell",
  title: "Processus, Sysmon et PowerShell : reconstituer une exécution",
  summary: "Comprends ce que le journal Security ne montre pas toujours, ce que Sysmon ajoute, comment la journalisation PowerShell complète la vue, puis relie processus, DNS, réseau et fichier pour raconter une exécution.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer les limites de 4688, distinguer ce que Sysmon ajoute, relier des événements par « ProcessGuid », décoder une commande PowerShell encodée, reconnaître des parentés de processus suspectes, puis reconstituer une exécution en quatre étapes."),
    prerequisites("avoir suivi « Ouvertures de session et comptes : événements 4624, 4625, 4672 et 4720 »."),
    scenario("Moussa reçoit l’export d’un poste « atelier-pc » sur lequel un document Word a été ouvert juste avant un trafic réseau étrange. Le journal « Security » montre bien des ouvertures de session, mais pas assez de détails sur les processus. Moussa doit décider s’il lui faut Sysmon, les journaux PowerShell ou les deux pour raconter ce que le poste a exécuté."),
    videoSlot("Relier Word, PowerShell, DNS et réseau dans les traces Windows"),
    text("Le journal « Security » peut produire 4688 quand un processus démarre, mais la ligne de commande n’y apparaît que si la stratégie dédiée est activée. C’est utile, pas suffisant. Sysmon, lui, n’est pas présent par défaut : c’est un service à installer avec une configuration. Une fois actif, il écrit dans « Microsoft-Windows-Sysmon/Operational » et ajoute des détails précieux comme la ligne de commande complète, les hachages, les parents, les connexions réseau, les créations de fichiers, les chargements d’image, certaines actions sur le registre et les requêtes DNS."),
    schema([
      "Comparer les sources",
      "4688 Security   nouveau processus, selon la stratégie",
      "Sysmon 1        image, ligne de commande, parent, hachages",
      "Sysmon 3        connexion réseau liée au processus",
      "Sysmon 7        image chargée dans un processus",
      "Sysmon 8 et 10  thread distant ou accès à un processus",
      "Sysmon 11       fichier créé ou remplacé",
      "Sysmon 12 à 14  création, suppression ou modification du registre",
      "Sysmon 22       requête DNS liée au processus",
      "PowerShell 4103 journalisation de module",
      "PowerShell 4104 contenu d’un bloc de script si activée",
    ].join("\n")),
    text("Microsoft documente pour Sysmon l’intérêt de « ProcessGuid » : il reste stable pour la corrélation même si l’identifiant numérique du processus est réutilisé plus tard. C’est la clé idéale pour suivre une exécution de l’événement 1 vers l’événement 3 ou 22. Les champs utiles à retenir sont « Image », « CommandLine », « ParentImage », « ParentCommandLine », « User », « ProcessGuid », « QueryName », « QueryResults », « DestinationIp » et « DestinationPort ». Tu ne juges pas un seul champ : tu combines la parenté, le contexte utilisateur et la suite des actions."),
    text("Pour PowerShell, 4103 enregistre surtout l’activité du module et 4104 le texte des blocs de script quand la journalisation est activée. C’est précieux quand une commande a été passée via « -EncodedCommand ». Cette chaîne est du Base64 en UTF-16LE : tu peux la décoder localement avec PowerShell sans rejouer la commande. Attention : les journaux PowerShell et Sysmon peuvent contenir des secrets ou des chemins sensibles. On les protège comme n’importe quelle preuve."),
    text("Démonstration guidée : le fichier JSON lignes ci-dessous est inventé, mais il respecte le style d’une télémétrie exportée. La commande relit les événements 1, 3 et 22, puis décode la commande PowerShell encodée. L’intérêt n’est pas la charge utile, ici volontairement bénigne, mais la méthode de lecture : parent, DNS, réseau, puis fichier ou autre effet visible."),
    code([
      "# Relire des événements Sysmon exportés en JSON lignes",
      "$events = Get-Content .\\sysmon.jsonl | ForEach-Object { $_ | ConvertFrom-Json }",
      "$events | Where-Object { $_.EventID -in 1,3,22 } | ForEach-Object {",
      "  '{0} id={1} image={2} parent={3} dns={4} dst={5}:{6} guid={7}' -f $_.UtcTime, $_.EventID, $_.Image, $_.ParentImage, $_.QueryName, $_.DestinationIp, $_.DestinationPort, $_.ProcessGuid",
      "}",
      "$commandLine = ($events | Where-Object { $_.EventID -eq 1 -and $_.Image -like '*powershell.exe' } | Select-Object -First 1).CommandLine",
      "$encoded = [regex]::Match($commandLine, '(?i)(?:-EncodedCommand|-enc)\\s+([A-Za-z0-9+/=]+)').Groups[1].Value",
      "[Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($encoded))",
      "# exemple de sortie (valeurs fictives)",
      "# 2026-03-10 08:30:00.100 id=1 image=C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE parent=C:\\Windows\\explorer.exe dns= dst=: guid={11111111-1111-1111-1111-111111111111}",
      "# 2026-03-10 08:30:02.220 id=1 image=C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe parent=C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE dns= dst=: guid={22222222-2222-2222-2222-222222222222}",
      "# 2026-03-10 08:30:03.010 id=22 image=C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe parent= dns=cdn-status.example.org dst=: guid={22222222-2222-2222-2222-222222222222}",
      "# 2026-03-10 08:30:03.600 id=3 image=C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe parent= dns= dst=192.0.2.44:443 guid={22222222-2222-2222-2222-222222222222}",
      "# Get-ChildItem C:\\Users\\Public | Select-Object -First 3",
    ].join("\n"), "powershell"),
    schema([
      "Indices forts sans automatisme",
      "WINWORD.EXE -> powershell.exe     parenté inhabituelle",
      "powershell.exe -> requête DNS     pivot vers le domaine",
      "powershell.exe -> 192.0.2.44:443  pivot vers la connexion",
      "powershell.exe -> fichier temp    effet local observable",
    ].join("\n")),
    text("Certaines parentés attirent l’attention : un document Office qui lance « powershell.exe » ou « cmd.exe », ou un processus serveur web qui lance un interpréteur. Ce sont des indices, pas une preuve. Un administrateur peut avoir de bonnes raisons, un produit métier aussi. L’important est la chaîne complète : qui a lancé quoi, avec quelle ligne de commande, vers quel domaine, puis vers quelle adresse, et quel fichier ou autre artefact apparaît ensuite."),
    example("Exemple corrigé : tu peux raconter l’exécution fictive ainsi. Étape 1, « WINWORD.EXE » est ouvert par « awa ». Étape 2, il lance « powershell.exe » avec une commande encodée. Étape 3, ce même « ProcessGuid » effectue une requête DNS pour « cdn-status.example.org », puis une connexion HTTPS vers « 192.0.2.44 ». Étape 4, un fichier temporaire apparaît. Ce n’est pas une preuve suffisante d’infection à lui seul, mais c’est une chronologie nette qui justifie un pivot vers les journaux web, proxy ou EDR."),
    mistakes("attendre de Sysmon qu’il existe partout alors qu’il est absent par défaut ; confondre « ProcessId » et « ProcessGuid » lors d’une corrélation ; décoder une commande puis la réexécuter par curiosité ; oublier que les journaux de script peuvent contenir des secrets ou des données internes."),
    safety("Tu analyses seulement des exports autorisés de ta propre organisation. Ne lance jamais une commande encodée lue dans un journal sur une machine réelle pour « voir ce qu’elle fait ». Décode-la en texte, travaille sur une copie et conserve les exports comme des preuves sensibles."),
    takeaway("4688 donne un point de départ, Sysmon ajoute le détail, et la journalisation PowerShell peut révéler le contenu d’un script. Le meilleur pivot est souvent « ProcessGuid ». Une parenté inhabituelle attire l’attention, mais c’est la chaîne complète qui construit l’analyse."),
    practice("Dans « TP 2 : journaux Windows : sessions, comptes et PowerShell », relie un processus PowerShell à une requête DNS, une connexion réseau et une commande encodée décodée proprement, puis réponds au quiz."),
    reference("msEvent4688"),
    reference("msSysmon"),
    reference("msPsLogging"),
  ],
  quiz: {
    title: "Quiz : Sysmon et PowerShell",
    questions: [
      questions.choice("Quel champ Sysmon sert particulièrement bien à corréler plusieurs événements d’un même processus ?", ["Status", "ProcessGuid", "TargetDomainName", "EventRecordID"], 1, "Microsoft présente « ProcessGuid » comme une valeur stable pour relier les événements d’un même processus, même si l’identifiant numérique du processus est réutilisé plus tard. « EventRecordID » ordonné un journal, mais ne relie pas un processus à lui seul.", "facile"),
      questions.choice("Pourquoi 4688 ne suffit-il pas toujours pour comprendre une exécution PowerShell ?", ["Parce qu’il n’existe pas sur Windows 10", "Parce que la ligne de commande n’y figure que si la stratégie dédiée est activée", "Parce qu’il n’indique jamais le nom du processus parent", "Parce qu’il remplace tous les journaux PowerShell"], 1, "4688 peut être très utile, mais Microsoft précise que le champ de ligne de commande dépend de la stratégie d’audit. Le faux raccourci serait de croire qu’un seul événement Security remplace Sysmon et la journalisation PowerShell.", "moyen"),
      questions.multi("Lis cette séquence : « WINWORD.EXE -> powershell.exe », puis « Sysmon 22 QueryName=cdn-status.example.org », puis « Sysmon 3 DestinationIp=192.0.2.44:443 ». Quelles affirmations sont solides ? (plusieurs réponses)", ["PowerShell a été lancé par Word", "Le même processus a effectué une requête DNS puis une connexion réseau", "Le domaine seul prouve une compromission", "La chaîne mérite d’être corrélée avec d’autres sources"], [0, 1, 3], "La parenté et la corrélation par processus sont solides. En revanche, un seul domaine ou une seule connexion ne prouvent pas à eux seuls une attaque : il faut encore du contexte, des fichiers créés ou d’autres preuves concordantes.", "difficile"),
      questions.tf("Quand la journalisation des blocs de script est activée, PowerShell peut enregistrer le contenu des blocs de script qu’il traite.", true, "Vrai : c’est précisément l’intérêt de cette journalisation. Elle aide à comprendre ce qui a été traité, mais elle peut aussi exposer des données sensibles, donc il faut protéger ces journaux.", "moyen"),
    ],
  },
};

const webFormatLesson: NewLesson = {
  key: "logs-web-format",
  title: "Les journaux d’accès web : format, codes HTTP et agents utilisateurs",
  summary: "Décompose une ligne « combined », comprends ce qu’elle montre et ce qu’elle ne montre pas, puis compte les clients, les codes et les chemins les plus visibles avec des commandes simples.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("lire une ligne de journal d’accès web champ par champ, expliquer les familles de codes HTTP, reconnaître les limites du référent et de l’agent utilisateur, compter les requêtes par adresse et par code, puis distinguer le journal d’accès du journal d’erreurs."),
    prerequisites("avoir suivi « Lire un événement dans un journal »."),
    scenario("Fatou administre le site vitrine de la coopérative Harmattan. Le site répond encore, mais elle reçoit des plaintes sur des lenteurs et quelques erreurs aléatoires. Avant de parler d’attaque, elle veut lire le format des accès, voir quels clients parlent le plus, quels codes reviennent et si les erreurs viennent du client ou du serveur."),
    videoSlot("Lire un journal d’accès web sans se noyer"),
    text("Le format « combined », courant sur Apache et nginx, écrit une ligne par requête servie. Dans Apache, on le résume souvent par « %h %l %u %t \\\"%r\\\" %>s %b \\\"%{Referer}i\\\" \\\"%{User-Agent}i\\\" ». Dans nginx, le format prédéfini « combined » est « $remote_addr - $remote_user [$time_local] \\\"$request\\\" $status $body_bytes_sent \\\"$http_referer\\\" \\\"$http_user_agent\\\" ». On y voit l’adresse du client, l’identité éventuelle, la date, la requête HTTP, le code de statut, la taille du corps de réponse, le référent et l’agent utilisateur. Le champ Apache « %t » et la variable nginx « $time_local » gardent le fuseau horaire, par exemple « [10/Mar/2026:09:00:01 +0000] ». Avec Apache, « %b » écrit « - » quand aucun octet de corps n’est envoyé, alors que nginx « $body_bytes_sent » écrit un nombre. Le journal d’accès est écrit après la réponse : il te montre donc le résultat visible côté serveur web, pas le corps d’un « POST » ni tout le contexte applicatif."),
    schema([
      "192.168.1.20 - - [10/Mar/2026:09:00:01 +0000]",
      "\"GET / HTTP/1.1\" 200 5120 \"-\" \"Mozilla/5.0\"",
      "|__________|       |__________________________|",
      "adresse                 date et fuseau",
      "",
      "\"GET / HTTP/1.1\"  200  5120  référent  user-agent",
      "requête               code octets",
    ].join("\n")),
    text("Les familles de codes HTTP servent d’abord à classer. Les « 2xx » indiquent un succès, les « 3xx » une redirection, les « 4xx » une erreur côté client, par exemple 401 pour une requête non authentifiée, 403 pour un accès interdit, 404 pour une ressource introuvable et 429 pour trop de requêtes, et les « 5xx » une erreur côté serveur ou de passerelle, par exemple 500, 502 ou 503. Un 404 isolé n’est pas forcément grave. Une rafale de 404 sur des chemins très différents ou un groupe de 500 sur la même page raconte déjà autre chose."),
    text("Le référent et l’agent utilisateur sont utiles, mais falsifiables. Ils aident à comprendre un parcours ou à repérer un robot bruyant, pas à prouver l’identité d’une personne. Derrière un proxy inverse ou un CDN, l’adresse apparente peut être celle du proxy si la chaîne « X-Forwarded-For » n’est pas correctement traitée. Et si une requête est en « POST », le journal d’accès n’enregistre pas son corps : une erreur d’authentification applicative devra souvent être confirmée dans les journaux de l’application."),
    text("Démonstration guidée : avec un fichier « access.log » inventé, tu peux déjà produire un mini tableau de bord. Les commandes ci-dessous donnent les adresses les plus bavardes, les codes les plus fréquents, les chemins les plus demandés et la charge par minute. Elles tournent dans Git Bash et restent lisibles sur un poste Windows modeste."),
    code([
      "# Top des adresses, des codes et des chemins",
      "awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -5",
      "awk '{print $9}' access.log | sort | uniq -c | sort -n",
      "awk -F'\"' '{print $2}' access.log | awk '{print $2}' | sort | uniq -c | sort -rn | head -5",
      "awk '{gsub(/\\[/, \"\", $4); print substr($4,1,17)}' access.log | sort | uniq -c | sort -rn | head -5",
      "# exemple de sortie (valeurs fictives)",
      "#      10 192.168.1.77",
      "#       8 192.168.1.21",
      "#       7 192.168.1.44",
      "#       4 192.168.1.63",
      "#       4 192.168.1.30",
      "#",
      "#       1 403",
      "#       1 502",
      "#       1 503",
      "#       2 302",
      "#       2 429",
      "#       2 500",
      "#       3 404",
      "#       5 401",
      "#      24 200",
      "#",
      "#      10 /login",
      "#       4 /intranet",
      "#       4 /admin/login",
      "#       3 /profile",
      "#       3 /api/orders",
      "#",
      "#       9 10/Mar/2026:09:04",
      "#       7 10/Mar/2026:09:03",
      "#       6 10/Mar/2026:09:02",
    ].join("\n"), "bash"),
    schema([
      "Accès vs erreurs",
      "access.log   qui a demandé quoi, quand, avec quel code",
      "error.log    pourquoi le serveur ou le service a échoué",
      "",
      "Exemple :",
      "404 sur un chemin rare -> access.log d’abord",
      "500 répétés sur /intranet -> access.log puis error.log",
    ].join("\n")),
    text("Quand tu vois beaucoup de « 5xx », le journal d’erreurs devient indispensable, car lui seul dit souvent pourquoi le serveur a échoué. À l’inverse, pour mesurer un balayage de chemins ou un client bruyant, le journal d’accès suffit souvent. N’oublie jamais que ces journaux contiennent des adresses IP, parfois des identifiants dans l’URL et des habitudes de navigation : ils doivent être protégés, archivés avec prudence et partagés seulement si c’est nécessaire."),
    example("Exemple corrigé : dans l’extrait ci-dessus, « 192.168.1.77 » est le client le plus bavard, « /login » est la page la plus demandée, et « /admin/login » apparaît assez souvent pour mériter une lecture de séquence avec ses 401 puis son 200. Les « 500 », « 502 » et « 503 » concentrés sur « /intranet » racontent plutôt un problème côté service ou passerelle qu’un simple lien cassé."),
    mistakes("prendre le « User-Agent » pour une identité fiable ; oublier qu’un 200 peut être banal ou inquiétant selon le chemin ; conclure depuis le seul journal d’accès quand un « POST » ou une erreur applicative exige d’autres sources ; publier des journaux web complets alors qu’ils contiennent des données personnelles."),
    safety("Tu analyses les journaux de ton organisation ou d’un environnement d’exercice autorisé. Ne place jamais de secrets dans une URL, car ils se retrouveraient dans les journaux. Si tu partages un extrait, retire ce qui n’est pas nécessaire et garde la trace du fichier d’origine."),
    takeaway("Le format « combined » raconte l’adresse, la date, la requête, le code et quelques indices de contexte. Les familles de codes servent à trier, pas à juger seules. Le journal d’accès montre le résultat visible, tandis que le journal d’erreurs explique souvent le pourquoi."),
    practice("Dans « Intrusion web : du scan au webshell », commence par relire chaque ligne au format « combined », compte les 404, 401, 200 et 5xx, puis compare cette vue de format à la chronologie d’investigation déjà publiée avant le quiz."),
    reference("apacheLogConfig"),
    reference("nginxLog"),
    reference("mdnStatus"),
  ],
  quiz: {
    title: "Quiz : format des journaux web",
    questions: [
      questions.choice("Dans une ligne « combined », quel champ correspond en général au code HTTP final ?", ["Le premier champ", "Le champ juste après la requête entre guillemets", "Le référent", "L’agent utilisateur"], 1, "Dans le format usuel, le code suit immédiatement la requête entre guillemets, puis vient souvent la taille de la réponse. Le piège fréquent est de confondre ce code avec un élément du référent ou du navigateur.", "facile"),
      questions.choice("Pourquoi un journal d’accès ne suffit-il pas toujours pour comprendre un échec sur « POST /login » ?", ["Parce qu’il n’écrit jamais l’heure", "Parce qu’il n’enregistre pas le corps de la requête et peu de détails applicatifs", "Parce qu’il efface les requêtes en 401", "Parce qu’il remplace le journal d’erreurs"], 1, "Le journal d’accès montre qu’une requête a eu lieu et quel code elle a reçu, mais pas son corps ni toute la logique métier. Pour une authentification ratée, un journal applicatif complète souvent la lecture.", "moyen"),
      questions.multi("Lis cet extrait : « GET /admin/login 200 », puis « POST /admin/login 401 », puis « POST /admin/login 200 ». Quelles conclusions sont prudentes ? (plusieurs réponses)", ["La page d’authentification est accessible", "Une tentative d’authentification a d’abord échoué", "La réussite finale mérite du contexte supplémentaire", "La séquence prouve à elle seule une intrusion"], [0, 1, 2], "Cette séquence montre une page accessible, un échec puis une réussite, ce qui mérite une vérification du contexte du compte et du client. Elle ne prouve pas à elle seule une intrusion, car un utilisateur légitime peut aussi se tromper puis réussir.", "difficile"),
      questions.tf("L’agent utilisateur d’un client peut être falsifié, donc il aide à l’analyse sans suffire comme preuve d’identité.", true, "Vrai : un « User-Agent » donne des indices pratiques, mais il peut être modifié très facilement. Tu l’utilises comme un contexte parmi d’autres, pas comme une identité fiable.", "moyen"),
    ],
  },
};

const webAttacksLesson: NewLesson = {
  key: "logs-web-attaques",
  title: "Reconnaître scans, injections et force brute dans les accès web",
  summary: "Apprends à reconnaître dans les journaux d’accès les traces de balayage, de force brute, d’injection ou de traversée, puis à distinguer bruit opportuniste et séquence plus ciblée.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("reconnaître une rafale de 404 comme un balayage possible, distinguer une force brute d’un simple oubli de mot de passe, repérer dans les URL des indices d’injection SQL, de traversée ou de script, relier un succès probable à ce qui le précède, puis classer une séquence sans tirer de conclusion trop large."),
    prerequisites("avoir suivi « Les journaux d’accès web : format, codes HTTP et agents utilisateurs »."),
    scenario("Koffi doit relire les accès du site de Baobab Tech après un signalement : l’équipe a vu des pages d’administration consultées hors horaire et un fichier étrange dans un dossier de téléversement. Koffi n’a pas le droit de rejouer les URL, seulement de lire les traces. Son travail est donc de reconnaître des motifs dans les accès, puis de séparer le bruit opportuniste d’une séquence plus dangereuse."),
    videoSlot("Reconnaître une intrusion web sans rejouer l’attaque"),
    text("Dans un journal d’accès, beaucoup d’attaques se voient d’abord comme des motifs. Un scanner opportuniste enchaîne souvent des 404 sur des chemins connus comme « /admin », « /.env » ou « /.git/config ». Une force brute sur une page de connexion produit des « POST » répétés vers la même URL, avec des 401, 403 ou parfois des 200 et 302 selon l’application. Une injection SQL laisse souvent des signes dans l’URL : apostrophe encodée, « UNION SELECT », « OR 1=1 ». Une traversée de répertoires montre « ../ » ou son encodage en pourcentage."),
    schema([
      "Quelques signatures à reconnaître",
      "404 404 403 sur chemins sensibles   -> sondage ou scan",
      "POST /login répété + 401            -> brute force probable",
      "id=7%27 puis UNION SELECT           -> injection SQL à lire",
      "file=%2e%2e%2f...                   -> traversée de répertoires",
      "/uploads/rapport.php?cmd=...        -> appel d’un fichier téléversé",
    ].join("\n")),
    text("Le piège est de lire une seule URL comme une preuve. Une requête contenant « %27 » peut être un test isolé sans effet. Une requête vers « /admin », « /.env » ou un fichier téléversé prouve seulement que le serveur web a reçu cette demande et qu’il a répondu par tel code ; elle ne prouve ni une exécution de code, ni un vol de données à elle seule. Ce qui compte est la séquence : quels chemins ont été sondés avant, quel code est revenu, puis qu’est-ce qui a suivi. Un 200 ou un 302 sur un chemin d’administration juste après plusieurs échecs vaut davantage qu’un 404 isolé. De même, l’agent utilisateur « curl » ou « python-requests » est utile, mais pas définitif : il peut être falsifié ou tout simplement utilisé par un administrateur en test."),
    text("Démonstration guidée : le fichier ci-dessous contient douze accès inventés, tous au format réel. La première commande isole les lignes qui portent des indices d’injection, de traversée, de script ou d’appel d’un fichier téléversé. La seconde relit les réponses 200 et 302 pour chercher un succès probable après la phase de bruit ou de sondage."),
    code([
      "# Repérer des motifs web à vérifier",
      "grep -nEi '%27|UNION|%2e%2e|%3Cscript%3E|/uploads/.*\\.php\\?cmd=' access-attaque.log",
      "printf '\\nSucces probables\\n'",
      "awk '$9 ~ /200|302/ {print NR \":\" $0}' access-attaque.log",
      "# exemple de sortie (valeurs fictives)",
      "# 8:192.168.1.77 - - [10/Mar/2026:10:10:21 +0000] \"GET /report?id=7%27 HTTP/1.1\" 500 640 \"-\" \"curl/8.5.0\"",
      "# 9:192.168.1.77 - - [10/Mar/2026:10:10:24 +0000] \"GET /report?id=-1%20UNION%20SELECT%201,2 HTTP/1.1\" 200 840 \"-\" \"curl/8.5.0\"",
      "# 10:192.168.1.77 - - [10/Mar/2026:10:10:28 +0000] \"GET /download?file=%2e%2e%2f%2e%2e%2fwin.ini HTTP/1.1\" 403 220 \"-\" \"curl/8.5.0\"",
      "# 11:192.168.1.60 - - [10/Mar/2026:10:11:00 +0000] \"GET /uploads/rapport.php?cmd=REDACTED HTTP/1.1\" 200 128 \"https://example.org/uploads/fiche.pdf\" \"Mozilla/5.0\"",
      "# 12:192.168.1.60 - - [10/Mar/2026:10:11:04 +0000] \"GET /search?q=%3Cscript%3Ealert(1)%3C/script%3E HTTP/1.1\" 200 980 \"https://example.org/\" \"Mozilla/5.0\"",
      "#",
      "# Succes probables",
      "# 4:192.168.1.77 - - [10/Mar/2026:10:10:08 +0000] \"GET /admin/login HTTP/1.1\" 200 1180 \"-\" \"curl/8.5.0\"",
      "# 7:192.168.1.77 - - [10/Mar/2026:10:10:18 +0000] \"POST /admin/login HTTP/1.1\" 200 512 \"https://example.org/admin/login\" \"curl/8.5.0\"",
      "# 9:192.168.1.77 - - [10/Mar/2026:10:10:24 +0000] \"GET /report?id=-1%20UNION%20SELECT%201,2 HTTP/1.1\" 200 840 \"-\" \"curl/8.5.0\"",
      "# 11:192.168.1.60 - - [10/Mar/2026:10:11:00 +0000] \"GET /uploads/rapport.php?cmd=REDACTED HTTP/1.1\" 200 128 \"https://example.org/uploads/fiche.pdf\" \"Mozilla/5.0\"",
      "# 12:192.168.1.60 - - [10/Mar/2026:10:11:04 +0000] \"GET /search?q=%3Cscript%3Ealert(1)%3C/script%3E HTTP/1.1\" 200 980 \"https://example.org/\" \"Mozilla/5.0\"",
    ].join("\n"), "bash"),
    schema([
      "Scanner opportuniste vs attaque plus ciblée",
      "Opportuniste : beaucoup de chemins, peu ou pas de succès",
      "Ciblée      : moins de bruit, un succès, puis de nouveaux chemins",
      "",
      "Signal fort :",
      "404 404 403 200 sur /admin/login",
      "puis 200 sur /admin/export",
    ].join("\n")),
    text("Le succès final est souvent ce qui départage le bruit d’une séquence plus sérieuse. Un 200 sur « /admin/export » juste après plusieurs « POST /admin/login » vaut plus qu’un balayage de 404. De même, un appel à « /uploads/rapport.php?cmd=... » signale qu’un fichier téléversé exécutable a peut-être été appelé, mais ce journal ne te dit ni son contenu ni son impact exact. Tu devras pivoter vers les journaux applicatifs, système, ou vers une chronologie plus large."),
    text("Dans toutes ces lectures, reste défensif. Tu ne reproduis pas les charges vues dans les traces. Tu les reconnais seulement pour protéger ton système. Et tu rappelles que ces journaux contiennent des données personnelles et parfois des paramètres sensibles : ils restent internes, protégés et partagés seulement selon le besoin."),
    example("Exemple corrigé : la suite « 404, 404, 403, 200 sur /admin/login », puis « POST /admin/login 200 », puis « GET /admin/export 200 » se lit comme une exploration suivie d’une authentification probablement réussie et d’un accès à une ressource sensible. Ce n’est plus du simple bruit de scan. Il faut alors corréler avec l’application, les comptes et les autres journaux avant de mesurer l’impact."),
    mistakes("prendre toute rafale de 404 pour une compromission ; oublier qu’une application peut répondre 200 à une erreur métier ; traiter un « ?cmd= » comme une preuve définitive sans autre source ; recopier une URL d’attaque dans un navigateur de test au lieu de la lire comme une preuve."),
    safety("Tu reconnais des attaques uniquement dans les traces de tes propres systèmes ou d’un exercice autorisé. Tu ne rejoues pas les URL offensives vues dans les journaux contre un tiers. Travaille sur des copies locales et masque ce qui n’est pas nécessaire dans les extraits partagés."),
    takeaway("Les motifs comptent plus qu’une ligne isolée. Cherche la séquence complète : sondage, échec, succès probable, puis action sur une ressource sensible. Le code de réponse, le chemin et l’ordre temporel aident à distinguer bruit opportuniste et incident à investiguer."),
    practice("Dans « Intrusion web : du scan au webshell », repère le moment où le bruit devient une séquence crédible, note les 404, 401, 403, 200 et 302 utiles, puis compare ta lecture avec l’investigation détaillée avant le quiz."),
    reference("owaspBruteForce"),
    reference("owaspSqli"),
    reference("owaspPathTraversal"),
  ],
  quiz: {
    title: "Quiz : reconnaître une attaque web dans les accès",
    questions: [
      questions.choice("Quel motif évoque le plus un balayage de chemins ?", ["Des 404 en rafale sur des chemins connus", "Un seul 200 sur la page d’accueil", "Une image CSS chargée deux fois", "Un 304 sur un navigateur connu"], 0, "Une série rapide de 404 sur des chemins variés et sensibles ressemble à un scan ou à un sondage. Un 200 isolé sur la page d’accueil ou un 304 de cache n’a pas du tout la même portée.", "facile"),
      questions.choice("Dans un accès web, quel indice rend une suite d’échecs plus inquiétante qu’un simple scanner opportuniste ?", ["La présence d’un succès final sur une ressource sensible", "La présence d’un fuseau horaire dans la date", "Un agent utilisateur de navigateur courant", "Une taille de réponse inférieure à 1 ko"], 0, "Le succès final change la lecture : il montre que quelque chose a peut-être été obtenu. Le piège est de se concentrer sur la taille ou le navigateur déclaré, qui donnent du contexte mais ne valent pas un pivot aussi fort.", "moyen"),
      questions.multi("Lis ces lignes : « /report?id=7%27 -> 500 », puis « /report?id=-1%20UNION%20SELECT%201,2 -> 200 », puis « /download?file=%2e%2e%2f%2e%2e%2fwin.ini -> 403 ». Quelles affirmations sont prudentes ? (plusieurs réponses)", ["La première ligne ressemble à un test d’injection SQL", "La deuxième mérite une vérification attentive car elle obtient un 200", "La troisième évoque une traversée de répertoires", "L’ensemble prouve à lui seul une exfiltration réussie"], [0, 1, 2], "Les trois lignes montrent des motifs typiques à reconnaître. En revanche, parler déjà d’exfiltration réussie serait trop loin : il te manque encore des preuves sur les données lues, la suite de la session et les autres journaux.", "difficile"),
      questions.tf("Un « User-Agent » comme « curl » ou « python-requests » est un indice utile, mais il peut être falsifié.", true, "Vrai : beaucoup d’outils exposent leur nom, mais rien n’empêche un acteur de mentir dans ce champ. Tu l’utilises comme un indice pratique, jamais comme une preuve d’identité.", "moyen"),
    ],
  },
};

const applicationLogsLesson: NewLesson = {
  key: "logs-applicatifs",
  title: "Journaux applicatifs et bases de données : ce qu’il faut y chercher",
  summary: "Lis des journaux applicatifs structurés, cherche les événements métier qui comptent, relie une requête web à l’application puis à la base, et évite les fuites de secrets dans les traces.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("reconnaître un journal applicatif structuré, expliquer ce qu’une application devrait ou ne devrait jamais journaliser, filtrer du JSON lignes avec « jq » et PowerShell, relier un identifiant de requête à plusieurs sources, puis repérer des signes utiles côté base de données."),
    prerequisites("avoir suivi « Les journaux d’accès web : format, codes HTTP et agents utilisateurs »."),
    scenario("Ama maintient une petite API qui alimente le site de Cabinet Moussa. Le journal web montre des exports et des erreurs 500, mais Ama veut savoir quel compte applicatif était concerné, quelle requête a échoué et si la base de données a vu la même histoire. Elle doit donc passer du serveur web aux journaux applicatifs, puis au journal de base."),
    videoSlot("Relier une requête web, l’application et la base de données"),
    text("Les journaux applicatifs parlent le langage du métier. Là où le serveur web voit une URL et un code, l’application peut écrire « login failed », « rôle changed », « export started » ou « password reset requested ». Le format le plus pratique pour les outils est souvent le JSON lignes : un objet JSON par ligne. C’est facile à filtrer, à grouper et à corréler, à condition que chaque ligne garde des champs stables comme l’heure, le niveau, le service, l’identifiant de requête et, si besoin, l’utilisateur ou l’adresse source. Les niveaux les plus courants restent « DEBUG », « INFO », « WARN », « ERROR » et parfois « FATAL » : ils aident à trier, pas à conclure seuls."),
    schema([
      "Exemple JSON lignes",
      "{\"ts\":\"2026-03-10T10:30:24Z\",\"level\":\"error\",",
      "\"service\":\"api\",\"request_id\":\"req-1005\",",
      "\"user\":\"awa\",\"ip\":\"192.168.1.77\",",
      "\"msg\":\"export started\",\"rows\":850}",
    ].join("\n")),
    text("Ce qu’une application devrait journaliser : authentifications réussies ou échouées, changements de droits, exports massifs, erreurs récurrentes, accès à des données sensibles, identifiants de corrélation. Ce qu’elle ne doit jamais journaliser : mots de passe, jetons, clés, numéros complets de carte, ou tout autre secret complet. L’OWASP insiste aussi sur un point discret mais important : empêcher l’injection dans les journaux, par exemple des retours à la ligne forgés qui casseraient le format ou tromperaient un analyste."),
    text("Côté base de données, tu cherches surtout des échecs de connexion, des requêtes lentes, des connexions depuis une machine inattendue et des volumes anormaux. Le journal applicatif te dira souvent « qui » au sens métier, tandis que le journal de base te dira plutôt « quel client », « quelle durée » ou « quel refus ». Les deux se complètent, surtout si un même « request_id » ou un même horodatage relie les sources."),
    text("Démonstration guidée : sur Windows, « jq » n’est pas installé chez tout le monde, donc tu montres les deux chemins. Le premier filtre une requête précise avec « jq » via un petit fichier de filtre, plus robuste que des guillemets fragiles dans PowerShell 5.1. Le second relit la même requête « req-1005 » en PowerShell pour reconstituer un export, une ouverture de connexion base, une requête lente puis un refus d’accès. La méthode est reproductible et n’envoie rien vers un service tiers."),
    code([
      "# Filtrer une requête précise avec jq",
      "@'",
      "select(.request_id==\"req-1005\") | \"\\(.ts)\\t\\(.service)\\t\\(.request_id)\\t\\(.msg)\"",
      "'@ | Out-File .\\req-1005.jq -Encoding ascii",
      "$env:TEMP\\tools\\jq.exe -r -f .\\req-1005.jq .\\app.jsonl",
      "# exemple de sortie (valeurs fictives)",
      "# 2026-03-10T10:30:22Z\tapi\treq-1005\tlogin ok",
      "# 2026-03-10T10:30:23Z\tapi\treq-1005\trole changed",
      "# 2026-03-10T10:30:24Z\tapi\treq-1005\texport started",
      "# 2026-03-10T10:30:26Z\tapi\treq-1005\texport completed",
      "# 2026-03-10T10:30:27Z\tdb\treq-1005\tconnection opened",
      "# 2026-03-10T10:30:28Z\tdb\treq-1005\tslow query",
      "# 2026-03-10T10:30:29Z\tdb\treq-1005\taccess denied for user report",
      "",
      "# Reconstituer une requête précise en PowerShell",
      "Get-Content .\\app.jsonl | ForEach-Object { $_ | ConvertFrom-Json } |",
      "  Where-Object { $_.request_id -eq 'req-1005' } |",
      "  ForEach-Object {",
      "    '{0} service={1} user={2} client={3}{4} msg={5} rows={6} bytes={7} duration_ms={8}' -f $_.ts, $_.service, $_.user, $_.client, $(if ($_.ip) {\" ip=$($_.ip)\"} else {''}), $_.msg, $_.rows, $_.bytes, $_.duration_ms",
      "  }",
      "# exemple de sortie (valeurs fictives)",
      "# 2026-03-10T10:30:22Z service=api user=awa client= ip=192.168.1.77 msg=login ok rows= bytes= duration_ms=",
      "# 2026-03-10T10:30:23Z service=api user=awa client= ip=192.168.1.77 msg=role changed rows= bytes= duration_ms=",
      "# 2026-03-10T10:30:24Z service=api user=awa client= ip=192.168.1.77 msg=export started rows=850 bytes= duration_ms=",
      "# 2026-03-10T10:30:26Z service=api user=awa client= ip=192.168.1.77 msg=export completed rows=850 bytes=1843200 duration_ms=",
      "# 2026-03-10T10:30:27Z service=db user= client=192.168.1.12 msg=connection opened rows= bytes= duration_ms=",
      "# 2026-03-10T10:30:28Z service=db user= client=192.168.1.12 msg=slow query rows= bytes= duration_ms=4120",
      "# 2026-03-10T10:30:29Z service=db user= client=192.168.1.12 msg=access denied for user report rows= bytes= duration_ms=",
    ].join("\n"), "powershell"),
    schema([
      "Trois sources pour un même incident",
      "access.log      POST /login 302 puis /admin/export 200",
      "app.jsonl       request_id=req-1005, rôle changed, export",
      "db log          connection opened, slow query, access denied",
    ].join("\n")),
    text("Le grand intérêt du « request_id » est là : il relie l’accès web à la logique métier puis à l’effet côté base. Sans identifiant commun, tu es condamné à rapprocher seulement par heure et par adresse, ce qui est moins robuste. Si ton application n’écrit pas encore cet identifiant, c’est souvent l’une des améliorations les plus rentables à demander."),
    text("Rappelle-toi enfin que ces journaux sont très sensibles. Ils peuvent contenir des adresses IP, des noms de comptes, des chemins de fichiers, parfois des erreurs qui révèlent l’architecture. Tu les protèges, tu les minimises, et tu n’envoies jamais un extrait interne complet vers un service en ligne si tu n’as pas l’autorisation et le besoin réel."),
    example("Exemple corrigé : si le web montre un « POST /login 302 », puis l’application écrit « login ok », « rôle changed » et « export completed » pour « req-1005 », tandis que la base voit une requête lente puis « access denied for user report », tu peux raconter un incident cohérent : une session a réussi, un rôle a changé, un export a été lancé, puis la base a refusé une action supplémentaire. Le croisement évite de surinterpréter un seul « 500 » ou un seul « 200 »."),
    mistakes("journaliser des secrets complets dans l’application ; écrire du JSON lignes sans identifiant de corrélation ; croire qu’un « 500 » seul suffit sans relire l’application et la base ; oublier qu’un retour à la ligne injecté peut casser la lecture du journal."),
    safety("Les journaux applicatifs et de base de données contiennent souvent des données personnelles et des détails d’architecture. Tu les gardes dans ton périmètre autorisé, tu retires les éléments inutiles avant partage et tu évites tout envoi vers un service tiers sans validation explicite."),
    takeaway("Le journal applicatif explique l’intention métier, la base de données montre souvent l’effet technique, et le journal web donne la porte d’entrée. Un identifiant de corrélation les rend bien plus utiles. Aucun secret complet ne doit finir dans ces traces."),
    practice("Dans « Intrusion web : du scan au webshell », relis d’abord la chronologie web, puis transpose la même méthode à un journal applicatif : cherche quel identifiant de requête, quel compte et quel export tu voudrais retrouver, puis termine par le quiz."),
    reference("owaspLogging"),
    reference("jqManual"),
    reference("msConvertFromJson"),
  ],
  quiz: {
    title: "Quiz : journaux applicatifs et base de données",
    questions: [
      questions.choice("Quel champ rend la corrélation entre le web, l’application et la base beaucoup plus robuste ?", ["La couleur du thème de l’application", "Un identifiant de requête ou de corrélation", "Le fuseau du navigateur uniquement", "Le seul nom du serveur"], 1, "Un identifiant de requête suit la même action d’une source à l’autre et évite de corréler seulement à l’heure. Le nom du serveur ou le fuseau aident, mais ils ne remplacent pas un pivot aussi précis.", "facile"),
      questions.choice("Quel élément ne devrait jamais être journalisé en clair dans une application ?", ["Un niveau comme INFO ou ERROR", "Un mot de passe ou un jeton complet", "Un identifiant de requête", "Le nom logique d’un service"], 1, "Les secrets complets ne doivent pas se retrouver dans les journaux, car ces fichiers circulent, se sauvegardent et se consultent par plusieurs personnes. Un niveau ou un identifiant de requête, au contraire, sont utiles à l’analyse.", "moyen"),
      questions.multi("Lis cette séquence applicative : « login ok », « rôle changed », « export started », « export completed », puis côté base « slow query » et « access denied ». Quelles lectures sont prudentes ? (plusieurs réponses)", ["Une action importante a été menée après l’authentification", "Le même « request_id » aide à relier les sources", "Le refus côté base peut compléter l’histoire métier", "La seule présence d’une requête lente prouve une injection SQL"], [0, 1, 2], "La séquence montre une action authentifiée suivie d’un export et d’effets côté base, ce qui construit une histoire cohérente. En revanche, une requête lente seule ne prouve pas une injection SQL : elle peut avoir bien d’autres causes.", "difficile"),
      questions.tf("Sur Windows, si « jq » n’est pas disponible chez l’apprenant, PowerShell peut relire du JSON lignes via « ConvertFrom-Json » ligne par ligne.", true, "Vrai : c’est une alternative pratique et déjà présente sur beaucoup de postes Windows. Elle permet de rester autonome sans ajouter d’outil, même si « jq » reste très confortable pour certains filtres.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c6:5",
    position: 3,
    title: "Journaux Windows",
    description: "Ce module t’apprend à lire les événements Windows sans te perdre dans l’interface : choisir le bon journal, comprendre ce que la stratégie d’audit produit, puis relier sessions, comptes, processus, DNS, réseau et PowerShell. Critères de réussite : filtrer un export Windows de façon reproductible, relire une séquence 4625 puis 4624 avec ses types et ses codes, et reconstituer une exécution en reliant Sysmon et PowerShell par leurs champs communs.",
    lessons: [windowsEventsLesson, windowsSessionsLesson, sysmonPowerShellLesson],
  },
  {
    key: "c6:6",
    position: 4,
    title: "Journaux web et applications",
    description: "Ce module te donne une lecture complète des traces web et métier : format des accès, signaux d’attaque visibles, puis confirmation par les journaux applicatifs et de base de données. Critères de réussite : décomposer une ligne « combined », distinguer bruit et succès probable dans une séquence web, et raconter un incident à partir d’un journal d’accès, d’un « request_id » applicatif et d’un effet côté base.",
    lessons: [webFormatLesson, webAttacksLesson, applicationLogsLesson],
  },
];
