// Authoring kit shared by the pedagogical paths written after the first Réseaux path: block helpers,
// the lesson template and the list of references authors may cite. Every address below was fetched and
// answered 200 when the list was built; the tests check that lessons only cite addresses from this list.
// Read by scripts/seed-path-builder.cjs through scripts/ts-loader.cjs, so it must stay free of imports.

export type Difficulty = "facile" | "moyen" | "difficile";
export type BlockType = "text" | "heading" | "schema" | "code" | "example" | "callout" | "resource" | "image" | "video";

export interface PathBlock { type: BlockType; content: string; language?: string; url?: string }
export interface PathQuestion {
  type: "single_choice" | "multiple_choice" | "true_false";
  prompt: string;
  options: string[];
  correct: number | number[];
  explanation: string;
  difficulty: Difficulty;
}
export interface PathQuiz { title: string; questions: PathQuestion[] }
export interface NewLesson {
  key: string;
  title: string;
  summary: string;
  minutes: number;
  xp: number;
  blocks: PathBlock[];
  quiz?: PathQuiz;
  /** The lesson already exists as starter content: its text is replaced only while it is still untouched. */
  upgrade?: boolean;
  /**
   * For an upgraded starter lesson that keeps its quiz: `improve[i]` replaces the explanation of the i-th starter
   * question (only while it still carries the starter text) and `add` appends questions after the existing ones.
   */
  quizExtension?: { improve: string[]; add: PathQuestion[] };
}
/** A lesson published earlier that this path only moves to the right module and position (and may give a quiz). */
export interface ExistingLesson { key: string; existing: true; quiz?: PathQuiz }
export type PathLessonEntry = NewLesson | ExistingLesson;
export interface PathModuleEntry {
  key: string;
  position?: number;
  title: string;
  description: string;
  /** The module already exists: it is renamed only while it still carries this title. */
  existing?: { fromTitle: string };
  lessons: PathLessonEntry[];
}

export const isExistingLesson = (entry: PathLessonEntry): entry is ExistingLesson => "existing" in entry;

// --- Blocks -------------------------------------------------------------------------------------

export const text = (content: string): PathBlock => ({ type: "text", content });
export const heading = (content: string): PathBlock => ({ type: "heading", content });
export const schema = (content: string): PathBlock => ({ type: "schema", content });
export const code = (content: string, language = "text"): PathBlock => ({ type: "code", content, language });
export const example = (content: string): PathBlock => ({ type: "example", content });
export const callout = (content: string): PathBlock => ({ type: "callout", content });

// The renderer labels a callout from its first words (see parseCallout in lib/lesson-content.ts).
export const goals = (content: string): PathBlock => callout(`Objectifs : ${content}`);
export const prerequisites = (content: string): PathBlock => callout(`Prérequis : ${content}`);
export const scenario = (content: string): PathBlock => callout(`Mise en situation : ${content}`);
export const mistakes = (content: string): PathBlock => callout(`Erreurs fréquentes : ${content}`);
export const safety = (content: string): PathBlock => callout(`Sécurité : ${content}`);
export const takeaway = (content: string): PathBlock => callout(`À retenir : ${content}`);
export const practice = (content: string): PathBlock => callout(`Pour pratiquer : ${content}`);
/** A video the team has not published yet: the renderer shows an honest "en préparation" frame. */
export const videoSlot = (title: string): PathBlock => callout(`Vidéo à venir : ${title}`);

// --- References ---------------------------------------------------------------------------------

export const REFERENCES = {
  // Standards (English).
  rfc791: { title: "RFC 791 : Internet Protocol (IPv4)", url: "https://www.rfc-editor.org/rfc/rfc791", lang: "en" },
  rfc8200: { title: "RFC 8200 : Internet Protocol, Version 6 (IPv6)", url: "https://www.rfc-editor.org/rfc/rfc8200", lang: "en" },
  rfc4291: { title: "RFC 4291 : architecture d’adressage IPv6", url: "https://www.rfc-editor.org/rfc/rfc4291", lang: "en" },
  rfc4861: { title: "RFC 4861 : Neighbor Discovery pour IPv6", url: "https://www.rfc-editor.org/rfc/rfc4861", lang: "en" },
  rfc4862: { title: "RFC 4862 : autoconfiguration d’adresse sans état (SLAAC)", url: "https://www.rfc-editor.org/rfc/rfc4862", lang: "en" },
  rfc5952: { title: "RFC 5952 : écriture recommandée des adresses IPv6", url: "https://www.rfc-editor.org/rfc/rfc5952", lang: "en" },
  rfc8415: { title: "RFC 8415 : DHCPv6", url: "https://www.rfc-editor.org/rfc/rfc8415", lang: "en" },
  rfc1918: { title: "RFC 1918 : adresses IPv4 privées", url: "https://www.rfc-editor.org/rfc/rfc1918", lang: "en" },
  rfc4632: { title: "RFC 4632 : CIDR", url: "https://www.rfc-editor.org/rfc/rfc4632", lang: "en" },
  rfc826: { title: "RFC 826 : Address Resolution Protocol (ARP)", url: "https://www.rfc-editor.org/rfc/rfc826", lang: "en" },
  rfc9293: { title: "RFC 9293 : Transmission Control Protocol (TCP)", url: "https://www.rfc-editor.org/rfc/rfc9293", lang: "en" },
  rfc768: { title: "RFC 768 : User Datagram Protocol (UDP)", url: "https://www.rfc-editor.org/rfc/rfc768", lang: "en" },
  rfc792: { title: "RFC 792 : Internet Control Message Protocol (ICMP)", url: "https://www.rfc-editor.org/rfc/rfc792", lang: "en" },
  rfc4443: { title: "RFC 4443 : ICMPv6", url: "https://www.rfc-editor.org/rfc/rfc4443", lang: "en" },
  rfc1034: { title: "RFC 1034 : concepts du DNS", url: "https://www.rfc-editor.org/rfc/rfc1034", lang: "en" },
  rfc1035: { title: "RFC 1035 : mise en œuvre du DNS", url: "https://www.rfc-editor.org/rfc/rfc1035", lang: "en" },
  rfc2131: { title: "RFC 2131 : Dynamic Host Configuration Protocol (DHCP)", url: "https://www.rfc-editor.org/rfc/rfc2131", lang: "en" },
  rfc3022: { title: "RFC 3022 : NAT traditionnel", url: "https://www.rfc-editor.org/rfc/rfc3022", lang: "en" },
  rfc5905: { title: "RFC 5905 : Network Time Protocol version 4", url: "https://www.rfc-editor.org/rfc/rfc5905", lang: "en" },
  rfc9110: { title: "RFC 9110 : sémantique HTTP", url: "https://www.rfc-editor.org/rfc/rfc9110", lang: "en" },
  rfc8446: { title: "RFC 8446 : TLS 1.3", url: "https://www.rfc-editor.org/rfc/rfc8446", lang: "en" },
  rfc2328: { title: "RFC 2328 : OSPF version 2", url: "https://www.rfc-editor.org/rfc/rfc2328", lang: "en" },
  rfc2453: { title: "RFC 2453 : RIP version 2", url: "https://www.rfc-editor.org/rfc/rfc2453", lang: "en" },
  rfc5424: { title: "RFC 5424 : protocole Syslog", url: "https://www.rfc-editor.org/rfc/rfc5424", lang: "en" },
  rfc2827: { title: "RFC 2827 : filtrage d’entrée contre l’usurpation d’adresse (BCP 38)", url: "https://www.rfc-editor.org/rfc/rfc2827", lang: "en" },
  // Registries.
  ianaPorts: { title: "IANA : registre des noms de service et numéros de port", url: "https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml", lang: "en" },
  ianaIpv6: { title: "IANA : espace d’adressage IPv6", url: "https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xhtml", lang: "en" },
  ianaIpv4Special: { title: "IANA : adresses IPv4 à usage spécial", url: "https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml", lang: "en" },
  ianaIpv6Special: { title: "IANA : adresses IPv6 à usage spécial", url: "https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml", lang: "en" },
  // Tools and vendor documentation.
  wiresharkGuide: { title: "Wireshark : guide de l’utilisateur", url: "https://www.wireshark.org/docs/wsug_html_chunked/", lang: "en" },
  wiresharkFilters: { title: "Wireshark : référence des filtres d’affichage", url: "https://www.wireshark.org/docs/dfref/", lang: "en" },
  nmapMan: { title: "Nmap : manuel de référence", url: "https://nmap.org/book/man.html", lang: "en" },
  netacad: { title: "Cisco Networking Academy : cours gratuits", url: "https://www.netacad.com/", lang: "fr" },
  packetTracer: { title: "Cisco Packet Tracer : télécharger et apprendre", url: "https://www.netacad.com/cisco-packet-tracer", lang: "fr" },
  pythonIpaddress: { title: "Python : le module ipaddress", url: "https://docs.python.org/fr/3/library/ipaddress.html", lang: "fr" },
  man7Ip: { title: "Linux : manuel de la commande ip", url: "https://man7.org/linux/man-pages/man8/ip.8.html", lang: "en" },
  msIpconfig: { title: "Microsoft : la commande ipconfig", url: "https://learn.microsoft.com/fr-fr/windows-server/administration/windows-commands/ipconfig", lang: "fr" },
  msPing: { title: "Microsoft : la commande ping", url: "https://learn.microsoft.com/fr-fr/windows-server/administration/windows-commands/ping", lang: "fr" },
  msNslookup: { title: "Microsoft : la commande nslookup", url: "https://learn.microsoft.com/fr-fr/windows-server/administration/windows-commands/nslookup", lang: "fr" },
  msTracert: { title: "Microsoft : la commande tracert", url: "https://learn.microsoft.com/fr-fr/windows-server/administration/windows-commands/tracert", lang: "fr" },
  msArp: { title: "Microsoft : la commande arp", url: "https://learn.microsoft.com/fr-fr/windows-server/administration/windows-commands/arp", lang: "fr" },
  // The web.
  mdnHttp: { title: "MDN : aperçu de HTTP", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Overview", lang: "fr" },
  mdnMethods: { title: "MDN : les méthodes de requête HTTP", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Methods", lang: "fr" },
  mdnStatus: { title: "MDN : les codes de statut HTTP", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Status", lang: "fr" },
  mdnHeaders: { title: "MDN : les en-têtes HTTP", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers", lang: "fr" },
  mdnCookies: { title: "MDN : les cookies HTTP", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Guides/Cookies", lang: "fr" },
  mdnCors: { title: "MDN : le partage des ressources entre origines (CORS)", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Guides/CORS", lang: "fr" },
  mdnTls: { title: "MDN : Transport Layer Security", url: "https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Transport_Layer_Security", lang: "en" },
  // Security guidance.
  nistFirewalls: { title: "NIST SP 800-41 : guide des pare-feu et de la politique de filtrage", url: "https://csrc.nist.gov/pubs/sp/800/41/r1/final", lang: "en" },
  nistWlan: { title: "NIST SP 800-153 : sécuriser les réseaux sans fil", url: "https://csrc.nist.gov/pubs/sp/800/153/final", lang: "en" },
  nistNice: { title: "NIST : référentiel NICE des compétences en cybersécurité", url: "https://www.nist.gov/itl/applied-cybersecurity/nice/nice-framework-resource-center", lang: "en" },
  nistCsf: { title: "NIST : cadre de cybersécurité (CSF)", url: "https://www.nist.gov/cyberframework", lang: "en" },
  anssiFiltrage: { title: "ANSSI : définir une politique de filtrage réseau d’un pare-feu", url: "https://messervices.cyber.gouv.fr/guides/recommandations-pour-la-definition-dune-politique-de-filtrage-reseau-dun-pare-feu", lang: "fr" },
  anssiPareFeux: { title: "ANSSI : choisir des pare-feux maîtrisés dans les zones exposées à Internet", url: "https://messervices.cyber.gouv.fr/guides/recommandations-pour-choisir-des-pare-feux-maitrises-dans-les-zones-exposees-internet", lang: "fr" },
  anssiNettoyage: { title: "ANSSI : nettoyer une politique de filtrage réseau", url: "https://messervices.cyber.gouv.fr/guides/recommandations-et-methodologie-pour-le-nettoyage-dune-politique-de-filtrage-reseau", lang: "fr" },
  anssiWifi: { title: "ANSSI : recommandations de sécurité relatives aux réseaux Wi-Fi", url: "https://messervices.cyber.gouv.fr/guides/recommandations-de-securite-relatives-aux-reseaux-wi-fi", lang: "fr" },
  anssiHygiene: { title: "ANSSI : guide d’hygiène informatique", url: "https://cyber.gouv.fr/publications/guide-dhygiene-informatique", lang: "fr" },
  anssiLinux: { title: "ANSSI : recommandations de sécurité relatives à un système GNU/Linux", url: "https://cyber.gouv.fr/publications/recommandations-de-securite-relatives-un-systeme-gnulinux", lang: "fr" },
  // Fondamentaux : hygiène numérique, authentification, données et incidents.
  cybermalveillance: { title: "Cybermalveillance.gouv.fr : prévention et assistance aux victimes", url: "https://www.cybermalveillance.gouv.fr/", lang: "fr" },
  cmHameconnage: { title: "Cybermalveillance.gouv.fr : fiche réflexe contre l’hameçonnage", url: "https://www.cybermalveillance.gouv.fr/tous-nos-contenus/fiches-reflexes/hameconnage-phishing", lang: "fr" },
  cmRancongiciels: { title: "Cybermalveillance.gouv.fr : fiche réflexe contre les rançongiciels", url: "https://www.cybermalveillance.gouv.fr/tous-nos-contenus/fiches-reflexes/rancongiciels-ransomwares", lang: "fr" },
  cmSauvegardes: { title: "Cybermalveillance.gouv.fr : effectuer des sauvegardes régulières", url: "https://www.cybermalveillance.gouv.fr/tous-nos-contenus/bonnes-pratiques/sauvegardes", lang: "fr" },
  cmMisesAJour: { title: "Cybermalveillance.gouv.fr : faire les mises à jour de sécurité", url: "https://www.cybermalveillance.gouv.fr/tous-nos-contenus/bonnes-pratiques/mises-a-jour", lang: "fr" },
  cmMotsDePasse: { title: "Cybermalveillance.gouv.fr : bien gérer ses mots de passe", url: "https://www.cybermalveillance.gouv.fr/tous-nos-contenus/bonnes-pratiques/mots-de-passe", lang: "fr" },
  cmAntivirus: { title: "Cybermalveillance.gouv.fr : utiliser un antivirus", url: "https://www.cybermalveillance.gouv.fr/tous-nos-contenus/bonnes-pratiques/antivirus", lang: "fr" },
  cnilMotsDePasse: { title: "CNIL : mots de passe, les recommandations pour maîtriser sa sécurité", url: "https://www.cnil.fr/fr/mots-de-passe-recommandations-pour-maitriser-sa-securite", lang: "fr" },
  cnilPostes: { title: "CNIL : sécuriser les postes de travail", url: "https://www.cnil.fr/fr/securite-securiser-les-postes-de-travail", lang: "fr" },
  cnilViolations: { title: "CNIL : les violations de données personnelles, les règles à suivre", url: "https://www.cnil.fr/fr/violations-de-donnees-personnelles-les-regles-suivre", lang: "fr" },
  cnilRgpd: { title: "CNIL : comprendre le RGPD", url: "https://www.cnil.fr/fr/comprendre-le-rgpd", lang: "fr" },
  cnilRgpdEssentiel: { title: "CNIL : le RGPD, de quoi parle-t-on ?", url: "https://www.cnil.fr/fr/rgpd-de-quoi-parle-t-on", lang: "fr" },
  cnilDroits: { title: "CNIL : les droits pour maîtriser ses données personnelles", url: "https://www.cnil.fr/fr/mes-demarches/les-droits-pour-maitriser-vos-donnees-personnelles", lang: "fr" },
  cnilSauvegarder: { title: "CNIL : sécurité, sauvegarder", url: "https://www.cnil.fr/fr/securite-sauvegarder", lang: "fr" },
  cnilAuthentifier: { title: "CNIL : sécurité, authentifier les utilisateurs", url: "https://www.cnil.fr/fr/securite-authentifier-les-utilisateurs", lang: "fr" },
  anssiMfa: { title: "ANSSI : recommandations relatives à l’authentification multifacteur et aux mots de passe", url: "https://messervices.cyber.gouv.fr/guides/recommandations-relatives-lauthentification-multifacteur-et-aux-mots-de-passe", lang: "fr" },
  anssiEbios: { title: "ANSSI : la méthode EBIOS Risk Manager", url: "https://cyber.gouv.fr/securisation/analyse-des-risques/methode-ebios-rm/", lang: "fr" },
  anssiPortail: { title: "ANSSI : le portail de la cybersécurité", url: "https://cyber.gouv.fr/", lang: "fr" },
  effSsd: { title: "EFF : guide d’autodéfense contre la surveillance", url: "https://ssd.eff.org/fr", lang: "fr" },
  hibp: { title: "Have I Been Pwned : vérifier si une adresse figure dans une fuite", url: "https://haveibeenpwned.com/", lang: "en" },
  hibpPasswords: { title: "Have I Been Pwned : vérifier un mot de passe sans le révéler", url: "https://haveibeenpwned.com/Passwords", lang: "en" },
  nistIncident: { title: "NIST SP 800-61 : guide de gestion des incidents de sécurité", url: "https://csrc.nist.gov/pubs/sp/800/61/r2/final", lang: "en" },
  nistAuth: { title: "NIST SP 800-63B : lignes directrices sur l’authentification", url: "https://pages.nist.gov/800-63-3/sp800-63b.html", lang: "en" },
  nistSmallBusiness: { title: "NIST : ressources de cybersécurité pour les petites entreprises", url: "https://www.nist.gov/itl/smallbusinesscyber", lang: "en" },
  auMalabo: { title: "Union africaine : Convention de Malabo sur la cybersécurité et la protection des données personnelles", url: "https://au.int/en/treaties/african-union-convention-cyber-security-and-personal-data-protection", lang: "en" },
  msBitlocker: { title: "Microsoft : BitLocker, chiffrement des disques", url: "https://learn.microsoft.com/fr-fr/windows/security/operating-system-security/data-protection/bitlocker/", lang: "fr" },
  letsEncrypt: { title: "Let’s Encrypt : comment ça marche", url: "https://letsencrypt.org/fr/how-it-works/", lang: "fr" },
  cisaRansomware: { title: "CISA : arrêter les rançongiciels", url: "https://www.cisa.gov/stopransomware", lang: "en" },
  cisaSecureOurWorld: { title: "CISA : Secure Our World, les gestes de base", url: "https://www.cisa.gov/secure-our-world", lang: "en" },
  wikiCesar: { title: "Wikipédia : chiffrement par décalage (César)", url: "https://fr.wikipedia.org/wiki/Chiffrement_par_d%C3%A9calage", lang: "fr" },
  wikiBase64: { title: "Wikipédia : Base64", url: "https://fr.wikipedia.org/wiki/Base64", lang: "fr" },
  wikiSha2: { title: "Wikipédia : SHA-2", url: "https://fr.wikipedia.org/wiki/SHA-2", lang: "fr" },
  wikiDiceware: { title: "Wikipédia : Diceware, des phrases de passe tirées au hasard", url: "https://fr.wikipedia.org/wiki/Diceware", lang: "fr" },
  wikiIngenierieSociale: { title: "Wikipédia : ingénierie sociale", url: "https://fr.wikipedia.org/wiki/Ing%C3%A9nierie_sociale_(s%C3%A9curit%C3%A9_de_l%27information)", lang: "fr" },
  wikiSpf: { title: "Wikipédia : Sender Policy Framework (SPF)", url: "https://fr.wikipedia.org/wiki/Sender_Policy_Framework", lang: "fr" },
  wikiDkim: { title: "Wikipédia : DomainKeys Identified Mail (DKIM)", url: "https://fr.wikipedia.org/wiki/DomainKeys_Identified_Mail", lang: "fr" },
  wikiDmarc: { title: "Wikipédia : DMARC", url: "https://fr.wikipedia.org/wiki/DMARC", lang: "fr" },
  wikiMfa: { title: "Wikipédia : authentification multifacteur", url: "https://fr.wikipedia.org/wiki/Authentification_multifacteur", lang: "fr" },
  wikiPki: { title: "Wikipédia : infrastructure à clés publiques", url: "https://fr.wikipedia.org/wiki/Infrastructure_%C3%A0_cl%C3%A9s_publiques", lang: "fr" },
  rfc7208: { title: "RFC 7208 : Sender Policy Framework (SPF)", url: "https://www.rfc-editor.org/rfc/rfc7208", lang: "en" },
  rfc6376: { title: "RFC 6376 : DomainKeys Identified Mail (DKIM)", url: "https://www.rfc-editor.org/rfc/rfc6376", lang: "en" },
  rfc7489: { title: "RFC 7489 : DMARC", url: "https://www.rfc-editor.org/rfc/rfc7489", lang: "en" },
  rfc5322: { title: "RFC 5322 : format des messages électroniques", url: "https://www.rfc-editor.org/rfc/rfc5322", lang: "en" },
  rfc4648: { title: "RFC 4648 : encodages Base16, Base32 et Base64", url: "https://www.rfc-editor.org/rfc/rfc4648", lang: "en" },
  rfc5280: { title: "RFC 5280 : certificats X.509 et listes de révocation", url: "https://www.rfc-editor.org/rfc/rfc5280", lang: "en" },
  rfc6238: { title: "RFC 6238 : mots de passe à usage unique basés sur le temps (TOTP)", url: "https://www.rfc-editor.org/rfc/rfc6238", lang: "en" },
  rfc4226: { title: "RFC 4226 : mots de passe à usage unique basés sur un compteur (HOTP)", url: "https://www.rfc-editor.org/rfc/rfc4226", lang: "en" },
  webauthnGuide: { title: "WebAuthn.guide : comprendre les clés d’accès et WebAuthn", url: "https://webauthn.guide/", lang: "en" },
  fidoPasskeys: { title: "Alliance FIDO : les clés d’accès (passkeys)", url: "https://fidoalliance.org/passkeys/", lang: "en" },
  mdnWebAuthn: { title: "MDN : l’API Web Authentication", url: "https://developer.mozilla.org/fr/docs/Web/API/Web_Authentication_API", lang: "fr" },
  mdnSecurity: { title: "MDN : la sécurité sur le Web", url: "https://developer.mozilla.org/fr/docs/Web/Security", lang: "fr" },
  owaspPasswordStorage: { title: "OWASP : aide-mémoire sur le stockage des mots de passe", url: "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html", lang: "en" },
  owaspAuthentication: { title: "OWASP : aide-mémoire sur l’authentification", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html", lang: "en" },
  ncscTips: { title: "NCSC : les gestes essentiels pour rester en sécurité en ligne", url: "https://www.ncsc.gov.uk/collection/top-tips-for-staying-secure-online", lang: "en" },
  // Linux : manuels, wikis, documentations de distributions et outils (adresses vérifiées avant l’écriture du parcours).
  man7Hier: { title: "Linux : hier(7), la hiérarchie du système de fichiers", url: "https://man7.org/linux/man-pages/man7/hier.7.html", lang: "en" },
  man7Ls: { title: "Linux : manuel de la commande ls", url: "https://man7.org/linux/man-pages/man1/ls.1.html", lang: "en" },
  man7Ln: { title: "Linux : manuel de la commande ln", url: "https://man7.org/linux/man-pages/man1/ln.1.html", lang: "en" },
  man7Chmod: { title: "Linux : manuel de la commande chmod", url: "https://man7.org/linux/man-pages/man1/chmod.1.html", lang: "en" },
  man7Chown: { title: "Linux : manuel de la commande chown", url: "https://man7.org/linux/man-pages/man1/chown.1.html", lang: "en" },
  man7Umask: { title: "POSIX : manuel de la commande umask", url: "https://man7.org/linux/man-pages/man1/umask.1p.html", lang: "en" },
  man7Grep: { title: "Linux : manuel de la commande grep", url: "https://man7.org/linux/man-pages/man1/grep.1.html", lang: "en" },
  man7Regex: { title: "Linux : regex(7), les expressions régulières", url: "https://man7.org/linux/man-pages/man7/regex.7.html", lang: "en" },
  man7Find: { title: "Linux : manuel de la commande find", url: "https://man7.org/linux/man-pages/man1/find.1.html", lang: "en" },
  man7Sort: { title: "Linux : manuel de la commande sort", url: "https://man7.org/linux/man-pages/man1/sort.1.html", lang: "en" },
  man7Awk: { title: "POSIX : manuel de la commande awk", url: "https://man7.org/linux/man-pages/man1/awk.1p.html", lang: "en" },
  man7Tar: { title: "Linux : manuel de la commande tar", url: "https://man7.org/linux/man-pages/man1/tar.1.html", lang: "en" },
  man7Ps: { title: "Linux : manuel de la commande ps", url: "https://man7.org/linux/man-pages/man1/ps.1.html", lang: "en" },
  man7Kill: { title: "Linux : manuel de la commande kill", url: "https://man7.org/linux/man-pages/man1/kill.1.html", lang: "en" },
  man7Signal: { title: "Linux : signal(7), les signaux", url: "https://man7.org/linux/man-pages/man7/signal.7.html", lang: "en" },
  man7Proc: { title: "Linux : proc(5), le système de fichiers /proc", url: "https://man7.org/linux/man-pages/man5/proc.5.html", lang: "en" },
  man7Crontab: { title: "Linux : crontab(5), le format des tables cron", url: "https://man7.org/linux/man-pages/man5/crontab.5.html", lang: "en" },
  man7Passwd: { title: "Linux : passwd(5), le fichier /etc/passwd", url: "https://man7.org/linux/man-pages/man5/passwd.5.html", lang: "en" },
  man7Shadow: { title: "Linux : shadow(5), le fichier /etc/shadow", url: "https://man7.org/linux/man-pages/man5/shadow.5.html", lang: "en" },
  man7Sudoers: { title: "sudo : sudoers(5), le fichier de règles sudo", url: "https://man7.org/linux/man-pages/man5/sudoers.5.html", lang: "en" },
  man7Capabilities: { title: "Linux : capabilities(7), les capacités du noyau", url: "https://man7.org/linux/man-pages/man7/capabilities.7.html", lang: "en" },
  man7Credentials: { title: "Linux : credentials(7), identifiants des processus", url: "https://man7.org/linux/man-pages/man7/credentials.7.html", lang: "en" },
  man7Inode: { title: "Linux : inode(7), les inodes", url: "https://man7.org/linux/man-pages/man7/inode.7.html", lang: "en" },
  man7Ss: { title: "Linux : manuel de la commande ss", url: "https://man7.org/linux/man-pages/man8/ss.8.html", lang: "en" },
  man7Fstab: { title: "Linux : fstab(5), le fichier /etc/fstab", url: "https://man7.org/linux/man-pages/man5/fstab.5.html", lang: "en" },
  man7Lsblk: { title: "Linux : manuel de la commande lsblk", url: "https://man7.org/linux/man-pages/man8/lsblk.8.html", lang: "en" },
  man7Mount: { title: "Linux : manuel de la commande mount", url: "https://man7.org/linux/man-pages/man8/mount.8.html", lang: "en" },
  man7Auditd: { title: "Linux : manuel du démon d’audit auditd", url: "https://man7.org/linux/man-pages/man8/auditd.8.html", lang: "en" },
  man7Bash: { title: "Linux : manuel de l’interpréteur bash", url: "https://man7.org/linux/man-pages/man1/bash.1.html", lang: "en" },
  man7Test: { title: "Linux : manuel de la commande test", url: "https://man7.org/linux/man-pages/man1/test.1.html", lang: "en" },
  debSystemctl: { title: "Debian : manuel de systemctl", url: "https://manpages.debian.org/stable/systemd/systemctl.1.en.html", lang: "en" },
  debJournalctl: { title: "Debian : manuel de journalctl", url: "https://manpages.debian.org/stable/systemd/journalctl.1.en.html", lang: "en" },
  debSystemdService: { title: "Debian : systemd.service(5), les unités de service", url: "https://manpages.debian.org/stable/systemd/systemd.service.5.en.html", lang: "en" },
  debSystemdTimer: { title: "Debian : systemd.timer(5), les minuteurs", url: "https://manpages.debian.org/stable/systemd/systemd.timer.5.en.html", lang: "en" },
  debCrontab: { title: "Debian : crontab(5), le format des tables cron", url: "https://manpages.debian.org/stable/cron/crontab.5.en.html", lang: "en" },
  debSudoers: { title: "Debian : sudoers(5), le fichier de règles sudo", url: "https://manpages.debian.org/stable/sudo/sudoers.5.en.html", lang: "en" },
  debApt: { title: "Debian : manuel de apt", url: "https://manpages.debian.org/stable/apt/apt.8.en.html", lang: "en" },
  debSshdConfig: { title: "Debian : sshd_config(5), la configuration du serveur SSH", url: "https://manpages.debian.org/stable/openssh-server/sshd_config.5.en.html", lang: "en" },
  debSshKeygen: { title: "Debian : manuel de ssh-keygen", url: "https://manpages.debian.org/stable/openssh-client/ssh-keygen.1.en.html", lang: "en" },
  debUfw: { title: "Debian : manuel de ufw", url: "https://manpages.debian.org/stable/ufw/ufw.8.en.html", lang: "en" },
  debNft: { title: "Debian : manuel de nft (nftables)", url: "https://manpages.debian.org/stable/nftables/nft.8.en.html", lang: "en" },
  debCryptsetup: { title: "Debian : manuel de cryptsetup", url: "https://manpages.debian.org/stable/cryptsetup-bin/cryptsetup.8.en.html", lang: "en" },
  debRsync: { title: "Debian : manuel de rsync", url: "https://manpages.debian.org/stable/rsync/rsync.1.en.html", lang: "en" },
  debIp: { title: "Debian : manuel de la commande ip (iproute2)", url: "https://manpages.debian.org/stable/iproute2/ip.8.en.html", lang: "en" },
  openbsdSshdConfig: { title: "OpenBSD : sshd_config(5), la configuration du serveur SSH", url: "https://man.openbsd.org/sshd_config", lang: "en" },
  openbsdSshConfig: { title: "OpenBSD : ssh_config(5), la configuration du client SSH", url: "https://man.openbsd.org/ssh_config", lang: "en" },
  archPermissions: { title: "Arch Wiki : permissions et attributs des fichiers", url: "https://wiki.archlinux.org/title/File_permissions_and_attributes", lang: "en" },
  archAcl: { title: "Arch Wiki : listes de contrôle d’accès (ACL)", url: "https://wiki.archlinux.org/title/Access_Control_Lists", lang: "en" },
  archUsers: { title: "Arch Wiki : utilisateurs et groupes", url: "https://wiki.archlinux.org/title/Users_and_groups", lang: "en" },
  archSudo: { title: "Arch Wiki : sudo", url: "https://wiki.archlinux.org/title/Sudo", lang: "en" },
  archSystemd: { title: "Arch Wiki : systemd", url: "https://wiki.archlinux.org/title/Systemd", lang: "en" },
  archTimers: { title: "Arch Wiki : les minuteurs systemd", url: "https://wiki.archlinux.org/title/Systemd/Timers", lang: "en" },
  archJournal: { title: "Arch Wiki : le journal systemd", url: "https://wiki.archlinux.org/title/Systemd/Journal", lang: "en" },
  archCron: { title: "Arch Wiki : cron", url: "https://wiki.archlinux.org/title/Cron", lang: "en" },
  archOpenssh: { title: "Arch Wiki : OpenSSH", url: "https://wiki.archlinux.org/title/OpenSSH", lang: "en" },
  archUfw: { title: "Arch Wiki : Uncomplicated Firewall (ufw)", url: "https://wiki.archlinux.org/title/Uncomplicated_Firewall", lang: "en" },
  archNftables: { title: "Arch Wiki : nftables", url: "https://wiki.archlinux.org/title/Nftables", lang: "en" },
  archIptables: { title: "Arch Wiki : iptables", url: "https://wiki.archlinux.org/title/Iptables", lang: "en" },
  archFstab: { title: "Arch Wiki : fstab", url: "https://wiki.archlinux.org/title/Fstab", lang: "en" },
  archLvm: { title: "Arch Wiki : LVM", url: "https://wiki.archlinux.org/title/LVM", lang: "en" },
  archPartitioning: { title: "Arch Wiki : le partitionnement", url: "https://wiki.archlinux.org/title/Partitioning", lang: "en" },
  archDmCrypt: { title: "Arch Wiki : dm-crypt, le chiffrement de disque", url: "https://wiki.archlinux.org/title/Dm-crypt", lang: "en" },
  archGnupg: { title: "Arch Wiki : GnuPG", url: "https://wiki.archlinux.org/title/GnuPG", lang: "en" },
  archRsync: { title: "Arch Wiki : rsync", url: "https://wiki.archlinux.org/title/Rsync", lang: "en" },
  archSecurity: { title: "Arch Wiki : sécuriser un système Linux", url: "https://wiki.archlinux.org/title/Security", lang: "en" },
  archAudit: { title: "Arch Wiki : le cadre d’audit du noyau", url: "https://wiki.archlinux.org/title/Audit_framework", lang: "en" },
  archFail2ban: { title: "Arch Wiki : Fail2ban", url: "https://wiki.archlinux.org/title/Fail2ban", lang: "en" },
  archSysctl: { title: "Arch Wiki : sysctl", url: "https://wiki.archlinux.org/title/Sysctl", lang: "en" },
  archSelinux: { title: "Arch Wiki : SELinux", url: "https://wiki.archlinux.org/title/SELinux", lang: "en" },
  archApparmor: { title: "Arch Wiki : AppArmor", url: "https://wiki.archlinux.org/title/AppArmor", lang: "en" },
  archLogrotate: { title: "Arch Wiki : logrotate", url: "https://wiki.archlinux.org/title/Logrotate", lang: "en" },
  archBash: { title: "Arch Wiki : Bash", url: "https://wiki.archlinux.org/title/Bash", lang: "en" },
  archShell: { title: "Arch Wiki : les interpréteurs de commandes", url: "https://wiki.archlinux.org/title/Command-line_shell", lang: "en" },
  archCoreUtils: { title: "Arch Wiki : les utilitaires de base (coreutils)", url: "https://wiki.archlinux.org/title/Core_utilities", lang: "en" },
  ubuntuFrConsole: { title: "Ubuntu-fr : les commandes de base de la console", url: "https://doc.ubuntu-fr.org/tutoriel/console_commandes_de_base", lang: "fr" },
  ubuntuFrPermissions: { title: "Ubuntu-fr : les permissions", url: "https://doc.ubuntu-fr.org/permissions", lang: "fr" },
  ubuntuFrUsers: { title: "Ubuntu-fr : la gestion des utilisateurs", url: "https://doc.ubuntu-fr.org/gestion_des_utilisateurs", lang: "fr" },
  ubuntuFrSudo: { title: "Ubuntu-fr : sudo", url: "https://doc.ubuntu-fr.org/sudo", lang: "fr" },
  ubuntuFrCron: { title: "Ubuntu-fr : cron", url: "https://doc.ubuntu-fr.org/cron", lang: "fr" },
  ubuntuFrSsh: { title: "Ubuntu-fr : SSH", url: "https://doc.ubuntu-fr.org/ssh", lang: "fr" },
  ubuntuFrUfw: { title: "Ubuntu-fr : le pare-feu ufw", url: "https://doc.ubuntu-fr.org/ufw", lang: "fr" },
  ubuntuFrApt: { title: "Ubuntu-fr : APT", url: "https://doc.ubuntu-fr.org/apt", lang: "fr" },
  ubuntuFrRsync: { title: "Ubuntu-fr : rsync", url: "https://doc.ubuntu-fr.org/rsync", lang: "fr" },
  ubuntuFrGpg: { title: "Ubuntu-fr : GnuPG", url: "https://doc.ubuntu-fr.org/gpg", lang: "fr" },
  ubuntuFrCryptsetup: { title: "Ubuntu-fr : cryptsetup", url: "https://doc.ubuntu-fr.org/cryptsetup", lang: "fr" },
  openclassroomsLinux: { title: "OpenClassrooms : initiez-vous à Linux", url: "https://openclassrooms.com/fr/courses/7170491-initiez-vous-a-linux", lang: "fr" },
  wikiLinux: { title: "Wikipédia : Linux", url: "https://fr.wikipedia.org/wiki/Linux", lang: "fr" },
  wikiNoyauLinux: { title: "Wikipédia : le noyau Linux", url: "https://fr.wikipedia.org/wiki/Noyau_Linux", lang: "fr" },
  wikiDistribution: { title: "Wikipédia : distribution Linux", url: "https://fr.wikipedia.org/wiki/Distribution_Linux", lang: "fr" },
  wikiUnix: { title: "Wikipédia : Unix", url: "https://fr.wikipedia.org/wiki/Unix", lang: "fr" },
  wikiFhs: { title: "Wikipédia : Filesystem Hierarchy Standard", url: "https://fr.wikipedia.org/wiki/Filesystem_Hierarchy_Standard", lang: "fr" },
  wikiBash: { title: "Wikipédia : Bourne-Again shell (bash)", url: "https://fr.wikipedia.org/wiki/Bourne-Again_shell", lang: "fr" },
  wikiPermissionsUnix: { title: "Wikipédia : permissions UNIX", url: "https://fr.wikipedia.org/wiki/Permissions_UNIX", lang: "fr" },
  wikiSudo: { title: "Wikipédia : sudo", url: "https://fr.wikipedia.org/wiki/Sudo", lang: "fr" },
  wikiSystemd: { title: "Wikipédia : systemd", url: "https://fr.wikipedia.org/wiki/Systemd", lang: "fr" },
  wikiCron: { title: "Wikipédia : cron", url: "https://fr.wikipedia.org/wiki/Cron", lang: "fr" },
  wikiSsh: { title: "Wikipédia : Secure Shell (SSH)", url: "https://fr.wikipedia.org/wiki/Secure_Shell", lang: "fr" },
  wikiNetfilter: { title: "Wikipédia : Netfilter", url: "https://fr.wikipedia.org/wiki/Netfilter", lang: "fr" },
  wikiPaquets: { title: "Wikipédia : gestionnaire de paquets", url: "https://fr.wikipedia.org/wiki/Gestionnaire_de_paquets", lang: "fr" },
  wikiRsync: { title: "Wikipédia : rsync", url: "https://fr.wikipedia.org/wiki/Rsync", lang: "fr" },
  wikiTar: { title: "Wikipédia : tar", url: "https://fr.wikipedia.org/wiki/Tar_(informatique)", lang: "fr" },
  wikiLuks: { title: "Wikipédia : LUKS", url: "https://fr.wikipedia.org/wiki/LUKS", lang: "fr" },
  wikiGpg: { title: "Wikipédia : GNU Privacy Guard", url: "https://fr.wikipedia.org/wiki/GNU_Privacy_Guard", lang: "fr" },
  wikiFail2ban: { title: "Wikipédia : Fail2ban", url: "https://fr.wikipedia.org/wiki/Fail2ban", lang: "fr" },
  wikiSelinux: { title: "Wikipédia : Security-Enhanced Linux (SELinux)", url: "https://fr.wikipedia.org/wiki/Security-Enhanced_Linux", lang: "fr" },
  wikiApparmor: { title: "Wikipédia : AppArmor", url: "https://fr.wikipedia.org/wiki/AppArmor", lang: "fr" },
  wikiSyslog: { title: "Wikipédia : syslog", url: "https://fr.wikipedia.org/wiki/Syslog", lang: "fr" },
  wslInstall: { title: "Microsoft : installer WSL pour utiliser Linux sous Windows", url: "https://learn.microsoft.com/fr-fr/windows/wsl/install", lang: "fr" },
  wslAbout: { title: "Microsoft : qu’est-ce que le sous-système Windows pour Linux ?", url: "https://learn.microsoft.com/fr-fr/windows/wsl/about", lang: "fr" },
  termuxHome: { title: "Termux : un terminal Linux sur Android", url: "https://termux.dev/", lang: "en" },
  virtualboxHome: { title: "VirtualBox : virtualisation gratuite", url: "https://www.virtualbox.org/", lang: "en" },
  virtualboxManual: { title: "VirtualBox : manuel de l’utilisateur", url: "https://www.virtualbox.org/manual/", lang: "en" },
  ubuntuDesktop: { title: "Ubuntu : télécharger la version pour ordinateur", url: "https://ubuntu.com/download/desktop", lang: "en" },
  ubuntuCommandLine: { title: "Ubuntu : tutoriel de la ligne de commande pour débutants", url: "https://ubuntu.com/tutorials/command-line-for-beginners", lang: "en" },
  ubuntuServerDocs: { title: "Ubuntu : documentation du serveur", url: "https://ubuntu.com/server/docs", lang: "en" },
  ubuntuSecurityNotices: { title: "Ubuntu : avis de sécurité", url: "https://ubuntu.com/security/notices", lang: "en" },
  debianReference: { title: "Debian : le manuel de référence Debian", url: "https://www.debian.org/doc/manuals/debian-reference/", lang: "en" },
  debianHandbook: { title: "Debian : le manuel de l’administrateur Debian", url: "https://www.debian.org/doc/manuals/debian-handbook/", lang: "en" },
  debianSecurity: { title: "Debian : l’équipe de sécurité et les avis", url: "https://www.debian.org/security/", lang: "en" },
  debianTracker: { title: "Debian : le suivi des vulnérabilités (Security Tracker)", url: "https://security-tracker.debian.org/tracker/", lang: "en" },
  fedoraDnf: { title: "Fedora : gérer les logiciels avec DNF", url: "https://docs.fedoraproject.org/en-US/quick-docs/dnf/", lang: "en" },
  redhatHardening: { title: "Red Hat : durcissement de la sécurité de RHEL 9", url: "https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/security_hardening/index", lang: "en" },
  tldpBash: { title: "TLDP : guide de bash pour débutants", url: "https://tldp.org/LDP/Bash-Beginners-Guide/html/", lang: "en" },
  tldpAbs: { title: "TLDP : guide avancé de l’écriture de scripts bash", url: "https://tldp.org/LDP/abs/html/", lang: "en" },
  tldpAdmin: { title: "TLDP : guide de l’administrateur système Linux", url: "https://tldp.org/LDP/sag/html/", lang: "en" },
  linuxCommandBook: { title: "The Linux Command Line : le livre gratuit de William Shotts", url: "https://linuxcommand.org/tlcl.php", lang: "en" },
  gnuBash: { title: "GNU : le manuel de référence de Bash", url: "https://www.gnu.org/software/bash/manual/bash.html", lang: "en" },
  gnuCoreutils: { title: "GNU : le manuel des coreutils", url: "https://www.gnu.org/software/coreutils/manual/coreutils.html", lang: "en" },
  fhs: { title: "Linux Foundation : le Filesystem Hierarchy Standard 3.0", url: "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html", lang: "en" },
  posixShell: { title: "POSIX : le langage de commande du shell", url: "https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html", lang: "en" },
  shellcheck: { title: "ShellCheck : analyser ses scripts shell", url: "https://www.shellcheck.net/", lang: "en" },
  shellcheckSc2086: { title: "ShellCheck : SC2086, mettre les variables entre guillemets", url: "https://www.shellcheck.net/wiki/SC2086", lang: "en" },
  kernelAdmin: { title: "Noyau Linux : le guide de l’administrateur", url: "https://www.kernel.org/doc/html/latest/admin-guide/index.html", lang: "en" },
  kernelSysctl: { title: "Noyau Linux : les paramètres sysctl", url: "https://www.kernel.org/doc/html/latest/admin-guide/sysctl/index.html", lang: "en" },
  sudoWsSudoers: { title: "sudo.ws : le manuel de sudoers", url: "https://www.sudo.ws/docs/man/sudoers.man/", lang: "en" },
  openssh: { title: "OpenSSH : le manuel", url: "https://www.openssh.com/manual.html", lang: "en" },
  sshAcademy: { title: "SSH Academy : comprendre le protocole SSH", url: "https://www.ssh.com/academy/ssh", lang: "en" },
  lynis: { title: "Lynis : audit de sécurité et durcissement des systèmes Unix", url: "https://cisofy.com/lynis/", lang: "en" },
  fail2banGithub: { title: "Fail2ban : le projet", url: "https://github.com/fail2ban/fail2ban", lang: "en" },
  cryptsetupProject: { title: "cryptsetup : le projet (LUKS et dm-crypt)", url: "https://gitlab.com/cryptsetup/cryptsetup", lang: "en" },
  cisBenchmarks: { title: "CIS : les guides de configuration sécurisée (benchmarks)", url: "https://www.cisecurity.org/cis-benchmarks", lang: "en" },
  restic: { title: "restic : la documentation", url: "https://restic.readthedocs.io/", lang: "en" },
  nftablesWiki: { title: "nftables : le wiki du projet", url: "https://wiki.nftables.org/wiki-nftables/index.php/Main_Page", lang: "en" },
  gnupgDocs: { title: "GnuPG : la documentation", url: "https://www.gnupg.org/documentation/", lang: "en" },
  opensslDocs: { title: "OpenSSL : la documentation", url: "https://www.openssl.org/docs/", lang: "en" },
  cve: { title: "CVE : le programme des identifiants de vulnérabilités", url: "https://www.cve.org/", lang: "en" },
  nvd: { title: "NIST : la base nationale des vulnérabilités (NVD)", url: "https://nvd.nist.gov/", lang: "en" },
  firstCvss: { title: "FIRST : le système de notation CVSS", url: "https://www.first.org/cvss/", lang: "en" },
  // Analyse de logs : journalisation, formats, systèmes, réseau, détection, outils, investigation.
  nistLogMgmt: { title: "NIST SP 800-92 : guide de la gestion des journaux de sécurité", url: "https://csrc.nist.gov/pubs/sp/800/92/final", lang: "en" },
  nistForensics: { title: "NIST SP 800-86 : intégrer l’investigation numérique à la réponse aux incidents", url: "https://csrc.nist.gov/pubs/sp/800/86/final", lang: "en" },
  rfc3164: { title: "RFC 3164 : le protocole syslog BSD (historique)", url: "https://www.rfc-editor.org/rfc/rfc3164", lang: "en" },
  rfc5425: { title: "RFC 5425 : transport de syslog sur TLS", url: "https://www.rfc-editor.org/rfc/rfc5425", lang: "en" },
  rfc3339: { title: "RFC 3339 : date et heure sur Internet", url: "https://www.rfc-editor.org/rfc/rfc3339", lang: "en" },
  rfc3227: { title: "RFC 3227 : recommandations pour la collecte et l’archivage des preuves", url: "https://www.rfc-editor.org/rfc/rfc3227", lang: "en" },
  rfc7011: { title: "RFC 7011 : IPFIX, l’export de flux IP", url: "https://www.rfc-editor.org/rfc/rfc7011", lang: "en" },
  owaspLogging: { title: "OWASP : aide-mémoire sur la journalisation", url: "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html", lang: "en" },
  owaspLoggingVocab: { title: "OWASP : vocabulaire de journalisation applicative", url: "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Vocabulary_Cheat_Sheet.html", lang: "en" },
  owaspTop10: { title: "OWASP : le Top 10 des risques des applications web", url: "https://owasp.org/www-project-top-ten/", lang: "en" },
  owaspSqli: { title: "OWASP : l’injection SQL", url: "https://owasp.org/www-community/attacks/SQL_Injection", lang: "en" },
  owaspXss: { title: "OWASP : le cross-site scripting (XSS)", url: "https://owasp.org/www-community/attacks/xss/", lang: "en" },
  owaspPathTraversal: { title: "OWASP : la traversée de répertoires", url: "https://owasp.org/www-community/attacks/Path_Traversal", lang: "en" },
  owaspBruteForce: { title: "OWASP : l’attaque par force brute", url: "https://owasp.org/www-community/attacks/Brute_force_attack", lang: "en" },
  cisAuditLogs: { title: "CIS : le contrôle « gestion des journaux d’audit »", url: "https://www.cisecurity.org/controls/audit-log-management", lang: "en" },
  cnilTracer: { title: "CNIL : sécurité, tracer les opérations", url: "https://www.cnil.fr/fr/securite-tracer-les-operations", lang: "fr" },
  cnilGuideSecurite: { title: "CNIL : guide de la sécurité des données personnelles", url: "https://www.cnil.fr/fr/guide-de-la-securite-des-donnees-personnelles-nouvelle-edition-2024", lang: "fr" },
  cnilConservation: { title: "CNIL : les durées de conservation des données", url: "https://www.cnil.fr/fr/passer-laction/les-durees-de-conservation-des-donnees", lang: "fr" },
  cnilArchiver: { title: "CNIL : sécurité, archiver de manière sécurisée", url: "https://www.cnil.fr/fr/securite-archiver-de-maniere-securisee", lang: "fr" },
  cnilFormer: { title: "CNIL : sécurité, impliquer et former les utilisateurs", url: "https://www.cnil.fr/fr/securite-impliquer-et-former-les-utilisateurs", lang: "fr" },
  anssiJournalisation: { title: "ANSSI : recommandations pour la mise en œuvre d’un système de journalisation", url: "https://messervices.cyber.gouv.fr/guides/recommandations-de-securite-pour-la-mise-en-oeuvre-dun-systeme-de-journalisation", lang: "fr" },
  certFr: { title: "CERT-FR : le centre gouvernemental de veille, d’alerte et de réponse", url: "https://www.cert.ssi.gouv.fr/", lang: "fr" },
  certFrCti: { title: "CERT-FR : menaces et incidents", url: "https://www.cert.ssi.gouv.fr/cti/", lang: "fr" },
  wikiJournalisation: { title: "Wikipédia : journalisation", url: "https://fr.wikipedia.org/wiki/Journalisation", lang: "fr" },
  wikiIso8601: { title: "Wikipédia : ISO 8601", url: "https://fr.wikipedia.org/wiki/ISO_8601", lang: "fr" },
  wikiUtc: { title: "Wikipédia : temps universel coordonné", url: "https://fr.wikipedia.org/wiki/Temps_universel_coordonn%C3%A9", lang: "fr" },
  wikiNetflow: { title: "Wikipédia : NetFlow", url: "https://fr.wikipedia.org/wiki/NetFlow", lang: "fr" },
  wikiRegex: { title: "Wikipédia : expression régulière", url: "https://fr.wikipedia.org/wiki/Expression_r%C3%A9guli%C3%A8re", lang: "fr" },
  wikiSoc: { title: "Wikipédia : centre des opérations de sécurité", url: "https://fr.wikipedia.org/wiki/Centre_des_op%C3%A9rations_de_s%C3%A9curit%C3%A9", lang: "fr" },
  ianaTz: { title: "IANA : la base de données des fuseaux horaires", url: "https://www.iana.org/time-zones", lang: "en" },
  chrony: { title: "chrony : documentation (synchronisation d’horloge)", url: "https://chrony-project.org/documentation.html", lang: "en" },
  rsyslogDoc: { title: "rsyslog : la documentation", url: "https://www.rsyslog.com/doc/", lang: "en" },
  rsyslogConfig: { title: "rsyslog : la configuration", url: "https://www.rsyslog.com/doc/configuration/index.html", lang: "en" },
  man7Ausearch: { title: "Manuel : ausearch(8), chercher dans les journaux d’audit", url: "https://man7.org/linux/man-pages/man8/ausearch.8.html", lang: "en" },
  man7Auditctl: { title: "Manuel : auditctl(8), les règles d’audit", url: "https://man7.org/linux/man-pages/man8/auditctl.8.html", lang: "en" },
  man7Last: { title: "Manuel : last(1) et lastb(1), l’historique des connexions (util-linux)", url: "https://man7.org/linux/man-pages/man1/last.1@@util-linux.html", lang: "en" },
  man7Logrotate: { title: "Manuel : logrotate(8), la rotation des journaux", url: "https://man7.org/linux/man-pages/man8/logrotate.8.html", lang: "en" },
  man7Date: { title: "Manuel : date(1), afficher et convertir les dates", url: "https://man7.org/linux/man-pages/man1/date.1.html", lang: "en" },
  man7Uniq: { title: "Manuel : uniq(1)", url: "https://man7.org/linux/man-pages/man1/uniq.1.html", lang: "en" },
  man7Cut: { title: "Manuel : cut(1)", url: "https://man7.org/linux/man-pages/man1/cut.1.html", lang: "en" },
  man7Sed: { title: "Manuel : sed(1)", url: "https://man7.org/linux/man-pages/man1/sed.1.html", lang: "en" },
  man7Tr: { title: "Manuel : tr(1)", url: "https://man7.org/linux/man-pages/man1/tr.1.html", lang: "en" },
  man7Wc: { title: "Manuel : wc(1)", url: "https://man7.org/linux/man-pages/man1/wc.1.html", lang: "en" },
  openbsdSshd: { title: "OpenBSD : le manuel de sshd(8)", url: "https://man.openbsd.org/sshd", lang: "en" },
  fail2banWiki: { title: "Fail2ban : le wiki", url: "https://github.com/fail2ban/fail2ban/wiki", lang: "en" },
  debJournaldConf: { title: "Debian : manuel de journald.conf", url: "https://manpages.debian.org/stable/systemd/journald.conf.5.en.html", lang: "en" },
  debJournalRemote: { title: "Debian : manuel de systemd-journal-remote", url: "https://manpages.debian.org/stable/systemd-journal-remote/systemd-journal-remote.8.en.html", lang: "en" },
  msSecAudit: { title: "Microsoft : vue d’ensemble de l’audit de sécurité", url: "https://learn.microsoft.com/fr-fr/windows/security/threat-protection/auditing/security-auditing-overview", lang: "fr" },
  msAdvAudit: { title: "Microsoft : paramètres avancés de la stratégie d’audit de sécurité", url: "https://learn.microsoft.com/fr-fr/windows/security/threat-protection/auditing/advanced-security-audit-policy-settings", lang: "fr" },
  msEvent4624: { title: "Microsoft : événement 4624, ouverture de session réussie", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4624", lang: "fr" },
  msEvent4625: { title: "Microsoft : événement 4625, échec d’ouverture de session", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4625", lang: "fr" },
  msEvent4634: { title: "Microsoft : événement 4634, fermeture de session", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4634", lang: "fr" },
  msEvent4648: { title: "Microsoft : événement 4648, ouverture de session avec des informations d’identification explicites", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4648", lang: "fr" },
  msEvent4672: { title: "Microsoft : événement 4672, privilèges spéciaux attribués à une nouvelle session", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4672", lang: "fr" },
  msEvent4688: { title: "Microsoft : événement 4688, création d’un processus", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4688", lang: "fr" },
  msEvent4720: { title: "Microsoft : événement 4720, création d’un compte utilisateur", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4720", lang: "fr" },
  msEvent4740: { title: "Microsoft : événement 4740, verrouillage d’un compte", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4740", lang: "fr" },
  msEvent1102: { title: "Microsoft : événement 1102, effacement du journal d’audit", url: "https://learn.microsoft.com/fr-fr/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-1102", lang: "fr" },
  msSysmon: { title: "Microsoft : Sysmon, le moniteur système de Sysinternals", url: "https://learn.microsoft.com/fr-fr/sysinternals/downloads/sysmon", lang: "fr" },
  msSysinternals: { title: "Microsoft : la suite Sysinternals", url: "https://learn.microsoft.com/fr-fr/sysinternals/", lang: "fr" },
  msGetWinEvent: { title: "Microsoft : l’applet de commande Get-WinEvent", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.diagnostics/get-winevent", lang: "fr" },
  msPsLogging: { title: "Microsoft : la journalisation de PowerShell", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.core/about/about_logging_windows", lang: "fr" },
  msWevtutil: { title: "Microsoft : la commande wevtutil", url: "https://learn.microsoft.com/fr-fr/windows-server/administration/windows-commands/wevtutil", lang: "fr" },
  msLogonTypes: { title: "Microsoft : les types d’ouverture de session", url: "https://learn.microsoft.com/fr-fr/windows-server/identity/securing-privileged-access/reference-tools-logon-types", lang: "fr" },
  msEventForwarding: { title: "Microsoft : la redirection d’événements Windows", url: "https://learn.microsoft.com/fr-fr/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection", lang: "fr" },
  msEventLogging: { title: "Microsoft : la journalisation d’événements Windows", url: "https://learn.microsoft.com/fr-fr/windows/win32/eventlog/event-logging", lang: "fr" },
  msSelectString: { title: "Microsoft : l’applet de commande Select-String", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.utility/select-string", lang: "fr" },
  msConvertFromJson: { title: "Microsoft : l’applet de commande ConvertFrom-Json", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.utility/convertfrom-json", lang: "fr" },
  msImportCsv: { title: "Microsoft : l’applet de commande Import-Csv", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.utility/import-csv", lang: "fr" },
  msGroupObject: { title: "Microsoft : l’applet de commande Group-Object", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.utility/group-object", lang: "fr" },
  msSortObject: { title: "Microsoft : l’applet de commande Sort-Object", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.utility/sort-object", lang: "fr" },
  msWhereObject: { title: "Microsoft : l’applet de commande Where-Object", url: "https://learn.microsoft.com/fr-fr/powershell/module/microsoft.powershell.core/where-object", lang: "fr" },
  sysmonCommunity: { title: "TrustedSec : le guide communautaire de Sysmon", url: "https://github.com/trustedsec/SysmonCommunityGuide", lang: "en" },
  sysmonConfig: { title: "SwiftOnSecurity : une configuration de départ pour Sysmon", url: "https://github.com/SwiftOnSecurity/sysmon-config", lang: "en" },
  apacheLogs: { title: "Apache : les fichiers journaux", url: "https://httpd.apache.org/docs/2.4/logs.html", lang: "en" },
  apacheLogConfig: { title: "Apache : le format des journaux (mod_log_config)", url: "https://httpd.apache.org/docs/2.4/mod/mod_log_config.html", lang: "en" },
  nginxLog: { title: "nginx : le module de journalisation des accès", url: "https://nginx.org/en/docs/http/ngx_http_log_module.html", lang: "en" },
  suricataDocs: { title: "Suricata : la documentation", url: "https://docs.suricata.io/en/latest/", lang: "en" },
  suricataEve: { title: "Suricata : la sortie EVE au format JSON", url: "https://docs.suricata.io/en/latest/output/eve/eve-json-output.html", lang: "en" },
  suricataRules: { title: "Suricata : les règles", url: "https://docs.suricata.io/en/latest/rules/index.html", lang: "en" },
  squidLog: { title: "Squid : les formats de journaux", url: "https://wiki.squid-cache.org/Features/LogFormat", lang: "en" },
  pfsenseLogs: { title: "pfSense : consulter les journaux", url: "https://docs.netgate.com/pfsense/en/latest/monitoring/logs/index.html", lang: "en" },
  netfilterDoc: { title: "netfilter : la documentation", url: "https://www.netfilter.org/documentation/", lang: "en" },
  sigmaSite: { title: "Sigma : des règles de détection indépendantes du produit", url: "https://sigmahq.io/", lang: "en" },
  sigmaRules: { title: "Sigma : écrire une règle", url: "https://sigmahq.io/docs/basics/rules.html", lang: "en" },
  sigmaGithub: { title: "Sigma : le dépôt des règles", url: "https://github.com/SigmaHQ/sigma", lang: "en" },
  mitreAttack: { title: "MITRE ATT&CK : la base de connaissances des techniques d’attaque", url: "https://attack.mitre.org/", lang: "en" },
  mitreTactics: { title: "MITRE ATT&CK : les tactiques", url: "https://attack.mitre.org/tactics/enterprise/", lang: "en" },
  mitreDataSources: { title: "MITRE ATT&CK : les sources de données", url: "https://attack.mitre.org/datasources/", lang: "en" },
  mitreT1110: { title: "MITRE ATT&CK : T1110, force brute", url: "https://attack.mitre.org/techniques/T1110/", lang: "en" },
  mitreT1059: { title: "MITRE ATT&CK : T1059, interpréteurs de commandes et de scripts", url: "https://attack.mitre.org/techniques/T1059/", lang: "en" },
  mitreT1505003: { title: "MITRE ATT&CK : T1505.003, shell web", url: "https://attack.mitre.org/techniques/T1505/003/", lang: "en" },
  mitreT1070001: { title: "MITRE ATT&CK : T1070.001, effacement des journaux d’événements Windows", url: "https://attack.mitre.org/techniques/T1070/001/", lang: "en" },
  mitreT1078: { title: "MITRE ATT&CK : T1078, comptes valides", url: "https://attack.mitre.org/techniques/T1078/", lang: "en" },
  mitreT1053: { title: "MITRE ATT&CK : T1053, tâche ou job planifié", url: "https://attack.mitre.org/techniques/T1053/", lang: "en" },
  mitreT1136: { title: "MITRE ATT&CK : T1136, création de compte", url: "https://attack.mitre.org/techniques/T1136/", lang: "en" },
  mitreT1071004: { title: "MITRE ATT&CK : T1071.004, protocole applicatif DNS", url: "https://attack.mitre.org/techniques/T1071/004/", lang: "en" },
  mitreT1190: { title: "MITRE ATT&CK : T1190, exploitation d’une application exposée", url: "https://attack.mitre.org/techniques/T1190/", lang: "en" },
  mitreT1046: { title: "MITRE ATT&CK : T1046, découverte des services réseau", url: "https://attack.mitre.org/techniques/T1046/", lang: "en" },
  mitreT1021004: { title: "MITRE ATT&CK : T1021.004, services distants par SSH", url: "https://attack.mitre.org/techniques/T1021/004/", lang: "en" },
  mitreT1021001: { title: "MITRE ATT&CK : T1021.001, services distants par RDP", url: "https://attack.mitre.org/techniques/T1021/001/", lang: "en" },
  mitreT1048: { title: "MITRE ATT&CK : T1048, exfiltration par un protocole alternatif", url: "https://attack.mitre.org/techniques/T1048/", lang: "en" },
  mitreT1105: { title: "MITRE ATT&CK : T1105, transfert d’outils vers la machine", url: "https://attack.mitre.org/techniques/T1105/", lang: "en" },
  mitreT1566: { title: "MITRE ATT&CK : T1566, hameçonnage", url: "https://attack.mitre.org/techniques/T1566/", lang: "en" },
  mitreT1486: { title: "MITRE ATT&CK : T1486, chiffrement de données à des fins d’extorsion", url: "https://attack.mitre.org/techniques/T1486/", lang: "en" },
  pyramidOfPain: { title: "David Bianco : la pyramide de la douleur", url: "https://detect-respond.blogspot.com/2013/03/the-pyramid-of-pain.html", lang: "en" },
  killChain: { title: "Lockheed Martin : la Cyber Kill Chain", url: "https://www.lockheedmartin.com/en-us/capabilities/cyber/cyber-kill-chain.html", lang: "en" },
  elasticDetectionRules: { title: "Elastic : le dépôt des règles de détection", url: "https://github.com/elastic/detection-rules", lang: "en" },
  wazuhDocs: { title: "Wazuh : la documentation", url: "https://documentation.wazuh.com/current/index.html", lang: "en" },
  wazuhRuleset: { title: "Wazuh : les règles et décodeurs", url: "https://documentation.wazuh.com/current/user-manual/ruleset/index.html", lang: "en" },
  wazuhQuickstart: { title: "Wazuh : démarrage rapide", url: "https://documentation.wazuh.com/current/quickstart.html", lang: "en" },
  graylogDocs: { title: "Graylog : la documentation", url: "https://go2docs.graylog.org/current/home.htm", lang: "en" },
  elasticDocs: { title: "Elastic : la documentation de la pile Elastic", url: "https://www.elastic.co/guide/index.html", lang: "en" },
  filebeatDocs: { title: "Elastic : Filebeat, collecter des fichiers journaux", url: "https://www.elastic.co/guide/en/beats/filebeat/current/index.html", lang: "en" },
  securityOnionDocs: { title: "Security Onion : la documentation", url: "https://docs.securityonion.net/", lang: "en" },
  ossecDocs: { title: "OSSEC : la documentation", url: "https://www.ossec.net/docs/", lang: "en" },
  lokiDocs: { title: "Grafana Loki : la documentation", url: "https://grafana.com/docs/loki/latest/", lang: "en" },
  opensearchDocs: { title: "OpenSearch : la documentation", url: "https://opensearch.org/docs/latest/", lang: "en" },
  syslogNgGithub: { title: "syslog-ng : le projet", url: "https://github.com/syslog-ng/syslog-ng", lang: "en" },
  fluentBitDocs: { title: "Fluent Bit : la documentation", url: "https://docs.fluentbit.io/manual", lang: "en" },
  jqManual: { title: "jq : le manuel", url: "https://jqlang.github.io/jq/manual/", lang: "en" },
  regex101: { title: "regex101 : tester une expression régulière", url: "https://regex101.com/", lang: "en" },
  regularExpressionsInfo: { title: "Regular-Expressions.info : tout sur les expressions régulières", url: "https://www.regular-expressions.info/", lang: "en" },
  cyberChef: { title: "CyberChef : l’atelier d’analyse de données du GCHQ", url: "https://gchq.github.io/CyberChef/", lang: "en" },
  goaccess: { title: "GoAccess : analyseur de journaux web en temps réel", url: "https://goaccess.io/", lang: "en" },
  lnav: { title: "lnav : un lecteur de journaux dans le terminal", url: "https://lnav.org/", lang: "en" },
  virusTotal: { title: "VirusTotal : analyser un fichier, une adresse ou un domaine", url: "https://www.virustotal.com/", lang: "en" },
  urlhaus: { title: "URLhaus : adresses de diffusion de logiciels malveillants", url: "https://urlhaus.abuse.ch/", lang: "en" },
  misp: { title: "MISP : la plateforme libre de partage d’indicateurs", url: "https://www.misp-project.org/", lang: "en" },
  ripeStat: { title: "RIPEstat : informations sur une adresse IP ou un réseau", url: "https://stat.ripe.net/", lang: "en" },
  firstTlp: { title: "FIRST : le protocole TLP pour partager de l’information sensible", url: "https://www.first.org/tlp/", lang: "en" },
  // Sécurité Web.
  owaspCsSqli: { title: "OWASP : aide-mémoire sur la prévention de l’injection SQL", url: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html", lang: "en" },
  owaspCsQueryParam: { title: "OWASP : aide-mémoire sur les requêtes paramétrées", url: "https://cheatsheetseries.owasp.org/cheatsheets/Query_Parameterization_Cheat_Sheet.html", lang: "en" },
  owaspCsXss: { title: "OWASP : aide-mémoire sur la prévention du XSS", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html", lang: "en" },
  owaspCsDomXss: { title: "OWASP : aide-mémoire sur la prévention du XSS basé sur le DOM", url: "https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html", lang: "en" },
  owaspCsCsrf: { title: "OWASP : aide-mémoire sur la prévention du CSRF", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html", lang: "en" },
  owaspCsSession: { title: "OWASP : aide-mémoire sur la gestion des sessions", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html", lang: "en" },
  owaspCsOauth2: { title: "OWASP : aide-mémoire OAuth 2.0", url: "https://cheatsheetseries.owasp.org/cheatsheets/OAuth2_Cheat_Sheet.html", lang: "en" },
  owaspCsInputValidation: { title: "OWASP : aide-mémoire sur la validation des entrées", url: "https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html", lang: "en" },
  owaspCsAuthorization: { title: "OWASP : aide-mémoire sur l’autorisation", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html", lang: "en" },
  owaspCsIdor: { title: "OWASP : aide-mémoire sur la prévention des références directes d’objet non sécurisées (IDOR)", url: "https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html", lang: "en" },
  owaspCsSsrf: { title: "OWASP : aide-mémoire sur la prévention du SSRF", url: "https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html", lang: "en" },
  owaspCsFileUpload: { title: "OWASP : aide-mémoire sur le téléversement de fichiers", url: "https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html", lang: "en" },
  owaspCsCsp: { title: "OWASP : aide-mémoire sur la Content Security Policy", url: "https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html", lang: "en" },
  owaspCsRest: { title: "OWASP : aide-mémoire sur la sécurité des API REST", url: "https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html", lang: "en" },
  owaspCsSecrets: { title: "OWASP : aide-mémoire sur la gestion des secrets", url: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html", lang: "en" },
  owaspCsDependencies: { title: "OWASP : aide-mémoire sur la gestion des dépendances vulnérables", url: "https://cheatsheetseries.owasp.org/cheatsheets/Vulnerable_Dependency_Management_Cheat_Sheet.html", lang: "en" },
  owaspCsHeaders: { title: "OWASP : aide-mémoire sur les en-têtes HTTP de sécurité", url: "https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html", lang: "en" },
  owaspCsTls: { title: "OWASP : aide-mémoire sur Transport Layer Security", url: "https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Security_Cheat_Sheet.html", lang: "en" },
  owaspCsThreatModeling: { title: "OWASP : aide-mémoire sur la modélisation des menaces", url: "https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html", lang: "en" },
  owaspCsErrors: { title: "OWASP : aide-mémoire sur la gestion des erreurs", url: "https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html", lang: "en" },
  owaspCsDeserialization: { title: "OWASP : aide-mémoire sur la désérialisation", url: "https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html", lang: "en" },
  owaspCsXxe: { title: "OWASP : aide-mémoire sur la prévention des entités externes XML (XXE)", url: "https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html", lang: "en" },
  owaspCsCommandInjection: { title: "OWASP : aide-mémoire sur la défense contre l’injection de commandes", url: "https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html", lang: "en" },
  owaspCsClickjacking: { title: "OWASP : aide-mémoire sur la défense contre le détournement de clic", url: "https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html", lang: "en" },
  owaspCsForgotPassword: { title: "OWASP : aide-mémoire sur la réinitialisation de mot de passe", url: "https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html", lang: "en" },
  owaspCsMfa: { title: "OWASP : aide-mémoire sur l’authentification multifacteur", url: "https://cheatsheetseries.owasp.org/cheatsheets/Multifactor_Authentication_Cheat_Sheet.html", lang: "en" },
  owaspCsMassAssignment: { title: "OWASP : aide-mémoire sur l’assignation en masse", url: "https://cheatsheetseries.owasp.org/cheatsheets/Mass_Assignment_Cheat_Sheet.html", lang: "en" },
  owaspCsNpm: { title: "OWASP : aide-mémoire sur la sécurité npm", url: "https://cheatsheetseries.owasp.org/cheatsheets/NPM_Security_Cheat_Sheet.html", lang: "en" },
  owaspCsSupplyChain: { title: "OWASP : aide-mémoire sur la sécurité de la chaîne d’approvisionnement logicielle", url: "https://cheatsheetseries.owasp.org/cheatsheets/Software_Supply_Chain_Security_Cheat_Sheet.html", lang: "en" },
  owaspCsNode: { title: "OWASP : aide-mémoire sur la sécurité de Node.js", url: "https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Security_Cheat_Sheet.html", lang: "en" },
  owaspCsRedirects: { title: "OWASP : aide-mémoire sur les redirections non validées", url: "https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html", lang: "en" },
  owaspCsCookieTheft: { title: "OWASP : aide-mémoire sur la limitation du vol de cookies", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cookie_Theft_Mitigation_Cheat_Sheet.html", lang: "en" },
  owaspCsDos: { title: "OWASP : aide-mémoire sur le déni de service", url: "https://cheatsheetseries.owasp.org/cheatsheets/Denial_of_Service_Cheat_Sheet.html", lang: "en" },
  owaspCsAttackSurface: { title: "OWASP : aide-mémoire sur l’analyse de la surface d’attaque", url: "https://cheatsheetseries.owasp.org/cheatsheets/Attack_Surface_Analysis_Cheat_Sheet.html", lang: "en" },
  owaspTop10Edition: { title: "OWASP : le Top 10:2025 des risques applicatifs", url: "https://top10.owasp.org/2025/", lang: "en" },
  owaspTop10A01: { title: "OWASP Top 10:2025 : A01, contrôle d’accès défaillant", url: "https://top10.owasp.org/2025/A01_2025-Broken_Access_Control/", lang: "en" },
  owaspTop10A02: { title: "OWASP Top 10:2025 : A02, mauvaise configuration de sécurité", url: "https://top10.owasp.org/2025/A02_2025-Security_Misconfiguration/", lang: "en" },
  owaspTop10A03: { title: "OWASP Top 10:2025 : A03, défaillances de la chaîne d’approvisionnement logicielle", url: "https://top10.owasp.org/2025/A03_2025-Software_Supply_Chain_Failures/", lang: "en" },
  owaspTop10A05: { title: "OWASP Top 10:2025 : A05, injection", url: "https://top10.owasp.org/2025/A05_2025-Injection/", lang: "en" },
  owaspTop10A07: { title: "OWASP Top 10:2025 : A07, défaillances d’authentification", url: "https://top10.owasp.org/2025/A07_2025-Authentication_Failures/", lang: "en" },
  owaspTop10A10: { title: "OWASP Top 10:2025 : A10, mauvaise gestion des conditions exceptionnelles", url: "https://top10.owasp.org/2025/A10_2025-Mishandling_of_Exceptional_Conditions/", lang: "en" },
  owaspApiTop10: { title: "OWASP : le Top 10 de la sécurité des API (2023)", url: "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", lang: "en" },
  owaspAsvs: { title: "OWASP : l’Application Security Verification Standard (ASVS)", url: "https://owasp.org/www-project-application-security-verification-standard/", lang: "en" },
  owaspWstg: { title: "OWASP : le guide de test de sécurité web (WSTG)", url: "https://owasp.org/www-project-web-security-testing-guide/", lang: "en" },
  owaspJuiceShop: { title: "OWASP Juice Shop : une application volontairement vulnérable pour s’entraîner", url: "https://owasp.org/www-project-juice-shop/", lang: "en" },
  owaspWebGoat: { title: "OWASP WebGoat : un parcours d’exercices de sécurité web", url: "https://owasp.org/www-project-webgoat/", lang: "en" },
  owaspDependencyCheck: { title: "OWASP Dependency-Check : détecter les composants vulnérables", url: "https://owasp.org/www-project-dependency-check/", lang: "en" },
  owaspSamm: { title: "OWASP SAMM : mesurer la maturité du développement sécurisé", url: "https://owasp.org/www-project-samm/", lang: "en" },
  owaspCsrfAttack: { title: "OWASP : l’attaque CSRF", url: "https://owasp.org/www-community/attacks/csrf", lang: "en" },
  owaspCommandInjection: { title: "OWASP : l’injection de commandes", url: "https://owasp.org/www-community/attacks/Command_Injection", lang: "en" },
  owaspClickjacking: { title: "OWASP : le détournement de clic (clickjacking)", url: "https://owasp.org/www-community/attacks/Clickjacking", lang: "en" },
  owaspSsrfAttack: { title: "OWASP : la falsification de requête côté serveur (SSRF)", url: "https://owasp.org/www-community/attacks/Server_Side_Request_Forgery", lang: "en" },
  owaspThreatModelingCommunity: { title: "OWASP : la modélisation des menaces", url: "https://owasp.org/www-community/Threat_Modeling", lang: "en" },
  owaspInsecureTransport: { title: "OWASP : le transport non sécurisé", url: "https://owasp.org/www-community/vulnerabilities/Insecure_Transport", lang: "en" },
  zapDocs: { title: "ZAP : la documentation du scanner de sécurité web OWASP ZAP", url: "https://www.zaproxy.org/docs/", lang: "en" },
  mdnCspGuide: { title: "MDN : la Content Security Policy (CSP)", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Guides/CSP", lang: "fr" },
  mdnCspHeader: { title: "MDN : l’en-tête Content-Security-Policy", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/Content-Security-Policy", lang: "fr" },
  mdnSetCookie: { title: "MDN : l’en-tête Set-Cookie", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/Set-Cookie", lang: "fr" },
  mdnSameOrigin: { title: "MDN : la politique de même origine", url: "https://developer.mozilla.org/fr/docs/Web/Security/Defenses/Same-origin_policy", lang: "fr" },
  mdnSri: { title: "MDN : l’intégrité des sous-ressources (SRI)", url: "https://developer.mozilla.org/fr/docs/Web/Security/Subresource_Integrity", lang: "fr" },
  mdnNosniff: { title: "MDN : l’en-tête X-Content-Type-Options", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/X-Content-Type-Options", lang: "fr" },
  mdnReferrerPolicy: { title: "MDN : l’en-tête Referrer-Policy", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/Referrer-Policy", lang: "fr" },
  mdnPermissionsPolicy: { title: "MDN : l’en-tête Permissions-Policy", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/Permissions-Policy", lang: "fr" },
  mdnHttpAuth: { title: "MDN : l’authentification HTTP", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Guides/Authentication", lang: "fr" },
  mdnObservatory: { title: "MDN HTTP Observatory : analyser les en-têtes de sécurité de son site", url: "https://developer.mozilla.org/en-US/observatory", lang: "en" },
  mdnXFrameOptions: { title: "MDN : l’en-tête X-Frame-Options", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/X-Frame-Options", lang: "fr" },
  mdnCoop: { title: "MDN : l’en-tête Cross-Origin-Opener-Policy", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/Cross-Origin-Opener-Policy", lang: "fr" },
  mdnAcao: { title: "MDN : l’en-tête Access-Control-Allow-Origin", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/Access-Control-Allow-Origin", lang: "fr" },
  mdnStatus429: { title: "MDN : le code de statut 429 Too Many Requests", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Status/429", lang: "fr" },
  mdnSecureContexts: { title: "MDN : les contextes sécurisés", url: "https://developer.mozilla.org/fr/docs/Web/Security/Secure_Contexts", lang: "fr" },
  webDevCsp: { title: "web.dev : atténuer le XSS avec une Content Security Policy stricte", url: "https://web.dev/articles/csp", lang: "en" },
  webDevSameSite: { title: "web.dev : les cookies SameSite expliqués", url: "https://web.dev/articles/samesite-cookies-explained", lang: "en" },
  rfc6265: { title: "RFC 6265 : HTTP State Management Mechanism (cookies)", url: "https://www.rfc-editor.org/rfc/rfc6265", lang: "en" },
  rfc6265bis: { title: "Brouillon IETF rfc6265bis : cookies, SameSite et préfixes", url: "https://datatracker.ietf.org/doc/draft-ietf-httpbis-rfc6265bis/", lang: "en" },
  rfc6797: { title: "RFC 6797 : HTTP Strict Transport Security (HSTS)", url: "https://www.rfc-editor.org/rfc/rfc6797", lang: "en" },
  rfc7519: { title: "RFC 7519 : JSON Web Token (JWT)", url: "https://www.rfc-editor.org/rfc/rfc7519", lang: "en" },
  rfc7515: { title: "RFC 7515 : JSON Web Signature (JWS)", url: "https://www.rfc-editor.org/rfc/rfc7515", lang: "en" },
  rfc8725: { title: "RFC 8725 : bonnes pratiques d’utilisation des JWT", url: "https://www.rfc-editor.org/rfc/rfc8725", lang: "en" },
  rfc6749: { title: "RFC 6749 : le cadre d’autorisation OAuth 2.0", url: "https://www.rfc-editor.org/rfc/rfc6749", lang: "en" },
  rfc7636: { title: "RFC 7636 : Proof Key for Code Exchange (PKCE)", url: "https://www.rfc-editor.org/rfc/rfc7636", lang: "en" },
  rfc9700: { title: "RFC 9700 : bonnes pratiques de sécurité d’OAuth 2.0", url: "https://www.rfc-editor.org/rfc/rfc9700", lang: "en" },
  rfc9116: { title: "RFC 9116 : le fichier security.txt", url: "https://www.rfc-editor.org/rfc/rfc9116", lang: "en" },
  rfc8996: { title: "RFC 8996 : abandon de TLS 1.0 et TLS 1.1", url: "https://www.rfc-editor.org/rfc/rfc8996", lang: "en" },
  rfc6454: { title: "RFC 6454 : le concept d’origine web", url: "https://www.rfc-editor.org/rfc/rfc6454", lang: "en" },
  rfc3986: { title: "RFC 3986 : syntaxe des URI", url: "https://www.rfc-editor.org/rfc/rfc3986", lang: "en" },
  rfc8259: { title: "RFC 8259 : le format JSON", url: "https://www.rfc-editor.org/rfc/rfc8259", lang: "en" },
  nist80063b4: { title: "NIST SP 800-63B-4 : lignes directrices sur l’authentification", url: "https://pages.nist.gov/800-63-4/sp800-63b.html", lang: "en" },
  cvss31Spec: { title: "FIRST : spécification CVSS v3.1", url: "https://www.first.org/cvss/v3.1/specification-document", lang: "en" },
  cvss31Calculator: { title: "FIRST : calculateur CVSS v3.1", url: "https://www.first.org/cvss/calculator/3.1", lang: "en" },
  cvss4Spec: { title: "FIRST : spécification CVSS v4.0", url: "https://www.first.org/cvss/v4.0/specification-document", lang: "en" },
  firstEpss: { title: "FIRST : EPSS, la probabilité d’exploitation d’une vulnérabilité", url: "https://www.first.org/epss/", lang: "en" },
  cwe89: { title: "CWE-89 : injection SQL", url: "https://cwe.mitre.org/data/definitions/89.html", lang: "en" },
  cwe79: { title: "CWE-79 : cross-site scripting", url: "https://cwe.mitre.org/data/definitions/79.html", lang: "en" },
  cwe352: { title: "CWE-352 : falsification de requête intersites (CSRF)", url: "https://cwe.mitre.org/data/definitions/352.html", lang: "en" },
  cwe639: { title: "CWE-639 : contournement d’autorisation par clé contrôlée par l’utilisateur", url: "https://cwe.mitre.org/data/definitions/639.html", lang: "en" },
  cwe918: { title: "CWE-918 : falsification de requête côté serveur (SSRF)", url: "https://cwe.mitre.org/data/definitions/918.html", lang: "en" },
  cwe22: { title: "CWE-22 : traversée de chemin", url: "https://cwe.mitre.org/data/definitions/22.html", lang: "en" },
  cwe78: { title: "CWE-78 : injection de commandes du système", url: "https://cwe.mitre.org/data/definitions/78.html", lang: "en" },
  cwe434: { title: "CWE-434 : téléversement de fichier de type dangereux", url: "https://cwe.mitre.org/data/definitions/434.html", lang: "en" },
  cwe611: { title: "CWE-611 : référence à une entité externe XML (XXE)", url: "https://cwe.mitre.org/data/definitions/611.html", lang: "en" },
  cwe502: { title: "CWE-502 : désérialisation de données non fiables", url: "https://cwe.mitre.org/data/definitions/502.html", lang: "en" },
  cwe798: { title: "CWE-798 : identifiants codés en dur", url: "https://cwe.mitre.org/data/definitions/798.html", lang: "en" },
  cwe862: { title: "CWE-862 : autorisation manquante", url: "https://cwe.mitre.org/data/definitions/862.html", lang: "en" },
  cwe287: { title: "CWE-287 : authentification incorrecte", url: "https://cwe.mitre.org/data/definitions/287.html", lang: "en" },
  cweTop25: { title: "CWE : le Top 25 des faiblesses logicielles les plus dangereuses", url: "https://cwe.mitre.org/top25/", lang: "en" },
  cweSite: { title: "CWE : la liste des faiblesses logicielles", url: "https://cwe.mitre.org/", lang: "en" },
  portSwiggerAcademy: { title: "PortSwigger : la Web Security Academy, des laboratoires gratuits en ligne", url: "https://portswigger.net/web-security", lang: "en" },
  dvwaRepo: { title: "DVWA : une application web volontairement vulnérable pour s’entraîner en local", url: "https://github.com/digininja/DVWA", lang: "en" },
  curlManpage: { title: "curl : la page de manuel", url: "https://curl.se/docs/manpage.html", lang: "en" },
  opensslSClient: { title: "OpenSSL : la commande s_client", url: "https://docs.openssl.org/master/man1/openssl-s_client/", lang: "en" },
  ssllabs: { title: "Qualys SSL Labs : tester la configuration TLS de son propre site", url: "https://www.ssllabs.com/ssltest/", lang: "en" },
  letsEncryptDocs: { title: "Let’s Encrypt : la documentation", url: "https://letsencrypt.org/docs/", lang: "en" },
  hstsPreload: { title: "HSTS Preload : la liste de préchargement HSTS des navigateurs", url: "https://hstspreload.org/", lang: "en" },
  cspEvaluator: { title: "CSP Evaluator : évaluer une politique de sécurité du contenu", url: "https://csp-evaluator.withgoogle.com/", lang: "en" },
  githubAdvisories: { title: "GitHub Advisory Database : les avis de sécurité des dépendances", url: "https://github.com/advisories", lang: "en" },
  npmAudit: { title: "npm : la commande npm audit", url: "https://docs.npmjs.com/cli/commands/npm-audit", lang: "en" },
  cyclonedx: { title: "CycloneDX : un format de nomenclature logicielle (SBOM)", url: "https://cyclonedx.org/", lang: "en" },
  spdx: { title: "SPDX : un format de nomenclature logicielle (SBOM)", url: "https://spdx.dev/", lang: "en" },
  slsa: { title: "SLSA : des niveaux de garantie pour la chaîne de production logicielle", url: "https://slsa.dev/", lang: "en" },
  nodeSecurityPractices: { title: "Node.js : les bonnes pratiques de sécurité", url: "https://nodejs.org/en/learn/getting-started/security-best-practices", lang: "en" },
  expressSecurity: { title: "Express : les bonnes pratiques de sécurité en production", url: "https://expressjs.com/en/advanced/best-practice-security.html", lang: "en" },
  flaskSecurity: { title: "Flask : la sécurité des applications web", url: "https://flask.palletsprojects.com/en/stable/web-security/", lang: "en" },
  djangoSecurity: { title: "Django : la sécurité dans Django", url: "https://docs.djangoproject.com/fr/5.0/topics/security/", lang: "fr" },
  phpSqlInjection: { title: "PHP : l’injection SQL", url: "https://www.php.net/manual/fr/security.database.sql-injection.php", lang: "fr" },
  phpPdoPrepared: { title: "PHP : les requêtes préparées avec PDO", url: "https://www.php.net/manual/fr/pdo.prepared-statements.php", lang: "fr" },
  anssiTls: { title: "ANSSI : recommandations de sécurité relatives à TLS", url: "https://cyber.gouv.fr/publications/recommandations-de-securite-relatives-tls", lang: "fr" },
  oidcCore: { title: "OpenID Connect Core 1.0 : la spécification", url: "https://openid.net/specs/openid-connect-core-1_0.html", lang: "en" },
  oidcHowItWorks: { title: "OpenID Connect : comment ça marche", url: "https://openid.net/developers/how-connect-works/", lang: "en" },
  // Sécurité Web (compléments issus des vérifications).
  nodeUrl: { title: "Node.js : le module url", url: "https://nodejs.org/api/url.html", lang: "en" },
  nodeHttp: { title: "Node.js : le module http", url: "https://nodejs.org/api/http.html", lang: "en" },
  nodeSqlite: { title: "Node.js : le module node:sqlite", url: "https://nodejs.org/api/sqlite.html", lang: "en" },
  nodeChildProcess: { title: "Node.js : le module child_process", url: "https://nodejs.org/api/child_process.html", lang: "en" },
  nodeCrypto: { title: "Node.js : le module crypto", url: "https://nodejs.org/api/crypto.html", lang: "en" },
  nodeFs: { title: "Node.js : le module fs", url: "https://nodejs.org/api/fs.html", lang: "en" },
  nodeConsole: { title: "Node.js : le module console", url: "https://nodejs.org/api/console.html", lang: "en" },
  letsEncryptFaq: { title: "Let’s Encrypt : la foire aux questions", url: "https://letsencrypt.org/docs/faq/", lang: "en" },
  mdnSecFetchSite: { title: "MDN : l’en-tête Sec-Fetch-Site", url: "https://developer.mozilla.org/fr/docs/Web/HTTP/Reference/Headers/Sec-Fetch-Site", lang: "fr" },
  awsImds: { title: "AWS : configurer le service de métadonnées d’instance (IMDS)", url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html", lang: "en" },
  owaspCsGraphql: { title: "OWASP : aide-mémoire sur la sécurité de GraphQL", url: "https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html", lang: "en" },
  mdnTrustedTypes: { title: "MDN : l’API Trusted Types", url: "https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API", lang: "en" },
  mdnCspReportTo: { title: "MDN : la directive CSP report-to", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy/report-to", lang: "en" },
  mdnCspReportUri: { title: "MDN : la directive CSP report-uri", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy/report-uri", lang: "en" },
  mdnReportingEndpoints: { title: "MDN : l’en-tête Reporting-Endpoints", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Reporting-Endpoints", lang: "en" },
  npmCi: { title: "npm : la commande npm ci", url: "https://docs.npmjs.com/cli/v10/commands/npm-ci", lang: "en" },
  npmSemver: { title: "npm : le versionnage sémantique", url: "https://docs.npmjs.com/about-semantic-versioning", lang: "en" },
  npmEventStream: { title: "npm : l’incident event-stream", url: "https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident.html", lang: "en" },
  nvdLog4shell: { title: "NVD : CVE-2021-44228 (Log4Shell)", url: "https://nvd.nist.gov/vuln/detail/CVE-2021-44228", lang: "en" },
  nvdXzBackdoor: { title: "NVD : CVE-2024-3094 (porte dérobée xz/liblzma)", url: "https://nvd.nist.gov/vuln/detail/CVE-2024-3094", lang: "en" },
  modsecurity: { title: "ModSecurity : le moteur de pare-feu applicatif open source", url: "https://modsecurity.org/", lang: "en" },
  owaspCrs: { title: "OWASP CRS : le jeu de règles génériques de détection", url: "https://coreruleset.org/", lang: "en" },
  owaspWstgCategories: { title: "OWASP WSTG : les catégories de tests de la version actuelle", url: "https://wstg.owasp.org/latest/4-Web_Application_Security_Testing/", lang: "en" },
  cisaKev: { title: "CISA : le catalogue des vulnérabilités exploitées (KEV)", url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog", lang: "en" },
  // Pentest.
  nmapSite: { title: "Nmap : le site du projet", url: "https://nmap.org/", lang: "en" },
  nmapBriefOptions: { title: "Nmap : résumé des options", url: "https://nmap.org/book/man-briefoptions.html", lang: "en" },
  nmapScanTechniques: { title: "Nmap : les techniques de scan de ports", url: "https://nmap.org/book/man-port-scanning-techniques.html", lang: "en" },
  nmapPortSpecification: { title: "Nmap : choisir les ports à scanner", url: "https://nmap.org/book/man-port-specification.html", lang: "en" },
  nmapHostDiscovery: { title: "Nmap : la découverte d’hôtes", url: "https://nmap.org/book/man-host-discovery.html", lang: "en" },
  nmapVersionDetection: { title: "Nmap : la détection de version", url: "https://nmap.org/book/man-version-detection.html", lang: "en" },
  nmapOutputFormats: { title: "Nmap : les formats de sortie", url: "https://nmap.org/book/man-output.html", lang: "en" },
  nmapScriptingEngine: { title: "Nmap : le moteur de scripts (NSE)", url: "https://nmap.org/book/nse.html", lang: "en" },
  nmapScriptUsage: { title: "Nmap : utiliser les scripts NSE", url: "https://nmap.org/book/nse-usage.html", lang: "en" },
  nmapPerformance: { title: "Nmap : performance et temps de scan", url: "https://nmap.org/book/performance.html", lang: "en" },
  nmapLegalIssues: { title: "Nmap : les questions juridiques du scan de ports", url: "https://nmap.org/book/legal-issues.html", lang: "en" },
  npcap: { title: "Npcap : la bibliothèque de capture de paquets pour Windows", url: "https://npcap.com/", lang: "en" },
  nist80115: { title: "NIST SP 800-115 : guide technique des tests et évaluations de sécurité", url: "https://csrc.nist.gov/pubs/sp/800/115/final", lang: "en" },
  nistGlossaryPentest: { title: "NIST : définition du test d’intrusion", url: "https://csrc.nist.gov/glossary/term/penetration_testing", lang: "en" },
  nistGlossaryRoE: { title: "NIST : définition des règles d’engagement", url: "https://csrc.nist.gov/glossary/term/rules_of_engagement", lang: "en" },
  ncscPentest: { title: "NCSC (Royaume-Uni) : le test d’intrusion, guide pour les organisations", url: "https://www.ncsc.gov.uk/guidance/penetration-testing", lang: "en" },
  wstgStable: { title: "OWASP : le guide de test de sécurité web (WSTG), version stable", url: "https://wstg.owasp.org/stable/", lang: "en" },
  mitreEnterpriseMatrix: { title: "MITRE ATT&CK : la matrice Enterprise", url: "https://attack.mitre.org/matrices/enterprise/", lang: "en" },
  mitreTechniques: { title: "MITRE ATT&CK : la liste des techniques Enterprise", url: "https://attack.mitre.org/techniques/enterprise/", lang: "en" },
  mitreD3fend: { title: "MITRE D3FEND : les contre-mesures défensives associées aux techniques d’attaque", url: "https://d3fend.mitre.org/", lang: "en" },
  crtSh: { title: "crt.sh : chercher dans les journaux de transparence des certificats", url: "https://crt.sh/", lang: "en" },
  rfc9082: { title: "RFC 9082 : format des requêtes RDAP", url: "https://www.rfc-editor.org/rfc/rfc9082", lang: "en" },
  rfc9083: { title: "RFC 9083 : format JSON des réponses RDAP", url: "https://www.rfc-editor.org/rfc/rfc9083", lang: "en" },
  greenboneDocs: { title: "Greenbone (OpenVAS) : la documentation", url: "https://greenbone.github.io/docs/latest/", lang: "en" },
  nucleiDocs: { title: "Nuclei : la documentation du scanner à modèles", url: "https://docs.projectdiscovery.io/opensource/nuclei/overview", lang: "en" },
  zapGettingStarted: { title: "ZAP : prise en main de l’application de bureau", url: "https://www.zaproxy.org/docs/desktop/start/", lang: "en" },
  burpGettingStarted: { title: "Burp Suite : prise en main", url: "https://portswigger.net/burp/documentation/desktop/getting-started", lang: "en" },
  metasploitDocs: { title: "Metasploit : la documentation du framework", url: "https://docs.metasploit.com/", lang: "en" },
  metasploitable3: { title: "Metasploitable 3 : une machine virtuelle volontairement vulnérable pour s’entraîner", url: "https://github.com/rapid7/metasploitable3", lang: "en" },
  juiceShopRepo: { title: "OWASP Juice Shop : le projet et son installation", url: "https://github.com/juice-shop/juice-shop", lang: "en" },
  juiceShopGuide: { title: "OWASP Juice Shop : le guide d’accompagnement (Pwning OWASP Juice Shop)", url: "https://pwning.owasp-juice.shop/", lang: "en" },
  juiceShopDocker: { title: "OWASP Juice Shop : l’image Docker officielle", url: "https://hub.docker.com/r/bkimminich/juice-shop", lang: "en" },
  tryHackMe: { title: "TryHackMe : des parcours d’apprentissage guidés en ligne", url: "https://tryhackme.com/", lang: "en" },
  hackTheBox: { title: "Hack The Box : des laboratoires d’entraînement en ligne", url: "https://www.hackthebox.com/", lang: "en" },
  overTheWire: { title: "OverTheWire : des jeux de guerre pour apprendre les bases en ligne de commande", url: "https://overthewire.org/wargames/", lang: "en" },
  picoCtf: { title: "picoCTF : des défis de cybersécurité pour débutants", url: "https://picoctf.org/", lang: "en" },
  vulnHub: { title: "VulnHub : des machines virtuelles vulnérables à télécharger pour s’entraîner", url: "https://www.vulnhub.com/", lang: "en" },
  dockerGetStarted: { title: "Docker : prise en main", url: "https://docs.docker.com/get-started/", lang: "en" },
  dockerRunReference: { title: "Docker : la commande docker run", url: "https://docs.docker.com/reference/cli/docker/container/run/", lang: "en" },
  dockerNetworking: { title: "Docker : la mise en réseau des conteneurs", url: "https://docs.docker.com/engine/network/", lang: "en" },
  hyperVOverview: { title: "Microsoft : présentation de Hyper-V", url: "https://learn.microsoft.com/fr-fr/windows-server/virtualization/hyper-v/overview?pivots=windows", lang: "fr" },
  kaliDocs: { title: "Kali Linux : la documentation officielle", url: "https://www.kali.org/docs/", lang: "en" },
  wiresharkSampleCaptures: { title: "Wireshark : des captures d’exemple à télécharger", url: "https://wiki.wireshark.org/SampleCaptures", lang: "en" },
  owaspVulnDisclosure: { title: "OWASP : aide-mémoire sur la divulgation de vulnérabilités", url: "https://cheatsheetseries.owasp.org/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.html", lang: "en" },
  projectZeroPolicy: { title: "Google Project Zero : sa politique de divulgation des vulnérabilités", url: "https://projectzero.google/vulnerability-disclosure-policy.html", lang: "en" },
  securityTxtSite: { title: "security.txt : le site du standard", url: "https://securitytxt.org/", lang: "en" },
  certFrContact: { title: "CERT-FR : comment le contacter", url: "https://www.cert.ssi.gouv.fr/contact/", lang: "fr" },
  awsPentestPolicy: { title: "AWS : la politique sur les tests d’intrusion", url: "https://aws.amazon.com/fr/security/penetration-testing/", lang: "fr" },
  azurePentest: { title: "Microsoft Azure : les tests d’intrusion sur Azure", url: "https://learn.microsoft.com/en-us/azure/security/fundamentals/pen-testing", lang: "en" },
  msrcPentestRules: { title: "Microsoft : les règles d’engagement des tests d’intrusion sur le cloud Microsoft", url: "https://www.microsoft.com/en-us/msrc/pentest-rules-of-engagement", lang: "en" },
  eurLexRgpd: { title: "EUR-Lex : le texte du règlement général sur la protection des données (RGPD)", url: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32016R0679", lang: "fr" },
  epssApi: { title: "FIRST : l’API publique d’EPSS", url: "https://api.first.org/epss/", lang: "en" },
  nvdCvss31Calculator: { title: "NVD : le calculateur CVSS 3.x", url: "https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator", lang: "en" },
  hibpApi: { title: "Have I Been Pwned : l’API publique (dont Pwned Passwords)", url: "https://haveibeenpwned.com/API/v3", lang: "en" },
  msAdBestPractices: { title: "Microsoft : bonnes pratiques de sécurisation d’Active Directory", url: "https://learn.microsoft.com/fr-fr/windows-server/identity/ad-ds/plan/security-best-practices/best-practices-for-securing-active-directory", lang: "fr" },
  msAdPrivilegedGroups: { title: "Microsoft : comptes et groupes privilégiés dans Active Directory", url: "https://learn.microsoft.com/fr-fr/windows-server/identity/ad-ds/plan/security-best-practices/appendix-b--privileged-accounts-and-groups-in-active-directory", lang: "fr" },
  anssiActiveDirectory: { title: "ANSSI : recommandations de sécurité relatives à Active Directory", url: "https://messervices.cyber.gouv.fr/guides/recommandations-de-securite-relatives-active-directory", lang: "fr" },
  wifiAllianceSecurity: { title: "Wi-Fi Alliance : la sécurité du Wi-Fi (WPA3)", url: "https://www.wi-fi.org/security", lang: "en" },
  msNetshWlan: { title: "Microsoft : la commande netsh wlan", url: "https://learn.microsoft.com/fr-fr/windows-server/administration/windows-commands/netsh-wlan", lang: "fr" },
  gophishDocs: { title: "Gophish : la documentation de la plateforme libre de simulation d’hameçonnage", url: "https://getgophish.com/documentation/", lang: "en" },
  signalSpam: { title: "Signal Spam : signaler les courriels indésirables et d’hameçonnage", url: "https://www.signal-spam.fr/", lang: "fr" },
  gitleaksRepo: { title: "Gitleaks : détecter les secrets dans un dépôt Git", url: "https://github.com/gitleaks/gitleaks", lang: "en" },
  trufflehogRepo: { title: "TruffleHog : détecter les secrets exposés", url: "https://github.com/trufflesecurity/trufflehog", lang: "en" },
  pingCastleSite: { title: "PingCastle : un outil d’audit de la sécurité d’Active Directory", url: "https://www.pingcastle.com/", lang: "en" },
  nodeNet: { title: "Node.js : l’API net (adresses IP, BlockList)", url: "https://nodejs.org/api/net.html", lang: "en" },
  nodeOs: { title: "Node.js : l’API os", url: "https://nodejs.org/api/os.html", lang: "en" },
  nodeCliOptions: { title: "Node.js : les options de la ligne de commande", url: "https://nodejs.org/api/cli.html", lang: "en" },
  nvdCveProcess: { title: "NVD : les CVE et le processus de la NVD", url: "https://nvd.nist.gov/general/cve-process", lang: "en" },
  cveProgramOverview: { title: "CVE : présentation du programme", url: "https://www.cve.org/About/Overview", lang: "en" },
  // Pentest (compléments issus de la fiche technique).
  budapestConvention: { title: "Convention de Budapest sur la cybercriminalité (texte du traité)", url: "https://assets.publishing.service.gov.uk/media/5a7c929ded915d6969f45d32/8309.pdf", lang: "en" },
  nis2Directive: { title: "Union européenne : la directive NIS 2 (2022/2555)", url: "https://eur-lex.europa.eu/eli/dir/2022/2555/oj/eng", lang: "en" },
  iso29147: { title: "ISO/IEC 29147 : la divulgation de vulnérabilités", url: "https://www.iso.org/standard/72311.html", lang: "en" },
  iso30111: { title: "ISO/IEC 30111 : le traitement des vulnérabilités", url: "https://www.iso.org/standard/69725.html", lang: "en" },
  osstmmIsecom: { title: "ISECOM : la méthodologie OSSTMM", url: "https://www.isecom.org/research.html", lang: "en" },
  rfc9162: { title: "RFC 9162 : la transparence des certificats, version 2.0", url: "https://www.rfc-editor.org/rfc/rfc9162.txt", lang: "en" },
  mitreVersionHistory: { title: "MITRE ATT&CK : l’historique des versions", url: "https://attack.mitre.org/resources/versions/", lang: "en" },
  tiberEu: { title: "Banque centrale européenne : le cadre TIBER-EU", url: "https://www.ecb.europa.eu/paym/cyber-resilience/tiber-eu/html/index.en.html", lang: "en" },
  cbestBoE: { title: "Banque d’Angleterre : le cadre CBEST", url: "https://www.bankofengland.co.uk/financial-stability/operational-resilience-of-the-financial-sector/cbest-threat-intelligence-led-assessments-implementation-guide", lang: "en" },
  passiAnssi: { title: "ANSSI : le référentiel de qualification des prestataires d’audit (PASSI)", url: "https://cyber.gouv.fr/offre-de-service/solutions-certifiees-et-qualifiees/comprendre-levaluation-de-securite/qualification-de-produit-et-services/referentiels-qualification/", lang: "fr" },
  crestAccreditation: { title: "CREST : l’accréditation des prestataires de tests d’intrusion", url: "https://www.crest-approved.org/membership/accreditation/", lang: "en" },
  pciDssLibrary: { title: "PCI Security Standards Council : la bibliothèque de documents", url: "https://www.pcisecuritystandards.org/document_library/", lang: "en" },
  trivyDocs: { title: "Trivy : la documentation du scanner de vulnérabilités", url: "https://trivy.dev/latest/docs/", lang: "en" },
  wslOverview: { title: "Microsoft : qu’est-ce que le sous-système Windows pour Linux (WSL)", url: "https://learn.microsoft.com/en-us/windows/wsl/about", lang: "en" },
  vmwareWorkstationDocs: { title: "VMware : la documentation de Workstation", url: "https://docs.vmware.com/", lang: "en" },
  rootMe: { title: "Root-Me : une plateforme d’entraînement en cybersécurité", url: "https://www.root-me.org/", lang: "fr" },
  zaproxyLicense: { title: "OWASP ZAP : la licence du projet", url: "https://github.com/zaproxy/zaproxy/blob/main/LICENSE", lang: "en" },
  rfc9106: { title: "RFC 9106 : la fonction de hachage Argon2", url: "https://www.rfc-editor.org/rfc/rfc9106.txt", lang: "en" },
  phpPasswordHash: { title: "PHP : la fonction password_hash", url: "https://www.php.net/manual/en/function.password-hash.php", lang: "en" },
  msNlmp: { title: "Microsoft : le protocole d’authentification NTLM (MS-NLMP)", url: "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/", lang: "en" },
  cryptManpage: { title: "Linux : la page de manuel crypt(3)", url: "https://man7.org/linux/man-pages/man3/crypt.3.html", lang: "en" },
  rfc1321: { title: "RFC 1321 : la fonction de hachage MD5", url: "https://www.rfc-editor.org/rfc/rfc1321.html", lang: "en" },
  fips1804: { title: "NIST : le standard de hachage sécurisé FIPS 180-4", url: "https://csrc.nist.gov/pubs/fips/180-4/upd1/final", lang: "en" },
  githubSecretScanning: { title: "GitHub : la détection de secrets dans le code", url: "https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning", lang: "en" },
  gophishRepo: { title: "Gophish : le dépôt du projet de simulation d’hameçonnage", url: "https://github.com/gophish/gophish", lang: "en" },

} as const satisfies Record<string, { title: string; url: string; lang: "fr" | "en" }>;

export type ReferenceKey = keyof typeof REFERENCES;

/** A "Pour aller plus loin" link; the caption says when the source is in English. */
export const reference = (key: ReferenceKey, caption?: string): PathBlock => {
  const entry = REFERENCES[key];
  return { type: "resource", url: entry.url, content: `${caption ?? entry.title}${entry.lang === "en" ? " (en anglais)" : ""}` };
};

// --- Quiz questions -----------------------------------------------------------------------------

export const questions = {
  tf: (prompt: string, truth: boolean, explanation: string, difficulty: Difficulty = "facile"): PathQuestion => ({
    type: "true_false", prompt, options: ["Vrai", "Faux"], correct: truth ? 0 : 1, explanation, difficulty,
  }),
  choice: (prompt: string, options: string[], correct: number, explanation: string, difficulty: Difficulty = "facile"): PathQuestion => ({
    type: "single_choice", prompt, options, correct, explanation, difficulty,
  }),
  /** All the right options must be ticked and no other: a partial answer scores nothing. */
  multi: (prompt: string, options: string[], correct: number[], explanation: string, difficulty: Difficulty = "moyen"): PathQuestion => ({
    type: "multiple_choice", prompt, options, correct, explanation, difficulty,
  }),
};
