import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const passwordAuditLesson: NewLesson = {
  key: "pt-mots-de-passe-audit",
  title: "Auditer une politique de mots de passe et des empreintes",
  summary: "Tu apprends à juger une politique de mots de passe, à reconnaître des formats d’empreintes et à décrire un risque sans jamais glisser vers le cassage.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("évaluer une politique de mots de passe, reconnaître des formats d’empreintes, estimer un espace de recherche, puis formuler un constat défensif sans proposer de cassage."),
    prerequisites("connaître les bases de l’authentification et comprendre qu’un mot de passe côté serveur doit être haché, pas stocké en clair."),
    scenario("Awa reçoit un export de comptes de la boutique Soleil. Le client veut savoir si sa politique de mots de passe est saine et si les empreintes stockées semblent modernes. Awa ne doit ni casser les mots de passe ni manipuler des données réelles : elle doit lire, classer et recommander."),
    videoSlot("Auditer des empreintes sans basculer vers le cassage"),
    text("Auditer des mots de passe dans un pentest défensif commence par une distinction simple : on évalue d’abord la politique, ensuite le stockage, puis le risque. La politique décrit la longueur minimale, la prise en charge d’un gestionnaire de mots de passe, la présence d’une blocklist, la rotation et l’usage éventuel d’un second facteur. Le stockage décrit ce que le serveur garde réellement : un hachage adapté, un sel, parfois des paramètres de coût. Le risque vient du croisement des deux, pas d’une fascination pour le « mot de passe fort » isolé."),
    schema([
      "Trois questions utiles",
      "",
      "politique : longueur, MFA, blocklist ?",
      "stockage  : hachage moderne, sel, coût ?",
      "risque    : comptes sensibles, réutilisation ?",
      "",
      "On audite, on ne casse pas",
    ].join("\n")),
    text("La référence la plus utile pour ce cours reste NIST SP 800-63B-4. Retenir l’essentiel suffit : quand le mot de passe est le seul facteur, la longueur minimale attendue est de 15 caractères ; dans un parcours MFA, le minimum NIST descend à 8 caractères. Le vérificateur doit aussi accepter le collage, les gestionnaires de mots de passe et comparer les nouveaux secrets à une blocklist. En revanche, imposer une rotation périodique sans compromission connue est une mauvaise habitude, parce qu’elle pousse souvent vers des variantes faibles et prévisibles."),
    schema([
      "Indices de format à reconnaître",
      "",
      "$argon2id$  -> Argon2id",
      "$2y$        -> bcrypt",
      "$6$         -> SHA-512 crypt",
      "32 hexa      -> souvent MD5, à confirmer",
      "",
      "Indice utile, jamais verdict seul",
    ].join("\n")),
    text("Reconnaître un format d’empreinte sert à inventer moins, pas à « faire du crack ». RFC 9106 rappelle qu’Argon2id doit être pris en charge et l’aide-mémoire OWASP sur le stockage des mots de passe recommande au minimum 19 MiB de mémoire, 2 itérations et 1 degré de parallélisme. En pratique, une chaîne qui commence par « $argon2id$ » suggère un choix moderne. Dans les sorties PHP courantes, « $2y$ » renvoie à bcrypt. Sous Unix, « $6$ » évoque SHA-512 crypt. Une longueur hexadécimale de 32 caractères peut signaler un format ancien comme MD5, mais elle ne suffit jamais à conclure seule. Le bon constat dit par exemple : « plusieurs empreintes courtes et homogènes suggèrent un format ancien ou mal adapté, à confirmer côté plateforme »."),
    text("Démonstration guidée : les calculs ci-dessous servent uniquement à comparer des politiques et à reconnaître des formats factices. Ils n’attaquent rien et n’essaient aucun mot de passe. Vérifie d’abord « node --version », puis lis ce script local. Il compare l’espace de recherche de trois politiques et classe quelques empreintes de démonstration à partir de leur préfixe ou de leur longueur."),
    code([
      "# fichier demo-mots-de-passe-audit.cjs",
      "const alphabet = 26 + 26 + 10;",
      "const policies = [",
      "  { label: '8 caracteres avec MFA', length: 8 },",
      "  { label: '12 caracteres avec MFA', length: 12 },",
      "  { label: '15 caracteres facteur unique', length: 15 },",
      "];",
      "const hashes = [",
      "  '$argon2id$v=19$m=19456,t=2,p=1$sel$empreinte',",
      "  '$2y$12$abcdefghijklmnopqrstuuuuuuuuuuuuuuuuuuuuuuuu',",
      "  '$6$sel$abcdefgh',",
      "  '5f4dcc3b5aa765d61d8327deb882cf99',",
      "];",
      "const classify = (value) => {",
      "  if (value.startsWith('$argon2id$')) return 'argon2id';",
      "  if (value.startsWith('$2y$')) return 'bcrypt';",
      "  if (value.startsWith('$6$')) return 'sha512-crypt';",
      "  if (/^[a-f0-9]{32}$/i.test(value)) return 'hex32 a confirmer';",
      "  return 'inconnu';",
      "};",
      "const rows = policies.map((item) => ({",
      "  label: item.label,",
      "  possibilities: Number((BigInt(alphabet) ** BigInt(item.length)).toString().slice(0, 6)),",
      "}));",
      "console.log(JSON.stringify({ rows, formats: hashes.map(classify) }, null, 2));",
      "# exemple de sortie (valeurs fictives)",
      "# {",
      "#   \"rows\": [",
      "#     { \"label\": \"8 caracteres avec MFA\", \"possibilities\": 218340 },",
      "#     { \"label\": \"12 caracteres avec MFA\", \"possibilities\": 322626 },",
      "#     { \"label\": \"15 caracteres facteur unique\", \"possibilities\": 768909 }",
      "#   ],",
      "#   \"formats\": [\"argon2id\", \"bcrypt\", \"sha512-crypt\", \"hex32 a confirmer\"]",
      "# }",
    ].join("\n"), "javascript"),
    text("Le nombre affiché dans « possibilities » est volontairement tronqué pour rester lisible sur mobile. L’idée à retenir n’est pas la valeur complète, mais l’écart de taille entre 8, 12 et 15 caractères quand on garde le même alphabet. Une politique un peu plus longue, compatible avec un gestionnaire de mots de passe et appuyée par une blocklist, protège mieux qu’une politique courte combinée à des rotations fréquentes et pénibles."),
    example("Exemple corrigé : un client impose 8 caractères, un changement mensuel et aucune MFA. Un autre accepte 15 caractères en facteur unique, autorise le collage, vérifie les mots de passe compromis et ne force pas la rotation sans incident. Le second cadre est généralement plus sain. Si, en plus, l’export montre des préfixes « $argon2id$ », tu peux écrire que la politique et le stockage vont dans le bon sens. Si tu vois surtout des longueurs hexadécimales courtes à confirmer, tu notes le doute et tu demandes une vérification côté plateforme, sans jamais proposer de dictionnaire ni d’outil de cassage."),
    mistakes("confondre hachage et chiffrement ; appeler « bcrypt » toute chaîne qui commence par « $ » ; croire qu’une rotation mensuelle compense une politique courte ; glisser de l’inventaire d’empreintes vers le cassage."),
    safety("tu ne testes jamais de cassage de mots de passe dans ce parcours. Tu travailles sur des empreintes factices ou fournies pour lecture, tu masques les données sensibles et tu restes dans un cadre autorisé, avec des comptes de démonstration ou un laboratoire personnel."),
    takeaway("une bonne revue sépare la politique, le stockage et le risque. NIST insiste sur la longueur, la blocklist et l’usage des gestionnaires. Reconnaître un format d’empreinte sert à décrire et corriger, pas à attaquer."),
    practice("Travaille dans « TP 2 : auditer des mots de passe et des comptes » : tu y reliras des politiques et des empreintes fournies pour qualifier le stockage et le niveau de risque, puis tu termineras par le quiz."),
    reference("nist80063b4"),
    reference("owaspPasswordStorage"),
    reference("phpPasswordHash"),
    reference("cryptManpage"),
    reference("anssiMfa"),
    reference("rfc9106"),
  ],
  quiz: {
    title: "Quiz : politique de mots de passe et empreintes",
    questions: [
      questions.choice("Quel constat est le plus défendable pendant un audit de mots de passe ?", ["« On va lancer un cassage pour être fixés »", "« La politique et le format des empreintes suggèrent un risque, à confirmer sans casser »", "« Un mot de passe long rend inutile la MFA »", "« Toute rotation mensuelle est une bonne pratique moderne »"], 1, "En pentest défensif, tu décris ce que la politique et le stockage suggèrent, puis tu recommandes une vérification ou une correction. La mauvaise réponse la plus tentante est le cassage « pour être sûr », justement exclu du cadre pédagogique et éthique du cours.", "facile"),
      questions.choice("Quelle affirmation reflète le mieux NIST SP 800-63B-4 dans ce parcours ?", ["Toujours exiger une rotation mensuelle", "Autoriser le collage, les gestionnaires et vérifier une blocklist", "Interdire les phrases de passe longues", "Exiger une règle fixe du type majuscule, chiffre, symbole"], 1, "Le repère utile ici est l’acceptation des gestionnaires, du collage et la comparaison avec une blocklist, plutôt qu’une composition artificielle ou une rotation automatique sans compromission. La réponse tentante est la politique de complexité imposée, très répandue mais moins solide qu’on le croit.", "moyen"),
      questions.multi("Dans un extrait de base, quelles lignes donnent un indice de format exploitable pour l’inventaire ? (plusieurs réponses)", ["« $argon2id$... »", "« $2y$... »", "« $6$... »", "« 5f4dcc3b5aa765d61d8327deb882cf99 »", "« 8f3a »"], [0, 1, 2, 3], "Les quatre premières chaînes donnent un indice utile : trois par leur préfixe explicite, la quatrième par sa longueur hexadécimale de 32 caractères, fréquente pour certains formats anciens. La dernière, trop courte pour correspondre à une longueur d’empreinte connue, ne permet aucune conclusion. L’erreur classique est de croire que seuls les préfixes « $ » sont parlants, alors que la longueur peut aussi orienter l’inventaire, sans jamais suffire à elle seule.", "difficile"),
      questions.tf("Une politique de 15 caractères en facteur unique, avec blocklist et gestionnaire de mots de passe, peut être plus saine qu’une politique de 8 caractères avec rotation mensuelle.", true, "Vrai : la longueur réelle, la prise en charge des gestionnaires et l’absence de rotation arbitraire améliorent souvent la qualité des secrets choisis. La rotation forcée seule rassure parfois, mais elle produit souvent des variantes prévisibles et n’efface pas une politique trop courte.", "moyen"),
    ],
  },
};

const secretsConfigurationLesson: NewLesson = {
  key: "pt-secrets-configuration",
  title: "Chercher les secrets et les mauvaises configurations",
  summary: "Tu apprends à reconnaître des secrets exposés et des réglages dangereux, puis à rédiger un constat utile sans recopier ni réutiliser la donnée trouvée.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("repérer des emplacements de secrets fréquents, distinguer une exposition prouvée d’un simple indice, décider quoi masquer, puis proposer une remédiation proportionnée."),
    prerequisites("avoir compris qu’un test d’intrusion documente le risque et la correction, sans utiliser un secret trouvé ni fouiller un dépôt tiers hors périmètre."),
    scenario("Ama relit l’arborescence d’une application de l’association Teranga. Elle voit un fichier « .env », une ancienne sauvegarde « config.old », un message d’erreur détaillé et un dépôt Git exposé dans une note de scanner. Son rôle est de prouver ce qui est visible, de minimiser la donnée et de recommander la rotation ou le nettoyage adaptés."),
    videoSlot("Décrire un secret exposé sans le recopier"),
    text("Dans une mission défensive, un secret exposé n’est jamais un trophée. C’est un indice de risque qui demande une preuve minimale, une qualification honnête et une correction rapide. Un fichier « .env », un dépôt « .git » accessible, une sauvegarde oubliée, un stockage public trop large, une valeur sensible dans un journal ou un compte par défaut sont des signaux fréquents. Mais leur simple présence n’a pas tous le même sens : tu dois distinguer ce qui est réellement exposé, ce qui n’est qu’un nom de fichier, et ce qui demande une confirmation supplémentaire."),
    schema([
      "Trois niveaux utiles",
      "",
      "indice       -> nom de fichier, note de scan",
      "exposition   -> lecture ou acces prouve",
      "impact       -> portee du secret ou du reglage",
      "",
      "Toujours masquer la valeur",
    ].join("\n")),
    text("Le bon réflexe consiste à lier secrets et mauvaise configuration. Une clé d’API dans un fichier public relève souvent aussi d’une gouvernance incomplète : séparation des environnements, portée excessive du secret, absence de rotation, journalisation trop bavarde ou revue de code insuffisante. Un CORS trop large, un mode debug resté actif, des erreurs détaillées ou un panneau d’administration exposé ne sont pas des secrets, mais participent au même problème : le système révèle plus qu’il ne devrait."),
    schema([
      "Correction défensive typique",
      "",
      "1. limiter l’exposition",
      "2. faire tourner le secret",
      "3. réduire sa portée",
      "4. nettoyer copies et journaux",
      "5. vérifier la non-régression",
    ].join("\n")),
    text("Documenter un secret exposé ne signifie jamais le recopier. Dans le rapport, tu écris par exemple « une clé d’API de démonstration était visible dans un fichier de configuration accessible », puis tu précises le chemin, le contexte et la remédiation attendue. Tu peux conserver une preuve minimale convenue, comme le début et la fin d’une valeur factice, mais pas la totalité si elle n’est pas nécessaire. Le même principe vaut pour les mauvaises configurations : prouver qu’une page de débogage répond ou qu’un en-tête CORS accepte trop largement, sans multiplier les essais ni abuser de l’exposition."),
    text("Démonstration guidée : le script suivant crée un petit inventaire fictif de fichiers et de réglages, puis les classe en « exposition prouvée », « à vérifier » ou « configuration faible ». Il n’utilise aucun secret réel et ne contacte rien. Il sert seulement à t’entraîner à écrire une note propre et à déclencher la bonne séquence de correction."),
    code([
      "# fichier demo-secrets-configuration.cjs",
      "const findings = [",
      "  { item: '.env', readable: true, kind: 'secret' },",
      "  { item: 'config.old', readable: true, kind: 'secret' },",
      "  { item: 'debug=true', readable: true, kind: 'config' },",
      "  { item: 'Server: nginx', readable: true, kind: 'weak-indicator' },",
      "  { item: '.git', readable: false, kind: 'to-confirm' },",
      "];",
      "const classify = (entry) => {",
      "  if (entry.kind === 'secret' && entry.readable) return 'exposition_prouvee';",
      "  if (entry.kind === 'config') return 'configuration_faible';",
      "  if (entry.kind === 'to-confirm') return 'a_verifier';",
      "  return 'indice_faible';",
      "};",
      "console.log(JSON.stringify(findings.map((entry) => ({ item: entry.item, status: classify(entry) })), null, 2));",
      "# exemple de sortie (valeurs fictives)",
      "# [",
      "#   { \"item\": \".env\", \"status\": \"exposition_prouvee\" },",
      "#   { \"item\": \"config.old\", \"status\": \"exposition_prouvee\" },",
      "#   { \"item\": \"debug=true\", \"status\": \"configuration_faible\" },",
      "#   { \"item\": \"Server: nginx\", \"status\": \"indice_faible\" },",
      "#   { \"item\": \".git\", \"status\": \"a_verifier\" }",
      "# ]",
    ].join("\n"), "javascript"),
    text("L’intérêt du tri est visible tout de suite. Un simple en-tête « Server » n’a pas le même poids qu’un fichier « .env » réellement lisible. À l’inverse, un chemin « .git » mentionné dans un export de scanner ne vaut pas encore exposition prouvée si aucune note ne démontre la lecture. Cette discipline évite de gonfler artificiellement la gravité, tout en accélérant la bonne réponse côté client : réduire l’exposition, faire tourner le secret, limiter sa portée et vérifier ce qui reste en circulation."),
    example("Exemple corrigé : Ama constate qu’un export de scanner mentionne « .env » et qu’une note humaine précise qu’un fichier de configuration lisible contenait une clé de démonstration. Le constat défendable est donc double : secret exposé et mauvaise gestion de configuration. La recommandation utile n’est pas « cacher la page », mais « retirer le fichier de l’exposition publique, faire tourner la clé, réduire sa portée, vérifier les journaux et les copies, puis confirmer qu’aucun autre emplacement public ne révèle la même donnée »."),
    mistakes("copier un secret dans le rapport ; confondre présence d’un nom de fichier et exposition réelle ; surestimer un simple en-tête technique ; oublier la rotation et la réduction de portée après une fuite."),
    safety("tu ne réutilises jamais un secret trouvé et tu n’essaies jamais de pivoter grâce à lui dans ce parcours. Tu travailles sur des valeurs factices ou des preuves minimales autorisées, en masquant toute donnée sensible dans tes notes et dans le rapport."),
    takeaway("un secret exposé demande une preuve minimale, une qualification honnête et une remédiation complète : retrait de l’exposition, rotation, réduction de portée et nettoyage. Une mauvaise configuration se juge par ce qu’elle révèle ou permet réellement, pas par un simple indice isolé."),
    practice("Travaille dans « TP 4 : trier le rapport d’un scanner de vulnérabilités » : tu y distingueras les expositions réellement prouvées, les indices à vérifier et les remédiations prioritaires, puis tu termineras par le quiz."),
    reference("owaspTop10A02"),
    reference("owaspCsSecrets"),
    reference("owaspCsHeaders"),
    reference("anssiHygiene"),
    reference("githubSecretScanning"),
  ],
  quiz: {
    title: "Quiz : secrets et mauvaises configurations",
    questions: [
      questions.choice("Quel comportement est correct quand un secret apparaît dans une preuve d’audit ?", ["Le recopier intégralement pour impressionner le client", "Le masquer et décrire l’exposition ainsi que la correction attendue", "L’utiliser pour confirmer d’autres accès", "Le publier pour accélérer la rotation"], 1, "La bonne pratique consiste à masquer la valeur, à décrire le contexte d’exposition et à recommander rotation, réduction de portée et nettoyage. La fausse bonne idée la plus tentante est la recopie intégrale, qui augmente inutilement le risque et n’apporte pas de preuve supplémentaire.", "facile"),
      questions.choice("Quelle phrase décrit le mieux la différence entre un indice et une exposition prouvée ?", ["Un nom de fichier « .env » prouve à lui seul la fuite d’un secret", "Une exposition prouvée exige un accès ou une lecture observée, pas seulement un nom ou une alerte", "Un en-tête « Server » vaut toujours un constat critique", "Toute alerte de scanner est déjà un constat validé"], 1, "Un indice aide à orienter l’analyse, mais l’exposition prouvée demande une lecture, une réponse ou une note fiable qui confirme le fait. La réponse tentante est de faire confiance à l’alerte seule, alors qu’un scanner ne remplace pas la validation minimale.", "moyen"),
      questions.multi("Parmi ces actions, lesquelles appartiennent à une remédiation défensive complète après une fuite de secret ? (plusieurs réponses)", ["Faire tourner le secret", "Réduire sa portée", "Nettoyer les copies exposées et les journaux concernés", "Réutiliser le secret pour mieux mesurer l’impact"], [0, 1, 2], "Une correction sérieuse retire l’exposition, fait tourner le secret, limite ses droits et traite les copies encore visibles ainsi que les emplacements de journalisation où la valeur a pu être enregistrée. Réutiliser le secret serait au contraire un abus de la donnée trouvée et sortirait du cadre défensif du parcours.", "difficile"),
      questions.tf("Un réglage « debug=true » peut constituer un problème de configuration même s’il ne contient aucun secret en lui-même.", true, "Vrai : un mode de débogage actif peut révéler des chemins, des erreurs détaillées, des variables ou des comportements trop bavards. Le risque vient alors de l’exposition d’informations ou de surface, même sans valeur secrète en clair dans le réglage lui-même.", "moyen"),
    ],
  },
};

const accountsPrivilegesLesson: NewLesson = {
  key: "pt-comptes-privileges",
  title: "Comptes, privilèges et chemins d’escalade : lire et décrire sans exploiter",
  summary: "Tu apprends à reconnaître des droits trop larges, des comptes de service risqués et des chemins d’escalade plausibles, puis à les corriger sans en faire un tutoriel offensif.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("repérer des privilèges excessifs, lire un inventaire de comptes ou de groupes, décrire un chemin d’escalade plausible, puis proposer une correction sans démonstration offensive."),
    prerequisites("avoir compris le principe du moindre privilège et savoir qu’un pentest défensif documente des chemins plausibles sans chercher à les dérouler jusqu’au bout."),
    scenario("Moussa reçoit pour Baobab Tech un inventaire de groupes privilégiés, de comptes de service et de sorties de lecture comme « sudo -l ». Il doit dire où les droits paraissent trop larges, ce qu’un attaquant pourrait vraisemblablement en tirer, puis comment réduire le risque sans détailler un pas à pas d’élévation."),
    videoSlot("Décrire un chemin d’escalade sans en faire un tutoriel"),
    text("Un compte privilégié n’est pas un problème par nature. Il le devient quand sa portée dépasse le besoin réel, quand son usage n’est pas borné, ou quand il se mélange à des comptes ordinaires. Le principe du moindre privilège sert ici de grille de lecture : quels droits sont nécessaires, pour quel rôle, sur quel périmètre, pour combien de temps ? Un groupe d’administration trop large, un compte de service interactif, une tâche planifiée à droits élevés ou un binaire SUID inattendu dessinent des chemins d’escalade plausibles, même sans démonstration active."),
    schema([
      "Chemin plausible à documenter",
      "",
      "compte ou groupe trop large",
      "-> action possible observée",
      "-> actif touché",
      "-> impact probable",
      "-> correction attendue",
      "",
      "Sans tutoriel offensif",
    ].join("\n")),
    text("Sur Linux, des sorties de lecture comme « sudo -l » ou un inventaire de fichiers SUID aident à voir un risque de délégation excessive. Sur Windows ou Active Directory, on regarde plutôt les groupes privilégiés, les comptes de service à haute valeur, WinRM, certaines GPO ou des partages trop ouverts. Des groupes comme « Enterprise Admins », « Domain Admins », « Administrators » et « Schema Admins » demandent une vigilance particulière dans un inventaire AD. Dans les deux mondes, le même piège revient : confondre « permission élevée » et « constat exploité ». Le bon texte dit ce qui est observé, pourquoi c’est risqué et quelle séparation de rôles corriger."),
    schema([
      "Signaux courants",
      "",
      "service + admin local",
      "NOPASSWD: ALL",
      "groupe privilégié trop large",
      "secret dans script d’admin",
      "partage d’administration trop ouvert",
      "",
      "Lire, qualifier, corriger",
    ].join("\n")),
    text("Un « chemin d’escalade » dans ce cours est une phrase défendable, pas une recette. Par exemple : « le compte de service de sauvegarde est membre d’un groupe d’administration du serveur de fichiers ; cette combinaison dépasse le besoin apparent et augmente le risque d’élévation en cas de compromission du compte ». Cette formulation suffit pour prioriser une correction. Elle n’a pas besoin de détailler les commandes, les abus possibles ni un scénario d’exploitation complet."),
    text("Démonstration guidée : le script local suivant lit un inventaire fictif de comptes et signale quelques motifs défensifs simples. Il ne lance aucune commande système. Il montre seulement comment transformer un export de lecture en alertes de tri « groupe trop large », « service interactif » ou « délégation sudo trop large »."),
    code([
      "# fichier demo-comptes-privileges.cjs",
      "const entries = [",
      "  { account: 'svc-backup', kind: 'service', groups: ['Backup Operators', 'Administrators'], sudo: '' },",
      "  { account: 'awa', kind: 'user', groups: ['support'], sudo: '' },",
      "  { account: 'deploy', kind: 'service', groups: ['web'], sudo: 'NOPASSWD: ALL' },",
      "  { account: 'fatou', kind: 'user', groups: ['Domain Admins'], sudo: '' },",
      "];",
      "const findings = entries.flatMap((entry) => {",
      "  const list = [];",
      "  if (entry.kind === 'service' && entry.groups.includes('Administrators')) list.push('service_admin');",
      "  if (entry.sudo.includes('NOPASSWD: ALL')) list.push('sudo_trop_large');",
      "  if (entry.groups.includes('Domain Admins')) list.push('groupe_tres_sensible');",
      "  return list.map((tag) => ({ account: entry.account, tag }));",
      "});",
      "console.log(JSON.stringify(findings, null, 2));",
      "# exemple de sortie (valeurs fictives)",
      "# [",
      "#   { \"account\": \"svc-backup\", \"tag\": \"service_admin\" },",
      "#   { \"account\": \"deploy\", \"tag\": \"sudo_trop_large\" },",
      "#   { \"account\": \"fatou\", \"tag\": \"groupe_tres_sensible\" }",
      "# ]",
    ].join("\n"), "javascript"),
    text("Le tri seul ne suffit pas : il faut rattacher chaque alerte à un usage réel. Un compte de service dans un groupe d’administration n’est pas une faille « par magie », mais un risque de rupture du moindre privilège. Une ligne « NOPASSWD: ALL » n’est pas à expliquer par une chaîne offensive : elle appelle une revue des commandes nécessaires, une limitation du périmètre et une journalisation claire. De même, l’appartenance à un groupe très sensible n’a de sens qu’avec son rôle et son environnement."),
    example("Exemple corrigé : Koffi lit une sortie « sudo -l » fournie pour un compte de déploiement et voit « NOPASSWD: ALL ». Le constat défendable n’est pas « root compromis », mais « le compte de déploiement dispose d’une délégation sudo sans mot de passe sur l’ensemble des commandes, ce qui dépasse le besoin apparent et augmente fortement le risque d’élévation en cas de compromission ». La correction utile devient alors : réduire les commandes autorisées, isoler le compte et revoir les usages automatiques."),
    mistakes("appeler « escalade » toute permission élevée ; détailler un pas à pas offensif ; oublier de relier le droit observé au rôle réel ; documenter un groupe sensible sans proposer de réduction ou de séparation."),
    safety("dans ce parcours, tu ne cherches pas à exploiter les privilèges observés. Tu travailles sur des inventaires fournis, des journaux ou ton propre laboratoire, et tu t’arrêtes à la description du chemin plausible, de l’impact probable et de la correction attendue."),
    takeaway("le moindre privilège reste la meilleure grille de lecture. Un compte, un groupe ou une délégation deviennent risqués quand leur portée dépasse le besoin réel. Le bon pentest défensif décrit ce chemin, son impact plausible et la correction, sans en faire une recette."),
    practice("Travaille dans « TP 4 : trier le rapport d’un scanner de vulnérabilités » : tu y liras des indices de comptes et de privilèges pour distinguer un vrai risque de délégation excessive d’un simple détail d’inventaire, puis tu termineras par le quiz."),
    reference("msAdBestPractices"),
    reference("msAdPrivilegedGroups"),
    reference("anssiActiveDirectory"),
    reference("sudoWsSudoers"),
  ],
  quiz: {
    title: "Quiz : comptes et privilèges",
    questions: [
      questions.choice("Quel énoncé décrit le mieux un chemin d’escalade dans ce cours ?", ["Une recette complète d’élévation à rejouer", "Une combinaison de droits ou de rôles qui augmente plausiblement l’accès en cas de compromission", "Un mot réservé aux environnements Windows", "Un compte administrateur toujours illégitime"], 1, "Ici, un chemin d’escalade est une description défendable d’un risque de droits excessifs, pas un tutoriel. La réponse tentante est la recette complète, précisément exclue du périmètre pédagogique et éthique du parcours.", "facile"),
      questions.choice("Pourquoi « NOPASSWD: ALL » mérite-t-il une attention particulière dans une sortie « sudo -l » fournie ?", ["Parce qu’il donne au compte une délégation sudo très large sans nouvelle barrière interactive", "Parce qu’il prouve qu’un attaquant a déjà obtenu root", "Parce qu’il désactive toujours la journalisation", "Parce qu’il n’a aucun impact si le compte est technique"], 0, "Une règle « NOPASSWD: ALL » élargit fortement le pouvoir d’un compte et réduit la friction en cas d’abus. La mauvaise réponse la plus tentante est la compromission déjà prouvée, alors qu’on ne documente ici qu’un chemin plausible et un risque clair.", "moyen"),
      questions.multi("Quels éléments peuvent signaler une rupture du moindre privilège ? (plusieurs réponses)", ["Un compte de service membre d’un groupe d’administration", "Une délégation « NOPASSWD: ALL »", "Un groupe très sensible attribué à un compte sans justification claire", "Le simple fait qu’un administrateur existe"], [0, 1, 2], "Les trois premiers éléments élargissent des droits au-delà du besoin apparent ou nécessitent au moins une justification solide. La simple existence d’un administrateur n’est pas une faille en soi : tout dépend du rôle, du périmètre, de la séparation et du contrôle autour de ce compte.", "difficile"),
      questions.tf("Documenter un groupe privilégié sans rappeler l’usage réel du compte et la correction attendue donne un constat incomplet.", true, "Vrai : le nom du groupe seul ne suffit pas. Un constat défendable doit expliquer pourquoi le droit paraît excessif dans ce contexte précis et quelle réduction, séparation ou revue d’usage permettra de corriger le risque sans ambiguïté.", "moyen"),
    ],
  },
};

const controlledExploitationLesson: NewLesson = {
  key: "pt-exploitation-controlee",
  title: "Exploitation contrôlée : principes, limites et plateformes d’entraînement",
  summary: "Tu apprends quand une démonstration d’accès est réellement couverte, pourquoi la preuve minimale prime et où s’entraîner légalement sans confondre labo et production.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("lire des règles d’engagement, distinguer une preuve minimale d’une démonstration excessive, classer des actions selon leur autorisation, puis citer des plateformes d’entraînement légales."),
    prerequisites("connaître le périmètre, les conditions d’arrêt et l’idée centrale du parcours : vérifier et documenter d’abord, ne jamais improviser une chaîne d’attaque."),
    scenario("Koffi tient un journal de mission pour un portail interne autorisé. Une faiblesse semble permettre une démonstration d’accès. Le client a prévu des règles d’engagement strictes, une fenêtre courte et un contact d’urgence. Koffi doit décider s’il faut s’arrêter à une preuve minimale, demander confirmation ou ne rien tenter du tout."),
    videoSlot("Choisir la preuve minimale avant toute démonstration"),
    text("Dans ce parcours, « exploitation contrôlée » ne veut pas dire pousser l’attaque jusqu’au bout. Cela veut dire vérifier, dans un cadre écrit, si une démonstration d’accès minimale est nécessaire et couverte. Si la règle d’engagement ne l’autorise pas, on s’arrête avant. Si elle l’autorise, on choisit l’impact le plus faible, on journalise l’action, on limite la preuve à ce qui démontre le problème et on prévient quand une étape peut toucher la disponibilité ou les données."),
    schema([
      "Question avant toute démonstration",
      "",
      "est-ce explicitement autorisé ?",
      "la preuve minimale suffit-elle ?",
      "l’impact est-il borné ?",
      "le contact prévu est-il informé ?",
      "",
      "Si non : stop ou clarification",
    ].join("\n")),
    text("La preuve minimale garde une place centrale. Si un code « 200 » inattendu ou la lecture d’une ressource convenue suffit à démontrer un accès non prévu, aller plus loin n’apporte souvent rien. C’est la différence entre un pentest responsable et une démonstration spectaculaire. Plus tu avances sans nécessité, plus tu risques de toucher des données réelles, de perturber un service ou de sortir du mandat. Le bon réflexe est donc de préférer la preuve la plus petite qui répond à la question."),
    schema([
      "Où s’entraîner légalement",
      "",
      "PortSwigger Academy",
      "OWASP Juice Shop",
      "DVWA",
      "Metasploitable 3",
      "",
      "Labo oui, production non",
    ].join("\n")),
    text("L’endroit normal pour apprendre la partie la plus intrusive d’un test n’est pas la production d’un client. Ce sont des plateformes d’entraînement conçues pour cela, comme PortSwigger Web Security Academy, que son éditeur présente comme un centre de formation gratuit, ou des laboratoires locaux comme OWASP Juice Shop, DVWA et Metasploitable 3. Rapid7 présente Metasploit Framework comme gratuit et open source, tandis que le dépôt Metasploitable 3 décrit une VM volontairement vulnérable, publiée sous licence de type BSD, destinée à servir de cible de laboratoire. Ces environnements servent à comprendre les mécanismes et les limites, pas à copier un geste sur un tiers. Dans une mission réelle, ce qui compte reste le mandat, le journal et la proportionnalité."),
    text("Démonstration guidée : le script suivant classe des actions fictives selon des règles d’engagement locales. Il aide à décider entre « autorisé », « à confirmer » et « interdit ». Il ne contient aucune commande offensive : seulement de la logique de tri défensive pour apprendre à dire non ou à s’arrêter au bon moment."),
    code([
      "# fichier demo-exploitation-controlee.cjs",
      "const actions = [",
      "  { name: 'lire une ressource temoin convenue', proof: 'minimale', approved: true, sensitive: false },",
      "  { name: 'telecharger un export RH complet', proof: 'excessive', approved: false, sensitive: true },",
      "  { name: 'declencher une charge non prevue', proof: 'offensive', approved: false, sensitive: true },",
      "  { name: 'confirmer un acces avec deux comptes de test', proof: 'minimale', approved: true, sensitive: false },",
      "];",
      "const decide = (item) => {",
      "  if (!item.approved) return 'interdit';",
      "  if (item.sensitive || item.proof === 'excessive') return 'a_confirmer';",
      "  return 'autorise';",
      "};",
      "console.log(JSON.stringify(actions.map((item) => ({ action: item.name, decision: decide(item) })), null, 2));",
      "# exemple de sortie (valeurs fictives)",
      "# [",
      "#   { \"action\": \"lire une ressource temoin convenue\", \"decision\": \"autorise\" },",
      "#   { \"action\": \"telecharger un export RH complet\", \"decision\": \"interdit\" },",
      "#   { \"action\": \"declencher une charge non prevue\", \"decision\": \"interdit\" },",
      "#   { \"action\": \"confirmer un acces avec deux comptes de test\", \"decision\": \"autorise\" }",
      "# ]",
    ].join("\n"), "javascript"),
    text("Le tri rappelle une règle utile : l’autorisation ne supprime pas le besoin de proportion. Une démonstration d’accès peut être couverte, mais rester trop large si elle aspire des données inutiles ou si elle s’écarte de la preuve convenue. À l’inverse, une lecture témoin, un contrôle avec deux comptes de test ou une vérification sur une plateforme d’entraînement légale peuvent suffire à apprendre ou à documenter, sans transformer la mission en terrain d’expérimentation."),
    example("Exemple corrigé : Ama voit qu’une route d’administration répond pour un compte standard dans un environnement autorisé. Le contrat permet une confirmation d’accès minimale, mais interdit toute extraction de données réelles. La bonne action est donc de confirmer le défaut avec une ressource témoin ou une réponse HTTP suffisante, d’écrire ce qui a été observé, puis de s’arrêter. Télécharger l’export complet « pour montrer l’impact » dépasserait la preuve minimale et le mandat."),
    mistakes("croire qu’exploiter plus prouve mieux ; confondre laboratoire d’entraînement et production ; oublier de journaliser une démonstration autorisée ; traiter une autorisation générale comme un chèque en blanc."),
    safety("aucune commande d’exploitation, charge utile, shell ou contournement n’a sa place ici. Tu apprends à décider, cadrer et arrêter. Toute pratique intrusive se fait uniquement sur ton propre laboratoire ou sur une plateforme d’entraînement conçue pour cela."),
    takeaway("l’exploitation contrôlée n’est acceptable que si elle est explicitement couverte, proportionnée et journalisée. La preuve minimale prime. Pour apprendre les gestes plus intrusifs, on s’entraîne sur des plateformes légales, pas sur une production réelle."),
    practice("Travaille dans « TP 6 : relire le journal d’une mission : règles d’engagement, preuves et nettoyage » : tu y jugeras ce qui était autorisé, excessif ou à confirmer dans un journal fourni, puis tu termineras par le quiz."),
    reference("nistGlossaryRoE"),
    reference("nist80115"),
    reference("ncscPentest"),
    reference("portSwiggerAcademy"),
    reference("owaspJuiceShop"),
    reference("dvwaRepo"),
    reference("metasploitable3"),
    reference("metasploitDocs"),
  ],
  quiz: {
    title: "Quiz : exploitation contrôlée",
    questions: [
      questions.choice("Dans ce parcours, qu’est-ce qu’une exploitation contrôlée ?", ["Une démonstration plus spectaculaire que le client ne l’attend", "Une validation d’accès proportionnée, explicitement couverte et limitée à la preuve nécessaire", "Une chaîne d’attaque complète dès qu’une faille apparaît", "Un scan plus rapide pour finir avant les alertes"], 1, "Une exploitation contrôlée reste une démonstration minimale, couverte par les règles d’engagement et bornée par le besoin de preuve. La réponse tentante est la chaîne d’attaque complète, justement contraire à la logique de proportion et d’arrêt défendue dans le cours.", "facile"),
      questions.choice("Pourquoi la preuve minimale garde-t-elle la priorité même quand une démonstration d’accès est autorisée ?", ["Parce qu’elle réduit le risque sur les données, la disponibilité et le dépassement de mandat", "Parce qu’elle remplace toute journalisation", "Parce qu’elle garantit qu’aucune alerte ne sera déclenchée", "Parce qu’elle permet de tester un tiers sans autorisation"], 0, "La preuve minimale protège la cible et le testeur : moins de données touchées, moins d’impact et moins de risque de sortir du mandat. La fausse bonne réponse la plus tentante est l’absence d’alerte, alors que la preuve minimale ne promet pas l’invisibilité, seulement la proportion.", "moyen"),
      questions.multi("Quelles plateformes peuvent être citées honnêtement comme environnements d’entraînement légaux dans cette leçon ? (plusieurs réponses)", ["PortSwigger Web Security Academy", "OWASP Juice Shop", "Metasploitable 3", "Le portail d’un client non prévu au contrat"], [0, 1, 2], "La Web Security Academy, Juice Shop et Metasploitable 3 existent précisément pour l’apprentissage légal et contrôlé. Un portail client hors mandat n’est pas une plateforme d’entraînement : le simple fait qu’il soit accessible ne crée aucune autorisation supplémentaire.", "difficile"),
      questions.tf("Une action explicitement autorisée peut tout de même être excessive si elle va au-delà de la preuve convenue ou touche des données inutiles.", true, "Vrai : l’autorisation doit toujours être lue avec les limites de proportion, d’impact et de preuve minimale. Une mission défensive n’a pas besoin d’une démonstration plus large que le constat qu’elle cherche à prouver.", "moyen"),
    ],
  },
};

const postExploitationLesson: NewLesson = {
  key: "pt-post-exploitation",
  title: "Après l’accès : preuves, impact et arrêt propre",
  summary: "Tu apprends à documenter ce qui suit une confirmation d’accès autorisée, à limiter la preuve, puis à séparer clairement faits observés, impact réel et hypothèses.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("inventorier les artefacts utiles après un accès autorisé, distinguer un fait observé d’une hypothèse, limiter la rétention de preuve, puis décider quand s’arrêter proprement."),
    prerequisites("avoir compris que toute démonstration après accès doit rester couverte par les règles d’engagement et bornée par la preuve minimale."),
    scenario("Fatou relit le journal d’une mission où un accès autorisé a été confirmé. Le client a permis une vérification limitée, mais interdit toute collecte large de données. Fatou doit dire ce qu’il fallait noter, ce qu’il ne fallait pas toucher et où l’équipe aurait dû s’arrêter pour rester propre."),
    videoSlot("Après l’accès : documenter sans fouiller"),
    text("Le moment qui suit une confirmation d’accès est souvent celui où la discipline compte le plus. Le risque n’est plus seulement de rater une faille, mais d’en faire trop. Lire un répertoire entier, télécharger des archives ou explorer des comptes non prévus peut vite transformer une preuve minimale en collecte excessive. La bonne posture consiste à noter l’artefact utile, à consigner l’heure, le compte, le contexte et la raison de l’arrêt, puis à séparer soigneusement le fait observé de tout effet supposé mais non vérifié."),
    schema([
      "Ce qu on peut documenter",
      "",
      "compte utilisé",
      "heure et actif touchés",
      "ressource témoin lue",
      "privilège observé",
      "artefact créé ou modifié",
      "",
      "Sans fouille extensive",
    ].join("\n")),
    text("Le mot important ici est traçabilité. Un fait observé peut être : « le compte de test standard a obtenu un code 200 sur une ressource d’administration », ou « un répertoire témoin convenu était lisible ». Une hypothèse serait : « ce défaut pourrait permettre un mouvement latéral ». L’hypothèse peut être utile dans la recommandation, mais elle ne doit jamais être présentée comme un effet constaté si tu ne l’as pas réellement observé dans le cadre autorisé."),
    schema([
      "Fait, impact, hypothèse",
      "",
      "fait      -> ce qui a été vu",
      "impact    -> ce que cela expose déjà",
      "hypothèse -> ce qui serait possible ensuite",
      "",
      "Ne pas les mélanger",
    ].join("\n")),
    text("La preuve minimale vaut aussi pour la rétention. Tu n’as pas besoin de copier un dossier entier pour prouver qu’un accès était excessif. Un nom de ressource, un extrait témoin convenu, un horodatage et un contexte suffisent souvent. C’est particulièrement important si des données personnelles ou métier sensibles sont en jeu. Plus tu conserves de copies, plus tu élargis le risque juridique et opérationnel de la mission."),
    text("Démonstration guidée : le script suivant lit un journal fictif et extrait les artefacts qu’une équipe doit suivre après une confirmation d’accès : compte temporaire et règle modifiée. Le but n’est pas de montrer comment créer ces artefacts, mais de savoir les documenter et de vérifier qu’ils seront retirés ensuite."),
    code([
      "# fichier demo-post-exploitation.cjs",
      "const journal = [",
      "  { time: '09:10', action: 'login-ok', detail: 'compte_test_standard' },",
      "  { time: '09:12', action: 'read-marker', detail: '/srv/demo/proof.txt' },",
      "  { time: '09:14', action: 'temp-account', detail: 'audit-temp' },",
      "  { time: '09:16', action: 'firewall-rule', detail: 'allow 10.20.5.7 -> 443' },",
      "  { time: '09:18', action: 'stop', detail: 'preuve suffisante' },",
      "];",
      "const tracked = journal.filter((entry) => ['temp-account', 'firewall-rule'].includes(entry.action));",
      "console.log(JSON.stringify(tracked, null, 2));",
      "# exemple de sortie (valeurs fictives)",
      "# [",
      "#   { \"time\": \"09:14\", \"action\": \"temp-account\", \"detail\": \"audit-temp\" },",
      "#   { \"time\": \"09:16\", \"action\": \"firewall-rule\", \"detail\": \"allow 10.20.5.7 -> 443\" }",
      "# ]",
    ].join("\n"), "javascript"),
    text("Ce petit extrait suffit à illustrer l’essentiel : après l’accès, tout ce qui est créé ou modifié doit être suivi. Même si l’accès lui-même a été autorisé, un compte temporaire ou une règle réseau ne doivent pas disparaître du récit. Ils servent à la clôture, au nettoyage et au re-test. À l’inverse, le simple fait d’avoir pu lire « /srv/demo/proof.txt » n’autorise pas à parcourir tout « /srv/demo » si la preuve convenue est déjà atteinte."),
    example("Exemple corrigé : Moussa confirme un défaut d’autorisation sur une ressource témoin prévue avec le client. Il note l’heure, le compte, la ressource lue et le code de réponse, puis arrête là. Dans son rapport, il écrit que l’accès non prévu a été démontré sur une ressource témoin et que l’impact observé est une lecture non autorisée. Il peut ajouter qu’une exposition plus large est plausible, mais il la présente comme une hypothèse à traiter, pas comme un fait établi."),
    mistakes("présenter une hypothèse comme un fait ; conserver trop de copies « au cas où » ; oublier les artefacts créés pendant la démonstration ; croire qu’un accès obtenu autorise une exploration libre."),
    safety("après l’accès, tu ne fouilles pas. Tu limites la preuve, tu notes ce qui a été créé ou modifié, tu protèges les données sensibles et tu t’arrêtes dès que le constat est suffisamment démontré dans le cadre autorisé."),
    takeaway("la phase après accès doit rester sobre, traçable et courte. Un bon journal sépare le fait observé, l’impact déjà démontré et l’hypothèse éventuelle, tout en préparant le nettoyage de ce qui a été créé."),
    practice("Travaille dans « TP 6 : relire le journal d’une mission : règles d’engagement, preuves et nettoyage » : tu y vérifieras la qualité des preuves, les arrêts au bon moment et la trace des artefacts à retirer, puis tu termineras par le quiz."),
    reference("eurLexRgpd"),
    reference("nist80115"),
    reference("ncscPentest"),
  ],
  quiz: {
    title: "Quiz : après l’accès",
    questions: [
      questions.choice("Quelle formulation reste la plus juste après une confirmation d’accès autorisée ?", ["« L’accès obtenu autorise maintenant une exploration complète »", "« On documente la preuve minimale, les artefacts créés et on s’arrête dès que le constat est démontré »", "« On télécharge tout pour mesurer l’impact réel »", "« Le journal n’est plus utile une fois l’accès confirmé »"], 1, "Après l’accès, la discipline consiste à limiter la preuve, à suivre les artefacts créés et à arrêter l’action dès que le constat est défendable. La fausse bonne réponse la plus tentante est l’exploration complète, qui dépasse justement la proportion défendue dans ce parcours.", "facile"),
      questions.choice("Pourquoi faut-il distinguer « fait observé » et « hypothèse » dans un rapport ?", ["Parce qu’une hypothèse vaut automatiquement preuve si elle paraît logique", "Parce qu’un fait observé est démontré alors qu’une hypothèse décrit seulement un impact plausible ou une suite possible", "Parce qu’un rapport ne doit jamais parler d’impact", "Parce qu’une hypothèse interdit toute recommandation"], 1, "Un fait observé repose sur une preuve réellement vue dans le cadre autorisé. Une hypothèse sert à orienter la remédiation ou la prudence, mais elle ne doit pas être présentée comme si elle avait été démontrée. C’est la base d’un rapport honnête et utile.", "moyen"),
      questions.multi("Que faut-il suivre particulièrement dans un journal après un accès autorisé ? (plusieurs réponses)", ["Les comptes temporaires créés", "Les règles ou paramètres modifiés", "Les fichiers ou artefacts déposés", "Chaque dossier du serveur, même hors preuve convenue"], [0, 1, 2], "Comptes temporaires, règles modifiées et artefacts déposés doivent être suivis pour le nettoyage et la clôture. Explorer chaque dossier hors preuve convenue serait au contraire une dérive : tu augmentes la collecte et le risque sans nécessité pédagogique ou contractuelle.", "difficile"),
      questions.tf("Une copie complète de données métier n’est pas nécessaire quand une ressource témoin, un horodatage et un contexte suffisent déjà à prouver le constat.", true, "Vrai : la minimisation s’applique aussi aux preuves. Garder seulement ce qui est utile au constat réduit le risque pour le client, la charge de protection du prestataire et les ambiguïtés au moment de la clôture ou du re-test.", "moyen"),
    ],
  },
};

const cleanupHandoverLesson: NewLesson = {
  key: "pt-nettoyage-remise",
  title: "Nettoyer, restituer les accès et clôturer la mission",
  summary: "Tu apprends à retirer ce que l’équipe a créé, à révoquer les accès temporaires et à clôturer une mission sans confondre nettoyage légitime et effacement de traces.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("inventorier les artefacts de mission, vérifier ce qui reste à supprimer, distinguer nettoyage et effacement de traces, puis préparer une clôture et un re-test propres."),
    prerequisites("avoir compris la logique de preuve minimale, de journal horodaté et de suivi des artefacts créés pendant une démonstration autorisée."),
    scenario("Awa clôture une mission courte pour la boutique Soleil. Le journal mentionne un compte temporaire, une règle de pare-feu, un fichier témoin et un accès API de démonstration. Elle doit s’assurer que tout ce qui a été créé est retiré ou restitué, que les preuves utiles restent protégées, puis préparer un point de re-test."),
    videoSlot("Clore une mission sans laisser de dette technique"),
    text("La fin d’un pentest défensif n’est pas un détail administratif. C’est une phase de sécurité à part entière. Tout ce que l’équipe a créé ou modifié doit être retiré, révoqué ou rendu inutile, puis tracé dans une note de clôture. Cela inclut les comptes temporaires, règles réseau, jetons de démonstration, fichiers déposés, scripts copiés, tâches planifiées et paramètres changés. Le nettoyage protège autant le client que le prestataire : ce qui reste par oubli peut devenir un risque réel après la mission."),
    schema([
      "Reste à vérifier avant clôture",
      "",
      "comptes temporaires",
      "secrets ou jetons de démo",
      "fichiers témoins déposés",
      "règles réseau temporaires",
      "tâches et services ajoutés",
      "",
      "Retirer, tracer, valider",
    ].join("\n")),
    text("Il faut aussi distinguer clairement nettoyage et effacement de traces. Le nettoyage légitime retire les artefacts créés par l’équipe et le documente. L’effacement de traces, lui, chercherait à faire disparaître les journaux du client ou à masquer ce qui s’est passé. Cette seconde idée n’a pas sa place dans le parcours. Une mission défensive laisse une traçabilité suffisante, précisément pour permettre la relecture, la clôture et le re-test."),
    schema([
      "Preuves à garder / copies à détruire",
      "",
      "garder : extrait minimal, horodatage, contexte",
      "détruire : copie excessive, secret complet, dump inutile",
      "",
      "Conserver seulement le nécessaire",
    ].join("\n")),
    text("La clôture ne consiste pas seulement à supprimer. Elle consiste aussi à restituer : désactiver un compte de test, faire tourner un jeton provisoire, fermer un accès API temporaire, ou confirmer qu’une règle de pare-feu d’exception a bien disparu. Le rapport final ou l’annexe de clôture doit indiquer ce qui a été retiré, ce qui reste volontairement en place pour un re-test, qui l’a validé et sur quelle période les preuves seront conservées."),
    text("Démonstration guidée : le script ci-dessous relit un journal fictif d’actions créées et supprimées. Il signale ce qui reste encore ouvert à la fin de la mission. C’est un exercice de relecture défensive, pas une procédure système. Il aide à bâtir une note « reste à nettoyer » claire et courte."),
    code([
      "# fichier demo-nettoyage-remise.cjs",
      "const journal = [",
      "  { item: 'audit-temp', event: 'created' },",
      "  { item: 'proof.txt', event: 'created' },",
      "  { item: 'fw-rule-443', event: 'created' },",
      "  { item: 'audit-temp', event: 'removed' },",
      "  { item: 'proof.txt', event: 'removed' },",
      "];",
      "const state = new Map();",
      "for (const entry of journal) state.set(entry.item, entry.event);",
      "const remaining = [...state.entries()].filter(([, event]) => event !== 'removed').map(([item]) => item);",
      "console.log(JSON.stringify({ remaining }, null, 2));",
      "# exemple de sortie (valeurs fictives)",
      "# {",
      "#   \"remaining\": [\"fw-rule-443\"]",
      "# }",
    ].join("\n"), "javascript"),
    text("Le résultat illustre une situation classique : presque tout a été retiré, mais une règle temporaire subsiste. C’est exactement le type d’oubli qu’une bonne clôture doit empêcher. La note associée peut rester simple : « la règle temporaire fw-rule-443 restait active en fin de mission ; sa suppression a été demandée avant remise finale ». Cette phrase vaut mieux qu’une clôture optimiste qui suppose que tout est propre sans le vérifier."),
    example("Exemple corrigé : Koffi constate qu’un compte de test a bien été supprimé et que le fichier témoin a disparu, mais qu’un jeton d’API de démonstration et une règle réseau temporaire restent valides. La bonne clôture sépare alors trois colonnes : retiré, reste à révoquer, conservé pour re-test avec accord explicite. Elle ne supprime pas le journal du client et ne détruit pas des preuves utiles avant validation de la remise."),
    mistakes("confondre nettoyage et effacement de traces ; oublier un secret ou un jeton temporaire ; détruire trop tôt des preuves encore nécessaires ; clôturer sans vérifier ce qui reste pour le re-test."),
    safety("tu ne supprimes que ce que l’équipe a créé ou ce que le client t’a explicitement demandé de retirer. Tu ne touches pas aux journaux du client, tu documentes les exceptions de re-test et tu gardes seulement la preuve minimale nécessaire."),
    takeaway("une mission propre se termine par un inventaire, une révocation et une validation. Nettoyer, ce n’est pas cacher : c’est retirer ses propres artefacts, protéger les preuves utiles et préparer un re-test sans laisser de dette technique."),
    practice("Travaille dans « TP 6 : relire le journal d’une mission : règles d’engagement, preuves et nettoyage » : tu y repéreras les artefacts oubliés, les écarts de clôture et les éléments à conserver ou révoquer avant le re-test, puis tu termineras par le quiz."),
    reference("nist80115"),
    reference("eurLexRgpd"),
    reference("ncscPentest"),
  ],
  quiz: {
    title: "Quiz : nettoyage et clôture",
    questions: [
      questions.choice("Quelle définition correspond le mieux au nettoyage légitime de fin de mission ?", ["Effacer les journaux du client pour faire disparaître le bruit du test", "Retirer les artefacts créés par l’équipe et documenter ce retrait", "Supprimer toutes les preuves pour éviter tout risque", "Laisser les accès temporaires actifs jusqu’au prochain audit"], 1, "Le nettoyage légitime consiste à retirer ce que l’équipe a créé ou modifié pour la mission, puis à le tracer clairement. La réponse tentante est l’effacement des journaux, justement exclu : ce serait masquer la trace au lieu de clôturer proprement.", "facile"),
      questions.choice("Pourquoi faut-il distinguer « retiré », « reste à révoquer » et « conservé pour re-test » ?", ["Parce qu’une clôture honnête décrit des statuts différents et évite les faux « tout est propre »", "Parce qu’un re-test interdit tout retrait", "Parce qu’un artefact temporaire n’a jamais d’importance", "Parce qu’un compte de test n’est jamais un accès réel"], 0, "Ces trois statuts structurent la clôture : ce qui est retiré, ce qui doit encore l’être, et ce qui reste volontairement sous accord pour un re-test. La mauvaise réponse la plus tentante est de tout ranger sous « propre », au risque de masquer un oubli ou une exception non documentée.", "moyen"),
      questions.multi("Quels éléments méritent une vérification explicite avant la remise finale ? (plusieurs réponses)", ["Comptes temporaires", "Jetons ou secrets de démonstration", "Règles réseau temporaires", "Toute trace de journalisation du client"], [0, 1, 2], "Comptes, jetons et règles temporaires sont typiquement créés ou activés pour la mission et doivent être retirés ou revalidés. Les journaux du client, eux, ne sont pas des artefacts à effacer : ils font partie de la traçabilité normale et peuvent même aider à la clôture et au re-test.", "difficile"),
      questions.tf("Conserver un extrait minimal de preuve et détruire une copie excessive de données sensibles peuvent faire partie de la même clôture propre.", true, "Vrai : la bonne clôture garde ce qui est nécessaire pour défendre le constat et préparer le re-test, tout en supprimant les copies superflues qui élargiraient le risque pour le client ou le prestataire. La minimisation continue donc jusqu’à la remise finale.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c5:8",
    position: 7,
    title: "Comptes, mots de passe et secrets",
    description: "Ce module t’apprend à relire une politique de mots de passe, à reconnaître des empreintes et à décrire des risques de comptes ou de secrets sans jamais basculer vers le cassage ou l’abus. Critères de réussite : distinguer politique, stockage et risque ; reconnaître des formats d’empreintes et des expositions de secrets ; formuler un constat et une correction défensifs sans tutoriel offensif.",
    lessons: [passwordAuditLesson, secretsConfigurationLesson, accountsPrivilegesLesson],
  },
  {
    key: "c5:9",
    position: 8,
    title: "Exploitation contrôlée et fin de mission",
    description: "Ce module t’apprend à raisonner sur les limites d’une démonstration autorisée, à réduire l’impact et à clôturer proprement une mission défensive. Critères de réussite : décider quand une preuve minimale suffit ; séparer faits observés, impacts et hypothèses ; inventorier, retirer et documenter les artefacts de mission avant le re-test.",
    lessons: [controlledExploitationLesson, postExploitationLesson, cleanupHandoverLesson],
  },
];
