import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const scannersVulnsLesson: NewLesson = {
  key: "pt-scanners-vulns",
  title: "Scanners de vulnérabilités : ce qu’ils voient et ce qu’ils ne voient pas",
  summary: "Tu apprends à lire un export de scanner sans le confondre avec un pentest, puis à distinguer version, configuration, preuve faible et constat déjà défendable.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer scanner et pentest, expliquer ce qu’un scan authentifié voit de plus, relier une alerte à CVE, CWE et NVD, puis classer un export en éléments à confirmer."),
    prerequisites("connaître le cadre autorisé d’un test d’intrusion et savoir lire une version logicielle, un service exposé et une preuve technique simple."),
    scenario("Ama relit un export reçu par la boutique Soleil après une évaluation de vulnérabilités autorisée. Le fichier contient des lignes sévères, des références CVE, un cookie sans attribut de sécurité et des alertes peu convaincantes sur un hôte de démonstration. Son travail n’est pas de recopier la sévérité de l’outil, mais de dire ce qui ressemble à un vrai constat, à une piste ou à un faux positif."),
    videoSlot("Lire un export de scanner avec un regard de pentest"),
    text("Un scanner de vulnérabilités et un pentest ne répondent pas à la même question. Le scanner cherche surtout des signatures connues : une version observée, un en-tête, un service, un paquet installé, une mauvaise configuration visible, parfois une preuve faible tirée d’une réponse HTTP ou d’un certificat. Le pentest, lui, remet ces signaux dans un contexte de mission, de preuves minimales et d’impact métier. Une alerte n’est donc ni une vérité absolue, ni une preuve d’exploitabilité."),
    schema([
      "Scanner vs pentest",
      "",
      "scanner -> versions, signatures, configs visibles",
      "pentest -> preuves minimales, contexte, priorités",
      "",
      "Le scanner accélère le tri",
      "Le pentest tranche ce qui compte vraiment",
    ].join("\n")),
    text("Le scan non authentifié voit surtout la surface exposée depuis le réseau ou l’application : bannières, réponses HTTP, certificats, ports et configurations visibles. Le scan authentifié voit souvent davantage : versions réellement installées, paquets manquants, droits trop larges, options de configuration internes. Dans les deux cas, tu dois relire les limites de l’outil : produit testé, date, profondeur, plug-ins activés, mode authentifié ou non. Sinon, tu risques de comparer des constats qui n’ont pas été observés avec le même niveau de preuve."),
    schema([
      "Repères utiles dans une alerte",
      "",
      "CVE : identifiant d’une vulnérabilité précise",
      "CWE : famille de faiblesse",
      "NVD : enrichissement, score, produits touchés",
      "",
      "Un identifiant aide à lire",
      "Il ne remplace pas la validation locale",
    ].join("\n")),
    text("CVE, CWE et NVD t’aident à parler le même langage. Une CVE nomme un problème précis. Une CWE décrit une faiblesse plus générale, par exemple une mauvaise validation d’entrée. La NVD enrichit souvent la CVE avec des produits touchés et un score. Mais même quand une référence existe, il faut encore vérifier la version réellement observée, la configuration locale, la présence d’un contrôle compensatoire et la qualité de la preuve fournie par le scanner."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script local ci-dessous classe un petit export fictif en quatre catégories : « version », « configuration », « preuve faible » et « à vérifier ». L’idée n’est pas d’attaquer quoi que ce soit, mais de transformer un fichier brut en file d’attente de relecture défensive."),
    code([
      "# fichier demo-scanners-vulns.cjs",
      "const alerts = [",
      "  { id: 'V14', host: '192.0.2.14', title: 'OpenSSH version 8.x detectee', evidence: 'banner: OpenSSH 8.4', kind: 'version' },",
      "  { id: 'V21', host: '192.0.2.14', title: 'Cookie de session sans HttpOnly', evidence: 'Set-Cookie: sid=abc123; Secure', kind: 'configuration' },",
      "  { id: 'V32', host: '192.0.2.14', title: 'Injection SQL presumee', evidence: 'reponse 500 sans detail', kind: 'preuve faible' },",
      "  { id: 'V40', host: '192.0.2.14', title: 'Version nginx possiblement obsolete', evidence: 'Server: nginx', kind: 'a verifier' },",
      "];",
      "const summary = alerts.reduce((acc, alert) => {",
      "  acc[alert.kind] = (acc[alert.kind] || 0) + 1;",
      "  return acc;",
      "}, {});",
      "const ready = alerts.filter((alert) => alert.kind === 'configuration').map((alert) => alert.id);",
      "console.log(JSON.stringify({ summary, ready }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"summary\": {",
      "//     \"version\": 1,",
      "//     \"configuration\": 1,",
      "//     \"preuve faible\": 1,",
      "//     \"a verifier\": 1",
      "//   },",
      "//   \"ready\": [",
      "//     \"V21\"",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : sur « 192.0.2.14 », seule l’alerte « cookie de session sans HttpOnly » est déjà proche d’un constat, car la preuve montre un en-tête observé et une propriété attendue absente. « OpenSSH version 8.x détectée » reste un indice à relier au bon produit et à la bonne version. « Injection SQL présumée » n’est qu’une hypothèse si tout repose sur un simple code 500. « Server: nginx » dit encore moins : un frontal ou un proxy peut parler ainsi sans prouver la version locale ni une faille."),
    mistakes("recopier la gravité affichée par l’outil sans relire la preuve ; croire qu’absence d’alerte signifie absence de risque ; oublier de distinguer scan authentifié et non authentifié ; appeler « vulnérabilité confirmée » une simple bannière ou un code de retour."),
    safety("un export de scanner doit venir de ton laboratoire, d’une plateforme d’entraînement légale ou d’un périmètre couvert par une autorisation écrite. Tu ne lances pas de scan offensif sur un tiers pour « vérifier » une ligne du rapport. Tu relis, tu classes, puis tu demandes une validation minimale dans le cadre convenu."),
    takeaway("un scanner accélère la découverte, mais il ne remplace ni la méthode ni le jugement. Ce qu’il voit bien relève des versions et configurations visibles. Ce qu’il voit mal relève souvent de la logique métier, du contexte et des preuves fines."),
    practice("Travaille dans « TP 4 : trier le rapport d’un scanner de vulnérabilités » : tu y qualifieras un export fourni, avec des faux positifs et des preuves faibles, sans lancer le moindre scan. Termine ensuite par le quiz."),
    reference("greenboneDocs"),
    reference("nucleiDocs"),
    reference("trivyDocs"),
    reference("nvdCveProcess"),
  ],
  quiz: {
    title: "Quiz : lire un scanner de vulnérabilités",
    questions: [
      questions.choice("Que montre le mieux un scanner de vulnérabilités ?", ["Des signatures, versions et configurations visibles à relire ensuite", "La preuve qu’un attaquant a déjà tout compromis", "L’impact métier complet sans contexte", "Une autorisation implicite d’aller exploiter"], 0, "Un scanner repère surtout des indices techniques : versions, signatures, services, en-têtes, configurations visibles. La mauvaise réponse la plus tentante est l’impact métier complet, alors que cet impact dépend encore du périmètre, des actifs et de la qualité de la preuve.", "facile"),
      questions.choice("Pourquoi une alerte fondée sur « Server: nginx » doit-elle être relue avec prudence ?", ["Parce qu’un en-tête suffit toujours à prouver une CVE", "Parce qu’un frontal ou une bannière générique peut masquer la version ou même le logiciel réel", "Parce qu’un serveur HTTP ne peut jamais envoyer cet en-tête", "Parce qu’un en-tête HTTP remplace une validation locale"], 1, "Une bannière ou un en-tête apporte un indice utile, mais il peut être partiel, générique ou fourni par un intermédiaire. L’erreur tentante est de transformer cet indice en faille confirmée, ce que la preuve disponible ne permet pas encore.", "moyen"),
      questions.multi("Quelles informations aident vraiment à relire une alerte de scanner ? (plusieurs réponses)", ["Le mode authentifié ou non authentifié", "La preuve technique affichée", "Le produit ou service visé", "Le seul mot « critique » sans détail"], [0, 1, 2], "Le mode d’observation, la preuve brute et le produit réellement visé permettent de juger la qualité d’une alerte. Le mot « critique » seul ne suffit pas : il décrit l’opinion de l’outil, pas encore un constat défendable dans ton contexte.", "difficile"),
      questions.tf("Une absence d’alerte dans un export suffit à prouver l’absence de faiblesse sur l’actif étudié.", false, "Faux : un export dépend du moment, des signatures, du mode de scan et de ce que l’outil sait observer. L’absence d’alerte peut être rassurante sur un point précis, mais elle ne vaut jamais preuve générale d’absence de risque ou de défaut métier.", "moyen"),
    ],
  },
};

const verifierSansExploiterLesson: NewLesson = {
  key: "pt-verifier-sans-exploiter",
  title: "Vérifier une vulnérabilité sans l’exploiter : les preuves minimales",
  summary: "Tu apprends à choisir la preuve la moins intrusive qui démontre un problème, puis à distinguer constat confirmé, preuve insuffisante et observation hors cadre.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("définir une preuve minimale, relire une observation avec ses préconditions, séparer fait et hypothèse, puis classer une note en preuve suffisante, insuffisante ou hors cadre."),
    prerequisites("savoir qu’une alerte d’outil ne vaut pas preuve et connaître le rôle des règles d’engagement, des comptes de test et des conditions d’arrêt."),
    scenario("Fatou dispose de deux comptes de test fournis pour l’association Teranga. Elle voit un identifiant manipulé dans une URL, une réponse inhabituelle sur une route d’export et un formulaire qui reflète une valeur bénigne. Elle doit décider ce qui suffit déjà à démontrer un problème et ce qui demanderait une action trop intrusive ou interdite."),
    videoSlot("Choisir une preuve minimale qui reste défendable"),
    text("La preuve minimale est la plus petite observation qui démontre le problème sans dégrader inutilement le système ni sortir du cadre convenu. En pentest défensif, ce principe protège la disponibilité, limite la collecte de données et améliore la qualité du rapport. Tu ne cherches pas la démonstration la plus impressionnante. Tu cherches celle qui est suffisamment claire, reproductible et acceptable au regard des règles d’engagement."),
    schema([
      "Trois statuts utiles",
      "",
      "preuve suffisante   -> le fait est démontré",
      "preuve insuffisante -> piste plausible, pas encore démontrée",
      "hors cadre          -> action interdite ou non autorisée",
      "",
      "Toujours noter rôle, date, requête, réponse",
    ].join("\n")),
    text("Une preuve minimale peut prendre plusieurs formes. Un utilisateur standard qui reçoit un « 200 » sur une ressource réservée à l’administration constitue déjà une démonstration de contrôle d’accès défaillant. Une valeur inoffensive reflétée telle quelle à un endroit dangereux peut suffire à documenter un manque de validation ou une surface XSS à confirmer. Un fichier de test bénin accepté malgré une politique supposée restrictive peut aussi devenir un constat. À l’inverse, un simple code 500 ou une intuition non corroborée reste une preuve insuffisante."),
    schema([
      "Exemples de preuves minimales approuvées",
      "",
      "200 sur une ressource d’un autre compte",
      "Set-Cookie sans attribut attendu",
      "valeur bénigne reflétée comme entrée non neutralisée",
      "fichier de test accepté alors qu’il devrait être refusé",
      "",
      "Inutile : extraire toute une base ou un CSV RH",
    ].join("\n")),
    text("La méthode compte autant que le résultat. Chaque note doit préciser le compte utilisé, la date, la requête ou l’action effectuée, la réponse observée et la conclusion. Tu sépares ce qui est vu de ce qui est supposé. Si une action supplémentaire devient nécessaire, tu vérifies d’abord qu’elle reste autorisée. Sans cet effort de traçabilité, tu risques de transformer une bonne intuition en constat fragile."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script local ci-dessous classe des observations fictives en « preuve suffisante », « preuve insuffisante » ou « hors cadre ». Il ne lance rien contre une cible. Il t’aide seulement à formaliser le bon réflexe avant d’écrire une note de mission."),
    code([
      "# fichier demo-preuves-minimales.cjs",
      "const observations = [",
      "  { id: 'N07', kind: 'access', detail: '200 sur /admin/export avec compte standard', authorized: true, proven: true },",
      "  { id: 'N11', kind: 'input', detail: 'code 500 apres une saisie atypique', authorized: true, proven: false },",
      "  { id: 'N18', kind: 'download', detail: 'telecharger tout le dossier RH pour prouver l acces', authorized: false, proven: false },",
      "  { id: 'N22', kind: 'session', detail: 'cookie de session sans HttpOnly', authorized: true, proven: true },",
      "];",
      "const classify = (item) => {",
      "  if (!item.authorized) return 'hors cadre';",
      "  return item.proven ? 'preuve suffisante' : 'preuve insuffisante';",
      "};",
      "const result = observations.map((item) => ({ id: item.id, status: classify(item) }));",
      "console.log(JSON.stringify(result, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// [",
      "//   { \"id\": \"N07\", \"status\": \"preuve suffisante\" },",
      "//   { \"id\": \"N11\", \"status\": \"preuve insuffisante\" },",
      "//   { \"id\": \"N18\", \"status\": \"hors cadre\" },",
      "//   { \"id\": \"N22\", \"status\": \"preuve suffisante\" }",
      "// ]",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si un compte standard obtient « 200 » sur « /admin/export », la preuve minimale est déjà là. Tu peux documenter le défaut sans télécharger tout le CSV du personnel. À l’inverse, un simple « 500 » après une saisie atypique ne prouve ni une injection ni un impact. Tu décris alors une piste à confirmer, pas une faille démontrée. Cette différence protège autant la cible que ta crédibilité."),
    mistakes("chercher la charge la plus spectaculaire au lieu de la preuve la plus sobre ; oublier de noter le rôle ou le compte utilisé ; mélanger fait observé et hypothèse ; franchir une étape interdite « pour être sûr » sans revalider le cadre."),
    safety("tu travailles seulement sur ton laboratoire, une plateforme d’entraînement légale ou un périmètre couvert par une autorisation écrite. Si une action risque la stabilité, expose des données réelles ou dépasse les règles d’engagement, tu t’arrêtes et tu remontes la question au contact prévu."),
    takeaway("une bonne preuve minimale démontre le problème avec le moins d’impact possible. Un constat solide dit qui a fait quoi, quand, avec quel résultat. Ce qui n’est pas démontré reste une hypothèse, et ce qui n’est pas autorisé reste hors cadre."),
    practice("Travaille dans « TP 4 : trier le rapport d’un scanner de vulnérabilités » : le laboratoire t’entraîne à juger quelles notes prouvent réellement un problème, lesquelles restent insuffisantes et lesquelles demanderaient une action non justifiée. Termine ensuite par le quiz."),
    reference("nist80115"),
    reference("ncscPentest"),
    reference("owaspWstg"),
    reference("owaspTop10A01"),
    reference("owaspTop10A05"),
  ],
  quiz: {
    title: "Quiz : preuves minimales",
    questions: [
      questions.choice("Quelle preuve est préférable dans un pentest défensif ?", ["La plus intrusive possible pour impressionner le client", "La moins intrusive qui démontre clairement le problème", "Une intuition technique sans trace", "Une extraction complète de données réelles"], 1, "La meilleure preuve est celle qui établit le constat sans causer plus d’impact que nécessaire. La mauvaise réponse la plus tentante est l’extraction complète : elle semble convaincre davantage, alors qu’elle augmente inutilement le risque et sort souvent du besoin réel.", "facile"),
      questions.choice("Pourquoi un simple code HTTP 500 reste-t-il souvent insuffisant pour conclure à une injection ?", ["Parce qu’un code 500 prouve toujours un XSS, jamais une injection", "Parce qu’une erreur serveur peut avoir plusieurs causes et ne démontre pas à elle seule la faiblesse soupçonnée", "Parce que les applications modernes n’utilisent plus le code 500", "Parce qu’un 500 annule automatiquement le périmètre contractuel"], 1, "Une erreur 500 peut venir d’un bug, d’un format inattendu ou d’un contrôle applicatif sans rapport direct avec une injection exploitable. La tentation est de traiter tout signal fort comme une faille confirmée, alors qu’il manque encore une preuve défendable.", "moyen"),
      questions.multi("Parmi ces éléments, lesquels appartiennent à une bonne fiche de preuve minimale ? (plusieurs réponses)", ["Le compte ou rôle utilisé", "La requête ou l’action observée", "La réponse ou le résultat obtenu", "Une conclusion sensationnaliste sans détail"], [0, 1, 2], "Une preuve lisible doit permettre de comprendre le contexte, l’action et le résultat. Une formule sensationnaliste sans détail ne démontre rien et empêche un tiers de vérifier si le constat est réel, proportionné et reproductible.", "difficile"),
      questions.tf("Si une action utile devient non autorisée par les règles d’engagement, elle doit être classée hors cadre même si elle pourrait confirmer l’hypothèse.", true, "Vrai : le cadre contractuel et la protection de la cible passent avant la curiosité technique. Une confirmation obtenue en dépassant les règles d’engagement fragilise le test, l’éthique de la mission et souvent la valeur du rapport final.", "moyen"),
    ],
  },
};

const priorisationRisqueLesson: NewLesson = {
  key: "pt-priorisation-risque",
  title: "Prioriser : CVSS, EPSS, KEV et contexte de l’organisation",
  summary: "Tu apprends à séparer gravité et priorité, à relire un vecteur CVSS 3.1, puis à croiser EPSS, KEV et contexte métier pour décider quoi corriger d’abord.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("lire un vecteur CVSS 3.1, distinguer CVSS 3.1 et 4.0, expliquer EPSS et KEV, puis classer plusieurs constats selon leur priorité métier."),
    prerequisites("savoir lire une alerte de vulnérabilité, comprendre ce qu’est une preuve minimale et connaître la différence entre un constat confirmé et une hypothèse."),
    scenario("Moussa prépare un comité de remédiation pour Baobab Tech. Cinq constats confirmés arrivent sur la table : un portail public modérément noté, un service interne très bien segmenté, une vulnérabilité déjà vue dans le catalogue KEV et deux tickets moins urgents mais faciles à corriger. Il doit expliquer pourquoi une note technique élevée ne suffit pas toujours à décider l’ordre de correction."),
    videoSlot("Passer d’une note technique à une vraie priorité"),
    text("La gravité et la priorité ne sont pas la même chose. La gravité décrit surtout la sévérité technique du problème, par exemple avec un score CVSS. La priorité ajoute le contexte : exposition publique ou non, criticité de l’actif, rôle nécessaire, contrôles compensatoires, facilité de correction, existence d’un exploit observé dans la nature. Un bon pentest ne remet donc pas au client une simple liste triée par score. Il explique pourquoi on corrige d’abord tel constat, dans telle fenêtre, sur tel actif."),
    schema([
      "Gravité != priorité",
      "",
      "CVSS  -> sévérité technique",
      "EPSS  -> probabilité d’exploitation à 30 jours",
      "KEV   -> exploitation observée dans la nature",
      "contexte -> actif, exposition, contrôles, urgence",
      "",
      "Priorité = synthèse, pas un seul nombre",
    ].join("\n")),
    text("CVSS 3.1 te donne un vecteur comme « AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H » pour décrire l’accès, la complexité, les privilèges requis, l’interaction utilisateur, la portée et les impacts sur confidentialité, intégrité et disponibilité. CVSS 4.0 existe aussi, avec des groupes Base, Threat, Environmental et Supplemental mieux séparés. Ici, tu apprends à lire précisément 3.1 sans en faire la totalité de la décision."),
    schema([
      "Repère simple pour la priorisation",
      "",
      "CVSS élevé + actif public critique = souvent priorité haute",
      "CVSS moyen + portail d’authentification = peut monter",
      "CVSS élevé + service interne très segmenté = peut descendre",
      "KEV oui = signal fort, pas passe-droit pour un faux positif",
    ].join("\n")),
    text("EPSS ajoute un autre angle : la probabilité d’exploitation dans les 30 jours. Une valeur proche de 1 attire l’attention, mais ne remplace pas la validation locale. KEV apporte un signal encore plus fort : la vulnérabilité a déjà été exploitée dans la nature. Pourtant, même KEV ne sauve pas une mauvaise observation. Si la version locale n’est pas touchée ou si le constat n’est pas confirmé, le fait d’être dans KEV ne le transforme pas en priorité réelle."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script local ci-dessous recalcule trois notes CVSS 3.1 à partir de vecteurs connus, puis trie cinq constats fictifs selon une règle volontairement simple qui combine note, EPSS, KEV et criticité métier. Le but est d’apprendre à justifier une priorité, pas d’inventer une formule magique universelle."),
    code([
      "# fichier demo-priorisation-risque.cjs",
      "const roundUp1 = (value) => {",
      "  const scaled = Math.round(value * 100000);",
      "  return scaled % 10000 === 0 ? scaled / 100000 : (Math.floor(scaled / 10000) + 1) / 10;",
      "};",
      "const metrics = {",
      "  AV: { N: 0.85, A: 0.62, L: 0.55, P: 0.2 },",
      "  AC: { L: 0.77, H: 0.44 },",
      "  PRU: { N: 0.85, L: 0.62, H: 0.27 },",
      "  PRC: { N: 0.85, L: 0.68, H: 0.5 },",
      "  UI: { N: 0.85, R: 0.62 },",
      "  CIA: { H: 0.56, L: 0.22, N: 0 },",
      "};",
      "function score(vector) {",
      "  const parts = Object.fromEntries(vector.replace('CVSS:3.1/', '').split('/').map((item) => item.split(':')));",
      "  const C = metrics.CIA[parts.C];",
      "  const I = metrics.CIA[parts.I];",
      "  const A = metrics.CIA[parts.A];",
      "  const ISS = 1 - (1 - C) * (1 - I) * (1 - A);",
      "  const impact = parts.S === 'U'",
      "    ? 6.42 * ISS",
      "    : 7.52 * (ISS - 0.029) - 3.25 * Math.pow(ISS - 0.02, 15);",
      "  const PR = parts.S === 'U' ? metrics.PRU[parts.PR] : metrics.PRC[parts.PR];",
      "  const exploitability = 8.22 * metrics.AV[parts.AV] * metrics.AC[parts.AC] * PR * metrics.UI[parts.UI];",
      "  if (impact <= 0) return 0;",
      "  const total = parts.S === 'U' ? Math.min(impact + exploitability, 10) : Math.min(1.08 * (impact + exploitability), 10);",
      "  return roundUp1(total);",
      "}",
      "const vectors = [",
      "  'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',",
      "  'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',",
      "  'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H',",
      "];",
      "const scores = vectors.map((vector) => ({ vector, score: score(vector) }));",
      "const findings = [",
      "  { id: 'V21', cvss: 6.1, epss: 0.72, kev: false, business: 5 },",
      "  { id: 'V34', cvss: 8.8, epss: 0.11, kev: false, business: 2 },",
      "  { id: 'V52', cvss: 7.5, epss: 0.41, kev: true, business: 4 },",
      "  { id: 'V61', cvss: 5.3, epss: 0.09, kev: false, business: 3 },",
      "  { id: 'V70', cvss: 4.8, epss: 0.63, kev: false, business: 1 },",
      "];",
      "const ranked = findings.map((item) => ({",
      "  ...item,",
      "  priorityScore: +(item.cvss + item.epss * 2 + (item.kev ? 2 : 0) + item.business).toFixed(2),",
      "})).sort((a, b) => b.priorityScore - a.priorityScore);",
      "console.log(JSON.stringify({ scores, ranked }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"scores\": [",
      "//     { \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H\", \"score\": 9.8 },",
      "//     { \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N\", \"score\": 6.1 },",
      "//     { \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H\", \"score\": 8.8 }",
      "//   ],",
      "//   \"ranked\": [",
      "//     { \"id\": \"V52\", \"cvss\": 7.5, \"epss\": 0.41, \"kev\": true, \"business\": 4, \"priorityScore\": 14.32 },",
      "//     { \"id\": \"V21\", \"cvss\": 6.1, \"epss\": 0.72, \"kev\": false, \"business\": 5, \"priorityScore\": 12.54 },",
      "//     { \"id\": \"V34\", \"cvss\": 8.8, \"epss\": 0.11, \"kev\": false, \"business\": 2, \"priorityScore\": 11.02 },",
      "//     { \"id\": \"V61\", \"cvss\": 5.3, \"epss\": 0.09, \"kev\": false, \"business\": 3, \"priorityScore\": 8.48 },",
      "//     { \"id\": \"V70\", \"cvss\": 4.8, \"epss\": 0.63, \"kev\": false, \"business\": 1, \"priorityScore\": 7.06 }",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : le constat « V21 » n’a qu’un CVSS 6.1, mais il touche un portail d’authentification public très critique. « V34 » monte à 8.8 techniquement, pourtant il reste cantonné à un service interne fortement segmenté avec peu d’exposition. « V52 » cumule un score élevé, un signal KEV et une forte criticité métier : il passe logiquement en tête. La bonne restitution explique ce raisonnement au lieu de réciter un classement automatique."),
    mistakes("lire EPSS comme une gravité ; croire qu’un élément dans KEV devient prioritaire même s’il est faux positif ; trier mécaniquement par CVSS sans regarder l’actif ; oublier qu’un contrôle compensatoire peut réduire l’urgence réelle."),
    safety("tu n’as pas besoin d’un code d’exploitation pour prioriser un constat. Tu travailles à partir d’un export, d’une preuve minimale, de notes de validation et de la criticité métier. Si un doute subsiste sur la version touchée ou le périmètre, tu l’écris au lieu de forcer une priorité artificielle."),
    takeaway("CVSS t’aide à parler de gravité, EPSS te parle de probabilité d’exploitation et KEV de réalité observée sur le terrain. La priorité finale naît du contexte métier, des preuves et des contrôles déjà en place."),
    practice("Travaille dans « TP 4 : trier le rapport d’un scanner de vulnérabilités » : tu y recalculeras des notes, reliras un tableau EPSS/KEV fictif et défendras un ordre de correction. Termine ensuite par le quiz."),
    reference("cvss31Spec"),
    reference("cvss31Calculator"),
    reference("cvss4Spec"),
    reference("firstEpss"),
    reference("firstEpssFaq"),
    reference("cisaKev"),
    reference("nvdCvss31Calculator"),
  ],
  quiz: {
    title: "Quiz : priorisation du risque",
    questions: [
      questions.choice("Que décrit d’abord un score CVSS ?", ["La sévérité technique du constat", "Le budget nécessaire à la correction", "La date probable du prochain incident", "Le niveau juridique de l’autorisation"], 0, "CVSS décrit avant tout la gravité technique selon un vecteur précis. La mauvaise réponse la plus tentante est la priorité globale, mais celle-ci dépend encore de l’exposition, de la criticité métier et des contrôles compensatoires.", "facile"),
      questions.choice("Quel énoncé décrit le mieux EPSS ?", ["Une note réglementaire imposée par la NVD", "Une estimation de probabilité d’exploitation sur 30 jours, à relire avec le contexte", "Une preuve qu’une faille est déjà exploitée en production", "Une version simplifiée de CVSS 4.0"], 1, "EPSS est un score probabiliste utile pour prioriser, pas une preuve d’exploitation observée ni une gravité en soi. La confusion la plus fréquente consiste justement à le lire comme un verdict définitif alors qu’il complète d’autres signaux.", "moyen"),
      questions.multi("Quels éléments peuvent faire monter ou descendre une priorité réelle ? (plusieurs réponses)", ["La criticité métier de l’actif", "La présence de contrôles compensatoires", "L’exposition publique ou non", "Le seul fait qu’un chiffre CVSS soit élevé"], [0, 1, 2], "La priorité dépend du métier, de l’exposition, des contrôles en place et des preuves disponibles. Un score CVSS élevé compte, mais il ne suffit pas à lui seul à décider l’ordre de correction sans regarder où vit le problème et ce qui limite déjà son impact.", "difficile"),
      questions.tf("Une entrée dans KEV apporte un signal fort, mais elle ne transforme pas un faux positif en constat prioritaire.", true, "Vrai : KEV indique qu’une vulnérabilité est exploitée dans la nature, pas que ton observation locale est forcément correcte. Si la version n’est pas touchée ou si la preuve est fausse, le bon réflexe reste de corriger l’analyse avant de corriger le système.", "moyen"),
    ],
  },
};

const webCartographieLesson: NewLesson = {
  key: "pt-web-cartographie",
  title: "Cartographier une application web : proxy d’interception et plan du site",
  summary: "Tu apprends à lire un historique de proxy, à dégager les routes, rôles et points sensibles, puis à produire un plan du site avant toute conclusion de sécurité.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("décrire le rôle d’un proxy d’interception, repérer routes, méthodes et rôles, distinguer cartographie et vulnérabilité, puis résumer une application web en zones utiles au test."),
    prerequisites("connaître les bases d’HTTP et savoir qu’un test web doit rester dans un périmètre autorisé, avec des comptes et des règles d’engagement fournis."),
    scenario("Awa reçoit un export d’historique de proxy pour une application de la boutique Soleil. Les requêtes couvrent la connexion, le compte client, un espace d’administration, une API et un téléversement. Avant de chercher la moindre faiblesse, elle doit comprendre qui parle à qui, avec quelles méthodes, quels cookies et quelles routes sensibles."),
    videoSlot("Voir une application web avant de la juger"),
    text("La première valeur d’un proxy d’interception n’est pas d’attaquer. C’est de voir. Un historique de proxy te montre des routes, des paramètres, des méthodes HTTP, des codes de retour, des en-têtes, des cookies et parfois des rôles différents. Tant que tu n’as pas construit ce plan du site, tu risques de confondre une redirection normale avec un bug, une route interne avec une fonctionnalité publique, ou un simple asset avec un point d’entrée métier."),
    schema([
      "Carte simple d’une application web",
      "",
      "auth      -> login, reset, logout",
      "compte    -> profil, commandes, documents",
      "admin     -> export, gestion, tableaux",
      "api       -> /api/... et objets métier",
      "upload    -> dépôt et lecture de fichiers",
      "",
      "Cartographier avant de tester",
    ].join("\n")),
    text("Burp Suite Community Edition et OWASP ZAP sont surtout utiles ici comme instruments de lecture et de consignation. Tu y regardes le plan du site, les méthodes « GET » et « POST », les chemins répétés, les changements de code de statut, les cookies de session, les téléchargements, les exports et les routes qui semblent liées à l’administration. Une route cachée ou peu vue n’est pas automatiquement une vulnérabilité. C’est d’abord un élément de la surface fonctionnelle."),
    schema([
      "Ce que tu relèves dans un historique",
      "",
      "méthode   -> GET, POST, PUT, DELETE",
      "route     -> chemin et zone fonctionnelle",
      "rôle      -> compte utilisé ou contexte",
      "indices   -> cookies, televersement, export",
      "preuve    -> code, taille, en-tête, réponse",
    ].join("\n")),
    text("Le plan du site devient utile quand il relie les routes au métier. Une route « /api/orders/42 » n’a pas le même poids qu’un « /assets/app.css ». Une route « /admin/export » n’a pas la même sensibilité qu’un « /contact ». En pratique, tu regroupes donc les requêtes par zones : authentification, compte, documents, API, administration, téléversement. Tu notes aussi le ou les rôles utilisés, car la suite du test web dépend presque toujours de cette séparation."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script local ci-dessous lit un mini historique fictif, supprime les assets statiques, compte les requêtes fonctionnelles et produit une carte courte « route / méthodes / codes / session ». Cette étape suffit déjà à préparer un TP de lecture d’historique sans lancer d’action sur une application réelle."),
    code([
      "# fichier demo-web-cartographie.cjs",
      "const entries = [",
      "  { method: 'GET', path: '/login', status: 200, hasCookie: false },",
      "  { method: 'POST', path: '/login', status: 302, hasCookie: false },",
      "  { method: 'GET', path: '/account/orders', status: 200, hasCookie: true },",
      "  { method: 'GET', path: '/api/orders/42', status: 200, hasCookie: true },",
      "  { method: 'GET', path: '/admin/export', status: 403, hasCookie: true },",
      "  { method: 'POST', path: '/upload', status: 200, hasCookie: true },",
      "  { method: 'GET', path: '/assets/app.css', status: 200, hasCookie: false },",
      "];",
      "const zoneOf = (path) => path.startsWith('/admin') ? 'admin' :",
      "  path.startsWith('/api') ? 'api' :",
      "  path.startsWith('/account') ? 'compte' :",
      "  path.startsWith('/upload') ? 'upload' :",
      "  path.startsWith('/login') ? 'auth' : 'autre';",
      "const functional = entries.filter((item) => !item.path.startsWith('/assets/'));",
      "const map = [...new Set(functional.map((item) => item.path))].map((path) => {",
      "  const related = functional.filter((item) => item.path === path);",
      "  return {",
      "    path,",
      "    zone: zoneOf(path),",
      "    methods: [...new Set(related.map((item) => item.method))],",
      "    statuses: [...new Set(related.map((item) => item.status))],",
      "    withCookie: related.filter((item) => item.hasCookie).length,",
      "    sensitive: /^\\/(admin|api|upload)/.test(path),",
      "  };",
      "});",
      "console.log(JSON.stringify({ requestCount: functional.length, map }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"requestCount\": 6,",
      "//   \"map\": [",
      "//     { \"path\": \"/login\", \"zone\": \"auth\", \"methods\": [\"GET\", \"POST\"], \"statuses\": [200, 302], \"withCookie\": 0, \"sensitive\": false },",
      "//     { \"path\": \"/account/orders\", \"zone\": \"compte\", \"methods\": [\"GET\"], \"statuses\": [200], \"withCookie\": 1, \"sensitive\": false },",
      "//     { \"path\": \"/api/orders/42\", \"zone\": \"api\", \"methods\": [\"GET\"], \"statuses\": [200], \"withCookie\": 1, \"sensitive\": true },",
      "//     { \"path\": \"/admin/export\", \"zone\": \"admin\", \"methods\": [\"GET\"], \"statuses\": [403], \"withCookie\": 1, \"sensitive\": true },",
      "//     { \"path\": \"/upload\", \"zone\": \"upload\", \"methods\": [\"POST\"], \"statuses\": [200], \"withCookie\": 1, \"sensitive\": true }",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : ici, six requêtes fonctionnelles suffisent à faire ressortir cinq routes utiles et trois zones sensibles probables. « /admin/export » mérite déjà un drapeau de sensibilité, même si la réponse actuelle est « 403 ». La bonne note n’est pas « vulnérabilité d’accès admin », mais « route d’administration visible à suivre avec un compte de rôle différent si le cadre le permet ». De la même façon, « /upload » signale une zone utile pour la suite, sans conclure à un problème tant qu’aucune preuve bénigne n’a été observée."),
    mistakes("tester une route avant d’avoir identifié son rôle métier ; compter les assets statiques comme des fonctionnalités sensibles ; confondre une route d’administration visible avec un accès cassé ; oublier quel compte a produit quelle requête dans l’historique."),
    safety("le proxy d’interception sert ici à relire un historique fourni, sur ton laboratoire ou dans un périmètre explicitement autorisé. Tu n’emploies pas cette leçon pour intercepter le trafic d’un tiers ou contourner un accès protégé."),
    takeaway("voir une application web avant de la tester évite beaucoup d’erreurs. Une bonne cartographie relie routes, méthodes, rôles et zones sensibles. Elle prépare le test et améliore la qualité des preuves à venir."),
    practice("Travaille dans « TP 5 : analyser l’historique d’un test d’application web » : tu y transformeras un historique de proxy fourni en plan du site, en distinguant fonctionnalités métier, administration, API et bruit. Termine ensuite par le quiz."),
    reference("burpGettingStarted"),
    reference("zapGettingStarted"),
    reference("owaspWstg"),
    reference("portSwiggerAcademy"),
    reference("owaspCsAttackSurface"),
  ],
  quiz: {
    title: "Quiz : cartographier une application web",
    questions: [
      questions.choice("Pourquoi commencer par cartographier l’application ?", ["Pour comprendre routes, rôles et zones sensibles avant d’interpréter un comportement", "Pour prouver plus vite une injection SQL", "Pour remplacer le besoin de comptes de test", "Pour ignorer les codes de statut"], 0, "La cartographie sert d’abord à comprendre ce que l’application expose et comment elle s’organise. La fausse bonne réponse la plus tentante est la preuve rapide d’une faille, alors qu’un test fiable commence par une lecture structurée des routes et des rôles.", "facile"),
      questions.choice("Que vaut un chemin « /admin/export » vu dans un historique avec une réponse « 403 » ?", ["Une preuve automatique de contrôle d’accès cassé", "Une route sensible à documenter et à relire, pas encore une faille démontrée", "Un asset statique sans intérêt", "Une permission implicite de retester hors cadre"], 1, "Une route d’administration visible reste un élément important de la surface fonctionnelle, mais un « 403 » cohérent peut justement montrer un contrôle qui tient. La tentation serait de baptiser « faille » toute route sensible, ce qui ferait disparaître la nuance essentielle entre visibilité et faiblesse.", "moyen"),
      questions.multi("Quels éléments aident vraiment à bâtir un plan du site utile ? (plusieurs réponses)", ["Les méthodes HTTP observées", "Les rôles ou comptes utilisés", "Les zones fonctionnelles comme auth, compte, admin ou API", "Le simple fait qu’un fichier CSS existe"], [0, 1, 2], "Méthodes, rôles et zones fonctionnelles donnent une lecture métier du trafic. Un fichier CSS peut être utile au rendu, mais il n’aide pas à lui seul à comprendre l’architecture fonctionnelle du test ou la priorité des vérifications suivantes.", "difficile"),
      questions.tf("Une cartographie propre peut déjà améliorer le cadrage du test, même avant la moindre preuve de vulnérabilité.", true, "Vrai : elle aide à savoir où passent les comptes, quels points d’entrée semblent sensibles et quelles routes méritent une relecture plus précise. Cette préparation réduit les erreurs d’interprétation et évite des manipulations inutiles ou hors sujet.", "moyen"),
    ],
  },
};

const webAuthentificationLesson: NewLesson = {
  key: "pt-web-authentification",
  title: "Tester l’authentification, les sessions et le contrôle d’accès",
  summary: "Tu apprends à relire des comptes de test, des cookies et des réponses HTTP pour documenter sobrement l’authentification, la session et l’autorisation.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("distinguer identité, authentification et autorisation, relire un cookie de session, comparer deux rôles sur une même route, puis écrire une preuve minimale d’accès ou de session."),
    prerequisites("savoir cartographier une application web, comprendre le principe des comptes de test et connaître les bases d’HTTP, des cookies et des codes de statut."),
    scenario("Ama audite l’application de l’association Teranga avec deux comptes de test fournis : un compte standard et un compte administrateur. Elle doit vérifier la connexion, la déconnexion, les cookies, les routes d’administration et quelques objets métiers, sans forcer le moindre mot de passe ni contourner une authentification multifacteur."),
    videoSlot("Comparer deux rôles sans sortir du cadre"),
    text("L’authentification répond à la question « qui es-tu ? ». La session répond à « comment l’application se souvient-elle de toi ? ». L’autorisation répond à « as-tu le droit de faire cela ? ». En test web, ces trois axes se croisent souvent, mais il faut les distinguer si tu veux écrire un constat propre. Un message de connexion mal conçu n’est pas automatiquement un défaut d’accès. Un cookie présent n’est pas automatiquement une mauvaise session. Et un « 403 » peut au contraire montrer que le contrôle d’accès fonctionne correctement."),
    schema([
      "Trois questions différentes",
      "",
      "identité      -> quel compte ou quel rôle ?",
      "authentification -> comment l’application te reconnaît ?",
      "autorisation  -> à quoi ce compte peut-il accéder ?",
      "",
      "Ne pas mélanger les trois",
    ].join("\n")),
    text("Pour l’authentification, tu relis surtout les écrans et flux de connexion, les réinitialisations, le verrouillage, les comptes de test fournis et les différences de messages. Pour la session, tu regardes les cookies, la déconnexion, l’expiration, le renouvellement et les attributs comme « Secure » ou « HttpOnly ». Pour l’autorisation, tu compares la même route ou le même objet avec deux rôles différents. C’est cette comparaison qui permet de documenter un IDOR/BOLA ou un contrôle d’accès horizontal ou vertical défaillant."),
    schema([
      "Ce qu’une relecture utile observe",
      "",
      "login/logout -> codes, redirections, messages",
      "Set-Cookie   -> HttpOnly, Secure, SameSite",
      "route admin  -> 200, 302, 403, 404 selon le rôle",
      "objet metier -> lecture de son objet vs objet d’un autre",
    ].join("\n")),
    text("La preuve minimale approuvée reste sobre. Un compte standard qui obtient « 200 » sur « /admin/export » alors qu’un second historique montre qu’il devrait être bloqué suffit déjà à documenter un contrôle d’accès cassé. De la même façon, un cookie de session sans attribut attendu peut devenir un constat de gestion de session. En revanche, tu n’as pas besoin de voler une session, de casser une MFA ou de contourner un verrouillage pour prouver ce type de faiblesse dans ce parcours."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script local ci-dessous relit des « Set-Cookie » fictifs et compare la réponse de deux rôles sur trois routes. Il te montre comment résumer un historique sans ajouter d’action intrusive."),
    code([
      "# fichier demo-web-auth-session.cjs",
      "const cookies = [",
      "  'sid=abc123; Path=/; Secure; SameSite=Lax',",
      "  'prefs=light; Path=/'",
      "];",
      "const routes = [",
      "  { role: 'standard', path: '/profile', status: 200 },",
      "  { role: 'admin', path: '/profile', status: 200 },",
      "  { role: 'standard', path: '/admin/export', status: 200 },",
      "  { role: 'admin', path: '/admin/export', status: 200 },",
      "  { role: 'standard', path: '/api/orders/42', status: 403 },",
      "  { role: 'admin', path: '/api/orders/42', status: 200 },",
      "];",
      "const cookieAudit = cookies.map((value) => ({",
      "  value,",
      "  missing: ['HttpOnly', 'Secure', 'SameSite'].filter((item) => !new RegExp(item).test(value)),",
      "}));",
      "const byPath = [...new Set(routes.map((item) => item.path))].map((path) => ({",
      "  path,",
      "  statuses: routes.filter((item) => item.path === path).map((item) => `${item.role}:${item.status}`),",
      "}));",
      "console.log(JSON.stringify({ cookieAudit, byPath }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"cookieAudit\": [",
      "//     { \"value\": \"sid=abc123; Path=/; Secure; SameSite=Lax\", \"missing\": [\"HttpOnly\"] },",
      "//     { \"value\": \"prefs=light; Path=/\", \"missing\": [\"HttpOnly\", \"Secure\", \"SameSite\"] }",
      "//   ],",
      "//   \"byPath\": [",
      "//     { \"path\": \"/profile\", \"statuses\": [\"standard:200\", \"admin:200\"] },",
      "//     { \"path\": \"/admin/export\", \"statuses\": [\"standard:200\", \"admin:200\"] },",
      "//     { \"path\": \"/api/orders/42\", \"statuses\": [\"standard:403\", \"admin:200\"] }",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : ici, le couple le plus inquiétant n’est pas seulement l’absence de « HttpOnly » sur le cookie principal. C’est surtout le fait qu’un compte standard reçoive « 200 » sur « /admin/export », exactement comme l’administrateur, alors que « /profile » reste logiquement accessible aux deux rôles. La route « /api/orders/42 » montre au contraire une séparation correcte avec « 403 » pour l’utilisateur standard. Ce contraste t’aide à écrire un constat précis au lieu d’accuser toute l’application d’avoir « des droits cassés partout »."),
    mistakes("confondre authentification et autorisation ; tester avec un compte réel au lieu d’un compte fourni ; appeler « défaut » une simple différence de message sans impact ; oublier la déconnexion ou les attributs de cookie en se focalisant seulement sur les routes d’admin."),
    safety("aucune force brute, aucun vol de session, aucun contournement MFA et aucune réutilisation de compte réel n’ont leur place ici. Tu restes sur des comptes de test fournis, une plateforme d’entraînement légale ou ton propre laboratoire, avec des preuves minimales et des règles d’arrêt claires."),
    takeaway("pour bien tester le web, il faut séparer authentification, session et autorisation. Deux comptes de test et une comparaison propre valent mieux qu’une hypothèse. Une bonne preuve minimale montre la différence de comportement, pas une démonstration excessive."),
    practice("Travaille dans « TP 5 : analyser l’historique d’un test d’application web » : tu y reliras des cookies, des routes et des réponses de deux rôles pour distinguer session, accès correct et contrôle d’accès cassé. Termine ensuite par le quiz."),
    reference("owaspWstg"),
    reference("owaspCsSession"),
    reference("owaspCsAuthorization"),
    reference("owaspCsIdor"),
    reference("owaspApiTop10"),
    reference("owaspApi1Bola2023"),
    reference("mdnSetCookie"),
    reference("nist80063b4"),
  ],
  quiz: {
    title: "Quiz : authentification, session et accès",
    questions: [
      questions.choice("Quelle question relève d’abord de l’autorisation ?", ["Comment l’application crée le cookie de session", "Si ce compte a le droit d’ouvrir cette ressource ou cette fonction", "Quel navigateur l’utilisateur emploie", "Quelle bannière répond sur le port 443"], 1, "L’autorisation détermine ce qu’un compte peut faire ou lire. La réponse tentante est le cookie de session, qui relève plutôt de la gestion de session et de l’authentification persistante, pas du contrôle des droits métier.", "facile"),
      questions.choice("Pourquoi comparer deux rôles sur la même route est-il si utile ?", ["Parce que cela remplace toute lecture des en-têtes", "Parce que la différence ou l’absence de différence de réponse aide à prouver un défaut d’accès ou au contraire un refus légitime", "Parce que cela force toujours un code 500", "Parce que cela supprime le besoin de comptes de test"], 1, "Comparer deux rôles permet d’observer si l’application bloque vraiment un accès ou traite tout le monde pareil. L’erreur tentante est de croire qu’un historique ou un en-tête isolé suffit toujours, alors qu’un défaut d’autorisation se démontre souvent par contraste.", "moyen"),
      questions.multi("Quels indices appartiennent bien à une relecture de session ? (plusieurs réponses)", ["Les attributs d’un cookie comme Secure ou HttpOnly", "Le comportement de la déconnexion", "La possibilité de lire l’objet d’un autre compte", "L’expiration ou le renouvellement de la session"], [0, 1, 3], "Les attributs de cookie, la déconnexion et l’expiration relèvent de la gestion de session. Lire l’objet d’un autre compte touche surtout au contrôle d’accès, même si la session sert de support technique à cette vérification.", "difficile"),
      questions.tf("Un « 403 » cohérent pour le compte standard sur une route sensible peut constituer un bon signe de contrôle d’accès, pas un constat de faille.", true, "Vrai : dans un historique correctement relu, un refus cohérent est une information utile, car il montre justement que la séparation des rôles fonctionne à cet endroit. Tout refus n’est donc pas un problème ; il faut relier le code au rôle attendu et à la fonctionnalité testée.", "moyen"),
    ],
  },
};

const webEntreesLesson: NewLesson = {
  key: "pt-web-entrees",
  title: "Tester les entrées : injections, XSS et téléversements avec des preuves minimales",
  summary: "Tu apprends à choisir des observations bénignes sur les entrées d’une application web, puis à documenter un indice utile sans glisser vers une charge d’exploitation.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("repérer les champs intéressants, choisir une charge bénigne, distinguer reflet, erreur et acceptation, puis classer l’observation selon OWASP et CWE sans dépasser le cadre."),
    prerequisites("savoir cartographier une application web, comprendre la notion de preuve minimale et connaître les différences entre contrôle d’accès, session et validation des entrées."),
    scenario("Koffi relit l’historique d’un test web fourni sur une application de démonstration. Il voit un champ de recherche refléter une valeur neutre, un message d’erreur côté serveur sur un paramètre inattendu et un formulaire de téléversement qui accepte un type de fichier surprenant. Il doit décider ce que chaque observation prouve vraiment et jusqu’où il peut aller sans quitter le cadre défensif."),
    videoSlot("Vérifier une entrée sans transformer le test en attaque"),
    text("Tester les entrées en pentest ne consiste pas à rejouer un catalogue de charges célèbres. Cela consiste d’abord à identifier les zones où une entrée utilisateur influence une recherche, un filtre, un message, un fichier ou une action métier, puis à demander : quelle observation bénigne suffit à montrer que la validation, l’encodage ou le contrôle attendu n’est pas au rendez-vous ? Dans ce parcours, tu restes sur des preuves minimales et des charges inoffensives."),
    schema([
      "Angles de lecture sur les entrées",
      "",
      "recherche / filtre -> reflet, erreur, différence de résultat",
      "champ libre        -> encodage, validation, message",
      "identifiant objet  -> changement de cible ou refus",
      "televersement      -> type annonce, type accepte, statut",
      "",
      "On observe d’abord, on conclut ensuite",
    ].join("\n")),
    text("Pour une injection supposée, un message d’erreur ou une différence de comportement peut suffire à signaler un manque de robustesse, sans conclure encore à une exploitation possible. Pour un XSS, un reflet bénin et contrôlé peut déjà signaler une surface à confirmer, sans suffire à lui seul à démontrer qu’un script s’exécute. Pour un téléversement, l’acceptation d’un fichier de test anodin avec un type inattendu peut démontrer un contrôle trop faible. À chaque fois, le bon constat dit exactement ce qui a été observé, ce que cela suggère, et ce que tu n’as pas fait."),
    schema([
      "Ce qu’on écrit / ce qu’on n’écrit pas",
      "",
      "oui  -> valeur bénigne reflétée",
      "oui  -> message d’erreur reproductible",
      "oui  -> fichier de test accepté à tort",
      "non  -> webshell ou extraction massive",
      "non  -> charge destructive ou intrusive",
    ].join("\n")),
    text("Cette discipline évite trois erreurs fréquentes. La première est de confondre acceptation et exécution : un téléversement peut accepter un fichier sans jamais l’exécuter. La deuxième est de confondre erreur et injection démontrée : un « 500 » seul n’est pas une preuve complète. La troisième est de recopier des charges offensives dont tu n’as pas besoin pour écrire un constat défendable. Le parcours Sécurité Web explique déjà la mécanique de SQL, XSS, validation et téléversement. Ici, ton angle est celui du pentest responsable : preuve minimale, classement OWASP Top 10:2025, rattachement CWE et rédaction prudente."),
    schema([
      "Mini-tableau de tri",
      "",
      "reflet contrôlé        -> A05 Injection (à confirmer) -> CWE à confirmer -> pas de script actif",
      "erreur détaillée       -> A10 Mishandling of Exceptional Conditions -> CWE-209 -> pas de charge intrusive",
      "téléversement accepté  -> catégorie OWASP à confirmer -> CWE-434 -> pas de webshell",
      "",
      "Toujours ecrire ce que tu n’as pas fait",
    ].join("\n")),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script local ci-dessous prend quatre observations fictives et leur assigne une catégorie, une preuve retenue, une étiquette OWASP, une CWE et la décision « stop ici ». Il ne génère aucune charge active. Il t’aide seulement à relire un historique de manière propre et cohérente."),
    code([
      "# fichier demo-web-entrees.cjs",
      "const observations = [",
      "  { id: 'E04', type: 'reflet', note: 'la valeur cyberpingo-test reapparait dans la page', route: '/search' },",
      "  { id: 'E09', type: 'erreur', note: 'message d erreur detaille avec chemin serveur sur un parametre inattendu', route: '/invoice/view' },",
      "  { id: 'E13', type: 'upload', note: 'fichier texte accepte avec un type annonce inattendu', route: '/upload' },",
      "  { id: 'E17', type: 'controle-ok', note: 'fichier refuse correctement', route: '/upload' },",
      "];",
      "const classify = (item) => ({",
      "  id: item.id,",
      "  categorie: item.type === 'reflet' ? 'xss-a-confirmer' : item.type === 'erreur' ? 'erreur-a-relire' : item.type === 'upload' ? 'televersement' : 'controle-correct',",
      "  preuve: item.type === 'controle-ok' ? 'pas de constat' : item.note,",
      "  owasp: item.type === 'reflet' ? 'A05 Injection (a confirmer)' : item.type === 'erreur' ? 'A10 Mishandling of Exceptional Conditions' : item.type === 'upload' ? 'categorie OWASP a confirmer' : 'aucune',",
      "  cwe: item.type === 'reflet' ? 'a confirmer' : item.type === 'erreur' ? 'CWE-209' : item.type === 'upload' ? 'CWE-434' : 'aucune',",
      "  nePasFaire: item.type === 'reflet' ? 'pas de script actif' : item.type === 'erreur' ? 'pas de charge intrusive' : item.type === 'upload' ? 'pas de webshell' : 'rien de plus a faire',",
      "  decision: item.type === 'controle-ok' ? 'documenter le refus' : 'stop ici',",
      "});",
      "console.log(JSON.stringify(observations.map(classify), null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// [",
      "//   { \"id\": \"E04\", \"categorie\": \"xss-a-confirmer\", \"preuve\": \"la valeur cyberpingo-test reapparait dans la page\", \"owasp\": \"A05 Injection (a confirmer)\", \"cwe\": \"a confirmer\", \"nePasFaire\": \"pas de script actif\", \"decision\": \"stop ici\" },",
      "//   { \"id\": \"E09\", \"categorie\": \"erreur-a-relire\", \"preuve\": \"message d erreur detaille avec chemin serveur sur un parametre inattendu\", \"owasp\": \"A10 Mishandling of Exceptional Conditions\", \"cwe\": \"CWE-209\", \"nePasFaire\": \"pas de charge intrusive\", \"decision\": \"stop ici\" },",
      "//   { \"id\": \"E13\", \"categorie\": \"televersement\", \"preuve\": \"fichier texte accepte avec un type annonce inattendu\", \"owasp\": \"categorie OWASP a confirmer\", \"cwe\": \"CWE-434\", \"nePasFaire\": \"pas de webshell\", \"decision\": \"stop ici\" },",
      "//   { \"id\": \"E17\", \"categorie\": \"controle-correct\", \"preuve\": \"pas de constat\", \"owasp\": \"aucune\", \"cwe\": \"aucune\", \"nePasFaire\": \"rien de plus a faire\", \"decision\": \"documenter le refus\" }",
      "// ]",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : la valeur neutre « cyberpingo-test » reflétée dans une zone sensible suffit à documenter une entrée qui ressort à un endroit sensible, utile à relire sous l’angle « A05 Injection », sans rattacher trop vite le cas à « CWE-79 » tant qu’aucune exécution n’est démontrée. Un message d’erreur détaillé qui révèle une trace, un chemin ou une information interne devient une anomalie à classer sous « A10 Mishandling of Exceptional Conditions » et « CWE-209 ». Le téléversement qui accepte un simple fichier texte avec un type inattendu peut, lui, devenir un constat de contrôle faible ; « CWE-434 » reste alors un bon repère technique, tandis que le rattachement OWASP dépend du contrôle manquant réellement observé."),
    mistakes("copier une charge connue au lieu de choisir une valeur bénigne ; conclure à une injection complète sur un simple message d’erreur ; confondre acceptation d’un fichier et exécution côté serveur ; oublier de lier le constat à une catégorie OWASP ou à une CWE utile."),
    safety("aucun webshell, aucune traversée active, aucune extraction de base réelle et aucune charge destructive n’ont leur place ici. Tu travailles sur un historique fourni, sur ton laboratoire ou sur une plateforme d’entraînement légale, avec des preuves minimales et des valeurs factices évidentes."),
    takeaway("sur les entrées web, voir juste vaut mieux que frapper fort. Une observation bénigne bien rédigée peut déjà suffire à documenter un défaut. Ton rôle est de prouver avec mesure, de classer avec précision et de t’arrêter avant l’escalade inutile."),
    practice("Travaille dans « TP 5 : analyser l’historique d’un test d’application web » : tu y reliras des observations sur des entrées, des téléversements et des réponses d’erreur pour juger ce qui est prouvé, ce qui reste hypothétique et ce qui doit rester hors cadre. Termine ensuite par le quiz."),
    reference("owaspTop10A02"),
    reference("owaspTop10A05"),
    reference("owaspTop10A10"),
    reference("owaspCsInputValidation"),
    reference("owaspCsXss"),
    reference("owaspCsFileUpload"),
    reference("cwe79"),
    reference("cwe209"),
    reference("cwe434"),
  ],
  quiz: {
    title: "Quiz : tester les entrées",
    questions: [
      questions.choice("Quel est le bon réflexe de départ face à un champ utilisateur intéressant ?", ["Chercher d’abord une observation bénigne qui montre le comportement de l’entrée", "Lancer immédiatement une charge d’exploitation célèbre", "Téléverser un shell pour aller plus vite", "Conclure à une faille avant toute réponse"], 0, "Le bon réflexe consiste à demander ce qu’une observation simple et sans impact peut déjà démontrer. La réponse tentante est la charge célèbre, alors qu’elle sort souvent du besoin réel et peut transformer une lecture utile en action inutilement risquée.", "facile"),
      questions.choice("Pourquoi un fichier de test accepté avec un type inattendu peut-il déjà être intéressant ?", ["Parce qu’il prouve forcément l’exécution côté serveur", "Parce qu’il peut démontrer un contrôle de téléversement trop faible même sans exécution", "Parce qu’il remplace toute relecture de la réponse HTTP", "Parce qu’il dispense de vérifier la route ou le rôle utilisé"], 1, "L’acceptation d’un fichier là où il devrait être rejeté peut suffire à montrer une validation trop faible. La fausse bonne réponse est l’exécution automatique : accepter n’est pas exécuter, et la rigueur consiste justement à ne pas prétendre plus que ce que la preuve montre.", "moyen"),
      questions.multi("Quelles formulations restent correctes dans ce parcours ? (plusieurs réponses)", ["« Valeur bénigne reflétée dans la réponse »", "« Message d’erreur reproductible à relire »", "« Webshell déployé pour confirmer »", "« Fichier de test anodin accepté à tort »"], [0, 1, 3], "Les trois formulations retenues décrivent une preuve minimale sobre et lisible. Le webshell, au contraire, sort du cadre pédagogique et éthique fixé ici, puisqu’il transforme une observation web en action intrusive inutile pour démontrer le problème.", "difficile"),
      questions.tf("Un refus correct d’un téléversement ou d’un paramètre manipulé mérite aussi d’être noté, car il montre qu’un contrôle fonctionne à cet endroit.", true, "Vrai : relire ce qui tient est aussi utile que documenter ce qui casse, surtout pour éviter les conclusions trop larges. Un bon test web ne transforme pas toute tentative en constat ; il note aussi les refus cohérents qui bornent correctement la surface exposée.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c5:6",
    position: 5,
    title: "Vulnérabilités et priorisation",
    description: "Ce module t’apprend à trier un rapport de vulnérabilités, à demander une preuve minimale avant d’affirmer, puis à prioriser avec des repères techniques et métier. Critères de réussite : distinguer alerte, faux positif et constat ; choisir une preuve suffisante sans exploiter ; classer des constats avec CVSS, EPSS, KEV et le contexte de l’organisation.",
    lessons: [scannersVulnsLesson, verifierSansExploiterLesson, priorisationRisqueLesson],
  },
  {
    key: "c5:7",
    position: 6,
    title: "Tester une application web",
    description: "Tu y apprendras à lire un historique de proxy, à cartographier une application web et à documenter des preuves minimales défendables sur l’authentification, les sessions, les accès et les entrées. Critères de réussite : produire un plan du site utile ; distinguer hypothèse et constat confirmé ; classer un constat web sans dépasser le cadre autorisé.",
    lessons: [webCartographieLesson, webAuthentificationLesson, webEntreesLesson],
  },
];
