import {
  code,
  example,
  figure,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const pentestCadreLesson: NewLesson = {
  key: "pentest-cadre",
  title: "Autorisation et périmètre d’un audit",
  summary: "Apprends à cadrer un test d’intrusion de façon défensive : autorisation écrite, périmètre explicite, exclusions, tiers et décision claire dès qu’une cible inattendue apparaît.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("distinguer test d’intrusion, audit et scan, repérer les éléments minimaux d’une autorisation écrite, lire un périmètre, vérifier si une cible entre dans le cadre, puis décider quoi clarifier avant toute action."),
    prerequisites("avoir les bases des parcours Fondamentaux et Réseaux, ou connaître les notions de domaine, d’adresse IP et de service exposé."),
    scenario("Awa prépare une mission pour Baobab Tech. La lettre de mission cite « example.com », « app.example.com » et la plage « 192.0.2.0/24 ». En relisant un certificat public, elle voit aussi « cdn.example.net ». La découverte semble utile, mais elle sait qu’un actif visible n’est pas automatiquement autorisé : elle doit d’abord décider ce qui est dans le périmètre, hors périmètre, ou à clarifier."),
    videoSlot("Autorisation écrite, périmètre et arrêt sur cible inconnue"),
    text("Un test d’intrusion sert à vérifier une exposition autorisée pour mieux la corriger. Ce n’est ni un concours d’agressivité, ni une permission générale de « voir ce qui passe ». Un scan automatisé liste surtout des indices techniques. Un audit peut inclure des preuves, des documents et de la configuration. Le test d’intrusion, lui, relie objectif, périmètre, méthode et restitution, dans un cadre explicitement accepté par le propriétaire."),
    figure({
      kind: "compare",
      title: "Décision avant toute action",
      sides: [
        {
          title: "Dans le périmètre",
          tone: "green",
          items: ["action permise"],
        },
        {
          title: "Exclu",
          tone: "red",
          items: ["pas d’action technique"],
        },
        {
          title: "Ambigu ou tiers non validé",
          tone: "amber",
          items: ["arrêt", "demande écrite de clarification"],
        },
      ],
      verdict: "On ne décide qu’après autorisation écrite, périmètre explicite, puis lecture de l’actif observé dans la mission.",
    }),
    text("Le cadrage minimal doit préciser les objectifs, le périmètre, les exclusions, les fenêtres horaires, les contacts, les conditions d’arrêt, la gestion des données et les tiers éventuels. Une cible nouvelle, un sous-domaine non listé, un CDN, une API SaaS ou une adresse vue dans un certificat ne changent pas ce cadre tout seuls. La règle défensive est simple : si le doute existe, on clarifie avant toute action."),
    code([
      "# prérequis",
      "node --version",
      "# exemple de sortie (valeurs fictives)",
      "# v26.7.0",
      "",
      "# vérifier un petit périmètre local fictif",
      "node -e \"const scope={domains:['example.com','app.example.com'], cidrs:['192.0.2.0/24'], excluded:['paiement.example.org'], clarify:['cdn.example.net']}; const ipToInt=(ip)=>ip.split('.').reduce((acc,octet)=>(acc<<8)+Number(octet),0)>>>0; const cidrContains=(cidr,ip)=>{const [base,bits]=cidr.split('/'); const mask=bits==='0' ? 0 : (0xffffffff << (32-Number(bits)))>>>0; return (ipToInt(base)&mask)===(ipToInt(ip)&mask);}; const countAddresses=(cidr)=>2**(32-Number(cidr.split('/')[1])); console.log('adresses IPv4 couvertes:', countAddresses(scope.cidrs[0])); console.log('cible 192.0.2.44:', cidrContains(scope.cidrs[0],'192.0.2.44') ? 'dans le périmètre' : 'hors périmètre'); console.log('cible cdn.example.net:', scope.clarify.includes('cdn.example.net') ? 'à clarifier' : 'hors périmètre'); console.log('cible paiement.example.org:', scope.excluded.includes('paiement.example.org') ? 'hors périmètre' : 'à clarifier');\"",
      "# exemple de sortie (valeurs fictives)",
      "# adresses IPv4 couvertes: 256",
      "# cible 192.0.2.44: dans le périmètre",
      "# cible cdn.example.net: à clarifier",
      "# cible paiement.example.org: hors périmètre",
    ].join("\n"), "bash"),
    text("Démonstration guidée : cette démonstration repose sur un petit jeu de données local décrivant le périmètre autorisé. Le script Node.js compte les adresses couvertes par un CIDR de documentation, vérifie si une IP d’exemple appartient bien à la plage autorisée, puis classe trois cibles en « dans le périmètre », « hors périmètre » ou « à clarifier ». Le but n’est pas de découvrir de nouvelles cibles, mais de s’entraîner à prendre une décision propre avant toute action technique."),
    example("Exemple corrigé : « example.com » et « app.example.com » figurent dans la mission, donc Awa peut préparer des vérifications sur ces noms. « 192.0.2.44 » appartient à « 192.0.2.0/24 », donc l’adresse est couverte. En revanche, « cdn.example.net » sert peut-être le site mais ne figure ni comme tiers autorisé ni comme actif du client : décision correcte, « à clarifier ». « paiement.example.org » est hors périmètre tant qu’aucune extension écrite ne l’ajoute."),
    mistakes("croire qu’un domaine principal autorise tous ses sous-domaines ; traiter une IP vue dans un certificat comme automatiquement testable ; oublier qu’un tiers SaaS ou CDN a ses propres règles ; penser qu’une découverte intéressante permet un détour sans validation."),
    safety("Tu ne testes que ton laboratoire, une plateforme d’entraînement légale, ou un système pour lequel tu disposes d’une autorisation écrite. Une cible ambiguë, même visible publiquement, reste interdite tant qu’elle n’est pas confirmée. En mission réelle, toute donnée observée doit être minimisée, protégée et partagée seulement avec les destinataires prévus."),
    takeaway("Le pentest défensif commence avant le premier paquet. Sans autorisation écrite claire, on ne teste rien. Sans périmètre explicite, on clarifie. Une cible découverte en cours de route n’entre jamais automatiquement dans la mission."),
    practice("Travaille dans « TP 1 : lire une lettre de mission et fixer le périmètre » : tu y relis une lettre de mission, des règles d’engagement et des cibles découvertes pour décider ce qui est autorisé, interdit ou à clarifier, puis tu termines par le quiz de la leçon."),
    reference("nistGlossaryPentest"),
    reference("nistGlossaryRoE"),
    reference("nist80115"),
    reference("ncscPentest"),
  ],
  quizExtension: {
    improve: [
      "L’autorisation écrite et le périmètre sont la base du test d’intrusion responsable. Une connexion Internet ou un outil payant n’ajoutent aucune légitimité. La mauvaise réponse la plus tentante est de croire que la visibilité publique d’un actif suffit, alors qu’elle ne remplace jamais un accord explicite.",
      "Une cible inconnue doit être clarifiée avant toute action, car une découverte technique n’étend pas le cadre juridique ou contractuel. La fausse bonne idée est de la tester « juste un peu » pour confirmer son intérêt, alors qu’un premier geste hors périmètre est déjà un écart de mission.",
    ],
    add: [
      questions.choice("Une mission mentionne « example.com » et « api.example.com », mais pas « cdn.example.net ». Quelle est la meilleure décision ?", ["Tester le CDN parce qu’il sert le site", "L’ignorer sans rien noter", "Le signaler et demander une clarification écrite avant toute action", "Le remplacer par une autre cible publique"], 2, "Le bon réflexe est de demander une clarification écrite. Le CDN peut appartenir à un tiers et avoir ses propres règles. La réponse la plus tentante est de le tester car il aide le site, mais utilité technique et autorisation sont deux choses différentes.", "moyen"),
      questions.multi("Lis cet extrait : « actifs autorisés : example.com, app.example.com, 192.0.2.0/24 ; exclusions : tout prestataire tiers ; condition d’arrêt : stabilité menacée ». Quelles affirmations sont correctes ? (plusieurs réponses)", ["192.0.2.44 peut entrer dans le périmètre si l’adresse appartient bien à la plage autorisée", "Un domaine tiers vu dans un certificat reste à clarifier", "Toute cible découverte pendant la mission devient autorisée si elle semble liée", "Une menace sur la stabilité impose l’arrêt et l’alerte du contact prévu"], [0, 1, 3], "La plage 192.0.2.0/24 couvre bien ses adresses internes, un tiers vu en route n’est pas autorisé par défaut, et une menace sur la stabilité déclenche l’arrêt prévu. La réponse la plus tentante mais fausse est de croire qu’une cible liée techniquement devient testable automatiquement.", "difficile"),
    ],
  },
};

const pentestMethodeLesson: NewLesson = {
  key: "pentest-methode",
  title: "Une méthode de test responsable",
  summary: "Suis une méthode de mission lisible et défensive : cadrage, reconnaissance, validation prudente, preuve minimale, journal horodaté, arrêt propre et restitution.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("ordonner les phases d’une mission, distinguer preuve minimale et geste intrusif, lire un journal horodaté, détecter une action hors fenêtre, puis expliquer quand il faut s’arrêter et prévenir."),
    prerequisites("avoir compris le rôle de l’autorisation écrite, du périmètre et des contacts prévus dans une mission."),
    scenario("Koffi et Fatou préparent une mission pour l’association Teranga. Tout est autorisé sur le papier, mais la vraie difficulté reste la discipline : noter ce qui est fait, choisir la preuve la moins intrusive et s’arrêter dès qu’un signe d’instabilité apparaît. Une méthode utile ne cherche pas à « pousser plus loin », elle cherche à démontrer proprement ce qui doit être corrigé."),
    videoSlot("Une méthode de test responsable, du cadrage à l’arrêt propre"),
    text("Une mission de test d’intrusion commence par le cadrage, puis enchaîne reconnaissance, validation prudente, collecte de preuves minimales et restitution. Cette chronologie n’a rien d’un rituel bureaucratique : elle réduit les erreurs, protège la disponibilité, et aide à expliquer après coup pourquoi chaque action a été faite. Une méthode saine documente aussi ce qu’elle refuse de faire : pas de preuve destructrice, pas d’écart aux règles d’engagement, pas de collecte excessive de données."),
    figure({
      kind: "steps",
      title: "Méthode simple de mission",
      numbered: true,
      items: [
        { title: "Cadrage validé" },
        { title: "Reconnaissance autorisée" },
        { title: "Validation prudente" },
        { title: "Preuve minimale" },
        { title: "Note horodatée" },
        { title: "Arrêt si risque ou instabilité" },
        { title: "Restitution et nettoyage" },
      ],
    }),
    text("La preuve minimale est un principe central. Tu montres juste assez pour prouver le constat, pas davantage. Si un défaut d’autorisation peut être démontré avec deux comptes de test et une réponse HTTP cohérente, tu ne cherches pas à extraire toute la base client. Si un service devient instable, tu n’insistes pas pour « rentabiliser la fenêtre ». Tu informes le contact prévu, tu notes l’heure et tu aides à revenir à un état sûr."),
    code([
      "# prérequis",
      "node --version",
      "# exemple de sortie (valeurs fictives)",
      "# v26.7.0",
      "",
      "# relire un journal de mission fictif",
      "node -e \"const entries=[{at:'2026-03-10T10:40:00Z',phase:'validation',action:'nouvelle tentative après instabilité'},{at:'2026-03-10T09:00:00Z',phase:'cadrage',action:'lecture de la RoE'},{at:'2026-03-10T09:50:00Z',phase:'validation',action:'preuve minimale login'},{at:'2026-03-10T18:05:00Z',phase:'notes',action:'mise à jour hors fenêtre'},{at:'2026-03-10T10:35:00Z',phase:'validation',action:'service instable'},{at:'2026-03-10T09:20:00Z',phase:'reconnaissance',action:'contrôle DNS autorisé'}].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)); const counts=entries.reduce((m,e)=>(m[e.phase]=(m[e.phase]||0)+1,m),{}); const start=Date.parse(entries[0].at), end=Date.parse(entries[entries.length-1].at); const unstable=Date.parse(entries.find(e=>e.action==='service instable').at); const outside=entries.filter(e=>{const d=new Date(e.at); const mins=d.getUTCHours()*60+d.getUTCMinutes(); return mins<9*60 || mins>18*60;}).length; const afterInstability=entries.filter(e=>Date.parse(e.at)>unstable).length; console.log('phases:', Object.entries(counts).map(([k,v])=>k+'='+v).join(', ')); console.log('durée totale (min):', Math.round((end-start)/60000)); console.log('actions après instabilité:', afterInstability); console.log('actions hors fenêtre:', outside);\"",
      "# exemple de sortie (valeurs fictives)",
      "# phases: cadrage=1, reconnaissance=1, validation=3, notes=1",
      "# durée totale (min): 545",
      "# actions après instabilité: 2",
      "# actions hors fenêtre: 1",
    ].join("\n"), "bash"),
    text("Démonstration guidée : le journal de mission est volontairement désordonné. Le script le trie, compte les actions par phase, calcule la durée totale, puis signale ce qui se passe après l’événement « service instable » et hors fenêtre autorisée. Ici, deux actions arrivent après l’instabilité, et l’une d’elles est aussi hors fenêtre. La bonne lecture n’est pas « la mission a été intense », mais « la discipline s’est dégradée après un signal d’arrêt »."),
    figure({
      kind: "steps",
      title: "Preuve minimale utile",
      numbered: true,
      items: [
        { title: "Constat" },
        { title: "Préconditions" },
        { title: "Action courte et autorisée" },
        { title: "Résultat horodaté" },
        { title: "Arrêt" },
        { title: "Recommandation" },
      ],
    }),
    text("Un bon journal distingue aussi les faits et les commentaires. « 09:50, deux comptes de test, réponse 403 sur la ressource visée » est un fait utile. « Nous aurions pu aller plus loin » n’est pas une preuve. Cette discipline rend la restitution plus solide, protège mieux le client et évite qu’un autre lecteur confonde curiosité technique et nécessité métier."),
    example("Exemple corrigé : Koffi démontre un défaut d’autorisation avec deux comptes de test fournis par le propriétaire, note la précondition, l’heure, la réponse observée et la preuve minimale retenue. Quand le service ralentit ensuite, il arrête, prévient le contact prévu et documente l’arrêt. C’est une meilleure preuve qu’une tentative plus intrusive qui risquerait de dégrader la disponibilité."),
    mistakes("croire qu’une preuve crédible doit forcément aller jusqu’à l’exploitation complète ; continuer après un signe d’instabilité ; mélanger notes personnelles, hypothèses et preuves livrables ; oublier de signaler une action hors fenêtre."),
    safety("Toute validation se fait sur des comptes de test fournis ou autorisés, jamais sur les comptes réels d’un client. Si la disponibilité, l’intégrité métier ou la confidentialité des données paraissent menacées, l’arrêt prévaut sur la curiosité technique. Le journal de mission peut contenir des données sensibles : limite sa diffusion."),
    takeaway("Une méthode responsable vaut par sa traçabilité et sa maîtrise du risque. Tu cadres, tu observes, tu démontres sobrement, tu notes, puis tu t’arrêtes au bon moment. La preuve minimale bien documentée vaut mieux qu’une action spectaculaire."),
    practice("Prépare-toi avec « Projet final : conduire un test d’intrusion sur dossier et rédiger le rapport » : cette leçon t’aide surtout à relire la logique de mission, la discipline de preuve et le moment où il faut s’arrêter, puis tu termines par le quiz de la leçon."),
    reference("nist80115"),
    reference("ncscPentest"),
    reference("nistGlossaryRoE"),
    reference("owaspVulnDisclosure"),
  ],
  quizExtension: {
    improve: [
      "La meilleure preuve est celle qui démontre le problème avec le moins d’impact possible. Une action plus destructrice n’ajoute pas automatiquement de valeur, alors qu’elle augmente le risque pour le service, les données et la mission elle-même.",
      "Quand un service devient instable, l’arrêt et l’alerte du contact prévu passent avant le reste. Continuer plus vite aggrave souvent le problème et transforme une mission défensive en incident provoqué par manque de discipline.",
    ],
    add: [
      questions.choice("Quel élément rend une preuve plus utile dans un rapport ?", ["Qu’elle soit la plus impressionnante possible", "Qu’elle reste ambiguë pour garder du suspense", "Qu’elle soit minimale, horodatée et liée à un constat précis", "Qu’elle évite toute note de contexte"], 2, "Une preuve utile montre le constat, la précondition, l’heure et le résultat observé sans impact inutile. Le piège tentant est de croire qu’une preuve spectaculaire impressionne davantage, alors qu’une preuve minimale et claire aide beaucoup mieux à corriger.", "moyen"),
      questions.multi("Lis cette synthèse : « phases: cadrage=1, reconnaissance=1, validation=3, notes=1 ; actions après instabilité: 2 ; actions hors fenêtre: 1 ». Quelles conclusions sont raisonnables ? (plusieurs réponses)", ["Une partie du travail a continué après un signal d’instabilité", "Une action au moins a dépassé la fenêtre autorisée", "Le service a forcément été compromis", "Le journal de mission aide à détecter un écart de discipline"], [0, 1, 3], "Le résumé prouve une poursuite après l’instabilité et au moins un écart horaire, ce qui suffit à signaler un problème de méthode. En revanche, il ne prouve pas à lui seul une compromission. La tentation classique est de transformer un écart de processus en conclusion technique excessive.", "difficile"),
    ],
  },
};

const ptTypesReferentielsLesson: NewLesson = {
  key: "pt-types-referentiels",
  title: "Types de tests et référentiels : PTES, NIST SP 800-115, WSTG et ATT&CK",
  summary: "Compare les grands types de mission et les référentiels qui servent à cadrer, tester, documenter et relire un test d’intrusion sans les confondre.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer boîte noire, grise et blanche, comparer évaluation de vulnérabilités et test d’intrusion, relier un besoin au bon référentiel, puis expliquer ce que PTES, NIST SP 800-115, WSTG et ATT&CK apportent chacun."),
    prerequisites("avoir compris le cadrage d’une mission et l’idée de preuve minimale pendant un test d’intrusion."),
    scenario("Ama rejoint Baobab Tech pour aider à préparer trois demandes différentes : une revue web, un exercice plus global de mission, et un atelier de défense qui veut parler le langage des techniques adverses sans rejouer une chaîne d’attaque. Pour éviter le flou, elle doit choisir le bon mot et le bon référentiel pour chaque besoin."),
    videoSlot("Choisir le bon type de mission et le bon référentiel"),
    text("Tous les tests de sécurité ne se ressemblent pas. Une évaluation de vulnérabilités cherche surtout à identifier et prioriser des faiblesses possibles, souvent avec beaucoup d’automatisation. Un test d’intrusion va plus loin dans la validation contrôlée, mais dans un périmètre et avec des règles négociées. Une mission en boîte noire part de peu d’informations, une boîte grise reçoit des indices ou des comptes de test, et une boîte blanche s’appuie sur davantage de contexte technique. Une red team reste autre chose : elle est plus proche d’un exercice piloté qu’un débutant ne doit pas confondre avec un simple scan « plus agressif »."),    
    figure({
      kind: "cards",
      title: "Repères simples",
      columns: 2,
      items: [
        { term: "Évaluation de vulnérabilités", text: "identifier et prioriser", tone: "cyan" },
        { term: "Test d’intrusion", text: "valider prudemment", tone: "green" },
        { term: "Boîte noire", text: "peu d’informations initiales", tone: "neutral" },
        { term: "Boîte grise", text: "quelques infos ou comptes", tone: "blue" },
        { term: "Boîte blanche", text: "documentation ou architecture fournies", tone: "violet" },
        { term: "Red team", text: "exercice piloté, plus large", tone: "amber" },
      ],
    }),
    text("Les référentiels servent de cartes, pas de recettes d’attaque. Le site du Penetration Testing Execution Standard (PTES) présente sept sections principales de mission, utiles pour structurer le travail de bout en bout. NIST SP 800-115, Technical Guide to Information Security Testing and Assessment, reste un guide de planification, de techniques et de restitution. Le WSTG d’OWASP sert surtout au test d’applications web. ATT&CK, enfin, décrit un vocabulaire de tactiques et de techniques adverses observables. Dire « ATT&CK est ma méthode de pentest » serait donc trompeur : ATT&CK aide à décrire et relier des comportements, pas à remplacer tout le cadrage de mission."),
    code([
      "# prérequis",
      "node --version",
      "# exemple de sortie (valeurs fictives)",
      "# v26.7.0",
      "",
      "# classer quelques besoins dans des repères connus",
      "node -e \"const rows=[{item:'revue du cadrage',ptes:'Pre-engagement Interactions',nist:'Planning',wstg:'n/a',attack:'n/a'},{item:'test d’authentification web',ptes:'Vulnerability Analysis',nist:'Examination',wstg:'Authentication Testing',attack:'n/a'},{item:'journal de collecte d’identifiants',ptes:'n/a',nist:'n/a',wstg:'n/a',attack:'Credential Access'},{item:'rédaction du rapport',ptes:'Reporting',nist:'Report',wstg:'n/a',attack:'n/a'}]; for (const row of rows) console.log(row.item+' -> PTES='+row.ptes+' | NIST='+row.nist+' | WSTG='+row.wstg+' | ATT&CK='+row.attack);\"",
      "# exemple de sortie (valeurs fictives)",
      "# revue du cadrage -> PTES=Pre-engagement Interactions | NIST=Planning | WSTG=n/a | ATT&CK=n/a",
      "# test d’authentification web -> PTES=Vulnerability Analysis | NIST=Examination | WSTG=Authentication Testing | ATT&CK=n/a",
      "# journal de collecte d’identifiants -> PTES=n/a | NIST=n/a | WSTG=n/a | ATT&CK=Credential Access",
      "# rédaction du rapport -> PTES=Reporting | NIST=Report | WSTG=n/a | ATT&CK=n/a",
    ].join("\n"), "bash"),
    text("Démonstration guidée : le but du script n’est pas de prouver qu’il existe une correspondance parfaite entre les référentiels. Il montre plutôt qu’un besoin de mission, un test web, une observation défensive et un rapport ne se classent pas tous au même endroit. Un test d’authentification web parle bien au WSTG, alors qu’un journal qui montre une collecte d’identifiants parle surtout à ATT&CK. Ce tri évite de surcharger un référentiel avec un rôle qu’il ne remplit pas."),
    figure({
      kind: "cards",
      title: "Quand utiliser quoi ?",
      columns: 2,
      items: [
        { term: "PTES", text: "structurer une mission", tone: "cyan" },
        { term: "NIST SP 800-115", text: "cadrer, conduire, restituer", tone: "blue" },
        { term: "WSTG", text: "tester une application web", tone: "green" },
        { term: "ATT&CK", text: "décrire des tactiques et techniques", tone: "violet" },
      ],
    }),
    text("Reste prudent sur les détails d’édition. Dans cette base, NIST SP 800-115 est confirmé comme publication finale du 30 septembre 2008. Le WSTG renvoie aujourd’hui vers sa version stable v4.2. ATT&CK publie une version courante et rappelle qu’une tactique décrit le « pourquoi » d’une technique, donc il faut revalider les chiffres et libellés avant de les figer. PTES, enfin, reste un repère important, mais sa page officielle manque encore dans les références de ce dépôt : on peut utiliser ses sept sections connues avec prudence, puis signaler la référence manquante dans le message de fin."),
    example("Exemple corrigé : si Ama doit relire un historique de proxy et décider quels tests d’authentification sont pertinents, elle pense d’abord WSTG. Si elle doit expliquer la structure globale de mission au client, elle pense PTES et NIST SP 800-115. Si elle doit relier un comportement observé au vocabulaire d’un centre de défense, elle pense ATT&CK. Aucun de ces repères ne transforme à lui seul une mission en « recette complète »."),
    mistakes("présenter ATT&CK comme une méthode complète de pentest ; dire que le WSTG couvre tous les systèmes non web ; inventer des catégories WSTG qui n’apparaissent pas dans la version stable ; écrire « dernière version » sans revérifier le site source."),
    safety("Un référentiel ne donne jamais une permission d’agir. Même si une technique existe dans ATT&CK ou une étape dans PTES, elle ne devient pas autorisée pour autant. Tu restes dans le périmètre, les règles d’engagement et les preuves minimales prévues."),
    takeaway("Les types de mission disent ce que tu cherches à faire. Les référentiels t’aident à structurer, tester, décrire et restituer. Choisir le bon repère évite les confusions et donne un langage commun au client, au testeur et à la défense."),
    practice("Prépare-toi avec « Projet final : conduire un test d’intrusion sur dossier et rédiger le rapport » : ce laboratoire ne déroule pas chaque référentiel séparément, mais il t’oblige à structurer la mission et le rapport avec des repères cohérents, puis tu termines par le quiz."),
    reference("nist80115"),
    reference("wstgStable"),
    reference("mitreEnterpriseMatrix"),
    reference("mitreTechniques"),
  ],
  quiz: {
    title: "Quiz : types de tests et référentiels",
    questions: [
      questions.choice("Quel référentiel est le plus directement dédié aux tests d’application web ?", ["MITRE ATT&CK Enterprise", "OWASP WSTG", "NIST SP 800-115", "Un programme bug bounty"], 1, "Le WSTG est un guide de tests de sécurité web. NIST SP 800-115 cadre plus largement des tests et évaluations de sécurité, tandis qu’ATT&CK décrit surtout des tactiques et techniques observables. Le piège fréquent est de choisir ATT&CK parce qu’il semble très riche, alors qu’il ne remplace pas un guide de tests web.", "facile"),
      questions.choice("Quelle description correspond le mieux à une mission en boîte grise ?", ["Aucune information n’est fournie au départ", "Toute l’architecture et le code source sont fournis", "Quelques informations ou comptes de test sont fournis", "Le périmètre est volontairement secret jusqu’à la fin"], 2, "La boîte grise donne un peu de contexte, par exemple un compte de test ou une architecture résumée. La réponse la plus tentante est la boîte noire, car elle paraît plus « réaliste », mais elle décrit justement l’absence d’informations initiales.", "moyen"),
      questions.multi("Lis cet objectif : « relire un historique de proxy et vérifier les tests autour de la connexion, de la session et du contrôle d’accès ». Quels repères sont les plus adaptés ? (plusieurs réponses)", ["OWASP WSTG", "NIST SP 800-115", "MITRE ATT&CK Enterprise comme guide principal de tests web", "PTES pour la structure globale de mission"], [0, 1, 3], "Le WSTG parle directement des familles de tests web, NIST aide à cadrer l’approche, et PTES peut structurer la mission. Le faux ami est ATT&CK comme guide principal de tests web : il aide à décrire des comportements adverses, mais pas à remplacer un guide de vérifications applicatives.", "difficile"),
      questions.tf("Une évaluation de vulnérabilités et un test d’intrusion sont des synonymes exacts.", false, "Faux : une évaluation de vulnérabilités identifie et priorise surtout des faiblesses possibles, souvent avec plus d’automatisation. Un test d’intrusion ajoute de la validation contrôlée, du cadrage et des preuves plus contextualisées. La confusion est courante, mais elle fausse la préparation de mission.", "moyen"),
    ],
  },
};

const ptDroitEthiqueLesson: NewLesson = {
  key: "pt-droit-ethique",
  title: "Droit, éthique et divulgation responsable d’une faille",
  summary: "Comprends pourquoi l’autorisation écrite, la minimisation des données et la divulgation coordonnée comptent autant que la technique pendant un test d’intrusion.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer pourquoi un test autorisé reste encadré par le droit et l’éthique, distinguer signalement privé et publication, minimiser les données conservées, puis rédiger une note de divulgation responsable prudente."),
    prerequisites("avoir compris l’autorisation écrite, le périmètre et la logique de preuve minimale dans une mission de test d’intrusion."),
    scenario("Moussa aide la boutique Soleil à préparer un audit autorisé. En relisant une page publique et une note de support, il tombe sur une exposition probable qui mérite d’être signalée, mais il hésite : faut-il publier, envoyer un message privé, conserver toutes les preuves, ou attendre ? Son rôle n’est pas de jouer au justicier, mais d’agir de façon défendable et utile."),
    videoSlot("Droit, éthique et divulgation responsable pendant un pentest"),
    text("Le droit et l’éthique ne sont pas des sujets « autour » du pentest : ils en font partie. Une autorisation écrite n’est pas une formalité administrative, c’est la frontière entre une vérification défensive et une action illégitime. Même quand une faiblesse semble évidente, tu ne décides pas seul d’étendre le périmètre, d’extraire plus de données ou de publier ton résultat. Tu suis le cadre convenu, et tu gardes en tête que la loi dépend aussi du pays, du secteur et du contrat."),
    figure({
      kind: "compare",
      title: "Réflexe défensif en cas de découverte",
      sides: [
        {
          title: "Preuve minimale suffisante",
          tone: "green",
          items: ["signalement privé coordonné", "pas de publication sauvage"],
        },
        {
          title: "Preuve insuffisante",
          tone: "amber",
          items: ["compléter seulement ce qui est autorisé"],
        },
      ],
      verdict: "À partir d’un constat plausible, on complète dans le cadre autorisé puis on signale par un canal privé coordonné.",
    }),
    text("Comme grand repère international, tu peux citer la Convention sur la cybercriminalité, dite Convention de Budapest, ouverte à la signature à Budapest le 23 novembre 2001 : elle aide à comprendre que les États traitent sérieusement les atteintes aux systèmes et organisent leur coopération. Pour un public africain, la Convention de Malabo, officiellement African Union Convention on Cyber Security and Personal Data Protection, reste un repère important sur cybersécurité et données personnelles, mais il faut rester prudent si tu n’as pas relu son statut officiel du moment. Même logique pour le droit national : on ne donne jamais de conseil juridique dans le cours, et on n’invente ni article ni peine locale."),
    text("Le RGPD fournit un bon langage pour parler des données rencontrées pendant une mission : minimisation, besoin d’en connaître, durée de conservation limitée, destinataires définis. En Europe, la directive NIS 2, officiellement Directive (EU) 2022/2555, rappelle aussi que la cybersécurité, la gestion du risque et la notification d’incident s’inscrivent dans une gouvernance plus large. Ici encore, la bonne posture n’est pas de jouer au juriste : tu apprends surtout à reconnaître ce qui doit être cadré, documenté et transmis au bon interlocuteur."),
    figure({
      kind: "steps",
      title: "Ce qu’on garde dans un livrable",
      numbered: true,
      items: [
        { title: "Utile au constat ?", text: "oui ou non" },
        { title: "Identifie une personne ?", text: "oui ou non" },
        { title: "Preuve minimale suffit ?", text: "oui ou non" },
        { title: "En cas de doute", text: "masquer, résumer, ou ne pas garder" },
      ],
    }),
    text("Quand une faille doit être signalée, la divulgation coordonnée reste la bonne voie. Tu cherches d’abord une politique de signalement, un fichier « security.txt » standardisé par la RFC 9116, une équipe sécurité, un CERT ou le contact prévu dans la mission. Tu envoies un message sobre : produit ou service touché, version ou contexte, impact, preuve minimale, conditions de reproduction sûres et coordonnées de suivi. Tu n’envoies ni base de données, ni secret complet, ni formulation agressive. La preuve doit aider à corriger, pas à embarrasser."),
    code([
      "# prérequis",
      "node --version",
      "# exemple de sortie (valeurs fictives)",
      "# v26.7.0",
      "",
      "# calculer une échéance de relance et de purge à partir d’une découverte fictive",
      "node -e \"const discovered=new Date('2026-03-10T09:15:00Z'); const followUpDays=7; const retentionDays=14; const addDays=(d,n)=>new Date(d.getTime()+n*24*60*60*1000); const followUp=addDays(discovered,followUpDays).toISOString().slice(0,10); const purge=addDays(discovered,retentionDays).toISOString().slice(0,10); console.log('relance conseillée:', followUp); console.log('purge convenue:', purge); console.log('ordre des destinataires: contact mission -> équipe sécurité -> CERT si nécessaire');\"",
      "# exemple de sortie (valeurs fictives)",
      "# relance conseillée: 2026-03-17",
      "# purge convenue: 2026-03-24",
      "# ordre des destinataires: contact mission -> équipe sécurité -> CERT si nécessaire",
    ].join("\n"), "bash"),
    text("Démonstration guidée : le script ne simule aucune attaque. Il part d’une date de découverte fictive, calcule une relance et une date de purge convenues, puis rappelle un ordre logique de destinataires quand tu agis dans une mission déjà cadrée. Ce petit exercice montre qu’un bon signalement n’est pas seulement technique : il dépend aussi d’un calendrier, d’un canal de contact et d’une discipline de conservation des preuves."),
    example("Exemple corrigé : Moussa peut écrire « Exposition probable d’une ressource d’administration accessible sans contrôle attendu. Vérification effectuée dans le cadre autorisé, le 2026-03-10, avec preuve minimale conservée. Recommandation : fermer l’accès public, revoir le contrôle d’accès, puis confirmer la correction en re-test. » Il ne publie pas la capture complète si elle contient des données sensibles, et il n’invente pas une règle de droit nationale qu’il n’a pas relue."),
    mistakes("confondre bug bounty et permission générale ; citer une loi locale ou une peine sans source relue ; conserver plus de données qu’il n’en faut ; croire qu’un intérêt public supposé justifie une publication sauvage."),
    safety("Ce cours ne donne pas de conseil juridique. Pour une situation réelle, fais valider le cadre par les personnes compétentes de ton organisation, et par un juriste si nécessaire. Ne contourne jamais un anti-bot ou un accès protégé pour « mieux prouver » une découverte, et ne republie pas de données sensibles."),
    takeaway("L’autorisation écrite, la minimisation des données et la divulgation coordonnée font partie du métier. Une preuve utile aide à corriger, reste proportionnée et suit le bon canal de signalement. Le droit varie selon les pays : quand tu n’es pas sûr, tu formules prudemment et tu fais relire."),
    practice("Travaille dans « TP 1 : lire une lettre de mission et fixer le périmètre » : ce laboratoire t’apprend à relire le cadre de mission, les interdictions et les clarifications nécessaires, mais il ne remplace ni une lecture juridique locale ni une procédure réelle de divulgation. Termine ensuite par le quiz."),
    reference("budapestConvention"),
    reference("auMalabo"),
    reference("eurLexRgpd"),
    reference("nis2Directive"),
    reference("rfc9116"),
    reference("securityTxtSite"),
    reference("owaspVulnDisclosure"),
    reference("certFrContact"),
  ],
  quiz: {
    title: "Quiz : droit, éthique et divulgation",
    questions: [
      questions.choice("Quel énoncé résume le mieux la bonne posture devant une faiblesse probable trouvée pendant une mission ?", ["Publier vite pour éviter qu’elle soit ignorée", "Conserver toutes les données complètes, au cas où", "Suivre le cadre autorisé, garder une preuve minimale et signaler par le bon canal", "Étendre le périmètre si l’impact semble important"], 2, "La bonne posture combine cadre autorisé, preuve minimale et signalement coordonné. La mauvaise réponse la plus tentante est la publication immédiate : elle peut aggraver le risque, exposer des données et sortir du cadre contractuel ou juridique.", "facile"),
      questions.choice("Pourquoi une donnée personnelle publique doit-elle souvent être masquée dans le livrable ?", ["Parce qu’une donnée publique devient forcément fausse", "Parce qu’elle peut ne pas être nécessaire en clair pour prouver le constat", "Parce qu’elle interdit toute mention du constat", "Parce que seule l’équipe juridique peut lire un rapport"], 1, "Une donnée publique n’a pas besoin d’être recopiée en clair si une formulation résumée suffit à démontrer le problème. La tentation fréquente est de tout garder « pour être complet », alors que la minimisation et la proportionnalité protègent mieux le client et le rapport.", "moyen"),
      questions.multi("Lis cette situation : « Awa découvre un panneau d’administration exposé. Le périmètre couvre le domaine, mais pas la publication publique des preuves. » Quelles actions restent défendables ? (plusieurs réponses)", ["Conserver une preuve minimale horodatée", "Chercher un canal de signalement comme security.txt ou le contact de mission", "Publier immédiatement les captures complètes pour faire pression", "Masquer les données sensibles dans la note de signalement"], [0, 1, 3], "Conserver une preuve minimale, utiliser le bon canal et masquer les données sensibles correspondent à une divulgation coordonnée. Publier immédiatement des captures complètes sortirait du cadre et ferait disparaître la prudence attendue d’un test défensif.", "difficile"),
      questions.tf("Une autorisation écrite ne suffit pas à transformer toutes les actions techniquement possibles en actions acceptables.", true, "Vrai : l’autorisation doit encore être lue avec ses limites, son périmètre, ses exclusions et ses conditions d’arrêt. Une action techniquement faisable peut rester interdite, disproportionnée ou juridiquement sensible si elle dépasse ce qui a été convenu.", "moyen"),
    ],
  },
};

const ptContratRoeLesson: NewLesson = {
  key: "pt-contrat-roe",
  title: "Lettre de mission, règles d’engagement et gestion des données",
  summary: "Apprends à relire une lettre de mission et des règles d’engagement pour repérer les manques, les tiers non clarifiés et les clauses qui protègent la mission.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("repérer les champs indispensables d’une lettre de mission, lire des règles d’engagement, calculer une fenêtre de test, détecter un tiers non autorisé, puis reformuler un cadrage incomplet de façon acceptable."),
    prerequisites("avoir compris ce qu’est un périmètre, pourquoi l’autorisation écrite compte et comment une mission s’arrête si la stabilité ou les données sont menacées."),
    scenario("Kwame intervient côté prestataire pour une mission sur « example.org » et « api.example.org ». Le brouillon de cadrage paraît sérieux, mais il manque des détails sur les comptes de test, la protection des preuves et un SaaS tiers utilisé par l’application. Avant la moindre action, il doit relire le document comme un outil de réduction du risque, pas comme une simple formalité."),
    videoSlot("Lire une lettre de mission et des règles d’engagement comme un défenseur"),
    text("Une lettre de mission utile dit qui teste quoi, pourquoi, quand, comment et avec quelles limites. Les règles d’engagement, souvent abrégées en RoE, rendent ce cadrage exploitable au quotidien : quels actifs sont autorisés, quelles actions restent interdites, quels comptes sont fournis, qui prévenir en cas d’instabilité, comment gérer les données et quels tiers sont exclus. Sans ces éléments, même un bon technicien travaille à l’aveugle."),
    figure({
      kind: "table",
      title: "Lecture rapide d’un cadrage",
      columns: ["Champ", "À vérifier"],
      rows: [
        ["objectif", "pourquoi la mission existe"],
        ["périmètre", "quoi tester"],
        ["exclusions", "quoi ne pas toucher"],
        ["fenêtre", "quand agir"],
        ["contacts", "qui prévenir"],
        ["données", "quoi garder et comment"],
        ["tiers", "qui nécessite un accord séparé"],
      ],
      highlight: 1,
    }),
    text("Le cadrage n’est pas complet si un environnement n’est pas nommé clairement. Un domaine sans indication d’environnement peut cacher de la production, de la préproduction ou un SaaS tiers. De même, des comptes de test « à fournir plus tard » ne sont pas un détail : sans eux, certaines vérifications deviennent impossibles ou risquées. Enfin, la gestion des données doit être écrite. Une preuve minimale mal protégée peut devenir un incident à elle seule."),
    figure({
      kind: "steps",
      title: "Donnée de mission",
      numbered: true,
      items: [
        { title: "Collecte minimale" },
        { title: "Chiffrée" },
        { title: "Destinataires définis" },
        { title: "Durée convenue" },
        { title: "Suppression en fin de mission" },
      ],
    }),
    text("Les tiers méritent une attention spéciale. Un fournisseur d’authentification, un CDN, une passerelle de paiement ou un outil de ticketing intégré à l’application ne deviennent pas testables parce qu’ils apparaissent dans une capture ou un en-tête. Le document doit dire si le client a le droit de les faire tester, et dans quelles limites. Sinon, la seule décision saine est « à clarifier »."),
    code([
      "# prérequis",
      "node --version",
      "# exemple de sortie (valeurs fictives)",
      "# v26.7.0",
      "",
      "# vérifier un brouillon de RoE fictif",
      "node -e \"const draft={scope:['example.org','api.example.org'], exclusions:['cdn.example.net'], contacts:['contact-technique'], start:'2026-03-10T08:00:00Z', end:'2026-03-10T18:00:00Z', accountsProvided:false, dataRetentionDays:14, evidenceEncryptionDefined:false, thirdPartyAuth:'sso.partner.example'}; const required=['scope','contacts','start','end','dataRetentionDays']; const missing=required.filter((key)=>!(key in draft)); const hours=(Date.parse(draft.end)-Date.parse(draft.start))/3600000; const needsClarification=[]; if(!draft.accountsProvided) needsClarification.push('comptes de test'); if(!draft.evidenceEncryptionDefined) needsClarification.push('protection des preuves'); if(draft.thirdPartyAuth) needsClarification.push('tiers d’authentification'); console.log('champs manquants:', missing.length ? missing.join(', ') : 'aucun'); console.log('fenêtre de test (heures):', hours); console.log('à clarifier:', needsClarification.join(', '));\"",
      "# exemple de sortie (valeurs fictives)",
      "# champs manquants: aucun",
      "# fenêtre de test (heures): 10",
      "# à clarifier: comptes de test, protection des preuves, tiers d’authentification",
    ].join("\n"), "bash"),
    text("Démonstration guidée : le script relit un brouillon fictif et vérifie trois choses simples. D’abord, il confirme que les champs essentiels existent. Ensuite, il calcule la durée de la fenêtre de test. Enfin, il signale trois points qui empêchent une exécution propre : l’absence de comptes de test fournis, l’absence de protection explicite des preuves et la présence d’un tiers d’authentification sans validation écrite. C’est exactement le type de lecture que tu dois faire avant d’ouvrir un proxy ou un scanner."),
    example("Exemple corrigé : une clause acceptable peut dire « Périmètre : example.org et api.example.org ; exclusions : tout fournisseur tiers non listé ; fenêtre : de 8 h à 18 h UTC ; comptes de test : fournis par le client avant le début ; données collectées : preuve minimale, chiffrée, supprimée après la période convenue ». Cette formulation reste sobre, opérationnelle et défendable. Un simple « tester le site » serait au contraire trop vague."),
    mistakes("oublier de préciser l’environnement testé ; traiter les comptes de test comme un détail ; ne rien écrire sur la rétention et le chiffrement des preuves ; supposer qu’un tiers apparent est testable sans confirmation écrite."),
    safety("Le cadrage d’une mission n’est pas un avis juridique valable tel quel pour tous les pays. Utilise-le comme outil de réduction du risque et fais relire les points contractuels sensibles par les personnes compétentes. Sans clause claire sur un tiers ou sur la gestion des données, tu n’improvises pas."),
    takeaway("Une bonne lettre de mission réduit les surprises. Elle précise le périmètre, les exclusions, les comptes, les contacts, les données et les tiers. Si un de ces points reste flou, la bonne décision n’est pas de « deviner », mais de clarifier avant toute action."),
    practice("Travaille dans « TP 1 : lire une lettre de mission et fixer le périmètre » : tu y reliras un cadrage, des règles d’engagement et des actions proposées pour décider ce qui est autorisé, interdit ou à clarifier, puis tu termines par le quiz."),
    reference("nistGlossaryRoE"),
    reference("nist80115"),
    reference("ncscPentest"),
    reference("eurLexRgpd"),
    reference("msrcPentestRules"),
  ],
  quiz: {
    title: "Quiz : lettre de mission et RoE",
    questions: [
      questions.choice("Quel élément manque le plus gravement dans une mission qui prévoit des tests authentifiés ?", ["La couleur du logo du client", "Les comptes de test et leurs droits", "Le nombre de captures d’écran attendues", "Le type de police utilisé dans le rapport"], 1, "Sans comptes de test ni droits définis, certaines vérifications deviennent impossibles ou poussent au bricolage dangereux. La réponse la plus tentante est le volume de preuves attendu, mais la mission ne peut même pas démarrer proprement si l’accès prévu n’existe pas.", "facile"),
      questions.choice("Pourquoi un fournisseur SSO tiers vu dans le parcours d’authentification doit-il souvent être classé « à clarifier » ?", ["Parce qu’un tiers est forcément vulnérable", "Parce qu’il peut relever d’un autre propriétaire et d’autres règles d’autorisation", "Parce qu’il ne peut jamais être critique", "Parce qu’il remplace le besoin de comptes de test"], 1, "Un tiers peut appartenir à un autre propriétaire et être soumis à des règles séparées. La mauvaise réponse la plus tentante est de croire qu’un composant visible dans le parcours applicatif devient automatiquement testable, alors que la responsabilité contractuelle peut être différente.", "moyen"),
      questions.multi("Lis cet extrait : « périmètre : example.org, api.example.org ; exclusions : tout prestataire tiers ; fenêtre : 08:00 à 18:00 UTC ; comptes : à fournir plus tard ; rétention : 14 jours ». Quelles remarques sont justes ? (plusieurs réponses)", ["La fenêtre de test dure 10 heures", "L’absence de comptes de test fournis reste un point bloquant ou au moins à clarifier", "La présence d’une rétention écrite rend inutile toute règle de chiffrement", "Un tiers d’authentification visible dans le flux resterait à clarifier"], [0, 1, 3], "La fenêtre fait bien dix heures, les comptes non fournis doivent être clarifiés, et un tiers visible dans le flux ne devient pas autorisé par magie. La fausse bonne réponse est de croire que la rétention suffit : la durée de conservation n’efface pas les besoins de chiffrement et de destinataires définis.", "difficile"),
      questions.tf("Une règle d’engagement peut être techniquement détaillée tout en restant insuffisante si elle ne dit rien sur les données collectées.", true, "Vrai : le cadrage n’est pas complet si la mission sait quoi tester mais pas quoi conserver, à qui transmettre les preuves, combien de temps les garder ni comment les protéger. La technique seule ne remplace pas la gouvernance des données.", "moyen"),
    ],
  },
};

const ptLaboPersonnelLesson: NewLesson = {
  key: "pt-labo-personnel",
  title: "Monter un laboratoire personnel légal avec peu de moyens",
  summary: "Choisis un laboratoire personnel réaliste, gratuit ou léger, pour t’entraîner légalement sans promettre à tort qu’un seul outil suffit à tout faire.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("comparer WSL, machine virtuelle et plateformes d’entraînement légales, estimer un montage réaliste sur un poste modeste, expliquer les limites de chaque solution, puis choisir un laboratoire personnel proportionné et isolé."),
    prerequisites("aucun, sauf l’idée simple qu’un test d’intrusion se pratique uniquement sur son propre matériel, un laboratoire isolé ou une plateforme d’entraînement légale."),
    scenario("Awa veut apprendre chez elle avec peu de moyens. Son ordinateur Windows est modeste, sa connexion n’est pas toujours stable et elle n’a pas envie de casser son poste principal. Elle doit donc choisir un montage réaliste : parfois WSL pour lire des fichiers et lancer de petits scripts, parfois une seule machine virtuelle locale, parfois une plateforme en ligne déjà prévue pour l’entraînement légal."),
    videoSlot("Monter un laboratoire personnel légal et raisonnable"),
    text("Un laboratoire personnel n’a pas besoin d’être spectaculaire pour être utile. Il doit surtout être légal, isolé et adapté à ton matériel. Si tu débutes, la première bonne décision est de séparer ce qui sert à lire et analyser des fichiers de ce qui sert à héberger une cible d’entraînement. Tu peux apprendre beaucoup avec un simple terminal, des exports fournis, des captures de sortie et quelques applications volontairement vulnérables lancées chez toi."),
    figure({
      kind: "compare",
      title: "Trois familles de laboratoire",
      sides: [
        {
          title: "WSL ou terminal léger",
          tone: "blue",
          items: ["lire, trier, calculer, tester des scripts"],
        },
        {
          title: "VM locale isolée",
          tone: "green",
          items: ["héberger une cible volontairement vulnérable"],
        },
        {
          title: "Plateforme légale en ligne",
          tone: "violet",
          items: ["s’entraîner sans gérer l’infrastructure"],
        },
      ],
    }),
    text("Windows Subsystem for Linux (WSL) permet d’exécuter un environnement GNU/Linux directement sur Windows ; dans cette leçon, il sert surtout à travailler en ligne de commande, lire des fichiers, manipuler des exports et exécuter de petits outils défensifs. Pour héberger une cible volontairement vulnérable comme OWASP Juice Shop ou WebGoat, une machine virtuelle ou une plateforme d’entraînement dédiée reste plus simple à utiliser. Hyper-V, quand il est disponible, fait partie des options documentées. L’important est de commencer petit : une seule cible à la fois vaut mieux qu’un empilement impossible à maintenir."),
    text("Sur téléphone Android, un terminal comme Termux peut aider à lire des fichiers, lancer quelques commandes locales et réviser des notions. Dans ce parcours, on ne le présente pas comme un laboratoire complet : si tu n’as qu’un téléphone, privilégie les parties lecture, tri et raisonnement, puis complète avec une plateforme d’entraînement légale quand la connexion le permet."),
    figure({
      kind: "steps",
      title: "Règles d’or du labo personnel",
      numbered: true,
      items: [
        { title: "Sur son propre matériel" },
        { title: "Cible volontairement vulnérable" },
        { title: "Réseau isolé si possible" },
        { title: "Instantané avant essais" },
        { title: "Jamais de scan d’un réseau tiers" },
      ],
    }),
    text("Les plateformes d’entraînement légales comblent souvent les limites matérielles. PortSwigger Web Security Academy permet de s’entraîner au web sans monter toute l’infrastructure. OWASP Juice Shop et Metasploitable 3 sont pensés pour un labo local isolé. L’idée n’est pas de collectionner les marques : c’est de choisir un support adapté à l’exercice. Si tu apprends à lire une preuve web, la Web Security Academy peut suffire. Si tu veux pratiquer une installation locale, une seule cible vulnérable dans une VM isolée est déjà très formatrice."),
    code([
      "# prérequis",
      "node --version",
      "# exemple de sortie (valeurs fictives)",
      "# v26.7.0",
      "",
      "# estimer un montage de laboratoire fictif",
      "node -e \"const profiles=[{name:'portable_modeste', ramGb:8, storageGb:80, wantsVm:true, wantsTwoTargets:false},{name:'pc_confortable', ramGb:16, storageGb:200, wantsVm:true, wantsTwoTargets:true},{name:'telephone_seul', ramGb:4, storageGb:32, wantsVm:false, wantsTwoTargets:false}]; const decide=(p)=>{ if(!p.wantsVm) return 'terminal léger ou plateforme légale'; if(p.ramGb < 12 || p.storageGb < 120) return 'une seule VM ou un seul conteneur à la fois'; return p.wantsTwoTargets ? 'deux cibles possibles si le poste reste stable' : 'une VM confortable'; }; for (const p of profiles) console.log(p.name+': '+decide(p));\"",
      "# exemple de sortie (valeurs fictives)",
      "# portable_modeste: une seule VM ou un seul conteneur à la fois",
      "# pc_confortable: deux cibles possibles si le poste reste stable",
      "# telephone_seul: terminal léger ou plateforme légale",
    ].join("\n"), "bash"),
    text("Démonstration guidée : le script ne prétend pas donner une configuration officielle. Il montre seulement une logique prudente : peu de RAM ou peu de stockage poussent vers une seule cible à la fois, alors qu’un téléphone seul oriente plutôt vers la lecture d’exports et les plateformes légales. L’intérêt pédagogique est de t’empêcher de surcharger ton matériel dès le départ."),
    example("Exemple corrigé : pour un poste Windows récent mais modeste, Awa peut choisir WSL pour les exercices sur fichiers, puis une seule VM locale isolée pour Juice Shop avec un instantané avant les essais. Pour un vieux portable, mieux vaut rester sur des exports, des scripts Node.js simples et une plateforme légale en ligne. Pour un téléphone seul, la bonne stratégie est d’apprendre d’abord les notions, les journaux et les preuves, puis de compléter plus tard sur une machine plus adaptée."),
    mistakes("croire qu’un simple environnement en ligne de commande suffit à lui seul pour tous les exercices du labo ; vouloir installer plusieurs cibles d’un coup ; scanner un réseau tiers « pour essayer » ; inventer des minima matériels précis sans source relue."),
    safety("Tu n’entraînes jamais tes outils sur un réseau qui n’est pas le tien. Garde tes essais sur ton propre matériel, dans une machine virtuelle, un conteneur ou une plateforme explicitement prévue pour l’apprentissage. Avant une manipulation risquée dans un laboratoire local, prends un instantané si ton outil le permet."),
    takeaway("Un bon laboratoire personnel est simple, légal et proportionné. WSL aide à lire et calculer, une VM isolée ou une plateforme légale servent à héberger ou pratiquer les cibles d’entraînement selon l’exercice. Commencer petit est un choix professionnel, pas une faiblesse."),
    practice("Travaille dans « TP 1 : lire une lettre de mission et fixer le périmètre » : ce laboratoire ne demande aucune machine et t’apprend le cadre. Monter ton laboratoire personnel est un exercice à faire chez toi, hors plateforme, puis tu termines par le quiz."),
    reference("hyperVOverview"),
    reference("wslOverview"),
    reference("termuxHome"),
    reference("portSwiggerAcademy"),
    reference("owaspJuiceShop"),
    reference("owaspWebGoat"),
    reference("metasploitable3"),
  ],
  quiz: {
    title: "Quiz : laboratoire personnel légal",
    questions: [
      questions.choice("Quel choix décrit le mieux un laboratoire personnel responsable pour débuter ?", ["Scanner un réseau voisin pour voir si tout fonctionne", "Commencer avec un environnement isolé, petit et adapté à son matériel", "Installer le plus d’outils possibles dès le premier jour", "Tester directement un service réel si sa page d’accueil est publique"], 1, "Un laboratoire responsable est isolé, légal et proportionné à ton matériel. La mauvaise réponse la plus tentante est d’installer trop de choses d’un coup, alors que la surcharge technique brouille l’apprentissage et augmente le risque d’erreur.", "facile"),
      questions.choice("Quelle limite faut-il garder en tête avec WSL dans ce parcours ?", ["WSL interdit totalement l’usage de Node.js", "WSL remplace automatiquement toute la virtualisation réseau", "WSL est pratique pour la ligne de commande et les fichiers, mais ce parcours s’appuie aussi sur des VM ou des plateformes dédiées selon l’exercice", "WSL n’est utile que sur téléphone Android"], 2, "WSL est très utile pour la ligne de commande, les scripts et la lecture d’exports, mais ce parcours utilise aussi des VM ou des plateformes dédiées quand il faut héberger ou pratiquer sur une cible d’entraînement. La confusion la plus fréquente est de lui demander plus que le rôle qu’on lui donne ici.", "moyen"),
      questions.multi("Parmi ces choix, lesquels restent cohérents avec la règle d’un laboratoire légal et peu coûteux ? (plusieurs réponses)", ["Utiliser une plateforme d’entraînement légale quand on n’a pas assez de matériel", "Prendre un instantané avant des essais risqués sur sa VM", "Scanner Internet « juste pour apprendre Nmap »", "Lancer une seule cible volontairement vulnérable à la fois sur un poste modeste"], [0, 1, 3], "Une plateforme légale, un instantané et une cible unique sur un poste modeste sont des décisions prudentes et réalistes. Scanner Internet pour apprendre sort du cadre légal et défensif rappelé partout dans le parcours.", "difficile"),
      questions.tf("Un téléphone seul peut servir à apprendre certaines notions, mais il ne faut pas le présenter comme un remplacement honnête d’un laboratoire complet avec virtualisation.", true, "Vrai : un téléphone peut suffire pour lire, trier et réviser, surtout avec un terminal léger, mais il ne remplace pas honnêtement un laboratoire complet ni une machine virtuelle capable d’héberger des cibles d’entraînement locales.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c5:1",
    position: 1,
    existing: { fromTitle: "Cadre et méthode" },
    title: "Cadre et méthode d’un test d’intrusion",
    description: "Ce module pose les bases d’un test d’intrusion défensif : savoir ce qui est autorisé, comment travailler proprement, et quels repères méthodologiques servent vraiment. Critères de réussite : lire un périmètre et ses exclusions ; expliquer une méthode de preuve minimale et d’arrêt propre ; choisir le bon type de mission et le bon référentiel pour structurer le travail.",
    lessons: [pentestCadreLesson, pentestMethodeLesson, ptTypesReferentielsLesson],
  },
  {
    key: "c5:3",
    position: 2,
    title: "Droit, éthique et préparation",
    description: "Ce module montre qu’un test d’intrusion utile dépend autant du cadre humain et juridique que de la technique. Critères de réussite : expliquer une divulgation responsable et proportionnée ; relire une lettre de mission et des règles d’engagement en repérant les manques ; choisir un laboratoire personnel légal, simple et adapté à ses moyens.",
    lessons: [ptDroitEthiqueLesson, ptContratRoeLesson, ptLaboPersonnelLesson],
  },
];
