import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const ptReseauInterneLesson: NewLesson = {
  key: "pt-reseau-interne",
  title: "Tester un réseau interne : segmentation, filtrage et services exposés",
  summary: "Tu apprends à lire un réseau interne comme un dispositif de défense : segments, flux d’administration, services hérités et écarts entre ce qui devrait être joignable et ce qui l’est vraiment.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("lire une segmentation simple, repérer des flux internes surprenants, distinguer un service utile d’une exposition excessive, puis formuler une preuve minimale et une correction défensive."),
    prerequisites("avoir compris la lecture d’un scan réseau, les états Nmap courants et le rôle des services internes comme SMB, LDAP, WinRM, Kerberos, RDP ou RPC."),
    scenario("Moussa reçoit les résultats d’un test interne autorisé pour Baobab Tech. Le scan a déjà été réalisé dans le cadre convenu, avec un mémo de segmentation attendu. Son rôle n’est pas de « bouger partout », mais d’expliquer pourquoi certains flux sont normaux, pourquoi d’autres surprennent, et quelle correction proposer sans inventer une compromission."),
    videoSlot("Lire un réseau interne comme un problème de segmentation"),
    text("Un test réseau interne n’est pas un terrain libre. Il sert à vérifier si la segmentation, les ACL et les pare-feu internes tiennent la route une fois à l’intérieur. L’idée centrale est défensive : quels segments devraient communiquer, pour quels usages, et qu’est-ce qui paraît trop ouvert ? Un service interne n’est pas inquiétant parce qu’il existe, mais parce qu’il est accessible depuis un endroit où il ne devrait pas l’être."),
    schema([
      "Question de base sur un réseau interne",
      "",
      "segment source -> flux attendu ? -> service observé",
      "      |                 |                |",
      "      |                 |                |",
      "   poste user      oui / non       admin / partage / BD",
      "   invité          oui / non       web / LDAP / SMB / RDP",
      "   serveur         oui / non       WinRM / RPC / impression",
      "",
      "Le risque vient de l’écart entre attendu et observé",
    ].join("\n")),
    text("La segmentation sépare par exemple les postes utilisateurs, les serveurs, les invités, les zones d’administration et parfois l’OT. Les protocoles courants te donnent des indices : SMB pour le partage, LDAP et Kerberos pour l’annuaire, WinRM et RDP pour l’administration Windows, RPC pour de nombreux services, SSH pour Linux et équipements réseau. Leur simple présence n’est pas une faille. Ce qui compte est la provenance : voir WinRM et RDP depuis un VLAN utilisateurs vers un serveur sensible est rarement anodin."),
    schema([
      "Observation -> lecture défensive",
      "",
      "SMB poste -> serveur fichiers     : souvent normal",
      "LDAP poste -> contrôleur de domaine : selon besoin",
      "RDP user -> serveur critique      : à justifier",
      "WinRM user -> serveur critique    : souvent excessif",
      "BD exposée à plusieurs segments  : priorité élevée",
      "",
      "On décrit un écart, pas une attaque réussie",
    ].join("\n")),
    text("Côté Active Directory, garde une focale de surface d’exposition. Tu peux décrire qu’un contrôleur de domaine répond à LDAP, Kerberos, SMB ou RPC depuis trop de segments, qu’un compte de service apparaît là où il ne devrait pas, ou qu’un bastion d’administration manque. Tu n’enseignes pas ici l’élévation de privilèges. Tu apprends à écrire : « tel segment atteint tel service sensible, alors que la politique annoncée disait l’inverse »."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script ci-dessous lit des observations réseau fictives et une politique de segmentation simplifiée. Il compte les couples « segment vers service » inattendus et signale les expositions d’administration à forte priorité. Tout est local et inventé : tu t’entraînes à raisonner sur des flux, pas à scanner un tiers."),
    code([
      "# fichier demo-reseau-interne.cjs",
      "const policy = {",
      "  users: ['https', 'dns', 'smb-files'],",
      "  admin: ['rdp', 'winrm', 'ssh', 'ldap', 'kerberos'],",
      "  servers: ['https', 'smb-files', 'sql'],",
      "};",
      "const observations = [",
      "  { from: 'users', host: 'srv-fichiers', service: 'smb-files' },",
      "  { from: 'users', host: 'srv-rh', service: 'rdp' },",
      "  { from: 'users', host: 'dc01', service: 'winrm' },",
      "  { from: 'admin', host: 'dc01', service: 'kerberos' },",
      "  { from: 'servers', host: 'db01', service: 'sql' },",
      "  { from: 'users', host: 'db01', service: 'sql' },",
      "];",
      "const rows = observations.map((item) => ({",
      "  ...item,",
      "  allowed: policy[item.from].includes(item.service),",
      "}));",
      "const unexpected = rows.filter((item) => !item.allowed);",
      "const critical = unexpected.filter((item) => ['rdp', 'winrm', 'sql'].includes(item.service));",
      "console.log(JSON.stringify({",
      "  total: rows.length,",
      "  unexpected: unexpected.length,",
      "  critical: critical.map((item) => `${item.from}->${item.host}:${item.service}`),",
      "}, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"total\": 6,",
      "//   \"unexpected\": 3,",
      "//   \"critical\": [",
      "//     \"users->srv-rh:rdp\",",
      "//     \"users->dc01:winrm\",",
      "//     \"users->db01:sql\"",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : Ama peut écrire que le segment « users » atteint à tort « srv-rh » en RDP, « dc01 » en WinRM et « db01 » en SQL. Ce constat ne prouve pas une compromission, mais il suffit déjà à montrer une segmentation trop permissive. La recommandation utile n’est pas « sécuriser le réseau », mais « réserver RDP et WinRM au segment d’administration, et limiter SQL aux flux serveurs justifiés »."),
    mistakes("confondre réseau interne et droit de tout tester ; conclure à une faille critique sans comparer avec la politique attendue ; oublier les flux d’administration légitimes ; décrire un contrôleur de domaine comme compromis alors qu’on n’a observé qu’une exposition réseau."),
    safety("même en interne, tu restes dans le périmètre autorisé, la fenêtre prévue et la preuve minimale. Si un segment, un site distant ou un équipement industriel n’étaient pas couverts, tu ne « profites » pas du rebond réseau pour les inclure. Tu décris les écarts observés, sans tutoriel de mouvement latéral."),
    takeaway("un bon test interne lit d’abord la segmentation. Le vrai signal vient des flux surprenants : qui atteint quoi, depuis où, et pour quelle raison défendable ou non. Décrire cet écart vaut déjà une preuve utile."),
    practice("Travaille dans « TP 3 : lire les résultats d’un scan réseau » : tu y liras des sorties déjà produites pour compter les services, repérer les expositions inattendues et relier un port ouvert à une erreur de segmentation, puis tu termines par le quiz."),
    reference("nmapOutputFormats"),
    reference("nmapVersionDetection"),
    reference("msAdBestPractices"),
    reference("anssiActiveDirectory"),
    reference("ncscPentest"),
  ],
  quiz: {
    title: "Quiz : réseau interne et segmentation",
    questions: [
      questions.choice("Dans un test interne défensif, quelle question vient avant la chasse au « port intéressant » ?", ["Quel service est accessible depuis quel segment, et est-ce attendu ?", "Quel exploit utiliser d’abord sur le contrôleur de domaine", "Comment contourner l’ACL sans être vu", "Quel mot de passe par défaut essayer"], 0, "La lecture d’un réseau interne commence par l’écart entre la politique attendue et l’observation. La mauvaise réponse la plus tentante est de sauter directement au service sensible, alors qu’un port n’a de sens qu’en fonction du segment qui l’atteint.", "facile"),
      questions.choice("Pourquoi voir WinRM depuis un VLAN utilisateurs vers un serveur sensible mérite-t-il souvent une forte priorité ?", ["Parce que WinRM est interdit partout par définition", "Parce qu’un flux d’administration exposé trop largement augmente la surface de mouvement interne", "Parce qu’un serveur Windows ne doit jamais répondre au réseau", "Parce que WinRM remplace toujours Kerberos"], 1, "WinRM est un protocole d’administration légitime, mais son exposition depuis trop de segments affaiblit la séparation des rôles. La réponse tentante est l’interdiction absolue, alors que le vrai problème est l’ouverture depuis le mauvais endroit.", "moyen"),
      questions.multi("Lis cet extrait : « users -> srv-rh:rdp ; users -> dc01:winrm ; admin -> dc01:kerberos ». Quelles affirmations sont raisonnables ? (plusieurs réponses)", ["Le flux « admin -> dc01:kerberos » peut être cohérent avec une zone d’administration", "Les deux flux depuis « users » méritent une justification ou une réduction", "L’extrait prouve qu’un administrateur a été compromis", "La segmentation semble plus permissive que prévu pour des services sensibles"], [0, 1, 3], "L’extrait suffit à relever deux expositions d’administration depuis un segment utilisateurs et un flux potentiellement normal depuis le segment admin. En revanche, il ne prouve aucune compromission. Le piège est de transformer une exposition réseau en incident déjà réalisé.", "difficile"),
      questions.tf("Dans un rapport de test interne, écrire « le réseau est trop plat » sans nommer le segment source, le service et l’actif touché serait trop vague pour être utile.", true, "Vrai : un constat utile doit préciser qui atteint quoi et depuis où. Sans cela, la correction devient floue et la preuve difficile à relire. La formule générale peut aider à discuter, mais elle ne remplace pas l’observation concrète.", "moyen"),
    ],
  },
};

const ptWifiAuditLesson: NewLesson = {
  key: "pt-wifi-audit",
  title: "Auditer le Wi-Fi de son propre réseau",
  summary: "Tu apprends à inventorier un Wi-Fi autorisé, à relire ses réglages défensifs et à proposer des corrections utiles sans tomber dans les recettes de capture, de cassage ou de contournement.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer WPA2, WPA3 et WPS, inventorier des points d’accès, repérer des réglages défensifs faibles, puis proposer une amélioration utile pour son propre réseau."),
    prerequisites("connaître la notion de réseau local, savoir ce qu’est un point d’accès et avoir compris qu’un audit actif ne se fait que sur son propre matériel ou avec une autorisation écrite."),
    scenario("Fatou aide la boutique Soleil à relire son Wi-Fi invité et son Wi-Fi interne. Elle ne veut ni capturer le trafic des autres, ni lancer un test agressif. Son objectif est plus simple et plus utile : dresser l’inventaire des points d’accès autorisés, vérifier le mode de sécurité, l’isolation invité, WPS et les mots de passe faibles, puis proposer une remise au propre défendable."),
    videoSlot("Auditer un Wi-Fi autorisé sans recette offensive"),
    text("Dans ce parcours, l’audit Wi-Fi reste strictement défensif. Tu peux expliquer les notions de WPA2, WPA3, WPS, SSID invité, isolation client et inventaire des points d’accès. Tu peux lire la configuration de ton propre réseau ou d’un réseau couvert par un accord clair. En revanche, tu n’apprends pas ici à capturer une poignée de main, désauthentifier des clients, casser un mot de passe ni contourner un portail. Le but est de corriger, pas de rejouer une attaque contre un tiers."),
    schema([
      "Ce qu’un audit Wi-Fi défensif regarde",
      "",
      "SSID -> mode WPA2/WPA3",
      "     -> WPS actif ou non",
      "     -> isolement invité",
      "     -> inventaire des bornes",
      "     -> mot de passe robuste",
      "     -> mise à jour du matériel",
      "",
      "Pas de capture, pas de deauth, pas de cassage",
    ].join("\n")),
    text("WPA3 est aujourd’hui le repère le plus solide pour un réseau personnel ou PME quand le matériel le supporte. WPA2 reste encore très courant, mais demande une hygiène plus stricte sur le mot de passe et les réglages. WPS facilite l’association d’un appareil sur certains routeurs, mais il vaut mieux le désactiver quand il n’est pas nécessaire. L’isolation invité réduit en plus les échanges non nécessaires avec le réseau interne et mérite donc une vérification explicite."),
    schema([
      "Lecture défensive rapide",
      "",
      "WPA3 + invités isolés + WPS off   : bon point",
      "WPA2 + mot de passe fort          : acceptable",
      "WPA2 + WPS actif                  : à corriger",
      "invité sans isolation             : à corriger",
      "borne inconnue ou perso           : à clarifier",
      "",
      "Le contexte compte autant que le mode radio",
    ].join("\n")),
    text("Sur Windows, la commande « netsh wlan » aide à inventorier ton propre poste et les profils sans rien casser. Sur un point d’accès, tu peux aussi relire l’interface d’administration, la version logicielle, le canal utilisé et la liste des SSID publiés. Le signal utile n’est pas « un Wi-Fi existe », mais « ce Wi-Fi protège-t-il correctement les usages et sépare-t-il bien les invités des systèmes plus sensibles ? »."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant lit un inventaire Wi-Fi fictif et produit une liste d’actions défensives. Il ne parle ni de capture ni d’attaque. Il classe seulement les réglages d’un réseau autorisé : mode de sécurité, WPS, isolation invité et mot de passe trop faible à remplacer."),
    code([
      "# fichier demo-wifi-audit.cjs",
      "const networks = [",
      "  { ssid: 'Soleil-Interne', mode: 'WPA3', wps: false, guestIsolation: true, weakPassphrase: false },",
      "  { ssid: 'Soleil-Invite', mode: 'WPA2', wps: true, guestIsolation: false, weakPassphrase: false },",
      "  { ssid: 'AP-perso-boutique', mode: 'WPA2', wps: false, guestIsolation: false, weakPassphrase: true },",
      "];",
      "const actions = [];",
      "for (const item of networks) {",
      "  if (item.wps) actions.push(`${item.ssid}: desactiver WPS`);",
      "  if (!item.guestIsolation) actions.push(`${item.ssid}: isoler les clients invites`);",
      "  if (item.weakPassphrase) actions.push(`${item.ssid}: changer le mot de passe Wi-Fi`);",
      "  if (item.mode !== 'WPA3') actions.push(`${item.ssid}: verifier la compatibilite WPA3`);",
      "}",
      "console.log(JSON.stringify({ total: networks.length, actions }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"total\": 3,",
      "//   \"actions\": [",
      "//     \"Soleil-Invite: desactiver WPS\",",
      "//     \"Soleil-Invite: isoler les clients invites\",",
      "//     \"Soleil-Invite: verifier la compatibilite WPA3\",",
      "//     \"AP-perso-boutique: isoler les clients invites\",",
      "//     \"AP-perso-boutique: changer le mot de passe Wi-Fi\",",
      "//     \"AP-perso-boutique: verifier la compatibilite WPA3\"",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si le Wi-Fi invité de la boutique Soleil reste en WPA2 avec WPS actif et sans isolation client, Fatou n’a pas besoin d’aller plus loin pour formuler un constat utile. Elle peut recommander de couper WPS, d’isoler les invités et d’étudier WPA3 si le matériel le permet. Si un point d’accès personnel apparaît en plus dans l’inventaire, la priorité devient aussi organisationnelle : le faire retirer ou l’intégrer proprement à la gestion du site."),
    mistakes("confondre audit Wi-Fi et démonstration d’attaque ; oublier que le réseau invité doit être séparé ; croire que WPA2 est « cassé par défaut » sans regarder le reste des réglages ; négliger les points d’accès personnels ou oubliés."),
    safety("tu audites ton propre réseau, un laboratoire personnel ou un périmètre couvert par un accord explicite. Tu n’interceptes pas le trafic d’un voisin, tu ne lances pas de désauthentification et tu n’essaies pas de casser un mot de passe. Si tu dois manipuler un point d’accès réel, fais-le dans une plage calme et avec un plan de retour arrière."),
    takeaway("un audit Wi-Fi défensif repose d’abord sur l’inventaire, la séparation des usages et des réglages propres. WPS inutile, isolation absente et point d’accès non géré valent souvent plus qu’une longue liste de théories radio."),
    practice("Prépare-toi avec « Projet final : conduire un test d’intrusion sur dossier et rédiger le rapport » : la plateforme ne rejoue pas un audit Wi-Fi, donc cette leçon se pratique surtout chez toi et avec accord. Le projet final t’aide surtout à savoir comment rapporter proprement ce type de constat, puis tu termines par le quiz."),
    reference("wifiAllianceSecurity"),
    reference("msWindowsWifiSecurity"),
    reference("msWirelessSetupWps"),
    reference("cisaHomeNetworkSecurity"),
    reference("msNetshWlan"),
    reference("anssiWifi"),
    reference("ncscPentest"),
  ],
  quiz: {
    title: "Quiz : audit Wi-Fi défensif",
    questions: [
      questions.choice("Dans ce parcours, qu’est-ce qu’un audit Wi-Fi autorisé doit d’abord produire ?", ["Un inventaire et des recommandations défensives sur son propre réseau", "Une capture de trafic pour vérifier tous les mots de passe", "Une campagne de désauthentification des terminaux", "Un kit de cassage prêt à l’emploi"], 0, "Le premier objectif est de lire et corriger la configuration d’un réseau autorisé : mode WPA, isolation invité, WPS, inventaire des bornes et mot de passe faible. La réponse tentante est la capture, précisément exclue ici pour rester sur une posture défensive et légale.", "facile"),
      questions.choice("Pourquoi WPS actif reste-t-il souvent un mauvais signal dans une petite structure ?", ["Parce qu’il remplace toujours WPA3", "Parce qu’il ajoute une commodité qui augmente parfois inutilement la surface d’exposition", "Parce qu’il coupe l’accès invité par défaut", "Parce qu’il empêche toute mise à jour du point d’accès"], 1, "WPS vise la simplicité d’appairage, mais il devient vite un service de trop quand le besoin a disparu. La mauvaise réponse la plus tentante est de croire qu’il remplace WPA3, alors qu’il s’ajoute surtout comme fonction à réévaluer.", "moyen"),
      questions.multi("Lis cet inventaire : « Soleil-Invite : WPA2, WPS actif, isolation absente ; Soleil-Interne : WPA3, WPS inactif ; AP-perso-boutique : WPA2, isolation absente ». Quelles actions sont raisonnables ? (plusieurs réponses)", ["Couper WPS sur « Soleil-Invite »", "Isoler les clients invités", "Retirer ou gérer proprement « AP-perso-boutique »", "Tester le Wi-Fi du voisin pour comparer"], [0, 1, 2], "L’inventaire montre au moins trois actions utiles : couper WPS sur le réseau invité, rétablir l’isolation et traiter le point d’accès personnel. En revanche, le Wi-Fi du voisin reste hors cadre, même « juste pour comparer ».", "difficile"),
      questions.tf("Dire honnêtement que l’audit Wi-Fi se pratique surtout chez soi ou avec accord, et non sur la plateforme, fait partie du cadrage pédagogique attendu.", true, "Vrai : la leçon doit rappeler que la plateforme ne rejoue pas une attaque radio réelle et que ce sujet se travaille dans un réseau autorisé. Cette honnêteté évite de promettre un laboratoire qui n’existe pas et garde le bon cadre légal.", "moyen"),
    ],
  },
};

const ptIngenierieSocialeLesson: NewLesson = {
  key: "pt-ingenierie-sociale",
  title: "Campagnes d’hameçonnage autorisées : cadre, consentement et indicateurs",
  summary: "Tu apprends à cadrer une simulation d’hameçonnage autorisée comme un exercice défensif : périmètre humain, consentement organisationnel, indicateurs utiles et débriefing sans humiliation.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("définir le cadre d’une simulation humaine autorisée, distinguer consentement et surprise opérationnelle, choisir des indicateurs utiles, puis préparer un débriefing orienté remédiation."),
    prerequisites("avoir compris l’autorisation écrite, les règles d’engagement, la minimisation des données et la logique de preuve minimale dans un test d’intrusion."),
    scenario("Awa doit aider l’association Teranga à préparer une campagne d’hameçonnage autorisée. La direction veut mesurer la capacité de signalement, pas piéger les salariés pour les humilier. Il faut donc définir qui approuve, quelles personnes sont dans le périmètre, quelles données seront conservées, quels messages restent acceptables, et comment transformer les résultats en amélioration concrète."),
    videoSlot("Encadrer une simulation d’hameçonnage autorisée"),
    text("L’ingénierie sociale n’est acceptable ici que dans un cadre défensif très strict. Une campagne d’hameçonnage autorisée demande un accord explicite, un périmètre humain défini, un mode de collecte proportionné et un débriefing bienveillant. La surprise opérationnelle peut exister à l’intérieur de ce cadre, mais elle ne remplace jamais le consentement de l’organisation ni, si le contexte local l’exige, la validation RH, juridique ou de la gouvernance compétente."),
    schema([
      "Cadre minimal avant toute simulation",
      "",
      "accord explicite",
      "périmètre humain défini",
      "données collectées limitées",
      "indicateurs annoncés",
      "débriefing bienveillant",
      "point de contact incident",
      "",
      "Sans cela, on ne lance rien",
    ].join("\n")),
    text("Les indicateurs utiles restent simples : taux de clic, taux de signalement, délai de signalement, qualité des remontées et actions de remédiation. Ils aident à améliorer la sensibilisation, le filtrage et les procédures. Ce que tu évites, au contraire, c’est le « score de honte », la publication nominative et le piège conçu pour humilier. Une campagne saine mesure un système socio-technique, pas la valeur morale des personnes."),
    schema([
      "Indicateurs utiles / dérive à éviter",
      "",
      "clics           -> oui",
      "signalements    -> oui",
      "délai alerte    -> oui",
      "liste publique  -> non",
      "classement honte-> non",
      "collecte inutile -> non",
      "",
      "On cherche une progression, pas un coupable",
    ].join("\n")),
    text("Des outils comme Gophish peuvent être cités comme plateformes libres de simulation, mais pas comme tutoriels prêts à envoyer un faux message. Dans la leçon, tu raisonnes surtout sur le cadrage et les résultats. Tu peux aussi rappeler qu’un bouton de signalement, une procédure claire et un débriefing court valent souvent plus qu’une campagne très sophistiquée, surtout dans une petite organisation."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant lit des résultats fictifs de campagne et calcule des indicateurs simples. Il ne génère aucun message et n’aide pas à contourner une défense. Il sert seulement à préparer un tableau de restitution défensif : clics, signalements et délai médian de remontée."),
    code([
      "# fichier demo-ingenierie-sociale.cjs",
      "const results = [",
      "  { person: 'u1', clicked: true, reportedAfterMin: 42 },",
      "  { person: 'u2', clicked: false, reportedAfterMin: 15 },",
      "  { person: 'u3', clicked: true, reportedAfterMin: null },",
      "  { person: 'u4', clicked: false, reportedAfterMin: 33 },",
      "  { person: 'u5', clicked: false, reportedAfterMin: null },",
      "];",
      "const clicked = results.filter((item) => item.clicked).length;",
      "const reported = results.filter((item) => item.reportedAfterMin !== null).map((item) => item.reportedAfterMin).sort((a, b) => a - b);",
      "const median = reported.length ? reported[Math.floor(reported.length / 2)] : null;",
      "console.log(JSON.stringify({",
      "  total: results.length,",
      "  clickRate: `${Math.round((clicked / results.length) * 100)}%`,",
      "  reportRate: `${Math.round((reported.length / results.length) * 100)}%`,",
      "  medianReportMin: median,",
      "}, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"total\": 5,",
      "//   \"clickRate\": \"40%\",",
      "//   \"reportRate\": \"60%\",",
      "//   \"medianReportMin\": 33",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si une campagne autorisée montre 40 % de clics, 60 % de signalements et un délai médian de 33 minutes, Awa ne conclut pas « les salariés ont échoué ». Elle peut écrire : « le signalement existe déjà, mais doit être accéléré ; la sensibilisation sur certains indices de message mérite d’être reprise ; le bouton ou le canal d’alerte doit être rappelé ». La restitution vise un progrès collectif, pas une sanction publique."),
    mistakes("confondre surprise opérationnelle et absence de consentement ; garder plus de données nominatives que nécessaire ; mesurer uniquement les clics ; rédiger un débriefing humiliant ou accusateur."),
    safety("sans accord explicite, périmètre humain défini et conservation minimale, tu ne lances pas de simulation. Tu ne fournis aucun modèle prêt à envoyer, aucun scénario de manipulation d’un tiers et aucune méthode de contournement. Si la législation locale impose d’autres validations, un juriste ou la gouvernance compétente doit trancher."),
    takeaway("une campagne autorisée sert à améliorer le signalement et les réflexes, pas à piéger des personnes. Le bon cadre tient en quatre mots : consentement, proportion, indicateurs utiles, débriefing bienveillant."),
    practice("Prépare-toi avec « Projet final : conduire un test d’intrusion sur dossier et rédiger le rapport » : la plateforme ne rejoue pas une campagne d’hameçonnage. Cette leçon t’aide surtout à cadrer, mesurer et restituer ce type d’exercice avec accord, puis tu termines par le quiz."),
    reference("gophishDocs"),
    reference("gophishCampaigns"),
    reference("gophishEmailReporting"),
    reference("gophishReports"),
    reference("gophishRepo"),
    reference("cmHameconnage"),
    reference("owaspVulnDisclosure"),
  ],
  quiz: {
    title: "Quiz : hameçonnage autorisé",
    questions: [
      questions.choice("Quel est le bon point de départ d’une campagne d’hameçonnage défensive ?", ["Un accord explicite, un périmètre humain défini et un plan de débriefing", "Un modèle très crédible envoyé d’abord pour voir qui tombe dans le piège", "Une publication des noms des personnes qui cliquent", "Une collecte maximale pour garder toutes les preuves"], 0, "Une simulation saine commence par le consentement organisationnel, le périmètre et la restitution prévue. La réponse tentante est de démarrer par le message lui-même, alors qu’un bon cadrage compte davantage que la sophistication du leurre.", "facile"),
      questions.choice("Pourquoi le taux de signalement vaut-il souvent autant que le taux de clic ?", ["Parce qu’il remplace tout besoin de sensibilisation", "Parce qu’il montre si l’organisation détecte et remonte l’incident à temps", "Parce qu’il sert à classer publiquement les équipes", "Parce qu’il garantit qu’aucun clic n’a eu lieu"], 1, "Le signalement mesure la capacité collective à transformer une erreur ou un doute en alerte utile. La mauvaise réponse la plus tentante est de croire qu’il remplace la sensibilisation, alors qu’il complète surtout la lecture des clics.", "moyen"),
      questions.multi("Lis cette décision : « accord signé, collecte limitée aux clics et signalements, débriefing collectif sans noms, tableau des retours sous 24 h ». Quelles affirmations sont correctes ? (plusieurs réponses)", ["Le cadre va plutôt dans le sens d’une simulation proportionnée", "L’absence de noms dans le débriefing réduit le risque d’humiliation", "Il manque forcément une publication nominative pour que la campagne soit crédible", "Le délai de retour peut devenir un indicateur utile"], [0, 1, 3], "L’accord, la collecte limitée, le débriefing collectif et le délai de retour vont bien dans le sens d’un exercice défensif. En revanche, une publication nominative n’ajoute pas de qualité pédagogique et peut casser la confiance plus qu’elle n’améliore les réflexes.", "difficile"),
      questions.tf("Dans ce cours, citer Gophish est acceptable comme repère de simulation autorisée, mais pas comme tutoriel prêt à envoyer à un tiers.", true, "Vrai : la plateforme peut être mentionnée comme outil connu de simulation avec accord, mais la leçon ne doit ni fournir de modèle opérationnel ni encourager un envoi hors cadre. La nuance entre repère conceptuel et mode d’emploi est essentielle.", "moyen"),
    ],
  },
};

const pentestRapportLesson: NewLesson = {
  key: "pentest-rapport",
  title: "Rédiger une recommandation utile",
  summary: "Tu apprends à transformer une observation brute en recommandation exploitable : problème précis, impact contextualisé, action vérifiable, propriétaire du correctif et critères de re-test.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("séparer observation, preuve et recommandation, reformuler une action trop vague, contextualiser l’impact sans drame, puis définir ce qu’un re-test doit réellement vérifier."),
    prerequisites("avoir compris la preuve minimale, la rédaction d’un constat et la nécessité de masquer les données sensibles inutiles dans un rapport."),
    scenario("Awa relit des notes de mission pour Baobab Tech. Plusieurs observations sont justes, mais les recommandations restent faibles : « sécuriser l’admin », « corriger vite », « revoir les droits ». Elle doit les transformer en actions qu’une équipe peut attribuer, exécuter, vérifier et re-tester, sans recopier plus de données sensibles que nécessaire."),
    videoSlot("Passer d’une note brute à une recommandation utile"),
    text("Une recommandation utile ne répète pas seulement le problème. Elle explique quoi corriger, où, par qui et comment vérifier que cela a marché. Dire « sécuriser l’admin » ne suffit pas. Dire « limiter la route d’export aux comptes du rôle finance, vérifier côté serveur à chaque requête, puis rejouer le test avec un compte standard » aide déjà beaucoup plus une équipe de correction."),
    schema([
      "Structure simple d’une recommandation",
      "",
      "problème observé",
      "-> impact probable",
      "-> action concrète",
      "-> propriétaire du correctif",
      "-> délai raisonnable",
      "-> critère de re-test",
      "",
      "Le lecteur doit savoir quoi faire ensuite",
    ].join("\n")),
    text("L’impact doit rester contextualisé. Une même faiblesse peut compter davantage sur un portail exposé au public que sur un service interne très segmenté. La recommandation ne remplace pas la preuve, mais elle la relie à une décision. Elle doit aussi éviter les slogans du type « renforcer la sécurité » ou « sensibiliser les utilisateurs » sans préciser le mécanisme concret, le périmètre et le résultat attendu."),
    schema([
      "Trop vague / utile",
      "",
      "revoir les droits",
      "-> vérifier côté serveur le rôle requis",
      "",
      "sécuriser le cookie",
      "-> ajouter Secure, HttpOnly, SameSite=Lax",
      "",
      "faire un re-test",
      "-> rejouer le cas avec compte standard",
    ].join("\n")),
    text("Le re-test a, lui aussi, une portée précise. Il ne « garantit pas la sécurité globale ». Il vérifie surtout trois choses : la faille n’est plus reproductible, le besoin métier reste intact, et la correction n’a pas introduit de régression évidente. C’est pour cela qu’un bon critère de re-test se formule dès la recommandation, pas seulement à la fin du projet."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant reformate trois observations brutes en recommandations structurées. Il ajoute un propriétaire et un test de vérification, sans inventer de secret ni recopier une donnée personnelle. L’idée est de passer d’une note floue à une action claire et vérifiable."),
    code([
      "# fichier demo-pentest-rapport.cjs",
      "const findings = [",
      "  { issue: 'export admin visible au role standard', owner: 'equipe applicative', fix: 'verifier le role cote serveur', retest: 'compte standard -> 403' },",
      "  { issue: 'cookie de session sans HttpOnly', owner: 'equipe web', fix: 'ajouter HttpOnly et verifier les usages JS', retest: 'Set-Cookie contient HttpOnly' },",
      "  { issue: 'partage interne trop large', owner: 'equipe infra', fix: 'limiter le partage au groupe metier', retest: 'compte hors groupe -> acces refuse' },",
      "];",
      "const rows = findings.map((item) => ({",
      "  probleme: item.issue,",
      "  action: item.fix,",
      "  proprietaire: item.owner,",
      "  verification: item.retest,",
      "}));",
      "console.log(JSON.stringify(rows, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// [",
      "//   {",
      "//     \"probleme\": \"export admin visible au role standard\",",
      "//     \"action\": \"verifier le role cote serveur\",",
      "//     \"proprietaire\": \"equipe applicative\",",
      "//     \"verification\": \"compte standard -> 403\"",
      "//   },",
      "//   {",
      "//     \"probleme\": \"cookie de session sans HttpOnly\",",
      "//     \"action\": \"ajouter HttpOnly et verifier les usages JS\",",
      "//     \"proprietaire\": \"equipe web\",",
      "//     \"verification\": \"Set-Cookie contient HttpOnly\"",
      "//   },",
      "//   {",
      "//     \"probleme\": \"partage interne trop large\",",
      "//     \"action\": \"limiter le partage au groupe metier\",",
      "//     \"proprietaire\": \"equipe infra\",",
      "//     \"verification\": \"compte hors groupe -> acces refuse\"",
      "//   }",
      "// ]",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : au lieu d’écrire « sécuriser l’admin », Awa peut rédiger « sur la route d’export des factures, vérifier côté serveur que seul le rôle finance peut accéder à la ressource, puis rejouer le cas avec un compte standard et attendre un 403 ». La phrase devient testable, attribuable et utile pour le re-test. Elle évite aussi de recopier la moindre donnée métier dans le résumé."),
    mistakes("confondre recommandation et slogan ; oublier le propriétaire du correctif ; exposer des données sensibles dans le résumé alors qu’une preuve masquée suffit ; écrire « faire un re-test » sans dire quoi rejouer."),
    safety("une recommandation ne doit jamais pousser à collecter plus de données pour « mieux prouver ». Tu gardes le minimum utile, tu masques les éléments sensibles et tu restes honnête sur ce qui a été vérifié ou non. Le re-test ne devient pas une autorisation générale de tout rejouer."),
    takeaway("une recommandation utile relie un problème précis à une action concrète, un propriétaire, un délai raisonnable et un critère de vérification. Le re-test vérifie une correction, pas la sécurité entière d’une organisation, et la leçon suivante t’apprend à assembler ces éléments dans un constat technique complet."),
    practice("Travaille avec « Projet final : conduire un test d’intrusion sur dossier et rédiger le rapport » : tu y transformeras des constats et des notes en recommandations claires, priorisées et prêtes pour un re-test, puis tu termines par le quiz de la leçon."),
    reference("nist80115"),
    reference("owaspWstg"),
    reference("cvss31Spec"),
    reference("ncscPentest"),
  ],
  quizExtension: {
    improve: [
      "Une recommandation utile ne se limite pas au nom d’un outil ou à un slogan. Elle décrit au minimum le problème visé, l’action concrète attendue, le contexte qui la rend importante et la façon de vérifier la correction. La mauvaise réponse la plus tentante est le scanner, parce qu’il donne une étiquette rapide, mais il ne remplace jamais une consigne de remédiation.",
      "Le re-test sert à vérifier qu’une correction empêche encore la reproduction du problème tout en laissant vivre le besoin métier. Il ne sert ni à publier des secrets ni à étendre le périmètre. La mauvaise réponse la plus tentante consiste à croire qu’un re-test « remplace l’autorisation », alors qu’il reste borné par le même cadre de mission.",
    ],
    add: [
      questions.choice("Quelle formulation ressemble le plus à une recommandation utile ?", ["Sécuriser rapidement l’administration", "Corriger le serveur au plus vite", "Sur la route « /admin/export », vérifier côté serveur le rôle requis, limiter l’accès au groupe finance et rejouer le cas avec un compte standard", "Relancer le scanner après la réunion"], 2, "La troisième réponse décrit l’actif, le contrôle attendu et le critère de re-test. Les autres restent trop vagues pour être attribuées et vérifiées. La fausse bonne idée la plus tentante est « corriger vite », qui ne dit ni quoi changer ni comment valider le résultat.", "moyen"),
      questions.multi("Lis cet extrait : « constat : cookie de session sans HttpOnly ; impact : vol de session facilité sur poste partagé ; recommandation : ajouter HttpOnly et vérifier qu’aucun script légitime n’en dépend ; re-test : l’en-tête Set-Cookie contient HttpOnly ». Quelles affirmations sont correctes ? (plusieurs réponses)", ["La recommandation décrit une action concrète", "Le re-test vérifie un critère observable", "L’extrait oblige à recopier le cookie en clair dans le résumé", "L’impact reste contextualisé au poste partagé"], [0, 1, 3], "L’extrait relie bien le problème, l’impact, l’action et le critère de vérification, sans imposer de recopier un secret. Le piège est de croire qu’une preuve utile doit reproduire la donnée sensible en clair, alors qu’un rapport sérieux préfère justement la minimiser.", "difficile"),
    ],
  },
};

const ptRapportTechniqueLesson: NewLesson = {
  key: "pt-rapport-technique",
  title: "Le rapport technique : constats, preuves, notes et plan de correction",
  summary: "Tu apprends à assembler un constat technique complet : titre précis, actif touché, preuve minimale, note justifiée, priorité métier et plan de correction lisible.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("structurer un constat de bout en bout, distinguer gravité et priorité, justifier un vecteur CVSS 3.1, puis relier chaque preuve à une action de correction et un re-test."),
    prerequisites("avoir compris la preuve minimale, la logique d’une recommandation utile et les bases de CVSS, EPSS et du contexte métier dans la priorisation."),
    scenario("Koffi assemble le rapport technique de l’association Teranga. Il a des notes de scan, un historique web, des preuves minimales et des pistes de correction. Son enjeu n’est pas d’empiler des captures, mais de produire des constats qu’un RSSI, une équipe web et une équipe système peuvent relire sans ambiguïté."),
    videoSlot("Construire un constat technique utile du titre au re-test"),
    text("Le rapport technique est la partie où chaque constat doit tenir debout seul. Un lecteur doit y trouver l’actif touché, la description du problème, la preuve minimale, l’impact, la note si tu en utilises une, la priorité pratique, la correction proposée et le re-test attendu. Si un constat oblige à aller chercher cinq pages plus loin pour comprendre la preuve, il fatigue la lecture et fragilise la correction."),
    schema([
      "Colonnes utiles d’un constat",
      "",
      "titre précis",
      "actif ou route touchée",
      "preuve minimale",
      "impact observé",
      "vecteur CVSS 3.1",
      "priorité métier",
      "recommandation",
      "re-test attendu",
    ].join("\n")),
    text("La note de gravité ne suffit pas à décider seule. CVSS 3.1 aide à décrire l’exploitabilité et l’impact technique. La priorité, elle, dépend aussi de l’exposition réelle, du rôle métier de l’actif, d’éventuels contrôles compensatoires et d’autres signaux comme EPSS ou le catalogue Known Exploited Vulnerabilities (KEV) de la CISA. Dans un rapport technique, tu dois donc séparer clairement « score », « justification » et « ordre de traitement recommandé »."),
    schema([
      "Note / priorité",
      "",
      "CVSS 3.1  -> gravité technique",
      "exposition -> public / interne / segmenté",
      "métier     -> actif critique ou non",
      "compensat. -> présent ou absent",
      "priorité   -> décision de correction",
      "",
      "Un score n’est pas un ordre automatique",
    ].join("\n")),
    text("Le titre compte lui aussi. « Contrôle d’accès manquant sur l’export facture » aide davantage que « faille critique n°3 ». La preuve minimale doit rester reproductible sans divulguer plus que nécessaire. Une ligne d’en-tête, un statut HTTP, un extrait de journal ou un vecteur CVSS justifié valent mieux qu’une avalanche de captures mal cadrées. Si une donnée sensible apparaît, tu la masques et tu l’indiques sobrement."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant calcule une note CVSS 3.1 à partir d’un vecteur simple, puis génère une fiche courte de constat. Il sépare bien le score, la priorité métier et le re-test. Tout est fictif, mais le calcul et la structure restent réels."),
    code([
      "# fichier demo-rapport-technique.cjs",
      "const metric = { AV: 'N', AC: 'L', PR: 'L', UI: 'N', S: 'U', C: 'H', I: 'L', A: 'N' };",
      "const weights = {",
      "  AV: { N: 0.85, A: 0.62, L: 0.55, P: 0.2 },",
      "  AC: { L: 0.77, H: 0.44 },",
      "  UI: { N: 0.85, R: 0.62 },",
      "  CIA: { H: 0.56, L: 0.22, N: 0 },",
      "  PR: { U: { N: 0.85, L: 0.62, H: 0.27 }, C: { N: 0.85, L: 0.68, H: 0.5 } },",
      "};",
      "const roundUp1 = (n) => Math.ceil(n * 10) / 10;",
      "const iscBase = 1 - (1 - weights.CIA[metric.C]) * (1 - weights.CIA[metric.I]) * (1 - weights.CIA[metric.A]);",
      "const impact = 6.42 * iscBase;",
      "const exploit = 8.22 * weights.AV[metric.AV] * weights.AC[metric.AC] * weights.PR[metric.S][metric.PR] * weights.UI[metric.UI];",
      "const base = impact <= 0 ? 0 : roundUp1(Math.min(impact + exploit, 10));",
      "const finding = {",
      "  title: 'Export facture accessible a un role standard',",
      "  vector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N',",
      "  score: base.toFixed(1),",
      "  prioriteMetier: 'haute',",
      "  retest: 'compte standard -> 403 et parcours finance intact',",
      "};",
      "console.log(JSON.stringify(finding, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"title\": \"Export facture accessible a un role standard\",",
      "//   \"vector\": \"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N\",",
      "//   \"score\": \"7.1\",",
      "//   \"prioriteMetier\": \"haute\",",
      "//   \"retest\": \"compte standard -> 403 et parcours finance intact\"",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : au lieu d’un constat vague du type « export non sécurisé », Koffi peut écrire « Contrôle d’accès manquant sur l’export facture », préciser la route touchée, joindre une preuve courte, justifier le vecteur CVSS 3.1, puis ajouter : « priorité haute car exposition Internet et données métier sensibles ». La note technique reste ainsi distincte de la décision pratique de correction."),
    mistakes("mettre une note sans vecteur ni justification ; confondre gravité et priorité ; oublier l’actif exact ou la route touchée ; remplacer le correctif par du jargon comme « durcir la sécurité »."),
    safety("le rapport technique n’a pas besoin de reproduire des secrets, un export complet ou des données personnelles en clair pour être crédible. Tu gardes la preuve minimale, tu masques ce qui identifie inutilement et tu assumes clairement ce qui reste une hypothèse ou un faux positif."),
    takeaway("un bon constat technique tient en une page : titre précis, preuve minimale, note justifiée, priorité expliquée, correction actionnable et re-test observable. Score et priorité se complètent, mais ne se confondent jamais."),
    practice("Travaille avec « Projet final : conduire un test d’intrusion sur dossier et rédiger le rapport » : tu y rassembleras preuves, notes, priorités et recommandations dans un rapport multi-constats, puis tu termines par le quiz."),
    reference("cvss31Spec"),
    reference("cvss31Calculator"),
    reference("firstEpss"),
    reference("cisaKev"),
    reference("nist80115"),
    reference("owaspWstg"),
    reference("cweSite"),
    reference("nvdCvss31Calculator"),
  ],
  quiz: {
    title: "Quiz : rapport technique",
    questions: [
      questions.choice("Quel titre aide le mieux un lecteur technique et métier ?", ["Faille critique n°3", "Problème important à corriger vite", "Contrôle d’accès manquant sur l’export facture", "Constat divers"], 2, "Le troisième titre nomme le problème et l’actif touché. Les autres restent trop vagues pour guider une correction ou un re-test. La fausse bonne idée la plus tentante est « problème important », qui semble prioritaire mais n’apprend rien de concret.", "facile"),
      questions.choice("Pourquoi faut-il séparer la note CVSS 3.1 de la priorité métier ?", ["Parce qu’une priorité doit toujours être plus basse que le score", "Parce que le score décrit la gravité technique, alors que la priorité dépend aussi de l’exposition, du métier et des contrôles compensatoires", "Parce qu’un rapport ne doit jamais contenir de score", "Parce que le score remplace tout besoin de preuve"], 1, "CVSS 3.1 sert à formaliser l’exploitabilité et l’impact technique, mais la priorité de correction dépend aussi du contexte de l’actif. La réponse tentante est de croire qu’un score haut commande automatiquement l’ordre de traitement, ce qui est souvent trop simple.", "moyen"),
      questions.multi("Lis cet extrait : « titre : export facture accessible au rôle standard ; preuve : compte standard -> 200 ; vecteur : CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N ; priorité : haute car portail public et données métier sensibles ». Quelles affirmations sont correctes ? (plusieurs réponses)", ["Le constat sépare bien la preuve et la justification de priorité", "Le vecteur CVSS dispense d’expliquer l’exposition réelle", "La priorité peut rester haute même sans score maximal", "Le re-test devrait vérifier à la fois le 403 attendu et l’absence de régression métier"], [0, 2, 3], "L’extrait montre justement qu’un score n’efface pas le besoin de contexte, qu’une priorité haute peut venir d’une exposition publique, et qu’un re-test doit aussi vérifier le besoin métier. L’erreur tentante est de croire que le vecteur CVSS dit déjà tout.", "difficile"),
      questions.tf("Masquer une donnée personnelle dans une preuve peut être plus professionnel que la recopier intégralement dans un rapport technique.", true, "Vrai : une preuve utile n’est pas une copie exhaustive. Si la donnée sensible n’est pas nécessaire en clair pour démontrer le constat, la masquer réduit le risque de diffusion secondaire sans affaiblir la qualité du rapport.", "moyen"),
    ],
  },
};

const ptSyntheseRetestLesson: NewLesson = {
  key: "pt-synthese-retest",
  title: "Résumé exécutif, restitution orale et re-test",
  summary: "Tu apprends à transformer plusieurs constats en messages de direction, à préparer une restitution orale honnête et à cadrer un re-test sans promettre une sécurité absolue.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("résumer des constats en messages de direction, distinguer annexe technique et synthèse exécutive, préparer un oral sans blâme, puis définir ce qu’un re-test confirme réellement."),
    prerequisites("avoir compris la structure d’un rapport technique, la différence entre gravité et priorité, et le rôle d’une recommandation utile."),
    scenario("Fatou prépare la restitution finale pour la boutique Soleil. Elle a six constats détaillés, mais la direction n’a ni le temps ni le besoin de relire chaque en-tête HTTP. Elle doit donc produire trois messages clairs, préparer un oral qui aligne technique et métier, puis expliquer ce qu’un re-test a confirmé, ce qu’il n’a pas rejoué et ce qui reste partiel."),
    videoSlot("Synthèse exécutive, oral et re-test sans exagération"),
    text("Le résumé exécutif n’est pas un rapport technique raccourci. Il répond à d’autres questions : quels risques dominent, quels actifs ou usages sont touchés, dans quel ordre agir, et quels points restent en attente ? Il parle donc plus de priorités, de dépendances et de décisions que de lignes brutes de preuve. La partie technique, elle, reste disponible en annexe pour les équipes qui doivent corriger."),
    schema([
      "Trois couches de restitution",
      "",
      "résumé exécutif -> risque, ordre, décisions",
      "rapport détaillé -> preuve, score, correctif",
      "oral final -> aligner métier, technique, calendrier",
      "",
      "Chaque couche a son public principal",
    ].join("\n")),
    text("La restitution orale doit rester factuelle et utile. On y explique ce qui a été vérifié, ce qui est corrigé, ce qui reste partiel et ce qui n’a pas été rejoué. On évite le blâme nominatif et les phrases absolues du type « tout est sécurisé ». Un bon oral aide à choisir les trois premières actions, à clarifier les dépendances et à confirmer qui porte quoi dans la correction."),
    schema([
      "Re-test : ce qu’il dit",
      "",
      "faille rejouée ?        oui / non",
      "besoin métier intact ?  oui / non",
      "régression évidente ?   oui / non",
      "",
      "Il ne dit pas : plus aucun risque partout",
    ].join("\n")),
    text("Le re-test clôt une boucle précise. Il confirme qu’un problème n’est plus reproductible, que la correction n’a pas cassé le besoin métier et qu’aucune régression évidente n’apparaît dans le périmètre rejoué. Il ne remplace ni un audit complet, ni une surveillance continue. Dire cela clairement renforce la confiance au lieu de survendre la portée du travail."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant lit cinq constats fictifs avec leurs statuts de correction et produit deux sorties courtes : une synthèse exécutive et un tableau de re-test. Tout reste local et sert uniquement à apprendre à condenser sans trahir."),
    code([
      "# fichier demo-synthese-retest.cjs",
      "const findings = [",
      "  { id: 'W01', status: 'corrige', priority: 'haute', area: 'web' },",
      "  { id: 'N02', status: 'partiel', priority: 'haute', area: 'reseau' },",
      "  { id: 'C03', status: 'non_corrige', priority: 'moyenne', area: 'comptes' },",
      "  { id: 'W04', status: 'corrige', priority: 'moyenne', area: 'web' },",
      "  { id: 'I05', status: 'corrige', priority: 'haute', area: 'infra' },",
      "];",
      "const count = (status) => findings.filter((item) => item.status === status).length;",
      "const executive = [",
      "  `constats prioritaires encore ouverts: ${findings.filter((item) => item.priority === 'haute' && item.status !== 'corrige').length}`,",
      "  `corrections confirmées: ${count('corrige')}` ,",
      "  `elements partiels ou ouverts: ${count('partiel') + count('non_corrige')}` ,",
      "];",
      "console.log(JSON.stringify({ executive, retest: { corrige: count('corrige'), partiel: count('partiel'), nonCorrige: count('non_corrige') } }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"executive\": [",
      "//     \"constats prioritaires encore ouverts: 1\",",
      "//     \"corrections confirmées: 3\",",
      "//     \"elements partiels ou ouverts: 2\"",
      "//   ],",
      "//   \"retest\": {",
      "//     \"corrige\": 3,",
      "//     \"partiel\": 1,",
      "//     \"nonCorrige\": 1",
      "//   }",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : au lieu de lire six constats l’un après l’autre à la direction, Fatou peut dire : « trois corrections prioritaires sont confirmées, une correction réseau reste partielle, un point comptes reste ouvert, et le re-test n’a porté que sur les fonctions corrigées ». Cette formulation informe, priorise et borne honnêtement la portée du travail sans noyer l’auditoire dans les détails bruts."),
    mistakes("transformer la synthèse en inventaire technique complet ; promettre qu’un re-test « garantit » la sécurité ; blâmer des personnes au lieu de parler de processus et de correction ; oublier de distinguer corrigé, partiel et non corrigé."),
    safety("la restitution finale doit protéger les données sensibles autant que le rapport détaillé. Tu n’ajoutes pas de secret, tu ne nommes pas inutilement des personnes et tu ne présentes pas une hypothèse comme un fait confirmé. Si une correction n’a pas été rejouée, tu l’écris clairement."),
    takeaway("résumé exécutif, rapport détaillé et oral final ont chacun un rôle distinct. Le re-test confirme une correction dans un périmètre rejoué, mais ne remplace jamais une assurance globale de sécurité."),
    practice("Travaille avec « Projet final : conduire un test d’intrusion sur dossier et rédiger le rapport » : tu y apprendras à condenser plusieurs constats en priorités lisibles, puis à exprimer honnêtement ce que le re-test confirme ou non avant de terminer par le quiz."),
    reference("nist80115"),
    reference("ncscPentest"),
    reference("owaspWstg"),
    reference("cvss31Spec"),
  ],
  quiz: {
    title: "Quiz : synthèse et re-test",
    questions: [
      questions.choice("Que doit surtout contenir un résumé exécutif ?", ["Les preuves brutes ligne par ligne", "Les principaux risques, l’ordre de traitement et l’état d’avancement des corrections", "Uniquement les scores CVSS les plus hauts", "Les captures non masquées pour la direction"], 1, "Le résumé exécutif sert à orienter la décision : risques, priorités, dépendances et état des corrections. La réponse tentante est la preuve brute, utile en annexe technique mais beaucoup trop détaillée pour ce niveau de lecture.", "facile"),
      questions.choice("Pourquoi un re-test n’équivaut-il pas à une garantie globale de sécurité ?", ["Parce qu’il ne doit jamais être documenté", "Parce qu’il vérifie un ensemble borné de corrections et de régressions évidentes dans le périmètre rejoué", "Parce qu’il remplace toute surveillance ultérieure", "Parce qu’il ignore volontairement les besoins métier"], 1, "Le re-test a une portée précise : confirmer des corrections et quelques effets de bord évidents. La mauvaise réponse la plus tentante est d’en faire une promesse globale, alors qu’il reste limité par le périmètre et le temps du contrôle.", "moyen"),
      questions.multi("Lis cette synthèse : « trois corrections confirmées, une correction réseau partielle, un point comptes encore ouvert, re-test limité aux fonctions corrigées ». Quelles conclusions sont correctes ? (plusieurs réponses)", ["Le suivi distingue au moins trois statuts de correction", "La partie réseau peut nécessiter une action complémentaire", "Le re-test couvre forcément tout le système d’information", "La communication reste honnête sur ce qui n’a pas été rejoué"], [0, 1, 3], "La synthèse signale clairement ce qui est corrigé, partiel et ouvert, tout en bornant le re-test aux fonctions rejouées. Le piège serait d’en déduire une couverture globale, justement contredite par la dernière phrase.", "difficile"),
      questions.tf("Une restitution orale peut être très utile sans remplacer le rapport écrit.", true, "Vrai : l’oral aligne les parties prenantes, répond aux questions et aide à fixer les priorités, mais il ne remplace ni les preuves détaillées ni la traçabilité du rapport écrit. Les deux supports se complètent.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c5:10",
    position: 9,
    title: "Réseau interne, Wi-Fi et ingénierie sociale",
    description: "Ce module t’apprend à lire des expositions internes, à auditer proprement ton propre Wi-Fi et à encadrer une campagne d’hameçonnage autorisée sans dériver vers une recette offensive. Critères de réussite : relier un service interne à une erreur de segmentation ; formuler un audit Wi-Fi défensif sur son propre réseau ; distinguer indicateurs utiles et pratiques abusives dans une simulation humaine.",
    lessons: [ptReseauInterneLesson, ptWifiAuditLesson, ptIngenierieSocialeLesson],
  },
  {
    key: "c5:2",
    position: 10,
    existing: { fromTitle: "Restitution" },
    title: "Restitution et suivi",
    description: "Tu y apprendras à transformer des notes techniques en recommandations utiles, constats clairs, synthèse exécutive honnête et re-test sérieux. Critères de réussite : séparer preuve, impact et action ; construire un constat avec une note défendable ; expliquer ce qu’un re-test vérifie, et ce qu’il ne garantit pas.",
    lessons: [pentestRapportLesson, ptRapportTechniqueLesson, ptSyntheseRetestLesson],
  },
];
