import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const osintSourcesLesson: NewLesson = {
  key: "pt-osint-sources",
  title: "Sources publiques : DNS, certificats, WHOIS et moteurs de recherche",
  summary: "Tu apprends à inventorier des informations publiques utiles à un audit, à les croiser sans toucher la cible, puis à écrire un constat d’OSINT sobre et vérifiable.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("définir la reconnaissance passive, lire des enregistrements DNS courants, distinguer RDAP et WHOIS, interpréter un journal de certificats, puis rédiger un inventaire court avec ses limites."),
    prerequisites("avoir compris le cadre légal d’un test d’intrusion et connaître les bases de DNS, d’HTTP et des noms de domaine."),
    scenario("Ama prépare un audit autorisé pour Baobab Tech. Avant toute action sur la cible, elle doit documenter « example.com » à partir de sources publiques : DNS, réponses RDAP, journaux de transparence des certificats, pages publiques et moteurs de recherche. Son objectif n’est pas de tout savoir, mais de partir avec une carte propre, datée et défendable."),
    videoSlot("Collecter juste assez d’OSINT avant un audit"),
    text("La reconnaissance passive consiste à observer des indices publics sans interaction intrusive avec la cible. Tu lis ce que des tiers publient déjà : enregistrements DNS visibles, réponses RDAP, journaux de transparence des certificats, pages indexées, dépôts publics, documents d’aide, offres d’emploi. Le but n’est pas d’« aspirer Internet », mais de préparer la suite avec des faits vérifiables, datés et reliés au périmètre autorisé."),
    schema([
      "Sources passives utiles",
      "",
      "DNS public  -> noms, messagerie, délégation",
      "RDAP/WHOIS  -> titulaire, plages, contacts",
      "CT logs     -> certificats et noms observés",
      "moteurs     -> pages, titres, copies",
      "docs/publi  -> technologies, API, procédures",
      "",
      "Règle : public ne veut pas dire illimité",
    ].join("\n")),
    text("Côté DNS, tu dois surtout savoir lire ce que chaque type t’apprend. Un enregistrement « A » relie un nom à une IPv4, « AAAA » à une IPv6, « MX » à la messagerie, « NS » aux serveurs de noms, « CNAME » à un alias, « TXT » à des informations textuelles comme SPF, des clés publiques DKIM, des politiques DMARC ou des indices d’intégration. « SOA » décrit la zone et « CAA » borne les autorités de certification autorisées. Tu n’as pas besoin de refaire tout le cours Réseaux : ici, l’important est de déduire ce qu’un nom révèle, pas de faire de l’administration DNS."),
    schema([
      "Ce qu’une source peut dire, et ce qu’elle ne prouve pas",
      "",
      "A/AAAA  : où pointe un nom",
      "MX      : qui reçoit le courrier",
      "TXT     : politiques, clés ou traces d’intégration",
      "RDAP    : objet enregistré et métadonnées",
      "CT log  : qu’un certificat public a existé",
      "",
      "Aucune source seule n’est exhaustive",
    ].join("\n")),
    text("RDAP est aujourd’hui le repère moderne pour les données d’enregistrement. WHOIS reste très présent dans les habitudes et certains outils, mais son format libre est moins structuré. Les journaux de transparence des certificats servent, eux, à repérer des noms vus dans des certificats publics : un sous-domaine observé dans un CT log peut être utile à l’inventaire, sans prouver qu’il est encore actif ni qu’il est dans le périmètre. Tu notes donc toujours la source, la date et le niveau de confiance."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script ci-dessous travaille uniquement sur des valeurs fictives locales, au format réaliste. Il lit un petit inventaire DNS, deux réponses RDAP simplifiées et trois entrées de certificats, puis compte ce que chaque source apporte. Si tu veux ensuite utiliser « nslookup » ou « dig », fais-le seulement sur ton propre laboratoire ou sur une cible explicitement autorisée par écrit."),
    code([
      "// fichier demo-osint-sources.cjs",
      "const dns = [",
      "  { name: 'example.com', type: 'A', value: '192.0.2.10' },",
      "  { name: 'www.example.com', type: 'CNAME', value: 'example.com' },",
      "  { name: 'mail.example.com', type: 'A', value: '192.0.2.25' },",
      "  { name: 'example.com', type: 'MX', value: '10 mail.example.com' },",
      "  { name: 'example.com', type: 'TXT', value: 'v=spf1 mx -all' },",
      "  { name: 'api.example.com', type: 'AAAA', value: '2001:db8::20' },",
      "];",
      "const rdap = [",
      "  { handle: 'NET-192-0-2-0-1', kind: 'network' },",
      "  { handle: 'EXAMPLE-COM', kind: 'domain' },",
      "];",
      "const certs = [",
      "  { loggedAt: '2026-03-10', names: ['example.com', 'www.example.com'] },",
      "  { loggedAt: '2026-03-10', names: ['api.example.com'] },",
      "  { loggedAt: '2026-03-10', names: ['status.example.com'] },",
      "];",
      "const typeCounts = dns.reduce((acc, item) => {",
      "  acc[item.type] = (acc[item.type] || 0) + 1;",
      "  return acc;",
      "}, {});",
      "const names = [...new Set(certs.flatMap((item) => item.names))].sort();",
      "console.log(JSON.stringify({ typeCounts, rdapKinds: rdap.map((item) => item.kind), names }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"typeCounts\": {",
      "//     \"A\": 2,",
      "//     \"CNAME\": 1,",
      "//     \"MX\": 1,",
      "//     \"TXT\": 1,",
      "//     \"AAAA\": 1",
      "//   },",
      "//   \"rdapKinds\": [",
      "//     \"network\",",
      "//     \"domain\"",
      "//   ],",
      "//   \"names\": [",
      "//     \"api.example.com\",",
      "//     \"example.com\",",
      "//     \"status.example.com\",",
      "//     \"www.example.com\"",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : l’inventaire minimal ici retient quatre noms utiles. « example.com » et « www.example.com » sont corroborés par DNS et certificat, donc leur confiance est bonne. « api.example.com » n’apparaît qu’une fois dans les données fictives mais reste intéressant, car il combine un nom explicite et une IPv6 publique de documentation. « status.example.com » ne vient que du journal de certificats : tu peux le noter comme piste à confirmer, pas comme actif certain ni comme cible automatiquement autorisée."),
    mistakes("croire qu’une seule source passive suffit ; présenter WHOIS comme le standard moderne unique ; confondre un nom vu dans un certificat avec une cible active et autorisée ; oublier de dater la collecte ou de noter la source exacte."),
    safety("une source publique ne t’autorise ni le scraping massif, ni la republication complète de données personnelles, ni le contournement d’un accès protégé. Tu restes sur ton laboratoire, une plateforme d’entraînement légale, ou un périmètre couvert par une autorisation écrite."),
    takeaway("la reconnaissance passive prépare le terrain sans toucher la cible. DNS, RDAP et CT logs se complètent, mais aucun n’est exhaustif. Un bon inventaire note la source, la date, le niveau de confiance et ses limites."),
    practice("Travaille dans « TP 2 : reconnaissance passive sur des sources publiques fictives » : tu y liras des enregistrements DNS, un WHOIS/RDAP fictif et un journal de certificats pour inventorier des noms et des technologies sans toucher la cible. Termine ensuite par le quiz."),
    reference("rfc1034"),
    reference("rfc1035"),
    reference("ianaDnsParameters"),
    reference("rfc7208"),
    reference("rfc6376"),
    reference("rfc7489"),
    reference("crtSh"),
    reference("rfc9082"),
    reference("rfc9083"),
    reference("rfc3912"),
    reference("rfc9162"),
  ],
  quiz: {
    title: "Quiz : sources publiques",
    questions: [
      questions.choice("Quel énoncé décrit le mieux une reconnaissance passive ?", ["Lire des sources publiques pour préparer un audit sans interaction intrusive", "Tester immédiatement tous les ports d’une cible inconnue", "Créer un compte administrateur pour vérifier la surface exposée", "Publier les données collectées pour demander de l’aide"], 0, "La reconnaissance passive consiste à observer ce qui est déjà public et utile au périmètre. La mauvaise réponse la plus tentante est le scan de ports : il peut être légitime plus tard, mais ce n’est plus passif et il exige un cadre autorisé.", "facile"),
      questions.choice("Pourquoi un nom vu dans un journal de certificats doit-il être présenté avec prudence ?", ["Parce qu’un CT log ne garde jamais l’historique", "Parce qu’il indique qu’un certificat public a existé, pas que le nom est encore actif ni autorisé", "Parce qu’il remplace automatiquement le périmètre contractuel", "Parce qu’il interdit toute vérification par DNS"], 1, "Le journal de certificats est précieux pour l’inventaire, mais il ne prouve ni l’état actuel du service ni son inclusion dans le périmètre. L’erreur tentante est de transformer un indice public en feu vert opérationnel.", "moyen"),
      questions.multi("Parmi ces sources, lesquelles relèvent bien d’une collecte passive si elles sont déjà publiques ? (plusieurs réponses)", ["Une réponse RDAP", "Un journal de transparence des certificats", "Un fichier README public", "Un brute force sur un portail VPN"], [0, 1, 2], "RDAP, les CT logs et un dépôt public sont des sources passives quand tu te limites à ce qui est exposé volontairement. Un brute force change immédiatement de nature : il interagit avec la cible et sort du cadre de la collecte passive.", "difficile"),
      questions.tf("Présenter WHOIS comme l’unique standard moderne pour les données d’enregistrement serait exact aujourd’hui.", false, "Faux : WHOIS reste fréquent, mais RDAP est le protocole moderne structuré qu’il faut connaître et citer proprement. Dire l’inverse entretient une vision datée et masque l’intérêt des réponses JSON normalisées pour l’inventaire.", "moyen"),
    ],
  },
};

const surfaceExposeeLesson: NewLesson = {
  key: "pt-surface-exposee",
  title: "Cartographier la surface exposée : noms, technologies et services",
  summary: "Tu apprends à transformer des indices publics en carte d’exposition utile, puis à séparer ce que tu peux affirmer, soupçonner ou devoir confirmer plus tard.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("recouper des noms publics, repérer des technologies visibles, distinguer un indice d’un fait confirmé, puis produire une carte d’exposition lisible et prudente."),
    prerequisites("savoir ce qu’est une reconnaissance passive et savoir lire un nom de domaine, un en-tête HTTP simple et un certificat public."),
    scenario("Fatou prépare un audit autorisé pour l’association Teranga. Elle voit passer « example.org » dans une documentation publique, un certificat mentionnant « api.example.org », une offre d’emploi citant Nginx et PostgreSQL, puis un en-tête HTTP de démonstration. Elle doit transformer ces indices en surface exposée probable sans inventer de vulnérabilité ni toucher la cible."),
    videoSlot("Passer des indices publics à une carte d’exposition"),
    text("Cartographier la surface exposée, c’est relier des noms, des points d’entrée, des services visibles et des tiers apparents. Tu ne cherches pas encore à valider tout ce qui répond. Tu construis une hypothèse de travail : quels noms existent probablement, quelles briques semblent publiées, quels services web ou mail sont mentionnés, et quels éléments appartiennent peut-être à un tiers. La qualité de cette carte dépend moins du volume d’indices que de ta capacité à noter leur origine et leur niveau de confiance."),
    schema([
      "Carte d’exposition : quatre colonnes utiles",
      "",
      "nom            -> ce qui est observé",
      "source         -> d’où vient l’indice",
      "technologie    -> ce que la source suggère",
      "confiance      -> confirmé / probable / à vérifier",
      "",
      "Règle : observé n’est pas prouvé vulnérable",
    ].join("\n")),
    text("Les noms de domaine et sous-domaines donnent une première structure. Les certificats publics suggèrent des points d’entrée nommés. Une page d’aide, un fichier de configuration d’exemple ou une annonce d’emploi peuvent révéler un serveur web, un CDN, une base de données ou un fournisseur d’envoi d’emails. Un en-tête « Server » ou un titre HTML inventorié dans une note de mission peut, lui, ajouter un indice de technologie. Mais attention : une bannière seule ne suffit pas à déduire une version exploitable, ni même la pile exacte derrière un proxy ou un load balancer."),
    schema([
      "Indice public  -> ce que tu peux dire",
      "",
      "certificat     -> un nom a été utilisé",
      "README public  -> une technologie est citée",
      "offre d’emploi -> une pile est probablement en usage",
      "Server: nginx  -> un front web parle comme Nginx",
      "",
      "Aucun indice seul ne prouve une CVE",
    ].join("\n")),
    text("Tu dois aussi séparer l’actif principal des tiers. Un sous-domaine CNAME vers un service externe, un fournisseur d’authentification ou un outil d’assistance ne deviennent pas automatiquement des cibles testables. Ils peuvent compter dans la surface exposée au sens de l’inventaire, mais ils n’entrent dans l’action que si les règles d’engagement ou le propriétaire les couvrent explicitement. C’est là que la cartographie aide le cadrage au lieu de le contourner."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant fusionne des indices fictifs venant d’un CT log, d’une documentation publique, d’une annonce d’emploi et d’un extrait d’en-têtes HTTP. Il produit une table courte « nom / sources / technologie / confiance ». Tout est local et inventé : tu apprends à raisonner, pas à interroger une cible réelle."),
    code([
      "// fichier demo-surface-exposee.cjs",
      "const observations = [",
      "  { name: 'example.org', source: 'documentation', tech: 'site institutionnel' },",
      "  { name: 'www.example.org', source: 'ct', tech: 'certificat public' },",
      "  { name: 'api.example.org', source: 'ct', tech: 'certificat public' },",
      "  { name: 'api.example.org', source: 'doc-api', tech: 'JSON over HTTPS' },",
      "  { name: 'mail.example.org', source: 'dns-mx', tech: 'messagerie' },",
      "  { name: 'support.example.org', source: 'job', tech: 'Nginx' },",
      "  { name: 'support.example.org', source: 'headers', tech: 'Server: nginx' },",
      "];",
      "const byName = new Map();",
      "for (const item of observations) {",
      "  const current = byName.get(item.name) || { sources: new Set(), tech: new Set() };",
      "  current.sources.add(item.source);",
      "  current.tech.add(item.tech);",
      "  byName.set(item.name, current);",
      "}",
      "const rows = [...byName.entries()].map(([name, data]) => ({",
      "  name,",
      "  sources: data.sources.size,",
      "  technologies: [...data.tech].join(' ; '),",
      "  confiance: data.sources.size >= 2 ? 'probable' : 'a verifier',",
      "})).sort((a, b) => a.name.localeCompare(b.name));",
      "console.log(JSON.stringify(rows, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// [",
      "//   {",
      "//     \"name\": \"api.example.org\",",
      "//     \"sources\": 2,",
      "//     \"technologies\": \"certificat public ; JSON over HTTPS\",",
      "//     \"confiance\": \"probable\"",
      "//   },",
      "//   {",
      "//     \"name\": \"example.org\",",
      "//     \"sources\": 1,",
      "//     \"technologies\": \"site institutionnel\",",
      "//     \"confiance\": \"a verifier\"",
      "//   },",
      "//   {",
      "//     \"name\": \"mail.example.org\",",
      "//     \"sources\": 1,",
      "//     \"technologies\": \"messagerie\",",
      "//     \"confiance\": \"a verifier\"",
      "//   },",
      "//   {",
      "//     \"name\": \"support.example.org\",",
      "//     \"sources\": 2,",
      "//     \"technologies\": \"Nginx ; Server: nginx\",",
      "//     \"confiance\": \"probable\"",
      "//   },",
      "//   {",
      "//     \"name\": \"www.example.org\",",
      "//     \"sources\": 1,",
      "//     \"technologies\": \"certificat public\",",
      "//     \"confiance\": \"a verifier\"",
      "//   }",
      "// ]",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : « api.example.org » est une entrée plausible, car deux sources publiques différentes la mentionnent. Tu peux donc l’inscrire dans la surface exposée probable. En revanche, « support.example.org » ne devient pas une vulnérabilité parce qu’un en-tête parle comme Nginx. La bonne formulation est : « service de support probablement publié, front web semblant parler comme Nginx, confirmation technique à faire dans le cadre autorisé ». Cette nuance évite de vendre une certitude que tu n’as pas encore."),
    mistakes("confondre technologie visible et faille prouvée ; oublier de distinguer actif du client et service tiers ; supprimer le niveau de confiance dans l’inventaire ; croire qu’un nom absent d’une source unique n’existe pas."),
    safety("une carte d’exposition doit rester proportionnée. Tu minimises les données personnelles, tu cites les sources utiles, et tu ne transformes pas un indice public en permission de tester ce qui n’est pas explicitement autorisé."),
    takeaway("une bonne carte d’exposition relie des noms, des technologies et des services avec un niveau de confiance. Elle aide à cadrer la suite du test, pas à affirmer trop tôt qu’une technologie ou un tiers est vulnérable."),
    practice("Travaille dans « TP 2 : reconnaissance passive sur des sources publiques fictives » : le laboratoire te fait recouper des noms, des pages publiques et des indices techniques pour produire une surface exposée plausible, sans toucher la cible. Termine ensuite par le quiz."),
    reference("owaspCsAttackSurface"),
    reference("crtSh"),
    reference("owaspWstg"),
    reference("securityTxtSite"),
  ],
  quiz: {
    title: "Quiz : surface exposée",
    questions: [
      questions.choice("Que cherches-tu d’abord quand tu cartographies une surface exposée à partir de sources publiques ?", ["Des noms, services et technologies plausibles à confirmer dans le cadre autorisé", "Le mot de passe d’administration du site", "Une preuve que tous les tiers sont testables", "Un exploit prêt à l’emploi"], 0, "Le but initial est de dresser une carte de travail : noms, services, tiers apparents et technologies visibles. La réponse tentante est la preuve immédiate, mais une cartographie ne remplace ni le cadrage ni une validation technique autorisée.", "facile"),
      questions.choice("Pourquoi un en-tête « Server: nginx » doit-il être interprété avec prudence ?", ["Parce qu’il prouve automatiquement une CVE critique", "Parce qu’il peut refléter un front, un proxy ou une bannière trompeuse sans prouver la version réelle", "Parce qu’il ne peut jamais apparaître sur un service HTTPS", "Parce qu’il remplace une sortie Nmap complète"], 1, "Un en-tête utile donne un indice, mais il ne prouve ni la version exacte ni la pile complète. La fausse bonne réponse la plus tentante est la CVE immédiate : une bannière seule ne suffit pas à démontrer une vulnérabilité exploitable.", "moyen"),
      questions.multi("Quelles colonnes rendent une carte d’exposition plus honnête ? (plusieurs réponses)", ["La source de l’indice", "Le niveau de confiance", "Le mot « critique » sur chaque ligne", "La technologie observée ou supposée"], [0, 1, 3], "La source, la technologie observée et le niveau de confiance aident à relire et discuter la carte. Étiqueter tout en « critique » supprime le discernement et empêche de distinguer un simple indice d’un constat réellement confirmé.", "difficile"),
      questions.tf("Un sous-domaine vu dans un certificat public entre automatiquement dans le périmètre testable.", false, "Faux : un certificat public peut révéler un nom intéressant, mais le périmètre se décide dans les règles d’engagement. Transformer un indice d’inventaire en autorisation d’action serait précisément une erreur de méthode et de cadre.", "moyen"),
    ],
  },
};

const osintEthiqueLesson: NewLesson = {
  key: "pt-osint-ethique",
  title: "OSINT responsable : ce qu’on collecte, ce qu’on garde et ce qu’on ne touche pas",
  summary: "Tu apprends à garder une collecte utile, proportionnée et documentée, sans franchir d’accès protégé ni stocker des données personnelles inutilement.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("appliquer la minimisation des données, classer un artefact OSINT selon sa sensibilité, décider quoi masquer ou purger, puis rédiger une note d’OSINT responsable."),
    prerequisites("savoir ce qu’est une reconnaissance passive et pourquoi le périmètre, la date et la source comptent autant que l’information trouvée."),
    scenario("Moussa rassemble des sources publiques pour l’association Teranga. Dans un document ancien, il voit des adresses nominatives, un numéro de téléphone direct et le nom d’un ancien portail interne. Il doit décider ce qu’il conserve dans sa note de travail, ce qu’il masque pour le livrable et ce qu’il écarte complètement."),
    videoSlot("Faire de l’OSINT utile sans tout garder"),
    text("L’OSINT responsable ne consiste pas à stocker tout ce qui passe. Il consiste à collecter juste ce qui aide à cadrer, comprendre et corriger. Dès qu’une donnée touche à des personnes, à des contacts directs, à des documents non nécessaires ou à des éléments hors périmètre, tu te demandes : en ai-je vraiment besoin, pour combien de temps, et sous quelle forme ? Cette discipline protège la cible, le testeur et la qualité du rapport."),
    schema([
      "Décision simple sur un artefact public",
      "",
      "utile au périmètre ?  -> oui / non",
      "personnel ou sensible ? -> oui / non",
      "preuve minimale suffit ? -> oui / non",
      "",
      "Garder, masquer, purger :",
      "le minimum nécessaire",
    ].join("\n")),
    text("Le fait qu’une information soit publique n’autorise pas sa republication intégrale ni sa conservation sans fin. Une adresse email nominative, une signature de document ou un organigramme ancien peuvent être utiles à comprendre la surface humaine d’une organisation, mais ils doivent souvent être résumés, masqués ou exclus du livrable final. La logique du RGPD aide ici : minimisation, besoin d’en connaître, durée limitée, accès restreint."),
    schema([
      "Ce qu’on ne touche pas",
      "",
      "accès protégé derrière un compte",
      "anti-bot ou anti-scraping à contourner",
      "données personnelles complètes sans nécessité",
      "collecte de masse hors périmètre",
      "",
      "Observer un indice n’efface pas le cadre",
    ].join("\n")),
    text("La frontière la plus simple à retenir est la suivante : lire un indice public n’autorise pas à franchir un accès protégé « pour vérifier ». Tu ne contournes pas un anti-bot, tu ne crées pas un compte si ce n’est pas prévu, tu ne republies pas un document sensible pour illustrer ton propos. Tu cites sobrement la source, la date, ce qu’elle t’apprend, puis tu réduis le reste au strict nécessaire pour la preuve minimale."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant classe cinq artefacts OSINT fictifs selon leur utilité, leur sensibilité et leur action conseillée. Il calcule aussi une date de purge à partir de la date d’exemple « 2026-03-10 ». Tout reste local, défensif et non nominatif : l’objectif est de t’entraîner à décider proprement."),
    code([
      "// fichier demo-osint-ethique.cjs",
      "const baseDate = new Date('2026-03-10T00:00:00Z');",
      "const artifacts = [",
      "  { label: 'CT log avec api.example.com', useful: true, personal: false },",
      "  { label: 'adresse nominative sur PDF public', useful: true, personal: true },",
      "  { label: 'ancien mot de passe colle dans une capture', useful: false, personal: true },",
      "  { label: 'offre d’emploi citant Nginx', useful: true, personal: false },",
      "  { label: 'nom de portail hors perimetre', useful: false, personal: false },",
      "];",
      "const decisions = artifacts.map((item) => ({",
      "  label: item.label,",
      "  action: !item.useful ? 'purger' : item.personal ? 'masquer' : 'garder',",
      "}));",
      "const purgeDate = new Date(baseDate.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);",
      "console.log(JSON.stringify({ decisions, purgeDate }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"decisions\": [",
      "//     {",
      "//       \"label\": \"CT log avec api.example.com\",",
      "//       \"action\": \"garder\"",
      "//     },",
      "//     {",
      "//       \"label\": \"adresse nominative sur PDF public\",",
      "//       \"action\": \"masquer\"",
      "//     },",
      "//     {",
      "//       \"label\": \"ancien mot de passe colle dans une capture\",",
      "//       \"action\": \"purger\"",
      "//     },",
      "//     {",
      "//       \"label\": \"offre d’emploi citant Nginx\",",
      "//       \"action\": \"garder\"",
      "//     },",
      "//     {",
      "//       \"label\": \"nom de portail hors perimetre\",",
      "//       \"action\": \"purger\"",
      "//     }",
      "//   ],",
      "//   \"purgeDate\": \"2026-03-24\"",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : l’adresse nominative trouvée dans un PDF public peut justifier une mention du type « un contact nominatif est exposé dans une archive publique », mais pas la recopie de l’adresse complète dans le rapport. À l’inverse, un ancien mot de passe collé dans une capture d’écran sort du besoin minimal : si la mission n’exige pas de le conserver comme preuve convenue, tu le purges et tu décris le risque sans répéter la donnée."),
    mistakes("garder tous les artefacts « au cas où » ; oublier de noter la source et la date ; recopier des données personnelles complètes dans le rapport ; considérer qu’un anti-bot ou un compte requis n’est qu’un détail à contourner."),
    safety("tu minimises les données, tu protèges l’accès aux notes de mission et tu demandes un avis juridique local dès qu’une obligation nationale précise est en jeu. Sans besoin explicite, tu ne republies pas, tu ne scrapes pas massivement et tu ne franchis pas d’accès protégé."),
    takeaway("en OSINT, le bon réflexe n’est pas d’accumuler, mais de sélectionner. Tu gardes le minimum utile, tu masques ce qui identifie des personnes et tu purges ce qui est inutile ou trop sensible pour la preuve attendue."),
    practice("Travaille dans « TP 2 : reconnaissance passive sur des sources publiques fictives » : tu y apprendras à inventorier des indices utiles, puis à décider lesquels garder, masquer ou écarter dans un livrable responsable. Termine ensuite par le quiz."),
    reference("cnilRgpd"),
    reference("cnilConservation"),
    reference("cnilGuideSecurite"),
    reference("owaspVulnDisclosure"),
    reference("securityTxtSite"),
  ],
  quiz: {
    title: "Quiz : OSINT responsable",
    questions: [
      questions.choice("Quel principe décrit le mieux une collecte OSINT responsable ?", ["Conserver tout ce qui est public pour ne rien rater", "Collecter le minimum utile au périmètre, puis masquer ou purger le reste", "Publier les indices trouvés pour obtenir une validation externe", "Créer un compte si un document public semble incomplet"], 1, "La bonne approche consiste à limiter la collecte à ce qui sert réellement la mission, puis à masquer ou supprimer le surplus. La mauvaise réponse la plus tentante est la conservation intégrale : elle rassure à court terme, mais augmente le risque juridique et la mauvaise qualité du livrable.", "facile"),
      questions.choice("Pourquoi une adresse email nominative publique doit-elle souvent être masquée dans le rapport ?", ["Parce qu’une donnée publique ne demande jamais de source", "Parce qu’elle peut identifier une personne sans être nécessaire en clair pour démontrer le constat", "Parce qu’un PDF public est forcément faux", "Parce qu’elle interdit toute collecte passive"], 1, "Le fait qu’une donnée soit visible publiquement ne signifie pas qu’il faille la recopier en clair dans un rapport. La minimisation et la preuve utile exigent souvent de décrire le problème sans reproduire la donnée complète.", "moyen"),
      questions.multi("Quelles actions restent hors cadre dans une démarche OSINT responsable ? (plusieurs réponses)", ["Contourner un anti-bot pour finir l’inventaire", "Scraper massivement des profils hors périmètre", "Noter la source et la date de collecte", "Franchir un accès protégé pour vérifier une hypothèse"], [0, 1, 3], "Contourner un anti-bot, collecter massivement hors périmètre ou franchir un accès protégé sortent du cadre défensif et proportionné. Noter la source et la date fait au contraire partie d’une méthode saine et vérifiable.", "difficile"),
      questions.tf("Une donnée personnelle publique peut être utile à une mission, mais cela ne la rend pas libre de republication intégrale.", true, "Vrai : la publicité initiale d’une information n’efface ni la minimisation, ni le besoin d’en connaître, ni la prudence de rédaction. Un bon rapport préfère des formulations sobres et masquées quand la preuve complète n’est pas nécessaire.", "moyen"),
    ],
  },
};

const scanPortsLesson: NewLesson = {
  key: "pt-scan-ports",
  title: "Scanner des ports avec Nmap : concepts, options et lecture d’une sortie",
  summary: "Tu apprends à lire un scan de ports autorisé, à comprendre les options Nmap les plus courantes et à interpréter une sortie sans la transformer en preuve d’attaque.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("distinguer les états de ports, expliquer les options Nmap les plus courantes, lire les formats de sortie, puis résumer ce qu’un scan autorisé montre vraiment."),
    prerequisites("connaître le cadre d’autorisation d’un test, savoir ce qu’est un port réseau et avoir déjà vu la reconnaissance passive."),
    scenario("Koffi reçoit les résultats d’un scan autorisé sur un hôte de démonstration en plage de documentation. Il ne doit pas « faire plus », mais comprendre ce que le scan dit déjà : quels ports semblent ouverts, lesquels sont filtrés, quel format de sortie sera le plus utile pour l’analyse et quelles limites garder en tête avant toute suite."),
    videoSlot("Lire un scan Nmap sans surinterpréter"),
    text("Un scan de ports est une observation active : il interagit avec la cible et exige donc une autorisation écrite ou un laboratoire personnel. Nmap reste l’outil de référence le plus souvent cité pour cette lecture. Ce cours n’enseigne pas à contourner des défenses ni à « se cacher » d’elles. Il t’apprend à lire ce qu’un scan autorisé renvoie, à choisir un format de sortie utile et à décrire proprement les limites du résultat."),
    schema([
      "États de ports à connaître",
      "",
      "open             : un service semble répondre",
      "closed           : pas de service, mais l’hôte répond",
      "filtered         : un filtre bloque ou masque la réponse",
      "unfiltered       : port accessible, état applicatif incertain",
      "open|filtered    : Nmap ne tranche pas",
      "closed|filtered  : Nmap ne tranche pas",
    ].join("\n")),
    text("Quelques options reviennent souvent. « -sS » désigne le SYN scan, « -sT » le scan en connexion complète, « -sU » l’UDP, « -sn » la découverte d’hôtes sans scan de ports, et « -Pn » la supposition qu’un hôte est actif quand la découverte ne répond pas comme prévu. « -p » limite les ports, « --top-ports » cible les plus fréquents, « -sV » tente une détection de version, « -O » active la détection d’OS, « -sC » équivaut à « --script=default », « -n » évite la résolution DNS, « --reason » affiche la raison d’un état de port, et « -A » active en plus la détection d’OS, la détection de version, les scripts par défaut et le traceroute, donc davantage de bruit. Tout cela reste à manier dans un périmètre autorisé."),
    schema([
      "Formats de sortie utiles",
      "",
      "-oN : lisible pour l’humain",
      "-oG : greppable, pratique pour des filtres",
      "-oX : XML, pratique pour des traitements",
      "-oA demo : écrit les trois formats",
      "",
      "Un format n’ajoute pas de preuve, il change la lecture",
    ].join("\n")),
    text("Démonstration guidée : vérifie d’abord « node --version ». La démonstration ci-dessous lit une sortie fictive au format réel, inspirée de la documentation officielle. Le script Node.js la parcourt, compte les ports par état et résume les services vus. Si tu utilises ensuite Nmap chez toi, fais-le uniquement sur ton propre laboratoire ou sur une cible explicitement autorisée, par exemple un environnement d’entraînement prévu pour cela."),
    code([
      "// sortie Nmap fictive au format réel, à lire seulement",
      "// commande de démonstration, à n’utiliser que sur un laboratoire ou une cible autorisée",
      "// nmap -sS -sV --top-ports 10 192.0.2.10",
      "// exemple de sortie (valeurs fictives)",
      "// Starting Nmap 7.991 ( https://nmap.org ) at 2026-03-10 09:15 UTC",
      "// Nmap scan report for 192.0.2.10",
      "// Host is up (0.021s latency).",
      "// Not shown: 7 closed tcp ports (reset)",
      "// PORT    STATE    SERVICE VERSION",
      "// 22/tcp  open     ssh     OpenSSH 9.6",
      "// 80/tcp  open     http    nginx 1.24.0",
      "// 111/tcp filtered rpcbind",
      "// Nmap done: 1 IP address (1 host up) scanned in 1.42 seconds",
      "",
      "// fichier demo-scan-ports.cjs",
      "const lines = [",
      "  '22/tcp  open     ssh     OpenSSH 9.6',",
      "  '80/tcp  open     http    nginx 1.24.0',",
      "  '111/tcp filtered rpcbind',",
      "];",
      "const rows = lines.map((line) => {",
      "  const parts = line.trim().split(/\\s+/);",
      "  return { port: parts[0], state: parts[1], service: parts[2] };",
      "});",
      "const counts = rows.reduce((acc, row) => {",
      "  acc[row.state] = (acc[row.state] || 0) + 1;",
      "  return acc;",
      "}, {});",
      "console.log(JSON.stringify({ counts, rows }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"counts\": {",
      "//     \"open\": 2,",
      "//     \"filtered\": 1",
      "//   },",
      "//   \"rows\": [",
      "//     {",
      "//       \"port\": \"22/tcp\",",
      "//       \"state\": \"open\",",
      "//       \"service\": \"ssh\"",
      "//     },",
      "//     {",
      "//       \"port\": \"80/tcp\",",
      "//       \"state\": \"open\",",
      "//       \"service\": \"http\"",
      "//     },",
      "//     {",
      "//       \"port\": \"111/tcp\",",
      "//       \"state\": \"filtered\",",
      "//       \"service\": \"rpcbind\"",
      "//     }",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : ce scan fictif te permet d’écrire qu’un service SSH et un service HTTP semblent répondre, et qu’un port lié à « rpcbind » paraît filtré. Tu ne peux pas écrire qu’un serveur est vulnérable parce que Nmap a deviné une bannière, ni conclure qu’un port absent de la liste est inexistant partout. La bonne formulation reste : « sur cette cible autorisée, à cette date, avec ces options, Nmap a observé… »."),
    mistakes("traiter un scan comme une preuve absolue ; oublier que « filtered » décrit surtout la visibilité depuis ta position ; croire que « --top-ports » est exhaustif ; utiliser « -A » par habitude sans mesurer le bruit supplémentaire."),
    safety("tout scan de ports doit rester dans un cadre autorisé. Réduire l’impact ne veut pas dire enseigner l’évasion : tu limites le périmètre, la cadence et les options au besoin convenu, puis tu t’arrêtes si la stabilité paraît menacée."),
    takeaway("un scan Nmap décrit ce qu’il observe depuis une position donnée, avec des options données. Lire correctement les états, les formats et les limites vaut mieux que lancer plus d’options sans raison."),
    practice("Travaille dans « TP 3 : lire les résultats d’un scan réseau » : tu y liras des sorties Nmap au format normal, greppable et XML pour compter les services et repérer ceux qui ne devraient pas être ouverts. Termine ensuite par le quiz."),
    reference("nmapSite"),
    reference("nmapBriefOptions"),
    reference("nmapScanTechniques"),
    reference("nmapHostDiscovery"),
    reference("nmapOutputFormats"),
    reference("nmapPerformance"),
    reference("nmapLegalIssues"),
  ],
  quiz: {
    title: "Quiz : lecture d’un scan Nmap",
    questions: [
      questions.choice("Que signifie d’abord l’état « filtered » dans une sortie Nmap ?", ["Qu’un service est sûrement compromis", "Qu’un filtre ou un équipement masque suffisamment la réponse pour empêcher une conclusion nette", "Que le port est forcément ouvert mais lent", "Que la version du service est inconnue"], 1, "L’état « filtered » décrit ce que Nmap n’arrive pas à voir clairement depuis sa position, souvent à cause d’un filtrage réseau. La réponse tentante est l’ouverture implicite, alors que Nmap documente justement une incertitude d’observation.", "facile"),
      questions.choice("À quoi sert surtout « -oA demo » ?", ["À réduire automatiquement le bruit du scan", "À écrire simultanément les sorties normale, greppable et XML avec le même préfixe", "À forcer la détection de version sur tous les ports", "À remplacer l’autorisation écrite"], 1, "« -oA » sert à produire plusieurs formats de sortie à partir du même scan, ce qui aide l’analyse et l’archivage. L’erreur la plus tentante est de lui prêter une fonction technique sur le trafic, alors qu’il agit sur la sortie, pas sur la méthode de scan.", "moyen"),
      questions.multi("Parmi ces descriptions d’options Nmap, lesquelles sont exactes ? (plusieurs réponses)", ["« -sS » : scan TCP de type SYN", "« -sn » : découverte d’hôtes sans scan de ports", "« -Pn » : traiter les hôtes comme actifs, sans découverte préalable", "« --top-ports 100 » : ne scanner que des ports UDP"], [0, 1, 2], "Ces trois options font partie du vocabulaire courant de lecture Nmap : scan SYN, découverte d’hôtes seule et supposition d’hôte actif. « --top-ports 100 » choisit les 100 ports les plus fréquents du fichier de référence de Nmap, en TCP par défaut : ce n’est pas une option réservée à UDP. Connaître ces options ne dispense jamais du cadre autorisé ni de la prudence d’interprétation.", "difficile"),
      questions.tf("Voir « 80/tcp open http » suffit à prouver qu’une application web est vulnérable.", false, "Faux : la sortie indique qu’un service HTTP semble répondre sur le port 80. Elle ne prouve ni la présence d’une faiblesse, ni l’exploitabilité d’une version, ni la criticité métier. Elle sert d’inventaire technique, pas de verdict final.", "moyen"),
    ],
  },
};

const enumerationServicesLesson: NewLesson = {
  key: "pt-enumeration-services",
  title: "Énumérer les services : bannières, versions et protocoles courants",
  summary: "Tu apprends à lire des bannières et des en-têtes, à reconnaître quelques services courants, puis à dire ce qu’une version détectée suggère sans la transformer en vulnérabilité prouvée.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("reconnaître des services courants, interpréter une bannière ou un en-tête HTTP, distinguer un indice de version d’une preuve de faille, puis rédiger un tableau d’énumération prudent."),
    prerequisites("savoir lire une sortie de scan de ports et connaître les bases des ports TCP/UDP et des protocoles les plus répandus."),
    scenario("Awa relit les résultats d’un scan autorisé sur un hôte de démonstration. Elle voit SSH, HTTP, HTTPS et SMTP, plus quelques en-têtes web. Son travail n’est pas de lancer un exploit, mais de décrire ce que chaque service suggère, ce qu’il faut confirmer ensuite et ce qu’il serait abusif d’affirmer trop tôt."),
    videoSlot("Lire une bannière sans en faire un verdict"),
    text("L’énumération des services commence par une idée simple : un port ouvert ne dit pas tout, mais il raconte déjà quelque chose. Le couple « port + protocole + bannière » aide à reconnaître un service probable, à deviner sa fonction et parfois à apercevoir une version. Tu peux ainsi distinguer un SSH d’administration, un front HTTP, un SMTP de messagerie ou un DNS publié. En revanche, tu dois résister à la tentation de conclure trop vite qu’une version observée équivaut à une CVE démontrée."),
    schema([
      "Quelques repères utiles",
      "",
      "22/tcp   -> SSH",
      "25/tcp   -> SMTP",
      "53/tcp,udp -> DNS",
      "80/tcp   -> HTTP",
      "443/tcp  -> HTTPS",
      "3389/tcp -> RDP",
      "",
      "Repère ne veut pas dire certitude absolue",
    ].join("\n")),
    text("Une bannière peut venir directement du service, d’un reverse proxy, d’un équipement intermédiaire ou d’une chaîne forgée pour rester vague. Nmap avec « -sV » essaie d’affiner la détection à partir de signatures ; « curl -I » lit des en-têtes HTTP ; une ligne de certificat, un titre HTML ou une réponse SMTP peuvent ajouter des indices. Tout cela t’aide à formuler des hypothèses de travail : « service web semblant parler comme Nginx », « serveur SSH de type OpenSSH », « passerelle mail exposée ». Cela ne remplace ni une validation dans le bon cadre, ni une lecture du contexte métier."),
    schema([
      "Ce que tu peux dire / ne pas dire",
      "",
      "Tu peux dire :",
      "- service probable",
      "- bannière observée",
      "- version annoncée ou détectée",
      "",
      "Tu ne peux pas dire :",
      "- faille prouvée",
      "- impact métier certain",
      "- pile complète garantie",
    ].join("\n")),
    text("Le piège classique est de confondre précision apparente et vérité opérationnelle. « OpenSSH 9.6 » dans une sortie fictive bien formatée reste une détection. L’administrateur peut avoir appliqué des correctifs sans changer la bannière, ou un frontal peut cacher plusieurs services derrière le même en-tête. Ta mission d’énumération consiste donc à écrire un tableau sobre : service observé, ce qu’on peut raisonnablement dire, ce qu’il faudra confirmer plus tard si le cadre le demande."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script ci-dessous lit quatre lignes de services et trois extraits d’en-têtes HTTP fictifs, puis assemble un tableau local « port / protocole / preuve / commentaire ». Les valeurs sont inventées, mais le raisonnement est celui que tu dois suivre avant toute conclusion plus forte. Si tu emploies ensuite « curl -I », garde-le pour ton laboratoire ou pour une cible explicitement autorisée."),
    code([
      "// fichier demo-enumeration-services.cjs",
      "const ports = [",
      "  { port: '22/tcp', service: 'ssh', proof: 'OpenSSH 9.6' },",
      "  { port: '80/tcp', service: 'http', proof: 'Server: nginx' },",
      "  { port: '443/tcp', service: 'https', proof: 'server: nginx' },",
      "  { port: '25/tcp', service: 'smtp', proof: '220 mail.example ESMTP' },",
      "];",
      "const headersByPort = {",
      "  '80/tcp': ['Server: nginx', 'X-Content-Type-Options: nosniff'],",
      "  '443/tcp': ['server: nginx'],",
      "};",
      "const rows = ports.map((item) => ({",
      "  port: item.port,",
      "  protocole: item.port.split('/')[1],",
      "  service: item.service,",
      "  preuve: [...new Set([item.proof].concat(headersByPort[item.port] || []))].join(' | '),",
      "  commentaire: item.service === 'http'",
      "    ? 'front web probable, version a confirmer' : item.service === 'https'",
      "    ? 'service web chiffre probable, certificat et version a confirmer' : item.service === 'ssh'",
      "    ? 'acces d administration probable' : 'service de messagerie probable',",
      "}));",
      "console.log(JSON.stringify(rows, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// [",
      "//   {",
      "//     \"port\": \"22/tcp\",",
      "//     \"protocole\": \"tcp\",",
      "//     \"service\": \"ssh\",",
      "//     \"preuve\": \"OpenSSH 9.6\",",
      "//     \"commentaire\": \"acces d administration probable\"",
      "//   },",
      "//   {",
      "//     \"port\": \"80/tcp\",",
      "//     \"protocole\": \"tcp\",",
      "//     \"service\": \"http\",",
      "//     \"preuve\": \"Server: nginx | X-Content-Type-Options: nosniff\",",
      "//     \"commentaire\": \"front web probable, version a confirmer\"",
      "//   },",
      "//   {",
      "//     \"port\": \"443/tcp\",",
      "//     \"protocole\": \"tcp\",",
      "//     \"service\": \"https\",",
      "//     \"preuve\": \"server: nginx\",",
      "//     \"commentaire\": \"service web chiffre probable, certificat et version a confirmer\"",
      "//   },",
      "//   {",
      "//     \"port\": \"25/tcp\",",
      "//     \"protocole\": \"tcp\",",
      "//     \"service\": \"smtp\",",
      "//     \"preuve\": \"220 mail.example ESMTP\",",
      "//     \"commentaire\": \"service de messagerie probable\"",
      "//   }",
      "// ]",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si ton tableau indique « 80/tcp, http, Server: nginx », tu peux écrire qu’un front web semble répondre et que la bannière parle comme Nginx. Tu ne dois pas écrire « Nginx 1.24.0 vulnérable » sans validation supplémentaire, parce qu’une bannière peut être partielle, trompeuse ou corrigée hors version. La bonne énumération dit ce qui est observé et ce qui reste à confirmer."),
    mistakes("prendre une bannière pour une preuve de faille ; oublier que « -A » augmente le bruit ; déduire la pile complète d’un seul en-tête ; écrire qu’une version détectée suffit à conclure à une CVE."),
    safety("l’énumération reste une activité active dès qu’elle interroge un service réel. Tu la fais donc dans un laboratoire, une plateforme d’entraînement légale ou un périmètre couvert par une autorisation écrite, en limitant les requêtes au besoin convenu."),
    takeaway("une bannière, un en-tête ou une version détectée sont des indices utiles, pas des verdicts. L’énumération sert à décrire un service observable et à préparer une suite prudente, jamais à gonfler artificiellement une preuve."),
    practice("Travaille dans « TP 3 : lire les résultats d’un scan réseau » : tu y apprendras à reconnaître des services, à lire des versions détectées et à distinguer ce qu’une bannière permet d’écrire ou non dans une note technique. Termine ensuite par le quiz."),
    reference("nmapVersionDetection"),
    reference("nseCategories"),
    reference("nmapBriefOptions"),
    reference("curlManpage"),
    reference("ianaPorts"),
  ],
  quiz: {
    title: "Quiz : énumération des services",
    questions: [
      questions.choice("Que permet surtout une bannière de service bien lue ?", ["Formuler une hypothèse raisonnable sur le service observable", "Prouver automatiquement une vulnérabilité critique", "Remplacer le périmètre du contrat", "Identifier le propriétaire juridique du domaine"], 0, "Une bannière sert d’indice technique sur le service et parfois sur sa version ou sa fonction. La mauvaise réponse la plus tentante est la preuve de faille : lire une bannière ne démontre ni exploitabilité ni impact métier à elle seule.", "facile"),
      questions.choice("Pourquoi la détection de version de Nmap doit-elle être relue avec prudence ?", ["Parce qu’elle ne fonctionne jamais sur HTTP", "Parce qu’elle s’appuie sur des signatures et des réponses observées, qui peuvent être partielles ou masquées", "Parce qu’elle n’utilise pas le réseau", "Parce qu’elle force toujours l’ouverture du port"], 1, "La détection de version repose sur des observations utiles, mais pas absolues. Un proxy, un frontal ou une bannière générique peuvent limiter la précision. L’erreur tentante est de croire qu’une version détectée vaut immédiatement preuve complète.", "moyen"),
      questions.multi("Parmi les formulations suivantes, lesquelles restent honnêtes après une énumération prudente ? (plusieurs réponses)", ["« Service SSH probablement exposé pour l’administration »", "« Front web semblant parler comme Nginx »", "« CVE confirmée grâce à l’en-tête Server »", "« Version annoncée ou détectée à confirmer dans le cadre autorisé »"], [0, 1, 3], "Les formulations prudentes décrivent l’observation, la fonction probable et le besoin éventuel de confirmation. Dire qu’une CVE est confirmée à partir d’un simple en-tête ferait justement disparaître la nuance essentielle entre indice de version et faiblesse prouvée.", "difficile"),
      questions.tf("Un port 25/tcp observé comme SMTP peut correspondre à un service de messagerie sans indiquer, à lui seul, si l’organisation l’expose volontairement à Internet.", true, "Vrai : le protocole probable donne une piste fonctionnelle, mais pas le contexte métier complet ni la légitimité de l’exposition. Il faut ensuite recouper avec le périmètre, l’architecture et les règles d’engagement pour interpréter correctement cette présence.", "moyen"),
    ],
  },
};

const discretionImpactLesson: NewLesson = {
  key: "pt-discretion-impact",
  title: "Impact, bruit et prudence : tester sans casser",
  summary: "Tu apprends à réduire l’impact d’un test autorisé, à estimer son bruit et à décider quand ralentir, reporter ou arrêter pour protéger la disponibilité.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("estimer le volume d’un test, expliquer les profils de temporisation Nmap, distinguer réduction d’impact et évasion, puis décider quand ralentir, reporter ou arrêter."),
    prerequisites("avoir compris le cadrage d’une mission et savoir lire les options courantes d’un scan de ports autorisé."),
    scenario("Kwame dispose d’une fenêtre de test autorisée pour un environnement de démonstration. Le client a rappelé que la disponibilité prime, qu’un équipement ancien supporte mal les pics de requêtes et qu’un contact d’urgence doit être prévenu au moindre doute. Kwame doit choisir une approche mesurée, calculer le volume approximatif du test et savoir s’arrêter avant de provoquer un incident."),
    videoSlot("Réduire l’impact d’un test sans parler d’évasion"),
    text("Dans un test d’intrusion défensif, la discrétion signifie réduire l’impact sur la cible, pas se cacher d’une défense. Tu limites les options au besoin convenu, tu respectes les fenêtres horaires, tu surveilles les signes d’instabilité et tu préviens le contact prévu si quelque chose tourne mal. Un scan plus rapide n’est pas « meilleur » s’il brouille la lecture, déclenche trop d’alertes ou fatigue un équipement fragile."),
    schema([
      "Décision simple avant un test actif",
      "",
      "périmètre clair ?      oui / non",
      "fenêtre adaptée ?      oui / non",
      "volume acceptable ?    oui / non",
      "équipement fragile ?   oui / non",
      "",
      "Si non ou doute : réduire, reporter ou arrêter",
    ].join("\n")),
    text("Nmap propose des profils de temporisation de « -T0 » à « -T5 », nommés paranoid, sneaky, polite, normal, aggressive et insane. La documentation précise que « -T3 » est le réglage par défaut. Dans ce parcours, tu les lis seulement comme des compromis vitesse-fiabilité-impact : les profils pensés pour l’évasion sortent du cadre pédagogique. « -T4 » ou « -T5 » ne sont pas des badges de compétence : ils augmentent le bruit et le risque d’erreur ou de perturbation. À l’inverse, des options plus sobres, un sous-ensemble de ports et une sortie propre servent mieux une mission réelle quand la disponibilité compte."),
    schema([
      "Réduire l’impact",
      "",
      "moins d’hôtes",
      "moins de ports",
      "fenêtre plus calme",
      "cadence plus douce",
      "arrêt si instabilité",
      "",
      "Ce n’est pas de l’évasion",
    ].join("\n")),
    text("Les politiques cloud rappellent aussi cette prudence. AWS et Microsoft autorisent certains tests d’intrusion, mais encadrent fortement ce qui touche à la disponibilité, au déni de service, aux tiers ou aux tenants qui ne t’appartiennent pas. Tu ne transformes donc jamais une règle de prudence en recette pour passer sous un radar : tu documentes le volume prévu, les conditions d’arrêt et le contact d’escalade, puis tu t’y tiens."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Le script suivant estime un volume simple de sondes à partir d’un nombre d’hôtes, de ports, d’essais et d’une cadence choisie. Il ne remplace pas l’expérience d’un environnement réel, mais il t’aide à justifier un choix sobre avant de lancer un test autorisé. Tout reste local et fictif."),
    code([
      "// fichier demo-discretion-impact.cjs",
      "const scenarios = [",
      "  { name: 'fenetre sobre', hosts: 2, ports: 100, attemptsPerPort: 1, probesPerMinute: 600 },",
      "  { name: 'fenetre tendue', hosts: 5, ports: 1000, attemptsPerPort: 2, probesPerMinute: 2400 },",
      "];",
      "const rows = scenarios.map((item) => {",
      "  const probes = item.hosts * item.ports * item.attemptsPerPort;",
      "  const minutes = +(probes / item.probesPerMinute).toFixed(2);",
      "  return {",
      "    name: item.name,",
      "    probes,",
      "    minutes,",
      "    action: probes > 5000 ? 'reduire_ou_reporter' : 'acceptable_avec_surveillance',",
      "  };",
      "});",
      "console.log(JSON.stringify(rows, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// [",
      "//   {",
      "//     \"name\": \"fenetre sobre\",",
      "//     \"probes\": 200,",
      "//     \"minutes\": 0.33,",
      "//     \"action\": \"acceptable_avec_surveillance\"",
      "//   },",
      "//   {",
      "//     \"name\": \"fenetre tendue\",",
      "//     \"probes\": 10000,",
      "//     \"minutes\": 4.17,",
      "//     \"action\": \"reduire_ou_reporter\"",
      "//   }",
      "// ]",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : le scénario « fenêtre tendue » cumule trop d’hôtes, trop de ports et trop d’essais pour une période sensible. Même si quatre minutes paraissent courtes, dix mille sondes peuvent rester excessives pour l’équipement ou la politique du client. La bonne décision est donc de réduire le périmètre du test actif, de choisir moins de ports, ou de reporter à une fenêtre plus calme. La discrétion utile est une discipline de réduction d’impact, pas une compétition de furtivité."),
    mistakes("confondre discrétion et évasion ; utiliser un profil agressif par réflexe ; oublier les règles spécifiques des clouds ou des tiers ; continuer malgré un signe d’instabilité parce que « la fenêtre est courte »."),
    safety("si la stabilité, l’intégrité métier ou la sécurité des données paraissent menacées, tu t’arrêtes et tu préviens le contact prévu. Tu ne proposes jamais de déni de service, d’évasion d’IDS ou de saturation « pour voir », même dans un environnement autorisé."),
    takeaway("un test responsable se mesure autant par ce qu’il n’abîme pas que par ce qu’il découvre. Réduire le périmètre, la cadence et les options au besoin convenu protège la cible, le testeur et la qualité du résultat."),
    practice("Travaille dans « TP 3 : lire les résultats d’un scan réseau » : le laboratoire ne te fait pas lancer un scan, mais il t’apprend à relire un résultat et à décider si son périmètre, son volume ou sa prudence paraissent adaptés. Termine ensuite par le quiz."),
    reference("nmapPerformance"),
    reference("nmapTimingTemplates"),
    reference("nmapLegalIssues"),
    reference("awsPentestPolicy"),
    reference("azurePentest"),
    reference("msrcPentestRules"),
  ],
  quiz: {
    title: "Quiz : impact et prudence",
    questions: [
      questions.choice("Dans ce parcours, que signifie parler de discrétion pendant un test autorisé ?", ["Réduire l’impact et le bruit sur la cible, pas contourner une défense", "Masquer systématiquement toutes les traces du test", "Augmenter la cadence avant que quelqu’un ne voie le trafic", "Tester d’abord, prévenir ensuite"], 0, "Ici, la discrétion reste une notion de maîtrise de l’impact : moins de bruit, moins de charge, plus de prévisibilité. La mauvaise réponse la plus tentante est le masquage des traces, justement exclu du cadre pédagogique et éthique du parcours.", "facile"),
      questions.choice("Pourquoi un profil de temporisation plus agressif n’est-il pas automatiquement un meilleur choix ?", ["Parce qu’il peut augmenter le bruit, la charge et l’incertitude de lecture", "Parce qu’il désactive toujours la sortie XML", "Parce qu’il remplace l’autorisation écrite", "Parce qu’il empêche de scanner plus d’un port"], 0, "Une temporisation agressive peut perturber la cible, générer plus d’alertes ou réduire la qualité de l’observation. L’erreur tentante est de confondre vitesse et professionnalisme, alors qu’un test utile doit d’abord rester sûr et lisible.", "moyen"),
      questions.multi("Quelles décisions réduisent réellement l’impact d’un test actif autorisé ? (plusieurs réponses)", ["Limiter le nombre d’hôtes ou de ports au besoin convenu", "Choisir une fenêtre plus calme", "Continuer malgré une instabilité légère pour finir plus vite", "Prévoir une règle d’arrêt et un contact d’escalade"], [0, 1, 3], "Réduire le périmètre, choisir une bonne fenêtre et prévoir un arrêt clair servent la disponibilité et la qualité du test. Continuer malgré une instabilité observée va exactement à l’encontre d’une méthode responsable et peut transformer un contrôle en incident.", "difficile"),
      questions.tf("Les politiques cloud d’AWS ou de Microsoft rappellent qu’un test autorisé n’autorise pas pour autant le déni de service ou le scan de tenants non possédés.", true, "Vrai : une autorisation reste bornée par un périmètre, des règles et des interdictions explicites, notamment sur la disponibilité ou les actifs tiers. Lire ces politiques fait partie de la prudence opérationnelle, surtout quand l’environnement touche des services managés.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c5:4",
    position: 3,
    title: "Reconnaissance passive",
    description: "Ce module t’apprend à documenter une cible autorisée à partir de sources publiques, puis à transformer ces indices en inventaire utile sans franchir le cadre. Critères de réussite : lire correctement DNS, RDAP et CT logs ; produire une carte d’exposition avec ses limites ; minimiser et masquer les données inutiles dans une note d’OSINT.",
    lessons: [osintSourcesLesson, surfaceExposeeLesson, osintEthiqueLesson],
  },
  {
    key: "c5:5",
    position: 4,
    title: "Reconnaissance active et énumération",
    description: "Tu y apprends à lire un scan autorisé, à interpréter des bannières et à choisir une approche de test qui protège la disponibilité. Critères de réussite : expliquer les options Nmap de base et les états de ports ; décrire prudemment un service observé sans surinterpréter sa version ; réduire l’impact d’un test actif et savoir quand ralentir, reporter ou arrêter.",
    lessons: [scanPortsLesson, enumerationServicesLesson, discretionImpactLesson],
  },
];
