import {
  code, example, figure, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const ethernetMac: NewLesson = {
  key: "reseaux-ethernet-mac",
  title: "Ethernet, adresses MAC et table de commutation",
  summary: "Comprendre ce qu’une trame Ethernet transporte, comment un commutateur apprend les adresses MAC et pourquoi ARP reste indispensable dans un LAN.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("identifier les champs essentiels d’une trame Ethernet, distinguer une adresse MAC unicast, multicast et de diffusion, expliquer pas à pas l’apprentissage d’un commutateur, lire une table MAC et interpréter un cache ARP."),
    prerequisites("avoir vu « LAN, WAN, topologies et équipements » et savoir qu’un routeur sépare des réseaux alors qu’un commutateur relie un même LAN."),
    scenario("Fatou relie une imprimante réseau au commutateur de Baobab Tech. L’imprimante reçoit bien une adresse IP, mais le premier envoi de document échoue puis le second passe sans problème. Pour comprendre ce délai, Fatou doit savoir ce que contient une trame Ethernet, comment le commutateur apprend les adresses MAC et pourquoi une requête ARP précède souvent la vraie communication."),
    videoSlot("Ethernet, MAC et ARP : ce que voit vraiment le commutateur"),
    text("Ethernet travaille dans le réseau local. Il transporte des trames, pas des paquets IP directement. Une trame contient au minimum une adresse MAC de destination, une adresse MAC source, un champ EtherType qui annonce le protocole transporté, les données et un contrôle d’erreur appelé FCS. L’adresse MAC fait 48 bits, souvent écrits en six groupes hexadécimaux. Le premier octet porte déjà une information utile : son bit de poids faible indique si l’adresse est unicast ou multicast."),
    figure({
      kind: "packet",
      title: "Trame Ethernet",
      rows: [
        {
          fields: [
            { name: "Destination", size: "6 octets", tone: "blue" },
            { name: "Source", size: "6 octets", tone: "blue" },
            { name: "EtherType", size: "2 octets", tone: "violet" },
            { name: "Données", size: "46-1500 o", weight: 4, tone: "cyan" },
            { name: "FCS", size: "4 octets", tone: "amber" },
          ],
        },
        {
          label: "Types d’adresse MAC",
          fields: [
            { name: "Diffusion", note: "ff:ff:ff:ff:ff:ff", tone: "red" },
            { name: "Multicast", note: "01:00:5e:..:..:..", tone: "amber" },
            { name: "Unicast", note: "08:00:27:..:..:..", tone: "green" },
          ],
        },
      ],
    }),
    text("Un commutateur apprend en observant l’adresse source des trames qui entrent sur ses ports. Si la destination est inconnue, il inonde la trame sur tous les ports du même VLAN, sauf le port d’entrée. Dès qu’une réponse revient, il apprend aussi cette nouvelle source et peut ensuite transmettre en unicast vers le bon port. Sa table MAC vieillit avec le temps : si un équipement se tait longtemps ou change de port, l’entrée finit par disparaître puis sera réapprise. Un commutateur moderne supprime les collisions par port, mais le domaine de diffusion reste celui du VLAN."),
    figure({
      kind: "steps",
      title: "Apprentissage pas à pas",
      numbered: true,
      items: [
        {
          title: "PC-A lance le premier échange",
          text: "PC-A sur Fa0/3 envoie vers une imprimante inconnue. Table MAC : apprend PC-A vers Fa0/3. Action : inondation sur les autres ports du VLAN.",
          tone: "amber",
        },
        {
          title: "L’imprimante répond",
          text: "Réponse depuis Fa0/9. Table MAC : apprend Imprimante vers Fa0/9. Action : réponse unicast vers Fa0/3.",
          tone: "green",
        },
        {
          title: "Échange suivant",
          text: "Action : unicast direct entre Fa0/3 et Fa0/9.",
          tone: "blue",
        },
      ],
    }),
    text("Démonstration guidée : commence par vérifier ce que ton poste sait déjà. Le cache ARP montre les correspondances IP vers MAC apprises récemment. Sur un commutateur Cisco IOS, la commande show mac address-table affiche ce que le commutateur a appris par port et par VLAN. Si une machine n’apparaît pas encore, provoque du trafic local avec un ping vers la passerelle ou vers une imprimante du même LAN, puis relis les deux tables."),
    code("# Windows : voir le cache ARP\narp -a\n\n# exemple de sortie\n# Interface: 192.168.1.25 --- 0xb\n#   Internet Address      Physical Address      Type\n#   192.168.1.1           9c-7b-ef-10-20-30     dynamic\n#   192.168.1.40          08-00-27-aa-bb-40     dynamic\n\n# Cisco IOS : voir la table MAC\nshow mac address-table\n\n# exemple de sortie\n# Vlan    Mac Address       Type        Ports\n# ----    -----------       --------    -----\n#  110    0800.27aa.bb25    DYNAMIC     Fa0/3\n#  110    0800.27aa.bb40    DYNAMIC     Fa0/9"),
    text("ARP fait le lien entre IPv4 et Ethernet dans un LAN. La requête « Qui a 192.168.1.40 ? » part en diffusion, car le poste ne connaît pas encore la MAC correspondante. La réponse revient en unicast et sera gardée quelque temps en cache. Deux risques de sécurité découlent de ce fonctionnement de confiance : l’inondation MAC, qui cherche à remplir la table du commutateur pour le faire diffuser davantage, et l’usurpation ARP, qui envoie une fausse réponse pour détourner du trafic. Les parades existent, comme la sécurité de port, la limitation de MAC apprises ou des mécanismes d’inspection ARP, mais elles n’effacent pas la nécessité de segmenter et de surveiller."),
    example("Exemple corrigé : le poste 192.168.1.25 veut joindre l’imprimante 192.168.1.40. Au premier échange, il ne connaît pas encore sa MAC et diffuse une requête ARP. Le commutateur apprend 08:00:27:aa:bb:25 sur Fa0/3, puis 08:00:27:aa:bb:40 sur Fa0/9 quand l’imprimante répond. Le second envoi n’est plus diffusé : la trame part directement vers Fa0/9. Si tu vois la passerelle 192.168.1.1 dans arp -a mais pas l’imprimante, le problème n’est pas la sortie Internet : c’est que la résolution locale n’a pas encore eu lieu ou qu’elle a échoué."),
    mistakes("confondre adresse MAC et adresse IP, alors qu’elles n’opèrent pas au même niveau ; croire qu’un commutateur lit l’adresse IP pour décider, alors qu’il travaille d’abord avec la MAC ; penser qu’une diffusion traverse les routeurs, alors qu’elle reste dans le VLAN local ; oublier qu’une table MAC vieillit, puis conclure trop vite qu’une entrée absente signifie une panne."),
    safety("ne tente jamais d’ARP spoofing ni d’inondation MAC hors d’un laboratoire ou d’un réseau que tu administres. Ces techniques perturbent vite le service d’autres personnes et laissent des traces faciles à attribuer."),
    takeaway("Ethernet livre des trames dans un LAN, le commutateur apprend les MAC en observant les sources, puis transmet en unicast quand il connaît la destination. ARP relie IPv4 à Ethernet, mais son modèle de confiance impose de segmenter et de surveiller le réseau local."),
    practice("ouvre le laboratoire « TP 2 : VLAN, trunk et routage inter-VLAN pour la PME Kora », identifie quelles MAC apparaissent sur chaque port après les premiers pings, puis termine par le quiz de la leçon."),
    reference("rfc826"),
    reference("msArp"),
    reference("netacad"),
  ],
  quiz: {
    title: "Quiz : Ethernet, MAC et commutation",
    questions: [
      questions.choice("Quel champ d’une trame Ethernet indique le protocole transporté, par exemple IPv4 ou ARP ?", ["Le FCS", "L’EtherType", "Le TTL", "Le port source"], 1, "L’EtherType identifie le contenu de la trame, par exemple 0x0800 pour IPv4 ou 0x0806 pour ARP. Le TTL appartient à IP, les ports source à TCP ou UDP, et le FCS sert seulement au contrôle d’erreur.", "facile"),
      questions.tf("Quand un commutateur reçoit une trame dont la destination MAC lui est inconnue, il la jette immédiatement.", false, "Faux : il commence par apprendre la MAC source sur le port d’entrée, puis il inonde la trame sur les autres ports du même VLAN. Il ne peut pas encore la filtrer, justement parce qu’il ignore où se trouve la destination.", "moyen"),
      questions.multi("Que peux-tu conclure à partir de cet extrait ? Vlan 110, 0800.27aa.bb25 -> Fa0/3 et 0800.27aa.bb40 -> Fa0/9. Plusieurs réponses sont justes.", ["Le commutateur a appris deux adresses MAC dans le VLAN 110", "Fa0/3 et Fa0/9 sont forcément dans des VLAN différents", "Un trafic unicast entre ces deux MAC peut désormais être transmis sans inondation", "Le routeur a forcément créé ces entrées"], [0, 2], "La table montre que deux sources ont été apprises dans le même VLAN sur deux ports distincts. Le commutateur peut donc transmettre directement entre elles. Rien n’indique des VLAN différents, et ces entrées sont créées par le commutateur lui-même, pas par le routeur.", "difficile"),
      questions.choice("Pourquoi une requête ARP est-elle envoyée en diffusion dans un LAN ?", ["Parce que la machine cherche quelle MAC correspond à une IPv4 locale qu’elle ne connaît pas encore", "Parce que le routeur doit apprendre le nom DNS du poste", "Parce qu’un port TCP n’est pas encore ouvert", "Parce que la table MAC du commutateur ne contient aucune entrée"], 0, "ARP sert à découvrir la MAC associée à une IPv4 locale. La diffusion vise tous les hôtes du VLAN pour que seul le bon réponde. DNS et TCP n’interviennent pas ici, et une table MAC vide n’est pas la cause : elle sera justement remplie pendant l’échange.", "moyen"),
    ],
  },
};

const vlanLesson: NewLesson = {
  key: "reseaux-vlan",
  title: "VLAN, ports access et trunk 802.1Q",
  summary: "Segmenter un même commutateur en plusieurs domaines de diffusion, configurer des ports access et trunk, puis vérifier qu’un VLAN n’assure pas à lui seul le routage ni la sécurité complète.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer l’intérêt d’un VLAN, distinguer un port access d’un trunk, configurer des VLAN et un trunk 802.1Q sur Cisco IOS, vérifier les VLAN actifs et repérer les erreurs de segmentation."),
    prerequisites("avoir compris comment un commutateur apprend les adresses MAC et savoir qu’une diffusion Ethernet reste locale au VLAN."),
    scenario("Moussa gère un petit plateau partagé entre la comptabilité, l’accueil et des visiteurs. Tout est branché sur deux commutateurs reliés entre eux. Il veut empêcher les invités de recevoir les diffusions de la comptabilité, sans tirer un réseau physique par service. Pour cela, il doit comprendre comment les VLAN séparent logiquement un LAN et comment un trunk transporte plusieurs VLAN entre deux équipements."),
    videoSlot("VLAN et trunk 802.1Q : segmenter sans recâbler tout le bâtiment"),
    text("Un VLAN est un domaine de diffusion logique. Deux postes branchés sur le même commutateur peuvent donc appartenir à des réseaux différents si leurs ports ne sont pas dans le même VLAN. Cette séparation améliore les performances en limitant les diffusions et renforce l’isolation, mais elle ne remplace pas un pare-feu : pour qu’un VLAN parle à un autre, il faudra plus tard du routage et souvent des ACL."),
    figure({
      kind: "network",
      title: "Bureau Atlas",
      cols: 4,
      rows: 3,
      nodes: [
        { id: "compta", label: "PC compta", sub: "Fa0/2, VLAN 110", icon: "pc", col: 0, row: 0, tone: "blue" },
        { id: "accueil", label: "PC accueil", sub: "Fa0/5, VLAN 120", icon: "pc", col: 0, row: 1, tone: "green" },
        { id: "guest", label: "Wi-Fi invités", sub: "Fa0/8, VLAN 130", icon: "access-point", col: 0, row: 2, tone: "amber" },
        { id: "sw1", label: "SW1", icon: "switch", col: 2, row: 1, tone: "violet" },
        { id: "sw2", label: "SW2", icon: "switch", col: 3, row: 1, tone: "violet" },
      ],
      links: [
        { from: "compta", to: "sw1" },
        { from: "accueil", to: "sw1" },
        { from: "guest", to: "sw1" },
        { from: "sw1", to: "sw2", label: "trunk 802.1Q", style: "thick", arrow: "both", tone: "violet" },
      ],
      caption: "Même câble entre SW1 et SW2, plusieurs VLAN transportés grâce au tag 802.1Q.",
    }),
    text("Sur un port access, les trames entrent et sortent sans étiquette : le poste n’a pas besoin de connaître le VLAN. Sur un trunk, le commutateur ajoute un tag 802.1Q qui contient notamment le VID, un identifiant sur 12 bits. Les valeurs utilisables vont de 1 à 4094. Le VLAN natif, lui, circule sans tag sur de nombreux équipements. C’est pratique, mais dangereux si ses deux extrémités ne sont pas alignées ou si on y laisse du trafic utilisateur. Le VLAN 1 existe par défaut : évite d’y laisser la production et l’administration par habitude."),
    code("vlan 110\n name COMPTA\nvlan 120\n name ACCUEIL\nvlan 130\n name INVITES\nvlan 199\n name NATIVE\n\ninterface FastEthernet0/2\n switchport mode access\n switchport access vlan 110\n\ninterface FastEthernet0/5\n switchport mode access\n switchport access vlan 120\n\ninterface GigabitEthernet0/1\n switchport mode trunk\n switchport trunk native vlan 199\n switchport trunk allowed vlan 110,120,130,199", "text"),
    text("Démonstration guidée : après la configuration, vérifie d’abord l’appartenance des ports avec show vlan brief. Puis vérifie le trunk avec show interfaces trunk. Si un poste de la comptabilité ne joint pas son serveur situé sur l’autre commutateur, regarde trois choses dans cet ordre : le port access du poste, la liste des VLAN autorisés sur le trunk, puis le VLAN natif. Une incohérence sur le trunk suffit à couper un seul VLAN tout en laissant les autres fonctionner."),
    code("show vlan brief\n\n# exemple de sortie\n# VLAN Name                             Status    Ports\n# 110  COMPTA                           active    Fa0/2\n# 120  ACCUEIL                          active    Fa0/5\n# 130  INVITES                          active    Fa0/8\n# 199  NATIVE                           active\n\nshow interfaces trunk\n\n# exemple de sortie\n# Port        Mode         Encapsulation  Status    Native vlan\n# Gi0/1       on           802.1q         trunking  199\n# Port        Vlans allowed on trunk\n# Gi0/1       110,120,130,199", "text"),
    text("Deux risques reviennent souvent. L’usurpation de trunk consiste à faire passer un poste malveillant pour un équipement réseau afin d’obtenir l’accès à plusieurs VLAN. Le double étiquetage exploite surtout un mauvais choix de VLAN natif pour faire sauter une frontière logique. Les parades sont simples à retenir : forcer les ports utilisateurs en mode access, désactiver la négociation de trunk si ton matériel le permet, choisir un VLAN natif inutilisé, limiter strictement les VLAN autorisés et ne jamais croire qu’un VLAN suffit, à lui seul, comme frontière de sécurité."),
    example("Exemple corrigé : un PC du VLAN 110 sur SW1 joint un serveur du VLAN 110 sur SW2 sans routeur, car le trunk transporte le tag 110 jusqu’au second commutateur. En revanche, ce même PC ne joint pas un poste du VLAN 120 tant qu’aucun équipement de couche 3 n’assure le routage entre 110 et 120. Si show interfaces trunk n’affiche que 110,130,199, le VLAN 120 est absent du lien : le problème n’est pas l’adresse IP des postes, mais la liste des VLAN autorisés."),
    mistakes("mettre un poste utilisateur sur un port laissé en trunk, ce qui agrandit inutilement sa surface d’attaque ; oublier switchport mode access avant switchport access vlan, puis croire que le VLAN ne s’applique pas ; garder le VLAN 1 partout par défaut sans plan clair ; croire que deux VLAN séparés sont automatiquement filtrés au niveau 3, alors qu’ils peuvent être routés sans restriction si aucune ACL n’est prévue."),
    safety("segmente pour réduire les risques, mais ne branche ni ne configure jamais un trunk sur un réseau qui ne t’appartient pas. Une erreur de VLAN natif ou de trunk peut exposer du trafic d’autres équipes en quelques secondes."),
    takeaway("un VLAN crée un domaine de diffusion logique. Un port access sert aux postes, un trunk transporte plusieurs VLAN grâce à 802.1Q. Le VLAN améliore l’isolation locale, mais il faut du routage et des règles de filtrage pour contrôler réellement les échanges entre réseaux."),
    practice("ouvre le laboratoire « TP 2 : VLAN, trunk et routage inter-VLAN pour la PME Kora », crée les VLAN, configure les ports access et le trunk, vérifie show vlan brief et show interfaces trunk, puis termine par le quiz de la leçon."),
    reference("netacad"),
    reference("packetTracer"),
  ],
  quiz: {
    title: "Quiz : VLAN, access et trunk",
    questions: [
      questions.choice("Quel énoncé décrit le mieux un port trunk ?", ["Il transporte un seul VLAN sans tag vers un poste utilisateur", "Il transporte plusieurs VLAN entre équipements réseau grâce à 802.1Q", "Il convertit automatiquement un VLAN en adresse IP", "Il bloque toutes les diffusions Ethernet"], 1, "Un trunk transporte plusieurs VLAN entre commutateurs, routeurs ou équipements équivalents en ajoutant un tag 802.1Q aux trames, sauf souvent pour le VLAN natif. Un port access, lui, sert aux postes et reste sans tag.", "facile"),
      questions.choice("Tu lis show interfaces trunk et vois Native vlan 1 sur SW1, mais Native vlan 199 sur SW2. Quel risque ou symptôme est le plus cohérent ?", ["Une incohérence du VLAN natif qui peut casser certains échanges et faciliter des abus", "Le trunk devient automatiquement un port access", "Les VLAN 110 et 120 fusionnent en un seul", "Le routage inter-VLAN se met en place tout seul"], 0, "Un VLAN natif incohérent provoque des comportements imprévisibles et fragilise l’isolation. Le trunk ne devient pas un port access, il ne fusionne pas les VLAN et il n’ajoute aucun routage par magie.", "difficile"),
      questions.multi("Quelles bonnes pratiques réduisent les risques liés aux VLAN ? Plusieurs réponses sont justes.", ["Forcer les ports utilisateurs en mode access", "Limiter les VLAN autorisés sur les trunks", "Choisir un VLAN natif inutilisé pour les postes", "Compter uniquement sur les VLAN pour filtrer le trafic entre services"], [0, 1, 2], "Forcer les ports d’utilisateur en access, limiter les VLAN autorisés et isoler le VLAN natif réduisent fortement les erreurs et les attaques. En revanche, un VLAN seul ne filtre pas le trafic de couche 3 : il faut aussi du routage contrôlé et souvent des ACL.", "moyen"),
      questions.tf("Deux postes dans deux VLAN différents peuvent communiquer directement sans équipement de couche 3.", false, "Faux : ils sont dans deux domaines de diffusion distincts. Sans routeur ou commutateur de niveau 3 pour faire le relais, aucune communication IP normale ne traverse cette frontière logique.", "moyen"),
    ],
  },
};

const routingTableLesson: NewLesson = {
  key: "reseaux-table-routage",
  title: "Comment un routeur décide : table de routage et routes statiques",
  summary: "Lire une table de routage, comprendre le plus long préfixe, ajouter des routes statiques utiles et éviter le piège classique de la route retour manquante.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("lire les champs d’une route, distinguer les routes connectées, locales, statiques et par défaut, appliquer la règle du plus long préfixe, configurer une route statique Cisco IOS et diagnostiquer une route retour absente."),
    prerequisites("avoir vu l’adressage IPv4, les VLAN et le rôle du routeur comme équipement qui relie des réseaux différents."),
    scenario("Nadia administre le routeur du siège de Sahel Services. Il a trois voisins : un routeur qui dessert les agences du nord, un routeur qui dessert l’agence de l’est, et la sortie vers le fournisseur d’accès. Un ping part vers l’agence de l’est, puis plus rien ne revient. Avant de parler de protocoles dynamiques, Nadia doit comprendre comment un routeur choisit une sortie, ce qu’il fait quand plusieurs routes correspondent et pourquoi un aller qui fonctionne ne garantit pas un retour."),
    videoSlot("Table de routage : comment un routeur choisit vraiment le prochain saut"),
    text("Une entrée de table de routage associe un réseau de destination à une action : envoyer vers une interface de sortie ou vers un prochain saut. Elle contient au moins un préfixe, parfois une métrique, souvent une distance administrative et un indicateur d’origine. Sur Cisco IOS, C désigne une route connectée, L une adresse locale d’interface, S une route statique et S* la route par défaut. La règle la plus importante n’est pas « la route la plus proche » mais « le plus long préfixe » : plus le masque est précis, plus il gagne."),
    figure({
      kind: "terminal",
      title: "Table de R1, le routeur du siège",
      lines: [
        { kind: "note", text: "Extrait simplifié" },
        { kind: "out", text: "C   10.1.0.0/16 is directly connected, GigabitEthernet0/0" },
        { kind: "out", text: "L   10.1.0.1/32 is directly connected, GigabitEthernet0/0" },
        { kind: "out", text: "S   10.2.0.0/16 [1/0] via 172.16.1.2" },
        { kind: "out", text: "S   10.2.8.0/24 [1/0] via 172.16.1.6" },
        { kind: "out", text: "S*  0.0.0.0/0 [1/0] via 172.16.1.10" },
      ],
    }),
    text("Si le paquet vise 10.2.8.130, trois routes correspondent : 10.2.0.0/16, 10.2.8.0/24 et la route par défaut. Pourtant le routeur choisit 10.2.8.0/24, car /24 est plus précis que /16 et infiniment plus précis que /0. Un paquet pour 10.2.3.7 n’a que deux candidates, le /16 et la route par défaut, et le /16 gagne. C’est ainsi qu’on garde une route générale pour tout un bloc, avec une exception fine pour un sous-réseau qui passe par un autre routeur. Une autre distinction utile : une route pointant vers un prochain saut convient bien sur un réseau multi-accès, alors qu’une route pointant directement vers l’interface est naturelle sur une liaison point à point."),
    figure({
      kind: "network",
      title: "Les voisins de R1",
      cols: 4,
      rows: 4,
      nodes: [
        { id: "lan", label: "LAN siège", sub: "10.1.0.0/16", icon: "network", col: 0, row: 1, tone: "blue" },
        { id: "r1", label: "R1", icon: "router", col: 1, row: 1, tone: "violet" },
        { id: "r2", label: "R2", sub: "agences du nord 10.2.0.0/16", icon: "router", col: 3, row: 0, tone: "green" },
        { id: "r3", label: "R3", sub: "agence de l’est 10.2.8.0/24", icon: "router", col: 3, row: 1, tone: "green" },
        { id: "isp", label: "Fournisseur d’accès", sub: "Internet", icon: "internet", col: 3, row: 2, tone: "amber" },
      ],
      links: [
        { from: "lan", to: "r1", label: "10.1.0.0/16", tone: "blue" },
        { from: "r1", to: "r2", label: "172.16.1.0/30", style: "thick", arrow: "both", tone: "violet" },
        { from: "r1", to: "r3", label: "172.16.1.4/30", style: "thick", arrow: "both", tone: "violet" },
        { from: "r1", to: "isp", label: "172.16.1.8/30", style: "thick", arrow: "both", tone: "violet" },
      ],
      caption: "Sur chaque lien /30, R1 prend l’adresse de rang 1 ; R2 = 172.16.1.2, R3 = 172.16.1.6, fournisseur = 172.16.1.10.",
    }),
    text("Démonstration guidée : sur Cisco IOS, ajoute d’abord une route statique vers chaque réseau distant, puis lis show ip route. Vérifie ensuite un aller et un retour. Si R1 sait aller vers 10.2.8.0/24 mais que R3 ignore comment revenir vers 10.1.0.0/16, le ping échouera malgré une route correcte d’un côté. Ce symptôme trompe souvent les débutants, qui corrigent la mauvaise machine."),
    code("ip route 10.2.0.0 255.255.0.0 172.16.1.2\nip route 10.2.8.0 255.255.255.0 172.16.1.6\nip route 0.0.0.0 0.0.0.0 172.16.1.10\n\nshow ip route\n\n# exemple de sortie\n# Gateway of last resort is 172.16.1.10 to network 0.0.0.0\n# C    10.1.0.0/16 is directly connected, GigabitEthernet0/0\n# S    10.2.0.0/16 [1/0] via 172.16.1.2\n# S    10.2.8.0/24 [1/0] via 172.16.1.6\n# S*   0.0.0.0/0 [1/0] via 172.16.1.10", "text"),
    text("Les routes statiques sont sobres, lisibles et sûres à petite échelle. Elles conviennent très bien à un petit site distant, à une sortie Internet unique ou à un réseau de secours. Dès que le nombre de préfixes grimpe, pense au résumé : deux réseaux adjacents comme 10.2.4.0/24 et 10.2.5.0/24 peuvent être annoncés ensemble en 10.2.4.0/23, ce qui allège les tables et la documentation. Le résumé ne doit jamais englober des réseaux inexistants que tu n’es pas prêt à acheminer."),
    example("Exemple corrigé : la destination 10.2.8.130 appartient à 10.2.8.0/24, à 10.2.0.0/16 et bien sûr à 0.0.0.0/0. Le routeur choisit donc 10.2.8.0/24, car c’est le plus long préfixe : le paquet part vers R3 (172.16.1.6) et non vers R2. La destination 10.2.3.7 n’appartient pas au /24 : elle suit le /16 vers R2. Autre calcul utile : 10.2.4.0/24 et 10.2.5.0/24 se résument proprement en 10.2.4.0/23. Si tu résumais trop large, par exemple en 10.2.0.0/16, tu masquerais peut-être une panne ou enverrais du trafic vers une zone qui ne l’attend pas."),
    mistakes("croire que la route par défaut l’emporte toujours, alors qu’elle ne sert qu’en dernier recours ; oublier la route retour sur le routeur opposé ; mélanger prochain saut et interface de sortie sans comprendre le type de lien ; résumer trop large et perdre en précision de diagnostic."),
    safety("n’ajoute des routes que sur des équipements que tu administres. Une mauvaise route statique peut détourner tout le trafic d’un site, ou créer une boucle difficile à repérer quand plusieurs techniciens interviennent."),
    takeaway("un routeur choisit d’abord le plus long préfixe. Les routes C, L, S et S* racontent l’origine des chemins. Les routes statiques sont excellentes quand le réseau reste simple, à condition de penser à l’aller, au retour et au bon niveau de résumé."),
    practice("ouvre le laboratoire « TP 3 : relier trois sites avec des routes statiques », ajoute les routes réseau par réseau, vérifie show ip route et les pings dans les deux sens, puis termine par le quiz de la leçon."),
    reference("rfc791"),
    reference("netacad"),
    reference("packetTracer"),
  ],
  quiz: {
    title: "Quiz : table de routage et routes statiques",
    questions: [
      questions.choice("Quelle route gagne si un paquet vers 10.2.8.130 correspond à 10.2.0.0/16, 10.2.8.0/24 et 0.0.0.0/0 ?", ["0.0.0.0/0, car elle est par défaut", "10.2.0.0/16, car elle a été créée en premier", "10.2.8.0/24, car c’est le préfixe le plus précis", "Aucune, le routeur hésite"], 2, "Le routeur applique la règle du plus long préfixe. La route /24 est plus spécifique que /16 et bien plus spécifique que /0. L’ordre de création n’est pas le critère décisif ici.", "moyen"),
      questions.tf("Si le ping part bien du site A vers le site B, le site B saura forcément répondre.", false, "Faux : le retour exige sa propre route. Une route correcte à l’aller ne garantit pas que le second routeur connaisse le chemin inverse, et c’est une cause très classique d’échec de ping.", "moyen"),
      questions.choice("Dans cet extrait, que signifie la lettre C devant 10.1.0.0/16 ?", ["Une route créée par un protocole de convergence", "Une route connectée directement à une interface du routeur", "Une route chiffrée", "Une route copiée depuis un autre équipement"], 1, "Sur Cisco IOS, C signifie connected, donc un réseau directement relié à une interface active du routeur. Ce n’est ni une route dynamique ni une route importée d’un autre équipement.", "facile"),
      questions.multi("Quelles affirmations sur les routes statiques sont justes ? Plusieurs réponses sont correctes.", ["Elles sont simples à comprendre dans un petit réseau", "Elles suppriment automatiquement le besoin d’une route retour", "Elles peuvent servir pour une route par défaut", "Elles demandent plus d’entretien quand le nombre de réseaux augmente"], [0, 2, 3], "Les routes statiques sont très lisibles et conviennent bien aux petits réseaux ou à une sortie par défaut. En revanche, elles ne créent pas de route retour toutes seules et deviennent vite lourdes à maintenir quand la topologie grandit.", "difficile"),
    ],
  },
};

const interVlanLesson: NewLesson = {
  key: "reseaux-inter-vlan",
  title: "Routage inter-VLAN : un routeur pour plusieurs réseaux",
  summary: "Faire communiquer plusieurs VLAN grâce à un routeur sur un bras ou à des interfaces virtuelles, puis vérifier les passerelles, le trunk et les pièges classiques.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer pourquoi deux VLAN ne se parlent pas sans couche 3, configurer un routeur sur un bras avec des sous-interfaces dot1Q, associer la bonne passerelle à chaque VLAN, vérifier le trunk et repérer les erreurs de routage inter-VLAN."),
    prerequisites("avoir configuré des VLAN et compris qu’un trunk 802.1Q transporte plusieurs réseaux logiques sur un même lien."),
    scenario("Au Cabinet Moussa, la comptabilité est en VLAN 110, l’accueil en VLAN 120 et les invités en VLAN 130. Le directeur veut que l’accueil atteigne le serveur d’impression de la comptabilité, mais pas le Wi-Fi invité. Tout passe par un seul lien entre le commutateur et le routeur. Pour réussir cette ouverture contrôlée, il faut comprendre le routage inter-VLAN et vérifier minutieusement les passerelles de chaque réseau."),
    videoSlot("Routage inter-VLAN : un seul lien, plusieurs réseaux"),
    text("Un VLAN sépare les diffusions, pas les besoins métier. Dès qu’un poste du VLAN 110 doit joindre une imprimante ou un serveur du VLAN 120, il faut un équipement de couche 3. La méthode classique, dite « routeur sur un bras », consiste à relier le commutateur à un routeur par un trunk unique, puis à créer une sous-interface par VLAN sur le routeur. Chaque sous-interface reçoit un tag 802.1Q et l’adresse de passerelle du VLAN correspondant."),
    figure({
      kind: "network",
      title: "Router on a stick",
      cols: 4,
      rows: 3,
      nodes: [
        { id: "v110", label: "VLAN 110", sub: "192.168.10.0/24", icon: "pc", col: 0, row: 0, tone: "blue" },
        { id: "v120", label: "VLAN 120", sub: "192.168.11.0/24", icon: "pc", col: 0, row: 1, tone: "green" },
        { id: "v130", label: "VLAN 130", sub: "192.168.12.0/24", icon: "access-point", col: 0, row: 2, tone: "amber" },
        { id: "sw1", label: "SW1", icon: "switch", col: 2, row: 1, tone: "violet" },
        { id: "r1", label: "R1", sub: "Gi0/0", icon: "router", col: 3, row: 1, tone: "violet" },
      ],
      links: [
        { from: "v110", to: "sw1" },
        { from: "v120", to: "sw1" },
        { from: "v130", to: "sw1" },
        { from: "sw1", to: "r1", label: "trunk", style: "thick", arrow: "both", tone: "violet" },
      ],
      caption: "Passerelles : 110 = 192.168.10.1 ; 120 = 192.168.11.1 ; 130 = 192.168.12.1.",
    }),
    text("Sur Cisco IOS, la syntaxe doit être exacte : interface GigabitEthernet0/0.110, encapsulation dot1Q 110, puis ip address. L’interface physique porte les sous-interfaces et doit être active. Sur un commutateur de niveau 3, on peut obtenir le même résultat avec des SVI, par exemple interface vlan 110 et la commande ip routing. Le principe ne change pas : chaque VLAN a sa passerelle propre, et le lien entre le poste et cette passerelle doit être cohérent de bout en bout."),
    code("! Routeur R1\ninterface GigabitEthernet0/0\n no shutdown\n\ninterface GigabitEthernet0/0.110\n encapsulation dot1Q 110\n ip address 192.168.10.1 255.255.255.0\n\ninterface GigabitEthernet0/0.120\n encapsulation dot1Q 120\n ip address 192.168.11.1 255.255.255.0\n\ninterface GigabitEthernet0/0.130\n encapsulation dot1Q 130\n ip address 192.168.12.1 255.255.255.0\n\n! Commutateur SW1\ninterface GigabitEthernet0/1\n switchport mode trunk\n switchport trunk allowed vlan 110,120,130", "text"),
    text("Démonstration guidée : vérifie d’abord le commutateur avec show interfaces trunk. Côté routeur, lis show ip interface brief pour voir si les sous-interfaces sont up. Ensuite teste à l’échelle : ping entre un poste et sa passerelle, puis entre deux VLAN. Si le poste 192.168.10.25 ne joint pas 192.168.11.50, regarde d’abord sa passerelle par défaut. Si elle pointe vers 192.168.10.254 au lieu de 192.168.10.1, le routage inter-VLAN ne sera jamais sollicité correctement."),
    code("show interfaces trunk\n\n# exemple de sortie\n# Port        Mode         Encapsulation  Status    Native vlan\n# Gi0/1       on           802.1q         trunking  1\n# Port        Vlans allowed on trunk\n# Gi0/1       110,120,130\n\nshow ip interface brief\n\n# exemple de sortie\n# Interface              IP-Address      OK? Method Status Protocol\n# Gi0/0                  unassigned      YES unset  up     up\n# Gi0/0.110              192.168.10.1    YES manual up     up\n# Gi0/0.120              192.168.11.1    YES manual up     up\n# Gi0/0.130              192.168.12.1    YES manual up     up", "text"),
    text("Le routeur sur un bras reste simple et économique, mais le lien unique peut devenir un goulot d’étranglement si beaucoup de trafic circule entre VLAN. Dans ce cas, un commutateur de niveau 3 avec SVI évite le détour par un seul câble. Quelle que soit la méthode, n’oublie pas la sécurité : autoriser tout entre tous les VLAN n’a pas de sens. Un routage inter-VLAN propre s’accompagne vite d’ACL, par exemple pour bloquer les invités vers la comptabilité tout en laissant sortir vers Internet."),
    example("Exemple corrigé : le poste 192.168.10.25/24 du VLAN 110 veut joindre 192.168.11.50/24 dans le VLAN 120. Il constate que la destination n’est pas locale, envoie donc sa trame à la passerelle 192.168.10.1, soit la sous-interface Gi0/0.110. Le routeur retire le tag 110, route au niveau IP, puis renvoie la trame avec le tag 120 vers le commutateur. Si encapsulation dot1Q 120 était configuré par erreur sur Gi0/0.110, le trafic du VLAN 110 arriverait sur la mauvaise sous-interface et le ping échouerait malgré des adresses IP correctes."),
    mistakes("oublier no shutdown sur l’interface physique, puis chercher un problème d’IP ; mettre un mauvais identifiant dans encapsulation dot1Q ; oublier de configurer le trunk entre commutateur et routeur ; laisser des passerelles hôtes incohérentes avec les sous-interfaces réellement configurées."),
    safety("le routage inter-VLAN ouvre volontairement des chemins entre réseaux internes. Fais-le seulement sur ton propre réseau et ajoute des ACL dès qu’un VLAN doit rester sensible, par exemple l’administration ou la comptabilité."),
    takeaway("deux VLAN ne communiquent pas sans couche 3. Le routeur sur un bras crée une sous-interface et une passerelle par VLAN, transportées sur un trunk unique. Vérifie toujours trois points : le trunk, les identifiants dot1Q et la passerelle configurée sur chaque hôte."),
    practice("ouvre le laboratoire « TP 2 : VLAN, trunk et routage inter-VLAN pour la PME Kora », configure les sous-interfaces du routeur, teste les passerelles puis les échanges entre VLAN, et termine par le quiz de la leçon."),
    reference("netacad"),
    reference("packetTracer"),
  ],
  quiz: {
    title: "Quiz : routage inter-VLAN",
    questions: [
      questions.choice("Dans une architecture « routeur sur un bras », à quoi sert encapsulation dot1Q 110 sur Gi0/0.110 ?", ["À activer DHCP sur le VLAN 110", "À indiquer que la sous-interface traite les trames taguées du VLAN 110", "À convertir le VLAN 110 en lien série", "À désactiver la passerelle du VLAN 110"], 1, "La commande associe la sous-interface au tag 802.1Q du VLAN 110. Sans cette correspondance, le routeur ne sait pas quelle sous-interface doit traiter les trames reçues sur le trunk.", "facile"),
      questions.tf("Si deux postes sont dans des VLAN différents, ils peuvent communiquer sans passerelle tant qu’ils sont branchés sur le même commutateur.", false, "Faux : le même commutateur ne suffit pas. Les VLAN créent des réseaux séparés et la communication IP entre eux exige un équipement de couche 3, donc une passerelle adaptée dans chaque VLAN.", "moyen"),
      questions.choice("Quel symptôme est le plus cohérent si show ip interface brief affiche Gi0/0.110 down/down et Gi0/0.120 down/down ?", ["Le lien physique porteur des sous-interfaces n’est pas opérationnel ou n’a pas été activé", "Le DNS est mal configuré", "Le VLAN 120 manque dans le plan d’adressage IPv6", "Le commutateur a appris trop d’adresses MAC"], 0, "Si plusieurs sous-interfaces sont down/down, le problème vient souvent de l’interface physique porteuse ou du trunk. Le DNS et l’IPv6 n’expliquent pas l’état administratif et protocolaire de ces interfaces.", "difficile"),
      questions.multi("Quelles vérifications sont pertinentes quand deux VLAN ne se joignent pas ? Plusieurs réponses sont justes.", ["Le port entre commutateur et routeur est bien en trunk", "Chaque VLAN a la bonne passerelle sur les hôtes", "Les identifiants dot1Q correspondent aux VLAN attendus", "La table ARP du poste contient forcément déjà toutes les MAC nécessaires avant le premier ping"], [0, 1, 2], "Le trunk, les passerelles et les identifiants dot1Q sont les trois vérifications majeures. En revanche, la table ARP n’a pas besoin d’être déjà complète avant le premier ping : elle se construit justement pendant les premiers échanges.", "moyen"),
    ],
  },
};

const dynamicRoutingLesson: NewLesson = {
  key: "reseaux-routage-dynamique",
  title: "Routage dynamique : RIP, OSPF et choix d’un protocole",
  summary: "Comparer routes statiques et protocoles dynamiques, lire les différences entre RIP et OSPF, puis choisir une solution réaliste selon la taille et la stabilité du réseau.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("distinguer routage statique et dynamique, comparer RIP et OSPF, lire une route apprise dynamiquement, interpréter les distances administratives et choisir un protocole cohérent pour un petit ou moyen réseau."),
    prerequisites("savoir lire une table de routage et configurer une route statique simple entre plusieurs réseaux."),
    scenario("Awa a d’abord relié trois sites avec des routes statiques. Tout allait bien, jusqu’au jour où un quatrième lien de secours a été ajouté. Chaque modification lui impose maintenant de retoucher plusieurs routeurs. Elle cherche une méthode plus souple, capable d’apprendre les réseaux automatiquement et de converger après une panne, sans pour autant choisir un protocole trop complexe pour son contexte."),
    videoSlot("Routage dynamique : quand arrêter d’écrire toutes les routes à la main"),
    text("Le routage statique est parfait quand la topologie bouge peu. Le routage dynamique ajoute une intelligence distribuée : les routeurs s’échangent des informations, apprennent les préfixes voisins, recalculent après une panne et mettent à jour leurs tables. Cela a un coût : davantage de configuration, de trafic de contrôle et de concepts à surveiller. Le bon choix dépend donc de la taille du réseau, de sa stabilité et du niveau d’autonomie souhaité."),
    figure({
      kind: "cards",
      title: "Comparer vite",
      columns: 2,
      items: [
        { term: "Statique", text: "simple, prévisible, peu bavard", tone: "green" },
        { term: "RIP", text: "vecteur de distance, métrique = nombre de sauts, maximum 15, envoi RIPv2 vers `224.0.0.9`", tone: "amber" },
        { term: "OSPF", text: "état de liens, coût, voisins, zones, Hello vers `224.0.0.5` et DR/BDR vers `224.0.0.6`", tone: "blue" },
        { term: "BGP", text: "entre systèmes autonomes sur Internet", tone: "violet" },
      ],
    }),
    text("RIP est facile à démarrer, mais il passe mal à l’échelle et converge lentement. OSPF demande plus de rigueur, mais il choisit mieux ses chemins, converge plus vite et domine dans les réseaux d’entreprise. La table de routage mélange souvent plusieurs sources : connecté, statique, OSPF, RIP. La distance administrative aide alors à arbitrer entre protocoles différents pour une même destination : connecté 0, statique 1, OSPF 110, RIP 120. Si OSPF et RIP annoncent le même préfixe, OSPF gagne avant même qu’on compare d’autres détails."),
    code("router rip\n version 2\n no auto-summary\n network 10.0.0.0\n network 172.16.0.0\n passive-interface GigabitEthernet0/0\n\nrouter ospf 1\n router-id 1.1.1.1\n passive-interface default\n no passive-interface GigabitEthernet0/1\n no passive-interface GigabitEthernet0/2\n network 10.1.0.0 0.0.255.255 area 0\n network 172.16.1.0 0.0.0.3 area 0\n network 172.16.1.4 0.0.0.3 area 0", "text"),
    text("Démonstration guidée : sur Cisco IOS, active un seul protocole à la fois dans un labo, puis lis show ip route et show ip protocols. Cherche d’abord la lettre d’origine des routes, R pour RIP ou O pour OSPF, puis la valeur entre crochets. Dans une ligne comme O 10.3.8.0/24 [110/20] via 172.16.1.2, 110 est la distance administrative et 20 la métrique OSPF montrée ici. Une ligne R 10.3.8.0/24 [120/2] via 172.16.1.6 perdra face à OSPF pour ce même préfixe."),
    code("show ip route\n\n# exemple de sortie\n# O    10.3.8.0/24 [110/20] via 172.16.1.2, 00:00:18, Gi0/1\n# R    10.3.9.0/24 [120/2]  via 172.16.1.6, 00:00:09, Gi0/2\n\nshow ip protocols\n\n# exemple de sortie\n# Routing Protocol is \"ospf 1\"\n# Routing for Networks:\n#   10.1.0.0 0.0.255.255 area 0\n#   172.16.1.0 0.0.0.3 area 0\n#   172.16.1.4 0.0.0.3 area 0", "text"),
    text("Deux bonnes habitudes méritent d’être retenues. D’abord, rends passives les interfaces qui ne doivent pas former de voisinage, notamment côté LAN utilisateur. Ensuite, authentifie les mises à jour quand le protocole le permet, pour éviter qu’un voisin non autorisé annonce de fausses routes. RIP et OSPF peuvent tous deux être sécurisés, mais OSPF offre en général une meilleure maîtrise des grands réseaux. BGP existe aussi, mais son terrain naturel est l’échange de routes entre systèmes autonomes, pas un petit LAN d’atelier."),
    example("Exemple corrigé : si un routeur apprend 10.3.8.0/24 à la fois par OSPF avec [110/20] et par RIP avec [120/2], il garde l’entrée OSPF, car 110 est inférieur à 120. La route RIP n’est pas « fausse », elle est simplement moins prioritaire. Pour trois petits sites avec une topologie stable, des routes statiques peuvent rester plus simples. Dès que plusieurs chemins et des évolutions fréquentes apparaissent, OSPF devient souvent le meilleur compromis."),
    mistakes("activer RIP ou OSPF sur toutes les interfaces sans réfléchir, y compris côté utilisateurs ; croire qu’une métrique plus faible l’emporte toujours, alors que la distance administrative tranche d’abord entre protocoles différents ; oublier passive-interface et exposer inutilement des échanges de routage ; choisir RIP par habitude sur un réseau qui grandit déjà trop vite."),
    safety("ne forme de voisinage dynamique qu’avec des équipements autorisés. Une annonce de routes frauduleuse peut détourner du trafic critique, surtout si aucune authentification ni limitation d’interface n’a été prévue."),
    takeaway("le routage dynamique réduit le travail manuel quand le réseau grandit. RIP est simple mais limité ; OSPF est plus robuste pour l’entreprise. Entre protocoles différents, la distance administrative décide d’abord, puis la table retient la meilleure route restante."),
    practice("ouvre le laboratoire « TP 3 : relier trois sites avec des routes statiques » puis imagine à quels endroits un protocole dynamique t’éviterait le plus de maintenance. Si tu poursuis en laboratoire libre, compare show ip route avant et après OSPF, puis termine par le quiz de la leçon."),
    reference("rfc2453"),
    reference("rfc2328"),
    reference("netacad"),
  ],
  quiz: {
    title: "Quiz : routage dynamique",
    questions: [
      questions.choice("Quel protocole utilise une métrique fondée sur le nombre de sauts, avec un maximum de 15 ?", ["OSPF", "RIP", "BGP", "ARP"], 1, "RIP compte les sauts et considère 16 comme injoignable. OSPF utilise un coût de lien, BGP sert entre systèmes autonomes, et ARP ne fait pas de routage du tout.", "facile"),
      questions.choice("Si une même route existe en statique et en OSPF, laquelle est préférée par défaut ?", ["OSPF, car il est dynamique", "La route statique, car sa distance administrative 1 est inférieure à 110", "RIP, car il parle à tout le monde", "Aucune, le routeur répartit toujours la charge"], 1, "Par défaut, une route statique a une distance administrative de 1, contre 110 pour OSPF. Le routeur préfère donc la statique, sauf configuration particulière. Le caractère dynamique ne donne pas la priorité.", "moyen"),
      questions.tf("La commande passive-interface sert notamment à éviter qu’une interface côté LAN utilisateur forme un voisinage de routage inutile.", true, "Vrai : rendre passive une interface empêche l’établissement de voisinages ou l’envoi d’annonces là où ce n’est pas nécessaire, tout en pouvant continuer à annoncer le réseau local selon le protocole et la configuration.", "moyen"),
      questions.multi("Dans quels cas OSPF est-il souvent un meilleur choix que RIP ? Plusieurs réponses sont correctes.", ["Quand le réseau contient plusieurs chemins et doit converger vite", "Quand on dépasse facilement la logique simple des petits sites", "Quand on veut rester limité à 15 sauts maximum", "Quand on a besoin d’un meilleur contrôle des voisinages et des zones"], [0, 1, 3], "OSPF est plus adapté aux réseaux plus riches en chemins, plus grands ou plus exigeants en convergence et en contrôle. La limite de 15 sauts est justement une faiblesse de RIP, pas un avantage pour choisir OSPF.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c2:8",
    position: 4,
    title: "Commutation Ethernet",
    description: "Tu vas comprendre comment un LAN transporte les trames, comment un commutateur apprend les adresses MAC et comment segmenter proprement un même câblage avec des VLAN. Critères de réussite : lire une table MAC, configurer un port access et un trunk 802.1Q, expliquer pourquoi deux VLAN séparés ne communiquent pas sans couche 3.",
    lessons: [ethernetMac, vlanLesson],
  },
  {
    key: "c2:9",
    position: 5,
    title: "Routage",
    description: "Tu vas apprendre comment un routeur choisit un chemin, comment relier plusieurs VLAN et quand préférer des routes statiques ou un protocole dynamique. Critères de réussite : interpréter show ip route, configurer une route statique ou un routeur sur un bras, justifier le choix entre statique, RIP et OSPF selon le contexte.",
    lessons: [routingTableLesson, interVlanLesson, dynamicRoutingLesson],
  },
];
