// Réseaux, programme complet : partie A (modules 1 à 3). Le modèle de leçon est donné par
// « reseaux-lan-wan » : copie sa structure, pas son contenu.
import {
  code, example, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const lanWan: NewLesson = {
  key: "reseaux-lan-wan",
  title: "LAN, WAN, topologies et équipements",
  summary: "Distinguer un réseau local d’un réseau étendu, reconnaître les topologies courantes et savoir ce que font un commutateur, un routeur, un point d’accès et un pare-feu.",
  minutes: 18,
  xp: 25,
  blocks: [
    goals("distinguer un LAN d’un WAN, reconnaître les quatre topologies courantes (étoile, bus, anneau, maillée), citer le rôle d’un commutateur, d’un routeur, d’un point d’accès et d’un pare-feu, et prévoir ce qui cesse de fonctionner quand un équipement central tombe en panne."),
    prerequisites("aucun. Il suffit d’avoir déjà branché un câble réseau ou utilisé une connexion Wi-Fi."),
    scenario("Awa ouvre un petit atelier de réparation à Douala. Elle dispose de trois ordinateurs, d’une imprimante partagée et d’une box fournie par son opérateur. Un matin, l’imprimante répond toujours, mais plus aucun site web ne s’ouvre. Pour comprendre ce qui se passe, Awa doit savoir quelles machines se parlent directement, lesquelles passent par la box, et ce qui relie son atelier au reste du monde."),
    videoSlot("Du câble au réseau : LAN, WAN et équipements en 6 minutes"),
    text("Un réseau local, ou LAN (Local Area Network), relie des machines proches les unes des autres : un atelier, une salle de classe, un étage de bureaux. Ses équipements appartiennent en général à la même organisation, qui décide seule de leur configuration. Un réseau étendu, ou WAN (Wide Area Network), relie des réseaux locaux éloignés, parfois à travers un pays ou un continent, en s’appuyant sur les liaisons d’un opérateur. Internet est le plus grand des WAN : c’est un ensemble de réseaux interconnectés, pas un réseau unique."),
    schema("   ATELIER D’AWA (LAN)                                    OPÉRATEUR (WAN)\n\n   [PC1]   [PC2]   [PC3]   [Imprimante]\n     \\       |       |       /\n      +------+-------+------+\n             [Commutateur]\n                  |\n               [  Box  ] ======= liaison de l’opérateur ======> ( Internet )"),
    text("La topologie décrit la façon dont les machines sont reliées. On distingue la topologie physique, c’est-à-dire le câblage réel, de la topologie logique, c’est-à-dire le chemin que suivent les données. Aujourd’hui, presque tous les réseaux locaux, filaires comme sans fil, sont en étoile : chaque machine est reliée à un équipement central. Les anciens réseaux en bus partageaient un seul câble, et l’anneau fait circuler les données de proche en proche. Dans un réseau maillé, plusieurs chemins existent entre les équipements : c’est le principe d’Internet, et celui de certains systèmes Wi-Fi à plusieurs bornes."),
    schema("Topologie  Principe                           Avantage                    Point faible\nÉtoile     tout passe par un équipement      une panne de poste reste     le centre est un point\n           central                           isolée                       de défaillance\nBus        un câble partagé par toutes       peu de câble                 une coupure bloque tout\n           les machines\nAnneau     chaque machine relie la suivante  accès organisé               une rupture coupe l’anneau\nMaillée    plusieurs chemins entre les       résiste aux pannes           coûteuse et complexe\n           équipements"),
    text("Quatre équipements reviennent partout. Le commutateur (switch) relie les machines d’un même réseau local et transmet chaque trame à la bonne machine d’après son adresse MAC. Le routeur relie des réseaux différents, par exemple ton LAN et celui de ton opérateur, et choisit le chemin d’après l’adresse IP. Le point d’accès Wi-Fi joue pour les appareils sans fil le rôle que joue le commutateur pour les câbles. Le pare-feu autorise ou refuse le trafic selon des règles. Une box domestique réunit tout cela dans un seul boîtier : modem, routeur, commutateur, point d’accès et pare-feu."),
    schema("Équipement      Ce qu’il lit             Ce qu’il relie\nCommutateur     adresse MAC              des machines d’un même réseau\nRouteur         adresse IP               des réseaux différents\nPoint d’accès   adresse MAC, sans fil    des appareils Wi-Fi à un réseau filaire\nPare-feu        IP, ports, état          deux zones dont il filtre le trafic"),
    text("Démonstration guidée : sur ton ordinateur, ouvre un terminal et repère ta passerelle. C’est l’adresse du routeur de ton LAN, celle par laquelle sort tout ce qui n’est pas local. Teste ensuite chaque maillon, du plus proche au plus lointain : d’abord la passerelle, puis une adresse publique. Si la première répond et pas la seconde, le problème se situe plutôt du côté du WAN."),
    code("# Windows : repérer la passerelle\nipconfig\n\n# Linux : même information\nip route show default\n# exemple de sortie (valeurs fictives)\n# default via 192.168.1.1 dev wlan0 proto dhcp metric 600\n\n# Tester chaque maillon\nping -c 3 192.168.1.1    # la box : le LAN fonctionne-t-il ?  (Windows : ping -n 3 192.168.1.1)\nping -c 3 1.1.1.1        # un serveur public : la sortie vers Internet marche-t-elle ?", "bash"),
    example("Chez Awa, l’imprimante répond (elle est dans le LAN, reliée au même commutateur) mais aucun site ne s’ouvre. Le ping vers la box (192.168.1.1) réussit, le ping vers 1.1.1.1 échoue. Le LAN fonctionne donc : la panne se situe entre la box et l’opérateur. Awa appelle son opérateur au lieu de remplacer ses câbles ou son commutateur."),
    mistakes("confondre « réseau » et « Internet », alors qu’un LAN fonctionne très bien sans accès à Internet ; croire qu’un commutateur lit les adresses IP, alors qu’il s’appuie sur les adresses MAC ; appeler routeur tout boîtier muni d’antennes, alors qu’une box cumule plusieurs fonctions ; penser qu’une étoile n’a aucun point faible, alors que son équipement central en est un."),
    safety("un équipement réseau voit passer le trafic de tout le monde. Change toujours le mot de passe d’administration fourni par défaut, mets à jour son logiciel et ne l’expose jamais à Internet sans protection."),
    takeaway("le LAN est local et sous ta responsabilité, le WAN relie des sites distants, Internet est un ensemble de WAN. L’étoile domine, et son centre est un point à protéger. Le commutateur relie des machines d’un même réseau, le routeur relie des réseaux différents."),
    practice("ouvre le laboratoire « TP 1 : construire le réseau d’une maison », place les équipements de la topologie et repère le LAN, la passerelle et la liaison vers le fournisseur d’accès. Termine par le quiz de la leçon."),
    reference("netacad", "Cisco Networking Academy : les cours d’initiation aux réseaux, gratuits"),
    reference("packetTracer"),
  ],
  quiz: {
    title: "Quiz : LAN, WAN et équipements",
    questions: [
      questions.choice("Quel équipement relie deux réseaux différents et choisit le chemin des paquets d’après leur adresse IP ?", ["Le commutateur", "Le routeur", "Le point d’accès Wi-Fi", "La carte réseau"], 1, "C’est le rôle du routeur : il lit l’adresse IP de destination et choisit la sortie. Le commutateur et le point d’accès restent dans un seul réseau et s’appuient sur les adresses MAC ; la carte réseau est l’interface d’une machine, elle ne relie rien d’autre."),
      questions.tf("Dans une topologie en étoile, la rupture du câble d’un seul poste coupe tout le réseau.", false, "Faux : seul ce poste est isolé, les autres continuent de communiquer, ce qui est un avantage de l’étoile. En revanche, la panne de l’équipement central, elle, coupe tout le monde.", "moyen"),
      questions.multi("Quelles affirmations sur un LAN sont exactes ? (plusieurs réponses)", ["Il couvre en général un espace limité, comme un atelier ou un étage", "Il peut fonctionner sans accès à Internet", "Il relie obligatoirement des sites situés dans des villes différentes", "Il utilise souvent des commutateurs et du Wi-Fi"], [0, 1, 3], "Un LAN est local, géré par une seule organisation, et ses machines se parlent sans Internet : une imprimante partagée en est la preuve. Relier des villes différentes est le rôle d’un WAN."),
      questions.choice("Awa constate que l’imprimante répond et que le ping vers la box réussit, mais que le ping vers 1.1.1.1 échoue. Quelle hypothèse est la plus cohérente ?", ["Le commutateur de l’atelier est en panne", "Le câble de l’imprimante est trop long", "La liaison entre la box et l’opérateur est en cause", "La carte réseau du PC1 est défectueuse"], 2, "Les tests réussis prouvent que le LAN fonctionne, commutateur, câbles et carte réseau compris. Seule la sortie vers Internet échoue : on suspecte la box ou la liaison de l’opérateur.", "difficile"),
    ],
  },
};

const osiPractice: NewLesson = {
  key: "l-c2-3",
  title: "Le modèle OSI en pratique",
  summary: "Utiliser les 7 couches OSI pour situer un protocole, un équipement ou une panne, puis relier ce modèle au TCP/IP réel d’une page web.",
  minutes: 20,
  xp: 25,
  upgrade: true,
  blocks: [
    goals("nommer les 7 couches, associer à chaque couche son rôle et son unité de données, relier OSI au modèle TCP/IP, situer un équipement ou une commande de diagnostic à la bonne couche, et raconter le trajet d’une page web de la couche 7 à la couche 1."),
    prerequisites("avoir suivi « LAN, WAN, topologies et équipements » ou déjà savoir distinguer un commutateur, un routeur et une passerelle."),
    scenario("Moussa aide un cybercafé à Abidjan. Les postes voient bien la borne Wi-Fi, mais une page interne ne s’ouvre plus. Le gérant dit seulement : « Internet est cassé ». Moussa doit éviter de changer du matériel au hasard. Il lui faut une méthode pour savoir si la panne vient du câble, de l’IP, du DNS ou de l’application elle-même."),
    videoSlot("Les 7 couches OSI avec un vrai dépannage"),
    text("Le modèle OSI sépare une communication réseau en 7 couches pour répondre à une question simple : à quel niveau se produit l’action, ou la panne ? La couche 1 transporte les bits sur le support physique. La couche 2 envoie des trames dans le réseau local. La couche 3 route des paquets entre réseaux. La couche 4 transporte des segments ou des datagrammes entre applications. Les couches 5, 6 et 7 gèrent la session, la présentation des données et l’application visible par l’utilisateur. Quand tu sais cela, tu ne dis plus seulement « le réseau ne marche pas » : tu précises la couche à vérifier."),
    schema("7 Application    service visible : HTTP, DNS, SMTP        unité : message\n6 Présentation  format, compression, chiffrement     unité : message\n5 Session       ouverture et suivi d’une session     unité : message\n4 Transport     TCP, UDP, ports                      unité : segment\n3 Réseau        IP, routage                          unité : paquet\n2 Liaison       Ethernet, Wi-Fi, MAC                 unité : trame\n1 Physique      câble, fibre, ondes                  unité : bits"),
    text("Dans la vraie vie, on parle souvent plus du modèle TCP/IP à 4 couches. Il regroupe les couches 5, 6 et 7 d’OSI dans l’application, garde transport et Internet, puis rassemble liaison et physique dans l’accès réseau. Les deux modèles ne se contredisent pas : OSI sert à raisonner finement, TCP/IP décrit mieux les protocoles réellement utilisés. Un navigateur qui ouvre une page web utilise par exemple HTTP à la couche 7, TLS à la 6, TCP à la 4, IP à la 3 et Ethernet ou Wi-Fi à la 2."),
    schema("OSI                      TCP/IP                Exemple d’équipement\n7, 6, 5 Application      Application           proxy, navigateur, serveur DNS\n4      Transport         Transport             pare-feu à états, load balancer\n3      Réseau            Internet              routeur\n2, 1   Liaison/Physique  Accès réseau          commutateur, point d’accès, câble"),
    text("Une page web traverse toutes les couches. Ton navigateur crée une requête HTTP : couche 7. TCP ajoute les ports source et destination : couche 4. IP ajoute l’adresse source et l’adresse de destination : couche 3. Ethernet ajoute les adresses MAC pour le prochain saut : couche 2. Enfin, la carte réseau envoie des signaux électriques ou radio : couche 1. Au retour, le serveur décapsule ces informations dans l’ordre inverse. Cette pile explique pourquoi un même problème peut avoir plusieurs symptômes : si la couche 2 tombe, HTTP et DNS échouent aussi, mais ils ne sont pas la cause initiale."),
    text("Démonstration guidée : quand un service ne répond plus, teste couche par couche. Commence par l’adresse IP de la passerelle avec ping : si elle ne répond pas, tu regardes d’abord les couches 1 à 3. Consulte ensuite le cache ARP pour vérifier que la couche 2 connaît bien une adresse MAC. Enfin, teste l’application avec curl ou un navigateur. Cette progression te fait gagner du temps et évite de redémarrer un serveur alors que le câble du point d’accès est débranché."),
    code("# Couche 3 : la passerelle répond-elle ?\nping -c 3 192.168.1.1\n# Windows : ping -n 3 192.168.1.1\n\n# Couches 2 et 3 : la machine connaît-elle l’adresse MAC du voisin ?\narp -a\n# exemple de sortie\n# Interface: 192.168.1.25 --- 0x8\n#   Internet Address      Physical Address      Type\n#   192.168.1.1           44-55-66-77-88-99     dynamic\n\n# Couche 7 : le service HTTP répond-il ?\ncurl -I http://192.168.1.50\n# exemple de sortie\n# HTTP/1.1 200 OK\n# Server: nginx", "bash"),
    example("Exemple corrigé : Nadia obtient des réponses au ping vers 192.168.1.1 et voit bien l’adresse MAC de la passerelle dans ARP, mais curl vers l’intranet renvoie « Connection refused ». Les couches 1, 2 et 3 fonctionnent. Le service est donc joignable jusqu’au serveur, mais l’application web ou son écoute TCP à la couche 7 ou 4 est en cause. Changer le commutateur n’aurait servi à rien."),
    mistakes("apprendre les noms des couches sans les relier à une action concrète ; croire que le modèle OSI reflète exactement tous les protocoles réels, alors qu’il sert surtout d’outil mental ; appeler « couche 3 » tout problème d’Internet, même quand le câble est débranché ; oublier le nom de l’unité de données, ce qui brouille la lecture d’une capture."),
    takeaway("OSI est une carte de lecture : chaque couche a un rôle, une unité de données et des outils de diagnostic. TCP/IP simplifie ce raisonnement en 4 couches, mais les deux modèles racontent le même trajet. Une panne bien décrite commence toujours par la couche réellement touchée."),
    practice("reprends le laboratoire « TP 1 : construire le réseau d’une maison », nomme chaque équipement par couche dominante, puis teste une panne simple en suivant l’ordre physique, liaison, IP, application. Termine par le quiz de la leçon."),
    reference("netacad"),
    reference("wiresharkGuide", "Wireshark : voir les couches dans une capture"),
    reference("msPing", "Microsoft : diagnostiquer avec ping"),
  ],
  quiz: {
    title: "Quiz : modèle OSI en pratique",
    questions: [
      questions.choice("Quelle unité de données est la bonne à la couche 3 du modèle OSI ?", ["Le segment", "La trame", "Le paquet", "Les bits"], 2, "La couche 3, dite réseau, manipule des paquets IP. La trame correspond à la couche 2, le segment à la couche 4 et les bits à la couche 1.", "facile"),
      questions.multi("Quelles associations sont correctes ? (plusieurs réponses)", ["Un routeur travaille surtout à la couche 3", "La commande arp -a aide à observer la couche 2", "curl teste directement la couche 1", "Un commutateur local lit surtout des adresses MAC"], [0, 1, 3], "Le routeur choisit un chemin IP, ARP relie IP et MAC dans le LAN, et le commutateur transmet des trames selon les adresses MAC. curl teste l’application, pas le support physique.", "moyen"),
      questions.choice("Tu peux joindre la passerelle avec ping et voir son adresse dans ARP, mais curl vers l’intranet renvoie « Connection refused ». Quelle couche dois-tu suspecter d’abord ?", ["La couche 1, physique", "La couche 2, liaison", "La couche 4 ou 7, transport ou application", "Aucune, tout fonctionne"], 2, "Le ping et ARP montrent que les couches basses fonctionnent jusqu’à la passerelle. Le refus de connexion pointe plutôt vers un service qui n’écoute pas, donc transport ou application.", "difficile"),
      questions.tf("Dans le modèle TCP/IP, les couches présentation et session sont généralement regroupées avec l’application.", true, "Vrai : TCP/IP simplifie la pile en 4 couches et regroupe les responsabilités hautes dans l’application. Cela ne supprime pas ces fonctions, cela les rassemble.", "moyen"),
    ],
  },
};

const encapsulationLesson: NewLesson = {
  key: "reseaux-encapsulation",
  title: "TCP/IP et encapsulation : le voyage d’un paquet",
  summary: "Suivre une requête HTTP à travers Ethernet, IPv4 et TCP, comprendre ce qui change à chaque saut et lire ces indices dans Wireshark.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("expliquer l’encapsulation et la décapsulation, reconnaître les champs essentiels des en-têtes Ethernet, IPv4 et TCP, décrire ce qui change à chaque saut, interpréter une taille de trame simple, et lire une requête web dans Wireshark."),
    prerequisites("avoir suivi « Le modèle OSI en pratique » et savoir qu’un routeur lit l’adresse IP tandis qu’un commutateur lit l’adresse MAC."),
    scenario("Fatou doit comprendre pourquoi un site interne est lent dans un petit cabinet à Lomé. Le serveur web répond, mais certaines requêtes expirent. Un collègue lui envoie une capture Wireshark pleine de lignes incompréhensibles. Pour ne pas subir l’outil, Fatou doit suivre un paquet de bout en bout et repérer ce qui reste stable, ce qui change, et à quel moment une taille trop grande peut poser problème."),
    videoSlot("Le voyage d’un paquet : de ton navigateur au serveur web"),
    text("L’encapsulation consiste à placer des données dans des enveloppes successives. Une application produit un message, TCP ajoute un en-tête de transport, IPv4 ajoute un en-tête réseau, puis Ethernet ajoute un en-tête de liaison pour le prochain saut. À l’arrivée, la machine retire ces en-têtes dans l’ordre inverse : c’est la décapsulation. Cette idée simple explique pourquoi une capture affiche plusieurs couches pour une seule action, comme un clic sur un lien."),
    schema("Trame Ethernet\n+----------------+----------------+---------+----------------------+\n| MAC dest 6 o   | MAC src 6 o    | Type 2  | charge utile         |\n+----------------+----------------+---------+----------------------+\n                                   |\n                                   v\nPaquet IPv4 : src, dst, TTL, protocole\nSegment TCP : port src, port dst, seq, ack, flags\nDonnées : GET /intranet HTTP/1.1"),
    text("Certains champs sont essentiels pour le diagnostic. En Ethernet, tu regardes surtout les adresses MAC source et destination, ainsi que l’EtherType, par exemple 0x0800 pour IPv4. En IPv4, l’adresse source, l’adresse de destination, le TTL et le protocole comptent beaucoup. En TCP, les ports source et destination, les numéros de séquence et les drapeaux SYN, ACK, FIN ou RST racontent l’état de la conversation."),
    schema("                 Lien 1         Lien 2          Lien 3\n                 PC > routeur 1  routeur 1 > 2   routeur 2 > serveur\nMAC source       PC             routeur 1       routeur 2\nMAC destination  routeur 1      routeur 2       serveur\nIP source        192.168.1.25   192.168.1.25    192.168.1.25\nIP destination   172.16.5.20    172.16.5.20     172.16.5.20\nTTL              64             63              62"),
    text("À chaque saut, les adresses MAC changent parce que la trame n’est valable que sur le lien local. En revanche, l’adresse IP source et l’adresse IP de destination restent identiques jusqu’au serveur, sauf si un mécanisme de traduction d’adresse intervient plus tard. Le TTL, lui, diminue à chaque routeur. Si un paquet devient trop grand pour le lien suivant, il peut être fragmenté en IPv4, mais c’est à éviter : cela complique les captures et peut dégrader les performances. Sur un réseau Ethernet classique, la MTU vaut souvent 1500 octets."),
    text("Démonstration guidée : ouvre une capture dans Wireshark et filtre d’abord le flux qui t’intéresse. Pour une requête web simple, commence par http ou tcp.port == 80. Clique ensuite sur un paquet et déplie successivement Ethernet II, Internet Protocol Version 4 et Transmission Control Protocol. Vérifie que les adresses IP restent stables d’un paquet à l’autre, que les MAC changent quand tu observes un autre lien, et que le TTL baisse d’un saut à l’autre."),
    code("# Quelques filtres Wireshark utiles\nhttp\nip.addr == 172.16.5.20\ntcp.stream eq 0\n\n# Lire un paquet en ligne de commande\ntshark -r capture.pcap -Y \"http.request\" -V\n# exemple de sortie\n# Ethernet II, Src: 00:11:22:33:44:55, Dst: 66:77:88:99:aa:bb\n# Internet Protocol Version 4, Src: 192.168.1.25, Dst: 172.16.5.20, TTL: 64\n# Transmission Control Protocol, Src Port: 49822, Dst Port: 80, Flags: 0x018 (PSH, ACK)", "bash"),
    example("Exemple corrigé : une requête HTTP de 146 octets de données, transportée sans options, utilise 20 octets d’en-tête TCP et 20 octets d’en-tête IPv4. Avec 14 octets d’en-tête Ethernet, la trame visible dans la capture mesure 200 octets. Elle reste donc largement sous la MTU de 1500 et ne sera pas fragmentée. Si tu voyais une charge utile IP de 2000 octets, il faudrait soit fragmenter, soit laisser le chemin rejeter le paquet pour forcer un ajustement de taille."),
    mistakes("penser que l’adresse MAC du serveur final apparaît dans toutes les trames, alors qu’on ne voit que la MAC du prochain saut ; confondre l’adresse IP de destination avec le port TCP de destination ; oublier que le TTL diminue seulement sur les routeurs, pas sur les commutateurs ; croire qu’une capture réseau montre toujours le FCS Ethernet, alors que beaucoup de cartes réseau l’enlèvent avant l’affichage."),
    safety("capture uniquement sur ton propre réseau ou avec une autorisation claire. Une trame peut révéler des identifiants, des chemins internes et des habitudes de navigation."),
    takeaway("l’encapsulation empile des en-têtes complémentaires : Ethernet pour le lien local, IP pour le trajet entre réseaux, TCP pour la conversation entre applications. Les MAC changent à chaque saut, les IP restent stables, le TTL baisse. Une capture devient lisible dès que tu sais quoi comparer."),
    practice("travaille dans « Réseau instable : lire une capture », repère l’ouverture TCP, la requête HTTP et l’évolution du TTL, puis termine par le quiz de la leçon."),
    reference("wiresharkGuide"),
    reference("wiresharkFilters", "Wireshark : filtres d’affichage utiles"),
    reference("rfc791"),
  ],
  quiz: {
    title: "Quiz : encapsulation et voyage d’un paquet",
    questions: [
      questions.choice("Quel champ change normalement à chaque routeur sur le chemin d’un paquet IPv4 ?", ["L’adresse IP de destination", "Le TTL", "Le port TCP source", "Le contenu HTTP"], 1, "Le TTL diminue à chaque passage sur un routeur pour éviter qu’un paquet boucle indéfiniment. L’adresse IP de destination reste la même jusqu’au destinataire, sauf cas particuliers comme le NAT.", "facile"),
      questions.multi("Que peux-tu affirmer à propos d’une requête HTTP classique transportée sur Ethernet et IPv4 ? (plusieurs réponses)", ["Les adresses MAC source et destination décrivent le lien local courant", "L’adresse IP de destination reste normalement la même de bout en bout", "La trame Ethernet garde la même MAC de destination sur tous les liens", "TCP ajoute des ports pour identifier les applications"], [0, 1, 3], "Les MAC appartiennent seulement au saut local et sont réécrites à chaque lien. En revanche, l’adresse IP finale reste stable et TCP ajoute bien les ports source et destination pour la conversation.", "moyen"),
      questions.choice("Dans une capture, tu lis : « IPv4 Src 192.168.1.25, Dst 172.16.5.20, TTL 63 » puis, sur un autre lien, « TTL 62 » pour la même requête. Quelle interprétation est la meilleure ?", ["Le paquet a traversé un routeur entre les deux points d’observation", "Le commutateur a diminué le TTL", "Le client a changé d’adresse IP en cours de route", "Le serveur a fermé la connexion"], 0, "La baisse de 63 à 62 montre un passage sur un routeur. Les commutateurs ne touchent pas au TTL et rien ici n’indique un changement d’IP ou une fermeture TCP.", "difficile"),
      questions.tf("Une trame Ethernet de 200 octets est au-dessus de la MTU Ethernet classique de 1500 octets.", false, "Faux : 200 est bien inférieur à 1500. Une telle trame ne pose donc pas de problème de fragmentation sur un lien Ethernet standard.", "moyen"),
    ],
  },
};

const vlsmLesson: NewLesson = {
  key: "reseaux-vlsm",
  title: "Plan d’adressage d’une entreprise : VLSM et passerelles",
  summary: "Construire un plan d’adressage réaliste avec des sous-réseaux de tailles différentes, vérifier les chevauchements et choisir une convention de passerelle cohérente.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("trier les besoins d’un plan d’adressage du plus grand au plus petit, choisir un préfixe adapté avec une marge réaliste, attribuer une passerelle cohérente, vérifier qu’aucun sous-réseau ne se chevauche, et reconnaître les plages privées RFC 1918."),
    prerequisites("avoir suivi les leçons déjà publiées « Adresses IPv4 et masques » et « Sous-réseaux et notation CIDR »."),
    scenario("Baobab Tech ouvre de nouveaux bureaux à Cotonou. L’atelier, l’administration, les invités et les serveurs ne doivent pas partager le même sous-réseau. Le responsable te demande un plan simple, lisible et évolutif. Si tu tailles trop petit, il faudra tout refaire. Si tu tailles au hasard, tu risques un chevauchement qui fera perdre des heures au moment de configurer les routeurs."),
    videoSlot("VLSM : découper juste, sans gaspiller ni se bloquer"),
    text("Le VLSM (Variable Length Subnet Mask) consiste à donner des tailles différentes aux sous-réseaux selon le besoin réel. La méthode fiable est toujours la même : compter les hôtes utiles, ajouter la passerelle et une marge de croissance, choisir le plus petit bloc qui tient, puis affecter les blocs du plus grand besoin au plus petit. Cette approche évite de donner un /24 entier à des serveurs qui n’occupent que quelques adresses."),
    schema("Rappels de tailles utiles\n/25 = 126 hôtes   /27 = 30 hôtes\n/26 = 62 hôtes    /28 = 14 hôtes\n/29 = 6 hôtes     /30 = 2 hôtes\n\nPlages privées RFC 1918\n10.0.0.0/8     172.16.0.0/12     192.168.0.0/16"),
    text("Pour Baobab Tech, on part du réseau privé 10.2.0.0/24. L’atelier a 58 postes prévus, une passerelle et 11 adresses de réserve : il faut donc au moins 70 hôtes utilisables, ce qui impose un /25. L’administration a besoin de 18 postes, d’une passerelle et de 7 adresses de marge : 26 hôtes, donc un /27. Les invités ont 12 terminaux prévus, une passerelle et une petite marge : 14 hôtes utilisables, donc un /28. Les serveurs ont 4 machines, une passerelle et une petite réserve : 6 hôtes utilisables, donc un /29."),
    schema("Service         Besoin utile   Préfixe   Réseau           Passerelle    Hôtes utilisables         Diffusion\nAtelier         70            /25       10.2.0.0/25      10.2.0.1      10.2.0.1 à 10.2.0.126    10.2.0.127\nAdministration  26            /27       10.2.0.128/27    10.2.0.129    10.2.0.129 à 10.2.0.158  10.2.0.159\nInvités         14            /28       10.2.0.160/28    10.2.0.161    10.2.0.161 à 10.2.0.174  10.2.0.175\nServeurs        6             /29       10.2.0.176/29    10.2.0.177    10.2.0.177 à 10.2.0.182  10.2.0.183"),
    text("Choisis ensuite une convention de passerelle et tiens-la partout. Ici, on retient la première adresse utilisable de chaque sous-réseau. D’autres équipes préfèrent la dernière. L’important n’est pas la convention choisie, mais le fait de la documenter et de l’appliquer partout. Un plan d’adressage devient pénible quand certains VLAN utilisent .1 comme passerelle et d’autres .254 sans raison claire."),
    text("Démonstration guidée : avant de configurer le moindre routeur, vérifie les blocs avec un outil de calcul. Le module Python ipaddress est parfait pour cela : il affiche le réseau, la diffusion et peut confirmer qu’aucun sous-réseau n’en recouvre un autre. Ce contrôle rapide t’évite les erreurs les plus coûteuses, celles qui semblent petites sur papier mais cassent plusieurs services en production."),
    code("python -c \"import ipaddress as ip; nets=[ip.ip_network('10.2.0.0/25'), ip.ip_network('10.2.0.128/27'), ip.ip_network('10.2.0.160/28'), ip.ip_network('10.2.0.176/29')];\nfor n in nets: print(n, n.network_address, n.broadcast_address, n.num_addresses-2)\nprint(any(a.overlaps(b) for i,a in enumerate(nets) for b in nets[i+1:]))\"\n# exemple de sortie\n# 10.2.0.0/25 10.2.0.0 10.2.0.127 126\n# 10.2.0.128/27 10.2.0.128 10.2.0.159 30\n# 10.2.0.160/28 10.2.0.160 10.2.0.175 14\n# 10.2.0.176/29 10.2.0.176 10.2.0.183 6\n# False", "bash"),
    example("Exemple corrigé : si tu donnais 10.2.0.128/28 à l’administration, tu n’aurais que 14 hôtes utilisables, bien moins que les 26 nécessaires. Et si un autre service recevait ensuite 10.2.0.136/29, ce bloc (de .136 à .143) se trouverait à l’intérieur du /28 de l’administration (de .128 à .143) : c’est un chevauchement, que la méthode overlaps() du module ipaddress signale par True. Le bon réflexe est donc : plus grand bloc d’abord, bornes exactes ensuite, vérification automatisée enfin."),
    mistakes("compter seulement les postes actuels et oublier la passerelle ou la croissance ; attribuer un petit bloc d’abord, puis découvrir qu’il coupe l’espace du grand service ; mélanger plusieurs conventions de passerelle ; utiliser une plage publique au lieu d’une plage privée RFC 1918 pour un réseau interne."),
    takeaway("le VLSM sert à dimensionner juste. Tu pars du besoin utile, tu choisis le plus petit préfixe qui tient, puis tu alloues du plus grand au plus petit. Un plan fiable se termine toujours par une vérification des bornes et des chevauchements."),
    practice("ouvre « Packet Tracer : le plan d’adressage de l’atelier Kora » pour refaire un plan en VLSM, puis réemploie cette méthode dans « Projet final : concevoir et documenter le réseau de Kora ». Termine par le quiz de la leçon."),
    reference("rfc1918"),
    reference("rfc4632"),
    reference("pythonIpaddress"),
  ],
  quiz: {
    title: "Quiz : VLSM et passerelles",
    questions: [
      questions.choice("Quel bloc est le plus petit capable de fournir au moins 70 hôtes utilisables ?", ["/26", "/25", "/27", "/28"], 1, "Un /25 offre 126 hôtes utilisables, ce qui couvre 70 avec de la marge. Un /26 n’en offre que 62, donc il est insuffisant.", "moyen"),
      questions.multi("Quelles pratiques rendent un plan VLSM plus fiable ? (plusieurs réponses)", ["Attribuer les réseaux du plus grand besoin au plus petit", "Vérifier les chevauchements avant la mise en production", "Choisir la passerelle au hasard tant qu’elle est libre", "Prévoir une marge de croissance raisonnable"], [0, 1, 3], "On place d’abord les gros blocs, on contrôle qu’ils ne se recouvrent pas et on prévoit un peu de croissance. Une passerelle au hasard complique la documentation et favorise les erreurs.", "moyen"),
      questions.choice("Dans le plan ci-dessous, quelle passerelle correspond au sous-réseau 10.2.0.160/28 si l’équipe utilise toujours la première adresse utilisable ?\n10.2.0.160/28 : hôtes 10.2.0.161 à 10.2.0.174", ["10.2.0.160", "10.2.0.161", "10.2.0.174", "10.2.0.175"], 1, "10.2.0.160 est l’adresse réseau et 10.2.0.175 la diffusion. Si la convention est « première adresse utilisable », la passerelle est bien 10.2.0.161.", "difficile"),
      questions.tf("Les plages privées RFC 1918 incluent notamment 10.0.0.0/8 et 172.16.0.0/12.", true, "Vrai : ce sont deux des trois grands espaces privés réservés aux réseaux internes, avec 192.168.0.0/16. Ils ne sont pas routés directement sur Internet.", "facile"),
    ],
  },
};

const ipv6FormatLesson: NewLesson = {
  key: "reseaux-ipv6-format",
  title: "IPv6 : format, notation et préfixes",
  summary: "Lire et écrire correctement une adresse IPv6, comprendre les règles de compression et découper un préfixe site en sous-réseaux /64.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("compter les bits d’une adresse IPv6, développer et compresser une écriture hexadécimale, interpréter un préfixe /32, /48 ou /64, découper un /48 en sous-réseaux /64, et expliquer pourquoi IPv6 change la place du NAT sans supprimer le pare-feu."),
    prerequisites("avoir déjà manipulé des adresses IPv4 et des préfixes CIDR, même de façon simple."),
    scenario("Sahel Services obtient enfin un préfixe IPv6 pour ses bureaux et son site de secours. Nadia ouvre la documentation opérateur et voit des écritures comme 2001:db8:1:12::34/64. Tout le monde autour d’elle dit que « c’est trop long » et qu’il faudra forcément faire du NAT. Nadia doit au contraire comprendre la logique du format, découper son /48 proprement et expliquer à l’équipe pourquoi IPv6 simplifie l’adressage sans rendre le filtrage optionnel."),
    videoSlot("IPv6 sans panique : lire, compresser et découper un préfixe"),
    text("Une adresse IPv6 contient 128 bits, soit quatre fois plus qu’une IPv4. On l’écrit en huit groupes hexadécimaux de 16 bits séparés par des deux-points. Chaque groupe va de 0000 à ffff. Le préfixe indique combien de bits décrivent le réseau : /64 pour un LAN courant, /48 pour un site entier, /32 pour un très grand bloc d’opérateur ou de documentation. Pour les exemples, on utilise toujours le préfixe de documentation 2001:db8::/32."),
    schema("Écriture complète : 2001:0db8:0001:0012:0000:0000:0000:0034\nSans zéros de tête : 2001:db8:1:12:0:0:0:34\nCompression maximale : 2001:db8:1:12::34\n\nRègles\n1. enlève les zéros de tête de chaque groupe\n2. compresse une seule suite continue de groupes 0000 avec ::"),
    text("La compression a deux règles à ne jamais oublier. Tu peux supprimer les zéros de tête dans chaque groupe, mais pas un groupe entier au hasard. Tu peux utiliser :: une seule fois dans l’adresse, sinon on ne sait plus combien de groupes manquent. Ainsi, 2001:db8:0:0:1:0:0:1 devient 2001:db8::1:0:0:1, pas 2001:db8::1::1. Retenir cette discipline évite des erreurs de copie très pénibles en configuration."),
    schema("/32 : très grand bloc, souvent côté opérateur ou documentation\n/48 : préfixe site, soit 65 536 sous-réseaux /64\n/64 : taille normale d’un LAN IPv6\n\n2001:db8:1::/48 découpé en /64\n2001:db8:1:0::/64\n2001:db8:1:1::/64\n2001:db8:1:2::/64\n...\n2001:db8:1:ffff::/64"),
    text("Avec IPv6, on raisonne souvent en préfixes, pas en « compter les hôtes un par un » comme en IPv4. Un /64 offre un espace énorme pour un seul LAN, et c’est normal : de nombreux mécanismes comme l’autoconfiguration s’appuient sur cette taille. Cela change aussi la place du NAT. En IPv6, tu peux donner une vraie adresse globale à chaque machine sans traduire tout le monde derrière une seule IPv4 publique. Cela ne veut pas dire « plus de sécurité par magie » : le rôle de protection revient clairement au pare-feu et aux politiques de filtrage."),
    text("Démonstration guidée : vérifie tes écritures avec un outil avant de documenter un plan d’adressage. Le module Python ipaddress sait compresser correctement une adresse et afficher les premiers /64 contenus dans un /48. C’est pratique quand tu veux réserver des blocs propres pour les utilisateurs, les serveurs et l’administration sans recopier des milliers de sous-réseaux à la main."),
    code("python -c \"import ipaddress as ip; a=ip.ip_interface('2001:db8:1:12::34/64'); print(a.ip.compressed); print(a.ip.exploded); print(a.network); n=ip.ip_network('2001:db8:1::/48');\nfor s in list(n.subnets(new_prefix=64))[:3]: print(s)\"\n# exemple de sortie\n# 2001:db8:1:12::34\n# 2001:0db8:0001:0012:0000:0000:0000:0034\n# 2001:db8:1:12::/64\n# 2001:db8:1::/64\n# 2001:db8:1:1::/64\n# 2001:db8:1:2::/64", "bash"),
    example("Exemple corrigé : 2001:0db8:0001:0012:0000:0000:0000:0034/64 se compresse en 2001:db8:1:12::34/64. Son réseau est 2001:db8:1:12::/64. Si ton site possède 2001:db8:1::/48, tu disposes de 65 536 réseaux /64, donc de quoi séparer très largement utilisateurs, serveurs, Wi-Fi invités et administration sans NAT."),
    mistakes("utiliser :: deux fois dans la même adresse ; oublier qu’un /64 est la taille normale d’un LAN IPv6 ; recopier des adresses de documentation interdites en production ; croire que l’absence de NAT remplace le pare-feu, alors que le filtrage reste indispensable."),
    safety("des adresses IPv6 globales sont directement routables. Publier une machine sur Internet sans règles de filtrage claires reste dangereux, même sans NAT."),
    takeaway("IPv6 est long, mais régulier : 128 bits, huit groupes hexadécimaux, une seule compression :: et une logique de préfixes très propre. Le /48 sert au site, le /64 au LAN. IPv6 réduit le besoin de NAT, mais renforce l’importance d’un pare-feu bien pensé."),
    practice("dans « TP 1 : construire le réseau d’une maison », ajoute un plan IPv6 en /64 pour le LAN principal, puis réserve d’autres /64 du même /48 pour l’extension du réseau. Réinvestis ensuite cette logique dans « Projet final : concevoir et documenter le réseau de Kora ». Termine par le quiz de la leçon."),
    reference("rfc8200"),
    reference("rfc4291"),
    reference("rfc5952"),
  ],
  quiz: {
    title: "Quiz : format IPv6 et préfixes",
    questions: [
      questions.choice("Combien de bits contient une adresse IPv6 ?", ["32", "64", "128", "256"], 2, "Une adresse IPv6 contient 128 bits. C’est ce qui explique son écriture sur huit groupes hexadécimaux et l’immense espace disponible.", "facile"),
      questions.multi("Quelles règles d’écriture IPv6 sont correctes ? (plusieurs réponses)", ["On peut supprimer les zéros de tête d’un groupe", "On peut utiliser :: une seule fois dans une adresse", "Un /48 contient 256 réseaux /64", "Le préfixe 2001:db8::/32 est réservé à la documentation"], [0, 1, 3], "Les zéros de tête peuvent disparaître et :: ne peut servir qu’une seule fois. Le bloc 2001:db8::/32 est bien réservé aux exemples. En revanche, un /48 contient 65 536 réseaux /64, pas 256.", "moyen"),
      questions.choice("Quelle est la bonne forme compressée de 2001:0db8:0001:0012:0000:0000:0000:0034 ?", ["2001:db8:1:12::34", "2001:db8:1:12::0::34", "2001::db8:1:12:34", "2001:db8:1:12:0:0:0:34"], 0, "On enlève les zéros de tête, puis on remplace la plus longue suite de groupes nuls par un seul « :: » : 2001:db8:1:12::34. Les autres écritures sont fausses : deux « :: » rendent l’adresse invalide, 2001::db8:1:12:34 désigne une autre adresse, et 2001:db8:1:12:0:0:0:34 est la même adresse mais n’est pas compressée.", "difficile"),
      questions.tf("En IPv6, le fait de ne pas dépendre du NAT ne dispense pas d’un pare-feu.", true, "Vrai : IPv6 facilite l’adressage de bout en bout, mais le contrôle d’accès reste indispensable. Le NAT ne doit jamais être confondu avec une politique de sécurité.", "moyen"),
    ],
  },
};

const ipv6TypesLesson: NewLesson = {
  key: "reseaux-ipv6-types",
  title: "IPv6 : adresses link-local, globales et autoconfiguration",
  summary: "Reconnaître les grands types d’adresses IPv6, comprendre SLAAC, DHCPv6 et NDP, puis lire une sortie système en double pile.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer les adresses link-local, global unicast, unique local et multicast, expliquer SLAAC et DHCPv6, décrire le rôle de NDP à la place d’ARP, lire une sortie ip -6 addr ou ipconfig, et tester une connectivité IPv6 en double pile."),
    prerequisites("avoir suivi « IPv6 : format, notation et préfixes » et savoir lire un préfixe /64."),
    scenario("Dans les bureaux de Cabinet Moussa, le Wi-Fi semble fonctionner en IPv4 mais l’application cloud répond lentement. Le poste de Nadia reçoit pourtant plusieurs adresses IPv6. L’équipe se demande si ces lignes « fe80:: » sont normales, si le routeur distribue les bonnes informations, et pourquoi ping -6 atteint un serveur alors qu’ARP n’existe plus. Pour dépanner proprement, il faut connaître les familles d’adresses et le mécanisme d’autoconfiguration."),
    videoSlot("IPv6 en pratique : types d’adresses et autoconfiguration"),
    text("IPv6 utilise plusieurs familles d’adresses. Les link-local commencent par fe80::/10 et existent sur chaque interface : elles servent aux échanges locaux, notamment avec le routeur. Les global unicast commencent en pratique dans 2000::/3 et sont routables à grande échelle. Les unique local appartiennent à fc00::/7, avec fd00::/8 pour les usages locaux courants : elles ressemblent aux adresses privées IPv4. Le multicast commence par ff00::/8 et remplace de nombreux usages de la diffusion. En IPv6, il n’existe pas d’adresse de broadcast générale."),
    schema("Type                 Préfixe        Usage principal\nLink-local           fe80::/10      voisinage local, passerelle, NDP\nGlobal unicast       2000::/3       Internet et réseaux interconnectés\nUnique local         fc00::/7       usage interne, souvent fd00::/8\nMulticast            ff00::/8       groupes, par exemple ff02::1 et ff02::2\n\nff02::1 = tous les nœuds du lien\nff02::2 = tous les routeurs du lien"),
    text("Quand une machine démarre, elle crée au minimum une adresse link-local. Ensuite, elle peut recevoir des annonces de routeur et fabriquer seule une adresse globale : c’est le SLAAC, pour Stateless Address Autoconfiguration. L’identifiant d’interface peut venir d’un schéma EUI-64, dérivé d’une MAC, ou plus souvent d’adresses temporaires générées pour protéger la vie privée. DHCPv6 peut compléter ou remplacer cette logique : en mode sans état, il fournit par exemple des DNS ; en mode avec état, il attribue aussi l’adresse. Dans beaucoup de réseaux, on trouve donc un mélange de SLAAC et de DHCPv6."),
    schema("Démarrage IPv6 simplifié\n1. l’interface crée fe80::/10\n2. elle envoie une sollicitation de routeur\n3. le routeur annonce le préfixe du LAN, par exemple 2001:db8:1:20::/64\n4. l’hôte crée une adresse globale et une route par défaut\n5. NDP résout les voisins et remplace ARP"),
    text("NDP, pour Neighbor Discovery Protocol, remplace ARP en IPv6. Il s’appuie sur ICMPv6 pour découvrir les voisins, vérifier qu’une adresse n’est pas déjà utilisée et connaître la passerelle par défaut. Désactiver l’ICMPv6 « pour être plus discret » casse souvent le réseau IPv6 : sans ces messages, les voisins, les routes et l’autoconfiguration fonctionnent mal. C’est une différence importante avec certaines mauvaises habitudes héritées d’IPv4."),
    text("Démonstration guidée : lis la sortie de l’interface avant de conclure qu’IPv6 est en panne. Cherche d’abord une adresse fe80::, signe que la carte est opérationnelle localement. Vérifie ensuite la présence d’une adresse globale ou temporaire dans le /64 attendu. Termine avec ping -6 vers la passerelle ou un serveur du même préfixe. En double pile, il est fréquent qu’IPv4 fonctionne et qu’IPv6 révèle un défaut d’annonce de routeur ou de filtrage ICMPv6."),
    code("# Linux\nip -6 addr show\n# exemple de sortie\n# 2: wlan0: <UP,BROADCAST,RUNNING,MULTICAST>\n#     inet6 2001:db8:1:20::23/64 scope global dynamic\n#     inet6 2001:db8:1:20:9c31:44af:71c2:aa10/64 scope global temporary dynamic\n#     inet6 fe80::b84d:12ff:fe34:5678/64 scope link\n\n# Windows\nipconfig\n\n# Test ciblé IPv6\nping -6 2001:db8:1:20::1", "bash"),
    example("Exemple corrigé : si une machine possède fe80::b84d:12ff:fe34:5678/64 et 2001:db8:1:20::23/64, elle a à la fois sa portée locale et une adresse globale pour le LAN 2001:db8:1:20::/64. Si ping -6 vers 2001:db8:1:20::1 répond, la couche 3 IPv6 fonctionne sur ce segment. Si seule l’adresse fe80:: existe, il faut d’abord vérifier les annonces de routeur ou la configuration DHCPv6."),
    mistakes("croire qu’une adresse fe80:: est une erreur alors qu’elle est normale et obligatoire ; chercher une diffusion IPv6 comme en IPv4, alors que le multicast la remplace ; couper ICMPv6 sans comprendre que NDP et SLAAC en dépendent ; oublier qu’un poste peut avoir plusieurs adresses IPv6 valides en même temps."),
    safety("n’essaie pas de tester des annonces de routeur, du DHCPv6 ou du NDP sur un réseau qui ne t’appartient pas. Une mauvaise publicité de routeur peut perturber tous les voisins du lien."),
    takeaway("IPv6 attribue plusieurs rôles à plusieurs types d’adresses : fe80:: pour le lien local, 2000::/3 pour les adresses globales, fd00::/8 pour l’interne, ff00::/8 pour les groupes. SLAAC et DHCPv6 peuvent coexister, et NDP remplace ARP. Lire une sortie ip -6 addr permet déjà de diagnostiquer beaucoup de pannes."),
    practice("dans « TP 1 : construire le réseau d’une maison », vérifie quelles adresses IPv6 apparaissent sur le LAN et teste la passerelle avec ping -6. Réutilise ensuite ces repères dans « Projet final : concevoir et documenter le réseau de Kora ». Termine par le quiz de la leçon."),
    reference("rfc4861"),
    reference("rfc4862"),
    reference("rfc8415"),
  ],
  quiz: {
    title: "Quiz : types d’adresses IPv6 et autoconfiguration",
    questions: [
      questions.choice("Quel préfixe correspond aux adresses link-local IPv6 ?", ["ff00::/8", "fd00::/8", "fe80::/10", "2000::/3"], 2, "Les adresses link-local commencent par fe80::/10. Elles servent aux échanges sur le lien local, notamment avec la passerelle et NDP.", "facile"),
      questions.multi("Quelles affirmations sur l’autoconfiguration IPv6 sont exactes ? (plusieurs réponses)", ["SLAAC peut créer une adresse globale à partir d’un préfixe annoncé par le routeur", "DHCPv6 sans état peut fournir des informations comme le DNS", "NDP remplace ARP en IPv6", "IPv6 utilise une diffusion générale identique au broadcast IPv4"], [0, 1, 2], "SLAAC, DHCPv6 et NDP sont bien trois briques centrales d’IPv6. En revanche, IPv6 n’a pas de broadcast général : il utilise le multicast pour atteindre des groupes précis.", "moyen"),
      questions.choice("Tu lis cette sortie :\ninet6 2001:db8:1:20::23/64 scope global dynamic\ninet6 fe80::b84d:12ff:fe34:5678/64 scope link\nQuelle conclusion est la plus juste ?", ["La machine ne possède qu’une adresse locale inutilisable", "La machine a une adresse globale et une link-local, ce qui est normal", "L’adresse fe80:: remplace forcément l’adresse 2001:db8:1:20::23", "La présence de deux adresses prouve une attaque"], 1, "Cette combinaison est normale : l’interface garde une adresse link-local et peut aussi avoir une adresse globale dans le /64 du LAN. Deux adresses IPv6 sur la même interface ne signalent pas une attaque à elles seules.", "difficile"),
      questions.tf("Bloquer aveuglément ICMPv6 peut casser NDP et donc perturber le fonctionnement normal d’IPv6.", true, "Vrai : NDP, la découverte de routeur et plusieurs mécanismes essentiels d’IPv6 s’appuient sur ICMPv6. Le filtrer sans discernement casse souvent le réseau.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c2:2",
    position: 1,
    existing: { fromTitle: "Les couches du réseau" },
    title: "Fondamentaux des réseaux",
    description: "Tu poses ici le vocabulaire et les réflexes qui serviront dans tout le parcours : équipements, couches, encapsulation et lecture d’un trajet réseau réel. Critères de réussite : expliquer le rôle d’un commutateur, d’un routeur et d’une passerelle ; situer un protocole, une commande ou une panne dans la bonne couche ; raconter le voyage d’une requête web en citant ce qui change à chaque saut.",
    lessons: [lanWan, osiPractice, encapsulationLesson],
  },
  {
    key: "c2:3",
    position: 2,
    existing: { fromTitle: "Adresser et segmenter" },
    title: "Adressage IPv4",
    description: "Ce module transforme les bases IPv4 en vraie méthode de planification : lire, découper, puis attribuer des sous-réseaux adaptés à une organisation qui grandit. Critères de réussite : reconnaître une plage privée RFC 1918 ; choisir un préfixe cohérent pour un besoin donné ; produire un plan VLSM sans chevauchement avec une convention de passerelle claire.",
    lessons: [
      { key: "reseaux-ipv4", existing: true },
      { key: "reseaux-cidr", existing: true },
      vlsmLesson,
    ],
  },
  {
    key: "c2:7",
    position: 3,
    title: "Adressage IPv6",
    description: "Tu apprends ici à lire IPv6 sans le subir : écriture, préfixes, types d’adresses et mécanismes d’autoconfiguration utiles au diagnostic moderne. Critères de réussite : compresser correctement une adresse IPv6 ; découper un /48 en /64 sans erreur ; interpréter une sortie système montrant des adresses link-local, globales et temporaires.",
    lessons: [ipv6FormatLesson, ipv6TypesLesson],
  },
];
