import {
  code, example, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const aclLesson: NewLesson = {
  key: "reseaux-acl",
  title: "Listes de contrôle d’accès : filtrer sans se bloquer",
  summary: "Comprends l’ordre d’évaluation d’une ACL, choisis son emplacement et écris des règles Cisco IOS exactes sans couper l’accès légitime.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer une ACL standard d’une ACL étendue, choisir son placement, écrire un masque inverse correct, interpréter ses compteurs, et éviter de te bloquer toi-même."),
    prerequisites("avoir vu le routage IPv4, les VLAN et les ports réseau."),
    scenario("Nadia administre le réseau de Baobab Tech. Les invités doivent sortir sur Internet, mais ne doivent jamais atteindre le VLAN d’administration. Si elle écrit une règle trop large, elle bloque des usages légitimes. Si elle oublie une règle, elle laisse passer trop de trafic."),
    videoSlot("Écrire une ACL Cisco sans se couper l’accès"),
    text("Une ACL, ou liste de contrôle d’accès, est une suite de règles lues de haut en bas. La première correspondance gagne, puis l’équipement s’arrête. À la fin, un refus implicite bloque tout ce qui n’a pas été autorisé. Une seule ligne mal placée peut donc couper un service entier."),
    schema("Type d’ACL      Ce qu’elle regarde        Où la placer en général\nStandard        source seulement           près de la destination\nÉtendue         source, destination,\n                protocole, port            près de la source\n\nFin implicite   deny any"),
    text("Cisco IOS utilise souvent des masques inverses, ou wildcards. C’est l’inverse du masque réseau : 255 devient 0, 0 devient 255. Pour un /24, le wildcard vaut 0.0.0.255. Une ACL étendue permet de dire « les invités ne parlent pas à l’administration, mais peuvent aller ailleurs ». Une ACL standard ne filtre ni par port ni par destination. Tu peux les écrire sous forme numérotée, par exemple « access-list 10 permit 10.3.130.0 0.0.0.255 », ou nommée avec « ip access-list extended NOM »."),
    example("Exemple corrigé : le VLAN invités est 10.3.130.0/24 et le VLAN d’administration 10.3.120.0/24. Le masque /24 devient le wildcard 0.0.0.255. La règle « deny ip 10.3.130.0 0.0.0.255 10.3.120.0 0.0.0.255 » bloque uniquement ce trajet. Elle ne bloque pas l’accès des invités au web public, parce que la destination Internet ne fait pas partie de 10.3.120.0/24."),
    text("Démonstration guidée : sur Cisco IOS, applique l’ACL en entrée sur l’interface du VLAN invités. Le trafic indésirable est stoppé avant de traverser le réseau. Note le « permit ip any any » final : sans lui, les invités perdent aussi leur accès Internet."),
    code("ip access-list extended INVITES-FILTRE\n deny ip 10.3.130.0 0.0.0.255 10.3.120.0 0.0.0.255\n permit ip any any\n!\ninterface GigabitEthernet0/0.130\n encapsulation dot1Q 130\n ip address 10.3.130.1 255.255.255.0\n ip access-group INVITES-FILTRE in\n!\nshow access-lists\n\nExtended IP access list INVITES-FILTRE\n    10 deny ip 10.3.130.0 0.0.0.255 10.3.120.0 0.0.0.255 (14 matches)\n    20 permit ip any any (126 matches)\n# exemple de sortie : les compteurs montrent qu’un trafic a bien été bloqué, puis que le reste a continué.", "bash"),
    text("Tu peux ajouter « log » à une règle sensible, mais évite de tout journaliser : sur un équipement modeste, trop de journaux gênent le diagnostic. Sous Linux, l’idée reste la même avec nftables ou iptables : un ordre de règles, une politique par défaut, puis des journaux ciblés."),
    schema("Erreur classique                     Effet\nACL appliquée en out au mauvais endroit  le trafic traverse déjà une partie du réseau\npermit trop tôt                          un deny plus précis ne sera jamais lu\noubli du permit final                    coupure involontaire\nACL sur les lignes VTY mal testée        perte de l’accès d’administration"),
    mistakes("placer une ACL étendue près de la destination, alors qu’elle est plus utile près de la source ; confondre masque réseau et wildcard ; oublier qu’il existe un refus implicite final ; tester directement sur les lignes VTY sans console de secours, puis se bloquer hors de l’équipement."),
    safety("n’applique ces règles que sur un réseau que tu administres. Prépare un retour arrière, conserve un accès console si possible, et note l’état avant modification pour éviter une coupure longue."),
    takeaway("une ACL est lue de haut en bas, la première correspondance gagne, puis le refus implicite termine le travail. Les ACL étendues filtrent finement, et leur emplacement compte autant que leur syntaxe."),
    practice("ouvre le laboratoire « TP 2 : VLAN, trunk et routage inter-VLAN pour la PME Kora », ajoute une ACL entre les VLAN, puis vérifie par des tests que seul le flux prévu passe. Termine par le quiz de la leçon."),
    reference("anssiFiltrage"),
    reference("nistFirewalls"),
    reference("netacad"),
  ],
  quiz: {
    title: "Quiz : ACL réseau",
    questions: [
      questions.choice("Quel énoncé décrit correctement le fonctionnement d’une ACL Cisco ?", ["Toutes les règles sont évaluées, puis la plus précise gagne", "La première règle correspondante décide, puis l’évaluation s’arrête", "Les règles « deny » passent toujours avant les « permit »", "Une ACL sans « permit » laisse passer le trafic local"], 1, "Cisco lit l’ACL ligne par ligne et s’arrête dès qu’une règle correspond. Il n’existe pas de « règle la plus précise » calculée à la fin, et le refus implicite final bloque tout ce qui n’a pas été autorisé.", "facile"),
      questions.tf("Pour le réseau 10.3.130.0/24, le wildcard correct dans une ACL Cisco est 0.0.0.255.", true, "C’est vrai : le masque 255.255.255.0 devient 0.0.0.255 dans une ACL. L’erreur tentante consiste à recopier le masque réseau tel quel, ce qui change complètement la portée de la règle.", "moyen"),
      questions.multi("Tu dois bloquer les invités vers l’administration, sans empêcher leur sortie Internet. Quelles décisions sont pertinentes ? (plusieurs réponses)", ["Utiliser une ACL étendue", "L’appliquer en entrée sur l’interface du VLAN invités", "Supprimer tout « permit » final", "Tester les compteurs avec « show access-lists »"], [0, 1, 3], "Une ACL étendue permet de viser précisément la source et la destination, puis les compteurs confirment le résultat. Retirer tout « permit » final couperait aussi les autres flux légitimes à cause du refus implicite.", "difficile"),
      questions.choice("Lis cet extrait : « 10 deny ip 10.3.130.0 0.0.0.255 10.3.120.0 0.0.0.255 (14 matches) » puis « 20 permit ip any any (126 matches) ». Que comprends-tu ?", ["L’ACL n’est pas utilisée, car il y a seulement 14 correspondances", "Des invités ont tenté d’atteindre l’administration, mais le reste du trafic continue", "Tout le trafic des invités est bloqué", "Le routeur doit redémarrer pour appliquer les règles"], 1, "Le compteur du « deny » montre des tentatives bloquées vers l’administration, tandis que le compteur du « permit ip any any » prouve que les autres flux passent encore. C’est précisément le comportement attendu ici.", "moyen"),
    ],
  },
};

const segmentationLesson: NewLesson = {
  key: "reseaux-segmentation-dmz",
  title: "Segmentation, DMZ et pare-feu : cloisonner pour limiter les dégâts",
  summary: "Apprends à découper un réseau en zones, à définir une DMZ utile et à relire une matrice de flux sans confondre VLAN et frontière de sécurité.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("identifier les zones d’un réseau, expliquer le rôle d’une DMZ, lire une matrice de flux, distinguer filtrage simple et inspection d’état, et repérer une segmentation trop permissive."),
    prerequisites("connaître les VLAN, l’adressage IPv4 et les bases du routage. Revois aussi « Listes de contrôle d’accès : filtrer sans se bloquer » si nécessaire."),
    scenario("Moussa publie un site web pour Sahel Services. Le serveur doit être accessible depuis Internet, mais la comptabilité et l’administration ne doivent jamais être exposées. Jusqu’ici, tout est dans le même réseau. Moussa doit cloisonner avant qu’un incident ne se produise."),
    videoSlot("Pourquoi une DMZ protège mieux qu’un seul grand LAN"),
    text("Segmenter, c’est séparer le réseau en zones qui n’ont pas toutes les mêmes droits. On crée par exemple un LAN bureautique, une zone invités, une zone d’administration et une DMZ. L’objectif est de limiter les dégâts : si un poste invité est compromis, il ne doit pas atteindre le serveur de paie ni l’interface d’administration du pare-feu."),
    schema("Internet\n   |\n[ Pare-feu ]\n  |   |   \\\n  |   |    +-- DMZ : 172.16.10.0/24\n  |   +------- LAN : 10.1.110.0/24\n  +----------- Invités : 10.1.130.0/24\n\nAdministration : 10.1.120.0/24, séparée du LAN"),
    text("Une DMZ, ou zone démilitarisée, héberge les services exposés, comme un site web public. On accepte qu’elle soit plus exposée, donc on lui donne le strict nécessaire. Politique par défaut : « tout refuser », puis ouvertures précises. Un VLAN ne suffit pas à lui seul : sans filtrage de couche 3 ou 4, deux VLAN peuvent encore communiquer."),
    schema("Source              Destination         Port / protocole   Décision\nInternet            172.16.10.10        TCP 443            autoriser\nLAN 10.1.110.0/24   172.16.10.20        TCP 22             autoriser admin\nInvités 10.1.130.0  10.1.120.0/24       any                refuser\nDMZ                 LAN                  any                refuser\nAdministration      Pare-feu             HTTPS, SSH         autoriser"),
    example("Exemple corrigé : si ton site public est sur 172.16.10.10, une redirection de port 443 vers ce serveur est raisonnable. Publier directement un serveur du LAN en 10.1.110.20 ouvre au contraire un chemin vers une zone qui contient aussi d’autres postes."),
    text("Démonstration guidée : imagine qu’un attaquant obtienne un accès sur le serveur web de la DMZ. Si les règles sont bien faites, ce serveur peut répondre aux clients Internet, mais ne peut pas initier de connexion vers le LAN. L’inspection d’état laisse revenir le trafic de réponse, sans transformer la DMZ en point de départ vers l’intérieur."),
    code("Règles de pare-feu : exemple de compteurs\n1  ALLOW Internet -> 172.16.10.10 TCP 443 (221 correspondances)\n2  DENY  172.16.10.0/24 -> 10.1.110.0/24 any (3 correspondances)\n3  DENY  10.1.130.0/24 -> 10.1.120.0/24 any (8 correspondances)\n4  ALLOW 10.1.120.0/24 -> 172.16.10.20 TCP 22 (17 correspondances)\n# exemple de sortie : le web public passe, l’administration garde son accès de maintenance, et les flux interdits restent bloqués.", "text"),
    text("La segmentation doit vivre dans le temps. Une matrice de flux se relit et se justifie. Les mauvaises habitudes sont connues : règle « any any », VLAN d’administration partagé, exceptions temporaires jamais retirées, absence de journaux. Une bonne documentation de flux aide autant la sécurité que le dépannage."),
    mistakes("croire qu’un VLAN est automatiquement une barrière de sécurité ; ouvrir une règle « permit ip any any » « pour tester », puis l’oublier ; placer l’administration dans le même segment que des postes ordinaires ; ne jamais revoir les flux après l’ajout d’un nouveau service."),
    safety("ne teste un filtrage ou une redirection de port que sur une infrastructure que tu gères. Exposer un service sur Internet sans autorisation ni sauvegarde de configuration est risqué et parfois interdit par la politique interne."),
    takeaway("segmenter réduit l’impact d’une compromission. La DMZ accueille les services exposés, mais n’a pas de voie libre vers le LAN. Une matrice de flux claire vaut mieux qu’un empilement de règles improvisées."),
    practice("dans le laboratoire « Projet final : concevoir et documenter le réseau de Kora », sépare les zones, définis les flux utiles entre elles et justifie chaque ouverture. Termine par le quiz de la leçon."),
    reference("anssiPareFeux"),
    reference("anssiNettoyage"),
    reference("nistFirewalls"),
  ],
  quiz: {
    title: "Quiz : segmentation et DMZ",
    questions: [
      questions.choice("Quel est le rôle principal d’une DMZ ?", ["Héberger les postes les plus sensibles de l’entreprise", "Recevoir les services exposés tout en limitant leur accès au LAN", "Remplacer toutes les ACL internes", "Éviter l’usage d’un pare-feu"], 1, "La DMZ accueille les services visibles depuis l’extérieur, mais avec des règles strictes vers l’intérieur. L’erreur tentante est d’y mettre des postes sensibles, alors qu’elle est justement plus exposée que le LAN.", "facile"),
      questions.tf("Un VLAN suffit à lui seul pour garantir qu’un serveur est isolé du reste du réseau.", false, "C’est faux : un VLAN sépare les domaines de diffusion, pas la politique de sécurité complète. Sans routage filtré, ACL ou pare-feu, le trafic peut encore circuler entre réseaux logiques.", "moyen"),
      questions.multi("Dans une matrice de flux saine, quelles décisions sont cohérentes ? (plusieurs réponses)", ["Autoriser Internet vers le serveur web public en TCP 443", "Refuser DMZ vers LAN par défaut", "Autoriser les invités vers l’administration pour « simplifier le support »", "Autoriser l’administration vers la DMZ pour la maintenance"], [0, 1, 3], "Le web public doit parfois être publié, et l’administration doit pouvoir maintenir les serveurs. En revanche, laisser les invités parler à l’administration détruit précisément l’objectif du cloisonnement.", "difficile"),
      questions.choice("Tu lis : « 20 deny ip 172.16.10.0 0.0.0.255 10.1.110.0 0.0.0.255 (3 matches) ». Quelle conclusion est la plus juste ?", ["La règle ne sert à rien, car trois correspondances sont trop peu", "Le serveur web public a tenté d’atteindre le LAN et a été bloqué", "Le LAN a été complètement coupé d’Internet", "L’ACL empêche les clients Internet d’accéder au site"], 1, "Le compteur indique bien des paquets issus de la DMZ vers le LAN qui ont été stoppés. C’est précisément un signe que la segmentation joue son rôle, même si le nombre de tentatives reste faible.", "moyen"),
    ],
  },
};

const wifiLesson: NewLesson = {
  key: "reseaux-wifi-durcissement",
  title: "Wi-Fi et équipements : sécuriser l’accès et l’administration",
  summary: "Sécurise un réseau Wi-Fi et les équipements qui le supportent : choix du chiffrement, isolation des invités, SSH, mises à jour et réduction de la surface d’exposition.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("comparer WPA2, WPA3 et 802.1X, isoler un réseau invités, repérer les faux bons réflexes comme le SSID caché, durcir l’administration d’un équipement, et lire une configuration IOS simple."),
    prerequisites("connaître les VLAN, les services réseau et les bases de l’administration d’un routeur ou d’un commutateur."),
    scenario("Fatou gère le Wi-Fi de Cabinet Moussa. Le réseau des salariés doit rester stable, le réseau invités ne doit voir aucune imprimante interne, et plusieurs équipements sont encore administrés en Telnet avec le mot de passe d’usine. Un faux point d’accès affichant un nom presque identique a déjà été vu dans le bâtiment voisin."),
    videoSlot("Durcir un Wi-Fi et l’administration d’un switch en 8 minutes"),
    text("La sécurité Wi-Fi commence par le bon mode. WEP est cassé et ne doit plus être utilisé. WPA2-PSK reste fréquent, mais dépend d’une phrase secrète solide et unique. WPA3-SAE améliore la résistance aux attaques hors ligne. En entreprise, 802.1X avec un serveur RADIUS reste souvent le meilleur choix : chaque utilisateur s’authentifie individuellement."),
    schema("Mode                  Niveau actuel         Remarque\nWEP                   à proscrire            cassé depuis longtemps\nWPA2-PSK              acceptable             dépend d’une phrase forte\nWPA3-SAE              meilleur               protège mieux l’échange initial\n802.1X + RADIUS       recommandé en entreprise\n                                           identité par utilisateur"),
    text("Le réseau invités doit être isolé, souvent dans un VLAN séparé, avec accès Internet seulement. Cacher le SSID n’est pas une vraie protection : un client déjà connecté le révèle. Le WPS augmente le risque et doit être désactivé. Méfie-toi aussi des faux points d’accès, ou evil twins, qui imitent un réseau légitime pour voler des identifiants."),
    example("Exemple corrigé : si les salariés utilisent le SSID « Cabinet-Moussa », un attaquant peut diffuser « Cabinet-Moussa_Free » dans le hall. Un téléphone qui s’y connecte par erreur peut livrer du trafic sensible. Un réseau invités séparé, avec portail ou mot de passe dédié, réduit déjà beaucoup le risque de mélange."),
    text("Démonstration guidée : le Wi-Fi n’est pas le seul sujet. L’équipement lui-même doit être durci. Sur Cisco IOS, remplace Telnet par SSH, définis un secret robuste, coupe les ports inutilisés et réserve l’administration à un VLAN dédié. Les commandes suivantes sont propres à Cisco."),
    code("hostname SW-ATLAS-1\nip domain-name atlas.local\ncrypto key generate rsa modulus 2048\nip ssh version 2\nusername admin privilege 15 secret <mot-de-passe-fort>\nenable secret <autre-secret-fort>\nline vty 0 4\n login local\n transport input ssh\n!\ninterface range FastEthernet0/10 - 24\n shutdown\n!\nshow ip ssh\n\nSSH Enabled - version 2.0\nAuthentication timeout: 120 secs; Authentication retries: 3\n# exemple de sortie : Telnet n’est plus accepté sur les lignes VTY, seules les sessions SSH sont permises.", "bash"),
    schema("Checklist de durcissement\n1. mot de passe d’usine changé\n2. mises à jour appliquées\n3. SSH activé, Telnet coupé\n4. VLAN de gestion séparé\n5. ports inutilisés arrêtés\n6. journaux envoyés vers un serveur"),
    text("Les bandes 2,4 GHz et 5 GHz ont aussi un impact pratique. La première porte souvent plus loin, mais subit plus d’interférences. La seconde offre souvent de meilleurs débits, mais traverse moins bien les obstacles. Un mauvais choix radio pousse parfois des équipes à ouvrir des réglages risqués « pour que ça marche ». Corrige la conception, pas la sécurité."),
    mistakes("garder le mot de passe ou le SSID par défaut ; croire qu’un SSID caché remplace un vrai chiffrement ; laisser WPS actif sur un équipement exposé ; administrer encore les équipements en Telnet, alors que SSH est disponible."),
    safety("ne tente jamais de casser un Wi-Fi qui n’est pas à toi ou pour lequel tu n’as pas d’autorisation explicite. Même un test « rapide » sur le réseau d’un voisin ou d’un café peut être illégal et nuisible."),
    takeaway("un Wi-Fi sûr repose sur un bon mode de sécurité, une vraie séparation des invités et des équipements bien administrés. SSH, mises à jour et ports inutilisés coupés valent autant que le choix WPA2 ou WPA3."),
    practice("dans le laboratoire « Projet final : concevoir et documenter le réseau de Kora », propose une politique Wi-Fi, un réseau invités isolé et un plan de durcissement des équipements d’accès. Termine par le quiz de la leçon."),
    reference("anssiWifi"),
    reference("anssiHygiene"),
    reference("nistWlan"),
  ],
  quiz: {
    title: "Quiz : sécurité Wi-Fi et durcissement",
    questions: [
      questions.choice("Quel mode de sécurité faut-il proscrire sur un Wi-Fi moderne ?", ["WPA3-SAE", "WPA2-PSK", "WEP", "802.1X"], 2, "WEP est cassé depuis longtemps et ne doit plus être utilisé. Le piège serait de le conserver pour de vieux équipements, alors qu’il affaiblit tout le réseau sans réelle protection.", "facile"),
      questions.tf("Cacher le SSID est une mesure suffisante pour protéger un réseau Wi-Fi d’entreprise.", false, "C’est faux : un client déjà associé révèle rapidement le nom du réseau, et le chiffrement reste l’élément essentiel. Un SSID caché peut même compliquer le support sans apporter de vraie sécurité.", "moyen"),
      questions.multi("Quelles mesures de durcissement sont pertinentes sur un commutateur ou un routeur d’accès ? (plusieurs réponses)", ["Activer SSH et couper Telnet", "Laisser les ports inutilisés ouverts « au cas où »", "Changer les mots de passe par défaut", "Séparer le VLAN de gestion"], [0, 2, 3], "SSH, les secrets robustes et un VLAN de gestion dédié réduisent fortement la surface d’attaque. Garder des ports inutilisés actifs, au contraire, offre des points d’entrée faciles et peu justifiés.", "moyen"),
      questions.choice("Tu lis « transport input ssh » sous « line vty 0 4 ». Que signifie cette ligne ?", ["Les utilisateurs Wi-Fi doivent se connecter en WPA3", "Les accès distants d’administration n’acceptent plus Telnet", "Le commutateur n’accepte plus aucune connexion distante", "SSH est autorisé seulement sur le VLAN invités"], 1, "Cette commande restreint les lignes VTY aux connexions SSH. Elle ne concerne pas directement le Wi-Fi des clients, mais l’administration de l’équipement lui-même.", "difficile"),
    ],
  },
};

const troubleshootingLesson: NewLesson = {
  key: "reseaux-depannage",
  title: "Méthode de dépannage et commandes de diagnostic",
  summary: "Adopte une méthode de dépannage réseau reproductible, du loopback au DNS, en t’appuyant sur des commandes simples et des hypothèses vérifiables.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("suivre une méthode de dépannage en sept étapes, choisir un point de départ pertinent, exécuter les commandes utiles, interpréter un « ping » ou un « tracert », et documenter la cause réelle."),
    prerequisites("avoir vu l’adressage IP, DNS, DHCP, les ports et le routage de base."),
    scenario("Awa reçoit un ticket : « le site compta.atlas.example ne s’ouvre plus ». Sur certains postes, Internet fonctionne encore. Sur d’autres, seul le nom du site pose problème. Si Awa change tout à la fois, elle risque d’aggraver l’incident. Elle doit avancer par tests courts, du plus simple au plus ciblé."),
    videoSlot("Dépanner un problème réseau sans partir dans tous les sens"),
    text("Une bonne méthode de dépannage suit sept étapes : définir le symptôme, collecter les faits, formuler une hypothèse, tester une seule idée à la fois, corriger, vérifier le retour à la normale, puis documenter. Cela paraît scolaire, mais c’est ce qui évite les changements au hasard. En réseau, un même symptôme visible par l’utilisateur peut venir d’une couche très différente."),
    schema("Échelle de tests\n1. 127.0.0.1\n2. sa propre IP\n3. la passerelle\n4. une IP distante\n5. un nom DNS\n\nSi l’étape 4 marche mais pas la 5 : pense DNS"),
    text("Tu peux aussi choisir une stratégie : de bas en haut, de haut en bas, diviser pour régner, ou suivre le chemin. Sur un incident simple, l’échelle de tests suffit souvent. Si le loopback fonctionne mais pas la passerelle, pense interface locale, câble, Wi-Fi, DHCP ou VLAN. Si l’IP distante répond mais pas le nom, le problème vient probablement du DNS, pas du routage."),
    schema("Symptôme observé                  Cause probable\nAPIPA 169.254.x.x                 pas de réponse DHCP\nnom KO, IP OK                     DNS en cause\npasserelle KO                     panne locale ou VLAN\ntracert bloqué dès le 1er saut    routeur local ou pare-feu\nport précis inaccessible          service arrêté ou filtrage"),
    text("Démonstration guidée : traite le ticket d’Awa sans sauter d’étape. Commence par lire l’adresse reçue, puis teste la passerelle, une IP publique, enfin le nom concerné. Ici, la cohérence entre les sorties vaut plus que la quantité de commandes tapées."),
    code("ipconfig /all\n\nEthernet adapter Ethernet0:\n   IPv4 Address. . . . . . . . . . . : 192.168.10.34\n   Default Gateway . . . . . . . . . : 192.168.10.1\n   DNS Servers . . . . . . . . . . . : 192.168.10.53\n\nping 192.168.10.1\n# exemple de sortie\n# Reply from 192.168.10.1: bytes=32 time=2ms TTL=64\n\nping 1.1.1.1\n# Reply from 1.1.1.1: bytes=32 time=31ms TTL=57\n\nnslookup compta.atlas.example\n# Serveur :  dns.atlas.local\n# Address:  192.168.10.53\n# *** dns.atlas.local can't find compta.atlas.example: Non-existent domain", "text"),
    example("Exemple corrigé : la passerelle répond, une IP publique répond aussi, mais « nslookup » renvoie « Non-existent domain ». Tu ne dois donc ni changer le câble ni redémarrer le commutateur. L’hypothèse la plus solide est un problème DNS : zone absente, enregistrement supprimé ou mauvais serveur configuré."),
    text("« tracert » ou « traceroute » aide quand l’échec est plus loin. La commande envoie des paquets avec un TTL croissant pour découvrir les sauts. Si le premier saut ne répond pas, cherche près de toi. Si seuls les derniers sauts échouent, le problème est plus loin dans le chemin. « arp -a », « route print », « ss » ou « netstat » complètent ensuite le diagnostic selon le symptôme."),
    code("tracert 172.16.10.20\n\nTracing route to 172.16.10.20 over a maximum of 30 hops\n\n  1    <1 ms    <1 ms    <1 ms  192.168.10.1\n  2     3 ms     2 ms     3 ms  10.2.0.1\n  3     *        *        *     Request timed out.\n\n# exemple de sortie : le poste atteint sa passerelle et le routeur amont, puis le chemin s’interrompt après.", "text"),
    mistakes("changer plusieurs paramètres en même temps ; ignorer ce qui marche déjà, alors que c’est une preuve utile ; oublier de noter l’heure, la commande et le résultat ; conclure « le réseau est cassé » sans préciser la couche ni l’étape qui échoue."),
    takeaway("un bon dépannage réduit l’incertitude pas à pas. Teste d’abord près de toi, puis plus loin. Quand l’IP marche mais pas le nom, pense DNS avant de tout toucher."),
    practice("dans le laboratoire « TP 4 : incident réseau chez Kora », suis une méthode de test du poste jusqu’au service et note précisément le moment où ça casse. Termine par le quiz de la leçon."),
    reference("msIpconfig"),
    reference("msPing"),
    reference("msTracert"),
  ],
  quiz: {
    title: "Quiz : méthode de dépannage",
    questions: [
      questions.choice("Quel ordre de test est le plus logique au début d’un dépannage poste client ?", ["Nom DNS, IP publique, passerelle, loopback", "Loopback, propre IP, passerelle, IP distante, nom DNS", "IP distante, passerelle, DNS, loopback", "ARP, SSH, HTTPS, NTP"], 1, "On part du plus proche au plus lointain pour isoler rapidement la zone en panne. Commencer par le nom DNS ou un service lointain masque souvent un problème beaucoup plus local.", "facile"),
      questions.tf("Si « ping 1.1.1.1 » répond mais que « nslookup compta.atlas.example » échoue, le problème le plus probable n’est pas le routage.", true, "C’est vrai : le chemin IP vers l’extérieur fonctionne déjà. Le symptôme pointe plutôt vers la résolution de nom, un enregistrement absent, ou un mauvais serveur DNS configuré.", "moyen"),
      questions.multi("Quelles pratiques améliorent vraiment le dépannage ? (plusieurs réponses)", ["Tester une hypothèse à la fois", "Noter les résultats et l’heure", "Modifier simultanément le DNS, le câble et la passerelle pour aller plus vite", "Comparer ce qui marche et ce qui échoue"], [0, 1, 3], "Un dépannage utile produit des preuves. Changer plusieurs choses à la fois empêche de savoir laquelle a eu un effet, et rend le retour arrière plus difficile en cas d’erreur.", "moyen"),
      questions.choice("Lis ce « tracert » : saut 1 = 192.168.10.1, saut 2 = 10.2.0.1, puis timeouts. Quelle conclusion est la plus prudente ?", ["La carte réseau locale est forcément morte", "Le poste ne voit pas sa passerelle", "Le chemin fonctionne au moins jusqu’au routeur amont, puis l’échec se situe plus loin", "Le DNS du poste est forcément faux"], 2, "Le poste atteint clairement sa passerelle et un routeur amont. Le problème n’est donc plus au niveau du lien local immédiat. Le DNS peut être concerné dans d’autres cas, mais pas ce que prouve cet extrait.", "difficile"),
    ],
  },
};

const showLesson: NewLesson = {
  key: "reseaux-lire-show",
  title: "Lire les sorties d’un équipement : interfaces, VLAN et routes",
  summary: "Lis efficacement les commandes « show » les plus utiles de Cisco IOS pour comprendre l’état réel d’un équipement sans te perdre dans les détails.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("reconnaître les modes IOS, utiliser l’aide « ? », interpréter l’état d’une interface, lire des VLAN et des trunks, relire une table de routage, et sauvegarder la configuration."),
    prerequisites("avoir vu les VLAN, le routage et les ACL. Quelques bases Cisco IOS sont utiles."),
    scenario("Koffi reçoit un switch et un routeur déjà configurés, mais plusieurs postes n’atteignent plus le serveur interne. Personne n’a touché au câblage selon l’équipe, pourtant un port semble silencieux et un VLAN manque d’un côté du trunk. Au lieu de modifier à l’aveugle, Koffi doit lire ce que disent vraiment les équipements."),
    videoSlot("Comprendre les commandes « show » qui sauvent du temps"),
    text("Sur Cisco IOS, le mode utilisateur te laisse consulter peu d’informations, le mode privilégié (« enable ») donne accès aux commandes « show », et le mode de configuration modifie l’équipement. L’aide « ? » évite d’inventer une syntaxe. En diagnostic, le plus utile est de bien lire quelques sorties fiables."),
    schema("Modes IOS\n>\n  mode utilisateur\n#\n  mode privilégié\n(config)#\n  configuration globale\n\nRéflexe : show ?"),
    text("« show ip interface brief » donne une vue rapide des interfaces : adresse IP, état administratif et état du protocole. « up/up » signifie qu’un lien fonctionne. « administratively down/down » indique un port coupé par configuration. « up/down » signale souvent un souci de couche 2, d’encapsulation ou de voisinage."),
    code("show ip interface brief\n\nInterface              IP-Address      OK? Method Status                Protocol\nGigabitEthernet0/0     unassigned      YES unset  up                    up\nGigabitEthernet0/0.110 10.1.110.1      YES manual up                    up\nGigabitEthernet0/0.120 10.1.120.1      YES manual up                    up\nGigabitEthernet0/0.130 10.1.130.1      YES manual up                    up\nGigabitEthernet0/1     unassigned      YES unset  administratively down down\n# exemple de sortie : Gi0/1 est coupée par configuration, pas par panne physique.", "text"),
    text("Pour les VLAN, commence par « show vlan brief », puis « show interfaces trunk ». La première commande dit quels ports sont access dans quel VLAN. La seconde dit quels VLAN traversent le trunk. C’est souvent là qu’un VLAN oublié explique une panne ciblée."),
    code("show vlan brief\n\nVLAN Name                             Status    Ports\n110  Utilisateurs                      active    Fa0/1, Fa0/2\n120  Administration                    active    Fa0/3\n130  Invites                           active    Fa0/4\n199  Gestion                           active    Fa0/24\n\nshow interfaces trunk\n\nPort        Mode         Encapsulation  Status        Native vlan\nFa0/24      on           802.1q         trunking      199\n\nPort        Vlans allowed on trunk\nFa0/24      110,120,199\n# exemple de sortie : le VLAN 130 manque dans la liste autorisée, les invités ne passeront donc pas par ce trunk.", "text"),
    example("Exemple corrigé : si les postes invités sur le VLAN 130 n’atteignent aucune passerelle, mais que les VLAN 110 et 120 fonctionnent, la sortie ci-dessus donne un indice fort. Le trunk autorise 110,120,199, mais pas 130. C’est donc un oubli sur le trunk, pas un problème DNS."),
    text("« show ip route » explique ce que le routeur sait joindre. Cherche les entrées « C », « L » et « S ». Une absence de route retour peut casser un service sans que l’interface locale semble en panne. « show access-lists » et « show ip nat translations » complètent l’analyse."),
    schema("Codes fréquents\nC  connected\nL  local\nS  static\nR  RIP\nO  OSPF\n\nSauvegarde : copy running-config startup-config"),
    text("Démonstration guidée : lis d’abord l’état des interfaces, puis les VLAN, ensuite les routes, enfin les ACL. Quand tu as corrigé, enregistre avec « copy running-config startup-config », sinon une coupure d’alimentation efface le travail."),
    mistakes("confondre « down/down » et « administratively down/down » ; lire « show vlan brief » sans vérifier aussi le trunk ; corriger avant d’avoir relevé la sortie initiale ; oublier de sauvegarder la configuration après validation."),
    takeaway("les commandes « show » racontent l’état réel, pas l’intention. Lis d’abord les interfaces, puis les VLAN et les routes. Un seul VLAN absent d’un trunk peut suffire à expliquer une panne très ciblée."),
    practice("dans le laboratoire « TP 4 : incident réseau chez Kora », relève les sorties « show », explique ce qu’elles prouvent, puis corrige uniquement ce qui est nécessaire. Termine par le quiz de la leçon."),
    reference("netacad"),
    reference("packetTracer"),
    reference("anssiHygiene"),
  ],
  quiz: {
    title: "Quiz : lire les sorties IOS",
    questions: [
      questions.choice("Que signifie « administratively down/down » dans « show ip interface brief » ?", ["Le câble est probablement coupé", "Le port est désactivé par configuration", "Le voisin répond trop lentement", "Le VLAN natif est incohérent"], 1, "Cet état signifie que l’interface est coupée par commande, souvent avec « shutdown ». Le piège classique consiste à chercher une panne physique alors que l’équipement lui-même interdit déjà l’activation du port.", "facile"),
      questions.tf("Si un VLAN manque dans « show interfaces trunk », des postes de ce VLAN peuvent échouer même si « show vlan brief » semble correct.", true, "C’est vrai : un port access peut être bien placé dans le bon VLAN sur un switch, mais si le trunk n’autorise pas ce VLAN jusqu’au routeur ou au switch voisin, le trafic s’arrête quand même.", "moyen"),
      questions.multi("Quelles commandes sont directement utiles pour comprendre un problème de segmentation sur Cisco ? (plusieurs réponses)", ["show vlan brief", "show interfaces trunk", "show ip interface brief", "copy running-config startup-config"], [0, 1, 2], "Les trois commandes montrent l’état du port, l’appartenance VLAN et les VLAN réellement transportés. « copy running-config startup-config » est important après correction, mais n’explique pas la panne initiale.", "moyen"),
      questions.choice("Tu lis « Vlans allowed on trunk : 110,120,199 » alors que le service invité est en VLAN 130. Quelle hypothèse est la meilleure ?", ["Le DNS des invités est forcément erroné", "Le trunk ne transporte pas le VLAN 130", "Le port Fa0/24 est administrativement down", "Le routeur a perdu toutes ses routes"], 1, "Le lien transporte explicitement 110, 120 et 199, pas 130. Le problème est donc très probablement la liste des VLAN autorisés sur le trunk, pas un souci DNS ou de routage global.", "difficile"),
    ],
  },
};

const documentationLesson: NewLesson = {
  key: "reseaux-documentation",
  title: "Documenter un réseau : schéma, plan d’adressage et compte rendu",
  summary: "Transforme un réseau en documentation exploitable : schéma, plan d’adressage, inventaire, journal des changements et compte rendu d’incident sans y stocker de secrets.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("décrire les éléments indispensables d’une documentation réseau, rédiger un plan d’adressage lisible, distinguer schéma physique et logique, produire un compte rendu d’incident, et éviter d’y mettre des secrets."),
    prerequisites("avoir déjà manipulé l’adressage, les VLAN, le routage et un peu de dépannage."),
    scenario("Après une panne, Atlas demande à Nadia « où est le vrai schéma ? ». Chacun possède une version différente, avec des IP contradictoires et aucun historique des changements. Quand un nouveau collègue arrive, il perd une journée à retrouver la passerelle d’un VLAN. Nadia comprend que l’absence de documentation est devenue un risque opérationnel à part entière."),
    videoSlot("Documenter un réseau pour qu’un autre puisse le comprendre"),
    text("Documenter un réseau, ce n’est pas faire un beau dessin pour un audit. C’est produire des informations qu’une autre personne peut utiliser pour exploiter, dépanner et sécuriser. Il faut au minimum un schéma physique, un schéma logique, un plan d’adressage, un tableau des VLAN, un inventaire, des sauvegardes de configuration et un journal des changements."),
    schema("Extrait de plan d’adressage\nVLAN  Nom              Réseau            Passerelle\n110   Utilisateurs     10.1.110.0/24     10.1.110.1\n120   Administration   10.1.120.0/24     10.1.120.1\n130   Invités          10.1.130.0/24     10.1.130.1\n199   Gestion          10.1.199.0/24     10.1.199.1"),
    text("Le schéma physique montre qui est branché où : baie, commutateurs, liaisons montantes, points d’accès, type de lien. Le schéma logique montre les VLAN, les réseaux, les routes, les zones de sécurité et les services. Les deux sont complémentaires. Une documentation utile applique aussi des conventions de nommage : SW-ATLAS-1, FW-ATLAS-EDGE, AP-ATLAS-REUNION."),
    example("Exemple corrigé : un compte rendu d’incident ne se limite pas à « panne corrigée ». Il doit contenir le contexte, les symptômes, le diagnostic, la cause racine, la correction et la vérification. Par exemple : « les invités n’atteignaient plus Internet car le VLAN 130 n’était pas autorisé sur le trunk Fa0/24 ; le trunk a été corrigé et vérifié par « show interfaces trunk » et par un test de navigation »."),
    text("Démonstration guidée : imagine qu’un collègue reprenne ton réseau demain. Peut-il, avec ta documentation, retrouver la passerelle du VLAN 120, savoir sur quel port est branché le point d’accès du hall, et comprendre pourquoi un flux DMZ vers LAN est refusé ? Si la réponse est non, il manque une pièce. On y met des références de coffre-fort ou d’outil de gestion des secrets, jamais des mots de passe en clair."),
    code("Nom d’équipement : FW-ATLAS-EDGE\nRôle            : pare-feu Internet et DMZ\nInterfaces       : WAN, LAN, DMZ\nSauvegarde config: coffre interne / sauvegarde hebdomadaire\nDernier changement : 2026-10-01, ajout règle HTTPS vers 172.16.10.10\n\nCompte rendu d’incident\n- Symptôme : invités sans Internet\n- Cause : VLAN 130 absent du trunk Fa0/24\n- Correction : ajout de 130 dans la liste autorisée\n- Vérification : ping passerelle OK, navigation OK, show interfaces trunk cohérent", "text"),
    schema("Journal des changements\nDate        Auteur   Changement                      Validation\n2026-09-28  Nadia    création VLAN 199 gestion      show vlan brief\n2026-10-01  Koffi    publication HTTPS DMZ          test 443 depuis Internet\n2026-10-03  Nadia    correction trunk VLAN 130      test invités + sauvegarde"),
    text("Une documentation périmée vaut parfois pire que pas de documentation. Mets une date, un auteur, une source de vérité et un cycle de revue. Après chaque changement validé, mets à jour le document et la sauvegarde de configuration ensemble. Tu gagneras du temps au prochain incident, mais aussi lors d’une passation."),
    mistakes("garder plusieurs versions contradictoires du même schéma ; oublier les conventions de nommage ; stocker des mots de passe ou des secrets dans le document ; décrire un changement sans noter comment il a été vérifié."),
    takeaway("une bonne documentation réseau doit être exploitable par quelqu’un d’autre. Schémas, adressage, VLAN, inventaire et journal des changements se complètent. Jamais de mot de passe en clair dans ces documents."),
    practice("dans le laboratoire « Projet final : concevoir et documenter le réseau de Kora », produis un schéma logique, un plan d’adressage, un tableau de VLAN et un court compte rendu d’incident. Termine par le quiz de la leçon."),
    reference("anssiHygiene"),
    reference("nistCsf"),
    reference("netacad"),
  ],
  quiz: {
    title: "Quiz : documentation réseau",
    questions: [
      questions.choice("Quel élément ne doit jamais apparaître en clair dans une documentation réseau partagée ?", ["Le nom des VLAN", "Les passerelles", "Les mots de passe d’administration", "Les noms des équipements"], 2, "Les mots de passe doivent rester dans un coffre ou un gestionnaire de secrets, jamais dans un schéma ou un tableau diffusé à plusieurs personnes. Les autres éléments servent justement à comprendre et exploiter le réseau.", "facile"),
      questions.tf("Un schéma physique et un schéma logique décrivent exactement la même chose, il suffit donc d’en garder un seul.", false, "C’est faux : le schéma physique décrit les branchements et emplacements, tandis que le schéma logique décrit réseaux, VLAN, routes et zones. Supprimer l’un des deux fait perdre une partie essentielle du contexte.", "moyen"),
      questions.multi("Quelles informations appartiennent à une documentation réseau utile ? (plusieurs réponses)", ["Un plan d’adressage", "Un journal des changements", "Une liste des secrets en clair pour aller plus vite", "Un tableau des VLAN"], [0, 1, 3], "Le plan d’adressage, les VLAN et l’historique des changements permettent d’exploiter et de dépanner. Les secrets en clair, eux, transforment la documentation en fuite potentielle et doivent être exclus.", "moyen"),
      questions.choice("Quel compte rendu d’incident est le plus exploitable ?", ["« Panne réseau réglée »", "« Internet KO, voir Nadia »", "« VLAN 130 absent du trunk Fa0/24, corrigé puis vérifié par « show interfaces trunk » et un test invité »", "« Il fallait redémarrer »"], 2, "Cette formulation donne le symptôme, la cause, la correction et la méthode de vérification. Les autres phrases sont trop vagues : elles n’aident ni une passation, ni un audit, ni un dépannage futur.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c2:10",
    position: 9,
    title: "Sécurité réseau",
    description: "Tu y apprends à filtrer, segmenter et durcir un accès réseau sans casser les usages légitimes. Critères de réussite : écrire une ACL cohérente, justifier une DMZ et une matrice de flux, et proposer un plan de sécurisation Wi-Fi et d’administration crédible.",
    lessons: [aclLesson, segmentationLesson, wifiLesson],
  },
  {
    key: "c2:6",
    position: 10,
    existing: { fromTitle: "Pratique et évaluation" },
    title: "Diagnostic et documentation",
    description: "Ce module te fait passer de l’observation à la preuve : tu lis les sorties d’équipement, tu dépannes méthodiquement et tu laisses une documentation exploitable. Critères de réussite : isoler une panne par étapes, interpréter correctement des sorties « show », et produire un compte rendu avec schéma et plan d’adressage cohérents.",
    lessons: [
      troubleshootingLesson,
      showLesson,
      { key: "reseaux-packet-tracer", existing: true },
      documentationLesson,
    ],
  },
];
