import {
  code, example, goals, mistakes, practice, prerequisites, questions, reference, safety, scenario, schema, takeaway, text, videoSlot,
  type NewLesson, type PathModuleEntry,
} from "./path-kit";

const dnsLesson: NewLesson = {
  key: "l1",
  title: "Comprendre le fonctionnement du DNS",
  summary: "Comprendre comment le DNS traduit un nom en adresse IP, où interviennent le cache, le TTL et les serveurs récursifs, et savoir diagnostiquer une panne où le nom échoue mais pas l’IP.",
  minutes: 20,
  xp: 25,
  upgrade: true,
  blocks: [
    goals("expliquer la hiérarchie du DNS, distinguer résolution récursive et itérative, identifier les enregistrements courants, interpréter une réponse nslookup ou dig, et diagnostiquer une panne où le nom échoue alors que l’adresse IP répond."),
    prerequisites("avoir vu ce qu’est une adresse IP et savoir qu’un routeur relie ton réseau local au reste du réseau."),
    scenario("Nadia ouvre l’intranet de Baobab Tech chaque matin. Un jour, le navigateur affiche « serveur introuvable », mais le technicien joint encore l’adresse IP du serveur avec un ping. La panne ne vient donc pas forcément du serveur. Pour éviter de changer le mauvais équipement, Nadia doit comprendre comment un nom devient une adresse IP."),
    videoSlot("Résolution DNS : du nom au serveur"),
    text("Le DNS (Domain Name System) est l’annuaire du réseau. Toi, tu retiens un nom comme atlas.example. Les machines ont besoin d’une adresse IP. L’espace de noms est hiérarchique : la racine, puis le domaine de premier niveau, puis le domaine, puis le sous-domaine. Quand ton poste ne connaît pas encore la réponse, il demande souvent à un résolveur récursif, celui de l’entreprise ou de la box, qui fait les recherches pour lui."),
    schema("racine (.)\n  |\n  +-- .example\n       |\n       +-- atlas.example\n       |\n       +-- intranet.atlas.example"),
    text("Le résolveur récursif peut interroger d’autres serveurs de façon itérative : la racine, puis le TLD, puis le serveur faisant autorité. Il garde ensuite la réponse en cache pendant une durée appelée TTL (Time To Live). Ce cache accélère l’ouverture des sites. Le DNS transporte surtout ses requêtes en UDP sur le port 53, mais il peut utiliser TCP pour des réponses plus volumineuses ou quand l’UDP ne suffit plus."),
    schema("Type   Rôle principal\nA      nom -> adresse IPv4\nAAAA   nom -> adresse IPv6\nCNAME  alias vers un autre nom\nMX     serveur de courrier\nNS     serveurs DNS autoritaires\nTXT    texte de politique ou de preuve\nPTR    adresse IP -> nom"),
    text("Démonstration guidée : teste d’abord la résolution, puis compare avec un accès direct par adresse IP. Si le ping vers 192.168.1.20 répond mais que nslookup ne renvoie rien, la panne se situe du côté du DNS ou de sa configuration. Les sorties ci-dessous sont des exemples cohérents, avec les mêmes adresses du début à la fin."),
    code("nslookup intranet.atlas.example 192.168.1.53\nServer:  resolver.atlas.example\nAddress: 192.168.1.53\n\nName:    intranet.atlas.example\nAddress: 192.168.1.20\n\n# Linux\n dig @192.168.1.53 intranet.atlas.example A +noall +answer\nintranet.atlas.example. 300 IN A 192.168.1.20\n\n# Test direct du serveur\nping 192.168.1.20\n# exemple de sortie : Reply from 192.168.1.20: bytes=32 time=3ms TTL=64", "bash"),
    text("Côté sécurité, DNS est critique et souvent discret. Une usurpation de réponse, ou DNS spoofing, peut rediriger vers un faux site. Un empoisonnement de cache peut toucher plusieurs utilisateurs d’un coup. DNSSEC aide à vérifier l’authenticité de certaines réponses. DoH et DoT chiffrent la requête entre le client et son résolveur, mais ne corrigent pas un domaine mal configuré. Le tunnel DNS existe aussi : un attaquant peut cacher des données dans des requêtes DNS."),
    example("Exemple corrigé : le serveur DNS renvoie un TTL de 300 secondes pour intranet.atlas.example. Nadia relance la même requête 95 secondes plus tard. Il reste donc 205 secondes de validité dans le cache. Si l’intranet ne s’ouvre plus alors que le ping vers 192.168.1.20 réussit, il faut d’abord vérifier le DNS."),
    mistakes("croire que DNS sert seulement à Internet, alors qu’un intranet d’entreprise en dépend aussi ; confondre le résolveur récursif avec le serveur faisant autorité ; oublier que le cache peut garder une ancienne réponse pendant le TTL ; tester seulement le nom sans comparer avec l’accès direct par adresse IP."),
    safety("n’interroge et n’analyse que les serveurs DNS de ton propre réseau ou d’un laboratoire autorisé. Un serveur mal configuré peut exposer des informations internes sur les noms et les services."),
    takeaway("DNS traduit un nom en adresse IP grâce à une hiérarchie et à un cache. UDP 53 est le cas le plus courant, TCP 53 reste utile aussi. Quand le nom échoue mais que l’IP répond, pense d’abord à la résolution DNS."),
    practice("ouvre le laboratoire « Réseau instable : lire une capture », repère la requête DNS, l’adresse IP renvoyée et le moment où la panne vient du nom plutôt que du serveur. Termine par le quiz de la leçon."),
    reference("rfc1034"),
    reference("rfc1035"),
    reference("msNslookup"),
  ],
};

const dhcpLesson: NewLesson = {
  key: "reseaux-dhcp",
  title: "DHCP : l’adressage automatique",
  summary: "Comprendre comment DHCP attribue une adresse IP, une passerelle et un DNS, savoir lire DORA, repérer une panne de bail et configurer un pool simple sur Cisco IOS.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("décrire les quatre étapes DORA, expliquer le bail et son renouvellement, identifier une adresse APIPA, configurer un pool DHCP simple, et interpréter une sortie ipconfig ou show ip dhcp binding."),
    prerequisites("avoir déjà vu l’adressage IPv4, le rôle de la passerelle et l’utilité du DNS."),
    scenario("Moussa ajoute dix PC dans la salle de formation de Sahel Services. Il les branche, mais certains reçoivent une adresse et d’autres restent sans réseau. Il ne veut pas configurer chaque machine à la main. Pour comprendre ce qui bloque, il doit savoir comment un client obtient automatiquement son adresse, sa passerelle et son serveur DNS."),
    videoSlot("DHCP : comment une machine reçoit son adresse"),
    text("DHCP (Dynamic Host Configuration Protocol) évite de saisir à la main l’adresse IP de chaque machine. Quand un client démarre et n’a rien, il diffuse un DHCP Discover. Un serveur répond avec une proposition, le client la demande officiellement, puis le serveur confirme. Ce cycle s’appelle DORA : Discover, Offer, Request, Acknowledge. DHCP fournit aussi le masque, la passerelle et le DNS."),
    schema("Client                         Serveur DHCP\n  | --- Discover  -----------> |  je cherche une config\n  | <--- Offer  -------------- |  voici 192.168.10.41/24\n  | --- Request  ------------> |  je prends cette adresse\n  | <--- Acknowledge --------- |  bail confirmé"),
    text("L’adresse n’est pas donnée pour toujours : elle est louée pour une durée appelée bail. Le client tente de renouveler son bail à 50 % de cette durée, puis de le renégocier à 87,5 % s’il n’a pas reçu de réponse. Si aucun serveur DHCP n’est joignable, Windows peut se rabattre sur une adresse APIPA en 169.254.0.0/16 : utile pour le dépannage, mais rarement pour sortir du sous-réseau."),
    schema("Élément          Exemple\nPlage distribuée  192.168.10.21 à 192.168.10.200\nExclusions        192.168.10.1 à 192.168.10.20\nRéservation       imprimante -> 192.168.10.15\nOptions           passerelle 192.168.10.1, DNS 192.168.1.53"),
    text("Démonstration guidée : lis d’abord ce que le poste a reçu, puis compare avec la configuration du serveur. Si le poste est dans un autre VLAN que le serveur, un routeur ou un commutateur de niveau 3 doit relayer les requêtes de diffusion avec ip helper-address. Les commandes Cisco ci-dessous sont propres à IOS."),
    code("# Client Windows\nipconfig /all\nipconfig /release\nipconfig /renew\n\n! Cisco IOS : routeur qui sert lui-même DHCP\nip dhcp excluded-address 192.168.10.1 192.168.10.20\nip dhcp pool ATLAS-USERS\n network 192.168.10.0 255.255.255.0\n default-router 192.168.10.1\n dns-server 192.168.1.53\n lease 0 8\n!\n! Cisco IOS : relais si le serveur DHCP distant est 10.1.0.10\ninterface GigabitEthernet0/0.110\n encapsulation dot1Q 110\n ip address 192.168.10.1 255.255.255.0\n ip helper-address 10.1.0.10\n!\nshow ip dhcp binding", "text"),
    text("Côté sécurité, DHCP peut être détourné. Un faux serveur peut distribuer une mauvaise passerelle et envoyer le trafic vers un attaquant. DHCP snooping aide à limiter ce risque en autorisant seulement certains ports du commutateur à répondre comme serveurs. En production, documente les exclusions et évite de mélanger des adresses statiques au milieu de la plage dynamique."),
    example("Exemple corrigé : Atlas donne un bail de 8 heures. Le client essaie un renouvellement à 4 heures, puis une nouvelle tentative large à 7 heures. Si le poste affiche 169.254.22.11 au lieu d’une adresse 192.168.10.x, il n’a pas reçu de réponse DHCP correcte et tu dois vérifier le serveur, le relais ou le VLAN."),
    mistakes("oublier d’exclure les adresses déjà utilisées par la passerelle ou les serveurs ; croire qu’une adresse APIPA suffit pour joindre Internet ; oublier ip helper-address quand le serveur est dans un autre réseau ; laisser n’importe quel port répondre en DHCP alors qu’un faux serveur peut détourner le trafic."),
    safety("ne branche pas un serveur DHCP de test sur un réseau d’entreprise sans autorisation. Une seule mauvaise offre DHCP peut perturber des dizaines de postes en quelques secondes."),
    takeaway("DHCP automatise l’adressage avec DORA. Le bail se renouvelle avant son expiration, pas au dernier moment. Une adresse 169.254.x.x est un signal de panne ou d’absence de serveur DHCP joignable."),
    practice("ouvre le laboratoire « TP 1 : construire le réseau d’une maison », distribue une plage cohérente, réserve la passerelle et vérifie qu’un poste récupère bien IP, masque, passerelle et DNS avant de finir par le quiz."),
    reference("rfc2131"),
    reference("msIpconfig"),
    reference("netacad"),
  ],
  quiz: {
    title: "Quiz : DHCP",
    questions: [
      questions.choice("Quelle étape vient juste après le DHCP Offer dans la séquence DORA ?", ["Acknowledge", "Discover", "Request", "Release"], 2, "Après l’offre, le client envoie un Request pour dire quelle adresse il accepte. L’Acknowledge vient seulement après, quand le serveur confirme le bail.", "facile"),
      questions.tf("Une adresse 169.254.22.11 indique souvent qu’un poste n’a pas obtenu de bail DHCP utilisable.", true, "Vrai : cette plage APIPA apparaît souvent quand aucun serveur DHCP n’a répondu ou quand la réponse n’était pas exploitable. Ce n’est pas une adresse destinée à un accès normal à Internet.", "moyen"),
      questions.multi("Quelles informations un serveur DHCP peut-il fournir à un client ? (plusieurs réponses)", ["Une passerelle par défaut", "Un ou plusieurs serveurs DNS", "Une adresse IP et un masque", "Le mot de passe administrateur du routeur"], [0, 1, 2], "DHCP distribue des paramètres réseau, pas des secrets d’administration. La tentation est de croire qu’il « configure tout », mais il ne doit jamais servir à exposer des mots de passe.", "moyen"),
      questions.choice("Sur Cisco IOS, quelle commande relaye les requêtes DHCP d’un autre réseau vers le serveur ?", ["ip helper-address 10.1.0.10", "ip default-gateway 10.1.0.10", "dhcp relay enable", "forward dhcp 10.1.0.10"], 0, "Sur IOS, ip helper-address relaie plusieurs diffusions utiles, dont DHCP. Les autres propositions ressemblent à des commandes plausibles, mais elles ne réalisent pas ce rôle.", "difficile"),
    ],
  },
};

const natPatLesson: NewLesson = {
  key: "reseaux-nat-pat",
  title: "NAT et PAT : partager une adresse publique",
  summary: "Comprendre pourquoi un routeur traduit des adresses privées, distinguer NAT statique, dynamique et PAT, lire une table de traduction et configurer une surcharge simple sur Cisco IOS.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer adresses privées et publiques, expliquer inside local et inside global, différencier NAT statique, dynamique et PAT, lire une table de traduction, et configurer un exemple PAT sur Cisco IOS."),
    prerequisites("savoir ce qu’est une passerelle, une adresse privée IPv4 et une communication client-serveur avec des ports."),
    scenario("Fatou administre un petit réseau chez Atlas. Tous les PC utilisent des adresses privées 10.2.1.x, mais l’opérateur n’a fourni qu’une seule adresse IPv4 publique. Malgré cela, tout le monde navigue en même temps. Pour comprendre ce « miracle », Fatou doit lire la traduction du routeur de sortie."),
    videoSlot("NAT et PAT : une adresse publique pour plusieurs machines"),
    text("NAT (Network Address Translation) modifie des adresses lorsqu’un paquet traverse le routeur. En IPv4, cela permet de faire sortir des machines privées vers Internet sans attribuer une adresse publique à chacune. Avec NAT statique, une adresse privée correspond toujours à la même adresse publique. Avec NAT dynamique, le routeur pioche dans un petit pool public. Avec PAT, plusieurs machines partagent une seule adresse publique grâce à des ports source différents."),
    schema("Type         Usage principal\nNAT statique publier un serveur interne de façon stable\nNAT dynamique prêter une adresse publique libre d’un pool\nPAT          partager une seule adresse publique entre plusieurs flux"),
    text("Les termes Cisco aident à ne pas se tromper. Inside local : l’adresse privée vue dans le LAN, par exemple 10.2.1.20. Inside global : l’adresse publique qui représente ce client à l’extérieur, par exemple 192.0.2.34. Outside global : l’adresse du serveur distant. Le routeur tient une table pour se souvenir de chaque traduction en cours. Sans cette table, la réponse ne saurait pas vers quel client revenir."),
    schema("Avant sortie : 10.2.1.20:51514  ->  192.0.2.80:443\nAprès PAT    : 192.0.2.34:40001 ->  192.0.2.80:443\n\nAvant sortie : 10.2.1.21:51514  ->  192.0.2.80:443\nAprès PAT    : 192.0.2.34:40002 ->  192.0.2.80:443"),
    text("Démonstration guidée : marque d’abord les interfaces inside et outside, puis applique la règle de traduction. La syntaxe ci-dessous est propre à Cisco IOS. Elle autorise tout le sous-réseau 10.2.1.0/24 à sortir avec l’adresse de l’interface externe. Ensuite, show ip nat translations vérifie que les flux réels correspondent au plan d’adressage."),
    code("access-list 10 permit 10.2.1.0 0.0.0.255\n!\ninterface GigabitEthernet0/0\n ip address 10.2.1.1 255.255.255.0\n ip nat inside\n!\ninterface GigabitEthernet0/1\n ip address 192.0.2.34 255.255.255.248\n ip nat outside\n!\nip nat inside source list 10 interface GigabitEthernet0/1 overload\n!\nshow ip nat translations\n# exemple de sortie\n# Pro  Inside global      Inside local       Outside local      Outside global\n# tcp  192.0.2.34:40001  10.2.1.20:51514    192.0.2.80:443     192.0.2.80:443", "text"),
    text("NAT ne remplace pas un pare-feu. Il masque une partie du plan d’adressage, mais il ne décide pas seul quels flux sont autorisés. Pour publier un service interne, on ajoute souvent une redirection de port, par exemple 192.0.2.34:443 vers 10.2.1.50:443. Sur les réseaux mobiles, CGNAT est fréquent : l’opérateur partage une adresse publique entre plusieurs abonnés. En IPv6, le filtrage reste indispensable."),
    example("Exemple corrigé : deux postes, 10.2.1.20 et 10.2.1.21, ouvrent chacun une session HTTPS avec le même port source 51514 vers 192.0.2.80. Le routeur PAT les traduit en 192.0.2.34:40001 et 192.0.2.34:40002. Les ports rendent les conversations distinctes."),
    mistakes("croire que NAT est un pare-feu complet ; oublier de marquer une interface en ip nat inside ou outside ; confondre l’adresse privée du client avec l’adresse publique vue sur Internet ; publier un service sans documenter la redirection et le risque."),
    safety("n’ouvre des redirections de port que pour des services indispensables et autorisés. Exposer une interface d’administration à Internet augmente immédiatement la surface d’attaque."),
    takeaway("NAT traduit des adresses IPv4 entre réseaux privés et publics. PAT partage une adresse publique grâce aux ports. Une table de traduction bien lue explique souvent pourquoi un flux sort ou ne revient pas."),
    practice("ouvre le laboratoire « Projet final : concevoir et documenter le réseau de Kora », choisis quelles machines sortent via PAT et lesquelles méritent une publication contrôlée, puis termine par le quiz."),
    reference("rfc3022"),
    reference("rfc1918"),
    reference("netacad"),
  ],
  quiz: {
    title: "Quiz : NAT et PAT",
    questions: [
      questions.choice("Quel mécanisme permet à plusieurs postes privés de partager une seule adresse IPv4 publique grâce aux ports source ?", ["NAT statique", "PAT", "ARP", "DHCP"], 1, "PAT, aussi appelé surcharge, distingue les flux avec des ports différents. NAT statique garde une correspondance fixe et ne sert pas à mutualiser massivement une seule adresse.", "facile"),
      questions.choice("Dans la terminologie Cisco, 10.2.1.20 est quoi si c’est l’adresse privée du poste dans le LAN ?", ["Inside global", "Outside global", "Inside local", "Outside local"], 2, "Inside local désigne l’adresse privée vue à l’intérieur du réseau. Inside global est l’adresse publique qui représente ce client vers l’extérieur.", "moyen"),
      questions.tf("Le fait d’utiliser NAT suffit à remplacer une politique de pare-feu.", false, "Faux : NAT change des adresses, mais il n’exprime pas à lui seul une politique de sécurité complète. Un pare-feu décide quels flux sont autorisés, refusés et journalisés.", "moyen"),
      questions.multi("Quelles actions sont nécessaires pour un PAT simple sur Cisco IOS ? (plusieurs réponses)", ["Définir au moins une ACL qui désigne les adresses internes", "Marquer les interfaces avec ip nat inside et ip nat outside", "Activer overload sur la règle de traduction", "Ajouter obligatoirement un serveur DNS public dans la configuration NAT"], [0, 1, 2], "L’ACL, les rôles inside or outside et le mot-clé overload sont indispensables dans cet exemple. Un DNS public peut être utile ailleurs, mais il n’est pas requis pour que PAT fonctionne.", "difficile"),
    ],
  },
};

const ntpServicesLesson: NewLesson = {
  key: "reseaux-ntp-services",
  title: "NTP et services d’infrastructure : l’heure, les journaux, la supervision",
  summary: "Comprendre pourquoi une heure correcte change tout en diagnostic, savoir lire NTP, syslog et supervision, et mettre en place des bases saines pour corréler des journaux réseau.",
  minutes: 18,
  xp: 25,
  blocks: [
    goals("expliquer le rôle de NTP et des strates, vérifier l’heure sur Linux, Windows et Cisco IOS, interpréter un décalage dans des journaux, distinguer syslog et SNMP, et choisir de bonnes pratiques de supervision."),
    prerequisites("savoir qu’un réseau produit des journaux et que le dépannage compare souvent plusieurs équipements en même temps."),
    scenario("Pendant un incident chez Cabinet Moussa, le pare-feu signale une connexion à 09:14 alors que le serveur web parle du même événement à 09:09. L’équipe croit d’abord à deux attaques différentes. En réalité, les horloges ne sont pas alignées. Sans heure cohérente, les journaux racontent une histoire fausse."),
    videoSlot("Pourquoi l’heure réseau compte autant que l’adresse IP"),
    text("NTP (Network Time Protocol) synchronise les horloges. Un serveur de strate 1 est relié à une source de temps de référence, une strate 2 se synchronise sur lui, et ainsi de suite. Tu n’as pas besoin d’une précision scientifique pour dépanner un réseau, mais tu as besoin d’équipements qui racontent tous la même heure, idéalement en UTC dans les journaux. Sinon, il devient difficile de suivre un incident, de vérifier un certificat ou de comprendre un échec de double facteur."),
    schema("Strate 0 : horloge de référence\nStrate 1 : serveur connecté à la référence\nStrate 2 : serveur synchronisé sur la strate 1\nStrate 3 : clients et équipements réseau"),
    text("NTP n’est qu’un morceau du socle. Syslog centralise les journaux, souvent en UDP 514, avec des niveaux de sévérité de 0 à 7. SNMP permet de lire des compteurs, des états d’interface et parfois de recevoir des alertes, mais SNMPv3 est préférable car les anciennes chaînes de communauté sont faciles à intercepter. Une vraie supervision combine disponibilité, performance et événements, pas seulement un ping de temps en temps."),
    schema("Niveau syslog  Sens\n0              urgence\n1              alerte\n2              critique\n3              erreur\n4              avertissement\n5              notification\n6              information\n7              débogage"),
    text("Démonstration guidée : vérifie d’abord si chaque machine a la bonne heure, puis si elle connaît un serveur NTP joignable. Ensuite, vérifie où partent les journaux. Les commandes ci-dessous illustrent les trois environnements qu’on rencontre le plus souvent. Les commandes IOS sont propres à Cisco."),
    code("# Linux\n timedatectl\n# Windows\n w32tm /query /status\n# Cisco IOS\nshow clock detail\nshow ntp status\nconfigure terminal\n ntp server 10.1.0.20\n service timestamps log datetime msec localtime show-timezone\n logging host 10.1.0.30\nend", "bash"),
    text("La corrélation dépend de l’écart entre les horloges. Si deux journaux parlent du même flux à cinq minutes d’intervalle, tu risques d’accuser le mauvais équipement. La bonne pratique est simple : choisir peu de serveurs NTP fiables, centraliser les journaux, utiliser UTC quand c’est possible et vérifier régulièrement les décalages. Pour la supervision, préfère des comptes SNMPv3 nominatifs et documentés, avec le minimum de droits nécessaire."),
    example("Exemple corrigé : le pare-feu note un refus à 09:14:05 et le serveur web le même flux à 09:09:07. L’écart est de 298 secondes, soit 4 minutes et 58 secondes. Sans correction, on pourrait croire à deux événements distincts. Après synchronisation NTP, les journaux se recalent et montrent qu’il s’agit bien du même incident."),
    mistakes("laisser chaque équipement prendre l’heure de façon différente ; stocker des journaux en heure locale sans préciser le fuseau ; utiliser encore SNMPv2c avec des chaînes trop simples ; croire qu’un simple ping suffit à faire de la supervision utile."),
    safety("ne publie pas inutilement tes serveurs NTP, syslog ou SNMP sur Internet. Ces services d’infrastructure donnent des informations précieuses sur ton réseau et doivent être limités aux hôtes autorisés."),
    takeaway("Une heure fiable rend les journaux comparables. NTP, syslog et supervision forment un trio de base pour diagnostiquer et défendre un réseau. Sans eux, tu vois des symptômes isolés au lieu d’un incident cohérent."),
    practice("ouvre le laboratoire « TP 4 : incident réseau chez Kora », compare les heures des équipements, repère quel journal devient trompeur quand l’horloge dérive, puis termine par le quiz."),
    reference("rfc5905"),
    reference("rfc5424"),
    reference("anssiHygiene"),
  ],
  quiz: {
    title: "Quiz : NTP et services d’infrastructure",
    questions: [
      questions.choice("Pourquoi un décalage de quelques minutes entre deux équipements est-il gênant pendant un incident ?", ["Parce qu’il bloque physiquement le trafic", "Parce qu’il empêche de corréler correctement les journaux", "Parce qu’il supprime automatiquement les paquets", "Parce qu’il désactive les ports du commutateur"], 1, "Le trafic peut continuer à circuler, mais les journaux ne racontent plus la même chronologie. On perd alors la capacité à relier la cause, l’effet et la correction dans le bon ordre.", "facile"),
      questions.choice("Quel protocole centralise souvent des journaux applicatifs et réseau via UDP 514 ?", ["SNMP", "ARP", "Syslog", "OSPF"], 2, "Syslog est le protocole classique de centralisation des journaux. SNMP sert plutôt aux états et compteurs, ARP à la résolution locale et OSPF au routage.", "moyen"),
      questions.multi("Quelles bonnes pratiques renforcent un service d’infrastructure sain ? (plusieurs réponses)", ["Utiliser SNMPv3 quand c’est possible", "Centraliser les journaux sur un hôte dédié", "Employer UTC dans les journaux ou au moins documenter clairement le fuseau", "Changer l’heure manuellement sur chaque poste chaque lundi"], [0, 1, 2], "Les trois premières pratiques améliorent la cohérence et la sécurité. Régler l’heure à la main est tentant quand on débute, mais cela crée vite plus d’écarts et d’erreurs qu’autre chose.", "moyen"),
      questions.tf("Un certificat ou une authentification forte peut échouer si l’horloge de la machine est trop décalée.", true, "Vrai : beaucoup de mécanismes de sécurité dépendent d’une notion de temps fiable. Une machine trop en retard ou trop en avance peut considérer un certificat comme expiré ou pas encore valide.", "difficile"),
    ],
  },
};

const portsLesson: NewLesson = {
  key: "l2",
  title: "Les ports et protocoles réseau",
  summary: "Comprendre comment un port identifie un service, distinguer les grandes plages de ports, reconnaître des services courants et lire rapidement ce qu’une machine écoute vraiment.",
  minutes: 20,
  xp: 25,
  upgrade: true,
  blocks: [
    goals("définir un socket IP:port, distinguer ports connus, enregistrés et dynamiques, associer les services réseau courants à leurs ports, comparer TCP et UDP, et interpréter une sortie ss ou netstat."),
    prerequisites("avoir déjà vu qu’une adresse IP identifie une machine et qu’un service applicatif peut écouter le réseau."),
    scenario("Awa arrive sur un serveur qui semble lent. Le site web répond, mais l’accès distant d’administration échoue. Avant de toucher au pare-feu, elle veut savoir quels services écoutent vraiment sur la machine et lesquels devraient être fermés. Pour cela, elle doit lire les ports comme les portes d’un bâtiment."),
    videoSlot("Ports réseau : qui écoute quoi, et pourquoi"),
    text("Une adresse IP identifie une machine. Un port identifie le service qui tourne sur cette machine. Ensemble, ils forment un socket, par exemple 192.168.1.20:443. Quand ton navigateur contacte un serveur web, il vise l’IP du serveur et le port 443. Ton poste, lui, ouvre souvent un port source temporaire dans une plage dynamique. Sans ports, tous les services recevraient le même trafic sans moyen de le séparer."),
    schema("Plage              Usage\n0 à 1023           ports connus, souvent réservés aux services classiques\n1024 à 49151       ports enregistrés\n49152 à 65535      ports dynamiques ou éphémères"),
    text("Le numéro de port ne dit pas tout : il faut aussi regarder le protocole de transport. Le port 53 existe en UDP et en TCP selon le contexte. Les services les plus fréquents sont utiles à connaître : HTTP 80, HTTPS 443, SSH 22, Telnet 23, FTP 21, SMTP 25 et 587, IMAP 143 et 993, POP3 110 et 995, DHCP 67 et 68, NTP 123, SMB 445, RDP 3389 et MySQL 3306. Les variantes sécurisées ne gardent pas toujours le même numéro de port."),
    schema("Service   Port(s)     Remarque\nHTTP      80          web en clair\nHTTPS     443         web dans TLS\nSSH       22          administration sécurisée\nTelnet    23          administration en clair\nDNS       53          UDP ou TCP\nDHCP      67/68       serveur / client\nNTP       123         synchronisation de l’heure\nSMB       445         partage Windows"),
    text("Démonstration guidée : liste d’abord les services qui écoutent en local, puis compare avec ce qui est réellement exposé sur le réseau. ss -tuln et netstat -an montrent les sockets ouverts. Un port ouvert écoute. Un port fermé n’a pas de service derrière. Un port filtré peut exister, mais un pare-feu bloque la tentative. Réduire la surface d’exposition consiste à ne laisser ouverts que les ports utiles."),
    code("# Linux\nss -tuln\n# exemple de sortie\n# Netid State  Local Address:Port  Peer Address:Port\n# tcp   LISTEN 0.0.0.0:22          0.0.0.0:*\n# tcp   LISTEN 0.0.0.0:443         0.0.0.0:*\n# udp   UNCONN 0.0.0.0:123         0.0.0.0:*\n\n# Windows\nnetstat -an\n# exemple de sortie\n# TCP    0.0.0.0:3389     0.0.0.0:0     LISTENING", "bash"),
    text("Côté sécurité, un port inutilement exposé devient une cible offerte. Telnet, FTP en clair ou un port d’administration ouvert à tous sont des signes d’hygiène fragile. Documente les exceptions, remplace les protocoles en clair par leurs variantes chiffrées, et vérifie qu’un service interne n’écoute pas par défaut sur toutes les interfaces."),
    example("Exemple corrigé : la plage dynamique va de 49152 à 65535, soit 16384 ports possibles. Si ton navigateur ouvre la connexion source 192.168.1.44:53000 vers 192.168.1.20:443, cela ne veut pas dire que 53000 est un service serveur : c’est un port temporaire côté client."),
    mistakes("croire qu’un numéro de port suffit à identifier le protocole sans regarder TCP ou UDP ; confondre le port source temporaire du client avec le port du service serveur ; laisser Telnet ou FTP en clair alors que SSH et HTTPS existent ; oublier qu’un service peut écouter seulement sur 127.0.0.1 et ne pas être exposé au réseau."),
    safety("n’inspecte que tes propres hôtes ou ceux pour lesquels tu as une autorisation. Faire l’inventaire des ports d’autrui sans cadre peut être perçu comme une reconnaissance hostile."),
    takeaway("Un port identifie un service, pas une machine. Il faut toujours lire le couple protocole plus port. Expose le moins de ports possible et préfère les variantes chiffrées."),
    practice("ouvre le laboratoire « Réseau instable : lire une capture », repère quel port serveur est visé, quel port client est temporaire et quel protocole de transport est utilisé avant de finir par le quiz."),
    reference("ianaPorts"),
    reference("man7Ip"),
    reference("netacad"),
  ],
  quiz: {
    title: "Quiz : ports et protocoles réseau",
    questions: [
      questions.choice("Quelle plage correspond aux ports dynamiques ou éphémères ?", ["0 à 1023", "1024 à 49151", "49152 à 65535", "65536 à 99999"], 2, "La plage 49152 à 65535 est celle que l’on voit souvent pour les ports source temporaires côté client. Les autres plages ont d’autres usages, et la dernière n’existe même pas en TCP ou UDP.", "facile"),
      questions.multi("Parmi ces services, lesquels sont les variantes chiffrées ou plus sûres par rapport à une version en clair ? (plusieurs réponses)", ["HTTPS par rapport à HTTP", "SSH par rapport à Telnet", "IMAPS sur 993 par rapport à IMAP sur 143", "FTP sur 21 par rapport à SFTP"], [0, 1, 2], "HTTPS, SSH et IMAPS apportent une protection de transport ou d’authentification par rapport aux versions en clair. FTP sur 21 n’est pas la version sûre de SFTP : ce sont deux protocoles différents.", "moyen"),
      questions.choice("Dans la sortie suivante, quel port correspond au service NTP ? « udp   UNCONN 0.0.0.0:123  0.0.0.0:* »", ["22", "80", "123", "445"], 2, "Le port 123 est celui de NTP. Les autres valeurs sont plausibles parce qu’elles correspondent à des services courants, mais elles ne servent pas à la synchronisation de l’heure.", "moyen"),
      questions.tf("Un port source client comme 53000 indique forcément qu’un service permanent écoute sur ce port côté serveur.", false, "Faux : un port source élevé est souvent un port temporaire choisi par le client pour une session donnée. Le service serveur, lui, écoute généralement sur un port bien défini, comme 443 pour HTTPS.", "difficile"),
    ],
  },
};

const udpIcmpLesson: NewLesson = {
  key: "reseaux-udp-icmp",
  title: "UDP et ICMP : transport léger et messages de contrôle",
  summary: "Comprendre quand UDP est préférable à TCP, reconnaître les messages ICMP utiles au diagnostic et lire ping ou traceroute sans confondre perte, filtrage et routage.",
  minutes: 20,
  xp: 25,
  blocks: [
    goals("comparer TCP et UDP, expliquer le rôle d’ICMP, interpréter un ping et un traceroute, reconnaître un message temps dépassé ou destination injoignable, et savoir quand filtrer ou autoriser ICMP."),
    prerequisites("connaître le rôle des ports réseau et avoir déjà vu qu’IP transporte des paquets entre réseaux."),
    scenario("Chez Sahel Services, la voix sur IP coupe parfois, mais le site web reste accessible. Le responsable pense à une panne globale, alors que plusieurs applications n’utilisent pas le même transport. En parallèle, le technicien lance un ping et un traceroute pour voir où le chemin casse. Pour interpréter ce qu’il voit, il doit distinguer UDP, ICMP et leurs usages."),
    videoSlot("UDP, ICMP, ping et traceroute : aller à l’essentiel"),
    text("UDP est volontairement simple : pas de connexion préalable, pas de retransmission, pas de garantie d’ordre. Son en-tête fait seulement 8 octets. Cette légèreté est utile quand la vitesse compte plus que la perfection immédiate, par exemple pour DNS, DHCP, la voix, le streaming en direct ou QUIC. Si une application a besoin d’une fiabilité stricte, elle peut la reconstruire elle-même ou choisir TCP à la place."),
    schema("UDP : léger, rapide, sans connexion, sans accusé automatique\nTCP : connecté, fiable, ordonné, plus bavard\n\nUsages fréquents d’UDP : DNS, DHCP, NTP, voix, vidéo en direct, QUIC"),
    text("ICMP n’est pas un protocole applicatif comme HTTP. Il transporte des messages de contrôle et de diagnostic pour IP. Les plus connus sont echo request et echo reply pour ping, destination unreachable quand un chemin ou un service n’est pas joignable, et time exceeded quand le TTL arrive à zéro. ICMPv6 est encore plus important en IPv6, car il participe aussi au bon fonctionnement du réseau et pas seulement au dépannage."),
    schema("Message ICMP             Usage courant\nEcho request / reply      ping\nDestination unreachable   réseau, hôte ou port injoignable\nTime exceeded             traceroute, TTL expiré"),
    text("Démonstration guidée : lis d’abord le ping, puis observe comment traceroute augmente progressivement le TTL pour révéler chaque saut. Si un routeur intermédiaire renvoie un message time exceeded, il se montre dans la liste. Si tous les sauts deviennent des étoiles, il peut s’agir d’un filtrage ICMP, d’un filtrage UDP ou d’un équipement qui choisit simplement de ne pas répondre."),
    code("ping 192.168.1.1\n# exemple de sortie : 4 envoyés, 3 reçus, 25% de perte\n\ntracert 192.0.2.80\n# exemple de sortie\n#  1   <1 ms   <1 ms   <1 ms  192.168.1.1\n#  2    4 ms    4 ms    5 ms  10.1.0.1\n#  3   12 ms   11 ms   13 ms  192.0.2.80", "bash"),
    text("Sur le plan sécurité, bloquer tout ICMP est une fausse bonne idée. Cela peut gêner le diagnostic, la découverte de MTU ou le fonctionnement normal d’IPv6. L’objectif n’est pas « tout autoriser », mais laisser passer les messages nécessaires et journaliser les abus. Il faut aussi connaître les usages malveillants : balayage ping à grande échelle, tunnel ICMP ou saturation par echo request, toujours à tester seulement dans un cadre autorisé."),
    example("Exemple corrigé : un ping de 4 paquets reçoit 3 réponses. La perte est donc de 25 %. Ce n’est pas une preuve automatique de panne applicative, mais un indice de qualité dégradée, cohérent avec une voix sur IP hachée alors qu’une page web finit quand même par s’afficher."),
    mistakes("croire qu’UDP est « mauvais » parce qu’il ne retransmet pas automatiquement ; confondre absence de réponse à un ping et panne certaine, alors qu’un filtrage peut suffire ; bloquer tout ICMP sans comprendre les impacts ; oublier qu’un traceroute peut utiliser des mécanismes différents selon l’outil et le système."),
    safety("ne lance des balayages ICMP ou des tests de chemin que sur des réseaux qui t’appartiennent ou te sont explicitement confiés. Même un simple ping peut déclencher des alertes sur un environnement sensible."),
    takeaway("UDP privilégie la simplicité et la rapidité. ICMP raconte ce que le réseau pense d’un paquet et aide beaucoup au diagnostic. Un bon dépannage combine lecture du transport, du routage et du filtrage."),
    practice("ouvre le laboratoire « Réseau instable : lire une capture », puis compare avec « TP 4 : incident réseau chez Kora » pour repérer où un message ICMP aide vraiment à comprendre la panne. Termine par le quiz."),
    reference("rfc768"),
    reference("rfc792"),
    reference("rfc4443"),
  ],
  quiz: {
    title: "Quiz : UDP et ICMP",
    questions: [
      questions.choice("Quel énoncé décrit le mieux UDP ?", ["Il établit toujours une connexion en trois temps", "Il garantit la retransmission et l’ordre des données", "Il est léger et ne fournit pas de retransmission automatique", "Il n’utilise jamais de numéro de port"], 2, "UDP reste volontairement minimal : pas de handshake, pas d’accusé automatique, pas d’ordre garanti. C’est justement ce qui le rend utile pour des usages sensibles à la latence.", "facile"),
      questions.choice("Quel message ICMP permet à traceroute d’afficher les routeurs intermédiaires ?", ["Echo reply", "Time exceeded", "Redirect", "Parameter problem"], 1, "Traceroute envoie des paquets avec un TTL croissant. Quand un routeur le décrémente à zéro, il renvoie un message ICMP time exceeded, ce qui révèle son adresse.", "moyen"),
      questions.tf("Bloquer tout ICMP est toujours une bonne pratique de sécurité.", false, "Faux : certains messages ICMP sont nécessaires au diagnostic et au bon fonctionnement du réseau, surtout en IPv6. Le bon réflexe consiste à filtrer intelligemment, pas à supprimer aveuglément.", "moyen"),
      questions.choice("Un ping indique « 4 envoyés, 3 reçus, 25% de perte ». Quelle lecture est la plus juste ?", ["Le réseau est forcément totalement coupé", "La machine distante n’existe pas", "La liaison montre une dégradation, mais pas une panne totale", "Le protocole UDP est désactivé"], 2, "Une perte de 25 % signifie qu’une partie des paquets passe encore. C’est souvent suffisant pour expliquer une application dégradée, mais pas pour conclure à une coupure totale ou à la disparition de la machine.", "difficile"),
    ],
  },
};

const httpTlsLesson: NewLesson = {
  key: "reseaux-http-tls",
  title: "HTTP, HTTPS et TLS : lire une requête web",
  summary: "Lire une requête et une réponse HTTP, comprendre ce que TLS protège vraiment, reconnaître les codes de statut utiles et éviter les erreurs qui exposent des données dans les URLs ou les cookies.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("identifier les éléments d’une requête et d’une réponse HTTP, interpréter les familles de codes de statut, expliquer le rôle de TLS et des certificats, lire une sortie curl -v, et repérer les données sensibles à ne pas placer dans une URL."),
    prerequisites("savoir ce qu’est un nom de domaine, un port réseau et une connexion client-serveur."),
    scenario("Koffi ouvre l’outil de réservation interne de son entreprise. Le navigateur affiche un cadenas, mais le responsable sécurité veut savoir ce que cela protège réellement. Dans le même temps, un développeur a mis un jeton dans l’URL d’un lien partagé par courriel. Pour juger le risque, Koffi doit lire la requête et ses en-têtes."),
    videoSlot("HTTP et TLS : ce que le navigateur dit vraiment au serveur"),
    text("HTTP décrit une conversation entre un client et un serveur web. Une requête contient au minimum une méthode, un chemin et une version, par exemple GET /login HTTP/1.1. Elle ajoute ensuite des en-têtes comme Host, Cookie ou User-Agent, puis parfois un corps. La réponse contient une version, un code de statut, des en-têtes, puis parfois un corps. Lire cette structure aide à comprendre ce qui a été demandé ou refusé."),
    schema("Requête HTTP\nGET /login HTTP/1.1\nHost: atlas.example\nCookie: session=abc123\n\nRéponse HTTP\nHTTP/1.1 200 OK\nContent-Type: text/html\nSet-Cookie: session=abc123; Secure; HttpOnly; SameSite=Lax"),
    text("Les codes de statut se lisent par famille : 2xx pour le succès, 3xx pour la redirection, 4xx pour une erreur côté client, 5xx pour une erreur côté serveur. Les cookies méritent une attention particulière : Secure évite leur envoi en clair sur HTTP, HttpOnly réduit l’accès côté script, SameSite limite certains abus inter-sites. Sans ces protections, le risque augmente."),
    schema("2xx  succès      200 OK, 201 Created\n3xx  redirection  301 Moved Permanently, 302 Found\n4xx  client       401 Unauthorized, 403 Forbidden, 404 Not Found\n5xx  serveur      500 Internal Server Error, 502 Bad Gateway"),
    text("HTTPS signifie simplement HTTP transporté dans TLS. Avant les données applicatives, le client et le serveur négocient une version, des paramètres cryptographiques et un certificat. Le navigateur vérifie ensuite la chaîne d’autorité et le nom présenté. TLS protège surtout la confidentialité et l’intégrité du contenu échangé, plus l’authentification du serveur. En revanche, l’adresse IP du serveur et le moment de la connexion restent visibles. HSTS aide à forcer HTTPS."),
    text("Démonstration guidée : lis la négociation TLS, puis la requête HTTP. curl -v montre les deux niveaux dans le même flux logique. Avec Wireshark, tls.handshake montre les étapes de négociation."),
    code("curl -v https://atlas.example/login\n# exemple de sortie\n# * SSL connection using TLSv1.3\n# * Server certificate:\n# *  subject: CN=atlas.example\n# > GET /login HTTP/1.1\n# > Host: atlas.example\n# > User-Agent: curl/8.0\n# < HTTP/1.1 302 Found\n# < Location: /dashboard\n# < Set-Cookie: session=abc123; Secure; HttpOnly; SameSite=Lax", "bash"),
    text("Une erreur fréquente est de mettre des informations sensibles dans l’URL : mot de passe, jeton de réinitialisation, numéro de dossier. Même si HTTPS protège le transport, l’URL peut se retrouver dans l’historique du navigateur, dans les journaux du serveur, dans un proxy ou dans un en-tête Referer. Préfère une requête POST."),
    example("Exemple corrigé : une réponse « HTTP/1.1 302 Found » avec « Location: /dashboard » n’est pas une panne. Le serveur demande simplement au client de suivre une redirection. Un cadenas dans le navigateur indique d’abord que le transport est chiffré et que le certificat présenté est accepté."),
    mistakes("croire que HTTPS cache aussi l’adresse IP du serveur ; confondre 401 et 403 ; stocker des secrets dans l’URL parce que « le site est en HTTPS » ; oublier les attributs Secure, HttpOnly ou SameSite sur un cookie de session."),
    safety("analyse seulement les requêtes web de ton propre environnement ou d’un laboratoire autorisé. Les en-têtes et les URL peuvent contenir des données personnelles."),
    takeaway("HTTP décrit la conversation applicative, TLS protège son transport. Lis les méthodes, les en-têtes et les codes de statut avant de conclure. Le chiffrement du transport ne remplace ni un bon design applicatif ni une bonne hygiène des cookies et des URL."),
    practice("ouvre le laboratoire « Réseau instable : lire une capture », repère la négociation TLS, le code de statut et les en-têtes utiles, puis termine par le quiz."),
    reference("rfc9110"),
    reference("rfc8446"),
    reference("mdnCookies"),
  ],
  quiz: {
    title: "Quiz : HTTP, HTTPS et TLS",
    questions: [
      questions.choice("Que protège principalement TLS dans une session HTTPS ?", ["Le contenu échangé, contre la lecture et l’altération en transit", "La qualité du code applicatif côté serveur", "Le nom des utilisateurs dans les journaux locaux", "Le routage IP jusqu’au client"], 0, "TLS protège surtout la confidentialité et l’intégrité des données en transit, ainsi que l’authentification du serveur via son certificat. Il ne garantit pas que l’application elle-même soit sans faille.", "facile"),
      questions.choice("Quelle famille de codes HTTP correspond en général à une erreur côté client ?", ["2xx", "3xx", "4xx", "5xx"], 2, "Les 4xx signalent que le serveur a compris la requête mais qu’il ne peut pas l’accepter telle quelle, par exemple 401, 403 ou 404. Les 5xx concernent plutôt des erreurs côté serveur.", "moyen"),
      questions.multi("Quels attributs renforcent un cookie de session ? (plusieurs réponses)", ["Secure", "HttpOnly", "SameSite", "Public"], [0, 1, 2], "Secure, HttpOnly et SameSite répondent chacun à un risque fréquent. « Public » semble plausible si l’on pense aux caches web, mais ce n’est pas un attribut de durcissement de cookie.", "moyen"),
      questions.tf("Placer un jeton secret dans l’URL devient sans risque dès lors que le site utilise HTTPS.", false, "Faux : HTTPS protège le transport, mais l’URL peut encore être copiée dans l’historique, des journaux, des proxys ou un en-tête Referer. Une donnée sensible n’a pas sa place dans une URL.", "difficile"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c2:1",
    position: 6,
    existing: { fromTitle: "Les services du réseau" },
    title: "Services réseau",
    description: "Ce module montre comment le réseau rend un nom lisible, attribue une adresse, partage une sortie Internet et garde des journaux exploitables. Critères de réussite : diagnostiquer une panne DNS ou DHCP simple, expliquer une traduction NAT ou PAT à partir d’une table, et vérifier qu’un équipement d’infrastructure a une heure et une journalisation cohérentes.",
    lessons: [
      dnsLesson,
      dhcpLesson,
      natPatLesson,
      ntpServicesLesson,
    ],
  },
  {
    key: "c2:4",
    position: 7,
    existing: { fromTitle: "Lire un échange TCP" },
    title: "Protocoles de transport et du web",
    description: "Ce module t’apprend à lire les transports réseau et une conversation web réelle, des ports locaux jusqu’aux requêtes HTTP dans TLS. Critères de réussite : interpréter un port ou un service exposé, distinguer ce qu’UDP et ICMP racontent d’un incident, et lire une requête web avec son niveau de protection réel.",
    lessons: [
      portsLesson,
      { key: "reseaux-tcp", existing: true },
      udpIcmpLesson,
      { key: "reseaux-dns-arp", existing: true },
      httpTlsLesson,
    ],
  },
];
