import {
  code,
  example,
  figure,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const xssLesson: NewLesson = {
  key: "web-xss",
  title: "Cross-Site Scripting : réfléchi, stocké, DOM et leurs remèdes",
  summary: "Tu vas distinguer les trois familles de XSS, lire leurs points d’injection, puis appliquer le bon remède : encodage de sortie, DOM sûr, assainissement du HTML riche et défenses en profondeur.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("définir ce qu’un XSS permet, distinguer les variantes réfléchi, stocké et DOM, reconnaître un point d’injection, choisir le bon encodage selon le contexte, remplacer « innerHTML » quand il ne faut que du texte, et expliquer les limites d’une défense seule."),
    prerequisites("avoir vu la différence entre une entrée non fiable et une sortie HTML, et savoir qu’un navigateur exécute du JavaScript dans l’origine du site affiché."),
    scenario("Chez Baobab Tech, Awa relit une page de commentaires et un petit script de recherche. Rien ne ressemble à une « attaque » spectaculaire : seulement du HTML, une zone de texte et quelques lignes JavaScript. Pourtant, si une donnée non fiable ressort sans protection, le navigateur l’exécutera avec les droits du site. Awa doit donc reconnaître où le script naît, ce qu’il peut faire, et surtout comment l’empêcher proprement."),
    videoSlot("Comprendre un XSS sans l’exécuter dans un navigateur"),
    text("Un XSS, ou cross-site scripting, apparaît quand une application renvoie ou réinsère une donnée non fiable dans une page sans la traiter pour son contexte réel. L’attaquant n’exécute pas son code « sur le serveur » : il le fait exécuter dans le navigateur de la victime, mais dans l’origine du site visité. Cela suffit pour lire ou modifier le contenu de la page, déclencher des actions avec la session courante, voler ce qui reste accessible à JavaScript, ou piéger l’utilisateur avec une interface trompeuse."),
    figure({
      kind: "cards",
      title: "Trois familles à distinguer",
      columns: 3,
      items: [
        { term: "XSS réfléchi", text: "La donnée revient dans la réponse à la même requête. Exemple : un terme de recherche réaffiché sans encodage.", tone: "amber", icon: "message" },
        { term: "XSS stocké", text: "La donnée dangereuse est enregistrée puis servie à d’autres. Exemple : un commentaire publié et relu plus tard.", tone: "red", icon: "database" },
        { term: "XSS DOM", text: "Le navigateur réinjecte lui-même la donnée dans le DOM. Exemple : un script lit `location.hash` puis écrit dans `innerHTML`.", tone: "violet", icon: "code" },
      ],
    }),
    text("La correction dépend du contexte de sortie. Dans le corps HTML, tu échappes au minimum « & », « < », « > », « \" » et « ' ». Dans un attribut, tu gardes toujours des guillemets autour de la valeur, puis tu l’échappes aussi. Dans le JavaScript, tu n’insères jamais une chaîne brute dans du code : tu la sors en JSON sérialisé, puis tu la traites comme donnée. Dans le DOM, « textContent » convient quand tu veux afficher du texte ; « innerHTML » devient un point d’injection dès que tu lui donnes une donnée non fiable. Pour une URL, tu valides le schéma et tu refuses « javascript: ». Pour du HTML riche volontaire, tu passes par un assainissement éprouvé, par exemple DOMPurify, avec une liste autorisée de balises."),
    text("Les moteurs de gabarits modernes échappent souvent par défaut. Les failles viennent alors des contournements : « |safe », « {{{ ... }}} », « dangerouslySetInnerHTML », « v-html » ou une réinjection directe avec « innerHTML ». Une CSP stricte, des cookies « HttpOnly » et, selon le navigateur, « Trusted Types » limitent l’impact, mais aucune de ces défenses ne remplace l’encodage de sortie. De la même manière, filtrer des mots comme « script » ne suffit pas : tu dois raisonner par contexte, pas par liste noire."),
    text("Démonstration guidée : ce script Node.js ne lance aucun navigateur. Il montre seulement la différence entre une sortie brute et une sortie échappée. Avant de le rejouer, vérifie ta version avec « node --version ». Si Node.js est trop ancien pour cette syntaxe JavaScript, mets-le à jour vers une version LTS récente. Tu peux le relire comme un test défensif : si la sortie « sûre » contient encore des balises interprétables, la fonction d’encodage est insuffisante."),
    code([
      "const escapeHtml = (value) => String(value)",
      "  .replace(/&/g, \"&amp;\")",
      "  .replace(/</g, \"&lt;\")",
      "  .replace(/>/g, \"&gt;\")",
      "  .replace(/\\\"/g, \"&quot;\")",
      "  .replace(/'/g, \"&#39;\");",
      "",
      "const inputs = [",
      "  \"bonjour\",",
      "  \"<b>promo</b>\",",
      "  \"\\\"citation\\\" & déjà\",",
      "  \"<img src=x onerror=alert(1)>\",",
      "  \"Ama & Koffi <admin>\",",
      "];",
      "",
      "for (const input of inputs) {",
      "  const unsafe = `<p>${input}</p>`;",
      "  const safe = `<p>${escapeHtml(input)}</p>`;",
      "  console.log(JSON.stringify({ input, unsafe, safe }));",
      "}",
      "// exemple de sortie (valeurs fictives)",
      "// {\"input\":\"bonjour\",\"unsafe\":\"<p>bonjour</p>\",\"safe\":\"<p>bonjour</p>\"}",
      "// {\"input\":\"<b>promo</b>\",\"unsafe\":\"<p><b>promo</b></p>\",\"safe\":\"<p>&lt;b&gt;promo&lt;/b&gt;</p>\"}",
      "// {\"input\":\"\\\"citation\\\" & déjà\",\"unsafe\":\"<p>\\\"citation\\\" & déjà</p>\",\"safe\":\"<p>&quot;citation&quot; &amp; déjà</p>\"}",
      "// {\"input\":\"<img src=x onerror=alert(1)>\",\"unsafe\":\"<p><img src=x onerror=alert(1)></p>\",\"safe\":\"<p>&lt;img src=x onerror=alert(1)&gt;</p>\"}",
      "// {\"input\":\"Ama & Koffi <admin>\",\"unsafe\":\"<p>Ama & Koffi <admin></p>\",\"safe\":\"<p>Ama &amp; Koffi &lt;admin&gt;</p>\"}",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : dans un journal d’accès, la chaîne « <script>alert(1)</script> » ou « <img src=x onerror=alert(1)> » signale une tentative, pas forcément une réussite. Si ton application la renvoie ensuite telle quelle dans une page de recherche, tu fabriques un XSS réfléchi. Si elle l’enregistre dans un commentaire et la ressert à tout le monde, tu fabriques un XSS stocké. Si ton script lit « location.hash » puis le colle dans « innerHTML », tu crées un XSS DOM. Dans les trois cas, le bon réflexe défensif reste le même : donnée non fiable, contexte de sortie identifié, remède adapté."),
    mistakes("penser qu’un XSS « vole toujours les cookies » alors qu’un cookie « HttpOnly » limite précisément cette lecture ; croire qu’un filtre de mots interdits suffit ; utiliser « innerHTML » quand seul du texte doit être affiché ; faire confiance à un échappement par défaut puis le désactiver localement pour « aller plus vite »."),
    safety("les exemples de chaînes dangereuses servent uniquement à la défense et à la lecture des journaux. Tu ne les rejoues que sur ton code de test, jamais sur un site tiers. Un journal d’accès ou un commentaire exporté peuvent contenir des données personnelles : ne les publie pas et ne les envoie pas à un service externe sans nécessité."),
    takeaway("un XSS exécute du JavaScript dans l’origine du site. La famille change, le principe reste : une donnée non fiable est réinterprétée comme du code ou du HTML actif. L’encodage de sortie selon le contexte est la défense de base ; CSP, « HttpOnly » et l’assainissement viennent ensuite en profondeur."),
    practice("Travaille dans « TP 3 : XSS, CSP et en-têtes : évaluer une politique » : classe les points d’injection, explique quel contexte de sortie est concerné, puis justifie la correction attendue avant de finir par le quiz."),
    reference("owaspCsXss"),
    reference("owaspCsDomXss"),
    reference("owaspXss"),
    reference("mdnTrustedTypes"),
  ],
  quiz: {
    title: "Quiz : XSS et remèdes",
    questions: [
      questions.choice("Quelle phrase décrit le mieux l’impact d’un XSS ?", ["Il exécute du script dans le navigateur de la victime, dans l’origine du site", "Il remplace toujours le mot de passe stocké en base", "Il contourne automatiquement tout contrôle d’accès serveur", "Il chiffre le contenu de la page avant lecture"], 0, "Un XSS agit dans le navigateur, avec le contexte du site affiché. Il peut donc déclencher des actions, lire la page ou tromper l’utilisateur. Les autres réponses confondent l’effet d’un script injecté avec des conséquences possibles mais non garanties.", "facile"),
      questions.choice("Quel choix est le plus sûr si tu veux afficher un texte venu de l’utilisateur dans une zone du DOM ?", ["« innerHTML » directement, pour garder la mise en forme", "« textContent », puis un assainissement séparé si tu veux vraiment du HTML riche", "Une expression régulière qui supprime seulement le mot « script »", "Un commentaire HTML caché"], 1, "« textContent » traite la valeur comme du texte, donc le navigateur ne l’interprète pas comme du HTML. Le faux ami le plus tentant est « innerHTML » : il paraît pratique, mais il ouvre exactement le point d’injection que l’on veut éviter.", "moyen"),
      questions.choice("Tu vois « {{{ commentaire }}} » ou « |safe » dans un gabarit. Quel risque te vient d’abord à l’esprit ?", ["Un risque de session trop courte", "Un risque de XSS si la donnée n’est pas déjà traitée pour son contexte", "Un risque de TLS obsolète", "Un risque de cookie sans « Secure »"], 1, "Ces contournements désactivent souvent l’échappement automatique du moteur de gabarits. La bonne alerte mentale est donc le XSS. Les autres risques existent ailleurs dans une application, mais pas dans ce point précis du rendu HTML.", "difficile"),
      questions.multi("Quelles défenses relèvent bien de la profondeur de défense contre le XSS, sans remplacer l’encodage de sortie ? (plusieurs réponses)", ["Une CSP stricte", "Des cookies « HttpOnly »", "Supprimer le mot « alert » dans les entrées", "Trusted Types dans les navigateurs qui les supportent"], [0, 1, 3], "Une CSP stricte, « HttpOnly » et Trusted Types limitent l’impact ou certains chemins d’exploitation. En revanche, supprimer un mot précis n’est pas une défense correcte : c’est une liste noire contournable qui ne comprend pas le contexte réel de la sortie.", "moyen"),
    ],
  },
};

const cspLesson: NewLesson = {
  key: "web-csp",
  title: "Content Security Policy : écrire et évaluer une politique",
  summary: "Tu apprendras à lire une politique CSP, à distinguer une politique faible d’une politique utile, puis à tester une politique avec des nonces, des hachages et un mode de déploiement prudent.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("définir ce que limite une CSP, reconnaître ses directives principales, distinguer une politique faible d’une politique forte, générer un nonce ou un hachage de script, repérer des sources dangereuses, et expliquer pourquoi la CSP complète mais ne remplace pas l’encodage."),
    prerequisites("avoir compris ce qu’est un XSS et pourquoi une page peut charger du code depuis plusieurs origines ou depuis un script inline."),
    scenario("À l’association Teranga, Kwame doit durcir un petit tableau de bord sans tout casser. L’application a déjà des gabarits qui échappent correctement, mais l’équipe charge encore quelques scripts inline et une bibliothèque tierce. Kwame veut donc écrire une CSP qui limite vraiment les chargements, tout en gardant une phase d’observation avant d’appliquer la politique en production."),
    videoSlot("Passer d’une CSP décorative à une CSP utile"),
    text("La Content Security Policy, ou CSP, est un en-tête de réponse qui indique au navigateur quelles ressources une page est autorisée à charger ou à exécuter. Elle réduit l’impact d’un XSS, de certains chargements tiers non voulus et d’autres formes d’injection de contenu. Elle ne « corrige » pourtant pas une page vulnérable : si tu réinjectes une donnée non fiable, la cause reste là. La CSP agit comme une barrière supplémentaire entre cette faute et le navigateur."),
    figure({
      kind: "table",
      title: "Directives utiles à connaître",
      columns: ["Directive", "Rôle"],
      rows: [
        ["default-src", "règle par défaut"],
        ["script-src", "scripts autorisés"],
        ["style-src", "feuilles de style autorisées"],
        ["img-src", "images autorisées"],
        ["connect-src", "appels réseau autorisés"],
        ["frame-ancestors", "qui peut intégrer la page"],
        ["base-uri", "contrôle la balise base"],
        ["form-action", "destinations de formulaire"],
        ["object-src", "souvent à `none` dans la majorité des cas"],
      ],
      mono: [0],
    }),
    text("Une politique faible laisse souvent « 'unsafe-inline' », « 'unsafe-eval' », « * » ou même « data: » dans « script-src ». À l’inverse, une politique moderne pour les scripts préfère un nonce aléatoire par réponse, éventuellement combiné à « 'strict-dynamic' ». Pour un script inline stable, tu peux aussi calculer un hachage « sha256-… ». La directive « frame-ancestors » protège contre l’intégration dans un cadre, « base-uri » évite qu’une balise « base » change le sens des liens, et « object-src 'none' » coupe une vieille surface d’attaque rarement nécessaire aujourd’hui."),
    text("Le déploiement prudent se fait en deux temps. D’abord « Content-Security-Policy-Report-Only », pour observer ce que la page casserait si la politique était appliquée. Ensuite la politique active, une fois les violations triées. Un rapport de violation arrive en JSON et peut partir vers un endpoint nommé avec « report-to », puis mappé par l’en-tête « Reporting-Endpoints ». Pour des navigateurs plus anciens, « report-uri » peut encore servir de repli. Cela ne dispense pas d’une relecture humaine : un site complexe peut produire beaucoup de bruit. De plus, un outil d’évaluation n’est qu’un indicateur. Une bonne note ne vaut pas revue d’architecture."),
    text("Démonstration guidée : ce script Node.js fait deux choses. Il génère un nonce, calcule le hachage d’un script inline, puis vérifie rapidement si une politique contient des sources trop permissives ou oublie des directives attendues. Avant de le rejouer, vérifie ta version avec « node --version ». Si Node.js est trop ancien pour cette syntaxe JavaScript, mets-le à jour vers une version LTS récente. Le but n’est pas de remplacer un parseur complet, mais d’apprendre les signaux défensifs à repérer immédiatement."),
    code([
      "const crypto = require(\"crypto\");",
      "",
      "const policy = \"default-src 'self'; script-src 'self' 'unsafe-inline' data:; style-src 'self'; img-src 'self' https://cdn.example.org\";",
      "const inlineScript = \"console.log('bonjour');\";",
      "const nonce = crypto.randomBytes(16).toString(\"base64\");",
      "const hash = crypto.createHash(\"sha256\").update(inlineScript).digest(\"base64\");",
      "",
      "const findings = [];",
      "if (/script-src[^;]*'unsafe-inline'/.test(policy)) findings.push(\"script-src contient 'unsafe-inline'\");",
      "if (/script-src[^;]*'unsafe-eval'/.test(policy)) findings.push(\"script-src contient 'unsafe-eval'\");",
      "if (/script-src[^;]*\\*/.test(policy)) findings.push(\"script-src contient *\");",
      "if (/script-src[^;]*data:/.test(policy)) findings.push(\"script-src contient data:\");",
      "if (!/object-src/.test(policy)) findings.push(\"object-src manque\");",
      "if (!/base-uri/.test(policy)) findings.push(\"base-uri manque\");",
      "",
      "console.log(JSON.stringify({ nonce, hash: `sha256-${hash}`, findings }, null, 2));",
      "// exemple de sortie",
      "// {",
      "//   \"nonce\": \"<change à chaque exécution>\",",
      "//   \"hash\": \"sha256-Jn2Y2xtz4ER+BNZCE8baFKzydzPnBVF6+i6nOCQOYeA=\",",
      "//   \"findings\": [",
      "//     \"script-src contient 'unsafe-inline'\",",
      "//     \"script-src contient data:\",",
      "//     \"object-src manque\",",
      "//     \"base-uri manque\"",
      "//   ]",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : compare trois politiques inventées. 1. « script-src 'self' 'unsafe-inline' » reste faible : le navigateur peut encore exécuter du script inline, ce qui réduit fortement la valeur de la CSP contre le XSS. 2. « script-src 'self' 'nonce-…' 'strict-dynamic'; object-src 'none'; base-uri 'none' » est beaucoup plus défendable. 3. « script-src * » paraît simple, mais elle autorise trop de sources et ne protège presque rien. La question à te poser n’est pas « y a-t-il une CSP ? » mais « qu’autorise réellement cette CSP ? »"),
    mistakes("poser une CSP et croire que l’application est « corrigée » ; conserver « 'unsafe-inline' » par confort sans plan pour l’enlever ; oublier « object-src 'none' » et « base-uri 'none' » ; déployer directement une politique active sans phase « Report-Only » sur un site vivant."),
    safety("tu testes la CSP sur tes propres pages ou un environnement autorisé. Si tu collectes des rapports de violation, traite-les comme des données applicatives : ils peuvent contenir des chemins, des origines, voire des éléments de page qu’il ne faut pas publier sans contrôle."),
    takeaway("la CSP dit au navigateur quoi charger et quoi exécuter. Une bonne politique réduit l’impact d’un XSS, mais elle ne remplace pas l’encodage de sortie. Cherche les signaux faibles d’une politique décorative : « 'unsafe-inline' », « * », « data: », ou l’absence de directives de base comme « object-src » et « base-uri »."),
    practice("Travaille dans « TP 3 : XSS, CSP et en-têtes : évaluer une politique » : lis plusieurs politiques, repère ce qu’elles laissent passer, interprète un rapport de violation, puis termine par le quiz."),
    reference("mdnCspHeader"),
    reference("owaspCsCsp"),
    reference("cspEvaluator"),
    reference("mdnCspReportTo"),
    reference("mdnCspReportUri"),
    reference("mdnReportingEndpoints"),
  ],
  quiz: {
    title: "Quiz : CSP",
    questions: [
      questions.choice("Quel est le meilleur résumé du rôle d’une CSP ?", ["Elle remplace les correctifs applicatifs et l’encodage de sortie", "Elle indique au navigateur quelles ressources une page peut charger ou exécuter", "Elle chiffre automatiquement les cookies de session", "Elle empêche toute erreur de logique métier"], 1, "La CSP agit dans le navigateur et limite les chargements ou exécutions permis. Elle complète donc la sécurité applicative, mais ne remplace ni un correctif de code, ni l’encodage de sortie, ni les autres contrôles serveur.", "facile"),
      questions.choice("Quelle politique est la plus inquiétante pour « script-src » ?", ["« script-src 'self' 'nonce-abc123' »", "« script-src 'self' https://cdn.example.org »", "« script-src 'self' 'unsafe-inline' data: »", "« script-src 'self'; object-src 'none' »"], 2, "La présence de « 'unsafe-inline' » et de « data: » dans « script-src » ouvre beaucoup trop de possibilités et affaiblit directement l’objectif défensif de la politique. Les autres réponses restent plus strictes, même si elles doivent encore être évaluées dans leur contexte complet.", "moyen"),
      questions.choice("Pourquoi déployer d’abord « Content-Security-Policy-Report-Only » ?", ["Pour autoriser plus de scripts inline que la politique finale", "Pour observer les violations sans casser immédiatement la page", "Pour désactiver la vérification TLS", "Pour contourner les cookies « HttpOnly »"], 1, "Le mode « Report-Only » sert à voir ce que la politique bloquerait, sans encore bloquer la production. Le piège serait de croire qu’il rend la politique « plus permissive » par nature : il change le mode d’application, pas la logique de ce qui est jugé interdit.", "difficile"),
      questions.multi("Quelles directives ou pratiques renforcent bien une CSP moderne pour les scripts ? (plusieurs réponses)", ["Un nonce aléatoire par réponse", "« 'strict-dynamic' » quand l’architecture l’exige", "« object-src 'none' »", "« script-src * 'unsafe-inline' »"], [0, 1, 2], "Un nonce, « 'strict-dynamic' » et « object-src 'none' » renforcent réellement une politique utile. À l’inverse, « script-src * 'unsafe-inline' » ressemble à une CSP, mais elle autorise tellement de choses qu’elle protège mal contre les injections de script.", "moyen"),
    ],
  },
};

const headersLesson: NewLesson = {
  key: "web-en-tetes-securite",
  title: "En-têtes de sécurité : HSTS, nosniff, cadres, référent et autorisations",
  summary: "Cette leçon t’apprend à lire les principaux en-têtes de sécurité, à savoir ce qu’ils empêchent réellement, puis à les poser côté serveur ou application sans leur prêter des pouvoirs qu’ils n’ont pas.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("identifier les principaux en-têtes de sécurité, expliquer l’effet réel de chacun, distinguer ce qui protège le navigateur de ce qui protège le serveur, lire un jeu d’en-têtes avec esprit critique, et proposer une valeur raisonnable quand elle est attendue."),
    prerequisites("avoir déjà vu HTTPS, l’origine web, la CSP, et compris qu’un en-tête de réponse est une instruction envoyée par le serveur au navigateur."),
    scenario("À la boutique Soleil, Ama récupère les en-têtes d’un site après une mise en ligne. La page « fonctionne », mais le tableau de bord de vérification signale des absences et quelques valeurs discutables. Ama doit donc lire les en-têtes sans tomber dans le piège du score magique : certains manques sont graves, d’autres utiles mais secondaires, et aucun en-tête n’efface une faille applicative à lui seul."),
    videoSlot("Lire un jeu d’en-têtes sans confondre présence et protection réelle"),
    text("Les en-têtes de sécurité sont des instructions de réponse HTTP qui changent le comportement du navigateur. Ils n’empêchent pas tout, mais ils ferment des chemins d’exploitation fréquents ou limitent des fuites inutiles. Ils vivent dans la réponse, donc leur effet dépend de ce que le navigateur comprend et reçoit réellement. La bonne question n’est pas seulement « l’en-tête est-il là ? », mais « quelle valeur porte-t-il et quel risque couvre-t-il ? »."),
    figure({
      kind: "table",
      title: "En-têtes de sécurité et rôle principal",
      columns: ["En-tête", "Rôle défensif principal"],
      rows: [
        ["Strict-Transport-Security", "force l’usage de HTTPS pour le domaine"],
        ["X-Content-Type-Options", "empêche le « sniffing » de type avec `nosniff`"],
        ["Referrer-Policy", "limite ce que le navigateur révèle en `Referer`"],
        ["Permissions-Policy", "autorise ou refuse certaines capacités du navigateur"],
        ["Cross-Origin-*", "isole la page ou ses ressources selon le besoin"],
        ["X-Frame-Options", "limite l’intégration en cadre, ancien mécanisme"],
        ["Content-Security-Policy", "cadre plus large, y compris `frame-ancestors`"],
        ["Cache-Control: no-store", "évite le stockage de réponses sensibles"],
      ],
      mono: [0],
    }),
    text("HSTS, via « Strict-Transport-Security », informe le navigateur que l’hôte doit être contacté en HTTPS seulement. Il aide aussi à empêcher le contournement d’erreurs de connexion sécurisée lors des visites suivantes. « max-age=31536000 » correspond à un an. « includeSubDomains » étend la règle aux sous-domaines, ce qui exige une vraie préparation. « nosniff » réduit l’interprétation hasardeuse des types par le navigateur. « Referrer-Policy » limite la quantité d’information transmise dans l’en-tête « Referer ». « Permissions-Policy » coupe des capacités comme la caméra, le micro ou la géolocalisation quand elles ne sont pas nécessaires. « Cross-Origin-Opener-Policy », « Cross-Origin-Embedder-Policy » et « Cross-Origin-Resource-Policy » servent, eux, à isoler une page ou ses ressources selon les besoins. « X-Frame-Options » reste utile sur d’anciens navigateurs, mais « frame-ancestors » dans la CSP offre aujourd’hui un contrôle plus moderne."),
    text("Tous ces en-têtes ont des limites. HSTS ne dit rien sur l’honnêteté du site et ne protège pas la toute première visite sans préchargement HSTS. « nosniff » ne corrige pas un téléversement dangereux. « Permissions-Policy » ne répare pas une logique métier. Cacher « Server » ou « X-Powered-By » réduit un peu la fuite d’information, mais ne constitue pas une protection au même niveau qu’une bonne authentification ou qu’un correctif. Enfin, « X-XSS-Protection » est obsolète : tu ne comptes pas dessus."),
    text("Démonstration guidée : ce script Node.js lit un petit jeu d’en-têtes inventé et produit une appréciation simple. Avant de le rejouer, vérifie ta version avec « node --version ». Si Node.js est trop ancien pour cette syntaxe JavaScript, mets-le à jour vers une version LTS récente. Le but n’est pas d’imiter un service d’audit complet, mais de vérifier si l’essentiel est présent avec une valeur cohérente. Tu peux ensuite poser les mêmes en-têtes côté serveur web, CDN ou application. Par exemple, dans Express, un « app.use » peut définir « nosniff » ou « Referrer-Policy » ; dans nginx, tu utiliserais une directive « add_header » dans le bon bloc."),
    code([
      "const headers = {",
      "  \"strict-transport-security\": \"max-age=31536000; includeSubDomains\",",
      "  \"x-content-type-options\": \"nosniff\",",
      "  \"referrer-policy\": \"strict-origin-when-cross-origin\",",
      "  \"permissions-policy\": \"camera=(), microphone=(), geolocation=()\",",
      "  \"x-frame-options\": \"SAMEORIGIN\",",
      "  \"cache-control\": \"no-store\",",
      "};",
      "",
      "const findings = [];",
      "if (!headers[\"strict-transport-security\"]) findings.push(\"HSTS manquant\");",
      "if (headers[\"x-content-type-options\"] !== \"nosniff\") findings.push(\"nosniff manquant ou incorrect\");",
      "if (!headers[\"referrer-policy\"]) findings.push(\"Referrer-Policy manquant\");",
      "if (!headers[\"permissions-policy\"]) findings.push(\"Permissions-Policy manquant\");",
      "if (!headers[\"x-frame-options\"]) findings.push(\"X-Frame-Options manquant\");",
      "if (!/no-store/.test(headers[\"cache-control\"] || \"\")) findings.push(\"Cache-Control sans no-store pour réponse sensible\");",
      "",
      "console.log(JSON.stringify({ ok: findings.length === 0, findings }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"ok\": true,",
      "//   \"findings\": []",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : un site peut obtenir une « bonne allure » avec HSTS et « nosniff », tout en laissant une page d’administration intégrable dans un cadre si « frame-ancestors » ou « X-Frame-Options » manquent. À l’inverse, une valeur « Referrer-Policy: strict-origin-when-cross-origin » réduit déjà proprement la fuite d’URL complètes vers d’autres origines. Le jugement défensif consiste donc à hiérarchiser : d’abord TLS et les protections du navigateur réellement utiles, puis les réductions de bruit ou d’empreinte comme « Server »."),
    mistakes("confondre présence et qualité d’une valeur ; croire qu’un score d’outil remplace une lecture humaine ; poser HSTS avant d’être prêt sur tous les sous-domaines ; s’appuyer sur « X-XSS-Protection » alors qu’il est obsolète."),
    safety("vérifie ces en-têtes seulement sur ton propre site ou dans le périmètre autorisé. Un outil externe d’audit doit rester dans le cadre prévu par ton organisation. Et si tu captures des réponses contenant des données personnelles, ne diffuse pas plus d’informations que nécessaire."),
    takeaway("les en-têtes de sécurité parlent surtout au navigateur. Ils ferment des chemins connus, mais ne remplacent ni un correctif applicatif ni une revue d’architecture. Lis leur valeur exacte, comprends leur rôle, puis décide lesquels sont essentiels pour le risque que tu traites."),
    practice("Travaille dans « TP 3 : XSS, CSP et en-têtes : évaluer une politique » : lis un jeu d’en-têtes, explique ce que chaque valeur protège ou non, puis termine par le quiz."),
    reference("rfc6797"),
    reference("owaspCsHeaders"),
    reference("mdnNosniff"),
    reference("mdnReferrerPolicy"),
    reference("mdnPermissionsPolicy"),
    reference("mdnCoop"),
    reference("mdnXFrameOptions"),
  ],
  quiz: {
    title: "Quiz : en-têtes de sécurité",
    questions: [
      questions.choice("À quoi sert d’abord « Strict-Transport-Security » ?", ["À forcer le navigateur à revenir en HTTP si le certificat change", "À indiquer que le domaine ne doit être contacté qu’en HTTPS lors des visites suivantes", "À empêcher tout XSS côté navigateur", "À cacher le nom du serveur web"], 1, "HSTS sert à imposer l’usage de HTTPS pour l’hôte et à empêcher certaines rétrogradations ou contournements lors des visites suivantes. Il ne corrige ni un XSS ni une fuite d’information côté application.", "facile"),
      questions.choice("Quelle valeur attend-on pour « X-Content-Type-Options » quand on veut empêcher le « sniffing » de type ?", ["none", "nosniff", "sameorigin", "strict"], 1, "La valeur défensive attendue est « nosniff ». Les autres réponses ressemblent à des mots de configuration plausibles, mais elles n’ont pas la signification voulue pour cet en-tête précis.", "moyen"),
      questions.choice("Tu lis « X-XSS-Protection: 1; mode=block » sur un site moderne. Quelle lecture est la plus saine ?", ["Cet en-tête est obsolète et ne doit pas servir de pilier défensif", "C’est une défense suffisante contre le XSS", "Il remplace une CSP stricte", "Il vaut seulement pour les cookies"], 0, "« X-XSS-Protection » est obsolète et ne constitue plus une base sérieuse de défense. Le piège serait de voir sa présence comme une preuve de protection alors que les navigateurs modernes ne s’y appuient plus comme avant.", "difficile"),
      questions.multi("Quels éléments protègent surtout le navigateur, sans corriger la logique applicative elle-même ? (plusieurs réponses)", ["HSTS", "Referrer-Policy", "Permissions-Policy", "La suppression d’un SQL concaténé vulnérable"], [0, 1, 2], "HSTS, « Referrer-Policy » et « Permissions-Policy » modifient le comportement du navigateur ou la confidentialité des échanges. En revanche, supprimer une concaténation SQL vulnérable corrige directement l’application elle-même : ce n’est plus un simple en-tête de réponse.", "moyen"),
    ],
  },
};

const sessionsLesson: NewLesson = {
  key: "web-sessions",
  title: "Sessions et cookies : identifiant, fixation, expiration et déconnexion",
  summary: "Tu verras comment HTTP sans état devient une session, quels attributs de cookie comptent vraiment, puis comment éviter fixation, réutilisation et déconnexion incomplète.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer pourquoi HTTP est sans état, décrire le rôle d’un identifiant de session, lire un en-tête « Set-Cookie », repérer une fixation de session, distinguer expiration d’inactivité et durée absolue, puis vérifier qu’une déconnexion invalide bien la session côté serveur."),
    prerequisites("avoir vu les cookies HTTP, l’origine web et le fait que le navigateur renvoie automatiquement un cookie au même site selon ses attributs."),
    scenario("Pour la boutique Soleil, Fatou audite une petite application qui fonctionne « simplement ». Pourtant, un détail la gêne : le même identifiant de session apparaît avant et après la connexion, et la déconnexion ne coupe pas toujours toutes les actions en arrière-plan. Fatou doit montrer pourquoi ces détails comptent, même quand la page semble correcte pour l’utilisateur."),
    videoSlot("Suivre une session du premier cookie à la vraie déconnexion"),
    text("HTTP est sans état : chaque requête arrive sans mémoire native de la précédente. La session côté serveur contourne cette limite en associant un identifiant aléatoire à un état conservé sur le serveur, puis en transportant cet identifiant dans un cookie. Ce cookie n’est donc pas « la session » : il n’en est que la clé côté client. Si cette clé est prévisible, réutilisée ou mal protégée, toute la session devient fragile."),
    figure({
      kind: "anatomy",
      title: "Cookie de session défensif",
      lines: [
        [
          { text: "Set-Cookie:", label: "en-tête HTTP", tone: "neutral" },
          { text: "__Host-session=RND...", label: "nom et identifiant", tone: "green" },
        ],
        [
          { text: "Path=/", label: "racine du site", tone: "blue" },
          { text: "Secure", label: "HTTPS seulement", tone: "green" },
          { text: "HttpOnly", label: "pas via JavaScript", tone: "violet" },
        ],
        [
          { text: "SameSite=Lax", label: "limite l’intersite", tone: "amber" },
          { text: "Max-Age=1800", label: "durée du cookie", tone: "cyan" },
        ],
      ],
      caption: "`__Host-` impose `Secure`, `Path=/` et l’absence de `Domain`.",
    }),
    text("Les attributs du cookie réduisent des risques précis. « Secure » évite l’envoi en clair sur HTTP. « HttpOnly » empêche JavaScript de lire le cookie directement, ce qui limite le vol par XSS sans empêcher un script injecté d’utiliser la session déjà présente. « SameSite » réduit des scénarios de CSRF selon la valeur choisie, et « SameSite=None » exige aussi « Secure ». Le préfixe « __Host- » renforce le cadre en exigeant « Secure », « Path=/ » et l’absence de « Domain ». Mais ces attributs ne suffisent pas : la vraie logique de session vit côté serveur."),
    text("La fixation de session apparaît quand l’application accepte de continuer après la connexion avec le même identifiant qu’avant. La défense consiste à régénérer l’identifiant à la connexion et à chaque changement de privilège. La déconnexion doit invalider la session côté serveur, pas seulement supprimer le cookie dans le navigateur. Sinon, une copie du même identifiant peut rester exploitable ailleurs. Enfin, une bonne gestion de session combine au moins une expiration d’inactivité et une durée absolue, car un identifiant vivant trop longtemps augmente la surface de réutilisation."),
    text("Démonstration guidée : ce petit serveur Node.js d’essai écoute en local. Il pose un cookie « invité », puis le régénère lors de la connexion sans accepter un identifiant inventé par le client. Avant de le rejouer, vérifie « node --version » et « curl.exe --version ». Comme cette démo reste volontairement en HTTP local pour rester simple avec « curl.exe », le cookie d’essai retire temporairement « Secure » afin que la rotation soit observable ; en production HTTPS, tu remets « Secure ». Avec « curl -i », tu lis les en-têtes « Set-Cookie » avant et après la connexion en réutilisant le même bocal de cookies. La preuve utile est là : l’identifiant change réellement."),
    code([
      "# server-session-demo.cjs",
      "const http = require(\"http\");",
      "const crypto = require(\"crypto\");",
      "const sessions = new Map();",
      "const newId = () => crypto.randomBytes(12).toString(\"hex\");",
      "const getId = (cookie = \"\") => {",
      "  const match = /demo-session=([^;]+)/.exec(cookie);",
      "  return match ? match[1] : null;",
      "};",
      "// Démo locale en HTTP : Secure est retiré ici pour que curl.exe puisse rejouer la rotation.",
      "const sendCookie = (res, id) => res.setHeader(\"Set-Cookie\", `demo-session=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=1800`);",
      "const server = http.createServer((req, res) => {",
      "  const current = getId(req.headers.cookie);",
      "  if (req.url === \"/\") {",
      "    const id = current && sessions.has(current) ? current : newId();",
      "    if (!sessions.has(id)) sessions.set(id, { role: \"guest\" });",
      "    sendCookie(res, id);",
      "    res.end(`role=${sessions.get(id).role}`);",
      "    return;",
      "  }",
      "  if (req.url === \"/login\") {",
      "    if (current && sessions.has(current)) sessions.delete(current);",
      "    const id = newId();",
      "    sessions.set(id, { role: \"member\" });",
      "    sendCookie(res, id);",
      "    res.end(`role=${sessions.get(id).role}`);",
      "    return;",
      "  }",
      "  res.statusCode = 404;",
      "  res.end(\"not found\");",
      "});",
      "server.listen(8087, \"127.0.0.1\", () => console.log(\"ready\"));",
      "",
      "# commandes vérifiées avec curl",
      "curl.exe -i -c cookies.txt http://127.0.0.1:8087/",
      "curl.exe -i -b cookies.txt -c cookies.txt http://127.0.0.1:8087/login",
      "# exemple de sortie (valeurs fictives)",
      "# HTTP/1.1 200 OK",
      "# Set-Cookie: demo-session=4fd4c0a8cdd4d15777c4185f; Path=/; HttpOnly; SameSite=Lax; Max-Age=1800",
      "#",
      "# role=guest",
      "# HTTP/1.1 200 OK",
      "# Set-Cookie: demo-session=ce6d6b4fce2685ad21351767; Path=/; HttpOnly; SameSite=Lax; Max-Age=1800",
      "#",
      "# role=member",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si le même identifiant de session reste visible avant et après la connexion, tu notes un risque de fixation de session. Si le journal montre la même session réutilisée depuis deux zones géographiques incompatibles en quelques minutes, tu notes une réutilisation suspecte. Et si la déconnexion efface seulement le cookie sans invalider l’état côté serveur, tu notes une déconnexion incomplète. Dans tous les cas, la correction prioritaire n’est pas cosmétique : elle touche la logique de génération, rotation et invalidation côté serveur."),
    mistakes("croire que le cookie contient forcément un secret ou un rôle digne de confiance ; supprimer seulement le cookie à la déconnexion ; oublier de régénérer l’identifiant à la connexion ; stocker l’identifiant de session dans l’URL, les journaux ou un espace trop exposé côté client."),
    safety("teste ces mécanismes uniquement sur ton application ou sur un environnement autorisé. Les cookies et journaux de session peuvent contenir des données personnelles ou sensibles. Ne publie pas de vraies valeurs de session, même tronquées, et évite tout service tiers non nécessaire pour les analyser."),
    takeaway("la session côté serveur repose sur un identifiant de cookie bien généré, bien tourné et bien invalidé. « Secure », « HttpOnly », « SameSite » et « __Host- » aident, mais la vraie sécurité vient aussi de la régénération à la connexion, de la déconnexion côté serveur et d’expirations raisonnables."),
    practice("Travaille dans « TP 4 : sessions, jetons JWT et mots de passe » : lis des « Set-Cookie », repère une fixation ou une expiration douteuse, puis termine par le quiz."),
    reference("mdnCookies"),
    reference("mdnSetCookie"),
    reference("rfc6265"),
    reference("rfc6265bis"),
    reference("owaspCsSession"),
    reference("nodeCrypto"),
  ],
  quiz: {
    title: "Quiz : sessions et cookies",
    questions: [
      questions.choice("Pourquoi dit-on que HTTP est sans état ?", ["Parce que le navigateur oublie toujours son historique", "Parce que chaque requête arrive sans mémoire native de la précédente", "Parce que TLS détruit les cookies à chaque page", "Parce que le serveur ne peut jamais savoir qui est connecté"], 1, "HTTP ne transporte pas naturellement une mémoire de session entre deux requêtes. Les applications compensent avec des cookies, des jetons ou d’autres mécanismes. Le piège serait de croire que l’état n’existe jamais : il existe, mais il doit être construit explicitement.", "facile"),
      questions.choice("Quel signe fait penser à une fixation de session ?", ["Le cookie de session change à la connexion", "Le même identifiant de session reste valable avant et après la connexion", "Le cookie porte l’attribut « HttpOnly »", "La réponse contient « Cache-Control: no-store »"], 1, "Si l’identifiant ne change pas au moment critique de la connexion, l’application accepte de continuer avec une clé déjà connue avant authentification. C’est exactement le schéma de la fixation. Les autres indices n’ont pas cette signification.", "moyen"),
      questions.choice("Quelle affirmation est la plus juste sur « HttpOnly » ?", ["Il empêche tout XSS", "Il remplace « Secure »", "Il rend le cookie illisible par JavaScript, mais n’empêche pas un script injecté d’utiliser la session déjà présente", "Il force la rotation de la session à la connexion"], 2, "« HttpOnly » réduit le vol direct du cookie par JavaScript, mais il ne corrige ni la cause d’un XSS ni l’abus d’une session déjà active dans le navigateur. Le faux ami est d’en faire une protection totale contre le XSS.", "difficile"),
      questions.multi("Quelles mesures améliorent réellement la sécurité d’une session côté serveur ? (plusieurs réponses)", ["Régénérer l’identifiant à la connexion", "Invalider la session côté serveur à la déconnexion", "Mettre l’identifiant dans l’URL pour mieux le relire", "Combiner expiration d’inactivité et durée absolue"], [0, 1, 3], "La régénération, l’invalidation côté serveur et des expirations bien pensées traitent directement les principaux risques de réutilisation ou de fixation. Mettre l’identifiant dans l’URL est au contraire une mauvaise pratique, car il fuit dans les journaux, l’historique et parfois dans « Referer ».", "moyen"),
    ],
  },
};

const jwtLesson: NewLesson = {
  key: "web-jwt",
  title: "Jetons JWT : structure, vérification et erreurs classiques",
  summary: "Tu apprendras à décoder un JWT, à vérifier sa signature et ses déclarations, puis à reconnaître les erreurs de mise en œuvre les plus coûteuses : « alg » non maîtrisé, secret faible ou stockage trop exposé.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("décrire les trois parties d’un JWT, décoder un jeton en base64url, vérifier sa signature, contrôler « iss », « aud », « exp » et « nbf », distinguer HS256 de RS256, puis reconnaître plusieurs erreurs de mise en œuvre classiques."),
    prerequisites("savoir ce qu’est un jeton d’authentification et accepter qu’un encodage lisible n’est pas un chiffrement."),
    scenario("Chez Baobab Tech, Moussa trouve un jeton dans un en-tête « Authorization ». Un collègue lui dit : « on ne peut rien en tirer, c’est chiffré ». Moussa doit justement expliquer l’inverse : un JWT signé n’est pas secret par nature, et le vrai travail consiste à vérifier ce qui est déclaré et comment la signature est contrôlée."),
    videoSlot("Décoder et vérifier un JWT sans le prendre pour une boîte noire"),
    text("Un JSON Web Token, ou JWT, est une représentation compacte de déclarations transportées entre deux parties. Sa forme la plus courante tient en trois parties séparées par des points : l’en-tête, la charge utile et la signature. L’en-tête et la charge sont encodés en base64url, donc lisibles par tous après décodage. Ce n’est pas du chiffrement. Tu n’y places donc jamais de secret. La sécurité vient de la signature ou, dans d’autres cas, d’un chiffrement séparé."),
    figure({
      kind: "packet",
      title: "Structure compacte d’un JWT",
      rows: [
        {
          label: "Format",
          fields: [
            { name: "en-tête", note: "typ, alg", weight: 2, tone: "blue" },
            { name: "charge", note: "iss, sub, aud, exp, nbf, iat, jti", weight: 4, tone: "violet" },
            { name: "signature", note: "vérifie les deux premières parties", weight: 3, tone: "green" },
          ],
        },
      ],
      caption: "Forme compacte : `en-tête.charge.signature`.",
    }),
    text("Avec HS256, la signature repose sur un secret partagé. Avec RS256 ou ES256, la vérification utilise une clé publique distincte de la clé privée de signature. Les erreurs les plus coûteuses sont connues : accepter « alg: none », laisser le jeton choisir lui-même l’algorithme, utiliser un secret HS256 faible, oublier de vérifier « exp » ou « aud », ou stocker le jeton dans un espace trop exposé à un XSS. Le serveur doit imposer sa liste d’algorithmes attendus et valider les déclarations utiles à son contexte."),
    text("Le point important est double : un jeton signé peut être lisible et pourtant intègre, et un jeton bien signé peut tout de même être refusé si son « aud » ne correspond pas, s’il a expiré, ou s’il n’est pas encore valable. La signature seule n’est donc pas la totalité de la vérification. Pour relire l’en-tête ou la charge, tu peux passer par Node.js, PowerShell ou Git Bash tant que tu ne confonds pas ce décodage avec une vérification cryptographique. Et la révocation reste difficile pour un JWT autonome : on compense souvent par des durées courtes, un jeton de rafraîchissement distinct et, selon le produit, une liste d’exclusion."),
    text("Démonstration guidée : ce script fabrique un JWT HS256 d’essai avec le secret « secret-d-exemple », le décode, le vérifie, puis montre qu’une charge modifiée casse immédiatement la signature. Avant de le rejouer, vérifie ta version avec « node --version ». Si Node.js est trop ancien pour cette syntaxe JavaScript, mets-le à jour vers une version LTS récente. C’est une lecture défensive, pas un conseil pour fabriquer des jetons maison en production."),
    code([
      "const crypto = require(\"crypto\");",
      "const secret = \"secret-d-exemple\";",
      "const b64url = (value) => Buffer.from(value).toString(\"base64\").replace(/=/g, \"\").replace(/\\+/g, \"-\").replace(/\\//g, \"_\");",
      "const jsonB64 = (obj) => b64url(JSON.stringify(obj));",
      "const sign = (head, body) => crypto.createHmac(\"sha256\", secret).update(`${head}.${body}`).digest(\"base64\").replace(/=/g, \"\").replace(/\\+/g, \"-\").replace(/\\//g, \"_\");",
      "",
      "const header = jsonB64({ alg: \"HS256\", typ: \"JWT\" });",
      "const payload = jsonB64({ iss: \"https://id.example.org\", aud: \"boutique-soleil\", sub: \"awa\", exp: 1910000000, nbf: 1909996400 });",
      "const signature = sign(header, payload);",
      "const token = `${header}.${payload}.${signature}`;",
      "const decoded = JSON.parse(Buffer.from(payload.replace(/-/g, \"+\").replace(/_/g, \"/\"), \"base64\").toString(\"utf8\"));",
      "const valid = sign(header, payload) === signature;",
      "const tamperedPayload = jsonB64({ ...decoded, aud: \"autre-service\" });",
      "const tamperedStillValid = sign(header, tamperedPayload) === signature;",
      "",
      "console.log(JSON.stringify({ token, decoded, valid, tamperedStillValid }, null, 2));",
      "// exemple de sortie abrégée pour la lisibilité",
      "// {",
      "//   \"token\": \"<jwt-d-exemple>\",",
      "//   \"decoded\": {",
      "//     \"iss\": \"https://id.example.org\",",
      "//     \"aud\": \"boutique-soleil\",",
      "//     \"sub\": \"awa\",",
      "//     \"exp\": 1910000000,",
      "//     \"nbf\": 1909996400",
      "//   },",
      "//   \"valid\": true,",
      "//   \"tamperedStillValid\": false",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si un client t’envoie un JWT parfaitement décodé avec « aud: autre-service », une signature encore valide ne suffit pas. Tu le refuses parce que ce jeton n’est pas destiné à ton service. De même, si « exp » est passé, tu le refuses même si la signature reste intacte. La règle saine est donc : signature correcte, algorithme attendu, déclarations contrôlées, contexte respecté."),
    mistakes("croire qu’un JWT « cache » son contenu ; accepter l’algorithme annoncé sans le comparer à la configuration attendue ; garder un secret HS256 trop simple ; ignorer « aud », « iss » ou « exp » sous prétexte que la signature passe."),
    safety("tu ne décodes et ne vérifies que des jetons de test ou des jetons dont l’analyse est autorisée. Un JWT peut contenir des données personnelles, même s’il ne devrait pas contenir de secret. Ne le colle pas dans un service externe sans nécessité, et n’enregistre pas de vrais jetons dans un rapport partagé."),
    takeaway("un JWT signé n’est pas un coffre-fort : en-tête et charge restent lisibles. Ce qui protège le jeton, c’est la signature correcte plus la vérification des déclarations et de l’algorithme attendu. Refuse tout jeton qui ne correspond pas exactement à ton contexte."),
    practice("Travaille dans « TP 4 : sessions, jetons JWT et mots de passe » : décode plusieurs jetons, contrôle leurs déclarations et explique pourquoi certains doivent être refusés, puis termine par le quiz."),
    reference("rfc7519"),
    reference("rfc8725"),
    reference("rfc7515"),
    reference("nodeCrypto"),
  ],
  quiz: {
    title: "Quiz : JWT",
    questions: [
      questions.choice("Que signifie vraiment l’encodage base64url des deux premières parties d’un JWT ?", ["Le contenu est chiffré par défaut", "Le contenu est simplement représenté de façon sûre pour l’URL et reste décodable", "Le contenu ne peut être lu que par le navigateur", "Le contenu change à chaque lecture"], 1, "La base64url sert au transport compact et sûr pour les caractères d’URL, pas au chiffrement. Le piège fréquent est de prendre un jeton opaque pour un contenu secret, alors qu’un simple décodage suffit à lire les déclarations transportées.", "facile"),
      questions.choice("Quelle erreur est la plus dangereuse parmi les suivantes ?", ["Refuser un jeton expiré", "Imposer côté serveur les algorithmes acceptés", "Accepter « alg: none » ou laisser le jeton imposer l’algorithme", "Vérifier « aud » avant d’utiliser le jeton"], 2, "Accepter « alg: none » ou laisser le jeton choisir l’algorithme ouvre la porte à des validations insuffisantes ou détournées. Les autres réponses décrivent au contraire de bons réflexes de vérification côté serveur.", "moyen"),
      questions.choice("Tu lis un jeton dont la signature est correcte, mais « aud » vaut « autre-service ». Quelle décision est juste ?", ["L’accepter, car seule la signature compte", "Le refuser, car la déclaration d’audience ne correspond pas à ton service", "Le convertir automatiquement pour ton application", "L’accepter seulement s’il vient d’un navigateur connu"], 1, "La signature prouve l’intégrité, pas la destination correcte du jeton. Si « aud » ne correspond pas à ton service, ce jeton n’est pas fait pour toi et doit être refusé. Le faux ami consiste précisément à réduire toute la vérification à la seule signature.", "difficile"),
      questions.multi("Quelles vérifications font partie d’une lecture saine d’un JWT ? (plusieurs réponses)", ["Vérifier l’algorithme attendu côté serveur", "Contrôler « exp » et « nbf »", "Accepter le stockage arbitraire partout côté navigateur sans risque", "Contrôler « iss » et « aud » selon le contexte"], [0, 1, 3], "La sécurité d’un JWT dépend de l’algorithme imposé, des dates et des déclarations de contexte comme « iss » et « aud ». En revanche, le stockage côté navigateur reste un vrai sujet d’exposition, surtout face au XSS, et ne doit pas être accepté sans réflexion.", "moyen"),
    ],
  },
};

const oauthLesson: NewLesson = {
  key: "web-oauth-oidc",
  title: "OAuth 2.0 et OpenID Connect : déléguer sans partager son mot de passe",
  summary: "Tu vas distinguer délégation et authentification, suivre le flux code d’autorisation avec PKCE, puis repérer les pièges de redirection, de « state » ou de portées trop larges.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer le but d’OAuth 2.0, distinguer OAuth d’OpenID Connect, nommer les rôles du protocole, suivre le flux code d’autorisation avec PKCE, calculer un « code_challenge », puis reconnaître plusieurs erreurs de mise en œuvre à éviter."),
    prerequisites("avoir déjà vu les sessions et les JWT, et comprendre qu’une application peut avoir besoin d’un accès délégué sans recevoir le mot de passe d’un autre service."),
    scenario("Kwame ajoute une connexion via un fournisseur d’identité à une application de dons de l’association Teranga. L’équipe veut « faire comme les grands sites » sans jamais demander le mot de passe du fournisseur à l’utilisateur. Kwame doit donc expliquer le vrai rôle d’OAuth 2.0, ce qu’OpenID Connect ajoute, et pourquoi un détail comme « state », PKCE ou l’URI de redirection exacte change réellement la sécurité du flux."),
    videoSlot("Comprendre le flux OAuth avec PKCE sans le confondre avec une simple session locale"),
    text("OAuth 2.0 sert à déléguer une autorisation. L’utilisateur n’a pas à donner son mot de passe du fournisseur au client. À la place, le client obtient des jetons après un dialogue avec le serveur d’autorisation, dans un cadre de portées limitées. Les rôles classiques sont le propriétaire de ressource, le client, le serveur d’autorisation et le serveur de ressources. OpenID Connect, ou OIDC, ajoute une couche d’authentification et d’identité au-dessus de ce socle. Il apporte notamment un jeton d’identité et le paramètre « nonce » pour aider à rejeter la relecture d’une réponse d’authentification qui ne correspond pas à la demande en cours."),
    figure({
      kind: "steps",
      title: "Flux code d’autorisation avec PKCE",
      numbered: true,
      items: [
        { title: "1. Préparation", text: "Le client prépare un `code_verifier` aléatoire.", icon: "key", tone: "cyan" },
        { title: "2. Dérivation", text: "Il en dérive un `code_challenge`.", icon: "hash", tone: "blue" },
        { title: "3. Redirection", text: "Il envoie l’utilisateur vers le serveur d’autorisation.", icon: "share", tone: "violet" },
        { title: "4. Retour", text: "Le serveur renvoie un code d’autorisation.", icon: "log-in", tone: "green" },
        { title: "5. Échange", text: "Le client échange ce code avec le `code_verifier`.", icon: "refresh", tone: "amber" },
        { title: "6. Vérification", text: "Le serveur compare puis remet les jetons.", icon: "shield-check", tone: "green" },
      ],
      caption: "Vérifications : `state`, `redirect_uri` exacte, portées minimales et PKCE.",
    }),
    text("Le flux recommandé ici est le code d’autorisation avec PKCE. Aujourd’hui, tu l’appliques à tous les clients, pas seulement aux clients publics : le client crée un « code_verifier » aléatoire, puis en dérive un « code_challenge », souvent avec la méthode « S256 ». Plus tard, il doit prouver qu’il connaît encore le « code_verifier ». Le paramètre « state » protège contre des confusions de réponse et des scénarios de type CSRF du flux. L’URI de redirection doit correspondre exactement à ce qui est enregistré. Une redirection trop large ou partiellement contrôlée ruine le cadre."),
    text("Les pièges classiques sont connus : redirection ouverte, « state » absent, portées trop larges, jeton mis dans l’URL quand il ne le faut pas, ou confusion entre OAuth et « login rapide ». Le flux implicite et le mot de passe du propriétaire de ressource ne sont plus les choix à enseigner ici. En OIDC, tu vérifies aussi le jeton d’identité, le « nonce » et les informations de profil réellement nécessaires. Enfin, déléguer ne veut pas dire tout recevoir : les portées demandées doivent rester minimales, et un service ne devrait pas demander des droits qu’il n’utilise pas réellement."),
    text("Démonstration guidée : ce script Node.js génère un « code_verifier » et son « code_challenge » en « S256 », selon le principe de PKCE. Avant de le rejouer, vérifie ta version avec « node --version ». Si Node.js est trop ancien pour cette syntaxe JavaScript, mets-le à jour vers une version LTS récente. Le résultat est en base64url sans rembourrage. C’est ce couple qui lie la phase d’autorisation à l’échange du code."),
    code([
      "const crypto = require(\"crypto\");",
      "const base64url = (buffer) => buffer.toString(\"base64\").replace(/=/g, \"\").replace(/\\+/g, \"-\").replace(/\\//g, \"_\");",
      "const codeVerifier = base64url(crypto.randomBytes(32));",
      "const codeChallenge = base64url(crypto.createHash(\"sha256\").update(codeVerifier).digest());",
      "",
      "console.log(JSON.stringify({ codeVerifier, codeChallenge, method: \"S256\" }, null, 2));",
      "// exemple de sortie (valeurs fictives)",
      "// {",
      "//   \"codeVerifier\": \"9EnA0r2Yv7Vh2LQb1mBq7s4M0uXwyuXIE6ALl94m7VQ\",",
      "//   \"codeChallenge\": \"XwPip7gG8Q7xLO_5V12m6H4mM-7qJfU5aK3C7Xv6I_A\",",
      "//   \"method\": \"S256\"",
      "// }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si un client redirige vers un domaine trop large ou oublie « state », un tiers peut tenter d’injecter une réponse non attendue ou d’abuser d’une redirection ouverte. Si, en plus, les portées demandées dépassent le besoin réel, le problème n’est plus seulement l’authentification : c’est une délégation trop généreuse. La bonne lecture reste donc : rôle de chaque acteur, portées minimales, PKCE, « state », et URI de redirection exacte."),
    mistakes("dire « OAuth fait le login » sans préciser qu’il s’agit d’abord d’autorisation déléguée ; oublier « state » ou PKCE ; enregistrer des URI de redirection trop souples ; demander toutes les portées disponibles « au cas où » ; confondre jeton d’identité OIDC et jeton d’accès."),
    safety("tu n’expérimentes ce flux que sur un bac à sable ou une application à toi. Les jetons, codes et URI de redirection réels sont sensibles. Ne les colle pas dans un service tiers, ne les publie pas dans un rapport partagé, et respecte les conditions du fournisseur d’identité utilisé."),
    takeaway("OAuth 2.0 sert à déléguer sans partager le mot de passe du fournisseur. OIDC ajoute une couche d’identité. Le flux à retenir ici est le code d’autorisation avec PKCE, « state », URI de redirection exacte et portées minimales. La bonne sécurité vient du protocole bien appliqué, pas seulement d’un bouton « Se connecter avec… »."),
    practice("Travaille dans « TP 4 : sessions, jetons JWT et mots de passe » : distingue les rôles, lis un flux simplifié, contrôle PKCE et les paramètres de sécurité, puis termine par le quiz."),
    reference("rfc6749"),
    reference("rfc7636"),
    reference("rfc9700"),
    reference("oidcCore"),
    reference("nodeCrypto"),
  ],
  quiz: {
    title: "Quiz : OAuth 2.0 et OIDC",
    questions: [
      questions.choice("Quel problème OAuth 2.0 cherche-t-il d’abord à résoudre ?", ["Accéder à une ressource au nom d’un utilisateur sans récupérer son mot de passe du fournisseur", "Remplacer complètement TLS", "Stocker des mots de passe locaux plus facilement", "Supprimer les cookies de session"], 0, "OAuth 2.0 traite d’abord la délégation d’autorisation. L’idée centrale est justement d’éviter que le client demande ou conserve le mot de passe d’un autre service. Les autres réponses concernent d’autres couches de sécurité.", "facile"),
      questions.choice("À quoi sert surtout PKCE dans le flux code d’autorisation ?", ["À chiffrer tous les journaux de l’application", "À lier le code d’autorisation à un secret éphémère connu du client légitime", "À remplacer « state »", "À supprimer le besoin d’une URI de redirection exacte"], 1, "PKCE relie le code d’autorisation à un « code_verifier » que le client doit connaître au moment de l’échange. Le faux ami est de croire que PKCE remplace toutes les autres vérifications : « state » et l’URI de redirection exacte restent nécessaires.", "moyen"),
      questions.choice("Quelle affirmation sur OIDC est la plus juste ?", ["OIDC remplace entièrement OAuth 2.0", "OIDC ajoute une couche d’identité, par exemple un jeton d’identité, au-dessus d’OAuth 2.0", "OIDC interdit tout usage de jeton", "OIDC n’utilise jamais de paramètre « nonce »"], 1, "OIDC complète OAuth 2.0 pour exprimer l’identité et l’authentification. Le piège serait de le présenter comme un protocole sans rapport ou comme un remplacement total, alors qu’il s’appuie justement sur les bases d’OAuth.", "difficile"),
      questions.multi("Quels contrôles restent importants dans un flux sain ? (plusieurs réponses)", ["Une URI de redirection exacte", "Le paramètre « state »", "Des portées minimales", "Accepter n’importe quel domaine de retour appartenant vaguement au même groupe"], [0, 1, 2], "Une URI exacte, « state » et des portées minimales limitent plusieurs abus connus. À l’inverse, accepter un domaine « presque proche » ou une redirection trop large ouvre la porte à des confusions ou à des détournements de flux.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c4:5",
    position: 5,
    title: "XSS et sécurité du navigateur",
    description: "Ce module t’apprend à reconnaître ce que le navigateur exécute ou charge quand une donnée non fiable traverse mal l’application, puis à ajouter des garde-fous réalistes sans les confondre avec le correctif principal. Critères de réussite : distinguer XSS réfléchi, stocké et DOM ; évaluer si une CSP ou un jeu d’en-têtes réduit vraiment le risque ; proposer une correction adaptée au contexte de sortie et aux protections du navigateur.",
    lessons: [xssLesson, cspLesson, headersLesson],
  },
  {
    key: "c4:6",
    position: 6,
    title: "Sessions, jetons et authentification",
    description: "Tu y suis l’identité technique d’un utilisateur ou d’un client web : cookie de session, jeton signé, puis délégation OAuth ou identité OIDC, avec leurs pièges de mise en œuvre les plus classiques. Critères de réussite : lire un « Set-Cookie » ou un JWT sans lui prêter de pouvoirs imaginaires ; expliquer quand régénérer, invalider ou vérifier un jeton ; décrire un flux OAuth 2.0 avec PKCE, « state » et portées minimales.",
    lessons: [sessionsLesson, jwtLesson, oauthLesson],
  },
];
