import {
  code,
  example,
  figure,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const webHttpBasesLesson: NewLesson = {
  key: "web-http-bases",
  title: "HTTP pour la sécurité : requêtes, réponses, méthodes et codes d’état",
  summary: "Lis un échange HTTP comme un développeur prudent : structure de la requête, sens des méthodes, codes d’état utiles et limites de confiance côté client.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("décrire une requête et une réponse HTTP, distinguer méthodes sûres et idempotentes, lire les codes d’état qui comptent pour la sécurité, repérer les en-têtes sensibles, puis expliquer pourquoi le serveur ne fait jamais confiance au client."),
    prerequisites("avoir les bases des parcours Fondamentaux et Réseaux, ou connaître l’idée d’un client qui parle à un serveur."),
    scenario("Ama aide Baobab Tech à comprendre pourquoi une page de connexion refuse parfois des utilisateurs. Dans le journal, elle voit des requêtes, des codes 401, des cookies et des URL qui contiennent trop d’informations. Pour corriger sans casser le site, elle doit relire l’échange HTTP lui-même, pas seulement l’interface du navigateur."),
    videoSlot("Lire un échange HTTP avec l’œil de la sécurité"),
    text("HTTP est le langage de base du web. Un client, par exemple un navigateur ou « curl.exe », envoie une requête. Le serveur répond avec une ligne d’état, des en-têtes et parfois un corps. En sécurité web, ce détail compte car une fuite, une mauvaise méthode ou un code d’état mal choisi changent ce que le navigateur, un intermédiaire ou un journal vont conserver."),
    figure({
      kind: "table",
      title: "Échange HTTP minimal",
      columns: ["Partie", "Valeur"],
      rows: [
        ["Requête", "GET /connexion HTTP/1.1"],
        ["En-tête", "Host: app.example.org"],
        ["En-tête", "Cookie: session=abc123"],
        ["Réponse", "HTTP/1.1 401 Unauthorized"],
        ["En-tête", "Content-Type: text/plain; charset=utf-8"],
        ["En-tête", "Set-Cookie: session=abc123; Path=/; HttpOnly; SameSite=Lax"],
        ["Corps", "auth required"],
      ],
      mono: [1],
    }),
    text("La méthode exprime l’intention. « GET », « HEAD », « OPTIONS » et « TRACE » sont dites sûres : elles ne devraient pas modifier l’état du serveur. « PUT » et « DELETE » sont idempotentes : si tu rejoues exactement la même requête, l’effet final reste le même. « POST » et « PATCH » ne le sont pas par défaut. Cette règle de conception a un impact défensif immédiat : si un « GET » déclenche une action sensible, tu facilites des erreurs et parfois des CSRF triviaux."),
    code([
      "# Dans PowerShell 5.1 sous Windows, utilise bien curl.exe",
      "curl.exe -i http://127.0.0.1:8080/connexion",
      "# exemple de sortie (valeurs fictives)",
      "# HTTP/1.1 401 Unauthorized",
      "# Content-Type: text/plain; charset=utf-8",
      "# Cache-Control: no-store",
      "# Set-Cookie: session=abc123; Path=/; HttpOnly; SameSite=Lax",
      "# X-From-Demo: cyberpingo",
      "# Date: Sun, 04 Oct 2026 04:02:19 GMT",
      "# Connection: close",
      "# Transfer-Encoding: chunked",
      "#",
      "# auth required",
    ].join("\n"), "bash"),
    text("Démonstration guidée : lance un petit serveur d’essai sur « 127.0.0.1:8080 », puis relis la réponse avec « curl.exe -i ». Tu vois ici un « 401 Unauthorized », qui veut dire en pratique « non authentifié ». Le serveur t’indique aussi qu’il ne faut pas mettre cette réponse en cache avec « Cache-Control: no-store », et renvoie un cookie de session. Cette manipulation marche aussi dans Git Bash, WSL ou Termux avec « curl » tout court."),
    figure({
      kind: "table",
      title: "Codes d’état à retenir",
      columns: ["Code", "Sens"],
      rows: [
        ["301, 308", "redirection durable"],
        ["302, 307", "redirection temporaire"],
        ["401", "il manque une authentification valide"],
        ["403", "tu es identifié, mais l’action reste interdite"],
        ["404", "ressource absente, ou existence non révélée"],
        ["405", "méthode refusée sur cette route"],
        ["429", "trop de requêtes, limitation de débit"],
        ["500, 503", "erreur côté serveur"],
      ],
      mono: [0],
    }),
    text("Les en-têtes les plus utiles côté sécurité sont souvent « Host », « Cookie », « Set-Cookie », « Authorization », « Content-Type », « Location », « Origin » et « Referer ». Le piège central est là : tout ce que le client envoie peut être falsifié. Un script, un proxy, un téléphone modifié ou une requête fabriquée à la main peuvent mentir sur l’adresse d’origine, le navigateur, les champs cachés ou les validations JavaScript. La règle de sécurité vit donc côté serveur."),
    example("Exemple corrigé : dans l’échange ci-dessus, le bon point est le code « 401 » pour une route de connexion et le « no-store » pour éviter de laisser cette réponse dans un cache. Le mauvais point serait d’envoyer un jeton ou un mot de passe dans l’URL, car l’adresse finirait dans l’historique, les journaux et parfois dans « Referer ». Si tu vois « https://app.example.org/reset?token=... », considère cela comme un signal d’alerte à corriger."),
    mistakes("mettre un secret dans une URL ; utiliser « 403 » et « 401 » comme s’ils étaient interchangeables ; faire modifier un état par « GET » ; croire qu’un champ caché ou un contrôle JavaScript suffit comme défense."),
    safety("tes essais se font sur ton serveur local, ta maquette ou un système pour lequel tu as une autorisation écrite. Même une simple requête fabriquée à la main reste hors cadre si elle vise le site d’un tiers. Les journaux HTTP contiennent souvent des données personnelles : ne les publie pas sans nécessité."),
    takeaway("HTTP te montre ce qui est envoyé, reçu et conservé. Les méthodes disent l’intention, les codes d’état disent le résultat, et les en-têtes donnent le contexte. Côté sécurité, ne fais confiance à rien de ce qui vient du client sans vérification serveur."),
    practice("Travaille dans « TP 1 : lire HTTP, cookies et en-têtes de sécurité » : repère les lignes de requête, les codes d’état et les en-têtes qui changent une décision de sécurité, puis termine par le quiz de la leçon."),
    reference("mdnHttp"),
    reference("rfc9110"),
    reference("curlManpage"),
  ],
  quiz: {
    title: "Quiz : HTTP, méthodes et codes d’état",
    questions: [
      questions.choice("Quel élément d’une requête HTTP indique l’intention principale du client ?", ["La méthode, par exemple GET ou POST", "Le code d’état de la réponse", "Le nom du certificat TLS", "Le fuseau horaire du navigateur"], 0, "La méthode exprime l’action demandée au serveur. Le code d’état n’arrive qu’après, dans la réponse. Le certificat TLS appartient à la couche HTTPS, et le fuseau horaire ne dit rien de l’intention de la requête.", "facile"),
      questions.choice("Pourquoi un mot de passe ne doit-il jamais apparaître dans une URL ?", ["Parce qu’une URL ne peut pas contenir de chiffres", "Parce qu’elle peut finir dans l’historique, les journaux et parfois dans « Referer »", "Parce que le navigateur la chiffre toujours deux fois", "Parce qu’un serveur refuse automatiquement toute URL avec un secret"], 1, "Une URL voyage loin : historique local, journaux applicatifs, outils d’analyse, parfois en-tête « Referer ». Le faux ami le plus tentant est de croire que le navigateur ou le serveur bloque cela par défaut, alors qu’ils ne savent pas si ta donnée est sensible.", "moyen"),
      questions.multi("Lis cet extrait : « POST /admin HTTP/1.1 », puis réponse « 403 Forbidden ». Quelles affirmations sont raisonnables ? (plusieurs réponses)", ["La route existe peut-être, mais l’action est interdite dans ce contexte", "Le client a reçu un refus après avoir tenté un POST", "Le serveur garantit que l’utilisateur n’existe pas", "Le code 403 remplace toujours un 401"], [0, 1], "Le « 403 » indique un refus d’autorisation, pas l’inexistence du compte ni une équivalence automatique avec « 401 ». La réponse la plus tentante est d’en déduire trop vite que l’utilisateur n’existe pas, alors que le code parle d’un accès refusé, pas d’une identité absente.", "difficile"),
      questions.tf("La validation JavaScript dans le navigateur améliore le confort, mais elle ne remplace jamais une vérification côté serveur.", true, "Vrai : le client peut être modifié, contourné ou entièrement remplacé. Une validation côté navigateur aide l’utilisateur, mais elle ne constitue pas une décision de sécurité défendable à elle seule.", "moyen"),
    ],
  },
};

const webHttpsLesson: NewLesson = {
  key: "web-https",
  title: "HTTPS : ce que le cadenas protège vraiment",
  summary: "Comprends ce que TLS protège dans une connexion web, ce qu’un certificat prouve vraiment, et pourquoi le cadenas ne garantit ni l’honnêteté du site ni la sécurité de l’application.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("expliquer ce que HTTPS apporte et ce qu’il n’apporte pas, lire les champs essentiels d’un certificat, repérer une erreur de configuration TLS courante, calculer une date d’expiration, puis décider quand HSTS et la redirection vers HTTPS aident vraiment."),
    prerequisites("avoir suivi « HTTP pour la sécurité : requêtes, réponses, méthodes et codes d’état », ou savoir lire une requête et une réponse."),
    scenario("Koffi aide la boutique Soleil après un message d’alerte du navigateur : le site est bien en « https », mais un certificat expire bientôt et une image part encore en HTTP. En réunion, quelqu’un conclut que le cadenas suffit à prouver que le site est sain. Koffi doit corriger deux idées à la fois : HTTPS protège le transport, pas la moralité du site ni toutes les failles de l’application."),
    videoSlot("HTTPS sans mythe : transport protégé, application encore à sécuriser"),
    text("HTTPS signifie HTTP dans TLS. La couche TLS apporte trois choses utiles : la confidentialité contre l’écoute du trajet réseau, l’intégrité contre la modification en route, et l’authentification du serveur grâce au certificat présenté au navigateur. Dans les grandes lignes, le navigateur vérifie le certificat, négocie une version moderne de TLS, en pratique TLS 1.3 ou 1.2, puis établit des clés de session. TLS 1.0 et 1.1 ne sont plus considérés comme acceptables. Cela ne veut pas dire qu’un site honnête, bien codé ou bien géré se cache forcément derrière chaque cadenas. Un faux site peut aussi obtenir un certificat valide pour son propre nom de domaine."),
    figure({
      kind: "compare",
      title: "Ce que le cadenas dit, et ne dit pas",
      sides: [
        {
          title: "Oui",
          tone: "green",
          mark: "check",
          items: [
            "le navigateur parle en TLS avec ce nom de domaine",
            "le trajet réseau est protégé contre l’écoute banale",
            "le certificat présenté est accepté par la chaîne de confiance",
          ],
        },
        {
          title: "Non",
          tone: "red",
          mark: "cross",
          items: [
            "le site est honnête",
            "l’application n’a pas de XSS ni d’injection",
            "l’équipe gère bien ses comptes et ses sauvegardes",
          ],
        },
      ],
    }),
    text("Le certificat X.509 contient plusieurs repères. Le plus utile pour le navigateur est le SAN, « Subject Alternative Name » : c’est la liste des noms que le certificat couvre réellement. Tu regardes aussi l’émetteur, puis la période de validité avec « notBefore » et « notAfter ». Une erreur typique est simple : certificat expiré, nom absent du SAN, chaîne incomplète, ou certificat auto-signé laissé en production."),
    figure({
      kind: "cards",
      title: "Sortie de certificat au format réel, annotée",
      columns: 2,
      items: [
        { term: "Certificate", text: "présence du certificat présenté", tone: "neutral" },
        { term: "Subject", text: "CN=www.boutique-soleil.example", tone: "blue" },
        { term: "X509v3 SAN", text: "DNS:www.boutique-soleil.example, DNS:boutique-soleil.example", tone: "green" },
        { term: "Issuer", text: "C=US, O=Let’s Encrypt, CN=R11", tone: "violet" },
        { term: "Not Before", text: "Mar 17 00:00:00 2026 GMT", tone: "amber" },
        { term: "Not After", text: "Jun 15 00:00:00 2026 GMT", tone: "red" },
      ],
      caption: "Lecture : le SAN couvre le nom, l’émetteur est connu, mais il faut surveiller l’expiration.",
    }),
    code([
      "# Calculer les jours restants avant l’expiration avec Node.js",
      "node -e \"const end=new Date('2026-06-15T00:00:00Z'); const now=new Date('2026-03-10T09:15:00Z'); console.log(Math.round((end-now)/86400000));\"",
      "# exemple de sortie (valeurs fictives)",
      "# 97",
    ].join("\n"), "bash"),
    text("Démonstration guidée : vérifie d’abord ta version avec « node --version ». Ce calcul n’utilise que l’objet « Date », donc n’importe quelle version actuelle et maintenue de Node.js convient. Si « node » n’est pas disponible sur ton poste, mets Node.js à jour puis rejoue l’extrait, ou refais la soustraction dans la console du navigateur. Tu n’as pas besoin d’un vrai domaine ici pour raisonner proprement. Lis un exemple de certificat au format réel, puis calcule la marge avant « notAfter » avec Node.js. Si tu vois 97 jours restants sur un certificat de 90 jours, c’est que tu n’as pas pris la même date de départ : la méthode compte autant que le résultat. Aujourd’hui, Let’s Encrypt propose par défaut des certificats de 90 jours, donc l’automatisation du renouvellement n’est pas un confort facultatif."),
    text("HSTS, avec l’en-tête « Strict-Transport-Security », demande au navigateur de ne plus revenir en HTTP après une première visite en HTTPS. Une valeur classique est « max-age=31536000; includeSubDomains ». La redirection HTTP vers HTTPS et la prévention du contenu mixte complètent ce travail. Mais un HSTS mal préparé peut aussi enfermer des sous-domaines qui ne parlent pas encore HTTPS : on prépare, on teste, puis on étend."),
    example("Exemple corrigé : un site renvoie « 301 » de HTTP vers HTTPS, ajoute « Strict-Transport-Security: max-age=31536000; includeSubDomains », et sert ses scripts, images et feuilles de style en HTTPS. C’est bien pour le transport. En revanche, si la page contient une injection XSS ou un mot de passe réinitialisable par un jeton prévisible, le cadenas ne corrige rien : HTTPS protège le trajet, pas le code applicatif."),
    mistakes("croire qu’un certificat valide prouve l’honnêteté du site ; oublier que le SAN compte plus que le seul « CN » historique ; laisser du contenu mixte ; activer HSTS partout sans vérifier les sous-domaines."),
    safety("teste TLS et les en-têtes seulement sur ton site, ton environnement de démonstration ou un périmètre autorisé par écrit. Un scan TLS plus poussé sur la production d’un tiers ne se lance jamais « pour voir ». Ne publie pas des extraits de certificat interne ou de journal si cela révèle des noms d’hôtes sensibles."),
    takeaway("HTTPS protège le transport entre le client et le serveur grâce à TLS. Le certificat prouve surtout à quel nom de domaine tu parles. Le cadenas aide, mais il ne remplace ni l’examen du domaine, ni la revue du code, ni l’hygiène de sécurité du site."),
    practice("Travaille dans « TP 1 : lire HTTP, cookies et en-têtes de sécurité » pour la partie certificat et en-têtes, puis reviens à « TP 4 : intégrité, chiffrement et certificats » pour relire l’idée de confiance et d’expiration. Termine par le quiz de la leçon."),
    reference("anssiTls"),
    reference("rfc8446"),
    reference("rfc6797"),
    reference("rfc8996"),
    reference("rfc5280"),
    reference("letsEncryptDocs"),
    reference("letsEncryptFaq"),
  ],
  quizExtension: {
    improve: [
      "HTTPS protège avant tout le trajet réseau : confidentialité, intégrité et authentification du serveur. La mauvaise réponse tentante est de croire qu’il garantit aussi l’honnêteté commerciale du site, alors qu’un site frauduleux peut très bien présenter un certificat valide pour son propre nom.",
      "Oui, un site avec un cadenas peut être frauduleux. Le cadenas dit que la connexion est protégée jusqu’au serveur qui possède ce certificat, pas que ce serveur mérite ta confiance ni qu’il ne cherche pas à te tromper.",
    ],
    add: [
      questions.choice("Quel champ d’un certificat aide le navigateur à vérifier que « boutique-soleil.example » fait bien partie des noms couverts ?", ["Le code d’état HTTP", "L’adresse IP du client", "Le SAN, « Subject Alternative Name »", "Le champ « Server » de la réponse"], 2, "Le SAN porte la liste des noms que le certificat couvre réellement. La réponse la plus tentante est le champ « Server », car il contient parfois un nom de produit, mais il ne participe pas à la vérification du nom demandé par le navigateur.", "moyen"),
      questions.multi("Lis cet extrait : « Not After : Jun 15 00:00:00 2026 GMT », puis en-tête « Strict-Transport-Security: max-age=31536000; includeSubDomains ». Quelles affirmations sont correctes ? (plusieurs réponses)", ["Le certificat a une date d’expiration explicite à surveiller", "HSTS demande au navigateur de rester en HTTPS après une première visite réussie en HTTPS", "Le cadenas prouve que l’application n’a pas de faille XSS", "Le site peut ignorer le renouvellement automatique du certificat sans risque"], [0, 1], "L’extrait montre bien une validité finie et un HSTS qui verrouille le retour vers HTTP. Les deux erreurs tentantes sont de croire que TLS corrige les failles applicatives, ou qu’un certificat à durée courte dispense d’automatiser le renouvellement, alors que c’est exactement l’inverse.", "difficile"),
    ],
  },
};

const webNavigateurOrigineLesson: NewLesson = {
  key: "web-navigateur-origine",
  title: "Le navigateur : origine, même origine et ce qu’il protège",
  summary: "Apprends ce que le navigateur isole, comment l’origine se calcule, pourquoi la même origine bloque la lecture et non l’envoi, et où SRI ajoute une vraie défense.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("définir une origine web, comparer même origine et même site, expliquer pourquoi le navigateur bloque surtout la lecture inter-origines, repérer le risque des ressources tierces, puis calculer une empreinte SRI simple."),
    prerequisites("avoir suivi « HTTP pour la sécurité : requêtes, réponses, méthodes et codes d’état » et connaître la différence entre une URL et un nom de domaine."),
    scenario("Fatou ajoute un script tiers sur le site de l’association Teranga. Tout fonctionne, mais un collègue lui demande pourquoi ce script peut lire la page alors qu’un autre site ne peut pas. En même temps, une API distante accepte bien la requête, mais le navigateur refuse de laisser le code lire la réponse. Fatou doit comprendre la frontière de sécurité du navigateur, pas seulement celle du serveur."),
    videoSlot("Origine web, même site et ressources tierces sans confusion"),
    text("Le navigateur ne fait pas qu’afficher du texte. Il rend une page, exécute du JavaScript, gère des cookies, du stockage local, des formulaires, des iframes et des téléchargements. Pour éviter qu’un site lise les secrets d’un autre, il sépare les contenus par origine. Une origine se compose du schéma, de l’hôte et du port. Si l’un des trois change, l’origine change."),
    figure({
      kind: "table",
      title: "Même origine ?",
      columns: ["URL comparée à `https://app.example.org`", "Verdict"],
      rows: [
        ["https://app.example.org/admin", "oui"],
        ["http://app.example.org", "non, schéma différent"],
        ["https://app.example.org:8443", "non, port différent"],
        ["https://api.example.org", "non, hôte différent"],
        ["https://shop.example.org:443", "origine différente si hôte différent"],
      ],
      mono: [0],
    }),
    text("La politique de même origine, souvent appelée SOP, empêche surtout une page de lire la réponse d’une autre origine sans accord explicite. En revanche, le navigateur sait envoyer des requêtes vers d’autres origines : charger une image, soumettre un formulaire, appeler une API. C’est pour cela qu’un CSRF existe : l’envoi est permis plus facilement que la lecture. « Même site » est une notion voisine, utile surtout pour les cookies « SameSite », mais elle n’est pas aussi stricte que l’origine. Une iframe d’une autre origine peut donc s’afficher dans ta page, mais son code ne lit pas librement ton DOM si l’origine diffère."),
    code([
      "# Tester six paires d’URL avec Node.js",
      "node -e \"const pairs=[['https://app.example.org','https://app.example.org/admin'],['https://app.example.org','http://app.example.org'],['https://app.example.org','https://app.example.org:8443'],['https://app.example.org','https://api.example.org'],['https://shop.example.org','https://shop.example.org:443'],['http://intranet.example.org:8080','http://intranet.example.org:8080/outils']]; const same=(a,b)=>{const x=new URL(a),y=new URL(b); const px=x.port||(x.protocol==='https:'?'443':'80'); const py=y.port||(y.protocol==='https:'?'443':'80'); return x.protocol===y.protocol && x.hostname===y.hostname && px===py;}; for (const [a,b] of pairs) console.log(`${a} | ${b} | ${same(a,b)}`);\"",
      "# exemple de sortie (valeurs fictives)",
      "# https://app.example.org | https://app.example.org/admin | true",
      "# https://app.example.org | http://app.example.org | false",
      "# https://app.example.org | https://app.example.org:8443 | false",
      "# https://app.example.org | https://api.example.org | false",
      "# https://shop.example.org | https://shop.example.org:443 | true",
      "# http://intranet.example.org:8080 | http://intranet.example.org:8080/outils | true",
    ].join("\n"), "bash"),
    text("Démonstration guidée : commence par « node --version ». L’objet global « URL » utilisé ici est disponible depuis Node.js 10.0.0. Si ta version est plus ancienne, mets Node.js à jour ou colle le même code dans la console du navigateur. La fonction compare le schéma, l’hôte et le port effectif, y compris les ports implicites 80 et 443. Tu peux la rejouer telle quelle sur Windows avec Node.js, ou dans WSL et Termux. Le résultat illustre le point clé : un chemin différent ne change pas l’origine, mais un autre schéma, un autre hôte ou un autre port la change immédiatement."),
    text("Les ressources tierces demandent une deuxième vigilance. Un script chargé depuis un autre domaine s’exécute avec les droits de la page qui l’inclut. S’il est compromis, il peut agir comme ton application. SRI, « Subresource Integrity », ajoute une empreinte attendue dans la balise afin que le navigateur refuse un fichier modifié. Cela n’autorise pas le script à être moins surveillé : SRI protège l’intégrité du fichier chargé, pas la confiance métier dans le fournisseur. Retiens aussi qu’une partie des API sensibles du navigateur ne fonctionne qu’en contexte sécurisé, donc sur HTTPS, et que les extensions ou logiciels présents sur le poste de l’utilisateur restent hors du contrôle du développeur."),
    code([
      "# Calculer une empreinte SRI en SHA-384 avec Node.js",
      "node -e \"const c=require('crypto'); const src=\\\"console.log('Bonjour CyberPingo');\\\\n\\\"; console.log('sha384-'+c.createHash('sha384').update(src).digest('base64'));\"",
      "# exemple de sortie (valeurs fictives)",
      "# sha384-ID7Mxm5d9IX/roLgTU97ZbmCAra5xPdxbrxWGA8G/2IJ7pOlMLDxLiHiiS4Ucye/",
    ].join("\n"), "bash"),
    text("Pour ce calcul SRI, vérifie aussi « node --version ». « crypto.createHash() » existe depuis les toutes premières versions de Node.js, donc toute version maintenue actuelle convient. Si « node » manque, mets Node.js à jour ou calcule l’empreinte avec l’outil de build de ton projet."),
    example("Exemple corrigé : une page de dons charge « https://cdn.example.org/widget.js ». Sans SRI, si ce fichier change côté CDN, le navigateur l’accepte. Avec l’attribut « integrity », il ne l’exécute que si l’empreinte correspond encore. En revanche, si ce script est légitime mais trop curieux, SRI ne limite pas ce qu’il fera une fois chargé : il faut aussi choisir ses dépendances et leurs permissions avec prudence."),
    mistakes("confondre chemin et origine ; croire que le navigateur bloque tout trafic inter-origines alors qu’il bloque surtout la lecture ; traiter « même site » comme synonyme exact de « même origine » ; intégrer un script tiers sans réfléchir à son pouvoir sur la page."),
    safety("tes essais se font sur des URL d’exemple, ton navigateur et ton code local. N’utilise pas cette compréhension pour contourner les défenses d’un autre site. Si tu analyses des cookies ou du stockage réel, rappelle-toi qu’ils peuvent contenir des données personnelles ou de session."),
    takeaway("L’origine web repose sur trois éléments : schéma, hôte, port. La politique de même origine protège surtout la lecture entre sites. Les ressources tierces vivent dans le contexte de ta page, donc leur intégrité et leur confiance comptent autant que ton propre code."),
    practice("Travaille dans « TP 1 : lire HTTP, cookies et en-têtes de sécurité » : compare des origines, relis les cookies et juge quand un site tiers reçoit trop de pouvoir. Termine ensuite par le quiz de la leçon."),
    reference("mdnSameOrigin"),
    reference("mdnCookies"),
    reference("rfc6454"),
    reference("mdnSri"),
    reference("nodeUrl"),
  ],
  quiz: {
    title: "Quiz : origine et navigateur",
    questions: [
      questions.choice("Qu’est-ce qui compose une origine web ?", ["Le schéma, l’hôte et le port", "Le chemin, le titre HTML et le cookie", "Le fuseau horaire, le port et la langue", "Le certificat, le navigateur et le proxy"], 0, "Une origine web se calcule avec le schéma, l’hôte et le port. Le chemin ou le titre de la page n’en font pas partie. Le piège fréquent est de croire que « /admin » crée une autre origine, alors qu’il ne change que la ressource demandée.", "facile"),
      questions.choice("Pourquoi dit-on que la politique de même origine bloque surtout la lecture ?", ["Parce qu’un navigateur refuse toute requête vers un autre site", "Parce qu’un navigateur peut encore envoyer certaines requêtes inter-origines, mais pas laisser le script lire librement la réponse", "Parce qu’un site tiers ne peut jamais charger d’image", "Parce qu’elle chiffre les cookies côté client"], 1, "Le navigateur permet beaucoup d’envois inter-origines utiles au web, comme les formulaires ou les images. Ce qu’il restreint surtout, c’est l’accès du script à la réponse. C’est justement cette asymétrie qui aide à comprendre le CSRF.", "moyen"),
      questions.multi("Lis ces deux URL : « https://app.example.org » et « https://app.example.org:8443 ». Quelles affirmations sont justes ? (plusieurs réponses)", ["Le port différent suffit à changer l’origine", "Elles restent de même origine car le nom d’hôte est identique", "Le schéma est identique dans les deux cas", "Un script de l’une peut considérer l’autre comme identique par défaut"], [0, 2], "Le schéma est bien le même, mais le port diffère, donc l’origine diffère aussi. La mauvaise réponse la plus tentante est de ne regarder que le nom d’hôte. En sécurité web, le port effectif fait partie intégrante de la frontière d’origine.", "difficile"),
      questions.tf("SRI protège l’intégrité d’un script tiers téléchargé, mais ne transforme pas automatiquement ce fournisseur en acteur de confiance.", true, "Vrai : SRI aide à vérifier que le fichier reçu correspond à l’empreinte attendue. En revanche, si le fournisseur envoie un code légitime mais indiscret, SRI ne change rien à ce que ce script pourra faire dans la page.", "moyen"),
    ],
  },
};

const webComptesLesson: NewLesson = {
  key: "web-comptes",
  title: "Protéger ses comptes avec un gestionnaire et la MFA",
  summary: "Renforce tes comptes web avec des mots de passe uniques, un gestionnaire, une MFA adaptée et une récupération de compte qui ne devient pas le maillon faible.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("choisir l’ordre de sécurisation de tes comptes, expliquer l’intérêt d’un gestionnaire de mots de passe, distinguer TOTP, SMS, passkeys et clés FIDO2, mesurer un ordre de grandeur d’essais possibles, puis protéger correctement les codes de récupération."),
    prerequisites("avoir déjà l’habitude de créer un compte sur le web, même sans connaître le fonctionnement côté serveur."),
    scenario("Awa utilise la même messagerie pour ses réinitialisations, ses achats et ses démarches administratives. Après une fuite sur un vieux service, elle reçoit plusieurs alertes de connexion. Rien n’indique encore une compromission complète, mais l’ordre des priorités est clair : sécuriser d’abord la messagerie, puis éliminer la réutilisation et choisir une MFA qui résiste au phishing."),
    videoSlot("Sécuriser ses comptes web sans s’épuiser"),
    text("Le meilleur mot de passe réutilisé est un mauvais mot de passe. La vraie défense côté utilisateur consiste à avoir un secret long, unique et généré pour chaque service, puis à le stocker dans un gestionnaire. Le gestionnaire réduit la mémoire à une seule phrase de passe maîtresse, à protéger sérieusement et à sauvegarder proprement. Son intérêt n’est pas magique : il t’aide surtout à ne plus recycler « motdepasse », « azerty » ou une petite variante d’un site à l’autre."),
    figure({
      kind: "steps",
      title: "Ordre de sécurisation conseillé",
      numbered: true,
      items: [
        { title: "messagerie principale" },
        { title: "compte Apple, Google ou Microsoft du téléphone ou du PC" },
        { title: "banque, argent mobile, commerce" },
        { title: "réseaux sociaux et messageries" },
        { title: "services moins critiques" },
      ],
    }),
    text("La MFA ajoute une seconde preuve. Une application TOTP vaut mieux qu’aucune MFA, mais les passkeys et les clés FIDO2 résistent mieux au phishing parce qu’elles sont liées au vrai domaine. Un faux site peut te pousser à recopier un code, mais il ne peut pas obtenir la même signature cryptographique qu’un site légitime avec une passkey liée à son origine. Les codes de récupération restent essentiels : ils sauvent l’accès quand tu perds l’appareil principal, mais deviennent eux-mêmes des secrets à ranger hors de cet appareil."),
    code([
      "# Ordre de grandeur hors ligne : 10 000 essais par seconde",
      "node -e \"const rate=10000; const a=Math.pow(26,8); const b=Math.pow(2000,4); const fmt=s=>s<86400?(s/3600).toFixed(2)+' h':s<31536000?(s/86400).toFixed(2)+' jours':(s/31536000).toFixed(2)+' ans'; console.log('8 minuscules:', a, fmt(a/rate)); console.log('4 mots parmi 2000:', b, fmt(b/rate));\"",
      "# exemple de sortie (valeurs fictives)",
      "# 8 minuscules: 208827064576 241.70 jours",
      "# 4 mots parmi 2000: 16000000000000 50.74 ans",
    ].join("\n"), "bash"),
    text("Démonstration guidée : commence par « node --version ». Ce calcul n’utilise que des opérations JavaScript de base, donc toute version maintenue actuelle de Node.js convient. Si « node » est absent, mets Node.js à jour puis rejoue l’extrait. Le script ci-dessus ne décrit pas une attaque en ligne contre un vrai service, car un site sérieux limite les tentatives. Il donne seulement un ordre de grandeur hors ligne sous une hypothèse affichée. Pour la phrase de quatre mots, l’idée n’est valable que si les mots sont tirés au hasard dans ce dictionnaire. Le message pratique est simple : la longueur et l’unicité changent radicalement le coût d’une attaque, surtout quand le service victime d’une fuite stockait mal les secrets."),
    text("Pense aussi aux sessions ouvertes. Beaucoup de services affichent les appareils connectés et permettent de fermer les anciennes sessions. C’est utile après une alerte, un téléphone perdu ou un doute sur un lien cliqué. La partie côté serveur, avec hachage, sessions et réinitialisation sûre, arrive dans les leçons suivantes : ici, tu protèges d’abord l’utilisateur, son coffre et sa récupération de compte."),
    example("Exemple corrigé : Awa commence par sa messagerie principale, active une passkey si le service la propose, garde une application TOTP comme secours si besoin, exporte ou imprime ses codes de récupération et les range séparément du téléphone. Ensuite, elle remplace les mots de passe réutilisés par des secrets uniques issus de son gestionnaire et ferme les sessions anciennes sur les comptes les plus sensibles."),
    mistakes("activer la MFA sans conserver de codes de récupération ; protéger le coffre du gestionnaire avec une phrase courte déjà utilisée ailleurs ; laisser la messagerie principale en dernier ; croire qu’un code SMS suffit toujours contre le phishing."),
    safety("ne partage jamais un code de connexion, un code de récupération ou une capture de ton gestionnaire avec un support non vérifié. Si tu aides quelqu’un d’autre, fais-le sur son appareil avec son accord, sans recopier ses secrets dans tes propres notes ou sur un service tiers."),
    takeaway("Un compte solide combine unicité, longueur, gestionnaire et MFA adaptée. La messagerie principale mérite la priorité absolue. Une passkey ou une clé FIDO2 résiste mieux au phishing qu’un code recopié, mais la récupération reste à protéger avec le même sérieux."),
    practice("Travaille dans « TP 2 : auditer des mots de passe et des comptes » pour vérifier ce qui expose le plus les utilisateurs, puis termine par le quiz de la leçon."),
    reference("cmMotsDePasse"),
    reference("anssiMfa"),
    reference("rfc6238"),
    reference("fidoPasskeys"),
  ],
  quizExtension: {
    improve: [
      "Un mot de passe unique par service évite qu’une fuite chez un prestataire entraîne immédiatement la compromission des autres comptes. La mauvaise idée la plus tentante est de réutiliser le même secret avec une petite variante, car une fuite ou un credential stuffing effacent vite cet avantage apparent.",
      "Les codes de récupération doivent rester dans un endroit sûr distinct de l’appareil principal, justement pour servir quand cet appareil est perdu, volé ou bloqué. Les publier, les envoyer à un inconnu ou les laisser dans le même coffre non protégé annule presque toute leur utilité.",
    ],
    add: [
      questions.choice("Quelle MFA résiste le mieux à un faux site qui essaye de te faire recopier ton second facteur ?", ["Le code reçu par SMS", "Le code TOTP affiché par une application", "Une passkey ou une clé FIDO2 liée au vrai domaine", "Une question secrète mémorisée"], 2, "Une passkey ou une clé FIDO2 vérifie le domaine et signe pour ce site précis, ce qui bloque bien mieux le phishing. Les codes SMS et TOTP restent utiles, mais ils peuvent être recopiés sur un site piégé si l’utilisateur se fait tromper.", "moyen"),
      questions.multi("Lis cet extrait : « 8 minuscules: 208827064576 241.70 jours » et « 4 mots parmi 2000: 16000000000000 50.74 ans ». Quelles conclusions sont raisonnables ? (plusieurs réponses)", ["L’ordre de grandeur dépend de l’hypothèse de vitesse d’essai affichée", "Une phrase plus longue peut coûter bien plus cher à deviner qu’un mot de passe court", "Le script prouve qu’un service réel accepte 10 000 tentatives par seconde", "La longueur et l’unicité restent deux leviers majeurs"], [0, 1, 3], "Le calcul dépend bien d’une hypothèse écrite, ici hors ligne, et ne décrit pas un site réel. En revanche, il illustre correctement le gain de coût apporté par la longueur et la diversité. La réponse la plus tentante est de confondre ordre de grandeur théorique et comportement d’un service bien configuré.", "difficile"),
    ],
  },
};

const webPhishingLesson: NewLesson = {
  key: "web-phishing",
  title: "Déjouer un message de phishing",
  summary: "Repère les demandes suspectes, lis le vrai domaine d’un lien, comprends pourquoi le cadenas ne suffit pas, puis vérifie toute demande sensible par un canal indépendant.",
  minutes: 24,
  xp: 55,
  upgrade: true,
  blocks: [
    goals("repérer les signaux d’un message de phishing, lire le domaine réel d’un lien, distinguer urgence légitime et pression fabriquée, choisir la bonne réaction après un clic, puis résumer en une phrase SPF, DKIM et DMARC."),
    prerequisites("avoir suivi « Protéger ses comptes avec un gestionnaire et la MFA », ou au moins savoir qu’un code de connexion reste un secret."),
    scenario("Moussa reçoit un message au nom de Baobab Tech : facture urgente, lien de connexion, ton pressant et demande de code immédiat. Le logo semble bon et le site affiche un cadenas. En quelques minutes, il doit décider s’il clique, s’il répond, ou s’il passe par un autre canal pour vérifier. Ce réflexe protège autant l’utilisateur que l’organisation."),
    videoSlot("Déjouer un phishing même quand il semble crédible"),
    text("Un message de phishing cherche presque toujours une action : saisir un mot de passe, partager un code, payer, ouvrir une pièce jointe ou installer quelque chose. Il peut arriver par courriel, SMS, appel, message sur un réseau social, fausse page de connexion ou hameçonnage ciblé, par exemple une fraude au président. L’urgence, la peur, l’autorité et le gain facile sont des leviers classiques. Mais le niveau de langue n’est pas une preuve fiable : un message très bien écrit peut être frauduleux, et un vrai message peut contenir une faute. Tu regardes donc la demande, pas seulement la forme."),
    figure({
      kind: "steps",
      title: "Réflexe simple face à un message sensible",
      numbered: true,
      items: [
        { title: "arrêter la réponse immédiate" },
        { title: "lire le vrai domaine du lien" },
        { title: "vérifier la demande par un canal connu" },
        { title: "signaler si l’organisation le prévoit" },
        { title: "si tu as cliqué, changer le mot de passe et prévenir" },
      ],
    }),
    text("Le faux site avec cadenas est un classique. HTTPS protège le trajet jusqu’au faux site, pas son honnêteté. Le domaine reste donc le repère central. « www.baobab-tech.example.attaque.example » n’est pas le domaine de Baobab Tech. De même, une URL avec un nom d’utilisateur avant « @ » peut tromper le regard. Les passkeys et les clés FIDO2 aident ici : elles lient l’authentification au vrai domaine et réduisent le risque de recopier un secret vers un faux site."),
    code([
      "# Extraire le vrai nom d’hôte de six liens avec Node.js",
      "node -e \"const links=['https://connexion.baobab-tech.example/se-connecter','https://baobab-tech.example.security-check.example/connexion','https://support-baobab-tech.example/reset','https://baobab-tech.example@attaque.example/facture','https://www.baobab-tech.example/paiement','https://baobab-tech.examp1e/connexion']; for (const link of links) console.log(new URL(link).hostname);\"",
      "# exemple de sortie (valeurs fictives)",
      "# connexion.baobab-tech.example",
      "# baobab-tech.example.security-check.example",
      "# support-baobab-tech.example",
      "# attaque.example",
      "# www.baobab-tech.example",
      "# baobab-tech.examp1e",
    ].join("\n"), "bash"),
    text("Démonstration guidée : vérifie d’abord « node --version ». L’objet global « URL » utilisé ici est disponible depuis Node.js 10.0.0. Si ta version est plus ancienne, mets Node.js à jour ou colle l’extrait dans la console du navigateur. Copie ensuite les liens suspects dans un petit script Node.js et fais afficher « hostname ». Tu forces ainsi ton regard à lire le domaine réel au lieu de te laisser guider par le texte visible. Dans la liste ci-dessus, « attaque.example » est le vrai nom d’hôte de la quatrième URL, pas « baobab-tech.example ». Cette habitude marche aussi sur Windows avec Node.js, même sans navigateur piloté."),
    text("Côté organisation, trois sigles servent surtout à l’authentification des courriels : SPF déclare quels serveurs peuvent envoyer pour un domaine, DKIM signe le message, et DMARC dit comment traiter les échecs d’alignement et de vérification. Aucun de ces mécanismes ne remplace la vigilance humaine, mais ils réduisent le spoofing simple et améliorent le signalement."),
    example("Exemple corrigé : si tu reçois « votre compte sera suspendu dans 10 minutes », ne réponds pas au message et n’appelle pas le numéro fourni par ce message. Ouvre toi-même l’application ou le site habituel, ou appelle un numéro déjà connu. Si tu as déjà saisi ton mot de passe, change-le immédiatement depuis le vrai site, ferme les sessions actives et signale l’incident selon la procédure prévue."),
    mistakes("juger un message uniquement sur ses fautes ; faire confiance au logo ou au cadenas ; répondre directement au message pour « vérifier » ; oublier de prévenir l’organisation après avoir cliqué."),
    safety("n’ouvre pas une pièce jointe douteuse sur ton poste de travail pour « vérifier ». Si ton organisation a une procédure de signalement, suis-la et conserve le message sans le diffuser inutilement. Un courriel suspect peut contenir des données personnelles : ne l’envoie pas à un service tiers sans nécessité."),
    takeaway("Le phishing te pousse à agir trop vite. Le bon réflexe est de ralentir, lire le vrai domaine, puis vérifier la demande par un canal indépendant. Les mécanismes de courrier et les passkeys aident, mais ils ne remplacent pas une décision prudente."),
    practice("Travaille dans « TP 1 : disséquer un courriel d’hameçonnage » pour relire l’expéditeur, les liens et la demande, puis termine par le quiz de la leçon."),
    reference("cmHameconnage"),
    reference("rfc7208"),
    reference("rfc6376"),
    reference("rfc7489"),
    reference("webauthnGuide"),
    reference("fidoPasskeys"),
    reference("nodeUrl"),
  ],
  quizExtension: {
    improve: [
      "Le canal officiel indépendant casse la mise en scène du fraudeur. Répondre au message ou cliquer sur le lien te laisse dans le décor choisi par l’attaquant, alors qu’un numéro déjà connu, une application ouverte par toi-même ou un collègue identifié donnent une vérification réellement séparée.",
      "Un code de connexion demandé par un inconnu reste un secret, même s’il ne dure que quelques secondes. Le ton poli, l’urgence ou le logo ne changent rien : partager ce code revient souvent à remettre la seconde preuve d’authentification à l’attaquant lui-même.",
    ],
    add: [
      questions.choice("Quel lien mérite le plus de méfiance si tu attends normalement un site « baobab-tech.example » ?", ["https://connexion.baobab-tech.example/se-connecter", "https://support-baobab-tech.example/reset", "https://baobab-tech.example.security-check.example/connexion", "https://www.baobab-tech.example/paiement"], 2, "Le vrai domaine ici se termine par « security-check.example », pas par « baobab-tech.example ». La réponse la plus tentante est le sous-domaine « support-baobab-tech.example », mais il reste bien dans la zone « .example » annoncée et ne cache pas un autre domaine final.", "moyen"),
      questions.multi("Lis ces noms d’hôte : « attaque.example », « www.baobab-tech.example », « baobab-tech.examp1e ». Lesquels doivent t’alerter pour une connexion habituelle à « baobab-tech.example » ? (plusieurs réponses)", ["attaque.example", "www.baobab-tech.example", "baobab-tech.examp1e", "aucun, car il y a un cadenas partout"], [0, 2], "« attaque.example » est clairement un autre domaine, et « examp1e » remplace une lettre par un chiffre pour tromper l’œil. « www.baobab-tech.example » reste cohérent avec le domaine attendu. Le faux ami le plus dangereux est de croire que le cadenas rend ces différences sans importance.", "difficile"),
    ],
  },
};

const webMotsDePasseServeurLesson: NewLesson = {
  key: "web-mots-de-passe-serveur",
  title: "Stocker les mots de passe côté serveur : hachage, sel et politiques",
  summary: "Passe du côté serveur : hachage lent, sel unique, comparaison sûre, politique NIST raisonnable et réinitialisation de mot de passe qui ne crée pas une nouvelle faille.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer mot de passe en clair, chiffrement et hachage, expliquer le rôle du sel et du poivre, comparer Argon2id, scrypt, bcrypt et PBKDF2, vérifier un mot de passe proprement, puis décrire une politique et une réinitialisation conformes aux bonnes pratiques."),
    prerequisites("avoir suivi « Protéger ses comptes avec un gestionnaire et la MFA » et connaître l’idée d’un secret unique côté utilisateur."),
    scenario("Kwame développe une petite application pour la boutique Soleil. Un collègue propose de stocker les mots de passe avec « SHA-256 » parce que c’est simple et déjà disponible. En parallèle, l’équipe veut des règles de mot de passe compliquées et un renouvellement mensuel. Kwame doit défendre une autre approche : stockage lent et robuste côté serveur, puis politique plus réaliste côté utilisateur."),
    videoSlot("Stocker un mot de passe sans stocker le mot de passe"),
    text("Un serveur ne garde jamais un mot de passe en clair. Il stocke une empreinte calculée par une fonction conçue pour cela : lente, coûteuse en mémoire ou en calcul, et différente pour chaque utilisateur grâce à un sel unique. Le hachage n’est pas du chiffrement : le but n’est pas de retrouver le secret, mais de vérifier qu’une nouvelle saisie produit la même empreinte. Une fonction rapide comme SHA-256 seule n’est donc pas adaptée, car elle aide aussi l’attaquant à tenter énormément d’essais."),
    figure({
      kind: "flow",
      title: "Stockage correct, en bref",
      nodes: [
        { label: "mot de passe saisi", icon: "key" },
        { label: "sel unique aléatoire", icon: "file", tone: "blue" },
        { label: "algorithme lent", text: "par exemple Argon2id ou scrypt", icon: "braces", tone: "amber" },
        { label: "empreinte stockée", icon: "database", tone: "green" },
      ],
      caption: "Optionnel : poivre côté serveur, séparé de la base.",
    }),
    text("Aujourd’hui, l’aide-mémoire OWASP recommande Argon2id avec au minimum 19 Mio de mémoire, 2 itérations et un parallélisme de 1. Si Argon2id n’est pas disponible, scrypt est une bonne option ; bcrypt reste acceptable pour l’existant avec un facteur d’au moins 10 et la limite connue de 72 octets ; PBKDF2 avec HMAC-SHA-256 et 600 000 itérations ou plus répond aux contextes FIPS. Le point clé n’est pas le nom seul : c’est le coût effectif pour ralentir une attaque hors ligne."),
    code([
      "# Montrer que le même mot de passe donne deux empreintes différentes avec deux sels",
      "node -e \"const c=require('crypto'); const pwd='motdepasse'; const h1=c.scryptSync(pwd,'salt-demo-1',32).toString('hex'); const h2=c.scryptSync(pwd,'salt-demo-2',32).toString('hex'); const ok=c.timingSafeEqual(Buffer.from(h1,'hex'), c.scryptSync(pwd,'salt-demo-1',32)); const bad=c.timingSafeEqual(Buffer.from(h1,'hex'), c.scryptSync('azerty','salt-demo-1',32)); console.log(h1); console.log(h2); console.log('ok='+ok); console.log('bad='+bad);\"",
      "# exemple de sortie (valeurs fictives)",
      "# 4bd9b5ff181b311cede0488291585302a9d2fe3205904c77d5ca7a01b66fe926",
      "# 88a3bc3a31c51f094436a4157e55f67808362796e43a7fa51f4c98e9f3d06cd3",
      "# ok=true",
      "# bad=false",
    ].join("\n"), "bash"),
    text("Démonstration guidée : commence par « node --version ». « crypto.scryptSync() » est disponible depuis Node.js 10.5.0 et « timingSafeEqual() » depuis Node.js 6.6.0, donc ce script demande au minimum Node.js 10.5.0. Si ta version est plus ancienne, mets Node.js à jour avant de le rejouer. Le script ci-dessus utilise « crypto.scryptSync », disponible sans dépendance supplémentaire, pour montrer deux sels distincts et une vérification en temps constant avec « timingSafeEqual ». Les deux empreintes diffèrent alors que le mot de passe est identique. C’est exactement l’effet recherché : empêcher les comparaisons massives simples et obliger l’attaquant à recalculer pour chaque utilisateur."),
    text("La politique de mots de passe a aussi changé. Les recommandations NIST demandent au minimum 15 caractères quand le mot de passe est le seul facteur, et au minimum 8 caractères quand il fait partie d’une MFA. Elles insistent aussi sur l’acceptation des phrases de passe, des gestionnaires, du collage et du remplissage automatique, puis sur l’abandon des règles de composition arbitraires et du changement périodique imposé sans suspicion de compromission. Côté application, cela se traduit aussi par une vérification contre une liste de mots de passe compromis, des messages d’erreur semblables pour « compte inconnu » et « mot de passe faux », une limitation des tentatives, et une réinitialisation par jeton aléatoire, à usage unique et à courte durée de vie."),
    example("Exemple corrigé : bonne décision, stocker une empreinte Argon2id ou scrypt avec un sel unique, limiter les essais, accepter une phrase longue issue d’un gestionnaire, et réinitialiser par un jeton aléatoire expirant vite. Mauvaise décision, garder un SHA-256 seul, forcer un symbole spécial sans raison claire, exiger un changement mensuel et afficher « ce compte n’existe pas » quand l’adresse n’est pas connue."),
    mistakes("parler de chiffrement alors qu’il s’agit de hachage ; réutiliser le même sel pour tout le monde ; journaliser des mots de passe ou des jetons de réinitialisation ; faire de la rotation forcée un réflexe alors qu’aucun indice de compromission n’existe."),
    safety("teste ces scripts uniquement avec des mots de passe d’exemple et des bases d’essai. N’envoie jamais un vrai mot de passe, une vraie base d’utilisateurs ou un vrai export de journaux à un service tiers. Les données d’authentification restent sensibles même en laboratoire."),
    takeaway("Côté serveur, on vérifie un mot de passe sans le conserver en clair. Le duo gagnant est un algorithme lent et un sel unique par secret. La politique moderne privilégie la longueur, les gestionnaires et la récupération sûre plutôt que des contraintes arbitraires faciles à contourner."),
    practice("Travaille dans « TP 4 : sessions, jetons JWT et mots de passe » pour comparer politiques, empreintes et erreurs de conception, puis termine par le quiz de la leçon."),
    reference("cnilAuthentifier"),
    reference("owaspPasswordStorage"),
    reference("owaspAuthentication"),
    reference("owaspCsForgotPassword"),
    reference("nist80063b4"),
    reference("nodeCrypto"),
  ],
  quiz: {
    title: "Quiz : stockage des mots de passe côté serveur",
    questions: [
      questions.choice("Pourquoi SHA-256 seul ne convient-il pas au stockage des mots de passe ?", ["Parce qu’il ne peut traiter que 8 caractères", "Parce qu’il est trop rapide pour ralentir une attaque hors ligne", "Parce qu’il ajoute déjà un sel automatiquement", "Parce qu’il ne fonctionne pas avec HTTPS"], 1, "SHA-256 est conçu pour aller vite. Cette vitesse aide aussi l’attaquant qui teste beaucoup d’essais hors ligne après une fuite. Le faux ami le plus fréquent est de croire que « cryptographique » suffit, alors qu’un stockage de mots de passe demande en plus un coût délibérément élevé.", "facile"),
      questions.choice("Quel élément doit être unique pour chaque mot de passe stocké ?", ["Le code d’état HTTP", "Le domaine du site", "Le sel", "Le même commentaire dans la base"], 2, "Le sel doit être unique et aléatoire pour empêcher les comparaisons massives et les tables précalculées. Le domaine, le commentaire ou un code HTTP n’ont aucun rôle dans cette défense. Le piège classique est de garder un seul sel commun, ce qui casse une bonne partie du bénéfice.", "moyen"),
      questions.multi("Lis cette sortie : « ok=true » puis « bad=false » après deux appels à « timingSafeEqual ». Quelles affirmations sont correctes ? (plusieurs réponses)", ["La vérification du bon mot de passe a réussi", "La comparaison du mauvais mot de passe a échoué", "Les deux empreintes identiques prouvent que les sels étaient les mêmes", "Le script illustre une vérification explicite plutôt qu’une lecture du mot de passe en clair"], [0, 1, 3], "Le script montre bien une réussite pour le bon secret, un échec pour le mauvais et une vérification sur empreintes calculées. Il ne dit pas que les sels étaient identiques, au contraire : l’exemple précédent montrait justement deux empreintes différentes pour deux sels distincts.", "difficile"),
      questions.tf("Imposer un changement périodique de mot de passe sans suspicion de compromission n’est plus recommandé comme règle générale.", true, "Vrai : les recommandations récentes privilégient la longueur, les gestionnaires et la détection de secrets compromis plutôt que des rotations arbitraires. Forcer un changement sans raison pousse souvent vers des variantes prévisibles et moins utiles qu’on ne le croit.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c4:1",
    position: 1,
    existing: { fromTitle: "Naviguer en sécurité" },
    title: "Le web, HTTP et HTTPS",
    description: "Ce module pose les bases techniques du web côté sécurité : ce qui circule dans HTTP, ce que TLS protège vraiment, et ce que le navigateur isole entre deux origines. Critères de réussite : lire une requête, une réponse et leurs en-têtes ; expliquer ce que le cadenas garantit, et ce qu’il ne garantit pas ; comparer deux URL pour juger leur origine et les risques associés aux ressources tierces.",
    lessons: [webHttpBasesLesson, webHttpsLesson, webNavigateurOrigineLesson],
  },
  {
    key: "c4:2",
    position: 2,
    existing: { fromTitle: "Protéger ses comptes" },
    title: "Comptes, mots de passe et phishing",
    description: "Tu y renforces les comptes web du point de vue utilisateur puis serveur : hygiène des secrets, MFA adaptée, lecture prudente des messages et stockage robuste des mots de passe. Critères de réussite : prioriser la sécurisation des comptes critiques ; reconnaître un domaine ou une demande de phishing qui trompe l’œil ; décrire un stockage serveur défendable avec hachage lent, sel unique et récupération sûre.",
    lessons: [webComptesLesson, webPhishingLesson, webMotsDePasseServeurLesson],
  },
];
