import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const webConfigSecretsLesson: NewLesson = {
  key: "web-config-secrets",
  title: "Configuration, secrets et erreurs : durcir sans rien laisser traîner",
  summary: "Apprends à reconnaître une mauvaise configuration, à protéger les secrets hors du code, et à faire échouer une application sans divulguer d’informations utiles à un attaquant.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("repérer les erreurs de configuration les plus fréquentes, séparer un secret du code, distinguer journal serveur et message client, organiser la rotation d’un secret, et vérifier qu’une application échoue fermée plutôt qu’ouverte."),
    prerequisites("avoir compris le fonctionnement général de HTTP, des en-têtes et du contrôle d’accès."),
    scenario("Kwame reprend une petite application de réservation pour la boutique Soleil. L’équipe a laissé un fichier « .env » dans une archive, une page d’erreur montre la trace complète, et le mode débogage est resté actif en préproduction. Kwame doit durcir l’ensemble sans casser le service ni publier par erreur des secrets dans le dépôt."),
    videoSlot("Durcir une application web sans exposer ses secrets ni ses erreurs"),
    text("L’OWASP Top 10:2025 place la mauvaise configuration de sécurité en A02. En pratique, cela recouvre moins une seule faille qu’une famille d’oublis : mot de passe par défaut, liste de répertoires ouverte, port d’administration accessible depuis Internet, stockage public, méthodes HTTP inutiles, CORS trop large, traces d’erreur complètes, mode débogage actif, fichier « .git » ou « .env » laissé dans la racine publiée. Le point commun est simple : l’application en dit trop, accepte trop, ou expose un composant qui n’aurait pas dû l’être."),
    schema([
      "Liste de contrôle de durcissement",
      "",
      "configuration : pas de valeur par défaut, pas de mode debug en production",
      "publication   : pas de « .env », « .bak », « .git », « phpinfo » ni archive oubliée",
      "réseau        : ports d’administration fermés ou restreints",
      "application   : erreurs sobres côté client, détails côté journal serveur",
      "secrets       : hors code et hors dépôt, rotation prévue, accès minimal",
      "environnements: dev, test et production séparés",
    ].join("\n")),
    text("Un secret n’est pas seulement un mot de passe. C’est aussi une clé API, un secret de session, un jeton d’accès, un mot de passe SMTP, un identifiant de base de données ou une clé privée. Il ne vit ni dans le code, ni dans le dépôt Git, ni dans une image copiée partout. Il vit dans une variable d’environnement, un coffre-fort, ou un mécanisme équivalent contrôlé. Si un secret fuit, la bonne réaction n’est pas « on le cachera mieux la prochaine fois ». Il faut considérer ce secret comme compromis, le remplacer, révoquer l’ancien, relire les journaux, et vérifier quelles fonctions dépendaient de lui."),
    text("Démonstration guidée : le script ci-dessous crée un petit dossier d’essai, y dépose quelques fichiers dangereux, puis cherche deux familles de problèmes. La première : des noms qui n’ont rien à faire dans un dossier publié, comme « .env » ou « sauvegarde.bak ». La seconde : des motifs de secrets fictifs commençant par « CLE_EXEMPLE_ ». L’objectif n’est pas de remplacer un outil spécialisé, mais d’apprendre à regarder avant de livrer."),
    text("Prérequis de démonstration : ouvre un terminal et vérifie d’abord ta version avec « node --version ». Cet extrait n’utilise que des modules cœur stables de Node.js et « console.table ». Si la commande échoue ou si l’extrait ne se lance pas, mets Node.js à jour avant de continuer."),
    code([
      "const fs = require(\"node:fs\");",
      "const os = require(\"node:os\");",
      "const path = require(\"node:path\");",
      "",
      "const racine = fs.mkdtempSync(path.join(os.tmpdir(), \"swb-config-\"));",
      "fs.mkdirSync(path.join(racine, \"public\"));",
      "fs.mkdirSync(path.join(racine, \"archives\"));",
      "fs.writeFileSync(path.join(racine, \"public\", \".env\"), \"SESSION_SECRET=CLE_EXEMPLE_ABC123\\n\", \"utf8\");",
      "fs.writeFileSync(path.join(racine, \"public\", \"app.js\"), \"console.log('ok');\\n\", \"utf8\");",
      "fs.writeFileSync(path.join(racine, \"archives\", \"sauvegarde.bak\"), \"ancienne configuration\\n\", \"utf8\");",
      "fs.writeFileSync(path.join(racine, \"README.txt\"), \"aucun secret ici\\n\", \"utf8\");",
      "",
      "const motifsFichiers = [/^\\.env$/i, /\\.bak$/i, /^\\.git$/i];",
      "const motifSecret = /CLE_EXEMPLE_[A-Z0-9_]+/g;",
      "const trouvailles = [];",
      "",
      "function parcourir(dossier) {",
      "  for (const nom of fs.readdirSync(dossier)) {",
      "    const complet = path.join(dossier, nom);",
      "    const stat = fs.statSync(complet);",
      "    if (stat.isDirectory()) {",
      "      parcourir(complet);",
      "      continue;",
      "    }",
      "    if (motifsFichiers.some((re) => re.test(nom))) {",
      "      trouvailles.push({ type: \"fichier\", chemin: path.relative(racine, complet) });",
      "    }",
      "    const contenu = fs.readFileSync(complet, \"utf8\");",
      "    if (motifSecret.test(contenu)) {",
      "      trouvailles.push({ type: \"secret\", chemin: path.relative(racine, complet) });",
      "      motifSecret.lastIndex = 0;",
      "    }",
      "  }",
      "}",
      "",
      "parcourir(racine);",
      "console.table(trouvailles);",
      "# exemple de sortie (valeurs fictives)",
      "# ┌─────────┬───────────┬──────────────────────────┐",
      "# │ (index) │ type      │ chemin                   │",
      "# ├─────────┼───────────┼──────────────────────────┤",
      "# │ 0       │ 'fichier' │ 'archives\\\\sauvegarde.bak' │",
      "# │ 1       │ 'fichier' │ 'public\\\\.env'            │",
      "# │ 2       │ 'secret'  │ 'public\\\\.env'            │",
      "# └─────────┴───────────┴──────────────────────────┘",
    ].join("\n"), "javascript"),
    schema([
      "Après une fuite de secret",
      "",
      "1. confirmer le secret concerné et le système touché",
      "2. révoquer ou remplacer le secret, puis redémarrer proprement si nécessaire",
      "3. relire les journaux utiles pour voir s’il a été utilisé",
      "4. corriger la cause : dépôt, archive, image, variable partagée, capture ou ticket",
    ].join("\n")),
    text("La gestion des erreurs mérite la même discipline. Côté client, tu renvoies un message compréhensible mais sobre : « opération impossible pour le moment » ou « accès refusé ». Côté serveur, tu conserves la trace détaillée avec l’identifiant de corrélation, le chemin, le code HTTP, le compte concerné et la pile technique si elle est utile. L’OWASP Top 10:2025 ajoute d’ailleurs la mauvaise gestion des conditions exceptionnelles en A10 : un test d’erreur mal géré peut transformer une panne en exposition d’information, ou une vérification ratée en accès accordé par défaut. Une défense sérieuse échoue donc fermée, pas ouverte."),
    example("Exemple corrigé : mauvaise réponse côté client, « stack trace: TypeError in paiement.js ligne 143, mot de passe DB=motdepasse ». Bonne réponse, « paiement indisponible, réessaie plus tard » avec un code de suivi. Côté serveur, le journal garde l’heure, le compte, la route, l’identifiant de corrélation et la trace technique complète. Si la clé de session a fuité dans un ancien export, on la remplace immédiatement, on invalide les sessions qui en dépendent et on vérifie les accès réalisés depuis la fuite."),
    mistakes("laisser un mode débogage actif en production ; croire qu’un fichier « .env » hors du code est automatiquement protégé ; réutiliser le même secret dans plusieurs environnements ; renvoyer la pile d’erreur complète au navigateur ; corriger le symptôme sans révoquer le secret compromis."),
    safety("analyse et corrige uniquement ta propre application ou un environnement pour lequel tu as une autorisation écrite. Les journaux et exports peuvent contenir des données personnelles et des secrets : ne les publie pas, ne les colle pas dans un service tiers, et utilise des valeurs fictives pour tes démonstrations."),
    takeaway("une mauvaise configuration expose souvent plus d’informations qu’une faille de code isolée. Les secrets vivent hors du dépôt, se remplacent quand ils fuient, et les erreurs détaillées restent côté serveur. En production, une défense robuste échoue fermée et sépare clairement dev, test et production."),
    practice("Travaille dans « TP 6 : configuration, dépendances et notation CVSS » : repère les fichiers oubliés, les erreurs trop bavardes et les secrets mal placés, puis propose une correction vérifiable avant de finir par le quiz."),
    reference("owaspTop10A02"),
    reference("owaspTop10A10"),
    reference("owaspCsSecrets"),
    reference("owaspCsErrors"),
    reference("cnilGuideSecurite"),
    reference("nodeFs"),
  ],
  quiz: {
    title: "Quiz : configuration, secrets et erreurs",
    questions: [
      questions.choice("Quel élément relève le plus directement d’une mauvaise configuration au sens de l’OWASP Top 10:2025 A02 ?", ["Un fichier « .env » publié avec l’application", "Une phrase de passe stockée dans un gestionnaire", "Un bouton masqué par CSS", "Un mot de passe long et unique"], 0, "Publier « .env » expose directement des secrets ou des paramètres sensibles. Les autres réponses ne décrivent pas une mauvaise configuration de sécurité comparable. Le faux ami est le bouton masqué : il peut gêner l’interface, mais pas au même niveau qu’un secret exposé.", "facile"),
      questions.choice("Tu découvres qu’une clé API a été copiée dans une archive accessible. Quelle action vient en premier ?", ["La laisser en place et changer seulement le nom du fichier", "La considérer comme compromise et la remplacer", "Supprimer le journal qui l’a révélée", "Attendre le prochain sprint"], 1, "Une clé exposée doit être considérée comme compromise. La réaction défensive correcte est la révocation ou la rotation, puis la recherche des usages éventuels. Renommer un fichier ou attendre laisse le risque actif.", "moyen"),
      questions.multi("Lis cette situation : « la page d’erreur affiche la pile complète, le chemin du serveur et le nom de la table SQL ». Quelles réponses sont justes ? (plusieurs réponses)", ["Le client reçoit trop d’informations techniques", "Le détail complet doit rester dans le journal serveur, pas dans la réponse publique", "Cette réponse prouve forcément une injection réussie", "Un message sobre côté navigateur est préférable"], [0, 1, 3], "L’exposition d’une pile technique aide un attaquant à cartographier l’application, même si l’erreur vient d’autre chose qu’une attaque. Elle n’établit pas, à elle seule, une injection réussie. En revanche, le détail doit rester côté serveur et le message public doit rester sobre.", "difficile"),
      questions.tf("Un secret stocké dans une variable d’environnement n’a plus besoin d’être renouvelé s’il fuit dans un ticket ou une capture d’écran.", false, "Faux : l’emplacement correct d’un secret ne change rien au fait qu’une fuite le rend compromis. S’il apparaît dans un ticket, une capture ou un export, il faut le remplacer et vérifier où il a pu être utilisé.", "moyen"),
    ],
  },
};

const webDependancesLesson: NewLesson = {
  key: "web-dependances",
  title: "Dépendances et chaîne d’approvisionnement : analyse, verrouillage et mises à jour",
  summary: "Comprends pourquoi ton application embarque surtout du code tiers, comment verrouiller les versions, lire un avis de sécurité et prioriser une mise à jour sans casser la production.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("lire un avis de sécurité de dépendance, expliquer l’intérêt d’un fichier de verrouillage, distinguer « npm install » et « npm ci », repérer un risque de typosquatting, et classer des mises à jour selon leur exposition réelle."),
    prerequisites("avoir déjà vu ce qu’est une application web côté serveur et compris la notion de correctif."),
    scenario("Awa hérite d’un petit service Node.js de Baobab Tech. Le dépôt contient cinquante dépendances directes et beaucoup plus de dépendances transitives. Une alerte parle d’une bibliothèque vulnérable, une autre d’un paquet au nom presque identique à un paquet connu. Awa doit décider quoi corriger d’abord et comment rendre les installations plus prévisibles."),
    videoSlot("Lire une alerte de dépendance et verrouiller sa chaîne d’approvisionnement"),
    text("Une application moderne exécute rarement seulement ton code. Elle exécute aussi le code des dépendances directes et transitives, leurs scripts d’installation, parfois leurs outils de construction, et les dépendances de ces dépendances. L’OWASP Top 10:2025 place ce sujet en A03, défaillances de la chaîne d’approvisionnement logicielle. Le risque ne vient pas seulement d’un CVE connu. Il vient aussi d’un paquet mal nommé, d’un mainteneur compromis, d’un script post-installation trop permissif, ou d’une installation impossible à rejouer exactement."),
    schema([
      "Ce qu’il faut suivre",
      "",
      "package.json      : ce que tu demandes",
      "package-lock.json : ce qui sera réellement installé",
      "npm ci            : installation propre depuis le verrouillage",
      "SBOM              : inventaire des composants livrés",
      "avis de sécurité  : versions touchées, corrigées, gravité, contexte",
    ].join("\n")),
    text("Le verrouillage des versions est une défense simple et souvent sous-estimée. Sans fichier de verrouillage, deux installations du même projet peuvent récupérer des versions différentes à quelques jours d’écart. Avec « npm ci », tu demandes une installation reproductible à partir de « package-lock.json », utile en intégration continue et en production. Cela ne supprime pas les vulnérabilités, mais cela supprime une partie du hasard. L’inventaire logiciel, souvent sous la forme d’une SBOM CycloneDX ou SPDX, sert ensuite à savoir ce que tu livres réellement et à retrouver vite où se cache un composant touché."),
    text("Les incidents réels rappellent que le risque n’est pas théorique. Log4Shell, CVE-2021-44228, révélé en décembre 2021, a montré l’impact massif d’une bibliothèque de journalisation très répandue. La porte dérobée dans xz/liblzma, CVE-2024-3094, révélée en mars 2024, a rappelé qu’un composant profond de la chaîne peut contaminer d’autres logiciels qui l’embarquent. L’affaire « event-stream » en 2018 a illustré un autre mécanisme : reprise de maintenance, ajout d’une dépendance malveillante « flatmap-stream », puis ciblage d’un portefeuille précis. Tu n’as pas besoin de retenir chaque date pour agir, mais tu dois retenir la leçon commune : connaître, verrouiller, vérifier et mettre à jour."),
    text("Démonstration guidée : le script ci-dessous compare une petite liste de dépendances inventées à des avis inventés. Chaque avis indique une version corrigée minimale. Le script repère les paquets vulnérables, puis montre aussi ce qu’acceptent deux intervalles SemVer usuels. Ici, « ^1.2.3 » accepte les mises à jour mineures et correctives compatibles de la branche majeure 1, alors que « ~1.2.3 » reste dans la branche « 1.2.x »."),
    text("Prérequis de démonstration : vérifie d’abord « node --version ». Cet extrait n’utilise que JavaScript de base et « console.table ». Si Node.js manque ou si la commande échoue, mets Node.js à jour avant de continuer."),
    code([
      "function parse(version) {",
      "  return version.split(\".\").map((v) => Number(v));",
      "}",
      "",
      "function compare(a, b) {",
      "  const va = parse(a);",
      "  const vb = parse(b);",
      "  for (let i = 0; i < 3; i += 1) {",
      "    if (va[i] !== vb[i]) return va[i] - vb[i];",
      "  }",
      "  return 0;",
      "}",
      "",
      "function semverRange(range, candidate) {",
      "  const base = range.slice(1);",
      "  const [maj, min, patch] = parse(base);",
      "  const [cMaj, cMin, cPatch] = parse(candidate);",
      "  if (range.startsWith(\"^\")) {",
      "    return cMaj === maj && compare(candidate, base) >= 0;",
      "  }",
      "  if (range.startsWith(\"~\")) {",
      "    return cMaj === maj && cMin === min && compare(candidate, base) >= 0;",
      "  }",
      "  return candidate === range;",
      "}",
      "",
      "const dependances = [",
      "  { nom: \"lib-http\", version: \"1.4.2\" },",
      "  { nom: \"flatmap-stream\", version: \"0.1.0\" },",
      "  { nom: \"templater\", version: \"2.0.3\" },",
      "];",
      "const avis = [",
      "  { nom: \"lib-http\", corrigeA: \"1.4.4\" },",
      "  { nom: \"templater\", corrigeA: \"2.1.0\" },",
      "];",
      "",
      "const vulnerables = dependances.filter((dep) => {",
      "  const alerte = avis.find((item) => item.nom === dep.nom);",
      "  return alerte && compare(dep.version, alerte.corrigeA) < 0;",
      "});",
      "",
      "console.table(vulnerables);",
      "console.log(\"^1.2.3 accepte 1.5.0 :\", semverRange(\"^1.2.3\", \"1.5.0\"));",
      "console.log(\"^1.2.3 accepte 2.0.0 :\", semverRange(\"^1.2.3\", \"2.0.0\"));",
      "console.log(\"~1.2.3 accepte 1.2.9 :\", semverRange(\"~1.2.3\", \"1.2.9\"));",
      "console.log(\"~1.2.3 accepte 1.3.0 :\", semverRange(\"~1.2.3\", \"1.3.0\"));",
      "# exemple de sortie (valeurs fictives)",
      "# ┌─────────┬─────────────┬─────────┐",
      "# │ (index) │ nom         │ version │",
      "# ├─────────┼─────────────┼─────────┤",
      "# │ 0       │ 'lib-http'  │ '1.4.2' │",
      "# │ 1       │ 'templater' │ '2.0.3' │",
      "# └─────────┴─────────────┴─────────┘",
      "# ^1.2.3 accepte 1.5.0 : true",
      "# ^1.2.3 accepte 2.0.0 : false",
      "# ~1.2.3 accepte 1.2.9 : true",
      "# ~1.2.3 accepte 1.3.0 : false",
    ].join("\n"), "javascript"),
    schema([
      "Pour lire un avis de dépendance",
      "",
      "1. quels paquets et quelles versions sont touchés ?",
      "2. quelle version corrige ?",
      "3. la dépendance est-elle dans le code livré ou seulement dans l’outillage ?",
      "4. le composant vulnérable est-il réellement atteignable ?",
      "5. quelle stratégie : mise à jour, retrait, contournement temporaire, surveillance ?",
    ].join("\n")),
    text("Une mise à jour ne se priorise pas seulement avec une gravité. Tu regardes aussi si la dépendance tourne en production, si la fonctionnalité vulnérable est atteignable, si un contournement crédible existe, et si la correction casse l’application. Un paquet de développement vulnérable dans une chaîne de construction ne s’ignore pas, mais il ne se traite pas forcément avant une bibliothèque exposée sur le chemin d’authentification en production. Le même raisonnement vaut pour le typosquatting : un nom presque bon peut coûter très cher s’il entre dans ton dépôt ou dans ton pipeline."),
    example("Exemple corrigé : « lib-http » tourne dans le service public d’authentification et sa version « 1.4.2 » reste sous la version corrigée « 1.4.4 ». « templater » est vulnérable lui aussi, mais n’est utilisé que pour générer un export interne lancé à la demande. La priorité va d’abord à « lib-http ». En parallèle, on garde un verrouillage propre, on exécute « npm ci » dans l’intégration continue, et on génère une SBOM pour savoir rapidement si la même bibliothèque se cache ailleurs."),
    mistakes("installer en production sans fichier de verrouillage ; croire qu’une seule gravité suffit à décider ; négliger les dépendances transitives ; ajouter un paquet au nom presque familier sans vérifier son origine ; mettre à jour en urgence sans test minimal ni plan de retour arrière."),
    safety("tu analyses tes propres dépendances ou celles d’un projet pour lequel tu as l’autorisation d’agir. Ne téléverse ni archive privée, ni code source sensible vers un service tiers sans nécessité. Quand tu partages un exemple pédagogique, garde des noms de paquets ou d’applications fictifs si le contexte réel est confidentiel."),
    takeaway("la chaîne d’approvisionnement se défend par l’inventaire, le verrouillage, la veille et la mise à jour testée. Un avis utile se lit avec son contexte réel d’exposition. Un paquet non verrouillé ou mal identifié peut devenir une faille aussi sérieuse qu’un bug dans ton propre code."),
    practice("Travaille dans « TP 6 : configuration, dépendances et notation CVSS » : lis des avis fictifs, retrouve les versions touchées, classe les correctifs par exposition réelle, puis termine par le quiz."),
    reference("owaspTop10A03"),
    reference("owaspCsDependencies"),
    reference("owaspCsSupplyChain"),
    reference("owaspCsNpm"),
    reference("githubAdvisories"),
    reference("cyclonedx"),
    reference("npmCi"),
    reference("npmSemver"),
    reference("npmEventStream"),
    reference("nvdLog4shell"),
    reference("nvdXzBackdoor"),
    reference("spdx"),
  ],
  quiz: {
    title: "Quiz : dépendances et chaîne d’approvisionnement",
    questions: [
      questions.choice("Quel fichier décrit le plus directement l’installation exacte qu’un pipeline Node.js doit rejouer ?", ["package-lock.json", "README.md", "LICENSE", ".editorconfig"], 0, "Dans un projet npm, « package-lock.json » fixe les versions résolues et aide à rejouer la même installation. Le faux ami tentant est « package.json », qui décrit l’intention et les intervalles, pas toujours l’arbre exact obtenu.", "facile"),
      questions.choice("Pourquoi « npm ci » est-il utile en intégration continue ?", ["Il ignore le fichier de verrouillage pour aller plus vite", "Il cherche automatiquement les CVE dans tout Internet", "Il vise une installation propre et reproductible depuis le verrouillage", "Il remplace tous les paquets par des versions majeures récentes"], 2, "L’intérêt principal de « npm ci » est la reproductibilité à partir du verrouillage. Il ne remplace ni la veille ni les tests, et il ne monte pas seul toutes les versions. L’erreur la plus courante est de lui prêter un rôle de scanner ou d’outil magique de mise à jour.", "moyen"),
      questions.multi("Lis cette situation : « une bibliothèque publique vulnérable est utilisée sur la route de connexion, une autre ne sert qu’à générer une documentation interne ». Quelles affirmations sont prudentes ? (plusieurs réponses)", ["La dépendance exposée sur la connexion mérite souvent la priorité", "La dépendance interne peut être ignorée définitivement", "La gravité seule ne suffit pas à classer les corrections", "Le contexte d’atteignabilité compte"], [0, 2, 3], "Une dépendance réellement exposée en production passe souvent avant un outil interne moins atteignable. Cela ne veut pas dire que l’autre peut être oubliée. La gravité, l’exposition et l’atteignabilité doivent être lues ensemble pour décider proprement.", "difficile"),
      questions.tf("Un nom de paquet presque identique à un paquet connu peut être le signe d’un typosquatting.", true, "Vrai : les attaques par typosquatting profitent d’une faute de frappe ou d’une lecture trop rapide pour faire installer le mauvais paquet. C’est précisément pourquoi il faut vérifier l’origine, le nom exact et la réputation minimale du composant avant de l’ajouter.", "moyen"),
    ],
  },
};

const webDevSecuriseLesson: NewLesson = {
  key: "web-dev-securise",
  title: "Développer sans reproduire les failles : revue de code, tests de sécurité et intégration continue",
  summary: "Intègre la sécurité au cycle de développement : exigences, revue de code, détection de secrets, tests automatisés et pipeline qui bloque avant la production.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("relier une exigence ASVS à un contrôle concret, préparer une petite revue de code sécurité, distinguer SAST, DAST et SCA, détecter un secret avant le commit, et expliquer le rôle d’un « security.txt » dans une divulgation coordonnée."),
    prerequisites("avoir déjà vu les principales familles de failles web, notamment injection, XSS, contrôle d’accès et secrets."),
    scenario("Moussa travaille sur une nouvelle API de dons pour l’association Teranga. Le code fonctionne, mais la première revue révèle une concaténation SQL, un « innerHTML », un secret codé en dur et une route d’administration sans contrôle d’accès clair. Moussa doit transformer cette revue en habitudes durables plutôt qu’en correction de dernière minute."),
    videoSlot("Faire entrer la sécurité dans la routine de développement"),
    text("Développer de façon sûre ne veut pas dire ajouter un contrôle final à la veille de la mise en production. Cela veut dire décider tôt ce qui doit être vrai, puis vérifier ces exigences tout au long du cycle. L’ASVS d’OWASP sert justement de catalogue d’exigences de vérification. Un projet simple exposé à Internet peut viser d’abord les contrôles de base. Une application plus sensible monte ensuite en exigence. La modélisation des menaces, par exemple avec STRIDE, sert à choisir où investir l’effort avant même d’écrire tout le code."),
    schema([
      "Chaîne de développement sûre",
      "",
      "exigences     : ASVS, périmètre, données sensibles, rôles",
      "conception    : menaces, surfaces d’attaque, choix d’architecture",
      "code          : revues, normes, tests unitaires de sécurité",
      "pipeline      : SAST, SCA, secrets, tests bloquants",
      "déploiement   : secrets séparés, rollback, vérifications finales",
      "retour        : rapports, incidents, correction et re-test",
    ].join("\n")),
    text("La revue de code sécurité cherche des motifs concrets. Quatre exemples reviennent sans cesse : une requête SQL concaténée avec une entrée utilisateur, un « innerHTML » alimenté par une donnée non fiable, un secret codé en dur, et une route sensible qui ne vérifie pas clairement le rôle autorisé. La revue ne se contente pas d’écrire « à revoir ». Elle note la preuve, le risque et la correction attendue. Une règle utile pour débuter : si la revue ne dit pas quoi corriger et comment vérifier la correction, elle n’est pas finie."),
    schema([
      "Extrait de revue à relire",
      "",
      "const sql = \"SELECT * FROM dons WHERE email = '\" + email + \"'\";",
      "zone.innerHTML = commentaire;",
      "const apiKey = \"CLE_EXEMPLE_SERVICE\";",
      "app.post(\"/admin/export\", exportCsv);",
      "",
      "Défauts à repérer : injection, XSS, secret codé en dur, contrôle d’accès absent",
    ].join("\n")),
    text("SAST, DAST et SCA ne couvrent pas la même chose. Le SAST lit le code ou l’arbre compilé sans exécuter l’application. Le DAST observe l’application en fonctionnement depuis l’extérieur. Le SCA analyse les dépendances et leurs avis de sécurité. Aucun ne remplace la revue humaine. Ensemble, ils réduisent l’oubli. La détection de secrets dans le pipeline répond à un besoin encore plus simple : empêcher qu’une clé ou un jeton entre dans le dépôt principal."),
    text("Démonstration guidée : le petit contrôle ci-dessous crée un fichier d’essai, puis refuse trois motifs faciles à repérer avant le commit. Le premier signale un secret fictif « CLE_EXEMPLE_ ». Le deuxième signale « innerHTML = ». Le troisième signale une concaténation SQL très naïve. Dans la vraie vie, tu utiliseras aussi des outils spécialisés. L’exercice t’apprend surtout à penser en garde-fou automatique."),
    text("Prérequis de démonstration : vérifie d’abord « node --version ». Cet extrait n’emploie que des API Node.js stables de longue date. Si Node.js manque ou si l’extrait échoue sur ta machine, mets-le à jour avant de continuer."),
    code([
      "const fs = require(\"node:fs\");",
      "const os = require(\"node:os\");",
      "const path = require(\"node:path\");",
      "",
      "const fichier = path.join(os.tmpdir(), \"swb-hook-demo.js\");",
      "fs.writeFileSync(",
      "  fichier,",
      "  [",
      "    'const apiKey = \"CLE_EXEMPLE_SERVICE\";',",
      "    'zone.innerHTML = commentaire;',",
      "    'const sql = \"SELECT * FROM dons WHERE email = \\\"\" + email + \"\\\"\";',",
      "  ].join(\"\\n\"),",
      "  \"utf8\",",
      ");",
      "",
      "const contenu = fs.readFileSync(fichier, \"utf8\");",
      "const regles = [",
      "  { nom: \"secret fictif\", motif: /CLE_EXEMPLE_[A-Z0-9_]+/ },",
      "  { nom: \"innerHTML\", motif: /\\.innerHTML\\s*=/ },",
      "  { nom: \"concat SQL naïve\", motif: /SELECT \\* FROM .*\\+\\s*[a-zA-Z_][a-zA-Z0-9_]*/ },",
      "];",
      "",
      "const trouves = regles.filter((regle) => regle.motif.test(contenu)).map((regle) => regle.nom);",
      "if (trouves.length > 0) {",
      "  console.log(\"commit refusé :\", trouves.join(\", \"));",
      "} else {",
      "  console.log(\"aucun motif bloquant détecté\");",
      "}",
      "# exemple de sortie (valeurs fictives)",
      "# commit refusé : secret fictif, innerHTML, concat SQL naïve",
    ].join("\n"), "javascript"),
    schema([
      "Avant de fusionner",
      "",
      "1. la revue de code note-t-elle les défauts concrets ?",
      "2. un test automatisé casse-t-il la fusion en cas de secret ou dépendance critique ?",
      "3. la correction a-t-elle été re-testée ?",
      "4. un « security.txt » existe-t-il pour la divulgation coordonnée ?",
    ].join("\n")),
    text("La divulgation coordonnée fait aussi partie d’un développement responsable. Le fichier « security.txt », défini par la RFC 9116, donne un point de contact et une politique minimale pour signaler une vulnérabilité. Il ne remplace ni un bug bounty, ni une équipe sécurité, mais il évite à un chercheur de ne pas savoir à qui écrire. Côté équipe produit, cela complète le cycle : exigences, construction, revue, test, réception d’un signal externe, correction, re-test."),
    example("Exemple corrigé : sur l’extrait de revue, la correction attendue n’est pas « mieux coder ». Elle est précise. La requête SQL devient paramétrée. « innerHTML » est remplacé par « textContent » ou par un assainissement contrôlé si du HTML riche est réellement nécessaire. La clé sort du code et passe dans un mécanisme de secret dédié. La route « /admin/export » vérifie un rôle explicite côté serveur avant l’action. Chaque correction reçoit ensuite un test ou un contrôle de pipeline correspondant."),
    mistakes("traiter la sécurité comme une étape finale ; croire qu’un seul outil remplace la revue humaine ; accepter un secret en disant qu’il sera changé plus tard ; fermer une alerte de scanner sans expliquer pourquoi ; fusionner une correction sans re-test ciblé."),
    safety("travaille uniquement sur ton dépôt ou un dépôt pour lequel tu as l’autorisation d’agir. Ne publie pas un secret réel dans un exemple, même pour « montrer le problème ». Les démonstrations gardent donc des motifs fictifs et des chemins d’essai."),
    takeaway("un développement sûr repose sur des exigences claires, des revues concrètes et des garde-fous automatiques. SAST, DAST, SCA et détection de secrets se complètent, mais ne remplacent pas l’analyse humaine. Une bonne correction se termine par un re-test et un moyen clair de recevoir un signal externe."),
    practice("Travaille dans « Projet final : auditer l’application de réservation et rédiger le rapport » : utilise cette leçon pour repérer les contrôles qui devraient déjà exister dans le cycle de développement, puis note honnêtement que le projet final prépare l’audit plus qu’il ne met en place toute la chaîne CI. Termine par le quiz."),
    reference("owaspAsvs"),
    reference("owaspSamm"),
    reference("owaspCsThreatModeling"),
    reference("rfc9116"),
    reference("nodeFs"),
  ],
  quiz: {
    title: "Quiz : développement sûr et pipeline",
    questions: [
      questions.choice("Quel rôle joue le SCA dans un pipeline de sécurité ?", ["Relire le HTML dans le navigateur", "Analyser les dépendances et leurs avis de sécurité", "Tester la charge CPU du serveur", "Créer automatiquement les comptes utilisateurs"], 1, "Le SCA vise la chaîne de dépendances et leurs vulnérabilités connues. Il ne remplace ni les tests dynamiques ni la revue de code. Le faux ami est de lui attribuer un rôle d’analyse fonctionnelle ou d’administration.", "facile"),
      questions.choice("Pourquoi un contrôle de secret avant le commit est-il utile ?", ["Parce qu’il corrige automatiquement toutes les failles", "Parce qu’il évite qu’une clé entre dans l’historique du dépôt", "Parce qu’il remplace le gestionnaire de mots de passe", "Parce qu’il transforme un mot de passe en hachage"], 1, "L’intérêt principal est d’empêcher qu’un secret entre dans l’historique Git, où il devient difficile à retirer complètement. Le faux raccourci serait de croire que ce contrôle remplace les autres mesures de stockage ou de rotation des secrets.", "moyen"),
      questions.multi("Lis cet extrait : « zone.innerHTML = commentaire; const apiKey = \"CLE_EXEMPLE_SERVICE\"; app.post(\"/admin/export\", exportCsv); ». Quels risques apparaissent ? (plusieurs réponses)", ["XSS potentiel", "Secret codé en dur", "Contrôle d’accès à vérifier sur une route sensible", "Certificat TLS expiré"], [0, 1, 2], "L’extrait montre bien un affichage dangereux, un secret dans le code et une route d’administration dont le contrôle d’accès n’est pas visible. Rien ici ne dit quoi que ce soit sur un certificat TLS, ce qui en fait la mauvaise réponse tentante pour quelqu’un qui mélange les couches.", "difficile"),
      questions.tf("Le fichier « security.txt » remplace à lui seul la revue de code, le bug bounty et la gestion des vulnérabilités.", false, "Faux : « security.txt » fournit surtout un point de contact et un cadre minimal de divulgation. Il complète le développement sûr, mais ne remplace ni les contrôles internes ni le traitement opérationnel des signalements.", "moyen"),
    ],
  },
};

const webWafDetectionLesson: NewLesson = {
  key: "web-waf-detection",
  title: "Se défendre en profondeur : pare-feu applicatif, limitation de débit, journaux et détection",
  summary: "Découvre comment ralentir, voir et qualifier une attaque web avec un WAF, une limitation de débit et des journaux utiles, sans confondre défense en profondeur et correction définitive.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("expliquer le rôle d’un WAF, distinguer limitation de débit et contrôle d’accès, choisir quoi journaliser sans fuite de secret, repérer un motif d’abus dans un journal, et décrire une réponse à incident web en cinq étapes."),
    prerequisites("avoir déjà étudié les injections, les accès refusés et la journalisation côté application."),
    scenario("Ama administre une petite application de dons. Une route reçoit beaucoup de 404 et de 401 depuis quelques adresses, le WAF bloque déjà quelques signatures, mais certaines requêtes passent encore. Ama doit comprendre ce que la couche défensive voit, ce qu’elle ne voit pas, et comment alerter sans noyer l’équipe."),
    videoSlot("Voir et ralentir une attaque web sans se raconter d’histoire"),
    text("La défense en profondeur ajoute des couches qui rendent l’attaque plus difficile, plus visible ou plus coûteuse, sans prétendre qu’une seule d’entre elles suffit. Un WAF filtre certaines requêtes connues ou anormales avant l’application, par exemple avec un moteur comme ModSecurity et un jeu de règles comme OWASP CRS. Une limitation de débit ralentit les abus répétitifs. La journalisation garde une trace utile de ce qui a été tenté, autorisé ou refusé. Aucune de ces couches ne corrige une injection SQL ou un XSS dans le code. Elles gagnent du temps et réduisent l’impact, mais la vraie correction reste dans l’application."),
    schema([
      "Couches utiles",
      "",
      "navigateur -> CDN ou reverse proxy -> WAF -> application -> base de données",
      "",
      "WAF                : filtre quelques motifs connus, pas la logique métier",
      "limitation de débit: ralentit les rafales, renvoie souvent 429",
      "journaux           : rendent l’abus visible et réanalysable",
      "correctif code     : supprime la cause profonde",
    ].join("\n")),
    text("Un journal de sécurité applicative répond à une règle simple : qui, quoi, quand, où, résultat, identifiant de corrélation. Tu y gardes par exemple l’adresse ou l’identifiant réseau utile, le compte s’il existe, la route appelée, la méthode, le code HTTP, la décision de sécurité, et l’identifiant qui relie la requête à d’autres traces. Tu n’y gardes jamais un mot de passe, un jeton de session, un secret d’API ou un numéro de carte. La CNIL recommande d’ailleurs de journaliser les actions, anomalies et interventions techniques utiles, sans dupliquer inutilement des données personnelles. Si tu dois journaliser un corps de requête pour une raison précise, tu le fais de façon minimale et contrôlée."),
    text("Démonstration guidée : le script lit un petit journal d’accès JSON inventé, puis lève une alerte lorsqu’une même adresse dépasse trois réponses 404 ou 401 dans une fenêtre glissante de cinq minutes. Il ne bloque rien lui-même. Il produit seulement un signal défendable. Dans une équipe réelle, ce type de logique complète le WAF : une requête peut être autorisée par le WAF et rester pourtant suspecte par sa fréquence ou par sa cible."),
    text("Prérequis de démonstration : vérifie d’abord « node --version ». Cet extrait utilise seulement des tableaux, des dates ISO et « console.table ». Si Node.js n’est pas installé ou si la commande échoue, mets-le à jour avant de continuer."),
    code([
      "const evenements = [",
      "  { ts: \"2026-03-10T09:00:00Z\", ip: \"192.0.2.44\", status: 404, path: \"/.env\" },",
      "  { ts: \"2026-03-10T09:01:10Z\", ip: \"192.0.2.44\", status: 404, path: \"/wp-login.php\" },",
      "  { ts: \"2026-03-10T09:02:05Z\", ip: \"192.0.2.44\", status: 401, path: \"/admin\" },",
      "  { ts: \"2026-03-10T09:03:12Z\", ip: \"192.0.2.55\", status: 200, path: \"/catalogue\" },",
      "  { ts: \"2026-03-10T09:04:01Z\", ip: \"192.0.2.44\", status: 404, path: \"/phpmyadmin/\" },",
      "];",
      "",
      "const seuil = 3;",
      "const fenetreMs = 5 * 60 * 1000;",
      "const alertes = [];",
      "",
      "for (let i = 0; i < evenements.length; i += 1) {",
      "  const courant = evenements[i];",
      "  if (![401, 404].includes(courant.status)) continue;",
      "  const debut = new Date(courant.ts).getTime() - fenetreMs;",
      "  const total = evenements.filter((evt) => evt.ip === courant.ip && [401, 404].includes(evt.status) && new Date(evt.ts).getTime() >= debut && new Date(evt.ts).getTime() <= new Date(courant.ts).getTime()).length;",
      "  if (total >= seuil) {",
      "    alertes.push({ ip: courant.ip, ts: courant.ts, total });",
      "  }",
      "}",
      "",
      "console.table(alertes);",
      "# exemple de sortie (valeurs fictives)",
      "# ┌─────────┬──────────────┬────────────────────────┬───────┐",
      "# │ (index) │ ip           │ ts                     │ total │",
      "# ├─────────┼──────────────┼────────────────────────┼───────┤",
      "# │ 0       │ '192.0.2.44' │ '2026-03-10T09:02:05Z' │ 3     │",
      "# │ 1       │ '192.0.2.44' │ '2026-03-10T09:04:01Z' │ 4     │",
      "# └─────────┴──────────────┴────────────────────────┴───────┘",
    ].join("\n"), "javascript"),
    schema([
      "Réponse à incident web en cinq étapes",
      "",
      "1. isoler ce qui doit l’être sans détruire les preuves",
      "2. préserver les journaux et la configuration utile",
      "3. comprendre le chemin d’attaque ou d’abus",
      "4. corriger la cause et pas seulement le symptôme",
      "5. vérifier le correctif et renforcer la détection",
    ].join("\n")),
    text("Le WAF et la limitation de débit ont des limites claires. Un WAF produit des faux positifs, peut gêner une fonctionnalité légitime, et se contourne parfois. Une limitation de débit doit distinguer un abus automatisé d’un pic normal d’activité, sinon elle pénalise les utilisateurs. Les réponses 429 avec un « Retry-After » cohérent aident le client légitime à se comporter correctement, mais elles ne valent pas contrôle d’accès. Enfin, une alerte utile reste une hypothèse à confirmer : elle doit être relue avec le contexte, les journaux applicatifs et, si besoin, le parcours complet de la requête."),
    example("Exemple corrigé : si le WAF bloque déjà quelques signatures sur « /.env », mais que le journal applicatif montre encore quatre 404 et 401 en cinq minutes sur « /admin », « /wp-login.php » et « /phpmyadmin/ », la conclusion raisonnable est « tentative de repérage persistante, pas correction suffisante ». On peut relever le signal, durcir la route d’administration, vérifier la limitation de débit, puis corriger le code ou la configuration qui laisserait passer une vraie faille si elle existait."),
    mistakes("présenter le WAF comme un correctif ; journaliser un jeton ou un mot de passe pour « aider le debug » ; alerter sur tout sans fenêtre ni seuil ; bloquer définitivement une adresse partagée sans procédure ; oublier l’identifiant de corrélation qui permettra de relier plusieurs journaux."),
    safety("n’analyse et ne modifie que ton application ou un système pour lequel tu as une autorisation écrite. Les journaux web peuvent contenir des données personnelles : protège-les, minimise-les et évite tout envoi à un service tiers. Toute mesure de blocage qui peut toucher des utilisateurs légitimes suit la procédure de l’organisation."),
    takeaway("un WAF, une limitation de débit et de bons journaux renforcent une application, mais ne corrigent pas le code à ta place. Une alerte utile décrit un motif, pas une certitude finale. La défense en profondeur sert à ralentir, voir, corriger, puis vérifier."),
    practice("Travaille dans « Projet final : auditer l’application de réservation et rédiger le rapport » : utilise cette leçon pour noter les défenses attendues et les limites d’un WAF ou d’une limitation de débit, en disant honnêtement que le projet final prépare surtout leur évaluation, pas leur déploiement complet. Termine par le quiz."),
    reference("owaspCsDos"),
    reference("mdnStatus429"),
    reference("cnilTracer"),
    reference("cnilGuideSecurite"),
    reference("modsecurity"),
    reference("owaspCrs"),
  ],
  quiz: {
    title: "Quiz : WAF, limitation de débit et détection",
    questions: [
      questions.choice("Quelle phrase décrit le mieux le rôle d’un WAF ?", ["Il corrige définitivement une injection SQL dans le code", "Il ajoute une couche de filtrage utile mais ne remplace pas le correctif", "Il rend inutiles les journaux applicatifs", "Il remplace le contrôle d’accès"], 1, "Un WAF réduit le bruit, bloque certains motifs et fait gagner du temps, mais la cause profonde reste dans le code ou la configuration. Le faux raccourci le plus dangereux consiste justement à confondre couche défensive et correction définitive.", "facile"),
      questions.choice("Pourquoi journaliser un identifiant de corrélation est-il utile ?", ["Pour remplacer toutes les autres données de journal", "Pour pouvoir relier la même requête entre plusieurs traces", "Pour stocker le mot de passe sous une autre forme", "Pour désactiver le WAF plus vite"], 1, "Un identifiant de corrélation aide à suivre une même requête entre reverse proxy, application et parfois base de données. Il ne remplace pas les autres champs et ne doit pas servir à masquer un secret ou à contourner un contrôle.", "moyen"),
      questions.multi("Lis cette situation : « 192.0.2.44 reçoit quatre 404 ou 401 en moins de cinq minutes sur /.env, /wp-login.php, /admin et /phpmyadmin/ ». Quelles conclusions sont prudentes ? (plusieurs réponses)", ["Le motif justifie une alerte ou une surveillance renforcée", "Le WAF seul suffit désormais comme correction", "Le comportement ressemble à du repérage automatisé", "Il faut vérifier le contexte avant d’annoncer une compromission"], [0, 2, 3], "Le motif et les chemins visés ressemblent bien à du repérage, donc un signal défensif est justifié. En revanche, rien ne permet d’annoncer une compromission certaine ni de prétendre que le WAF remplace la correction de fond.", "difficile"),
      questions.tf("Une réponse 429 et un en-tête « Retry-After » peuvent aider à limiter un abus, mais ne remplacent pas un vrai contrôle d’accès.", true, "Vrai : la limitation de débit agit sur la fréquence, pas sur le droit d’effectuer l’action. Un client peut attendre puis recommencer. Le contrôle d’accès reste donc une vérification distincte et indispensable.", "moyen"),
    ],
  },
};

const webCadreAuditLesson: NewLesson = {
  key: "web-cadre-audit",
  title: "Cadre d’un audit web : autorisation, périmètre et règles d’engagement",
  summary: "Pose le cadre légal et opérationnel d’un audit web : qui autorise, quoi tester, quand s’arrêter, comment traiter les données et comment s’entraîner légalement.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("distinguer audit, évaluation de vulnérabilités, revue de code et test d’intrusion, définir un périmètre, lire une règle d’engagement, repérer ce qui est hors champ, et choisir une plateforme d’entraînement légale."),
    prerequisites("connaître les principales familles de failles web et leur impact possible."),
    scenario("Fatou reçoit un message pressé : « peux-tu tester le portail de réservation cet après-midi ? ». Elle sait déjà que la bonne réponse n’est pas « oui » tout de suite. Sans autorisation écrite, sans périmètre, sans contact d’urgence et sans règle d’arrêt, une bonne intention peut devenir une faute grave pour l’organisation comme pour elle."),
    videoSlot("Poser le cadre d’un audit avant le premier test"),
    text("Un audit web n’est pas toujours un test d’intrusion complet. Tu peux mener une revue de configuration, une revue de code, une évaluation de vulnérabilités, un contrôle d’exigences, ou un test d’intrusion autorisé. Le mot compte moins que le cadre. Ce cadre tient sur quelques questions simples : qui t’autorise, quels environnements sont inclus, quels comptes de test sont fournis, quelles techniques sont autorisées ou interdites, à quelles heures, à quel volume, avec quel contact d’urgence, et dans quelles conditions tu dois t’arrêter."),
    schema([
      "Lettre de mission minimale",
      "",
      "cible        : URL, API, sous-domaines, environnement",
      "comptes      : jeux d’essai fournis, rôles, MFA éventuelle",
      "techniques   : lecture seule, scans passifs, tests actifs autorisés ou non",
      "horaires     : plage de test, jours exclus, période sensible",
      "volumétrie   : limites de requêtes, pas de déni de service",
      "contacts     : responsable métier, exploitant, urgence",
      "arrêt        : conditions d’arrêt et escalade",
    ].join("\n")),
    text("Le périmètre protège autant l’organisation que l’auditeur. Un CDN, un prestataire de paiement, un fournisseur d’e-mails transactionnels ou un hébergeur externe ne sont pas automatiquement dans le champ. Un sous-domaine de test ne l’est pas non plus si personne ne l’a écrit. Un environnement de production mérite encore plus de prudence : on y évite les tests destructifs et les rafales non négociées. La confidentialité compte aussi : pendant un audit, tu peux voir des journaux, des données personnelles, des noms internes ou des secrets. Tu minimises, tu protèges, et tu limites la copie ou la diffusion à ce qui est nécessaire à la mission."),
    text("Démonstration guidée : le petit script ci-dessous formalise une partie du périmètre. Il reçoit une liste d’hôtes autorisés et quelques exclusions. Ensuite, il répond à une question simple : « cette cible est-elle dans le champ convenu ? ». Cela ne remplace pas une vraie lettre de mission, mais cela montre qu’un périmètre se vérifie explicitement, pas à l’intuition."),
    text("Prérequis de démonstration : vérifie d’abord « node --version ». Cet extrait n’utilise que JavaScript de base. Si Node.js manque ou si la commande échoue, mets-le à jour avant de continuer."),
    code([
      "const scope = {",
      "  hotesAutorises: [\"app.example.org\", \"api.example.org\"],",
      "  exclus: [\"paiement.example.org\", \"status.example.org\"],",
      "};",
      "",
      "function estDansLePerimetre(hote) {",
      "  return scope.hotesAutorises.includes(hote) && !scope.exclus.includes(hote);",
      "}",
      "",
      "for (const hote of [\"app.example.org\", \"status.example.org\", \"cdn.example.org\"]) {",
      "  console.log(hote, estDansLePerimetre(hote));",
      "}",
      "# exemple de sortie (valeurs fictives)",
      "# app.example.org true",
      "# status.example.org false",
      "# cdn.example.org false",
    ].join("\n"), "javascript"),
    schema([
      "Divulgation responsable trouvée par hasard",
      "",
      "ne pas insister ni télécharger des données inutiles",
      "prendre juste assez de preuve pour expliquer le problème",
      "chercher « /.well-known/security.txt » ou un contact officiel",
      "prévenir sans publier la faille avant accord",
    ].join("\n")),
    text("Le cadre légal se résume alors en une règle claire : tu testes seulement ce que tu as le droit de tester, de la façon autorisée. Si tu trouves une faille par hasard en dehors d’une mission, tu ne l’exploites pas davantage. Tu cherches un contact de divulgation, souvent via « security.txt » ou un canal officiel, puis tu fournis une preuve minimale et défendable. Pour t’entraîner, tu restes sur des plateformes prévues pour cela, comme la Web Security Academy de PortSwigger, OWASP Juice Shop, WebGoat ou DVWA en local sur ta propre machine."),
    example("Exemple corrigé : une lettre de mission inventée autorise « app.example.org » et « api.example.org », en préproduction, de 09:00 à 17:00, avec comptes de test fournis, scans passifs autorisés et tests actifs sans déni de service. « paiement.example.org » reste hors champ car géré par un prestataire tiers. Si tu trouves un formulaire vulnérable sur ce sous-domaine tiers, tu le notes comme hors périmètre et tu passes par le contact prévu, tu ne continues pas l’exploration."),
    mistakes("croire qu’un accord oral suffit ; traiter tous les sous-domaines comme inclus ; oublier le prestataire tiers ; lancer un test actif sur la production sans volume négocié ; conserver des données de test plus longtemps que nécessaire."),
    safety("un audit web sans cadre écrit peut devenir une infraction ou un incident opérationnel. Protège les données rencontrées, respecte le besoin d’en connaître, et entraîne-toi uniquement sur des plateformes légales ou sur ton propre environnement de test."),
    takeaway("avant le premier test, tu dois savoir quoi, où, quand, comment et jusqu’où. Le périmètre n’est jamais supposé : il est écrit. La confidentialité et la minimisation des données font partie du travail d’audit. Pour apprendre, tu restes sur des cibles prévues pour cela."),
    practice("Travaille dans « Projet final : auditer l’application de réservation et rédiger le rapport » : commence par relire le périmètre, les exclusions et les règles d’engagement du dossier, puis termine par le quiz."),
    reference("owaspWstg"),
    reference("owaspJuiceShop"),
    reference("owaspWebGoat"),
    reference("rfc9116"),
    reference("cnilRgpd"),
  ],
  quiz: {
    title: "Quiz : cadre d’un audit web",
    questions: [
      questions.choice("Quel élément doit exister avant un test actif sur une application d’un tiers ?", ["Une autorisation écrite avec périmètre et règles d’engagement", "Un simple message informel sur la messagerie interne", "Une bonne intention défensive", "Un compte administrateur trouvé par hasard"], 0, "L’autorisation écrite fixe le périmètre, les limites et les responsabilités. Sans elle, l’intention défensive ne suffit pas. Le faux ami le plus dangereux est justement de croire qu’un accord flou ou oral couvre les risques juridiques et opérationnels.", "facile"),
      questions.choice("Pourquoi un sous-domaine de paiement tiers n’est-il pas automatiquement dans le périmètre d’un audit du site principal ?", ["Parce qu’un sous-domaine n’est jamais lié au site", "Parce qu’il peut dépendre d’un prestataire distinct hors accord", "Parce qu’il est forcément protégé par un WAF", "Parce qu’il n’utilise jamais HTTPS"], 1, "Un prestataire tiers peut exploiter un sous-domaine ou un service sans faire partie de la mission. Le point clé est contractuel et opérationnel, pas technique. Le faux raccourci consiste à penser que le DNS seul décide du périmètre.", "moyen"),
      questions.multi("Lis cette situation : « tu trouves une faille par hasard hors mission sur un site tiers ». Quelles réactions sont prudentes ? (plusieurs réponses)", ["Ne pas approfondir inutilement", "Chercher un contact « security.txt » ou officiel", "Télécharger toute la base pour prouver la gravité", "Fournir une preuve minimale et défendable"], [0, 1, 3], "Hors mission, la retenue protège autant le tiers que toi. Une preuve minimale suffit pour signaler. Télécharger des données ou approfondir sans cadre dépasse la divulgation responsable et augmente le risque pour tout le monde.", "difficile"),
      questions.tf("Une plateforme d’entraînement comme Web Security Academy ou Juice Shop en local constitue un cadre légal plus sûr qu’un site réel trouvé sur Internet.", true, "Vrai : ces plateformes existent pour l’apprentissage et le test autorisé. Un site réel trouvé sur Internet, même vulnérable, ne devient jamais une cible légale simplement parce qu’il semble mal protégé.", "moyen"),
    ],
  },
};

const webMethodeAuditLesson: NewLesson = {
  key: "web-methode-audit",
  title: "Mener un audit web par étapes : cartographier, vérifier, consigner",
  summary: "Suis une méthode d’audit web progressive : lecture seule d’abord, cartographie, configuration, sessions, accès, entrées, puis consignation rigoureuse des preuves.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("dérouler les grandes étapes du WSTG, distinguer lecture seule et test actif, cartographier des routes et des rôles, consigner une preuve utile, vérifier un faux positif, et résumer des en-têtes manquants à partir d’un jeu de réponses local."),
    prerequisites("avoir compris le cadre d’un audit, les principales familles de failles web et l’importance du périmètre."),
    scenario("Awa prépare l’audit de l’application de réservation de Baobab Tech. Elle a l’autorisation, les comptes de test et la fenêtre de tir. Son risque principal n’est plus juridique : c’est de partir dans tous les sens. Elle doit donc suivre une méthode, commencer en lecture seule, consigner proprement ses observations et ne lancer un test actif que lorsqu’elle sait pourquoi."),
    videoSlot("Mener un audit web avec une méthode reproductible"),
    text("Le WSTG d’OWASP sert de guide de test, pas de scénario rigide à cocher sans réfléchir. Sa logique reste pourtant très utile : cadrage, cartographie, configuration, identités, authentification, autorisation, sessions, injection et autres entrées non fiables, erreurs, cryptographie, logique métier, client et API. Le bon ordre n’est pas « tout tester tout de suite ». Le bon ordre est « comprendre d’abord, tester ensuite ». Une lecture seule des en-têtes, des cookies, de la configuration TLS, de « robots.txt », de « security.txt » et du plan du site donne souvent déjà beaucoup d’informations."),
    schema([
      "Audit web par étapes",
      "",
      "1. cartographier : pages, routes, rôles, versions, API",
      "2. lire : TLS, cookies, en-têtes, méthodes, réponses",
      "3. vérifier : sessions, accès, entrées, erreurs",
      "4. approfondir : logique métier, API, client riche",
      "5. consigner : requête, réponse, conclusion, preuve, référence",
    ].join("\n")),
    text("La différence entre analyse passive et active est simple mais importante. Passive : tu observes ce que l’application renvoie sans chercher à la faire sortir de son comportement normal. Active : tu modifies les paramètres, les comptes, les rôles, le volume ou les entrées pour vérifier une hypothèse. Même sur une cible autorisée, l’actif mérite une intention claire. Un scanner comme ZAP en mode « baseline » convient bien pour commencer sur son propre site : il signale quelques points de configuration sans lancer toute la boîte à outils offensive. Ensuite, chaque signal doit être vérifié manuellement, car un scanner produit toujours des faux positifs."),
    text("Démonstration guidée : le script ci-dessous lit un petit fichier local contenant des réponses HTTP inventées. Il ne fait aucune requête réseau réelle. Il résume pour chaque URL le statut, puis les en-têtes attendus qui manquent. C’est un bon exercice de méthode : collecter, lire, résumer, puis seulement décider quoi vérifier plus loin à la main."),
    text("Prérequis de démonstration : vérifie d’abord « node --version ». Cet extrait n’utilise que « node:fs », « node:os », « node:path » et « console.table ». Si Node.js manque ou si l’extrait échoue, mets-le à jour avant de continuer."),
    code([
      "const fs = require(\"node:fs\");",
      "const os = require(\"node:os\");",
      "const path = require(\"node:path\");",
      "",
      "const fichier = path.join(os.tmpdir(), \"swb-audit-reponses.json\");",
      "const reponses = [",
      "  { url: \"https://app.example.org/\", status: 200, headers: { \"strict-transport-security\": \"max-age=31536000\", \"x-content-type-options\": \"nosniff\" } },",
      "  { url: \"https://app.example.org/login\", status: 200, headers: { \"content-security-policy\": \"default-src 'self'\", \"referrer-policy\": \"strict-origin-when-cross-origin\" } },",
      "  { url: \"https://app.example.org/admin\", status: 403, headers: { \"x-content-type-options\": \"nosniff\" } },",
      "];",
      "fs.writeFileSync(fichier, JSON.stringify(reponses, null, 2), \"utf8\");",
      "",
      "const attentes = [\"strict-transport-security\", \"content-security-policy\", \"x-content-type-options\"];",
      "const charges = JSON.parse(fs.readFileSync(fichier, \"utf8\"));",
      "const resume = charges.map((item) => ({",
      "  url: item.url,",
      "  status: item.status,",
      "  manquants: attentes.filter((nom) => !(nom in item.headers)),",
      "}));",
      "console.table(resume);",
      "# exemple de sortie (valeurs fictives)",
      "# ┌─────────┬────────────────────────────────┬────────┬──────────────────────────────────────────────┐",
      "# │ (index) │ url                            │ status │ manquants                                    │",
      "# ├─────────┼────────────────────────────────┼────────┼──────────────────────────────────────────────┤",
      "# │ 0       │ 'https://app.example.org/'     │ 200    │ [ 'content-security-policy' ]                │",
      "# │ 1       │ 'https://app.example.org/login'│ 200    │ [ 'strict-transport-security', 'x-content-type-options' ] │",
      "# │ 2       │ 'https://app.example.org/admin'│ 403    │ [ 'strict-transport-security', 'content-security-policy' ] │",
      "# └─────────┴────────────────────────────────┴────────┴──────────────────────────────────────────────┘",
    ].join("\n"), "javascript"),
    schema([
      "Fiche de test à tenir à jour",
      "",
      "date UTC       : quand le test a été lancé",
      "cible          : URL, rôle et compte de test",
      "requête        : méthode, chemin, en-têtes utiles, corps si nécessaire",
      "réponse        : code, en-têtes, extrait utile",
      "conclusion     : fait, hypothèse ou faux positif",
      "suite          : re-test, correction attendue, référence WSTG ou ASVS",
    ].join("\n")),
    text("Consigner proprement une preuve aide autant que trouver une faille. Une bonne note permet à un collègue de rejouer le test, à un développeur de reproduire le problème, et à un responsable de comprendre la priorité. Tu notes donc la date, le rôle utilisé, la requête exacte, la réponse, puis la conclusion. Tu évites les phrases vagues comme « ça a l’air risqué ». Tu écris plutôt « la route « /admin/export » répond 200 au compte standard Ama, ce qui contredit la matrice de droits fournie »."),
    example("Exemple corrigé : mauvaise consigne, « l’appli semble manquer d’en-têtes, à vérifier ». Bonne consigne, « le 2026-03-10 à 09:42Z, la réponse 200 de « https://app.example.org/ » contient « Strict-Transport-Security » et « X-Content-Type-Options », mais pas de « Content-Security-Policy ». Signal de configuration à confirmer sur les autres routes avant recommandation globale. Référence : configuration et en-têtes du WSTG ». La deuxième version se rejoue et se relit, la première non."),
    mistakes("attaquer avant d’avoir cartographié ; confondre lecture seule et test actif ; recopier le résultat d’un scanner sans vérification manuelle ; oublier le rôle ou le compte de test utilisé ; écrire une conclusion sans requête ni réponse attachées."),
    safety("respecte le périmètre, les horaires et la volumétrie convenus. En production, évite les tests destructifs et les rafales non négociées. Toute preuve collectée peut contenir des données sensibles : limite la diffusion, protège les captures et détruis les copies non nécessaires selon la mission."),
    takeaway("un audit web sérieux commence par comprendre avant de forcer. Lecture seule, cartographie, test ciblé, preuve reproductible : voilà la séquence saine. Un scanner aide à voir, pas à conclure. La preuve consignée vaut autant que le test lui-même."),
    practice("Travaille dans « Projet final : auditer l’application de réservation et rédiger le rapport » : reprends les étapes du WSTG, commence par les observations en lecture seule, puis complète tes fiches de test avant le quiz."),
    reference("owaspWstg"),
    reference("zapDocs"),
    reference("owaspAsvs"),
    reference("owaspWstgCategories"),
    reference("nodeFs"),
  ],
  quiz: {
    title: "Quiz : méthode d’audit web",
    questions: [
      questions.choice("Quel réflexe respecte le mieux la logique du WSTG au début d’un audit ?", ["Tester tout de suite les entrées les plus agressives", "Commencer par la lecture seule et la cartographie", "Désactiver les journaux pour aller plus vite", "Créer d’abord de nouveaux comptes administrateurs"], 1, "La lecture seule et la cartographie donnent le contexte et évitent de lancer des tests mal ciblés. Le faux réflexe le plus courant est de vouloir prouver une faille avant même d’avoir compris la surface auditée.", "facile"),
      questions.choice("Pourquoi un résultat de scanner doit-il être vérifié manuellement ?", ["Parce qu’un scanner ne produit jamais aucun résultat utile", "Parce qu’il peut produire des faux positifs ou manquer le contexte", "Parce qu’il remplace la cartographie", "Parce qu’il supprime les journaux"], 1, "Les scanners sont précieux pour signaler des pistes, mais ils ne comprennent pas tout le contexte métier ou applicatif. Le risque classique est de recopier une alerte telle quelle sans preuve reproductible ni vérification de l’impact réel.", "moyen"),
      questions.multi("Lis cette note : « 09:42Z, compte Ama, GET /admin/export -> 200, alors que la matrice de droits dit standard ». Que peux-tu déjà affirmer ? (plusieurs réponses)", ["La note contient un horaire et un compte de test utiles", "Elle relie une requête, une réponse et une matrice métier", "La route est forcément protégée correctement", "La note est plus rejouable qu’un simple “ça semble risqué”"], [0, 1, 3], "Cette note documente déjà les éléments nécessaires au re-test et à la discussion avec les développeurs. En revanche, elle ne prouve pas que la route est correctement protégée. Elle montre plutôt une incohérence à confirmer et à expliquer.", "difficile"),
      questions.tf("Un audit passif peut déjà révéler des erreurs de configuration utiles sans lancer de test agressif.", true, "Vrai : des en-têtes manquants, une politique de cookies faible, des méthodes HTTP inutiles ou une configuration TLS insuffisante se voient souvent dès la lecture. C’est précisément pourquoi la lecture seule vient d’abord dans une méthode d’audit sérieuse.", "moyen"),
    ],
  },
};

const webRapportRemediationLesson: NewLesson = {
  key: "web-rapport-remediation",
  title: "Rédiger le rapport : sévérité, preuve, correctif et vérification",
  summary: "Transforme une observation brute en constat exploitable : preuve reproductible, catégorie OWASP et CWE, score CVSS, recommandation actionnable et plan de re-test.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("structurer un constat d’audit, distinguer observation et conclusion, calculer une note CVSS v3.1, relier un constat à OWASP et à une CWE, écrire une recommandation actionnable, et préparer un re-test clair."),
    prerequisites("avoir déjà étudié la méthode d’audit, la logique CVSS et les principales catégories de failles du parcours."),
    scenario("Koffi a terminé ses vérifications techniques sur l’application de réservation. Il a plusieurs observations valides, mais son responsable ne veut ni slogans vagues ni liste brute de captures. Koffi doit rédiger un rapport que la direction comprenne, que les développeurs puissent corriger, et qu’un re-test puisse confirmer."),
    videoSlot("Écrire un constat utile du point de vue technique comme métier"),
    text("Un rapport d’audit utile relie trois publics. La direction veut comprendre le niveau de risque, les biens touchés et l’ordre des priorités. Les développeurs veulent une preuve reproductible, une cause plausible et une correction testable. L’équipe sécurité veut un dossier qui se rejoue au re-test. La structure classique répond à ces trois besoins : résumé exécutif, périmètre et méthode, synthèse par gravité, constats détaillés, plan de correction, plan de re-test, puis annexes de preuve."),
    schema([
      "Fiche d’un constat",
      "",
      "titre          : court et spécifique",
      "catégorie      : OWASP 2025, CWE, éventuellement référence interne",
      "emplacement    : route, fonction, rôle, composant ou dépendance",
      "preuve         : requête, réponse, extrait ou capture minimale",
      "impact         : ce que cela permet ou expose",
      "note CVSS      : score + vecteur + limites de la note",
      "recommandation : action technique vérifiable",
      "re-test        : comment confirmer la correction",
    ].join("\n")),
    text("Un constat ne commence pas par « l’application est peu sûre ». Il commence par un fait. Exemple : « le compte standard Ama obtient 200 sur « /admin/export » ». Ensuite viennent l’interprétation et l’impact : contrôle d’accès défaillant, exposition potentielle de données, risque d’export non autorisé. La recommandation reste actionnable : vérifier le rôle côté serveur sur cette route et ajouter un test automatisé de refus. Une bonne recommandation se vérifie ensuite au re-test. Une mauvaise recommandation reste un slogan, par exemple « sécuriser l’application »."),
    text("Démonstration guidée : le script ci-dessous recalcule une note CVSS v3.1 pour un constat web simple. Il reprend les métriques de base, applique la formule de la spécification, puis sort la note arrondie vers le haut à une décimale avec une implémentation conforme à l’appendice de la spécification et la qualification associée. Ici, le vecteur complet de l’exemple aboutit à 9,8, ce qui permet de documenter proprement le rapport au lieu d’inventer une gravité « au feeling »."),
    text("Prérequis de démonstration : vérifie d’abord « node --version ». Cet extrait n’utilise que JavaScript de base. Si Node.js manque ou si la commande échoue, mets-le à jour avant de continuer."),
    code([
      "function roundUp1(decimal) {",
      "  const entier = Math.round(decimal * 100000);",
      "  if (entier % 10000 === 0) {",
      "    return entier / 100000;",
      "  }",
      "  return (Math.floor(entier / 10000) + 1) / 10;",
      "}",
      "",
      "function cvss31(vector) {",
      "  const AV = { N: 0.85, A: 0.62, L: 0.55, P: 0.2 };",
      "  const AC = { L: 0.77, H: 0.44 };",
      "  const UI = { N: 0.85, R: 0.62 };",
      "  const C = { H: 0.56, L: 0.22, N: 0 };",
      "  const I = { H: 0.56, L: 0.22, N: 0 };",
      "  const A = { H: 0.56, L: 0.22, N: 0 };",
      "  const S = vector.S;",
      "  const PR = S === \"U\" ? { N: 0.85, L: 0.62, H: 0.27 } : { N: 0.85, L: 0.68, H: 0.5 };",
      "  const iss = 1 - (1 - C[vector.C]) * (1 - I[vector.I]) * (1 - A[vector.A]);",
      "  const impact = S === \"U\" ? 6.42 * iss : 7.52 * (iss - 0.029) - 3.25 * Math.pow(iss - 0.02, 15);",
      "  const exploit = 8.22 * AV[vector.AV] * AC[vector.AC] * PR[vector.PR] * UI[vector.UI];",
      "  const base = impact <= 0 ? 0 : (S === \"U\" ? roundUp1(Math.min(impact + exploit, 10)) : roundUp1(Math.min(1.08 * (impact + exploit), 10)));",
      "  const niveau = base === 0 ? \"aucune\" : base < 4 ? \"faible\" : base < 7 ? \"moyenne\" : base < 9 ? \"élevée\" : \"critique\";",
      "  return { score: base, niveau };",
      "}",
      "",
      "const resultat = cvss31({ AV: \"N\", AC: \"L\", PR: \"N\", UI: \"N\", S: \"U\", C: \"H\", I: \"H\", A: \"H\" });",
      "console.log(resultat);",
      "# exemple de sortie (valeurs fictives)",
      "# { score: 9.8, niveau: 'critique' }",
    ].join("\n"), "javascript"),
    schema([
      "Prioriser sans se limiter à CVSS",
      "",
      "gravité technique : score et vecteur",
      "exposition        : Internet, interne, rôle nécessaire, fréquence",
      "actif concerné    : paiement, comptes, données, back-office",
      "exploitabilité    : simple ou non, automatisable ou non",
      "correctif         : disponible, testé, contournement provisoire ou non",
    ].join("\n")),
    text("Le CVSS aide à exprimer une gravité technique commune, mais il ne résume pas ton risque métier. Le rapport doit donc préciser la portée réelle : Internet ou intranet, compte standard ou compte d’administration, données sensibles ou fonction secondaire, exploitation simple ou non, correctif disponible ou pas. Il doit aussi séparer le fait, l’hypothèse et le faux positif éventuel. Un faux positif documenté ne disparaît pas du rapport d’équipe interne : il nourrit le réglage des outils et évite de refaire la même erreur au prochain audit."),
    example("Exemple corrigé : observation brute, « Ama voit un bouton d’export et reçoit un CSV ». Constat complet, « Contrôle d’accès défaillant sur « /admin/export » : le compte standard Ama obtient 200 sur la route d’export et reçoit un fichier CSV alors que la matrice de rôles limite cette fonction à l’administrateur. Catégorie : OWASP Top 10:2025 A01, CWE-862. Impact : export non autorisé de données. Preuve : requête GET, réponse 200, extrait d’en-tête et taille du fichier. Recommandation : vérification de rôle côté serveur et test automatisé de refus. Re-test : le compte standard doit recevoir 403, le compte administrateur 200. »"),
    mistakes("remplir un rapport avec des slogans ; oublier la preuve reproductible ; publier des données sensibles dans le résumé exécutif ; donner une note CVSS sans vecteur ; annoncer un correctif sans dire comment le vérifier ensuite."),
    safety("un rapport d’audit peut circuler loin. Sépare donc les détails sensibles du résumé large, applique le besoin d’en connaître, et évite de recopier des secrets, jetons ou données personnelles dans les parties qui n’en ont pas besoin."),
    takeaway("un bon rapport transforme une observation en décision de correction. Il doit être compris par la direction, rejoué par les développeurs et vérifié au re-test. CVSS structure la gravité technique, mais le contexte d’exposition et l’action de correction restent essentiels."),
    practice("Travaille dans « Projet final : auditer l’application de réservation et rédiger le rapport » : transforme chaque observation en constat complet, calcule la note utile, prépare le re-test, puis termine par le quiz."),
    reference("cvss31Spec"),
    reference("cvss31Calculator"),
    reference("owaspTop10A01"),
    reference("owaspWstg"),
    reference("cweSite"),
  ],
  quiz: {
    title: "Quiz : rapport, sévérité et remédiation",
    questions: [
      questions.choice("Quel élément manque à une recommandation comme « sécuriser l’application » ?", ["Un slogan plus alarmant", "Une action technique vérifiable", "Une couleur de gravité", "Un nom de machine plus court"], 1, "Une recommandation utile doit indiquer ce qu’il faut changer et comment le vérifier ensuite. « Sécuriser l’application » ne donne ni action précise, ni critère de re-test. Le faux ami consiste à croire qu’une phrase sévère suffit à guider la correction.", "facile"),
      questions.choice("Pourquoi noter le vecteur CVSS en plus du score ?", ["Parce que le score seul ne montre pas comment il a été obtenu", "Parce qu’un score sans vecteur devient automatiquement faux", "Parce que le vecteur remplace la preuve technique", "Parce qu’il supprime le besoin de recommandation"], 0, "Le vecteur explique les hypothèses retenues et permet à un lecteur de comprendre ou contester le calcul. Le score seul cache ce raisonnement. Il ne remplace ni la preuve, ni la recommandation, ni le contexte métier.", "moyen"),
      questions.multi("Lis ce constat : « le compte standard Ama obtient 200 sur « /admin/export » ». Quels compléments rendent le rapport meilleur ? (plusieurs réponses)", ["La preuve reproductible de la requête et de la réponse", "La catégorie OWASP ou CWE pertinente", "Une recommandation de correction testable", "L’accusation d’un développeur nommé"], [0, 1, 2], "Un bon constat relie fait, catégorie, preuve et correction. Accuser une personne ne fait pas partie du rapport utile. Le but est d’expliquer un problème vérifiable et de préparer sa remédiation, pas de distribuer la faute.", "difficile"),
      questions.tf("Une note CVSS élevée suffit à elle seule à prioriser un correctif sans regarder l’exposition ni l’actif concerné.", false, "Faux : CVSS exprime une gravité technique commune, mais la priorité dépend aussi de l’exposition réelle, du type d’actif, du contexte métier et de la facilité de correction ou de contournement. Sans ce contexte, le classement reste incomplet.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c4:9",
    position: 9,
    title: "Configuration, dépendances et défense",
    description: "Ce module t’apprend à durcir une application web au-delà du code métier : configuration, secrets, dépendances, pipeline et défense en profondeur. Critères de réussite : repérer une mauvaise configuration ou un secret mal placé ; classer une alerte de dépendance selon son exposition réelle ; expliquer ce qu’un WAF, une limitation de débit et de bons journaux apportent, sans les confondre avec un correctif.",
    lessons: [webConfigSecretsLesson, webDependancesLesson, webDevSecuriseLesson, webWafDetectionLesson],
  },
  {
    key: "c4:10",
    position: 10,
    title: "Auditer un site et rendre compte",
    description: "Tu y apprends à cadrer un audit, à le conduire avec méthode, puis à transformer les observations en rapport actionnable. Critères de réussite : vérifier un périmètre et des règles d’engagement avant tout test ; consigner des preuves reproductibles en distinguant lecture seule, hypothèse et conclusion ; rédiger un constat avec preuve, sévérité, recommandation et re-test.",
    lessons: [webCadreAuditLesson, webMethodeAuditLesson, webRapportRemediationLesson],
  },
];
