import {
  code,
  example,
  figure,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const accessControlLesson: NewLesson = {
  key: "web-controle-acces",
  title: "Contrôle d’accès : IDOR, élévation de privilèges et moindre privilège",
  summary: "Tu apprends à distinguer authentification et autorisation, à reconnaître un IDOR, puis à corriger un contrôle d’accès côté serveur sans te laisser tromper par une URL cachée ou un identifiant compliqué.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("distinguer authentification et autorisation, repérer un IDOR dans une route d’API, corriger un contrôle d’accès au niveau de l’objet et de la fonction, tester avec deux comptes, et reconnaître une énumération d’identifiants dans un journal."),
    prerequisites("avoir suivi les leçons sur les sessions et les jetons, et savoir lire une requête HTTP simple."),
    scenario("Fatou maintient l’application de commandes de la boutique Soleil. Un collègue lui dit que la page d’administration est « protégée » parce qu’elle n’apparaît dans aucun menu. En relisant l’API, Fatou voit aussi une route « /api/commandes/:id » qui renvoie une commande si l’on connaît son numéro. Elle doit prouver ce qui manque, le corriger côté serveur, puis vérifier avec deux comptes de test que l’utilisateur A ne lit pas les objets de l’utilisateur B."),
    videoSlot("Vérifier un contrôle d’accès sans confondre identité et droits"),
    text("S’authentifier, c’est prouver qui tu es. S’autoriser, c’est décider ce que tu as le droit de faire. Une application peut très bien reconnaître un utilisateur, puis lui donner trop de pouvoir sur une autre ressource. C’est pour cela que le contrôle d’accès reste la première famille du Top 10 OWASP 2025 : le serveur doit refuser par défaut, puis vérifier à chaque requête la fonction demandée et l’objet visé. Un lien caché, un bouton absent ou un champ désactivé dans le navigateur ne sont jamais des contrôles de sécurité."),
    figure({
      kind: "steps",
      title: "Relire une requête vers `/api/commandes/1042`",
      numbered: true,
      items: [
        { title: "Identifier l’utilisateur", text: "Qui appelle la route et avec quelle identité prouvée ?", icon: "user", tone: "cyan" },
        { title: "Vérifier le rôle", text: "La fonction demandée est-elle permise pour ce rôle ?", icon: "shield-check", tone: "blue" },
        { title: "Vérifier l’objet", text: "L’utilisateur a-t-il le droit sur l’objet `1042` ?", icon: "search", tone: "violet" },
        { title: "Décider", text: "Autoriser ou refuser côté serveur.", icon: "gavel", tone: "green" },
      ],
      caption: "Si l’étape 3 manque : IDOR ou BOLA. Si l’étape 2 manque : élévation de fonction.",
    }),
    text("Le cas classique s’appelle IDOR, ou BOLA dans le vocabulaire des API : l’application prend un identifiant contrôlé par l’utilisateur, comme « 1042 », puis retourne l’objet sans vérifier qu’il lui appartient. Une élévation horizontale laisse un utilisateur agir sur le compte d’un pair. Une élévation verticale laisse appeler une fonction réservée à l’administration. Les identifiants imprévisibles, comme les UUID, réduisent l’énumération mais ne remplacent jamais la règle principale : filtrer côté serveur par propriétaire, par rôle, ou par les deux."),
    text("Un autre piège fréquent est l’assignation en masse. Si ton API accepte tout le corps JSON tel quel, un champ « role » ou « isAdmin » peut être injecté par un client que tu ne maîtrises pas. Le remède est le même esprit : liste autorisée de champs, validation du type attendu, puis décision côté serveur. Tu testes toujours avec deux comptes réels de démonstration, pas seulement avec le compte administrateur qui peut masquer le défaut."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Ce script Node.js lance deux mini serveurs locaux sur « 127.0.0.1 ». Le premier est volontairement vulnérable : il renvoie une commande si l’identifiant existe. Le second ajoute le contrôle d’accès côté serveur. Tu peux le rejouer sur Windows avec Node.js puis « curl.exe ». Si ta version de Node.js est trop ancienne pour lancer le script, mets Node.js à jour puis rejoue la démonstration. Arrête-le ensuite avec « Ctrl+C »."),
    code([
      "# fichier demo-acces.cjs",
      "const http = require(\"node:http\");",
      "const commandes = [",
      "  { id: \"100\", owner: \"awa\", total: 7500 },",
      "  { id: \"101\", owner: \"awa\", total: 18000 },",
      "  { id: \"102\", owner: \"koffi\", total: 9500 },",
      "];",
      "",
      "function serveur(mode) {",
      "  return http.createServer((req, res) => {",
      "    const m = req.url.match(/^\\/api\\/commandes\\/(\\d+)$/);",
      "    if (!m) { res.writeHead(404).end(\"not found\"); return; }",
      "    const user = req.headers[\"x-user\"] || \"anonyme\";",
      "    const role = req.headers[\"x-role\"] || \"user\";",
      "    const commande = commandes.find((item) => item.id === m[1]);",
      "    if (!commande) { res.writeHead(404).end(\"absent\"); return; }",
      "    if (mode === \"corrige\" && role !== \"admin\" && commande.owner !== user) {",
      "      res.writeHead(403, { \"content-type\": \"application/json\" });",
      "      res.end(JSON.stringify({ error: \"forbidden\" }));",
      "      return;",
      "    }",
      "    res.writeHead(200, { \"content-type\": \"application/json\" });",
      "    res.end(JSON.stringify(commande));",
      "  });",
      "}",
      "",
      "serveur(\"vulnerable\").listen(8081, \"127.0.0.1\");",
      "serveur(\"corrige\").listen(8082, \"127.0.0.1\");",
      "console.log(\"8081 vulnerable, 8082 corrige\");",
    ].join("\n"), "javascript"),
    code([
      "# lancer le serveur de démonstration",
      "node demo-acces.cjs",
      "# exemple de sortie (valeurs fictives)",
      "# 8081 vulnerable, 8082 corrige",
      "",
      "# Awa lit la commande de Koffi sur le serveur vulnérable",
      "curl.exe -s -H \"X-User: awa\" http://127.0.0.1:8081/api/commandes/102",
      "# exemple de sortie (valeurs fictives)",
      "# {\"id\":\"102\",\"owner\":\"koffi\",\"total\":9500}",
      "",
      "# La même requête est refusée sur le serveur corrigé",
      "curl.exe -i -s -H \"X-User: awa\" http://127.0.0.1:8082/api/commandes/102",
      "# exemple de sortie (valeurs fictives)",
      "# HTTP/1.1 403 Forbidden",
      "# Content-Type: application/json",
      "# Date: Tue, 10 Mar 2026 09:15:00 GMT",
      "# Connection: keep-alive",
      "# Keep-Alive: timeout=5",
      "# Transfer-Encoding: chunked",
      "#",
      "# {\"error\":\"forbidden\"}",
      "",
      "# L’administratrice conserve l’accès",
      "curl.exe -s -H \"X-User: fatou\" -H \"X-Role: admin\" http://127.0.0.1:8082/api/commandes/102",
      "# exemple de sortie (valeurs fictives)",
      "# {\"id\":\"102\",\"owner\":\"koffi\",\"total\":9500}",
    ].join("\n"), "bash"),
    figure({
      kind: "timeline",
      title: "Journal inventé à relire",
      events: [
        { at: "09:15:01", title: "Awa lit `GET /api/commandes/100`", text: "réponse `200`", icon: "check", tone: "green" },
        { at: "09:15:02", title: "Awa lit `GET /api/commandes/101`", text: "réponse `200`", icon: "check", tone: "green" },
        { at: "09:15:03", title: "Awa tente `GET /api/commandes/102`", text: "réponse `403`", icon: "alert", tone: "amber" },
        { at: "09:15:04", title: "Awa tente `GET /api/commandes/103`", text: "réponse `403`", icon: "alert", tone: "amber" },
        { at: "09:15:05", title: "Awa tente `GET /api/commandes/104`", text: "réponse `403`", icon: "alert", tone: "red" },
      ],
      caption: "Même compte, IDs successifs : énumération probable.",
    }),
    example("Exemple corrigé : dans l’extrait ci-dessus, Awa demande cinq identifiants successifs. Deux réponses « 200 » concernent ses propres commandes, puis trois « 403 » arrivent d’affilée. Ce motif ne prouve pas une attaque à lui seul, mais il ressemble à une énumération d’objets. La bonne réaction est de vérifier si le client parcourait vraiment son propre historique, puis de confirmer que la route filtre bien sur « owner = utilisateur connecté » et que les refus sont journalisés sans renvoyer de détail sensible."),
    mistakes("croire qu’une URL non liée dans l’interface suffit à protéger une fonction ; vérifier le rôle sans vérifier l’objet demandé ; accepter un champ « role » ou « isAdmin » venu du client ; tester uniquement avec un compte administrateur, ce qui masque souvent l’IDOR."),
    safety("ne teste que ton application, ton environnement de démonstration local ou un périmètre autorisé par écrit. Les journaux d’accès et les exports de commandes peuvent contenir des données personnelles ou commerciales : ne les publie pas et ne les envoie pas à un service tiers sans nécessité."),
    takeaway("le contrôle d’accès vit côté serveur, à chaque requête. L’authentification ne suffit pas : il faut vérifier la fonction et l’objet. Un identifiant compliqué aide, mais il ne remplace jamais un filtrage par propriétaire, rôle et liste autorisée de champs."),
    practice("Travaille dans « TP 5 : contrôle d’accès, API et SSRF dans les journaux » : lis la matrice de droits, repère les accès à l’objet d’un autre utilisateur, puis relie-les au journal d’API avant de terminer par le quiz."),
    reference("owaspTop10A01"),
    reference("owaspCsAuthorization"),
    reference("owaspCsIdor"),
    reference("cwe639"),
    reference("owaspApiTop10"),
    reference("nodeHttp"),
  ],
  quiz: {
    title: "Quiz : contrôle d’accès",
    questions: [
      questions.choice("Quelle phrase décrit le mieux un IDOR sur « /api/commandes/102 » ?", ["Le serveur renvoie l’objet sans vérifier qu’il appartient à l’utilisateur connecté", "Le navigateur masque le bouton « supprimer »", "Le mot de passe de la base de données est trop court", "Le certificat HTTPS a expiré"], 0, "Un IDOR apparaît quand un identifiant contrôlé par le client suffit à lire ou modifier l’objet d’un autre. Le piège tentant est l’interface cachée : un bouton absent n’empêche jamais un appel direct à l’API.", "facile"),
      questions.choice("Pourquoi un UUID ne suffit-il pas à corriger un contrôle d’accès ?", ["Parce qu’un UUID casse toujours les journaux", "Parce qu’il réduit l’énumération, mais ne vérifie ni le propriétaire ni le rôle", "Parce qu’il oblige à désactiver HTTPS", "Parce qu’il empêche les sauvegardes"], 1, "Un identifiant moins prévisible rend l’exploration plus difficile, mais il ne décide jamais à lui seul qui a le droit d’accéder à l’objet. Sans vérification côté serveur, le défaut logique reste présent.", "moyen"),
      questions.multi("Lis ce corps JSON reçu par l’API : « {\"nom\":\"Awa\",\"role\":\"admin\",\"newsletter\":true} ». Quelles réponses défensives sont justes ? (plusieurs réponses)", ["Accepter tous les champs, puis cacher « role » dans l’interface", "Construire une liste autorisée de champs modifiables", "Décider du rôle côté serveur, sans faire confiance au champ envoyé", "Remplacer le mot « admin » par « utilisateur » dans le navigateur"], [1, 2], "La défense consiste à limiter explicitement les champs acceptés et à décider du rôle côté serveur. Cacher ou réécrire la valeur côté client ne change rien : le client reste contrôlé par l’utilisateur ou par un script.", "difficile"),
      questions.tf("Une route d’administration sans lien visible dans le menu reste une route d’administration publique tant que le serveur ne contrôle pas les droits.", true, "Vrai : l’absence de lien ne protège rien. Un utilisateur peut taper l’URL, suivre un favori, ou appeler directement l’API avec « curl ». Le serveur doit donc refuser explicitement les rôles non autorisés.", "moyen"),
    ],
  },
};

const csrfLesson: NewLesson = {
  key: "web-csrf",
  title: "CSRF : une requête que l’utilisateur n’a pas voulue, et ses défenses",
  summary: "Tu comprends comment un navigateur joint automatiquement les cookies, pourquoi cela ouvre la porte au CSRF, puis comment combiner SameSite, jeton anti-CSRF et contrôles d’origine sans te raconter d’histoire.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("expliquer le mécanisme du CSRF, reconnaître les conditions qui rendent une requête falsifiable, générer et vérifier un jeton anti-CSRF lié à une session, distinguer cookie et jeton Bearer, et interpréter un journal montrant une origine inattendue."),
    prerequisites("connaître les cookies de session et savoir qu’un navigateur peut envoyer automatiquement des en-têtes à un site déjà ouvert."),
    scenario("Ama gère un espace adhérents pour l’association Teranga. Un formulaire permet de changer l’adresse de livraison et l’application utilise un cookie de session classique. Un jour, l’équipe découvre des modifications inattendues alors qu’aucun mot de passe n’a été volé. Ama doit comprendre comment un autre site peut déclencher une requête au nom d’un utilisateur déjà connecté, puis ajouter plusieurs barrières au bon endroit."),
    videoSlot("Bloquer un CSRF sans casser les formulaires légitimes"),
    text("Le CSRF, ou falsification de requête intersite, exploite un fait simple : le navigateur joint automatiquement les cookies associés au site cible. Si la victime est déjà connectée, une page tierce peut lui faire envoyer une requête qu’elle n’avait pas l’intention d’envoyer. La politique de même origine ne bloque pas cet envoi : elle bloque surtout la lecture de la réponse par le script tiers. C’est pourquoi un formulaire de changement d’adresse ou de mot de passe reste sensible tant qu’il modifie l’état avec un simple cookie de session et sans secret supplémentaire."),
    figure({
      kind: "steps",
      title: "Chaîne d’un CSRF classique",
      numbered: true,
      items: [
        { title: "1. Session ouverte", text: "La victime est connectée à `boutique.example`.", icon: "user-check", tone: "cyan" },
        { title: "2. Cookie gardé", text: "Le navigateur conserve un cookie de session.", icon: "file-lock", tone: "blue" },
        { title: "3. Site piégé", text: "La victime ouvre aussi une page contrôlée par l’attaquant.", icon: "skull", tone: "red" },
        { title: "4. Requête déclenchée", text: "Ce site provoque une requête vers `boutique.example`.", icon: "send", tone: "violet" },
        { title: "5. Cookie joint", text: "Le navigateur renvoie le cookie automatiquement.", icon: "refresh", tone: "amber" },
        { title: "6. Action acceptée", text: "Sans défense, le serveur croit à une action voulue.", icon: "alert", tone: "red" },
      ],
    }),
    text("Pour qu’un CSRF réussisse, il faut en général une session ouverte, une requête prévisible et une action qui change l’état sans vérifier un secret supplémentaire. Un « GET » qui supprime, valide ou paye quelque chose est donc une très mauvaise idée. Les défenses utiles se complètent : « SameSite=Lax » ou « Strict » réduit les envois automatiques de cookies, mais ne remplace pas un jeton anti-CSRF. Le serveur peut aussi vérifier « Origin » et les en-têtes « Sec-Fetch-Site », puis exiger un en-tête personnalisé pour les appels AJAX légitimes."),
    text("Une API protégée par « Authorization: Bearer <jeton> » n’est pas touchée de la même manière, car le navigateur n’ajoute pas tout seul ce jeton dans l’en-tête. En revanche, une API consommée depuis le navigateur avec un cookie de session reste concernée. Et rappelle-toi la limite importante : une faille XSS peut contourner les protections CSRF en agissant depuis l’origine légitime. Le CSRF se traite donc avec les sessions, mais aussi avec l’hygiène XSS."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Ce script Node.js fabrique une session et un jeton aléatoire, puis vérifie le jeton reçu avec « timingSafeEqual ». Le secret n’est jamais déduit du navigateur : il est généré côté serveur et stocké avec la session. Si ta version de Node.js est trop ancienne pour lancer le script, mets Node.js à jour puis rejoue la démonstration. La comparaison en temps constant évite une comparaison naïve qui pourrait fuir des informations."),
    code([
      "# fichier demo-csrf.cjs",
      "const crypto = require(\"node:crypto\");",
      "",
      "const sessionId = crypto.randomBytes(8).toString(\"hex\");",
      "const csrfToken = crypto.randomBytes(16).toString(\"hex\");",
      "const sessionStore = new Map([[sessionId, { csrfToken }]]);",
      "",
      "function verifier(sessionIdRecu, tokenRecu) {",
      "  const session = sessionStore.get(sessionIdRecu);",
      "  if (!session || typeof tokenRecu !== \"string\") return false;",
      "  const attendu = Buffer.from(session.csrfToken, \"utf8\");",
      "  const recu = Buffer.from(tokenRecu, \"utf8\");",
      "  if (attendu.length !== recu.length) return false;",
      "  return crypto.timingSafeEqual(attendu, recu);",
      "}",
      "",
      "console.log({ sessionId, csrfToken });",
      "console.log(\"valide\", verifier(sessionId, csrfToken));",
      "const tokenModifie = csrfToken.endsWith(\"0\") ? csrfToken.slice(0, -1) + \"1\" : csrfToken.slice(0, -1) + \"0\";",
      "console.log(\"modifie\", verifier(sessionId, tokenModifie));",
      "console.log(\"autre session\", verifier(\"session-inconnue\", csrfToken));",
    ].join("\n"), "javascript"),
    code([
      "# lancer la démonstration",
      "node demo-csrf.cjs",
      "# exemple de sortie (valeurs fictives)",
      "# { sessionId: 'b54f4f9d2c13a88c', csrfToken: '2f8f5b8f5f4c4c3f5a5d13d9a8ff4a20' }",
      "# valide true",
      "# modifie false",
      "# autre session false",
    ].join("\n"), "bash"),
    figure({
      kind: "timeline",
      title: "Extrait inventé de journal",
      events: [
        { at: "09:15:00", title: "`POST /profil/adresse`", text: "`200`, `Origin: https://boutique.example`", icon: "check", tone: "green" },
        { at: "09:17:42", title: "`POST /profil/adresse`", text: "`200`, `Referer: https://cadeaux.example/promo`", icon: "alert", tone: "red" },
      ],
      caption: "Même action sensible, mais deuxième origine inattendue.",
    }),
    example("Exemple corrigé : si une requête « POST /profil/adresse » arrive avec un cookie valide mais sans jeton anti-CSRF, puis porte un « Referer » ou un « Origin » étranger au domaine attendu, tu ne conclus pas seulement à un clic maladroit. Tu vérifies d’abord si le formulaire exige un jeton synchronisé, si « SameSite » est bien réglé, puis si l’action pouvait encore être déclenchée par un « GET ». Le bon correctif combine au minimum une méthode non sûre adaptée, un jeton lié à la session et un contrôle d’origine."),
    mistakes("croire que « SameSite » suffit toujours à lui seul ; modifier l’état avec « GET » parce que c’est plus simple à relire ; oublier que les formulaires classiques et les appels AJAX n’ont pas les mêmes signaux ; penser qu’un jeton Bearer placé dans « Authorization » est joint automatiquement comme un cookie."),
    safety("n’essaie pas de rejouer un CSRF sur un service qui n’est pas le tien. Travaille sur un formulaire de démonstration local, sur ton propre site ou dans un cadre autorisé par écrit. Les journaux de profils, d’achats ou de formulaires contiennent souvent des données personnelles : garde-les en interne."),
    takeaway("le CSRF existe parce que le navigateur joint les cookies automatiquement. Une défense sérieuse combine « SameSite », un jeton anti-CSRF, des méthodes HTTP cohérentes et un contrôle d’origine. Et si une XSS existe, elle peut contourner ces barrières."),
    practice("Travaille dans « TP 5 : contrôle d’accès, API et SSRF dans les journaux » : ce TP ne rejoue pas de CSRF, mais il te fait lire des journaux et une matrice de droits pour reconnaître une action sensible qui manque de garde-fous, puis terminer par le quiz."),
    reference("mdnSameOrigin"),
    reference("mdnSetCookie"),
    reference("owaspCsrfAttack"),
    reference("cwe352"),
    reference("mdnSecFetchSite"),
    reference("nodeCrypto"),
  ],
  quiz: {
    title: "Quiz : CSRF",
    questions: [
      questions.choice("Quelle condition rend un formulaire particulièrement sensible au CSRF ?", ["Il modifie l’état avec un cookie de session, sans secret supplémentaire", "Il utilise du CSS externe", "Il renvoie un code 404", "Il stocke les journaux sur le serveur"], 0, "Le risque apparaît quand le navigateur peut joindre automatiquement le cookie et que l’application ne vérifie rien d’autre. Le faux ami tentant est le CSS : il ne décide pas de l’autorisation de la requête.", "facile"),
      questions.choice("Pourquoi une API appelée avec « Authorization: Bearer <jeton> » n’est-elle pas touchée de la même façon ?", ["Parce que le navigateur ajoute toujours ce jeton automatiquement", "Parce que l’en-tête « Authorization » doit être ajouté par le code client, pas par le navigateur à ton insu", "Parce qu’un jeton Bearer implique forcément HTTPS", "Parce qu’elle interdit tous les formulaires"], 1, "Un jeton Bearer n’est pas envoyé automatiquement comme un cookie de session. Le risque peut revenir si l’application utilise quand même un cookie, mais le mécanisme de base du CSRF classique dépend justement de cet envoi automatique.", "moyen"),
      questions.multi("Tu relis la ligne « POST /virement 200 Origin: https://promo.example ». Quelles vérifications défensives sont pertinentes ? (plusieurs réponses)", ["Vérifier si l’action exige un jeton anti-CSRF lié à la session", "Vérifier la politique « SameSite » du cookie", "Considérer que le code 200 prouve l’absence de problème", "Contrôler si « GET » modifie aussi le même état"], [0, 1, 3], "Le code 200 ne dit rien sur la légitimité de la requête. Une origine externe, un cookie mal réglé et une action modifiable par « GET » forment justement le trio qu’il faut contrôler avant de conclure.", "difficile"),
      questions.tf("Une faille XSS peut contourner des protections CSRF, même si le jeton et « SameSite » existent.", true, "Vrai : un script exécuté dans l’origine légitime peut lire la page, déclencher les actions autorisées et parfois récupérer les jetons présents dans le DOM. C’est pourquoi le CSRF se traite avec les sessions, mais aussi avec une bonne défense contre le XSS.", "moyen"),
    ],
  },
};

const corsLesson: NewLesson = {
  key: "web-cors",
  title: "CORS : partager entre origines sans ouvrir la porte",
  summary: "Tu comprends quand le navigateur déclenche une pré-requête CORS, pourquoi « * » et les cookies ne vont pas ensemble, puis comment écrire une liste d’origines exacte au lieu de refléter tout ce qui arrive.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("rappeler ce qu’est une origine web, distinguer requête simple et pré-requête CORS, interpréter les en-têtes « Access-Control-* », tester une liste d’origines exacte, et expliquer pourquoi CORS ne protège pas le serveur contre un client hors navigateur."),
    prerequisites("avoir compris la politique de même origine et savoir lire une requête HTTP avec ses en-têtes."),
    scenario("Koffi ouvre une API pour une application frontale et voit vite arriver la demande classique : « mets juste Access-Control-Allow-Origin: * pour que tout marche ». L’API utilise pourtant aussi des cookies de session pour le back-office. Koffi doit partager ce qu’il faut avec l’application officielle, sans transformer le navigateur en passe-partout pour des origines qu’il ne contrôle pas."),
    videoSlot("Configurer CORS proprement sans refléter toutes les origines"),
    text("Une origine web est définie par le schéma, l’hôte et le port. « https://app.example.org » et « https://app.example.org:8443 » sont donc deux origines différentes. La politique de même origine empêche un script chargé depuis une origine de lire librement les réponses d’une autre. CORS est un assouplissement contrôlé de cette règle : le serveur dit au navigateur quelles origines peuvent lire la réponse, avec quels en-têtes et quelles méthodes."),
    figure({
      kind: "compare",
      title: "Deux chemins CORS selon le type de requête",
      sides: [
        {
          title: "Requête simple",
          tone: "green",
          icon: "globe",
          items: [
            "Navigateur sur `https://app.example.org`",
            "`GET` simple vers `https://api.example.org`",
            "La réponse annonce `Access-Control-Allow-Origin`",
          ],
        },
        {
          title: "Requête non simple",
          tone: "amber",
          icon: "refresh",
          items: [
            "Le navigateur envoie d’abord `OPTIONS`",
            "`Access-Control-Request-Method` précise la méthode visée",
            "`Access-Control-Request-Headers` annonce les en-têtes non simples",
          ],
        },
      ],
    }),
    text("Une requête simple, comme un « GET » sans en-tête exotique, part directement. Une requête avec « Content-Type: application/json » ou un en-tête personnalisé déclenche souvent une pré-requête « OPTIONS ». Le navigateur demande alors si la méthode et les en-têtes sont autorisés. Le serveur répond avec « Access-Control-Allow-Origin », « Access-Control-Allow-Methods » et, si besoin, « Access-Control-Allow-Headers ». Quand la réponse varie selon l’origine, ajoute aussi « Vary: Origin » pour éviter un cache trompeur."),
    text("Le piège le plus grave est de refléter l’origine reçue sans la vérifier. Un autre piège est d’accepter « null », origine que l’on retrouve avec certains contextes locaux, des documents isolés ou des schémas comme « file: », ou d’écrire une expression trop large comme « example.com » qui laisse passer « example.com.attaquant.example ». Enfin, retiens la règle pratique essentielle : « Access-Control-Allow-Credentials: true » ne peut pas être combiné avec « * ». Si des cookies ou d’autres informations d’authentification voyagent, la réponse doit viser une origine exacte."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Cette fonction Node.js applique une liste d’origines exactes. Elle refuse les pièges fréquents, comme le mauvais schéma, le bon domaine en suffixe, ou la chaîne littérale « null ». Tu peux la rejouer telle quelle avec Node.js avant de la traduire dans ton application. Si ta version de Node.js est trop ancienne pour lancer le script, mets Node.js à jour puis rejoue la démonstration."),
    code([
      "# fichier demo-cors.cjs",
      "const autorisees = new Set([",
      "  \"https://app.example.org\",",
      "  \"https://admin.example.org\",",
      "]);",
      "",
      "function originAutorisee(origin) {",
      "  if (typeof origin !== \"string\") return false;",
      "  if (origin === \"null\") return false;",
      "  return autorisees.has(origin);",
      "}",
      "",
      "const tests = [",
      "  \"https://app.example.org\",",
      "  \"https://admin.example.org\",",
      "  \"http://app.example.org\",",
      "  \"https://app.example.org:8443\",",
      "  \"https://example.org\",",
      "  \"https://app.example.org.attaquant.example\",",
      "  \"null\",",
      "  undefined,",
      "];",
      "",
      "for (const valeur of tests) {",
      "  console.log(String(valeur), originAutorisee(valeur));",
      "}",
    ].join("\n"), "javascript"),
    code([
      "# lancer la démonstration",
      "node demo-cors.cjs",
      "# exemple de sortie (valeurs fictives)",
      "# https://app.example.org true",
      "# https://admin.example.org true",
      "# http://app.example.org false",
      "# https://app.example.org:8443 false",
      "# https://example.org false",
      "# https://app.example.org.attaquant.example false",
      "# null false",
      "# undefined false",
    ].join("\n"), "bash"),
    figure({
      kind: "table",
      title: "Configuration saine pour un front officiel",
      columns: ["En-tête", "Valeur"],
      rows: [
        ["Access-Control-Allow-Origin", "https://app.example.org"],
        ["Access-Control-Allow-Credentials", "true"],
        ["Access-Control-Allow-Methods", "GET, POST"],
        ["Access-Control-Allow-Headers", "Content-Type, X-CSRF-Token"],
        ["Vary", "Origin"],
      ],
      mono: [0, 1],
    }),
    example("Exemple corrigé : si ton back-office envoie des cookies et que tu réponds « Access-Control-Allow-Origin: * », le navigateur refusera de toute façon les réponses avec « credentials ». La bonne correction n’est pas de supprimer les cookies au hasard, mais de lister précisément « https://admin.example.org » et « https://app.example.org », puis de refuser tout le reste. CORS aide le navigateur à lire une réponse : il ne remplace ni l’authentification ni le contrôle d’accès de l’API."),
    mistakes("confondre CORS avec une protection du serveur contre tous les clients ; refléter l’origine reçue sans liste autorisée ; oublier « Vary: Origin » quand la réponse dépend de l’origine ; croire que « * » fonctionne encore avec les cookies et « Allow-Credentials: true »."),
    safety("ne teste les en-têtes CORS que sur ton site, ton API locale ou un périmètre autorisé. Un client hors navigateur ignore CORS : ne révèle donc jamais plus de données que ce que ton contrôle d’accès serveur permet réellement."),
    takeaway("CORS indique au navigateur qui peut lire une réponse. Il ne décide pas qui peut appeler ton API. Si des cookies sont en jeu, vise une origine exacte, ajoute « Vary: Origin » et refuse la tentation du reflet automatique."),
    practice("Travaille dans « TP 5 : contrôle d’accès, API et SSRF dans les journaux » : ce TP ne rejoue pas de pré-requête CORS complète, mais il te fait relire une matrice de droits et des journaux d’API pour distinguer partage légitime entre origines et ouverture trop large, puis terminer par le quiz."),
    reference("mdnCors"),
    reference("mdnAcao"),
    reference("rfc6454"),
  ],
  quiz: {
    title: "Quiz : CORS",
    questions: [
      questions.choice("Que contrôle CORS dans le navigateur ?", ["La lecture d’une réponse d’une autre origine par un script", "La création des comptes en base", "Le chiffrement TLS entre deux serveurs", "La rotation des journaux d’accès"], 0, "CORS encadre surtout la lecture des réponses cross-origin par le navigateur. Le faux ami classique est de lui attribuer une protection serveur générale, alors qu’un client hors navigateur peut ignorer complètement ces règles.", "facile"),
      questions.choice("Pourquoi « Access-Control-Allow-Credentials: true » ne va-t-il pas avec « Access-Control-Allow-Origin: * » ?", ["Parce que le joker n’existe plus en HTTP/1.1", "Parce que le navigateur exige une origine explicite quand des cookies ou d’autres informations d’authentification sont autorisés", "Parce que cela désactive automatiquement HTTPS", "Parce que cela force la méthode OPTIONS"], 1, "Quand des informations d’authentification entrent en jeu, le navigateur veut une origine précise, pas un joker. Le piège tentant est de croire que la combinaison reste valide si l’on ajoute simplement plus d’en-têtes.", "moyen"),
      questions.multi("Quelles origines doivent être refusées par une liste exacte contenant seulement « https://app.example.org » ? (plusieurs réponses)", ["https://app.example.org.attaquant.example", "http://app.example.org", "https://app.example.org", "https://app.example.org:8443"], [0, 1, 3], "Le bon domaine ne suffit pas : le schéma et le port font partie de l’origine, et un suffixe piégé ne vaut jamais l’origine exacte. Seule la chaîne strictement prévue doit passer.", "difficile"),
      questions.tf("Une API bien configurée en CORS reste vulnérable si son contrôle d’accès côté serveur accepte des objets ou des fonctions non autorisés.", true, "Vrai : CORS ne remplace ni l’authentification ni l’autorisation. Si le serveur rend des données à un client non autorisé, le défaut existe déjà, même si le navigateur bloque ensuite une partie des lectures cross-origin.", "moyen"),
    ],
  },
};

const uploadLesson: NewLesson = {
  key: "web-upload-fichiers",
  title: "Téléversement de fichiers et traversée de chemin",
  summary: "Tu apprends à traiter un téléversement comme une chaîne de contrôles, puis à bloquer une traversée de chemin en validant à la fois le contenu réel, le nom servi et le chemin canonique.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("énumérer les risques du téléversement de fichiers, vérifier un type réel par signature simple, corriger une traversée de chemin avec un chemin canonique, choisir un stockage non exécutable, et interpréter un journal montrant des « ../ » ou des encodages suspects."),
    prerequisites("savoir lire un chemin de fichier et connaître les bases des requêtes HTTP avec un corps de formulaire."),
    scenario("Moussa ajoute un envoi de justificatifs pour une application associative. Le client lui fournit un nom de fichier et un « Content-Type », puis le produit veut aussi un téléchargement des pièces déjà déposées. Moussa doit empêcher trois classes de problèmes à la fois : téléverser un contenu actif, écraser un fichier existant, ou demander un autre chemin que celui prévu pour la ressource."),
    videoSlot("Accepter un fichier sans lui faire confiance"),
    text("Un téléversement n’est jamais « juste un fichier ». C’est une donnée non fiable qui peut chercher à faire exécuter du code, à consommer le disque, à tromper ton application sur son type réel ou à viser un autre chemin que celui prévu. La défense se fait en couches : taille maximale, extension en liste autorisée, signature du fichier, renommage aléatoire, stockage hors de la racine web ou dans un stockage objet sans exécution, puis service avec « Content-Disposition » et « X-Content-Type-Options: nosniff ». Le « Content-Type » envoyé par le client est utile comme indice, jamais comme preuve."),
    figure({
      kind: "steps",
      title: "Chaîne de contrôle d’un téléversement",
      items: [
        { title: "Taille", text: "Vérifier que la taille reste acceptable.", icon: "gauge", tone: "cyan" },
        { title: "Extension", text: "N’accepter qu’une liste autorisée.", icon: "file", tone: "blue" },
        { title: "Signature", text: "Contrôler que le contenu réel est cohérent.", icon: "file-search", tone: "violet" },
        { title: "Nom interne", text: "Remplacer le nom par un identifiant côté serveur.", icon: "hash", tone: "green" },
        { title: "Stockage", text: "Conserver le fichier hors exécution.", icon: "hard-drive", tone: "amber" },
        { title: "Service", text: "Servir avec `Content-Disposition` et `nosniff`.", icon: "download", tone: "green" },
      ],
    }),
    text("La traversée de chemin est un défaut voisin. Si ton application construit un chemin avec une entrée utilisateur, « ../ », « ..%2f » ou un séparateur inattendu peuvent sortir du dossier prévu. Le bon réflexe est d’éviter autant que possible les chemins libres, puis de résoudre le chemin canonique et de vérifier qu’il reste sous le dossier autorisé. Cette idée vaut aussi pour l’extraction d’archives : un fichier interne nommé « ../../webroot/index.js » peut écrire hors du répertoire d’arrivée si tu ne normalises pas."),
    text("Démonstration guidée : vérifie d’abord « node --version ». La fonction suivante bloque un chemin qui sort du dossier prévu, puis reconnaît trois signatures simples : PNG, JPEG et PDF. La logique ne remplace pas un antivirus ni une bibliothèque spécialisée, mais elle montre les deux réflexes incontournables : ne pas faire confiance au nom demandé, et ne pas faire confiance au type déclaré. Si ta version de Node.js est trop ancienne pour lancer le script, mets Node.js à jour puis rejoue la démonstration."),
    code([
      "# fichier demo-upload.cjs",
      "const path = require(\"node:path\");",
      "",
      "function cheminSur(base, demande) {",
      "  const baseCanonique = path.resolve(base);",
      "  const cible = path.resolve(baseCanonique, demande);",
      "  const prefixe = baseCanonique + path.sep;",
      "  return cible === baseCanonique || cible.startsWith(prefixe);",
      "}",
      "",
      "function signature(buffer) {",
      "  if (buffer.slice(0, 8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]))) return \"png\";",
      "  if (buffer.slice(0, 3).equals(Buffer.from([0xff,0xd8,0xff]))) return \"jpeg\";",
      "  if (buffer.slice(0, 5).toString(\"ascii\") === \"%PDF-\") return \"pdf\";",
      "  return \"inconnu\";",
      "}",
      "",
      "const base = path.join(\"C:\\\\\", \"uploads-demo\");",
      "for (const demande of [\"photo.png\", \"docs/rapport.pdf\", \"../secret.txt\", \"..\\\\windows.ini\", \"images/../../config.json\", \".\"]) {",
      "  console.log(demande, cheminSur(base, demande));",
      "}",
      "",
      "console.log(signature(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00])));",
      "console.log(signature(Buffer.from([0xff,0xd8,0xff,0xe0,0x00])));",
      "console.log(signature(Buffer.from(\"%PDF-1.7\\n\", \"ascii\")));",
      "console.log(signature(Buffer.from(\"MZ....\", \"ascii\")));",
    ].join("\n"), "javascript"),
    code([
      "# lancer la démonstration",
      "node demo-upload.cjs",
      "# exemple de sortie (valeurs fictives)",
      "# photo.png true",
      "# docs/rapport.pdf true",
      "# ../secret.txt false",
      "# ..\\windows.ini false",
      "# images/../../config.json false",
      "# . true",
      "# png",
      "# jpeg",
      "# pdf",
      "# inconnu",
    ].join("\n"), "bash"),
    figure({
      kind: "timeline",
      title: "Journal inventé à relire",
      events: [
        { at: "09:15:00", title: "`GET /fichiers/rapport.pdf`", text: "réponse `200`", icon: "file", tone: "green" },
        { at: "09:15:05", title: "`GET /fichiers/../../config.json`", text: "réponse `400`", icon: "alert", tone: "red" },
        { at: "09:15:06", title: "`GET /fichiers/%2e%2e%2fsecret.txt`", text: "réponse `400`", icon: "alert", tone: "red" },
        { at: "09:15:08", title: "`POST /upload`", text: "`Content-Type: image/png`, réponse `415`", icon: "upload", tone: "amber" },
      ],
      caption: "Le type annoncé et le chemin demandé ne suffisent pas.",
    }),
    example("Exemple corrigé : dans ce journal, deux lectures essaient de sortir du dossier prévu avec « ../ » et « %2e%2e%2f ». Une autre envoie « Content-Type: image/png » mais finit en « 415 », signe que le serveur n’a pas cru le type annoncé. Le bon comportement est précisément celui-là : vérifier le contenu réel, renommer le fichier côté serveur, puis servir ensuite la pièce avec un nom contrôlé et un type fixé par le serveur, pas par le client."),
    mistakes("faire confiance au seul « Content-Type » envoyé par le client ; conserver le nom fourni comme nom de stockage interne ; servir un téléversement directement depuis une zone exécutable ; normaliser le chemin après avoir déjà tenté d’ouvrir le fichier."),
    safety("ne manipule que des fichiers de démonstration sur ta propre machine ou dans un environnement autorisé. Un téléversement peut contenir des données personnelles, des pièces d’identité ou des documents métier : ne les envoie pas à un service tiers pour « vérifier le type » si ce n’est pas nécessaire et encadré."),
    takeaway("un téléversement sûr additionne des couches : taille, extension, signature, renommage, stockage non exécutable et service contrôlé. Pour les chemins, le mot d’ordre est simple : résoudre, vérifier, puis seulement accéder au fichier."),
    practice("Travaille dans « TP 5 : contrôle d’accès, API et SSRF dans les journaux » : repère les tentatives de traversée de chemin et les téléchargements suspects dans les traces fournies, puis relie-les à la logique de validation avant de terminer par le quiz."),
    reference("owaspCsFileUpload"),
    reference("cwe434"),
    reference("cwe22"),
    reference("mdnNosniff"),
  ],
  quiz: {
    title: "Quiz : téléversement et chemins",
    questions: [
      questions.choice("Pourquoi le « Content-Type » envoyé par le client ne suffit-il pas ?", ["Parce qu’il peut être falsifié et ne prouve pas le contenu réel du fichier", "Parce qu’il est chiffré par TLS", "Parce qu’il change le propriétaire du fichier", "Parce qu’il désactive le stockage objet"], 0, "Le client peut annoncer n’importe quel type MIME. La défense doit donc regarder aussi la signature du fichier et décider côté serveur. Le faux ami fréquent consiste à croire que le navigateur ou TLS garantit l’honnêteté de cette valeur.", "facile"),
      questions.choice("Quel réflexe corrige le mieux une traversée de chemin ?", ["Remplacer « .. » par une chaîne vide dans le navigateur", "Résoudre le chemin canonique, puis vérifier qu’il reste sous le dossier autorisé", "Renommer le serveur pour cacher l’arborescence", "Accepter seulement les fichiers qui finissent par « .txt »"], 1, "Le contrôle sérieux se fait côté serveur sur le chemin résolu, car l’encodage, les séparateurs et les sous-dossiers peuvent tromper un simple remplacement de chaîne. L’extension seule ne protège pas contre un chemin qui sort du dossier prévu.", "moyen"),
      questions.multi("Tu relis les demandes « ../secret.txt », « docs/rapport.pdf » et « %2e%2e%2fconfig.json ». Quelles décisions sont justes ? (plusieurs réponses)", ["Refuser « ../secret.txt »", "Accepter « docs/rapport.pdf » si le reste des contrôles réussit", "Accepter « %2e%2e%2fconfig.json » car il n’y a pas de slash visible", "Normaliser l’entrée avant de décider"], [0, 1, 3], "Les deux formes de traversée doivent être refusées, même quand elles sont encodées. Le bon raisonnement consiste à normaliser puis vérifier le chemin canonique. Le piège tentant est précisément l’encodage qui masque visuellement le « ../ ».", "difficile"),
      questions.tf("Servir un téléversement avec « Content-Disposition: attachment » et « X-Content-Type-Options: nosniff » réduit le risque d’exécution inattendue côté navigateur.", true, "Vrai : ces en-têtes n’effacent pas tous les risques, mais ils limitent les interprétations dangereuses par le navigateur et poussent l’ouverture comme pièce jointe plutôt que comme contenu actif intégré.", "moyen"),
    ],
  },
};

const ssrfXxeLesson: NewLesson = {
  key: "web-ssrf-xxe",
  title: "SSRF, XXE et désérialisation : quand le serveur fait ce qu’on lui souffle",
  summary: "Tu apprends à reconnaître une SSRF, à limiter les destinations qu’un serveur peut appeler, puis à éviter les pièges voisins que sont les entités XML externes et la désérialisation d’objets non fiables.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("décrire une SSRF avec ses cibles internes, refuser des destinations locales ou privées dans une fonction Node.js, expliquer pourquoi les redirections et la résolution DNS comptent, résumer le risque XXE, et distinguer JSON validé d’une désérialisation d’objet dangereuse."),
    prerequisites("savoir qu’un serveur peut appeler d’autres services HTTP et connaître la différence entre une URL et une adresse IP."),
    scenario("Awa ajoute un aperçu d’image à partir d’une URL dans une petite API. Le produit veut aussi un import XML hérité d’un ancien partenaire. Pendant la revue, Awa réalise qu’un serveur qui « va chercher pour toi » peut atteindre des endroits invisibles depuis l’extérieur : un service local, une adresse de métadonnées ou un outil d’administration interne. Elle doit donc fermer les destinations dangereuses, puis empêcher qu’un XML ou un objet sérialisé ne pilote plus que prévu."),
    videoSlot("Limiter ce qu’un serveur a le droit d’aller chercher"),
    text("Une SSRF, ou falsification de requête côté serveur, apparaît quand l’application récupère une URL choisie par l’utilisateur. Le problème n’est pas seulement l’Internet public : le serveur peut souvent joindre « 127.0.0.1 », des plages privées, une adresse locale de lien comme « 169.254.169.254 », ou des services d’administration internes invisibles pour le navigateur. C’est pour cela qu’une fonction « importe cette image » ou « vérifie ce webhook » mérite le même sérieux qu’un accès base de données."),
    figure({
      kind: "network",
      title: "SSRF : ce que le serveur peut atteindre",
      cols: 4,
      rows: 3,
      nodes: [
        { id: "user", label: "Utilisateur", sub: "fournit une URL", icon: "user", col: 0, row: 1, tone: "cyan" },
        { id: "app", label: "Serveur applicatif", icon: "server", col: 1.5, row: 1, tone: "blue" },
        { id: "public", label: "Internet public", sub: "attendu", icon: "internet", col: 3, row: 0, tone: "green" },
        { id: "local", label: "localhost", sub: "à refuser", icon: "home", col: 3, row: 1, tone: "red" },
        { id: "private", label: "Réseau privé", sub: "à refuser", icon: "network", col: 3, row: 1.5, tone: "red" },
        { id: "meta", label: "Métadonnées cloud", sub: "à refuser", icon: "cloud", col: 3, row: 2, tone: "red" },
      ],
      links: [
        { from: "user", to: "app", label: "URL fournie", arrow: "to" },
        { from: "app", to: "public", label: "appel attendu", arrow: "to", tone: "green" },
        { from: "app", to: "local", label: "bloquer", arrow: "to", tone: "red" },
        { from: "app", to: "private", label: "bloquer", arrow: "to", tone: "red" },
        { from: "app", to: "meta", label: "bloquer", arrow: "to", tone: "red" },
      ],
    }),
    text("La défense la plus sûre est une liste autorisée de destinations exactes ou de domaines métier connus. Ensuite, il faut revalider après la résolution DNS et après chaque redirection, car un nom apparemment bénin peut finir sur une adresse privée. Le schéma compte aussi : « https » seulement dans beaucoup de cas, pas de « file: », pas de « gopher: ». Et même après ces filtres, la segmentation réseau et le moindre privilège de la machine restent importants, car un défaut de validation n’est jamais impossible."),
    text("Le risque XXE est voisin par sa logique : un analyseur XML mal réglé peut résoudre des entités externes et lire un fichier local ou appeler une URL. La réponse moderne est simple : désactiver les DTD et les entités externes, puis préférer JSON quand le protocole le permet. Pour la désérialisation, le principe défensif est le même : un objet natif venu du client n’est pas une simple donnée, c’est parfois du comportement emballé. Choisis donc JSON, valide-le par schéma, puis reconstruis toi-même les structures autorisées."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Cette fonction Node.js choisit une politique volontairement stricte. Elle n’accepte que « https » et deux hôtes autorisés. Toutes les adresses IP littérales sont refusées, y compris les adresses locales ou privées. En production, une application qui doit accepter plus large revalide aussi l’adresse obtenue après la résolution DNS et chaque redirection. Si ta version de Node.js est trop ancienne pour lancer le script, mets Node.js à jour puis rejoue la démonstration."),
    code([
      "# fichier demo-ssrf.cjs",
      "const net = require(\"node:net\");",
      "const { URL } = require(\"node:url\");",
      "",
      "const autorises = new Set([\"api.example.org\", \"cdn.example.org\"]);",
      "",
      "function destinationAutorisee(valeur) {",
      "  let url;",
      "  try { url = new URL(valeur); } catch { return false; }",
      "  if (url.protocol !== \"https:\") return false;",
      "  const host = url.hostname.replace(/^\\[|\\]$/g, \"\");",
      "  if (net.isIP(host)) return false;",
      "  return autorises.has(host);",
      "}",
      "",
      "for (const valeur of [",
      "  \"https://api.example.org/avatar.png\",",
      "  \"https://cdn.example.org/media.pdf\",",
      "  \"http://api.example.org/avatar.png\",",
      "  \"https://127.0.0.1/admin\",",
      "  \"https://169.254.169.254/latest/meta-data/\",",
      "  \"https://10.1.2.3/\",",
      "  \"https://192.168.1.9/\",",
      "  \"https://[::1]/\",",
      "  \"file:///etc/passwd\",",
      "  \"https://inconnu.example.org/\",",
      "]) console.log(valeur, destinationAutorisee(valeur));",
    ].join("\n"), "javascript"),
    code([
      "# lancer la démonstration",
      "node demo-ssrf.cjs",
      "# exemple de sortie (valeurs fictives)",
      "# https://api.example.org/avatar.png true",
      "# https://cdn.example.org/media.pdf true",
      "# http://api.example.org/avatar.png false",
      "# https://127.0.0.1/admin false",
      "# https://169.254.169.254/latest/meta-data/ false",
      "# https://10.1.2.3/ false",
      "# https://192.168.1.9/ false",
      "# https://[::1]/ false",
      "# file:///etc/passwd false",
      "# https://inconnu.example.org/ false",
    ].join("\n"), "bash"),
    figure({
      kind: "anatomy",
      title: "Extrait XML à ne pas accepter tel quel",
      lines: [
        [
          { text: "<!DOCTYPE note [", label: "DTD active", tone: "amber" },
        ],
        [
          { text: "<!ENTITY ext SYSTEM \"file:///etc/passwd\">", label: "entité externe", tone: "red" },
        ],
        [
          { text: "]>", label: "fin de DTD", tone: "neutral" },
          { text: "<note>&ext;</note>", label: "résout l’entité", tone: "red" },
        ],
      ],
      caption: "Remède : désactiver les DTD et les entités externes.",
    }),
    example("Exemple corrigé : un journal sortant qui montre « GET https://169.254.169.254/latest/meta-data/ » depuis un service d’aperçu d’images n’indique pas une simple erreur de copier-coller. Il révèle que le serveur a essayé d’atteindre une destination interne ou locale de lien qui n’aurait jamais dû faire partie de la fonction métier. La correction minimale est de limiter les hôtes autorisés, de refuser les schémas non prévus, puis de revalider aussi les redirections et l’adresse réellement résolue."),
    mistakes("laisser n’importe quelle URL externe passer parce que « ce n’est qu’un aperçu » ; vérifier le nom de domaine avant redirection puis oublier de recontrôler après ; conserver un import XML sans désactiver DTD et entités externes ; désérialiser directement un objet natif fourni par le client parce que « c’est plus pratique »."),
    safety("ne tente pas d’atteindre des services internes ou des métadonnées cloud hors de ton propre environnement de test. Une SSRF touche souvent des composants qui n’étaient pas prévus pour être exposés. Garde aussi les journaux sortants en interne : ils peuvent révéler l’architecture, des noms de services et des chemins sensibles."),
    takeaway("un serveur qui récupère une URL pour l’utilisateur agrandit sa surface d’attaque. La défense prioritaire est la liste autorisée, complétée par la revalidation DNS et des redirections. Pour XML et la désérialisation, le même principe gagne : limiter ce que l’analyseur ou le décodeur a le droit de faire."),
    practice("Travaille dans « TP 5 : contrôle d’accès, API et SSRF dans les journaux » : repère les requêtes sortantes vers l’intérieur, distingue ce qui est métier de ce qui ne l’est pas, puis termine par le quiz."),
    reference("owaspCsSsrf"),
    reference("owaspCsXxe"),
    reference("owaspCsDeserialization"),
    reference("owaspSsrfAttack"),
    reference("cwe918"),
    reference("cwe611"),
    reference("cwe502"),
    reference("awsImds"),
    reference("nodeUrl"),
  ],
  quiz: {
    title: "Quiz : SSRF, XXE et désérialisation",
    questions: [
      questions.choice("Quel scénario ressemble le plus à une SSRF ?", ["Une fonction serveur récupère une URL choisie par l’utilisateur", "Un utilisateur change son mot de passe", "Le navigateur bloque un script inline", "Un cookie expire après une heure"], 0, "La SSRF apparaît quand le serveur agit comme client HTTP ou réseau à partir d’une valeur fournie par l’utilisateur. Les autres situations n’impliquent pas cette délégation de requête côté serveur.", "facile"),
      questions.choice("Pourquoi faut-il revalider après une redirection ou une résolution DNS ?", ["Parce que le nom initial peut finalement mener à une adresse privée ou locale", "Parce que HTTPS interdit les redirections", "Parce que cela supprime les journaux", "Parce que le code 200 devient impossible"], 0, "Un nom ou une URL apparemment bénins peuvent finir sur une autre destination après résolution ou redirection. Le faux ami est la réponse « HTTPS interdit les redirections » : ce n’est pas vrai, et c’est précisément pour cela qu’il faut recontrôler.", "moyen"),
      questions.multi("Quelles réponses défensives sont correctes face à un import XML ancien ? (plusieurs réponses)", ["Préférer JSON quand le protocole le permet", "Désactiver DTD et entités externes dans l’analyseur", "Autoriser « file: » pour faciliter les tests", "Traiter les objets sérialisés du client comme de simples données sans validation"], [0, 1], "JSON réduit souvent la surface exposée, et un analyseur XML doit désactiver les entités externes. Autoriser « file: » ou faire confiance à des objets sérialisés non validés déplace le problème au lieu de le corriger.", "difficile"),
      questions.tf("Une liste autorisée d’hôtes exacts est souvent plus sûre qu’une règle « tout le HTTPS public est permis » pour une fonction d’aperçu d’image.", true, "Vrai : une fonction métier a rarement besoin de joindre l’ensemble du Web. Restreindre les destinations réduit fortement la surface d’attaque et simplifie aussi la relecture des journaux sortants.", "moyen"),
    ],
  },
};

const apiSecurityLesson: NewLesson = {
  key: "web-api-securite",
  title: "Sécuriser une API : autorisation par objet, limitation de débit et OWASP API Top 10",
  summary: "Tu apprends à lire l’API Top 10 2023 avec des exemples concrets, puis à combiner autorisation par objet, limitation de débit, validation de schéma et journalisation sobre pour une API réellement défensive.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("citer les familles de l’OWASP API Top 10 2023, distinguer autorisation par objet, fonction et propriété, mettre en place un limiteur de débit simple, relire une réponse d’API trop bavarde, et calculer un rythme de requêtes par jeton sur un journal JSON inventé."),
    prerequisites("avoir suivi les leçons sur le contrôle d’accès et les jetons, et savoir lire un objet JSON simple."),
    scenario("Kwame publie une API de commandes pour trois applications mobiles. Les pages HTML ont disparu, mais les mêmes questions reviennent : qui peut lire quel objet, qui peut appeler quelle fonction, et combien de fois par minute. En plus, l’équipe découvre une vieille version « /v1 » oubliée et des réponses qui renvoient plus de champs que nécessaire. Kwame doit donc sécuriser l’API comme un produit à part entière, pas comme un simple détail derrière le front."),
    videoSlot("Passer d’une API qui marche à une API qui résiste"),
    text("Une API change la forme de l’application, pas les fondamentaux de sécurité. Au lieu de pages HTML, tu exposes surtout des objets, des fonctions et des propriétés. L’OWASP API Top 10 2023 aide à ne pas oublier les angles majeurs : API1 Broken Object Level Authorization, API2 Broken Authentication, API3 Broken Object Property Level Authorization, API4 Unrestricted Resource Consumption, API5 Broken Function Level Authorization, API6 Unrestricted Access to Sensitive Business Flows, API7 Server Side Request Forgery, API8 Security Misconfiguration, API9 Improper Inventory Management et API10 Unsafe Consumption of APIs."),
    figure({
      kind: "cards",
      title: "Raccourci utile pour relire une API",
      items: [
        { term: "API1", text: "objet d’un autre utilisateur", tone: "red", icon: "user-x" },
        { term: "API3", text: "trop de propriétés lues ou modifiées", tone: "amber", icon: "list" },
        { term: "API5", text: "fonction d’administration appelée sans droit", tone: "red", icon: "briefcase" },
        { term: "API4", text: "consommation de ressources sans garde-fou", tone: "amber", icon: "gauge" },
        { term: "API9", text: "version ou point d’entrée oublié", tone: "violet", icon: "bookmark" },
        { term: "API10", text: "réponse tierce acceptée sans assez de contrôle", tone: "blue", icon: "share" },
      ],
      columns: 3,
    }),
    text("L’autorisation par objet répond à « puis-je lire ou modifier CET enregistrement ? ». L’autorisation par fonction répond à « puis-je appeler CETTE action ? ». L’autorisation par propriété répond à « quels champs ai-je le droit de lire ou d’écrire ? ». Une API saine retourne donc le minimum utile, refuse les champs inattendus dans les requêtes, limite la taille des corps, borne la pagination et renvoie « 429 Too Many Requests » avec « Retry-After » quand un client consomme trop vite."),
    text("N’oublie pas l’inventaire. Une API oubliée en « /v1 », un sous-domaine resté public, un schéma OpenAPI plus maintenu ou une documentation périmée deviennent vite des angles morts. La journalisation doit aider sans divulguer de secrets : identifiant de requête, jeton ou compte pseudonymisé, objet ciblé, résultat, temps de réponse, mais jamais le mot de passe ni le jeton brut. Pour GraphQL, ajoute une limite de profondeur et de complexité : une seule requête peut sinon coûter beaucoup trop cher."),
    text("Démonstration guidée : vérifie d’abord « node --version ». Ce script Node.js simule un limiteur de débit à fenêtre fixe de trois requêtes par minute et calcule aussi le nombre de requêtes par jeton sur un petit journal JSON inventé. Le but n’est pas de te vendre cet algorithme comme solution parfaite, mais de te faire voir ce qu’il compte vraiment et ce qu’il renvoie quand le seuil est dépassé. Si ta version de Node.js est trop ancienne pour lancer le script, mets Node.js à jour puis rejoue la démonstration."),
    code([
      "# fichier demo-api.cjs",
      "const fenetreMs = 60000;",
      "const limite = 3;",
      "const compteurs = new Map();",
      "",
      "function autoriser(token, horodatageMs) {",
      "  const entree = compteurs.get(token);",
      "  if (!entree || horodatageMs - entree.debut >= fenetreMs) {",
      "    compteurs.set(token, { debut: horodatageMs, total: 1 });",
      "    return { allowed: true, remaining: limite - 1 };",
      "  }",
      "  entree.total += 1;",
      "  return { allowed: entree.total <= limite, remaining: Math.max(0, limite - entree.total) };",
      "}",
      "",
      "for (const t of [0, 10000, 20000, 30000, 61000]) {",
      "  console.log(t, autoriser(\"tok-a\", t));",
      "}",
      "",
      "const journal = [",
      "  { token: \"tok-a\", route: \"/api/commandes\", status: 200 },",
      "  { token: \"tok-a\", route: \"/api/commandes\", status: 200 },",
      "  { token: \"tok-b\", route: \"/api/admin/export\", status: 403 },",
      "  { token: \"tok-a\", route: \"/api/commandes\", status: 429 },",
      "  { token: \"tok-b\", route: \"/api/admin/export\", status: 403 },",
      "];",
      "const parToken = {};",
      "for (const ligne of journal) parToken[ligne.token] = (parToken[ligne.token] || 0) + 1;",
      "console.log(parToken);",
    ].join("\n"), "javascript"),
    code([
      "# lancer la démonstration",
      "node demo-api.cjs",
      "# exemple de sortie (valeurs fictives)",
      "# 0 { allowed: true, remaining: 2 }",
      "# 10000 { allowed: true, remaining: 1 }",
      "# 20000 { allowed: true, remaining: 0 }",
      "# 30000 { allowed: false, remaining: 0 }",
      "# 61000 { allowed: true, remaining: 2 }",
      "# { tok-a: 3, tok-b: 2 }",
    ].join("\n"), "bash"),
    figure({
      kind: "compare",
      title: "Réponse trop bavarde à corriger",
      sides: [
        {
          title: "Champs utiles",
          tone: "green",
          icon: "check",
          items: ["`\"id\": 102`", "`\"client\": \"Awa\"`", "`\"total\": 9500`"],
        },
        {
          title: "Champs internes",
          tone: "red",
          icon: "close",
          items: ["`\"margeInterne\": 4300`", "`\"role\": \"admin\"`"],
        },
      ],
      verdict: "Une API grand public ne renvoie pas tout.",
    }),
    example("Exemple corrigé : si une réponse publique renvoie « margeInterne » et « role », tu n’as pas seulement un problème de style JSON. Tu as un défaut d’autorisation par propriété : des champs internes sortent sans nécessité métier. La bonne correction consiste à définir explicitement le schéma de sortie utile pour ce rôle, puis à tester que les autres propriétés ne quittent plus l’API, même si elles existent encore dans la base ou dans l’objet métier interne."),
    mistakes("traiter l’API comme un simple miroir de la base de données ; limiter le débit globalement sans distinguer jeton, compte ou adresse ; oublier les versions anciennes et les points d’entrée peu documentés ; journaliser les jetons complets ou des charges JSON sensibles pour « aider le débogage »."),
    safety("teste les limites de débit et les contrôles d’autorisation seulement sur ton API de démonstration, ton environnement de test ou un périmètre autorisé. Une campagne agressive sur une production peut devenir un déni de service. Les journaux d’API contiennent souvent des identifiants métier : garde-les en interne."),
    takeaway("une API sûre décide qui peut lire quel objet, appeler quelle fonction et voir quels champs. Elle borne aussi ce qu’un client peut consommer, inventorie ses versions et journalise assez pour comprendre sans divulguer de secrets."),
    practice("Travaille dans « TP 5 : contrôle d’accès, API et SSRF dans les journaux » : repère les appels à des fonctions interdites, relie-les aux objets visés et compte le rythme des requêtes par jeton avant de terminer par le quiz."),
    reference("owaspApiTop10"),
    reference("owaspCsRest"),
    reference("mdnStatus429"),
    reference("owaspAsvs"),
    reference("owaspCsGraphql"),
  ],
  quiz: {
    title: "Quiz : sécurité des API",
    questions: [
      questions.choice("Quel risque décrit le mieux API1:2023 ?", ["Un objet d’un autre utilisateur devient lisible ou modifiable faute de vérification", "Le code CSS n’est pas minifié", "Le certificat du serveur a un SAN incomplet", "Le serveur renvoie une page HTML trop longue"], 0, "API1:2023 traite la Broken Object Level Authorization, donc l’accès indu à un objet précis. Le piège tentant est de penser d’abord à l’authentification, alors que l’identité peut être correcte mais les droits insuffisants.", "facile"),
      questions.choice("Que montre le premier « false » dans la sortie du limiteur de débit ?", ["Que le jeton est invalide cryptographiquement", "Que la quatrième requête tombe dans la même fenêtre fixe et dépasse la limite", "Que la minute civile a changé", "Que la route n’existe plus"], 1, "Les trois premières requêtes consomment le quota de la fenêtre, puis la quatrième arrive encore avant le renouvellement. Le faux ami est la cryptographie du jeton : ici, le script ne la teste même pas.", "moyen"),
      questions.multi("Tu relis cette réponse d’API : « {\"id\":102,\"client\":\"Awa\",\"total\":9500,\"margeInterne\":4300,\"role\":\"admin\"} ». Quelles corrections sont justes ? (plusieurs réponses)", ["Définir un schéma de sortie limité aux champs utiles pour ce rôle", "Laisser tous les champs, puis compter sur CORS", "Tester que les champs internes ne sortent plus après correction", "Confondre ce défaut avec un simple problème d’affichage"], [0, 2], "Le problème porte sur la propriété exposée, pas sur l’apparence. CORS ne corrige rien côté serveur. Une correction sérieuse réduit explicitement la sortie et vérifie ensuite que les champs internes ne réapparaissent plus.", "difficile"),
      questions.tf("Une API oubliée en « /v1 » ou sur un sous-domaine ancien relève aussi de la sécurité des API, même si la nouvelle version est correcte.", true, "Vrai : l’inventaire fait partie du sujet. Une ancienne version moins maintenue peut rester accessible et offrir une surface d’attaque plus large que l’API officielle documentée aujourd’hui.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c4:7",
    position: 7,
    title: "Contrôle d’accès, CSRF et CORS",
    description: "Tu y apprends à décider qui peut faire quoi, depuis quelle origine et avec quelles garanties quand un navigateur transporte déjà des cookies ou appelle une API. Critères de réussite : corriger un accès à l’objet d’un autre utilisateur côté serveur ; expliquer quand un jeton anti-CSRF et « SameSite » sont nécessaires ; configurer une liste d’origines CORS exacte sans refléter tout ce qui arrive.",
    lessons: [accessControlLesson, csrfLesson, corsLesson],
  },
  {
    key: "c4:8",
    position: 8,
    title: "Fichiers, SSRF et API",
    description: "Ce module relie les entrées les plus piégeuses d’une application web : fichiers envoyés par l’utilisateur, URLs récupérées par le serveur et objets exposés par l’API. Critères de réussite : vérifier un téléversement sans faire confiance au nom ou au type annoncé ; bloquer une destination SSRF locale, privée ou non autorisée ; borner une API par objet, propriété et rythme de requêtes avec des journaux utiles.",
    lessons: [uploadLesson, ssrfXxeLesson, apiSecurityLesson],
  },
];
