import {
  code,
  example,
  goals,
  mistakes,
  practice,
  prerequisites,
  questions,
  reference,
  safety,
  scenario,
  schema,
  takeaway,
  text,
  videoSlot,
  type NewLesson,
  type PathModuleEntry,
} from "./path-kit";

const surfaceMenacesLesson: NewLesson = {
  key: "web-surface-menaces",
  title: "La surface d’attaque d’une application web et la modélisation des menaces",
  summary: "Tu apprends à voir une application web comme un ensemble de portes d’entrée, de frontières de confiance et de décisions de risque, pas seulement comme des pages HTML.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("repérer la surface d’attaque d’une application web, distinguer les frontières de confiance, classer des menaces par probabilité et impact, puis décider quoi réduire ou protéger en premier."),
    prerequisites("avoir compris ce qu’est une application web, une requête HTTP et un compte utilisateur."),
    scenario("Ama aide l’association Teranga à préparer une application de dons. L’équipe pense surtout à l’écran d’accueil et au formulaire de paiement, mais oublie l’administration, les sauvegardes, le stockage d’images, la messagerie et la chaîne d’intégration. Avant de parler de failles précises, Ama veut cartographier tout ce qui peut être touché, par qui et avec quelles conséquences."),
    videoSlot("Voir la surface d’attaque avant de chercher une faille"),
    text("La surface d’attaque d’une application web, c’est l’ensemble des points par lesquels une action non voulue peut entrer, sortir ou contourner une règle. Cela inclut les pages publiques, les formulaires, les API, les cookies, les comptes, le téléversement de fichiers, les tâches planifiées, les interfaces d’administration, les secrets, les dépendances, les journaux, les sauvegardes et les services tiers. Plus il y a de composants inutiles ou mal compris, plus la surface augmente."),
    schema([
      "Application de dons : surface d’attaque minimale",
      "",
      "navigateur -> pages publiques -> serveur web -> base",
      "           -> formulaire don -> API paiement -> tiers",
      "           -> espace membre   -> stockage docs",
      "admin      -> /admin         -> journaux",
      "CI/CD      -> build          -> secrets",
      "support    -> sauvegardes    -> exports CSV",
    ].join("\n")),
    text("Une frontière de confiance marque l’endroit où tu arrêtes de croire qu’une donnée est sûre. Le navigateur d’un visiteur n’est jamais une frontière de confiance, car il peut modifier les champs, les cookies, les en-têtes et le JavaScript. Un service tiers n’est pas une frontière magique non plus : tu lui délègues une fonction, pas ta responsabilité. La bonne question devient donc : qui contrôle cette donnée, qui la vérifie, et que se passe-t-il si elle ment ?"),
    schema([
      "Quatre questions de modélisation des menaces",
      "",
      "1. Que construisons-nous ?",
      "2. Qu’est-ce qui peut mal tourner ?",
      "3. Que faisons-nous pour réduire le risque ?",
      "4. Avons-nous bien vérifié ?",
      "",
      "STRIDE aide-mémoire :",
      "usurpation, falsification, répudiation,",
      "divulgation, déni de service, élévation",
    ].join("\n")),
    text("Les acteurs ne se résument pas à « le pirate ». Tu peux rencontrer un curieux qui clique partout, un robot automatisé qui teste des milliers d’URL, un concurrent qui cherche une fuite de données, un employé qui abuse d’un accès déjà légitime, ou un attaquant ciblé qui connaît ton organisation. Le risque se juge ensuite avec deux axes simples : la probabilité et l’impact. Ce n’est pas une science exacte, mais c’est mieux qu’une intuition floue."),
    text("Démonstration guidée : le script ci-dessous prend huit menaces d’exemple pour une application fictive et leur attribue une priorité à partir d’une matrice 3 × 3. Le calcul ne remplace pas un atelier d’équipe, mais il t’oblige à écrire tes hypothèses. Le code a été exécuté avec Node.js, uniquement sur des valeurs inventées."),
    code([
      "const threats = [",
      "  ['Formulaire de don sans anti-CSRF', 2, 2],",
      "  ['Sauvegarde publique sur le web', 2, 3],",
      "  ['Compte admin partage', 2, 3],",
      "  [\"Portail d'admin masque mais expose\", 1, 3],",
      "  ['Plugin de statistique inutile', 2, 1],",
      "  ['Bucket de journaux public', 1, 3],",
      "  ['Ancienne API oubliee', 2, 2],",
      "  ['Champ de recherche concatene en SQL', 3, 3],",
      "];",
      "const rows = threats.map(([name, p, i]) => ({",
      "  name, p, i, score: p * i,",
      "  priorite: p * i >= 6 ? 'haute' : p * i >= 3 ? 'moyenne' : 'basse',",
      "}));",
      "console.log(rows);",
      "// exemple de sortie (valeurs fictives)",
      "// { name: 'Sauvegarde publique sur le web', p: 2, i: 3, score: 6, priorite: 'haute' }",
      "// { name: 'Champ de recherche concatene en SQL', p: 3, i: 3, score: 9, priorite: 'haute' }",
      "// { name: 'Plugin de statistique inutile', p: 2, i: 1, score: 2, priorite: 'basse' }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : dans cette matrice, la « sauvegarde publique sur le web » et le « champ de recherche concaténé en SQL » montent en priorité haute, mais pas pour la même raison. La première expose directement des données déjà présentes. Le second ouvre la porte à une faiblesse active sur un point d’entrée courant. À l’inverse, un plugin inutile augmente bien la surface d’attaque, mais avec un impact moindre tant qu’il n’expose ni donnée sensible ni privilège fort. La décision raisonnable est donc de supprimer d’abord l’inutile, puis de corriger en priorité les points qui combinent exposition et conséquence."),
    mistakes("confondre surface d’attaque et nombre de pages visibles ; croire qu’un service tiers supprime la responsabilité de l’équipe ; noter le risque sans écrire l’hypothèse qui le justifie ; garder une vieille interface « au cas où » au lieu de la supprimer."),
    safety("quand tu parles de menaces, tu restes dans un cadre défensif. Tu cartographies ton propre site, ton environnement d’essai ou un périmètre couvert par une autorisation écrite. Les diagrammes, journaux et exports peuvent contenir des données personnelles : ne les publie pas et ne les envoie pas à un service tiers sans nécessité."),
    takeaway("la première défense consiste souvent à réduire ce qui existe. Une surface d’attaque se lit par points d’entrée, frontières de confiance, acteurs et conséquences. Le risque n’est pas un chiffre magique : c’est un raisonnement explicite sur la probabilité et l’impact."),
    practice("Travaille dans « Projet final : auditer l’application de réservation et rédiger le rapport » : cette leçon ne refait pas le projet à ta place, mais elle t’aide à repérer les zones à cartographier avant d’écrire tes constats. Termine ensuite par le quiz."),
    reference("owaspCsAttackSurface"),
    reference("owaspCsThreatModeling"),
    reference("anssiEbios"),
  ],
  quiz: {
    title: "Quiz : surface d’attaque et menaces",
    questions: [
      questions.choice("Laquelle de ces propositions fait partie de la surface d’attaque d’une application web, même si elle n’apparaît pas dans le menu public ?", ["L’interface d’administration et les sauvegardes", "Seulement la page d’accueil", "Uniquement le formulaire de connexion", "Rien tant que le site est en HTTPS"], 0, "Une interface d’administration, une sauvegarde exposée, une API oubliée ou un secret de CI/CD comptent autant qu’une page publique. L’erreur tentante consiste à réduire la surface d’attaque à ce que l’utilisateur voit à l’écran.", "facile"),
      questions.choice("Pourquoi dit-on que le navigateur du visiteur n’est pas une frontière de confiance ?", ["Parce qu’il ne sait jamais afficher du HTML", "Parce que l’utilisateur ou un script peut modifier les données envoyées", "Parce qu’il refuse toujours les cookies", "Parce qu’il chiffre moins bien que le serveur"], 1, "Le client peut changer des champs, des cookies, des en-têtes ou contourner une validation JavaScript. La mauvaise réponse la plus tentante est le chiffrement : TLS protège le transport, pas la fiabilité de ce que le client choisit d’envoyer.", "moyen"),
      questions.multi("Dans l’aide-mémoire STRIDE, quelles catégories décrivent bien des familles de menaces ? (plusieurs réponses)", ["Divulgation d’information", "Déni de service", "Taille de police insuffisante", "Élévation de privilèges"], [0, 1, 3], "STRIDE couvre notamment la divulgation d’information, le déni de service et l’élévation de privilèges. Une taille de police insuffisante relève de l’ergonomie ou de l’accessibilité, pas d’une catégorie de menace de sécurité.", "difficile"),
      questions.tf("Supprimer une fonction inutilisée réduit souvent mieux la surface d’attaque que d’ajouter une nouvelle règle autour d’elle.", true, "Vrai : si une fonction n’a plus d’utilité métier, la supprimer retire du code, des dépendances, des routes et des réglages à surveiller. Une règle ajoutée autour d’un composant inutile laisse encore un point d’entrée, donc encore une charge de vérification.", "moyen"),
    ],
  },
};

const owaspTop10Lesson: NewLesson = {
  key: "web-owasp-top10",
  title: "OWASP Top 10 : lire la liste, ses catégories et ses limites",
  summary: "Tu vas apprendre à utiliser l’OWASP Top 10:2025 comme une carte de sensibilisation utile, sans le confondre avec une norme exhaustive ni avec une checklist magique.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("nommer les catégories du Top 10:2025, relier un constat à la bonne famille, comparer 2021 et 2025, puis expliquer ce que le Top 10 apporte et ce qu’il ne remplace pas."),
    prerequisites("avoir déjà vu ce qu’est une surface d’attaque et pourquoi une même application accumule plusieurs familles de faiblesses."),
    scenario("Koffi doit préparer un mini-audit pour la boutique Soleil. Son responsable lui demande « de vérifier l’OWASP Top 10 ». S’il prend cette demande au pied de la lettre, il risque de cocher dix cases trop vite. Il doit au contraire s’en servir pour structurer son regard, puis compléter avec des exigences et une méthode de test."),
    videoSlot("Utiliser l’OWASP Top 10 sans en faire une béquille"),
    text("L’OWASP est une fondation communautaire qui produit des guides pratiques sur la sécurité applicative. Le Top 10 est un document de sensibilisation : il regroupe les familles de risques web les plus importantes à un moment donné, à partir de données et d’un consensus de terrain. C’est très utile pour former une équipe, classer des constats et parler le même langage. Ce n’est pas, à lui seul, une norme de vérification complète."),
    schema([
      "OWASP Top 10:2025, en ordre",
      "",
      "A01 Broken Access Control",
      "A02 Security Misconfiguration",
      "A03 Software Supply Chain Failures",
      "A04 Cryptographic Failures",
      "A05 Injection",
      "A06 Insecure Design",
      "A07 Authentication Failures",
      "A08 Software or Data Integrity Failures",
      "A09 Security Logging & Alerting Failures",
      "A10 Mishandling of Exceptional Conditions",
    ].join("\n")),
    text("Chaque catégorie résume une famille, pas une seule faiblesse. A01 couvre par exemple l’IDOR, la fonction interdite exposée, le SSRF et le CSRF quand ils révèlent un contrôle d’accès défaillant. A02 parle de mauvaise configuration : mode debug, stockage public, en-têtes absents, CORS trop large, méthodes inutiles, pages d’erreur bavardes. A03 élargit l’ancienne question des composants vulnérables à toute la chaîne d’approvisionnement : dépendances, build, distribution, scripts d’installation et confiance mal placée. A04 vise les défaillances cryptographiques, comme un secret mal protégé ou un chiffrement mal appliqué. A05 regroupe les injections SQL, de commandes, NoSQL ou de gabarits."),
    text("A06 concerne la conception non sécurisée : une logique métier qui oublie les abus prévisibles reste fragile même avec un bon correctif local. A07 couvre les défaillances d’authentification, comme une MFA contournable ou une réinitialisation de mot de passe trop faible. A08 vise l’intégrité des mises à jour, des builds et des données signées. A09 traite de la journalisation et des alertes qui ne permettent pas de détecter ni de comprendre un abus. A10 couvre la mauvaise gestion des conditions exceptionnelles : erreurs, limites, délais d’attente, surcharge et comportements inattendus qui font tomber l’application ou fuir trop d’informations."),
    schema([
      "Ce qui change entre 2021 et 2025",
      "",
      "SSRF : A10 en 2021 -> rattaché à A01 en 2025",
      "Supply chain : A06 2021 élargi -> A03 2025",
      "Misconfiguration : A05 2021 -> A02 2025",
      "Exceptional conditions : nouvelle A10 2025",
    ].join("\n")),
    text("Le bon usage du Top 10 est simple : cartographier tes constats, former les développeurs, repérer les angles morts récurrents et prioriser une première revue. Le mauvais usage consiste à conclure « site conforme » parce qu’aucun constat n’entre clairement dans dix intitulés. Pour vérifier en profondeur, tu complètes avec l’ASVS, qui décrit des exigences de sécurité, et avec le WSTG, qui donne une méthode de test. Pour les API, tu ajoutes le Top 10 API 2023."),
    text("Démonstration guidée : le script suivant classe huit constats inventés dans des catégories 2025. Le but n’est pas de faire croire qu’un programme remplace le jugement humain. Il montre plutôt qu’un même audit peut être raconté avec un vocabulaire stable, utile ensuite dans un rapport ou un tableau de suivi."),
    code([
      "const findings = {",
      "  'Page admin sans verification de role': 'A01 Broken Access Control',",
      "  'Bucket public et mode debug actif': 'A02 Security Misconfiguration',",
      "  'Dependance typosquattee dans la CI': 'A03 Software Supply Chain Failures',",
      "  'Requete SQL concatenee avec une entree': 'A05 Injection',",
      "  'Jeton de reinitialisation faible': 'A07 Authentication Failures',",
      "  'Secret signe dans le depot de build': 'A08 Software or Data Integrity Failures',",
      "  'Journal absent sur changement de role': 'A09 Security Logging & Alerting Failures',",
      "  'Application qui fuit en 500 sur un format inattendu': 'A10 Mishandling of Exceptional Conditions',",
      "};",
      "console.log(findings);",
      "// exemple de sortie (valeurs fictives)",
      "// 'Page admin sans verification de role': 'A01 Broken Access Control'",
      "// 'Dependance typosquattee dans la CI': 'A03 Software Supply Chain Failures'",
      "// 'Application qui fuit en 500 sur un format inattendu': 'A10 Mishandling of Exceptional Conditions'",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : un « bucket public et mode debug actif » relève mieux de A02 que de A09. Le problème principal n’est pas l’absence d’alerte, mais la mauvaise configuration elle-même. À l’inverse, une application qui ne journalise pas les changements de rôle touche directement A09, même si aucun compte n’a encore été abusé. Le Top 10 t’aide donc à ranger un constat selon sa famille dominante, pas à nier les recouvrements possibles."),
    mistakes("traiter le Top 10 comme une certification ; oublier de préciser l’édition citée ; ranger mécaniquement chaque bug dans la première catégorie qui « ressemble » ; croire qu’une application est sûre parce qu’elle n’a pas encore été testée contre l’ASVS ou le WSTG."),
    safety("les catégories OWASP servent à défendre, pas à fournir un mode d’emploi d’exploitation. Quand tu prépares un audit réel, reste dans le périmètre autorisé et privilégie les plateformes d’entraînement légales pour apprendre les gestes techniques hors production."),
    takeaway("le Top 10:2025 est une carte de lecture, pas la totalité du territoire. Il aide à classer, sensibiliser et prioriser. Pour vérifier en profondeur, complète-le avec le Top 10 API 2023, l’ASVS et le WSTG."),
    practice("Travaille dans « Projet final : auditer l’application de réservation et rédiger le rapport » : cette leçon te prépare à classer honnêtement les constats du projet, mais le projet lui-même demande ensuite de prouver, noter et recommander. Termine par le quiz."),
    reference("owaspTop10Edition"),
    reference("owaspApiTop10"),
    reference("owaspAsvs"),
    reference("owaspWstg"),
  ],
  quiz: {
    title: "Quiz : OWASP Top 10",
    questions: [
      questions.choice("Quel énoncé décrit le mieux l’OWASP Top 10 ?", ["Un document de sensibilisation et de priorisation", "Une certification légale automatique", "Une liste exhaustive de tous les bugs possibles", "Un scanner qui produit des preuves"], 0, "Le Top 10 aide à structurer une discussion et à classer des familles de risques. La mauvaise réponse la plus tentante est la liste exhaustive : elle rassure, mais elle oublie qu’un document de sensibilisation ne remplace ni des exigences détaillées ni une méthode d’audit.", "facile"),
      questions.choice("Dans l’édition 2025, où se retrouve le SSRF cité seul en A10 dans l’édition 2021 ?", ["Dans A03 Software Supply Chain Failures", "Dans A01 Broken Access Control", "Dans A09 Security Logging & Alerting Failures", "Il a disparu du paysage"], 1, "En 2025, le SSRF n’est plus une catégorie autonome et se rattache à A01. L’erreur tentante consiste à croire qu’il a été supprimé parce qu’il n’a plus son propre numéro, alors qu’il reste bien traité comme une faiblesse importante.", "moyen"),
      questions.multi("Quelles phrases décrivent un bon usage du Top 10 ? (plusieurs réponses)", ["Former une équipe au vocabulaire des grandes familles de risques", "Classer des constats d’audit dans un rapport", "Déclarer un site sûr sans test complémentaire", "Préparer une première priorisation avant l’ASVS ou le WSTG"], [0, 1, 3], "Le Top 10 sert très bien à former, classer et prioriser. En revanche, l’utiliser comme preuve suffisante de sécurité est une erreur, car il ne décrit pas toutes les exigences ni toutes les vérifications nécessaires.", "difficile"),
      questions.tf("L’OWASP API Security Top 10:2023 complète le Top 10 web général quand tu analyses une API.", true, "Vrai : une API a ses propres angles morts, comme l’autorisation par objet, la consommation de ressources ou l’inventaire de versions. Se limiter au Top 10 web général ferait perdre des nuances importantes sur les interfaces programmatiques.", "moyen"),
    ],
  },
};

const cweCvssLesson: NewLesson = {
  key: "web-cwe-cvss",
  title: "Vulnérabilité, CVE, CWE et CVSS : parler le même langage",
  summary: "Cette leçon t’aide à distinguer une faiblesse, une vulnérabilité précise et une note de gravité, puis à calculer et interpréter un score CVSS v3.1 sans le confondre avec le risque.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("distinguer CVE, CWE, CVSS, NVD et EPSS, lire un vecteur CVSS v3.1, recalculer une note de base, puis expliquer pourquoi la gravité technique ne suffit pas à mesurer le risque."),
    prerequisites("savoir ce qu’est une faiblesse applicative et pourquoi plusieurs constats peuvent appartenir à une même famille."),
    scenario("Fatou lit un avis de sécurité qui mentionne un CVE, plusieurs CWE et une note CVSS 9,8. Son équipe conclut tout de suite « risque critique partout ». Fatou doit remettre de l’ordre : comprendre ce que chaque sigle décrit, recalculer la note, puis ajouter le contexte de l’application avant de prioriser."),
    videoSlot("Lire un avis de vulnérabilité sans mélanger les sigles"),
    text("Une vulnérabilité précise dans un produit reçoit souvent un identifiant CVE, par exemple « CVE-2024-0001 ». Une CWE décrit au contraire un type de faiblesse, comme « CWE-89 » pour l’injection SQL ou « CWE-78 » pour l’injection de commandes. La NVD de NIST agrège et enrichit beaucoup de CVE. CVSS mesure la gravité technique d’une vulnérabilité. EPSS estime une probabilité d’exploitation à court terme. Le catalogue KEV de la CISA signale, lui, les vulnérabilités dont l’exploitation réelle est déjà confirmée. Quand tu lis une fiche CVE, relève au minimum le produit touché, les versions concernées, la CWE associée, le vecteur CVSS, la disponibilité d’un correctif et la présence éventuelle dans EPSS ou KEV. Ces objets se complètent, mais ne veulent pas dire la même chose."),
    schema([
      "Même langage, rôles différents",
      "",
      "CWE  : type de faiblesse",
      "CVE  : cas précis dans un produit",
      "NVD  : base enrichie de vulnérabilités",
      "CVSS : gravité technique",
      "EPSS : probabilité estimée d’exploitation",
      "",
      "Exemple : une CVE peut relever de CWE-89",
      "et recevoir une note CVSS de 9,8",
    ].join("\n")),
    text("Le score CVSS v3.1 de base repose sur huit métriques : AV, AC, PR, UI, S, C, I et A. Tu lis ainsi comment l’attaque arrive, si elle demande des privilèges ou une interaction, si elle change de portée, et quels impacts elle produit sur la confidentialité, l’intégrité et la disponibilité. La note finale va de 0,0 à 10,0 et s’arrondit toujours au dixième supérieur, pas au plus proche."),
    schema([
      "CVSS v3.1 : rappels utiles",
      "",
      "AV N/A/L/P  : vecteur d’attaque",
      "AC L/H      : complexité",
      "PR N/L/H    : privilèges requis",
      "UI N/R      : interaction utilisateur",
      "S U/C       : portée",
      "C I A N/L/H : impacts",
      "",
      "Bandes : 0,0 aucune ; 0,1-3,9 faible ;",
      "4,0-6,9 moyenne ; 7,0-8,9 élevée ;",
      "9,0-10,0 critique",
    ].join("\n")),
    text("Démonstration guidée : le script suivant implémente la formule officielle CVSS v3.1 avec son arrondi supérieur. Il calcule trois vecteurs, dont deux classiques : 9,8 pour un cas réseau sans privilège ni interaction avec impact fort sur C, I et A, puis 6,1 pour un cas demandant une interaction utilisateur et une portée modifiée. Le code a été exécuté avec Node.js et les deux premières notes ont été recoupées avec les exemples publiés par FIRST et le calculateur officiel."),
    code([
      "const AV={N:.85,A:.62,L:.55,P:.2},AC={L:.77,H:.44},UI={N:.85,R:.62},CIA={H:.56,L:.22,N:0};",
      "const up=(n)=>{const i=Math.round(n*100000);return i%10000===0?i/100000:(Math.floor(i/10000)+1)/10};",
      "const pr=(v,s)=>v==='N'?0.85:v==='L'?(s==='C'?0.68:0.62):(s==='C'?0.5:0.27);",
      "function score(vector){",
      "  const x=Object.fromEntries(vector.replace('CVSS:3.1/','').split('/').map((p)=>p.split(':')));",
      "  const iss=1-((1-CIA[x.C])*(1-CIA[x.I])*(1-CIA[x.A]));",
      "  const impact=x.S==='U'?6.42*iss:7.52*(iss-0.029)-3.25*Math.pow(iss-0.02,15);",
      "  const exploit=8.22*AV[x.AV]*AC[x.AC]*pr(x.PR,x.S)*UI[x.UI];",
      "  return impact<=0?0:(x.S==='U'?up(Math.min(impact+exploit,10)):up(Math.min(1.08*(impact+exploit),10)));",
      "}",
      "console.log(score('CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'));",
      "console.log(score('CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N'));",
      "console.log(score('CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:L/I:L/A:L'));",
      "// exemple de sortie (valeurs fictives)",
      "// 9.8",
      "// 6.1",
      "// 3.8",
    ].join("\n"), "javascript"),
    text("Une note CVSS n’est pas un risque d’organisation. Une faille à 9,8 sur un composant inaccessible depuis Internet peut être moins urgente qu’une faiblesse à 6,1 déjà exposée sur un portail métier critique sans journalisation correcte. Tu ajoutes donc le contexte : valeur de l’actif, exposition réelle, présence d’un correctif, exploitation connue, délai acceptable et capacité de détection. CVSS 4.0 existe déjà, mais la version 3.1 reste très utilisée et mérite d’être comprise."),
    example("Exemple corrigé : « CVE-2024-0001, CWE-89, CVSS 9,8 » se lit ainsi. La faiblesse de fond est une injection SQL, décrite par la CWE. La vulnérabilité précise dans un produit donné est identifiée par la CVE. Sa gravité technique de base est critique selon CVSS. Si l’application touchée n’est joignable que sur un réseau d’administration segmenté, la priorité de correction peut rester très élevée, mais le risque métier n’est pas identique à celui d’un portail client exposé publiquement."),
    mistakes("prendre un score CVSS pour un risque métier complet ; confondre une CWE avec une CVE ; lire « 9,8 » sans regarder le vecteur ; oublier qu’une base de vulnérabilités enrichie ne remplace pas la connaissance de son propre périmètre."),
    safety("la lecture d’un avis de sécurité reste défensive : tu comprends une faiblesse pour corriger, prioriser et vérifier. N’essaie jamais d’exploiter une CVE sur un système réel hors périmètre autorisé, même « juste pour confirmer »."),
    takeaway("CWE décrit la famille, CVE décrit le cas précis, CVSS mesure la gravité technique. Le vecteur compte autant que la note. Une priorité de correction sérieuse combine la gravité, l’exposition et le contexte métier."),
    practice("Travaille dans « TP 6 : configuration, dépendances et notation CVSS » : tu y liras des vecteurs, recalculeras des notes et prioriseras des constats sans confondre gravité et risque. Termine ensuite par le quiz."),
    reference("cve"),
    reference("cweSite"),
    reference("cvss31Spec"),
    reference("firstEpss"),
    reference("cisaKev"),
  ],
  quiz: {
    title: "Quiz : CWE, CVE et CVSS",
    questions: [
      questions.choice("Que décrit d’abord une CWE comme « CWE-89 » ?", ["Un type de faiblesse logicielle", "Une vulnérabilité précise d’un produit donné", "Une base de données nationale", "Un score de sévérité"], 0, "Une CWE désigne une famille de faiblesses, ici l’injection SQL. La mauvaise réponse la plus tentante est la vulnérabilité précise : ce rôle appartient plutôt à une CVE, qui parle d’un cas concret dans un logiciel ou un matériel précis.", "facile"),
      questions.choice("Que signifie l’arrondi « Roundup » dans CVSS v3.1 ?", ["On arrondit au plus proche dixième", "On arrondit toujours vers le dixième supérieur", "On tronque après la première décimale", "On ne garde qu’un entier"], 1, "La règle officielle CVSS v3.1 impose l’arrondi supérieur au dixième, même quand la différence paraît minime. C’est justement pour éviter des résultats différents selon l’outil ou le langage que la spécification détaille cet arrondi.", "moyen"),
      questions.multi("Lis le vecteur « CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H ». Quelles affirmations sont justes ? (plusieurs réponses)", ["L’attaque peut partir du réseau", "Elle ne demande ni privilège préalable ni interaction utilisateur", "La portée est modifiée", "Les impacts sur confidentialité, intégrité et disponibilité sont élevés"], [0, 1, 3], "AV:N, PR:N et UI:N se lisent directement dans le vecteur, tout comme C:H, I:H et A:H. En revanche S:U signifie portée inchangée, donc dire qu’elle est modifiée serait une mauvaise lecture du champ Scope.", "difficile"),
      questions.tf("Une vulnérabilité notée 6,1 peut être prioritaire avant une autre notée 9,8 si elle touche un actif plus exposé ou plus critique pour l’organisation.", true, "Vrai : CVSS mesure la gravité technique, pas le risque complet. Une faiblesse moyenne sur un portail public central peut mériter une réaction plus rapide qu’une faiblesse critique dans un composant peu exposé et fortement segmenté.", "moyen"),
    ],
  },
};

const injectionSqlLesson: NewLesson = {
  key: "web-injection-sql",
  title: "Injection SQL : comprendre, reconnaître et empêcher",
  summary: "Tu vas voir comment une entrée non fiable devient du SQL, comment reconnaître les signes d’une injection dans du code ou un journal, et comment la bloquer proprement avec des requêtes paramétrées.",
  minutes: 26,
  xp: 30,
  blocks: [
    goals("expliquer le mécanisme d’une injection SQL, reconnaître une concaténation dangereuse, lire des indices dans un journal, puis corriger avec des requêtes paramétrées et des privilèges minimaux."),
    prerequisites("avoir vu ce qu’est une requête HTTP, une base relationnelle simple et une frontière de confiance côté serveur."),
    scenario("Moussa maintient une petite application d’adhésion pour Baobab Tech. Une recherche d’utilisateur fonctionne « depuis toujours », mais les journaux montrent des apostrophes, des « OR 1=1 » et des réponses anormalement longues. Avant de parler d’attaque confirmée, Moussa veut comprendre le mécanisme, montrer la mauvaise pratique et prouver la correction."),
    videoSlot("Voir l’injection SQL comme une confusion entre code et données"),
    text("Une injection SQL apparaît quand une donnée non fiable est interprétée comme une partie de la requête au lieu de rester une simple valeur. Le problème n’est pas le caractère apostrophe lui-même : c’est la concaténation qui donne à l’entrée le pouvoir de casser la structure de la requête. Une injection peut alors lire trop de lignes, modifier des données, contourner une authentification ou provoquer des erreurs utiles à l’attaquant."),
    schema([
      "Chemin dangereux",
      "",
      "requete HTTP -> parametre q",
      "            -> concatene dans SQL",
      "            -> base interprete le tout comme du code",
      "",
      "Chemin correct",
      "requete HTTP -> parametre q",
      "            -> placeholder ?",
      "            -> base separe code et valeur",
    ].join("\n")),
    text("Les formes d’injection varient. En bande, l’attaquant récupère directement plus de données. En aveugle booléen, il observe seulement une différence de réponse. En aveugle par délai, il mesure un ralentissement. En second ordre, une donnée injectée est stockée puis réinterprétée plus tard. Même sans message d’erreur visible, l’injection reste possible. C’est pourquoi masquer les erreurs aide, mais ne remplace jamais la séparation du code et des données."),
    text("Démonstration guidée : l’exemple ci-dessous crée une petite base mémoire avec « node:sqlite ». Commence par vérifier ta version avec « node --version ». Le module existe depuis Node.js 22.5.0, mais sans drapeau expérimental seulement à partir de 22.13.0. Si ta version est plus ancienne, mets Node.js à jour avant de suivre cette démonstration. La version vulnérable fabrique la requête par concaténation. La version sûre utilise un paramètre. Le test a été exécuté avec Node.js sur des valeurs fictives de la leçon."),
    code([
      "const { DatabaseSync } = require('node:sqlite');",
      "const db = new DatabaseSync(':memory:');",
      "db.exec(\"CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, role TEXT);\");",
      "for (const row of [['Ama','membre'],['Koffi','admin'],['Awa','membre']]) {",
      "  db.prepare('INSERT INTO users (name, role) VALUES (?, ?)').run(...row);",
      "}",
      "const userInput = \"Ama' OR '1'='1\";",
      "const unsafeSql = \"SELECT name FROM users WHERE name = '\" + userInput + \"'\";",
      "const unsafeRows = db.prepare(unsafeSql).all().map((r) => r.name);",
      "const safeRows = db.prepare('SELECT name FROM users WHERE name = ?').all(userInput).map((r) => r.name);",
      "console.log({ unsafeSql, unsafeRows, safeRows });",
      "// exemple de sortie (valeurs fictives)",
      "// unsafeSql: SELECT name FROM users WHERE name = 'Ama' OR '1'='1'",
      "// unsafeRows: [ 'Ama', 'Koffi', 'Awa' ]",
      "// safeRows: []",
    ].join("\n"), "javascript"),
    schema([
      "Indices utiles dans un journal d’accès",
      "",
      "%27, apostrophes répétées, --",
      "UNION SELECT, information_schema",
      "OR 1=1, sleep(, benchmark(",
      "rafale de 500 ou réponses anormalement lentes",
    ].join("\n")),
    text("La défense principale tient en quatre points. D’abord, requêtes paramétrées partout où une valeur varie. Ensuite, liste autorisée pour les identifiants que la base ne paramètre pas, comme un nom de colonne ou le sens d’un tri. Puis moindre privilège pour le compte de base : pas de droits inutiles, pas d’accès à d’autres schémas. Enfin, erreurs détaillées côté serveur seulement. Un WAF peut réduire le bruit ou gagner du temps, mais il ne corrige pas le code."),
    example("Exemple corrigé : « SELECT * FROM users WHERE id = ? » est sûr sur le plan de l’injection si le pilote lie vraiment la valeur au placeholder. « SELECT * FROM users WHERE id = \" + req.query.id » est vulnérable parce qu’il mêle structure et donnée. « SELECT * FROM users ORDER BY \" + req.query.sort » reste dangereux même si le reste de la requête est paramétré, car un identifiant SQL ne se traite pas comme une valeur ordinaire : il faut une liste autorisée de colonnes et de directions."),
    mistakes("croire qu’échapper quelques caractères remplace les requêtes paramétrées ; penser qu’un ORM protège même quand on lui passe du SQL brut ; oublier les noms de colonnes et l’ordre de tri dans la liste autorisée ; exposer au client le message d’erreur complet du moteur SQL."),
    safety("les chaînes d’exemple ici servent à comprendre et corriger sur une base fictive locale. Tu ne réessaies jamais ces motifs sur un site tiers. Analyse seulement tes journaux, ton code ou un environnement expressément autorisé, puis corrige et vérifie."),
    takeaway("l’injection SQL n’est pas une question de caractère interdit, mais de séparation entre code et données. Paramètre les valeurs, autorise explicitement les identifiants, limite les privilèges de la base et garde les détails d’erreur côté serveur."),
    practice("Travaille dans « TP 2 : injections : reconnaître, comprendre et corriger » pour repérer la route vulnérable et la bonne correction. Tu peux aussi relire « Intrusion web : du scan au webshell » pour voir ce que ces tentatives laissent dans un journal d’accès. Termine par le quiz."),
    reference("owaspCsSqli"),
    reference("owaspCsQueryParam"),
    reference("cwe89"),
    reference("phpPdoPrepared"),
    reference("nodeSqlite"),
  ],
  quiz: {
    title: "Quiz : injection SQL",
    questions: [
      questions.choice("Quelle pratique empêche le plus directement une injection SQL sur une valeur utilisateur ?", ["Les requêtes paramétrées", "Un message d’erreur plus court", "Le changement de port de la base", "Une feuille de style plus stricte"], 0, "Les requêtes paramétrées empêchent la valeur d’être interprétée comme du code SQL. Masquer les erreurs ou déplacer le service peut réduire l’exposition ou la fuite d’informations, mais ne sépare pas structure et données.", "facile"),
      questions.choice("Pourquoi « ORDER BY \" + req.query.sort » reste-t-il dangereux, même si le filtre principal est paramétré ?", ["Parce que le tri est toujours exécuté en mémoire", "Parce qu’un identifiant SQL doit être choisi dans une liste autorisée", "Parce qu’ORDER BY désactive automatiquement les placeholders", "Parce que le tri ne marche jamais avec une base relationnelle"], 1, "Le nom de colonne ou la direction du tri ne se gèrent pas comme une valeur ordinaire. La mauvaise réponse tentante est l’idée que les placeholders seraient « désactivés » : le vrai problème est plutôt que tous les fragments SQL ne se paramètrent pas de la même manière.", "moyen"),
      questions.multi("Quels indices de journal peuvent faire penser à une tentative d’injection SQL ? (plusieurs réponses)", ["Des motifs comme « UNION SELECT » ou « OR 1=1 »", "Des réponses nettement plus lentes après certains paramètres", "La présence normale d’un code 200 sur une page statique", "Des apostrophes ou « %27 » répétées dans la même route"], [0, 1, 3], "Les motifs connus, les délais anormaux et les apostrophes répétées sur la même route méritent une vérification. Un simple code 200 sur une page statique n’indique rien à lui seul. Le piège est de confondre un comportement normal avec une signature de tentative.", "difficile"),
      questions.tf("Un WAF peut aider à réduire le bruit d’injection SQL, mais il ne remplace pas la correction du code vulnérable.", true, "Vrai : un WAF peut bloquer ou ralentir certaines charges et fournir des alertes utiles, mais il ne réécrit pas ton application. Tant que la concaténation reste dans le code, la faiblesse de fond demeure avec ses faux positifs et ses contournements possibles.", "moyen"),
    ],
  },
};

const injectionAutresLesson: NewLesson = {
  key: "web-injection-autres",
  title: "Injections de commandes, NoSQL et modèles : la même famille, les mêmes remèdes",
  summary: "Cette leçon relie plusieurs injections moins visibles à la même cause profonde : une donnée non fiable qui traverse un interpréteur sans garde suffisante.",
  minutes: 24,
  xp: 30,
  blocks: [
    goals("reconnaître une injection de commandes, un filtre NoSQL dangereux et une SSTI, comparer leurs remèdes, puis choisir la défense la plus simple avant d’ajouter des validations complémentaires."),
    prerequisites("avoir compris le principe général d’une injection et la différence entre code et donnée."),
    scenario("Awa corrige une application interne qui fait trois choses : elle lance un « ping » depuis un champ d’administration, elle construit un filtre JSON pour une connexion et elle affiche un modèle enrichi par l’utilisateur. Les bugs n’ont pas le même nom, mais Awa soupçonne la même erreur de fond."),
    videoSlot("Reconnaître la même famille d’injections derrière des technologies différentes"),
    text("L’injection de commandes du système apparaît quand une entrée utilisateur traverse un shell ou une commande construite comme une chaîne unique. L’injection NoSQL apparaît quand un objet JSON inattendu, par exemple avec « $ne » ou « $gt », est traité comme un filtre valide. La SSTI, ou injection de gabarit côté serveur, survient quand on compile ou évalue un modèle contenant une entrée non fiable. LDAP, XPath et même certains journaux peuvent tomber dans la même famille."),
    schema([
      "Même cause, interpréteurs différents",
      "",
      "shell   : commande système concaténée",
      "NoSQL   : opérateur JSON non attendu",
      "SSTI    : modèle compilé avec entrée",
      "LDAP    : filtre concaténé",
      "XPath   : expression concaténée",
      "journal : saut de ligne ou faux champ",
    ].join("\n")),
    text("La hiérarchie des remèdes commence avant la validation. Premier choix : éviter l’interpréteur quand ce n’est pas nécessaire. Deuxième choix : utiliser une API qui prend des arguments séparés, pas une chaîne. Troisième choix : valider par liste autorisée ce qui doit vraiment passer. Puis seulement, ajouter de l’encodage adapté au contexte et des privilèges minimaux. Nettoyer quelques caractères à la main ne suffit pas."),
    schema([
      "Ordre de défense recommandé",
      "",
      "1. Éviter l’interpréteur",
      "2. Paramétrer ou séparer les arguments",
      "3. Valider par liste autorisée",
      "4. Encoder selon le contexte",
      "5. Limiter les privilèges",
    ].join("\n")),
    text("Démonstration guidée : ce script montre deux erreurs fréquentes. Vérifie d’abord « node --version ». Le code utilise l’API Node.js « child_process.execFileSync » et le binaire local « ping » : l’exemple ci-dessous choisit « -n » sous Windows et « -c » sous macOS ou Linux. D’un côté, une version vulnérable construit la commande comme une chaîne. De l’autre, une version sûre refuse les hôtes hors liste autorisée et passe les arguments séparément. Le même script refuse aussi un objet JSON inattendu pour une connexion NoSQL fictive. La chaîne vulnérable est seulement affichée, pas exécutée."),
    code([
      "const { execFileSync } = require('node:child_process');",
      "function pingArgs(host){ return process.platform === 'win32' ? ['-n', '1', host] : ['-c', '1', host]; }",
      "function buildUnsafe(host){ return 'ping ' + pingArgs(host).join(' '); }",
      "function safePing(host){",
      "  if (!/^[A-Za-z0-9.-]+$/.test(host) || host.startsWith('-')) return { host, status: 'rejected' };",
      "  execFileSync('ping', pingArgs(host), { encoding: 'utf8' });",
      "  return { host, status: 'ok' };",
      "}",
      "function safeLoginFilter(body){",
      "  if (typeof body.username !== 'string') return { status: 'rejected', reason: 'username type' };",
      "  return { status: 'ok', filter: { username: body.username } };",
      "}",
      "console.log({",
      "  unsafeCommand: buildUnsafe('localhost;whoami'),",
      "  safePingLocalhost: safePing('localhost'),",
      "  safePingRejected: safePing('localhost;whoami'),",
      "  safeLoginOk: safeLoginFilter({ username: 'awa' }),",
      "  safeLoginRejected: safeLoginFilter({ username: { '$ne': '' } }),",
      "});",
      "// exemple de sortie (valeurs fictives)",
      "// unsafeCommand: 'ping -n 1 localhost;whoami'",
      "// safePingLocalhost: { host: 'localhost', status: 'ok' }",
      "// safePingRejected: { host: 'localhost;whoami', status: 'rejected' }",
      "// safeLoginRejected: { status: 'rejected', reason: 'username type' }",
    ].join("\n"), "javascript"),
    text("Pour les modèles côté serveur, la règle la plus sûre est simple : ne compile jamais un modèle qui contient une entrée utilisateur comme s’il s’agissait d’un morceau de code. Pour LDAP ou XPath, le raisonnement est le même qu’en SQL : pas de concaténation naïve. Pour les journaux, pense aussi à l’injection de sauts de ligne ou de faux séparateurs qui fabriquent une trace trompeuse."),
    example("Exemple corrigé : « ping -n 1 \" + host » est dangereux parce qu’il délègue l’interprétation au shell ou à la commande finale. « execFile('ping', ['-n', '1', host]) » réduit fortement ce risque, mais seulement si « host » a été validé. Un objet « { username: { '$ne': '' } } » ne doit jamais être accepté comme s’il s’agissait d’un simple nom d’utilisateur. Enfin, une entrée de support qui contient « \\nadmin=true » ne devrait pas pouvoir fabriquer une ligne de journal plus crédible qu’elle ne l’est réellement."),
    mistakes("croire que seules les bases SQL sont concernées par les injections ; exécuter la chaîne vulnérable « pour voir » ; accepter un objet JSON entier quand une chaîne était attendue ; laisser un moteur de gabarit interpréter du texte fourni par l’utilisateur."),
    safety("les exemples restent défensifs et locaux. Tu n’exécutes jamais une chaîne de commande construite avec une entrée non fiable sur une machine réelle hors laboratoire. Quand tu analyses des journaux, rappelle-toi qu’ils peuvent contenir des données personnelles et des noms internes."),
    takeaway("commande, filtre NoSQL, gabarit, LDAP ou XPath : la technologie change, mais l’erreur de fond reste la même. Sépare le code et la donnée, valide ce qui doit passer, puis réduis les privilèges pour limiter les dégâts si quelque chose échappe au contrôle."),
    practice("Travaille dans « TP 2 : injections : reconnaître, comprendre et corriger » pour distinguer le point d’injection, le mauvais correctif et le vrai remède. Termine ensuite par le quiz."),
    reference("owaspCsCommandInjection"),
    reference("owaspCsInputValidation"),
    reference("cwe78"),
    reference("owaspCsDeserialization"),
    reference("nodeChildProcess"),
  ],
  quiz: {
    title: "Quiz : autres injections",
    questions: [
      questions.choice("Quel point commun relie une injection de commandes, une SSTI et une injection NoSQL ?", ["Une donnée non fiable est interprétée comme du code ou une structure active", "Elles ne touchent que les applications Windows", "Elles exigent toujours un compte administrateur", "Elles disparaissent si le site utilise HTTPS"], 0, "Dans les trois cas, l’application laisse une entrée utilisateur modifier une structure interprétée ensuite par un moteur. La mauvaise réponse la plus tentante est HTTPS : le chiffrement protège le transport, pas la manière dont le serveur traite l’entrée.", "facile"),
      questions.choice("Pourquoi « execFile('ping', ['-n', '1', host]) » est-il préférable à une chaîne « ping -n 1 \" + host » ?", ["Parce qu’execFile chiffre la sortie", "Parce qu’il passe les arguments séparément au lieu de les concaténer", "Parce qu’il ignore automatiquement toute erreur de validation", "Parce qu’il transforme l’hôte en adresse IP sûre"], 1, "Le gain principal vient de la séparation des arguments et de l’absence de shell implicite. Cela ne remplace pas la validation de « host », mais retire une grande partie du risque lié à la concaténation brute.", "moyen"),
      questions.multi("Quelles mesures réduisent correctement plusieurs familles d’injection ? (plusieurs réponses)", ["Attendre une chaîne quand un champ métier doit être une chaîne", "Valider avec une liste autorisée les valeurs vraiment attendues", "Compiler un gabarit fourni par l’utilisateur pour gagner du temps", "Limiter les privilèges du service qui exécute la commande ou la requête"], [0, 1, 3], "Le typage attendu, la liste autorisée et le moindre privilège restent utiles dans plusieurs contextes. Compiler un gabarit non fiable est au contraire la définition même d’une SSTI : c’est donc la réponse tentante à éviter.", "difficile"),
      questions.tf("Afficher une chaîne de commande dangereuse pour l’expliquer est acceptable dans un cours défensif, mais l’exécuter sur un système réel ne l’est pas.", true, "Vrai : un cas d’école sert à reconnaître et corriger une faiblesse. Le faire tourner sur un système réel ferait basculer l’exercice vers un comportement offensif ou risqué, contraire au cadre défensif et légal du cours.", "moyen"),
    ],
  },
};

const validationEntreesLesson: NewLesson = {
  key: "web-validation-entrees",
  title: "Valider, normaliser et encoder : la règle des entrées et des sorties",
  summary: "Tu apprendras à traiter toute donnée comme non fiable, à la normaliser avant validation, puis à encoder correctement les sorties sans croire qu’une seule règle protège tous les contextes.",
  minutes: 22,
  xp: 30,
  blocks: [
    goals("normaliser une entrée avant validation, choisir une liste autorisée, distinguer validation et encodage, reconnaître plusieurs contextes de sortie, puis tester un validateur sur des cas normaux et piégés."),
    prerequisites("avoir compris que la sécurité côté client ne remplace jamais la vérification côté serveur."),
    scenario("Nadia reprend un formulaire d’inscription pour l’association Teranga. Le développeur précédent « nettoyait » quelques caractères puis affichait la même donnée dans un e-mail, une page HTML et un nom de fichier. Nadia veut remettre de l’ordre : quoi valider, quoi normaliser, quoi rejeter, et quoi encoder seulement au moment de la sortie."),
    videoSlot("Traiter les entrées et les sorties sans tout mélanger"),
    text("Toute entrée est non fiable : formulaire, URL, cookie, en-tête, corps JSON, fichier téléversé, donnée venue d’une API tierce ou d’un journal relu plus tard. Valider, c’est vérifier que la donnée correspond au type, à la longueur, à la plage et au format attendus. Une liste autorisée est presque toujours préférable à une liste noire, car tu définis ce qui est acceptable au lieu d’essayer de deviner tout ce qui pourrait être dangereux."),
    schema([
      "Entrer, normaliser, valider, sortir",
      "",
      "entrée brute -> normaliser -> valider -> stocker",
      "                                 |",
      "                                 v",
      "                         rejeter si hors règles",
      "",
      "à la sortie : encoder selon le contexte",
    ].join("\n")),
    text("La normalisation vient avant la validation. Tu peux devoir unifier la casse, réduire les espaces, convertir un type, ou décoder une forme encodée comme « %2e%2e » avant de décider si la valeur est acceptable. Sans cela, une même donnée peut contourner un contrôle selon la manière dont elle est écrite. Normaliser ne veut pourtant pas dire « nettoyer pour faire passer ». Si la donnée ne respecte pas la règle, tu la rejettes."),
    schema([
      "Contexte de sortie != même encodage",
      "",
      "HTML       -> encodage HTML",
      "attribut   -> attribut entre guillemets + encodage",
      "JavaScript -> JSON ou textContent, pas d’injection directe",
      "URL        -> valider le schéma puis encoder l’URL",
      "CSS        -> éviter l’injection directe, limiter les valeurs",
      "SQL        -> requêtes paramétrées",
      "shell      -> arguments séparés, pas de concaténation",
    ].join("\n")),
    text("Validation et encodage n’ont pas le même rôle. Tu valides au plus tôt pour refuser une donnée hors contrat et tu imposes aussi des tailles maximales raisonnables. Tu encodes au plus tard, au moment où tu sors cette donnée vers un contexte précis. Une adresse e-mail stockée en base peut être valide comme donnée métier, puis devoir encore être encodée pour être affichée dans du HTML. Inversement, un bon encodage HTML ne protège pas un appel SQL ou un shell. Les expressions régulières aident, mais un motif trop gourmand peut aussi provoquer un déni de service par consommation excessive."),
    text("Démonstration guidée : ce validateur Node.js normalise un petit formulaire d’inscription, puis rejette les champs hors contrat. Il montre aussi qu’un chemin contenant « %2e%2e%2f » doit être décodé avant d’être jugé. Les huit cas d’essai ci-dessous ont été exécutés avec Node.js."),
    code([
      "const allowed = new Set(['BJ','CI','SN','TG']);",
      "const normalizeName = (v) => v.normalize('NFKC').trim().replace(/\\s+/g, ' ');",
      "const decodePath = (v) => v.replace(/%2e/gi, '.').replace(/%2f/gi, '/');",
      "function validate(x){",
      "  const name = normalizeName(x.name || '');",
      "  const age = Number(x.age);",
      "  const email = String(x.email || '').trim().toLowerCase();",
      "  const country = String(x.country || '').trim().toUpperCase();",
      "  const avatar = decodePath(String(x.avatar || '').trim());",
      "  const errors = [];",
      "  if (!/^[A-Za-zÀ-ÖØ-öø-ÿ' -]{2,40}$/.test(name)) errors.push('name');",
      "  if (!Number.isInteger(age) || age < 13 || age > 120) errors.push('age');",
      "  if (!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email)) errors.push('email');",
      "  if (!allowed.has(country)) errors.push('country');",
      "  if (avatar.includes('..')) errors.push('avatar');",
      "  return { ok: errors.length === 0, errors, name, email, country, avatar };",
      "}",
      "const samples = [",
      "  { name: ' Awa  Ndiaye ', age: '19', email: 'AWA@Example.org ', country: 'sn', avatar: 'profil.png' },",
      "  { name: 'Moussa', age: '40', email: 'moussa@example.org', country: 'SN', avatar: '%2e%2e%2fsecret.txt' },",
      "  { name: 'Ama', age: '12', email: 'ama@example.org', country: 'BJ', avatar: 'profil.png' },",
      "  { name: 'Koffi', age: '27', email: 'koffi@example', country: 'CI', avatar: 'profil.png' },",
      "  { name: 'Fatou', age: '33', email: 'fatou@example.org', country: 'GH', avatar: 'profil.png' },",
      "  { name: ' Fatou\\u00A0Diop ', age: '33', email: 'fatou@example.org', country: 'tg', avatar: 'avatars%2Ffatou.png' },",
      "  { name: 'A', age: '20', email: 'a@example.org', country: 'SN', avatar: 'profil.png' },",
      "  { name: 'Kwame', age: '200', email: 'kwame@example.org', country: 'TG', avatar: 'profil.png' },",
      "];",
      "console.log(samples.map(validate));",
      "// exemple de sortie (valeurs fictives)",
      "// { ok: true, errors: [], name: 'Awa Ndiaye', email: 'awa@example.org', country: 'SN', avatar: 'profil.png' }",
      "// { ok: false, errors: [ 'avatar' ], name: 'Moussa', email: 'moussa@example.org', country: 'SN', avatar: '../secret.txt' }",
      "// { ok: false, errors: [ 'country' ], name: 'Fatou', email: 'fatou@example.org', country: 'GH', avatar: 'profil.png' }",
    ].join("\n"), "javascript"),
    example("Exemple corrigé : si ton formulaire attend un pays parmi « BJ », « CI », « SN » et « TG », la valeur « gh » ne doit pas être « réparée » silencieusement. Elle doit être rejetée avec un message sobre. De même, « %2e%2e%2fsecret.txt » ne doit pas passer parce que les caractères critiques ne sont pas encore visibles : après normalisation, le danger apparaît. Enfin, une adresse e-mail valide pour le métier reste une simple chaîne quand tu l’affiches : si elle part dans du HTML, tu l’encoderas encore pour ce contexte précis."),
    mistakes("nettoyer à la volée au lieu de rejeter les données hors contrat ; oublier la normalisation avant validation ; croire qu’un bon encodage HTML protège aussi une requête SQL ; écrire une regex compliquée sans réfléchir à sa taille, à ses performances et aux cas qu’elle oublie."),
    safety("valider côté serveur reste indispensable, même si le navigateur t’aide côté confort. Quand tu testes des validations, fais-le sur ton application ou ton environnement d’essai. Et quand un journal contient des adresses, noms ou e-mails, évite de le diffuser sans nécessité."),
    takeaway("toute entrée est non fiable. Normalise avant de valider, rejette plutôt que « nettoyer », puis encode au moment exact de la sortie selon le contexte. Une seule règle ne protège pas tous les interpréteurs."),
    practice("Travaille dans « TP 2 : injections : reconnaître, comprendre et corriger » : tu y verras comment une validation insuffisante laisse passer des valeurs trompeuses et comment une correction défensive doit rester explicite. Termine par le quiz."),
    reference("owaspCsInputValidation"),
    reference("owaspCsXss"),
    reference("owaspCsSqli"),
    reference("cwe79"),
  ],
  quiz: {
    title: "Quiz : validation, normalisation et encodage",
    questions: [
      questions.choice("Pourquoi normaliser une entrée avant de la valider ?", ["Pour rendre toutes les données secrètes", "Pour juger la valeur dans une forme stable et comparable", "Pour éviter d’écrire des messages d’erreur", "Pour remplacer toutes les sorties par du HTML"], 1, "Normaliser permet de comparer une valeur dans une forme cohérente : casse, espaces, encodage ou type. La mauvaise réponse la plus tentante est l’idée de « rendre secret », alors que la normalisation sert d’abord à éviter les contournements et les faux rejets.", "facile"),
      questions.choice("Laquelle de ces règles décrit correctement l’encodage de sortie ?", ["Le même encodage protège HTML, SQL et shell", "On encode au moment de la sortie selon le contexte précis", "On encode seulement les mots qui paraissent suspects", "Une regex suffit pour tous les contextes"], 1, "L’encodage dépend du contexte final : HTML, attribut, JavaScript, URL, SQL ou shell n’attendent pas les mêmes protections. Utiliser une seule règle partout laisse des angles morts, même si elle paraît pratique au début.", "moyen"),
      questions.multi("Quelles affirmations sont prudentes pour un validateur côté serveur ? (plusieurs réponses)", ["Il traite aussi les données venues d’une API tierce comme non fiables", "Il peut rejeter une valeur hors liste autorisée au lieu de la corriger silencieusement", "Il peut décoder « %2e%2e » avant d’évaluer un chemin", "Il suffit si le navigateur a déjà contrôlé le formulaire"], [0, 1, 2], "Une API tierce peut mentir ou être mal configurée, la liste autorisée doit pouvoir rejeter, et la normalisation avant validation révèle des formes encodées trompeuses. En revanche, la validation du navigateur ne remplace jamais celle du serveur.", "difficile"),
      questions.tf("Une expression régulière trop complexe peut elle-même devenir un problème de sécurité ou de disponibilité.", true, "Vrai : un motif mal conçu peut consommer beaucoup de temps CPU sur certaines entrées et créer un ReDoS. Le danger ne vient donc pas seulement de ce que la regex laisse passer, mais aussi de la manière dont elle se comporte sous charge.", "moyen"),
    ],
  },
};

export const modules: PathModuleEntry[] = [
  {
    key: "c4:3",
    position: 3,
    title: "Menaces, risques et référentiels",
    description: "Ce module t’apprend à regarder une application web comme un système entier, puis à décrire ses faiblesses avec un vocabulaire commun et vérifiable. Critères de réussite : cartographier une surface d’attaque et ses frontières de confiance ; classer un constat dans la bonne famille OWASP Top 10:2025 ; distinguer CWE, CVE et CVSS sans confondre gravité technique et risque métier.",
    lessons: [surfaceMenacesLesson, owaspTop10Lesson, cweCvssLesson],
  },
  {
    key: "c4:4",
    position: 4,
    title: "Les injections",
    description: "Tu y comprends pourquoi des données non fiables deviennent du code, et comment casser ce mécanisme avec des défenses sobres et vérifiables. Critères de réussite : reconnaître une injection SQL dans du code ou un journal ; appliquer le même raisonnement défensif aux commandes, filtres NoSQL et modèles ; normaliser, valider et encoder selon le bon contexte sans inventer de faux remèdes.",
    lessons: [injectionSqlLesson, injectionAutresLesson, validationEntreesLesson],
  },
];
