// Generated by scripts/generate-db-types.cjs from supabase/migrations. Do not edit by hand.
// Regenerate with `npm run db:types` after every schema change.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      activity_events: {
        Row: {
          id: number
          user_id: string
          kind: string
          entity_id: string | null
          label: string
          page: string | null
          xp_delta: number
          created_at: string
        }
        Insert: {
          id?: number
          user_id: string
          kind: string
          entity_id?: string | null
          label: string
          page?: string | null
          xp_delta?: number
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          kind?: string
          entity_id?: string | null
          label?: string
          page?: string | null
          xp_delta?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_logs: {
        Row: {
          id: number
          actor_id: string | null
          action: string
          target_type: string
          target_id: string | null
          details: Json
          created_at: string
        }
        Insert: {
          id?: number
          actor_id?: string | null
          action: string
          target_type: string
          target_id?: string | null
          details?: Json
          created_at?: string
        }
        Update: {
          id?: number
          actor_id?: string | null
          action?: string
          target_type?: string
          target_id?: string | null
          details?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_logs_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      badges: {
        Row: {
          id: string
          slug: string
          name: string
          description: string
          icon: string
          criteria_type: string
          criteria_value: number
          criteria_course_id: string | null
          xp_reward: number
          is_active: boolean
          position: number
          created_at: string
          updated_at: string
          criteria_lab_id: string | null
          criteria_skill_id: string | null
          rarity: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string
          icon?: string
          criteria_type: string
          criteria_value?: number
          criteria_course_id?: string | null
          xp_reward?: number
          is_active?: boolean
          position?: number
          created_at?: string
          updated_at?: string
          criteria_lab_id?: string | null
          criteria_skill_id?: string | null
          rarity?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string
          icon?: string
          criteria_type?: string
          criteria_value?: number
          criteria_course_id?: string | null
          xp_reward?: number
          is_active?: boolean
          position?: number
          created_at?: string
          updated_at?: string
          criteria_lab_id?: string | null
          criteria_skill_id?: string | null
          rarity?: string
        }
        Relationships: [
          {
            foreignKeyName: "badges_criteria_course_id_fkey"
            columns: ["criteria_course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "badges_criteria_lab_id_fkey"
            columns: ["criteria_lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "badges_criteria_skill_id_fkey"
            columns: ["criteria_skill_id"]
            isOneToOne: false
            referencedRelation: "skills"
            referencedColumns: ["id"]
          },
        ]
      }
      cb_rules: {
        Row: {
          key: string
          kind: string
          label: string
          description: string
          amount: number
          is_active: boolean
          position: number
          updated_at: string
        }
        Insert: {
          key: string
          kind: string
          label: string
          description?: string
          amount: number
          is_active?: boolean
          position?: number
          updated_at?: string
        }
        Update: {
          key?: string
          kind?: string
          label?: string
          description?: string
          amount?: number
          is_active?: boolean
          position?: number
          updated_at?: string
        }
        Relationships: []
      }
      cb_settings: {
        Row: {
          singleton: boolean
          rewards_enabled: boolean
          purchases_enabled: boolean
          gating_enabled: boolean
          paused_reason: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          singleton?: boolean
          rewards_enabled?: boolean
          purchases_enabled?: boolean
          gating_enabled?: boolean
          paused_reason?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          singleton?: boolean
          rewards_enabled?: boolean
          purchases_enabled?: boolean
          gating_enabled?: boolean
          paused_reason?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cb_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cb_transactions: {
        Row: {
          id: number
          user_id: string
          amount: number
          reason: string
          reference_type: string | null
          reference_id: string | null
          label: string
          source: string
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: number
          user_id: string
          amount: number
          reason: string
          reference_type?: string | null
          reference_id?: string | null
          label?: string
          source?: string
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          amount?: number
          reason?: string
          reference_type?: string | null
          reference_id?: string | null
          label?: string
          source?: string
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cb_transactions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cb_transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cb_wallets: {
        Row: {
          user_id: string
          balance: number
          lifetime_earned: number
          lifetime_spent: number
          updated_at: string
        }
        Insert: {
          user_id: string
          balance?: number
          lifetime_earned?: number
          lifetime_spent?: number
          updated_at?: string
        }
        Update: {
          user_id?: string
          balance?: number
          lifetime_earned?: number
          lifetime_spent?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cb_wallets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      certificates: {
        Row: {
          id: string
          user_id: string
          course_id: string | null
          certificate_number: string
          verification_code: string
          recipient_name: string
          course_title: string
          issued_at: string
          revoked_at: string | null
          revoked_reason: string | null
          pdf_path: string | null
          exam_percentage: number | null
          exam_attempt_id: string | null
        }
        Insert: {
          id?: string
          user_id: string
          course_id?: string | null
          certificate_number?: string
          verification_code?: string
          recipient_name: string
          course_title: string
          issued_at?: string
          revoked_at?: string | null
          revoked_reason?: string | null
          pdf_path?: string | null
          exam_percentage?: number | null
          exam_attempt_id?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string | null
          certificate_number?: string
          verification_code?: string
          recipient_name?: string
          course_title?: string
          issued_at?: string
          revoked_at?: string | null
          revoked_reason?: string | null
          pdf_path?: string | null
          exam_percentage?: number | null
          exam_attempt_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "certificates_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_exam_attempt_id_fkey"
            columns: ["exam_attempt_id"]
            isOneToOne: false
            referencedRelation: "exam_attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      challenges: {
        Row: {
          id: string
          slug: string
          title: string
          description: string
          icon: string
          period: string
          metric: string
          target: number
          xp_reward: number
          is_active: boolean
          starts_at: string | null
          ends_at: string | null
          position: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          title: string
          description?: string
          icon?: string
          period: string
          metric: string
          target: number
          xp_reward?: number
          is_active?: boolean
          starts_at?: string | null
          ends_at?: string | null
          position?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          title?: string
          description?: string
          icon?: string
          period?: string
          metric?: string
          target?: number
          xp_reward?: number
          is_active?: boolean
          starts_at?: string | null
          ends_at?: string | null
          position?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "challenges_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      contact_messages: {
        Row: {
          id: string
          user_id: string | null
          email: string | null
          subject: string
          message: string
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          email?: string | null
          subject: string
          message: string
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          email?: string | null
          subject?: string
          message?: string
          status?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contact_messages_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_modules: {
        Row: {
          id: string
          course_id: string
          title: string
          description: string
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          course_id: string
          title: string
          description?: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          course_id?: string
          title?: string
          description?: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_modules_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      course_unlocks: {
        Row: {
          user_id: string
          course_id: string
          source: string
          price_paid: number
          unlocked_at: string
        }
        Insert: {
          user_id: string
          course_id: string
          source: string
          price_paid?: number
          unlocked_at?: string
        }
        Update: {
          user_id?: string
          course_id?: string
          source?: string
          price_paid?: number
          unlocked_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "course_unlocks_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_unlocks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          id: string
          slug: string
          title: string
          short_description: string
          description: string
          thumbnail_url: string | null
          level: string
          category: string
          icon: string
          estimated_duration: number
          status: string
          access_level: string
          position: number
          completion_xp: number
          certificate_enabled: boolean
          created_by: string | null
          created_at: string
          updated_at: string
          published_at: string | null
          domain_id: string | null
          cb_price: number | null
          prerequisite_course_id: string | null
          exam_pass_percentage: number
          exam_duration_minutes: number
          exam_question_count: number
        }
        Insert: {
          id?: string
          slug: string
          title: string
          short_description?: string
          description?: string
          thumbnail_url?: string | null
          level?: string
          category?: string
          icon?: string
          estimated_duration?: number
          status?: string
          access_level?: string
          position?: number
          completion_xp?: number
          certificate_enabled?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
          published_at?: string | null
          domain_id?: string | null
          cb_price?: number | null
          prerequisite_course_id?: string | null
          exam_pass_percentage?: number
          exam_duration_minutes?: number
          exam_question_count?: number
        }
        Update: {
          id?: string
          slug?: string
          title?: string
          short_description?: string
          description?: string
          thumbnail_url?: string | null
          level?: string
          category?: string
          icon?: string
          estimated_duration?: number
          status?: string
          access_level?: string
          position?: number
          completion_xp?: number
          certificate_enabled?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
          published_at?: string | null
          domain_id?: string | null
          cb_price?: number | null
          prerequisite_course_id?: string | null
          exam_pass_percentage?: number
          exam_duration_minutes?: number
          exam_question_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "courses_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "courses_domain_id_fkey"
            columns: ["domain_id"]
            isOneToOne: false
            referencedRelation: "domains"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "courses_prerequisite_course_id_fkey"
            columns: ["prerequisite_course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_activity: {
        Row: {
          user_id: string
          activity_date: string
          lessons_completed: number
          quizzes_passed: number
          labs_solved: number
          xp_earned: number
          study_minutes: number
        }
        Insert: {
          user_id: string
          activity_date: string
          lessons_completed?: number
          quizzes_passed?: number
          labs_solved?: number
          xp_earned?: number
          study_minutes?: number
        }
        Update: {
          user_id?: string
          activity_date?: string
          lessons_completed?: number
          quizzes_passed?: number
          labs_solved?: number
          xp_earned?: number
          study_minutes?: number
        }
        Relationships: [
          {
            foreignKeyName: "daily_activity_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      domains: {
        Row: {
          id: string
          slug: string
          name: string
          description: string
          icon: string
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string
          icon?: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string
          icon?: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      enrollments: {
        Row: {
          id: string
          user_id: string
          course_id: string
          status: string
          last_lesson_id: string | null
          enrolled_at: string
          last_activity_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          course_id: string
          status?: string
          last_lesson_id?: string | null
          enrolled_at?: string
          last_activity_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string
          status?: string
          last_lesson_id?: string | null
          enrolled_at?: string
          last_activity_at?: string
          completed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "enrollments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_last_lesson_id_fkey"
            columns: ["last_lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      exam_attempts: {
        Row: {
          id: string
          user_id: string
          course_id: string
          started_at: string
          expires_at: string
          submitted_at: string | null
          score: number | null
          total_questions: number
          percentage: number | null
          passed: boolean | null
          pass_percentage: number
          module_breakdown: Json | null
          questions: Json
          answers: Json | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          course_id: string
          started_at?: string
          expires_at: string
          submitted_at?: string | null
          score?: number | null
          total_questions?: number
          percentage?: number | null
          passed?: boolean | null
          pass_percentage?: number
          module_breakdown?: Json | null
          questions?: Json
          answers?: Json | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string
          started_at?: string
          expires_at?: string
          submitted_at?: string | null
          score?: number | null
          total_questions?: number
          percentage?: number | null
          passed?: boolean | null
          pass_percentage?: number
          module_breakdown?: Json | null
          questions?: Json
          answers?: Json | null
          status?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "exam_attempts_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "exam_attempts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_assets: {
        Row: {
          id: string
          lab_id: string
          kind: string
          title: string
          description: string
          url: string
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          lab_id: string
          kind: string
          title: string
          description?: string
          url: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          lab_id?: string
          kind?: string
          title?: string
          description?: string
          url?: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_assets_lab_id_fkey"
            columns: ["lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_completions: {
        Row: {
          user_id: string
          lab_id: string
          xp_awarded: number
          completed_at: string
        }
        Insert: {
          user_id: string
          lab_id: string
          xp_awarded?: number
          completed_at?: string
        }
        Update: {
          user_id?: string
          lab_id?: string
          xp_awarded?: number
          completed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_completions_lab_id_fkey"
            columns: ["lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_completions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_submissions: {
        Row: {
          id: string
          user_id: string
          lab_id: string
          note: string
          link: string | null
          status: string
          feedback: string
          reviewed_by: string | null
          reviewed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          lab_id: string
          note: string
          link?: string | null
          status?: string
          feedback?: string
          reviewed_by?: string | null
          reviewed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          lab_id?: string
          note?: string
          link?: string | null
          status?: string
          feedback?: string
          reviewed_by?: string | null
          reviewed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_submissions_lab_id_fkey"
            columns: ["lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_submissions_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_submissions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_task_completions: {
        Row: {
          user_id: string
          task_id: string
          lab_id: string
          completed_at: string
        }
        Insert: {
          user_id: string
          task_id: string
          lab_id: string
          completed_at?: string
        }
        Update: {
          user_id?: string
          task_id?: string
          lab_id?: string
          completed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_task_completions_lab_id_fkey"
            columns: ["lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_task_completions_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "lab_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_task_completions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_tasks: {
        Row: {
          id: string
          lab_id: string
          position: number
          prompt: string
          hint: string
          answer_format: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          lab_id: string
          position?: number
          prompt: string
          hint?: string
          answer_format?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          lab_id?: string
          position?: number
          prompt?: string
          hint?: string
          answer_format?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_tasks_lab_id_fkey"
            columns: ["lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_unlocks: {
        Row: {
          user_id: string
          lab_id: string
          source: string
          price_paid: number
          unlocked_at: string
        }
        Insert: {
          user_id: string
          lab_id: string
          source: string
          price_paid?: number
          unlocked_at?: string
        }
        Update: {
          user_id?: string
          lab_id?: string
          source?: string
          price_paid?: number
          unlocked_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_unlocks_lab_id_fkey"
            columns: ["lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_unlocks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      labs: {
        Row: {
          id: string
          slug: string
          title: string
          description: string
          category: string
          difficulty: string
          xp_reward: number
          objectives: string[]
          hints: string[]
          terminal_lines: string[]
          flag_placeholder: string
          status: string
          position: number
          created_by: string | null
          created_at: string
          updated_at: string
          published_at: string | null
          course_id: string | null
          format: string
          briefing: string
          constraints: string[]
          tools: string[]
          requires_computer: boolean
          is_assessment: boolean
          estimated_minutes: number
          cb_price: number | null
        }
        Insert: {
          id?: string
          slug: string
          title: string
          description?: string
          category?: string
          difficulty?: string
          xp_reward?: number
          objectives?: string[]
          hints?: string[]
          terminal_lines?: string[]
          flag_placeholder?: string
          status?: string
          position?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
          published_at?: string | null
          course_id?: string | null
          format?: string
          briefing?: string
          constraints?: string[]
          tools?: string[]
          requires_computer?: boolean
          is_assessment?: boolean
          estimated_minutes?: number
          cb_price?: number | null
        }
        Update: {
          id?: string
          slug?: string
          title?: string
          description?: string
          category?: string
          difficulty?: string
          xp_reward?: number
          objectives?: string[]
          hints?: string[]
          terminal_lines?: string[]
          flag_placeholder?: string
          status?: string
          position?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
          published_at?: string | null
          course_id?: string | null
          format?: string
          briefing?: string
          constraints?: string[]
          tools?: string[]
          requires_computer?: boolean
          is_assessment?: boolean
          estimated_minutes?: number
          cb_price?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "labs_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "labs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      learner_sessions: {
        Row: {
          user_id: string
          current_page: string
          visible: boolean
          connected_at: string
          last_seen_at: string
          ended_at: string | null
        }
        Insert: {
          user_id: string
          current_page?: string
          visible?: boolean
          connected_at?: string
          last_seen_at?: string
          ended_at?: string | null
        }
        Update: {
          user_id?: string
          current_page?: string
          visible?: boolean
          connected_at?: string
          last_seen_at?: string
          ended_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "learner_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lesson_progress: {
        Row: {
          user_id: string
          lesson_id: string
          course_id: string
          status: string
          progress_percentage: number
          started_at: string | null
          completed_at: string | null
          last_viewed_at: string
          xp_awarded: number
        }
        Insert: {
          user_id: string
          lesson_id: string
          course_id: string
          status?: string
          progress_percentage?: number
          started_at?: string | null
          completed_at?: string | null
          last_viewed_at?: string
          xp_awarded?: number
        }
        Update: {
          user_id?: string
          lesson_id?: string
          course_id?: string
          status?: string
          progress_percentage?: number
          started_at?: string | null
          completed_at?: string | null
          last_viewed_at?: string
          xp_awarded?: number
        }
        Relationships: [
          {
            foreignKeyName: "lesson_progress_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_progress_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_progress_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lessons: {
        Row: {
          id: string
          course_id: string
          module_id: string
          title: string
          summary: string
          content_type: string
          content: Json
          duration_minutes: number
          xp_reward: number
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          course_id: string
          module_id: string
          title: string
          summary?: string
          content_type?: string
          content?: Json
          duration_minutes?: number
          xp_reward?: number
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          course_id?: string
          module_id?: string
          title?: string
          summary?: string
          content_type?: string
          content?: Json
          duration_minutes?: number
          xp_reward?: number
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lessons_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lessons_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "course_modules"
            referencedColumns: ["id"]
          },
        ]
      }
      levels: {
        Row: {
          level: number
          required_xp: number
          title: string
        }
        Insert: {
          level: number
          required_xp: number
          title: string
        }
        Update: {
          level?: number
          required_xp?: number
          title?: string
        }
        Relationships: []
      }
      mascot_lines: {
        Row: {
          id: string
          event: string
          expression: string
          text_fr: string
          audio_url: string | null
          voice_credit: string | null
          priority: number
          is_active: boolean
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event: string
          expression: string
          text_fr: string
          audio_url?: string | null
          voice_credit?: string | null
          priority?: number
          is_active?: boolean
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event?: string
          expression?: string
          text_fr?: string
          audio_url?: string | null
          voice_credit?: string | null
          priority?: number
          is_active?: boolean
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          body: string
          link: string | null
          data: Json
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          body?: string
          link?: string | null
          data?: Json
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          body?: string
          link?: string | null
          data?: Json
          read_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          email: string
          username: string
          display_name: string
          avatar_path: string | null
          bio: string
          role: string
          goal: string
          skill_level: string
          daily_minutes: number
          known_areas: string[]
          onboarding_completed: boolean
          xp: number
          level: number
          current_streak: number
          longest_streak: number
          last_activity_date: string | null
          last_activity_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string
          username: string
          display_name: string
          avatar_path?: string | null
          bio?: string
          role?: string
          goal?: string
          skill_level?: string
          daily_minutes?: number
          known_areas?: string[]
          onboarding_completed?: boolean
          xp?: number
          level?: number
          current_streak?: number
          longest_streak?: number
          last_activity_date?: string | null
          last_activity_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          username?: string
          display_name?: string
          avatar_path?: string | null
          bio?: string
          role?: string
          goal?: string
          skill_level?: string
          daily_minutes?: number
          known_areas?: string[]
          onboarding_completed?: boolean
          xp?: number
          level?: number
          current_streak?: number
          longest_streak?: number
          last_activity_date?: string | null
          last_activity_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      quiz_answers: {
        Row: {
          id: string
          question_id: string
          position: number
          label: string
          is_correct: boolean
        }
        Insert: {
          id?: string
          question_id: string
          position?: number
          label: string
          is_correct?: boolean
        }
        Update: {
          id?: string
          question_id?: string
          position?: number
          label?: string
          is_correct?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "quiz_answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "quiz_questions"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_attempts: {
        Row: {
          id: string
          user_id: string
          quiz_id: string
          course_id: string
          answers: Json
          score: number
          total: number
          percentage: number
          passed: boolean
          xp_awarded: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          quiz_id: string
          course_id: string
          answers?: Json
          score: number
          total: number
          percentage: number
          passed: boolean
          xp_awarded?: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          quiz_id?: string
          course_id?: string
          answers?: Json
          score?: number
          total?: number
          percentage?: number
          passed?: boolean
          xp_awarded?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_attempts_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_attempts_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quiz_attempts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_questions: {
        Row: {
          id: string
          quiz_id: string
          position: number
          question_type: string
          prompt: string
          image_url: string | null
          explanation: string
          difficulty: string
          xp_reward: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          quiz_id: string
          position?: number
          question_type?: string
          prompt: string
          image_url?: string | null
          explanation?: string
          difficulty?: string
          xp_reward?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          quiz_id?: string
          position?: number
          question_type?: string
          prompt?: string
          image_url?: string | null
          explanation?: string
          difficulty?: string
          xp_reward?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_questions_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
        ]
      }
      quizzes: {
        Row: {
          id: string
          course_id: string
          module_id: string
          lesson_id: string | null
          title: string
          description: string
          pass_percentage: number
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          course_id: string
          module_id: string
          lesson_id?: string | null
          title: string
          description?: string
          pass_percentage?: number
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          course_id?: string
          module_id?: string
          lesson_id?: string | null
          title?: string
          description?: string
          pass_percentage?: number
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quizzes_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quizzes_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quizzes_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "course_modules"
            referencedColumns: ["id"]
          },
        ]
      }
      ranks: {
        Row: {
          id: string
          slug: string
          name: string
          description: string
          position: number
          criteria: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string
          position: number
          criteria?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string
          position?: number
          criteria?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      skill_links: {
        Row: {
          id: string
          skill_id: string
          kind: string
          lesson_id: string | null
          quiz_id: string | null
          lab_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          skill_id: string
          kind: string
          lesson_id?: string | null
          quiz_id?: string | null
          lab_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          skill_id?: string
          kind?: string
          lesson_id?: string | null
          quiz_id?: string | null
          lab_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "skill_links_lab_id_fkey"
            columns: ["lab_id"]
            isOneToOne: false
            referencedRelation: "labs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "skill_links_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "skill_links_quiz_id_fkey"
            columns: ["quiz_id"]
            isOneToOne: false
            referencedRelation: "quizzes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "skill_links_skill_id_fkey"
            columns: ["skill_id"]
            isOneToOne: false
            referencedRelation: "skills"
            referencedColumns: ["id"]
          },
        ]
      }
      skills: {
        Row: {
          id: string
          domain_id: string | null
          slug: string
          name: string
          description: string
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          domain_id?: string | null
          slug: string
          name: string
          description?: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          domain_id?: string | null
          slug?: string
          name?: string
          description?: string
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "skills_domain_id_fkey"
            columns: ["domain_id"]
            isOneToOne: false
            referencedRelation: "domains"
            referencedColumns: ["id"]
          },
        ]
      }
      user_badges: {
        Row: {
          user_id: string
          badge_id: string
          earned_at: string
        }
        Insert: {
          user_id: string
          badge_id: string
          earned_at?: string
        }
        Update: {
          user_id?: string
          badge_id?: string
          earned_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_badges_badge_id_fkey"
            columns: ["badge_id"]
            isOneToOne: false
            referencedRelation: "badges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_badges_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_challenges: {
        Row: {
          user_id: string
          challenge_id: string
          period_start: string
          progress: number
          completed_at: string | null
          xp_awarded: number
          updated_at: string
        }
        Insert: {
          user_id: string
          challenge_id: string
          period_start: string
          progress?: number
          completed_at?: string | null
          xp_awarded?: number
          updated_at?: string
        }
        Update: {
          user_id?: string
          challenge_id?: string
          period_start?: string
          progress?: number
          completed_at?: string | null
          xp_awarded?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_challenges_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "challenges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_challenges_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_ranks: {
        Row: {
          user_id: string
          rank_id: string
          achieved_at: string
        }
        Insert: {
          user_id: string
          rank_id: string
          achieved_at?: string
        }
        Update: {
          user_id?: string
          rank_id?: string
          achieved_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_ranks_rank_id_fkey"
            columns: ["rank_id"]
            isOneToOne: false
            referencedRelation: "ranks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_ranks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_settings: {
        Row: {
          user_id: string
          timezone: string
          email_notifications: boolean
          streak_reminders: boolean
          new_content_alerts: boolean
          sound_effects: boolean
          updated_at: string
        }
        Insert: {
          user_id: string
          timezone?: string
          email_notifications?: boolean
          streak_reminders?: boolean
          new_content_alerts?: boolean
          sound_effects?: boolean
          updated_at?: string
        }
        Update: {
          user_id?: string
          timezone?: string
          email_notifications?: boolean
          streak_reminders?: boolean
          new_content_alerts?: boolean
          sound_effects?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_settings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_skills: {
        Row: {
          user_id: string
          skill_id: string
          state: string
          changed_at: string
        }
        Insert: {
          user_id: string
          skill_id: string
          state: string
          changed_at?: string
        }
        Update: {
          user_id?: string
          skill_id?: string
          state?: string
          changed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_skills_skill_id_fkey"
            columns: ["skill_id"]
            isOneToOne: false
            referencedRelation: "skills"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_skills_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      xp_transactions: {
        Row: {
          id: number
          user_id: string
          amount: number
          reason: string
          reference_type: string | null
          reference_id: string | null
          label: string
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: number
          user_id: string
          amount: number
          reason: string
          reference_type?: string | null
          reference_id?: string | null
          label?: string
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          amount?: number
          reason?: string
          reference_type?: string | null
          reference_id?: string | null
          label?: string
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "xp_transactions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "xp_transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      course_progress: {
        Row: {
          user_id: string | null
          course_id: string | null
          status: string | null
          enrolled_at: string | null
          completed_at: string | null
          last_lesson_id: string | null
          last_activity_at: string | null
          total_lessons: number | null
          completed_lessons: number | null
          total_quizzes: number | null
          passed_quizzes: number | null
          progress_percentage: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      admin_adjust_cb: {
        Args: {
          p_user: string
          p_amount: number
          p_reason: string
        }
        Returns: Json
      }
      admin_adjust_xp: {
        Args: {
          p_user: string
          p_amount: number
          p_reason: string
        }
        Returns: Json
      }
      admin_broadcast_notification: {
        Args: {
          p_title: string
          p_body: string
          p_link?: string
          p_audience?: string
        }
        Returns: number
      }
      admin_cb_overview: {
        Args: never
        Returns: Json
      }
      admin_cb_transactions: {
        Args: {
          p_user?: string
          p_reason?: string
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      admin_cb_wallets: {
        Args: {
          p_search?: string
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      admin_course_stats: {
        Args: {
          p_course_id: string
        }
        Returns: Json
      }
      admin_get_lab_flag: {
        Args: {
          p_lab_id: string
        }
        Returns: string
      }
      admin_get_lab_tasks: {
        Args: {
          p_lab_id: string
        }
        Returns: Json
      }
      admin_get_quiz: {
        Args: {
          p_quiz_id: string
        }
        Returns: Json
      }
      admin_grant_unlock: {
        Args: {
          p_kind: string
          p_id: string
          p_user: string
          p_reason: string
        }
        Returns: undefined
      }
      admin_import_course: {
        Args: {
          p_course: Json
        }
        Returns: Json
      }
      admin_overview: {
        Args: never
        Returns: Json
      }
      admin_restore_certificate: {
        Args: {
          p_certificate_id: string
        }
        Returns: undefined
      }
      admin_review_submission: {
        Args: {
          p_id: string
          p_status: string
          p_feedback?: string
        }
        Returns: undefined
      }
      admin_revoke_certificate: {
        Args: {
          p_certificate_id: string
          p_reason: string
        }
        Returns: undefined
      }
      admin_save_quiz: {
        Args: {
          p_quiz_id: string
          p_questions: Json
        }
        Returns: number
      }
      admin_set_cb_prerequisite: {
        Args: {
          p_course_id: string
          p_prerequisite_id: string
          p_reason: string
        }
        Returns: undefined
      }
      admin_set_cb_price: {
        Args: {
          p_kind: string
          p_id: string
          p_price: number
          p_reason: string
        }
        Returns: undefined
      }
      admin_set_cb_rule: {
        Args: {
          p_key: string
          p_amount: number
          p_active: boolean
          p_reason: string
        }
        Returns: undefined
      }
      admin_set_cb_settings: {
        Args: {
          p_rewards: boolean
          p_purchases: boolean
          p_gating: boolean
          p_paused_reason: string
          p_reason: string
        }
        Returns: undefined
      }
      admin_set_lab_flag: {
        Args: {
          p_lab_id: string
          p_flag: string
        }
        Returns: undefined
      }
      admin_set_lab_tasks: {
        Args: {
          p_lab_id: string
          p_tasks: Json
        }
        Returns: undefined
      }
      admin_set_role: {
        Args: {
          p_user: string
          p_role: string
        }
        Returns: undefined
      }
      admin_user_detail: {
        Args: {
          p_user: string
        }
        Returns: Json
      }
      admin_users: {
        Args: {
          p_search?: string
          p_role?: string
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      complete_lesson: {
        Args: {
          p_lesson_id: string
        }
        Returns: Json
      }
      complete_onboarding: {
        Args: {
          p_skill_level: string
          p_goal: string
          p_daily_minutes: number
          p_known_areas: string[]
        }
        Returns: undefined
      }
      consume_mentor_quota: {
        Args: never
        Returns: Json
      }
      delete_my_account: {
        Args: never
        Returns: undefined
      }
      end_session: {
        Args: never
        Returns: undefined
      }
      enroll_in_course: {
        Args: {
          p_course_id: string
        }
        Returns: Json
      }
      get_cb_catalog: {
        Args: never
        Returns: Json
      }
      get_course_exam_status: {
        Args: {
          p_course_id: string
        }
        Returns: Json
      }
      get_my_academy: {
        Args: never
        Returns: Json
      }
      get_my_cb_history: {
        Args: {
          p_limit?: number
          p_before?: number
        }
        Returns: Json
      }
      get_my_dashboard: {
        Args: never
        Returns: Json
      }
      get_my_stats: {
        Args: never
        Returns: Json
      }
      get_my_wallet: {
        Args: never
        Returns: Json
      }
      heartbeat: {
        Args: {
          p_page: string
          p_visible?: boolean
        }
        Returns: undefined
      }
      is_admin: {
        Args: never
        Returns: boolean
      }
      is_superadmin: {
        Args: never
        Returns: boolean
      }
      mark_all_notifications_read: {
        Args: never
        Returns: number
      }
      record_login: {
        Args: never
        Returns: undefined
      }
      reset_my_progress: {
        Args: never
        Returns: undefined
      }
      save_lesson_progress: {
        Args: {
          p_lesson_id: string
          p_percentage: number
        }
        Returns: undefined
      }
      start_course_exam: {
        Args: {
          p_course_id: string
        }
        Returns: Json
      }
      start_lesson: {
        Args: {
          p_lesson_id: string
        }
        Returns: Json
      }
      submit_contact_message: {
        Args: {
          p_subject: string
          p_email: string
          p_message: string
        }
        Returns: string
      }
      submit_course_exam: {
        Args: {
          p_attempt_id: string
          p_answers: Json
        }
        Returns: Json
      }
      submit_lab: {
        Args: {
          p_lab_id: string
          p_answer: string
        }
        Returns: Json
      }
      submit_lab_report: {
        Args: {
          p_lab_id: string
          p_note: string
          p_link?: string
        }
        Returns: undefined
      }
      submit_lab_task: {
        Args: {
          p_task_id: string
          p_answer: string
        }
        Returns: Json
      }
      submit_quiz: {
        Args: {
          p_quiz_id: string
          p_answers: Json
        }
        Returns: Json
      }
      unlock_course: {
        Args: {
          p_course_id: string
        }
        Returns: Json
      }
      unlock_lab: {
        Args: {
          p_lab_id: string
        }
        Returns: Json
      }
      verify_certificate: {
        Args: {
          p_code: string
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"]
export type Functions<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T]
