-- Spoken library of the mascot, generated by scripts/generate-voices.cjs (fr-FR-RemyMultilingualNeural).
-- Idempotent: only lines without audio are touched, so a human recording uploaded from the admin
-- "Mascotte et voix" page is never overwritten.

begin;

update public.mascot_lines as m
set audio_url = v.audio_url,
    voice_credit = 'Voix de synthèse neuronale (en attendant une voix humaine)'
from (values
  ('da285d27-f5dc-9470-288b-5239d3b4d73b', '/audio/mascot/da285d27-f5dc-9470-288b-5239d3b4d73b.mp3'),
  ('d87276bc-32ac-b61e-b061-c611b495e6e5', '/audio/mascot/d87276bc-32ac-b61e-b061-c611b495e6e5.mp3'),
  ('199c8897-2797-aff0-de28-71ca23bad1e1', '/audio/mascot/199c8897-2797-aff0-de28-71ca23bad1e1.mp3'),
  ('8a6d2c0b-c6af-5861-5ecb-a3e7b19d9457', '/audio/mascot/8a6d2c0b-c6af-5861-5ecb-a3e7b19d9457.mp3'),
  ('f81109a2-298b-3425-fd9a-8900724b9882', '/audio/mascot/f81109a2-298b-3425-fd9a-8900724b9882.mp3'),
  ('ff1f8c62-0c3e-8b51-17fb-1aa2e1e0e778', '/audio/mascot/ff1f8c62-0c3e-8b51-17fb-1aa2e1e0e778.mp3'),
  ('d20265aa-6f59-18a3-fa9c-7efd94751304', '/audio/mascot/d20265aa-6f59-18a3-fa9c-7efd94751304.mp3'),
  ('fdbce325-8d11-86ed-0c3f-4711db554265', '/audio/mascot/fdbce325-8d11-86ed-0c3f-4711db554265.mp3'),
  ('4e16390a-9efb-7a07-e19d-c240cab0e2e5', '/audio/mascot/4e16390a-9efb-7a07-e19d-c240cab0e2e5.mp3'),
  ('5ebb2053-f07e-6ea3-bef4-de8e81774703', '/audio/mascot/5ebb2053-f07e-6ea3-bef4-de8e81774703.mp3'),
  ('c92bb8fc-2df0-6989-781c-0b77358c1f0b', '/audio/mascot/c92bb8fc-2df0-6989-781c-0b77358c1f0b.mp3'),
  ('ef264b05-6e2e-1a7e-0c7d-a43b1bd16255', '/audio/mascot/ef264b05-6e2e-1a7e-0c7d-a43b1bd16255.mp3'),
  ('72a62b06-091f-21d3-b2d5-d8de43eaafe2', '/audio/mascot/72a62b06-091f-21d3-b2d5-d8de43eaafe2.mp3'),
  ('65b23789-9944-a131-fe16-66c717af20fa', '/audio/mascot/65b23789-9944-a131-fe16-66c717af20fa.mp3'),
  ('1c741aeb-ee97-8044-13ea-300e4588d990', '/audio/mascot/1c741aeb-ee97-8044-13ea-300e4588d990.mp3'),
  ('a8fd2f99-7338-2c44-a64e-efee18234cd9', '/audio/mascot/a8fd2f99-7338-2c44-a64e-efee18234cd9.mp3'),
  ('cb170032-3907-6241-cf05-f3a6ced1c2c5', '/audio/mascot/cb170032-3907-6241-cf05-f3a6ced1c2c5.mp3'),
  ('5a82bf3c-f089-d148-7238-39f21025814a', '/audio/mascot/5a82bf3c-f089-d148-7238-39f21025814a.mp3'),
  ('7782fcb9-e6b4-bfd0-b152-fbca1c58b83b', '/audio/mascot/7782fcb9-e6b4-bfd0-b152-fbca1c58b83b.mp3'),
  ('60a3491a-3849-6fb4-4ab7-710bc689838d', '/audio/mascot/60a3491a-3849-6fb4-4ab7-710bc689838d.mp3'),
  ('f7ca590c-213a-a310-4c5c-b43ab4568a82', '/audio/mascot/f7ca590c-213a-a310-4c5c-b43ab4568a82.mp3'),
  ('77509e8f-4f43-9818-e577-3a9ff2771018', '/audio/mascot/77509e8f-4f43-9818-e577-3a9ff2771018.mp3'),
  ('df374134-0736-2213-df0c-1178db413ca5', '/audio/mascot/df374134-0736-2213-df0c-1178db413ca5.mp3'),
  ('e282253a-f4a3-9fea-3a65-ec50330cb473', '/audio/mascot/e282253a-f4a3-9fea-3a65-ec50330cb473.mp3'),
  ('463bd6b8-2caf-cfab-21d0-b8d528ce2889', '/audio/mascot/463bd6b8-2caf-cfab-21d0-b8d528ce2889.mp3'),
  ('1ed50ce2-fb13-a77e-4713-1a5b3edd1458', '/audio/mascot/1ed50ce2-fb13-a77e-4713-1a5b3edd1458.mp3'),
  ('6fd7b129-3f65-3b43-f76e-1dffb8b3add4', '/audio/mascot/6fd7b129-3f65-3b43-f76e-1dffb8b3add4.mp3'),
  ('c141e802-ba05-10df-5c4c-e2fcd9e97d18', '/audio/mascot/c141e802-ba05-10df-5c4c-e2fcd9e97d18.mp3'),
  ('31c4b118-21b2-c0ba-c32a-49c0db3e1470', '/audio/mascot/31c4b118-21b2-c0ba-c32a-49c0db3e1470.mp3'),
  ('179f965c-0df7-6c74-4565-18949dfb36ad', '/audio/mascot/179f965c-0df7-6c74-4565-18949dfb36ad.mp3')
) as v (id, audio_url)
where m.id = v.id::uuid and m.audio_url is null;

commit;
