/**
 * Generates the spoken library of the mascot: one mp3 per `mascot_lines` row of the seed files plus the
 * "Pingo se présente" clip, and the idempotent SQL that attaches them.
 *
 *   npm i --no-save msedge-tts
 *   node scripts/generate-voices.cjs            # only missing files
 *   node scripts/generate-voices.cjs --force    # regenerate everything
 *
 * The voice is a neural synthesis, credited as such in the database. It is a stand-in that staff can replace
 * line by line with a human recording from the admin "Mascotte et voix" page; the SQL never overwrites a line
 * that already has audio.
 */
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "public", "audio");
const SEEDS = ["02_reseaux_path.sql", "03_soc_path.sql"].map((name) => path.join(ROOT, "supabase", "seed", name));
const SQL_FILE = path.join(ROOT, "supabase", "seed", "04_mascot_voices.sql");
const VOICE = "fr-FR-RemyMultilingualNeural";
const CREDIT = "Voix de synthèse neuronale (en attendant une voix humaine)";
const force = process.argv.includes("--force");

/** Pace and pitch follow the mood of the line, kept small so the voice stays natural. */
const PROSODY = {
  celebration: { rate: "+8%", pitch: "+4Hz" },
  proud: { rate: "+3%", pitch: "+2Hz" },
  happy: { rate: "+5%", pitch: "+3Hz" },
  surprised: { rate: "+6%", pitch: "+5Hz" },
  encouraging: { rate: "+0%", pitch: "+1Hz" },
  mission: { rate: "+2%", pitch: "-1Hz" },
  focused: { rate: "-3%", pitch: "-1Hz" },
  thinking: { rate: "-6%", pitch: "-2Hz" },
  disappointed: { rate: "-5%", pitch: "-3Hz" },
  expert: { rate: "-1%", pitch: "+0Hz" },
  explanation: { rate: "-3%", pitch: "+0Hz" },
};

function readLines() {
  const rows = [];
  const pattern = /\(\s*'([0-9a-f-]{36})',\s*'([a-z_]+)',\s*'([a-z]+)',\s*'((?:[^']|'')*)',\s*\d+,\s*\d+\s*\)/g;
  for (const file of SEEDS) {
    const sql = fs.readFileSync(file, "utf8");
    const start = sql.indexOf("insert into public.mascot_lines");
    if (start < 0) continue;
    const block = sql.slice(start, sql.indexOf("on conflict", start));
    for (const match of block.matchAll(pattern)) {
      rows.push({ id: match[1], event: match[2], expression: match[3], text: match[4].replace(/''/g, "'") });
    }
  }
  return rows;
}

async function synthesize(MsEdgeTTS, format, text, prosody, file) {
  const tts = new MsEdgeTTS();
  await tts.setMetadata(VOICE, format);
  const { audioStream } = tts.toStream(text, prosody);
  const chunks = [];
  await new Promise((resolve, reject) => {
    audioStream.on("data", (chunk) => chunks.push(chunk));
    audioStream.on("close", resolve);
    audioStream.on("error", reject);
  });
  tts.close();
  const bytes = Buffer.concat(chunks);
  if (bytes.length < 2000) throw new Error(`audio vide pour ${path.basename(file)}`);
  fs.writeFileSync(file, bytes);
  return bytes.length;
}

async function withRetry(task, attempts = 3) {
  let last;
  for (let i = 0; i < attempts; i += 1) {
    try { return await task(); } catch (error) { last = error; await new Promise((r) => setTimeout(r, 800 * (i + 1))); }
  }
  throw last;
}

async function main() {
  const { MsEdgeTTS, OUTPUT_FORMAT } = require("msedge-tts");
  const format = OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3;
  fs.mkdirSync(path.join(OUT, "mascot"), { recursive: true });

  const lines = readLines();
  if (lines.length === 0) throw new Error("aucune réplique trouvée dans les seeds");
  const intro = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "pingo-intro.json"), "utf8"));

  const jobs = [
    { file: path.join(OUT, "pingo-intro.mp3"), text: intro.text, prosody: { rate: "+2%", pitch: "+2Hz" } },
    ...lines.map((line) => ({
      file: path.join(OUT, "mascot", `${line.id}.mp3`),
      text: line.text,
      prosody: PROSODY[line.expression] ?? {},
    })),
  ];

  let made = 0;
  for (const job of jobs) {
    if (!force && fs.existsSync(job.file) && fs.statSync(job.file).size > 2000) continue;
    const size = await withRetry(() => synthesize(MsEdgeTTS, format, job.text, job.prosody, job.file));
    made += 1;
    console.log(`  ${path.relative(ROOT, job.file)}  ${(size / 1024).toFixed(1)} KB`);
  }

  const values = lines.map((line) => `  ('${line.id}', '/audio/mascot/${line.id}.mp3')`).join(",\n");
  const sql = `-- Spoken library of the mascot, generated by scripts/generate-voices.cjs (${VOICE}).
-- Idempotent: only lines without audio are touched, so a human recording uploaded from the admin
-- "Mascotte et voix" page is never overwritten.

begin;

update public.mascot_lines as m
set audio_url = v.audio_url,
    voice_credit = '${CREDIT}'
from (values
${values}
) as v (id, audio_url)
where m.id = v.id::uuid and m.audio_url is null;

commit;
`;
  fs.writeFileSync(SQL_FILE, sql, "utf8");
  console.log(`${made} fichier(s) générés, ${lines.length} répliques liées dans ${path.relative(ROOT, SQL_FILE)}`);
  process.exit(0);
}

main().catch((error) => { console.error(error); process.exit(1); });
