-- Generated by scripts/generate-content-seed.cjs from data/*.ts. Do not edit by hand.
-- Scoring catalogue: XP rewards, quiz answer keys and challenge flags stay server-side.

insert into private.content_lessons (id, course_id, title, xp_reward, source) values
  ('l-c1-1', 'c1', 'Qu''est-ce que la cybersécurité ?', 40, 'catalog'),
  ('l-c1-2', 'c1', 'Les types de menaces informatiques', 45, 'catalog'),
  ('l-c1-3', 'c1', 'Les acteurs de la cybersécurité', 40, 'catalog'),
  ('l1', 'c2', 'Comprendre le fonctionnement du DNS', 50, 'catalog'),
  ('l2', 'c2', 'Les ports et protocoles réseau', 60, 'catalog'),
  ('l-c2-3', 'c2', 'Le modèle OSI en pratique', 55, 'catalog'),
  ('l-c3-1', 'c3', 'Naviguer dans le système de fichiers Linux', 55, 'catalog'),
  ('l-c3-2', 'c3', 'Permissions et gestion des utilisateurs', 65, 'catalog'),
  ('web-https', 'c4', 'HTTPS : ce que le cadenas protège vraiment', 50, 'catalog'),
  ('web-comptes', 'c4', 'Protéger ses comptes avec un gestionnaire et la MFA', 50, 'catalog'),
  ('web-phishing', 'c4', 'Déjouer un message de phishing', 50, 'catalog'),
  ('pentest-cadre', 'c5', 'Autorisation et périmètre d’un audit', 50, 'catalog'),
  ('pentest-methode', 'c5', 'Une méthode de test responsable', 50, 'catalog'),
  ('pentest-rapport', 'c5', 'Rédiger une recommandation utile', 50, 'catalog'),
  ('logs-lire', 'c6', 'Lire un événement dans un journal', 50, 'catalog'),
  ('logs-correler', 'c6', 'Relier les événements sans conclure trop vite', 50, 'catalog'),
  ('logs-triage', 'c6', 'Qualifier une alerte et documenter la suite', 50, 'catalog')
on conflict (id) do update set course_id = excluded.course_id, title = excluded.title, xp_reward = excluded.xp_reward, source = 'catalog';

insert into private.content_quizzes (id, lesson_id, title, xp_reward, correct_answers, source) values
  ('q1', 'l1', 'Quiz — Le fonctionnement du DNS', 80, array['Traduire les noms de domaine en adresses IP', 'Vrai', 'dig']::text[], 'catalog'),
  ('quiz-web-https', 'web-https', 'Quiz — HTTPS : ce que le cadenas protège vraiment', 60, array['Le contenu de la connexion', 'Oui']::text[], 'catalog'),
  ('quiz-web-comptes', 'web-comptes', 'Quiz — Protéger ses comptes avec un gestionnaire et la MFA', 60, array['Un mot de passe unique par service', 'Dans un endroit sûr distinct de l’appareil principal']::text[], 'catalog'),
  ('quiz-web-phishing', 'web-phishing', 'Quiz — Déjouer un message de phishing', 60, array['Utiliser un canal officiel indépendant', 'Gardé secret']::text[], 'catalog'),
  ('quiz-pentest-cadre', 'pentest-cadre', 'Quiz — Autorisation et périmètre d’un audit', 60, array['Une autorisation explicite et un périmètre', 'Clarifier le périmètre avant toute action']::text[], 'catalog'),
  ('quiz-pentest-methode', 'pentest-methode', 'Quiz — Une méthode de test responsable', 60, array['La moins intrusive qui démontre le problème', 'Arrêter et prévenir le contact prévu']::text[], 'catalog'),
  ('quiz-pentest-rapport', 'pentest-rapport', 'Quiz — Rédiger une recommandation utile', 60, array['Une correction concrète et un contexte', 'Vérifier la correction']::text[], 'catalog'),
  ('quiz-logs-lire', 'logs-lire', 'Quiz — Lire un événement dans un journal', 60, array['L’horodatage', 'Non, il faut du contexte']::text[], 'catalog'),
  ('quiz-logs-correler', 'logs-correler', 'Quiz — Relier les événements sans conclure trop vite', 60, array['Pour confirmer ou nuancer une hypothèse', 'Pas nécessairement une même personne']::text[], 'catalog'),
  ('quiz-logs-triage', 'logs-triage', 'Quiz — Qualifier une alerte et documenter la suite', 60, array['Faits et hypothèses', 'Suivre la procédure et les autorisations prévues']::text[], 'catalog'),
  ('review-fundamentaux', 'l-c1-3', 'Les bons réflexes fondamentaux', 60, array['Limiter l’accès aux personnes autorisées', 'La défense et la détection']::text[], 'catalog'),
  ('review-linux', 'l-c3-2', 'Les permissions Linux', 60, array['Lire', 'Appliquer le moindre privilège']::text[], 'catalog')
on conflict (id) do update set lesson_id = excluded.lesson_id, title = excluded.title, xp_reward = excluded.xp_reward, correct_answers = excluded.correct_answers, source = 'catalog';

insert into private.content_challenges (id, title, xp_reward, expected_answer, source) values
  ('ch1', 'Découvrir les ports réseau', 100, 'ssh', 'catalog'),
  ('ch2', 'Premiers pas en OSINT', 80, 'libreoffice', 'catalog'),
  ('ch3', 'Comprendre les permissions Linux', 90, 'chmod 644 config.env', 'catalog'),
  ('ch4', 'Casser un chiffrement de César', 70, 'Code Salutational', 'catalog'),
  ('ch5', 'Repérer une injection SQL', 120, ''' OR ''1''=''1', 'catalog'),
  ('ch6', 'Auditer l''hygiène des mots de passe', 60, 'motdepasse', 'catalog')
on conflict (id) do update set title = excluded.title, xp_reward = excluded.xp_reward, expected_answer = excluded.expected_answer, source = 'catalog';
